### ISSUE TITLE
consensus needs to persist state for crash tolerance

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#1000]
This is to address #351.  Consensus state should not be part of the blockchain, but stored in a non-replicated part of the system database.

**Comment by binhn** [comment]
@corecode could you outline the work needed, especially what are we persisting.  Perhaps we should speed up the system chaincode so that we may leverage?

**Comment by corecode** [comment]
Persisting the ephemeral consensus state needs to happen outside consensus and therefore cannot go through a system chaincode.

The kind of state persistence we need could easily be served via some keys in rocksdb which are not managed via any (system) chaincodes.

**Comment by corecode** [comment]
Attack plan:
- persist all incoming messages, replay them on restart.
- persist lastexec seqno in the transaction writebatch, restore on restart.

**Comment by corecode** [comment]
Alternatively, persist processed state: `reqstore, pset*, qset*, certStore.commit, lastExec`
Where `pset*`/`qset*` are updated sets based on messages received and sent.  `seqNo` can be restored from the persisted state.  Unclear about `view`.

**Comment by corecode** [comment]
#1325 has been merged.
