### ISSUE TITLE
CONTRIBUTING.md missing

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1008]
We should move the contributing section of the README.md to CONTRIBUTING.md and elaborate with better help for prospective contributors.

**Comment by lehors** [comment]
For reference I suggest looking at the Node.js documentation which is very good: [Get Involved](https://nodejs.org/en/get-involved/), [Contribute](https://nodejs.org/en/get-involved/contribute/), and [Development](https://nodejs.org/en/get-involved/development/)

**Comment by christo4ferris** [comment]
agree, [Docker's](https://github.com/docker/docker/blob/master/CONTRIBUTING.md) is also quite comprehensive. I have just extracted from the [README.md](README.md) for starters. PR incoming...

**Comment by binhn** [comment]
good idea;  thanks !

**Comment by christo4ferris** [comment]
closed by #1019
