### ISSUE TITLE
Write paper on deploying hyperledger

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#1024]
Allen Bailey and Josh Horton to write one-page "whitepaper" for the April 30 weekend "hackathon" with business partners and competitors.

The whitepaper will describe in detail how to deploy hyperledger on Azure.

A second goal is for the whitepaper to describe how to deploy hyperledger on ANY platform - any "bare metal softlayer" deployment of hyperledger. But the immediate goal for the paper and confirmation / testing is to provide the deploy to Azure procedure for the hackathon.

**Comment by hannibalhuang** [comment]
Hi @joshhus , I'm interested in the "any platform" concept, would be glad to participate in the discussion

**Comment by stan101010** [comment]
Hi,  I'm very interested in the "any platform" concept too.  VM is great for development, it would be nice to have a 'anywhere' client built in GO.  Can anyone help me find this information on setting up independent nodes that talk to each other?  The "Setting up a network" example does it within the Vagrant machine.

**Comment by joequant** [comment]
Yes.  Look at
https://github.com/joequant/hyperledger
These are scripts that are derived from scripts written by yeasy.

./startnet.sh should download the docker images from docker hub and spin them off.

**Comment by stan101010** [comment]
Thank you very much!  This looks life what I need.

**Comment by yeasy** [comment]
Thanks joequant.
@stanacton 
I highly recommend u to have a look at [https://github.com/yeasy/docker-compose-files#hyperledger](https://github.com/yeasy/docker-compose-files#hyperledger) and
[https://github.com/yeasy/docker-hyperledger-peer](https://github.com/yeasy/docker-hyperledger-peer).

Which will help you quickly boot up a hyperledger cluster without any local configuration and vagrant layer.

**Comment by joequant** [comment]
Yes.  I'll take a look at using docker compose.

**Comment by wangbin767** [comment]
I am interested in whether this paper finished?

**Comment by joshhus** [comment]
Investigating, this was dependent on some test results, TBA.

**Comment by christo4ferris** [comment]
can we please open this in Jira? Thanks.

**Comment by joshhus** [comment]
Migrated to Jira: 
https://jira.hyperledger.org/browse/FAB-242?jql=project%20%3D%20FAB%20AND%20resolution%20%3D%20Unresolved%20AND%20creator%20in%20(currentUser())%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC
