### ISSUE TITLE
Peer executable not respecting consensus setting in core.yaml

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1028]
Description:

Setting up the core.yaml for obcpbft (as per directions in core.yaml) results in Peer using Noops

Steps to repro:
1.  Modify core.yaml to use obcpbft
2.  Build image
3.  Bring up 4 peers

Results:

VPs recognize and load obcpbft, then shortly thereafter load Noops.

Expected Results:

Peer should run consensus plugin entered in core.yaml, or if there's a new name for the plugin (corepbft?) then the comments in the core.yaml should reflect that.
[no obcpbft.txt](https://github.com/hyperledger/fabric/files/210651/no.obcpbft.txt)

**Comment by RicHernandez2** [comment]
Nope, I called it wrong, I was experimenting with env variables and left in a bad call:

`docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true **-e CORE_PEER_VALDATOR_CONSENSUS=pbft** -p 5000:5000 hyperledger-peer ./peer peer`

**Comment by tuand27613** [comment]
@RicHernandez2  ! giving me heart attack on friday afternoon ;-)

**Comment by RicHernandez2** [comment]
Take some beta blockers before you read this:

I took that whole section out of the commandline, I go to start the nodes, and they're doing the exact same thing!  D:

```
NO SECURITY


docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -p 5000:5000 hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp1 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp3 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303 hyperledger-peer ./peer peer

```

**Comment by RicHernandez2** [comment]
Here's the logs, a little too convenient that I would make this mistake and accidentally come across a real bug by accident, I'm going to blow away my current directories and do a new git clone... in the meantime, solid repro.

[a correct cli - still noops.txt](https://github.com/hyperledger/fabric/files/210735/a.correct.cli.-.still.noops.txt)

**Comment by RicHernandez2** [comment]
Ah!  It's been changed to just "PBFT" for the core.yaml, verified that this works.

Thanks, Tuan!
