### ISSUE TITLE
Reference Architecture image still contains references to OBC

### ISSUE THREAD

**Issue by nickgaski** [hyperledger-archives/fabric#1029]
images/refarch.png - In Section 2 of Prot Spec, still contains two instances of OBC.  Need design folks to edit.  @joshhus - can you track down one of them to edit this image?

**Comment by joshhus** [comment]
yup ... done ... but I don't have "push" access to that dir. 
![refarch](https://cloud.githubusercontent.com/assets/16542757/14394564/de205d10-fd9a-11e5-903e-fc5f86d686dd.png)

**Comment by srderson** [comment]
@joshhus You need to submit a PR as described in the GitHub flow at https://github.com/hyperledger/fabric/blob/master/CONTRIBUTING.md

**Comment by joshhus** [comment]
There are two usages of this graphic. Replacing the 2nd usage with the fixed one now. @nickgaski

**Comment by nickgaski** [comment]
Fixed via PR #1051
