### ISSUE TITLE
Documentation issues after move from OBC to hyperledger/fabric

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1037]
1. Section 3.1.2.1 of docs/protocol-spec.md is no longer valid. This proto appears have been completely redefined. To be frank I think it is probably too early in the project to be documenting fast-moving data structure definitions in a standalone protocol specification document, although eventually this will be required and changes should be subject to strict controls.
2. I don't see that the old 'obc-docs' issues have been moved to hyperledger/fabric. (Selfishly, I see that mine wasn't moved!)

**Comment by muralisrini** [comment]
@bcbrock : correct, I think docs are being worked upon. Hopefully fixed soon.

**Comment by joshhus** [comment]
thanks @bcbrock

**Comment by christo4ferris** [comment]
closing as I believe this to be fixed by now

**Comment by bcbrock** [comment]
Sorry @christo4ferris - Not only is the protocol-spec.md still wrong, but so is CoreAPI.md at line 606.
