### ISSUE TITLE
asset_management test case hasn't been moved to new chaincode interface

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#1038]

**Comment by muralisrini** [comment]
fabric/examples/chaincode/go/asset_management/asset_management.go should implement Init and Invoke methods
- move "init" code from Run into Init method
- rename Run to Invoke

**Comment by muralisrini** [comment]
will also create an issue to move asset_management from examples/... to another directory (probably chaincode) so we could have caught this sooner.

**Comment by muralisrini** [comment]
issue #1039 created for moving asset_management_test.go to chaincode/ folder

**Comment by srderson** [comment]
Fixed via PR #1050
