### ISSUE TITLE
go get shim fails - unrecognized import path "google/protobuf"

### ISSUE THREAD

**Issue by smartheartz** [hyperledger-archives/fabric#1041]
go get shim, using 

`go get github.com/hyperledger/fabric/core/chaincode/shim`

fails with the following error

`imports google/protobuf: unrecognized import path "google/protobuf"`

![image](https://cloud.githubusercontent.com/assets/18358012/14408020/636533cc-ff14-11e5-85d6-ca27396cecf8.png)

**Comment by muralisrini** [comment]
@smartheartz : seemed to work for me

![image](https://cloud.githubusercontent.com/assets/14361488/14410587/0841185c-ff01-11e5-87a2-6cff8124e461.png)

I wonder what the difference is ?

My go version : 

![image](https://cloud.githubusercontent.com/assets/14361488/14410616/a4705dd2-ff01-11e5-9d9d-c64a1da83c9d.png)

I tried the same from within the vagrant env and that worked too : 

![image](https://cloud.githubusercontent.com/assets/14361488/14410643/16b31ed4-ff02-11e5-8531-50d4e2f2122a.png)

Can you try under the vagrant dev env please ?

**Comment by smartheartz** [comment]
Thanks @muralisrini .  apt-get install go installed version 1.3 on my raspberry pi.  I have now installed version 1.6 and go get shim working fine.

I am not familiar with Vagrant, so not in a position to test using Vagrant.

**Comment by muralisrini** [comment]
Good to know @smartheartz . Thank you... interesting you should mention raspberry pi. If ok to share, would love to know your experiments.

**Comment by smartheartz** [comment]
Hi @muralisrini, yes happy to share.  I am in "teach myself mode" at the moment.  The bank I work for in Australia is running a Blockchain hackathon in late May.  The platform will be IBM Blue Mix.

So far, through trial and error, I have created a Blockchain service in Blue Mix; used Postman.com to learn about the REST APIs.  I even managed to deploy a contract (example02 from fabric/examples/chaincode/go/).  Using the Pi, I have created curl and python programs to access some of the the REST APIs.

My next step is to be able to compile (on the Pi) the the example02 code, then edit it to change the functionality slightly, and then compile my version.

Then I need to figure out how to deploy my version of the chaincode to my Blockchain service.  If you could point me to some documentation on how to deploy the compiled code to the Blockchain, I would be very grateful.  I anticipate using Postman.com first, then a python program on the Pi to do the deploy.

**Comment by muralisrini** [comment]
@smartheartz : let me make sure I understand first.

Currently you have REST API access from PI to Blockchain service on Bluemix. 

You want to download just the shim on to the PI and build your chaincode executable directly there. Then you want to deploy the executable directly instead of having hyperledger fabric build the executable and deploy.

Did I get that right ? Or not ? :-)

Adding @mrshah-at-ibm for Blockchain service in Bluemix.

**Comment by smartheartz** [comment]
I think so @muralisrini @mrshah-at-ibm .  I am still learning the terminology and the capabilities.

> > instead of having hyperledger fabric build the executable and deploy.

OK, I didn't know that the fabric could build the executable.  My assumption was that I had to build it with the go compiler (which I have just successfully done on the Pi - I have an 11 MByte file).  With a file that size, it would be much better to send the source code to the blockchain.

I used this to deploy example02.

{
    "type": "GOLANG",
    "chaincodeID":{
        "path":"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
    },
    "ctorMsg": {
        "function":"init",
        "args":["a", "100", "b", "200"]
      },
      "secureContext": "user_type1_340394d43c"
  }

The reason I thought I had to build the executable is because the file name above is chaincode_example02, not chaincode_example02.go.

I don't know what to replace the "path" with to deploy either the source or the executable from the Pi.  

Do I need to put one of the files on github and deploy from there?

**Comment by muralisrini** [comment]
@smartheartz :  yes, you can put one of the files on github and deploy it from there.

For example, "-p https://github.com/smartheartz/pichaincode" , with the chaincode  https://github.com/smartheartz/pichaincode/chaincode_exampl02.go in it.

The fabric would pull the code, build and deploy it. Currently, the URL should be accessible publicly without password.

**Comment by smartheartz** [comment]
Thanks @muralisrini : could you please clarify for me - what command do I use for "-p https://github.com/smartheartz/pichaincode"

**Comment by smartheartz** [comment]
Hi @muralisrini , you can ignore my last question - I think I have worked out that it is 

./[obc-]peer chaincode deploy -p 

I have managed to build the peer command on a Ubuntu server, start a Blockchain in dev mode; and deploy, invoke, and query the example-02 code, which was also stored on my Ubuntu server.

Now I can try writing my on chaincode a testing it on my dev Blockchain.

Thanks for you help.

**Comment by muralisrini** [comment]
@smartheartz : thanks for checking it out.
