### ISSUE TITLE
Chain deployment failing with tar error - possibly compression issue

### ISSUE THREAD

**Issue by joequant** [hyperledger-archives/fabric#1045]
I am getting chaincode deployment errors

ESC[36m21:12:14.554 [container] lockContainer -> DEBU 922ESC[0m got container (dev-vp1-5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5) lock
21:12:14.554 [container] newDockerClient -> INFO 923ESC[0m Creating VM with endpoint: http://172.17.0.1:4243
ESC[31m21:12:14.824 [container] build -> ERRO 924ESC[0m Error building Peer container: API error (500): Untar re-exec error: archive/tar: invalid tar header: output: 
ESC[36m21:12:14.824 [container] unlockContainer -> DEBU 925ESC[0m container lock deleted(dev-vp1-5844bc142dcc9e788785e026e22c855957b2c754c912702c58d997dedbc9a042f05d152f6db0fbd7810d95c1b880c210566c9de3093aae0ab76ad2d90e9cfaa5)

This may have something to do with docker handling of compressed tar files
https://github.com/docker/docker/issues/20296

However reverting to docker 1.9.1 does not seem to help.  This may be a docker 1.10 issue since it seems to have started recently.

**Comment by joequant** [comment]
It has something to do with commit  
https://github.com/openblockchain/obc-peer/commit/3362078d75dff4a50efee8c669c8fda7e9b6e596

When I revert the commit it works.  Methinks that there is some sort of race condition.

**Comment by joequant** [comment]
Could the problem be a race condition?  When the build image and the deployment are in the same procedure you know that one happens before the other.  Is there any possibility that the system will attempt to create a container before the image gets built?

**Comment by muralisrini** [comment]
@joequant : that commit actually makes re-launch stricter by removing the container and recreating one if exists. Basically should be cleaner on re-start. So I don't know why this change would cause it to fail.

Can you provide debug logs from the peer ...any race condition would hopefully be indicated in the logs.

**Comment by joequant** [comment]
It looks like it isn't that particular patch since the system is failing
again once I've done the updates.  It does seem to be some sort of timing
issue.  Let me see if I can reproduce running straight docker.

**Comment by joequant** [comment]
Closing since this could be the result of bad memory.

**Comment by joequant** [comment]
Closing this issue.  It appears that I had a machine with bad memory, and
that might be causing failures on the virtual machine.  I'm now running the
system with docker directly, and it seems to work.
