### ISSUE TITLE
Refactor setup scripts to allow for native development environments

### ISSUE THREAD

**Issue by joequant** [hyperledger-archives/fabric#1047]
The devenv setup script can be refactored so that it can be used to create a native development environment rather than requiring a Ubuntu based VM.  Ubuntu is great, but in production most users would be interested in being able to layer the fabric on top of a native system.

**Comment by christo4ferris** [comment]
@joequant, thanks for the suggestion. The documentation has undergone serious improvement includes info on how to set up a network or development environment on a variety of platforms, including natively on windows, mac, linux and Z. Closing this unless you specifically are interested in something not currently supported.
