### ISSUE TITLE
lots of permission errors reported on Unit Tests

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#1048]
Hi Dears,

I followed guide below
[3.1 Unit Tests](https://github.com/hyperledger/fabric#3-test)
To run all unit tests, in one window, run ./peer peer. In a second window

`cd $GOPATH/src/github.com/hyperledger/fabric
go test -timeout=20m $(go list github.com/hyperledger/fabric/... | grep -v /vendor/ | grep -v /examples/)`

I run the Unit test command "go test....." in **vagrant**, it reported lot of permission errors.
Could you kindly help how to fix?

Here are examples of two screen shots, such permission errors are lining a lot.
<img width="821" alt="2016-04-11 2 40 02" src="https://cloud.githubusercontent.com/assets/7720620/14418802/d6329df6-fff3-11e5-8636-41f7e6056068.png">
<img width="823" alt="2016-04-11 2 40 26" src="https://cloud.githubusercontent.com/assets/7720620/14418805/db43b4f6-fff3-11e5-9294-df4da7668410.png">

**Comment by zhuang-weiming** [comment]
I test it by root, it is running OK.

Can I say it would run by root, it would not run by vagrant?
<img width="882" alt="2016-04-11 3 56 00" src="https://cloud.githubusercontent.com/assets/7720620/14420304/eac15550-fffd-11e5-9e08-9aed6cc73232.png">

**Comment by corecode** [comment]
I have a fix for this, 81b44bbfc2eecdae0d9bdf37818889dc288919f7

**Comment by srderson** [comment]
My guess is that something may have failed during the `vagrant up` process as it should have executed the following line. https://github.com/hyperledger/fabric/blob/master/devenv/setup.sh#L129

You could try `vagrant destroy` and `vagrant up` again to see if it reports any errors.

**Comment by zhuang-weiming** [comment]
@corecode @srderson , Thank you for your response. 
I tried vagrant destroy and vagrant up twice, as @srderson  guess, there are lots of red log in vagrant up.

This is the end of failed log:
<img width="802" alt="2016-04-12 12 55 23" src="https://cloud.githubusercontent.com/assets/7720620/14450150/fb184b56-00ad-11e6-8f6e-edb3c46e5b27.png">

This is the start of log about setup.sh:
<img width="802" alt="2016-04-12 12 49 29" src="https://cloud.githubusercontent.com/assets/7720620/14450088/44734c02-00ad-11e6-9a28-2d67c57e63e2.png">

Can I know which step is wrong? I need to run setup.sh manually from which step?

**Comment by zhuang-weiming** [comment]
When I run setup.sh manually step by step, I appended two 'chown' as below, it seems worked OK.

```
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ sudo chown -R vagrant:vagrant /opt/gopath/
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ CGO_CFLAGS=" " CGO_LDFLAGS="-lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy" go install

vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ sudo chown -R vagrant:vagrant /opt/go/
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ go install -a github.com/golang/protobuf/protoc-gen-go
```

Should we add chown before this two steps?

Another question, 

```
#install golang deps
./installGolang.sh
package golang.org/x/tools/go/gcimporter15: unrecognized import path "golang.org/x/tools/go/gcimporter15" (https fetch: Get https://golang.org/x/tools/go/gcimporter15?go-get=1: dial tcp 216.58.216.209:443: i/o timeout)

vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric/devenv$ go get golang.org/x/tools/cmd/goimports
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports" (https fetch: Get https://golang.org/x/tools/cmd/goimports?go-get=1: dial tcp 216.58.216.209:443: i/o timeout)
```

Can I make it as below, please kindly help me ?

```
mkdir -p $GOPATH/src/golang.org/x/tools
git clone https://go.googlesource.com/tools $GOPATH/src/golang.org/x/tools
go build golang.org/x/tools/cmd/goimports
```

**Comment by srderson** [comment]
These packages are not required to run Fabric.

```
github.com/golang/lint/golint
golang.org/x/tools/cmd/goimports
```

For now, you may want to comment out the lines locally.
https://github.com/hyperledger/fabric/blob/master/devenv/installGolang.sh#L52
https://github.com/hyperledger/fabric/blob/master/devenv/installGolang.sh#L53

These packages seem to be blocked on some networks. We've seen it before. https://github.com/hyperledger/fabric/issues/901

The fix here is either to bake these packages into the base image or the ability for setup to continue even if lines 52 and 53 fail.

**Comment by zhuang-weiming** [comment]
@srderson Thank you!

The dev env setup was done with your help.

**Comment by srderson** [comment]
Great, glad the issue is resolved
