### ISSUE TITLE
OBCCA setup - docs are inconsistent

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1060]
https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/obcca-setup.md#build-and-run

and

https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md#security-setup-optional

Are in disagreement about the name of the CA server, and one seems to be calling it incorrectly (needs a "./" before server name)

**Comment by tuand27613** [comment]
@adecaro  @joshhus

**Comment by nickgaski** [comment]
Is the OBCCA-Setup doc the culprit here?  

Please confirm if this is correct:  
The CA can be built with the following command from the membersrvc directory
[go build -o membersrvc]
To run the CA
[./membersrvc]

@adecaro @jeffgarratt @joshhus

**Comment by adecaro** [comment]
@nickgaski, it is correct.

Actually, @diegomasini is in charge for the membership service. He can take care of the discrepancy in the documents.

**Comment by andresgaragiola** [comment]
@binhn after pull request #1149 this issue should be closed.

**Comment by RicHernandez2** [comment]
Checked docs, issue resolved.
