### ISSUE TITLE
<!-- HTML comments displaying in protocol spec

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#1062]
Hi Security team, 

Could you please check the output of your Security doc in the Protocol Spec here: https://github.com/hyperledger/fabric/blob/master/docs/protocol-spec.md

There are a number of what look like HTML comments  that are displaying externally to the readers / in the browser. 

In particular 4.3.1 on ... you could search the browser window for <!--

Though .md supports HTML, I believe the requirement is that any HTML tags have to start and end on their own line in an .md doc. You could try that. No guarantee 
that .md supports HTML comments though - there is likely an .md-specific comment tag, if that doesn't work.

Please check and/or request our assistance (ID / me and Nick) as needed, thanks!

Thanks,

Josh

**Comment by genggjh** [comment]
Looks like this is github specify defect. I can not reproduce this issue in my sublime markdown preview.

**Comment by christo4ferris** [comment]
per [SO](http://bit.ly/20xYTpi), the most universal "comment" syntax is to abuse the link label
eg. (on separate line)

[comment]: <> (This is a comment, it will not be included)

**Comment by joshhus** [comment]
Fixed by Chris, thanks. HTML has to be on its own line in .md.
