### ISSUE TITLE
Chaincode install path is hard coded

### ISSUE THREAD

**Issue by harrijk** [hyperledger-archives/fabric#1074]
The default chaincode `installpath` value is set to `/opt/gopath/bin` in the core.yaml file.  If one decides to change the `installpath`parameter to something other than the default value, the following error occurs when deploying chaincode:

`12:14:29.626 [container] start -> ERRO 04b start-could not start container API error (500): Cannot start container dev-jdoe-3a46d4d629d8c1f931bb29c1b52ca9698cba5d75487771882068975b15f0440fb73bab315f5dad72eaaaeaead5ea6a211ac013cfb8d55c64547d348d51504e7d: [8] System error: exec: /opt/gopath/bin/3a46d4d629d8c1f931bb29c1b52ca9698cba5d75487771882068975b15f0440fb73bab315f5dad72eaaaeaead5ea6a211ac013cfb8d55c64547d348d51504e7d: stat /opt/gopath/bin/3a46d4d629d8c1f931bb29c1b52ca9698cba5d75487771882068975b15f0440fb73bab315f5dad72eaaaeaead5ea6a211ac013cfb8d55c64547d348d51504e7d : no such file or directory`

When you change your default chaincode installpath within core.yaml, this also assumes that one has included the path within the Docker image used for chaincode operations.  When I built my base Docker image for chaincode use, I updated my PATH environment variable to include the chaincode installpath (/go/bin) set in my core.yaml file.

I took a look at the fabric core file `core/chaincode/chaincode_support.go` and noticed that on line 51 the constant `chaincodeInstallPathDefault` is set to `/opt/gopath/bin`.  Within the `NewChaincodeSupport` method on line 116 of chaincode_support.go, the `s.chaincodeInstallPath` is assigned the constant `chaincodeInstallPathDefault` (/opt/gopath/bin) rather than using the `installpath` value within the core.yaml file.

Just as a test, I went ahead and rebuilt the peer binary after updating  the `chaindeInstallPathDefault` constant in `chaincode_support.go` to match the `installpath` value used in my core.yaml file.  I then deployed chaincode and the error that I was experiencing previously did not occur.

Perhaps I'm missing something here... very possible. :-)

**Comment by srderson** [comment]
@muralisrini can you comment on this issue?

**Comment by muralisrini** [comment]
@harrijk : the installpath treatment is definitely incorrect. However I am not sure its the whole story. The chaincode is installed via "go install" which will put the chaincode in GOPATH in the image. By default this is /opt/gopath/bin. When you made it to work with the altered "installpath" did you also had to copy the chaincode binary in the image to /go/bin (in addition to _" ...I updated my PATH environment variable to include the chaincode installpath (/go/bin) set in my core.yaml file."_ ?)

In any case, given we don't expose setting GOPATH, I think we should just remove the "installpath" from core.yaml. As the fabric is fully managing the chaincode, I cannot think of a good reason why user may want it to run elsewhere. But perhaps there is one ?

**Comment by harrijk** [comment]
@muralisrini, since the `installpath` parameter is being ignored in core.yaml, the ultimate placement of the chaincode is made in `core/chaincode/chaincode_support.go` outlined in my original post for this issue.

**Comment by muralisrini** [comment]
@harrijk : Right, that change - if I understood correctly - will launch the container from /go/bin/3a46d4d629d8c1f931bb29c1b52ca9698cba5d75487771882068975b15f0440fb73bab315f5dad72eaaaeaead5ea6a211ac013cfb8d55c64547d348d51504e7d. If GOPATH is /opt/gopath/bin, I'd expect to find the exe under /opt/gopath/bin. Just wondering how the exe found its way into /go/bin. I could easily be missing something ...

**Comment by harrijk** [comment]
No worries.  If I didn't make a change to the `core/chaincode/chaincode_support.go` file on line 51 from `/opt/gopath/bin` to `/go/bin`, the chaincode exe would fail as my docker image listed in the chaincode: -> golang: -> Dockerfile parameter (FROM statement) of my core.yaml file does not contain a `/opt/gopath/bin` directory; it was setup with `/go/bin`.  Also, the GOPATH variable setup in that docker image is set to /go and not /opt/gopath/bin.

However, if I re-compile the peer exe after changing line 51 of `core/chaincode/chaincode_support.go` from `/opt/gopath/bin` to `/go/bin` then the chaincode exe runs without error.  

I hope this helps. 
Cheers.

**Comment by muralisrini** [comment]
Thanks. I think I see the problem... in my env GOPATH resolves to /opt/gopath in the image

![image](https://cloud.githubusercontent.com/assets/14361488/14564924/a6444cd8-02f6-11e6-8e11-e02e514e56b3.png)

And from a chaincode itself
![image](https://cloud.githubusercontent.com/assets/14361488/14565058/497cdd3e-02f7-11e6-8fb3-eaf2a873a490.png)

There were some changes to the paths recently when we moved to hyperledger. Wonder if you are on the latest ?

**Comment by harrijk** [comment]
Yeah, I switched over before I wrote up this issue.  Being curious, I was just wondering why I couldn't change the installpath without going through all of the above changes.  I have switched back to using /opt/gopath/bin as my install path in my Docker images.

**Comment by muralisrini** [comment]
Ok, that clears it up for me.

So given the fabric completely controls the generation of the exe and installation path exposing installpath does not make a lot of sense... would you agree ?

**Comment by harrijk** [comment]
I agree.

**Comment by yeasy** [comment]
hi, please take a look at #1103. Similar reason, but I guess we should allow people have the flexibility to control the installpath, as sometime they will have their own built image for testing or hacking.

So I think at least currently we should keep the installPath option in the core.yaml, while fix the code to let read the value before using the default one. Certainly we can add some comments to tell people the correct way to use it.

How do u think? Thanks!

**Comment by harrijk** [comment]
Hi.  I am open to keeping the installpath option as long as it is read in and used as opposed to its current state.

**Comment by muralisrini** [comment]
@yeasy : I applied your patch and modified installpath to "/go/bin". When I deployed, it failed with this error
03:37:38.782 [container] start -> ERRO 040 start-could not start container API error (500): Container command not found or does not exist.

This is as expected as the exe is placed in $GOPATH/bin (which is /opt/gopath/bin) in the image. So just making this change (and I see you agree on this) is not enough.

A better approach, in my opinion, would be to remove install path completely from the picture..ie, both in core.yaml AND in chaincode_support.go and have $GOPATH/bin in PATH . Basically make the code independent of install path. 

So this change works 
       //args = []string{chaincodeSupport.chaincodeInstallPath + cID.Name, fmt.Sprintf("-peer.address=%s", chaincodeSupport.peerAddress)}
       args = []string{cID.Name, fmt.Sprintf("-peer.address=%s", chaincodeSupport.peerAddress)}

The only dependency is on GOPATH/bin being in PATH (which it is in the default image).

Seems simple and clean... what do you think ?

**Comment by yeasy** [comment]
@murallsini IMHO, seems you need to update the GOPATH in your image?
InstallPath cannot be arbitrary, unless we put the full path to the chaincode exe.
As the exe should be started directly, it must be placed under the sys path, otherwise, it cannot be found.

**Comment by muralisrini** [comment]
@yeasy : correct. I found it it is in my path in my (default) image. The  point is, if you build your own image its easier to add GOPATH/bin to PATH in the image (in addition to the other changes you make there) than to have to change in the yaml too. But perhaps I'm missing something?

**Comment by yeasy** [comment]
@muralisrini Yes, I agree with u for image and golang experts it might be easier (Actually I do believe we should put GOPATH/bin on PATH anytime after setup golang). 
While we might keep the flexibility provided by the yaml way for customization usage. Think such scenario, we keep different version of chaincode, and want to testing... Then we can just change the installation path, instead of changing and rebuilding the image. The other consideration is for people who may be not be that familiar with golang setups.

**Comment by muralisrini** [comment]
@yeasy : 
_Think such scenario, we keep different version of chaincode, and want to testing... Then we can just change the installation path, instead of changing and rebuilding the image._

Note that you'll have to make sure to copy the chaincode to the right install path... While you are at it you might as well update PATH to point to the new folder in the image... and you won't have to make the additional change in the yaml.

I think removing the installpath is simple and will be enough 90% of the time. But I can see some benefit in calling it out explicitly (users don't want to launch  the wrong exe by mistake). If you feel strongly about having the installpath in the yaml, there's no harm in taking in your PR as is.

**Comment by yeasy** [comment]
@muralisrini, thanks for your reply, and let's try to make hyperledger more mature and easier for usage.

**Comment by muralisrini** [comment]
Can you add some doc to installpath in core.yaml... something like this

```
  # typically install path should not be modified. If modified, user must ensure the chaincode
  # executable is placed in the directory specifed by installpath in the image
  installpath: /opt/gopath/bin/
```

**Comment by yeasy** [comment]
@muralisrini Good idea, I will add it, thanks!

**Comment by harrijk** [comment]
@muralisrini, adding the comment to the core.yaml file still does not resolve this issue.  Even if someone was to change the installpath and update their docker images to reflect this new path, the code in core/chaincode/chaincode_support.go does not read in the core.yaml installpath value, and as a result all chaincode will be installed at the location specified supplied by chaincodeInstallPathDefault in core/chaincode/chaincode_support.go at line 51, which is currently set to /opt/gopath/bin.  Perhaps I'm missing something. :)

**Comment by muralisrini** [comment]
@harrijk : the comment goes with PR  https://github.com/hyperledger/fabric/pull/1103 ... when that is merged we should good ?

**Comment by harrijk** [comment]
Ha.  I knew I was missing something.  :)  Thanks for keeping me straight.  Yes, we should be good after the merge of the #1103 fix.

Cheers.
