### ISSUE TITLE
Panic upon discovering membersvc port 50051 is in use

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1078]
Description:

Was getting a demo of the provisioning script Ramesh has been working on, it spun up peers and a CA, but they all exited due to a hardware enumeration difference in my machine.  I didn't realize CA remained up, when I manually called the membersvc, it immediately panicked at the discovery of another CA already up.

Steps to repro:
1.  Run one CA
2.  Attempt to run another

Results:

CA fails with a panic

Expected results:

CA should fail gracefully
[panic at the disco.txt](https://github.com/hyperledger/fabric/files/216064/panic.at.the.disco.txt)

**Comment by adecaro** [comment]
@diegomasini, please, may you have a look a this?

**Comment by srderson** [comment]
Closed via PR #1083

**Comment by RicHernandez2** [comment]
Verified in manual test

![membersvc](https://cloud.githubusercontent.com/assets/17052305/14510184/3310a5da-019e-11e6-9c7d-42465e464b6d.JPG)
