### ISSUE TITLE
Any plan on performance benchmark?

### ISSUE THREAD

**Issue by yeasy** [hyperledger-archives/fabric#1086]
It is always hard to explore the performance bottleneck for distributed systems.

So it might be a good idea to introduce some standard testbed at an early stage, for evaluating different releases during the long-term evolution.

And, we can use the benchmark to generate various scenarios, to test hyperledger's behaviour with different parameters (e.g., node number, consensus algorithm).

How do you think?

Welcome for any feedback, thanks!

**Comment by jeremyeder** [comment]
I think a generic workload generator and benchmark has to be designed outside of the particular blockchain implementation. To allow comparison between implementations.

**Comment by yeasy** [comment]
Yes, you're right, @jeremyeder 
Maybe we can initiate some sub project to start from evaluating the performance and scalability of hyperleger, as it should be the open-source standard for blockchain techniques.

How do u think?

**Comment by jeremyeder** [comment]
Probably, yep.  Do you attend the TSC calls?

**Comment by yeasy** [comment]
@jeremyeder Yes, I will try to be there next week.

**Comment by yeasy** [comment]
Some preliminary results.

The test node is a single physical 4c8g linux 3.16 machine.

Currently only using 1 client/1 API to test the query and invoke transaction.

The sample testing code can be found at https://github.com/yeasy/hyperledger-py/tree/master/tests/benchmark.

It seems physically we can support 100s of tps right now.

Cannot attach file here, however, in summary
- query: typically around 200 tps.
- invoke: 140+ for pbft:classic, 210+ for  pbft:batch, while 290+ for noops.

**Comment by christo4ferris** [comment]
@yeasy closing this as we can use #1446 for tracking the need for performance benchmarking/regression testing.
