### ISSUE TITLE
Deprecated devops REST API ->  chaincode REST API.  What's the transition plan?

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1101]
I am in the process of converting the obcsdk to use the new POST /chaincode API instead of the 
/devops/<op> API.  

The old API works fine, which started me wondering how long it will be supported?   Forever?  For a couple weeks? 
This has bearing on things important to testers.  For example, should we write and maintain a regression bucket for the deprecated API?  Should I dual-flavor obcsdk (let you choose your API)?  Or should we write devops out of obcsdk, and stop testing devops entirely?  Or will we test them forever?

Here is something that happened in PureApplication: a deprecated process was supported for two releases,  but every time the deprecated interface was used, a log message would appear warning you to modernize the call.  After two releases, the old calls simply failed. 

Barry Mosakowski, Nishi Nidamarty and I discussed this.  We decided a defect is the best way to initiate dialogue about the transition strategy from the old to the new.

**Comment by binhn** [comment]
since we are in incubator, we will have to move much faster, so I think 3 sprints duration (6 weeks) is about right because we can't afford to maintain the depreciated APIs for a long period of time.  When we start releases, then the duration should be longer.

**Comment by angrbrd** [comment]
@jjjjibm, I think this is a valid point and should be addressed. I do not currently output any log messages when the deprecated API is being used. The only thing I did was update ALL of the available documentation to mark the /devops endpoints deprecated.

What I can do is add a [WARN] level message whenever any of the /devops/deploy, /devops/invoke, or /devops/query endpoints are being used. At the same time, I will create an issue to completely disable these REST endpoints by a specified date. We could push this out for another several sprints. Would this be acceptable? Please let me know and I will address.

Thanks.

**Comment by jjjjibm** [comment]
@binhn and @angrbrd 
- six weeks is plenty.  Based on Binhn's comment, I wrote devops out of the SDK and am not testing it since it will be gone by the time we are doing releases
- WARN level are good in case someone is using the deprecated APIs.

**Comment by jjjjibm** [comment]
Re-opening as Anya wants to use this issue to add warnings.

**Comment by angrbrd** [comment]
I have submitted a PR that will now output the following warning level messages into the peer logs whenever the deprecated /devops endpoints receive a request.

> [rest] Deploy -> WARN 017 /devops/deploy endpoint has been deprecated. Use /chaincode endpoint instead.
> [rest] Invoke -> WARN 01b /devops/invoke endpoint has been deprecated. Use /chaincode endpoint instead.
> [rest] Query -> WARN 01e /devops/query endpoint has been deprecated. Use /chaincode endpoint instead.

**Comment by angrbrd** [comment]
I have opened issue #1577 to track the removal of the deprecated /devops endpoints after the next several iterations.
