### ISSUE TITLE
Add minimum version to Vagrantfile

### ISSUE THREAD

**Issue by harche** [hyperledger-archives/fabric#1105]
~/go/src/github.com/hyperledger/fabric/devenv$  vagrant up 

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: box_version
* The box 'hyperledger/fabric-baseimage' could not be found.
```

**Comment by harche** [comment]
Vagrant 1.4.3

**Comment by srderson** [comment]
You need 1.7.4 or later

**Comment by harche** [comment]
Opps, I used whatever came from ubuntu 14.04 repository. Thanks, it works fine now.

**Comment by srderson** [comment]
I'm going to reopen this issue and use it to try adding a minimum version (https://www.vagrantup.com/docs/vagrantfile/vagrant_version.html) to the Vagrantfile. Hopefully this will result in it outputting a more useful error message.

**Comment by harche** [comment]
Sounds good, would you like me to send that fix?

**Comment by harche** [comment]
I have created a pull request to fix this issue, https://github.com/hyperledger/fabric/pull/1109

**Comment by srderson** [comment]
@harche Thanks! I've merged your PR.
