### ISSUE TITLE
not found 'go' in openblockchain/baseimage 

### ISSUE THREAD

**Issue by ckeyer** [hyperledger-archives/fabric#1106]
```
[root@luv fabric]# docker run --rm  openblockchain/baseimage:0.0.9 go
exec: "go": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
```

**Comment by srderson** [comment]
I'm not sure that the GOPATH in in $PATH in the base image. It is configured during the `vagrant up` process at https://github.com/hyperledger/fabric/blob/master/devenv/installGolang.sh#L37

@muralisrini Is this something the Go chaincode base image requires?

**Comment by muralisrini** [comment]
@ckeyer :  go is in "openblockchain/image" ...
![image](https://cloud.githubusercontent.com/assets/14361488/14568173/a6ead170-0305-11e6-98db-aa81066306a6.png)

Do you need go in 0.0.9 for any particular reason or are you just checking ?

**Comment by ckeyer** [comment]
thanks
