### ISSUE TITLE
is table struct complex?

### ISSUE THREAD

**Issue by cophey** [hyperledger-archives/fabric#1107]
`type Table struct {
    Name                     string
    ColumnDefinitions  []*ColumnDefinition
}`
`type ColumnDefinition struct {
    Name string
    Type ColumnDefinition_Type
    Key  bool  
}`
`type Row struct {
    Columns []*Column
}`
`type Column struct {
    // Types that are valid to be assigned to Value:
    Value isColumn_Value
}`

As this,when i use getrow api,it returned a json data as follow:
`{
    "OK":{
        "columns":[
            {
                "Value":{
                    "String_":"id1"
                }
            },
            {
                "Value":{
                    "String_":"test1"
                }
            },
            {
                "Value":{
                    "String_":"M"
                }
            },
            {
                "Value":{
                    "Int32":26
                }
            }
        ]
    }
}`

when i use getrows api,it returned a json data as follow:
`OK=[{"columns":[{"Value":{"String_":"id1"}},{"Value":{"String_":"test1"}},{"Value":{"String_":"M"}},{"Value":{"Int32":26}}]}]`

Is this response data some complex?or there are other considerations?Thanks!

**Comment by srderson** [comment]
It's defined in a proto. See https://github.com/hyperledger/fabric/blob/master/core/chaincode/shim/chaincode.proto

The generated code lives at https://github.com/hyperledger/fabric/blob/master/core/chaincode/shim/chaincode.pb.go
