### ISSUE TITLE
unable to acces the fabric folder on vagrant

### ISSUE THREAD

**Issue by ghost** [hyperledger-archives/fabric#1108]
unable to access the fabric folder on the guest machine after the vagrant ssh command.
cd $GOPATH/src/github.com/hyperledger/fabric gives 
no such file or directory
![vag](https://cloud.githubusercontent.com/assets/17274882/14559765/c386958a-0328-11e6-8d9a-c3f6d4a39d46.PNG)

**Comment by srderson** [comment]
Does $GOPATH/src/github.com/hyperledger/fabric exist on your host system?

Could you share the output from `vagrant up`?

**Comment by nitesh7sid** [comment]
yes it is present on my host system. 
![vagrant](https://cloud.githubusercontent.com/assets/18530954/14636533/a74daea2-0649-11e6-86cd-9aefb4c8973d.PNG)

**Comment by srderson** [comment]
There have been many changes to the vagrant env since this was opened. Please reopen if this is still an issue.
