### ISSUE TITLE
Fix PBFT consensus to avoid normal case view changes.

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#1119]
I discussed this in slack with @corecode but I am observing behavior where PBFT is being forced into a view change when it should not be.

Consider the scenario when vp2 is the primary and vp3 is offline, K=2, L=4

vp0 - send checkpoints 2, 4
vp0 - receive vp0 checkpoint 2, 4
vp1 - send checkpoints 2, 4
vp1 - receive vp1 checkpoints 2, 4
vp2 - send checkpoints 2, 4
vp2 - receive vp0,vp1,vp2 checkpoints 2, and 4
vp0,1 - receive vp2 checkpoints 2, and 4 (do not move watermarks, only f+1)
vp2 - move watermarks and send pre-prepare 5
vp0,1 - receive and ignore vp2 pre-prepare 5
vp0 receive vp1 checkpoints 2, and 4, move watermarks
vp1 receive vp0 checkpoints 2, and 4, move watermarks

We are now in a scenario where vp0 and vp1 have discarded a pre-prepare message from vp2, so the network will cease to make progress until the view change timer expires, causing an (unnecessary) view change when the primary was not behaving in a byzantine fashion.

Although this problem seems like it would be mitigated by the log, it is still seen frequently in stress testing.
1. Primary orders L requests
2. Network reaches consensus on order before first request is executed
3. All requests are executed, triggering the transmission of the checkpoints in quick succession
4. Sometimes, primary is first to get the checkpoint quorum, it broadcasts the next pre-prepare
5. The backups receive this pre-prepare before the checkpoint quorum, and initiate view change

My suspicion is this is especially likely in docker-ized testing like we do with behave, because all replicas are competing for the same CPU resources, and one replica's threads being serviced necessarily causes other replicas to be idle, but even though this is likely less of a concern in production, it still seems like a scenario worth at least considering addressing.

In an experimental branch, I was able to decrease the frequency of this occurrence by increasing the log size from 2_K to 4_K, and modifying the behavior of the primary to only submit pre-prepares if the sequence number was going to be less than or equal to L-K.   In this way, the primary had some additional buffer on the other side to give the other replicas an opportunity to receive eachother's checkpoints.  Still, there is nothing preventing the failure from still occurring, as if checkpoint messages are sufficiently delayed between peers, the primary could still advance its watermarks twice and send a pre-prepare to a replica which had not yet advanced its watermarks once.

@vukolic @corecode @kchristidis @tuand27613 any thoughts?

**Comment by corecode** [comment]
I guess we should limit the assignment of new sequence numbers more than the log size?  I.e. that the receive sequence number window is always larger than the send window?

**Comment by vukolic** [comment]
In PBFT, view changes occur if primary is faulty _or if network behaves asynchronously, delaying messages_. There is not much we can do about this in worst case where checkpoint messages are scheduled by environment in a bad way.

What we can (and need to) do is account for delays caused by slow execution. Letting replicas buffer _but not process_ messages above Hwm would be one approach. E.g., buffer requests from lastexec+Hwm to lastexec+2Hwm - but not process them.

Also, the issue should dissapear with planned separation of consenters and endorsers.

   Simon Schubert --- Re: [hyperledger/fabric] Fix PBFT consensus to avoid normal case view changes. (#1119) --- 
    From:"Simon Schubert" notifications@github.comTo:"hyperledger/fabric" fabric@noreply.github.comCc:"Marko Vukolic" mvu@zurich.ibm.comDate:Mon, Apr 18, 2016 12:54Subject:Re: [hyperledger/fabric] Fix PBFT consensus to avoid normal case view changes. (#1119)

  I guess we should limit the assignment of new sequence numbers more than the log size? I.e. that the receive sequence number window is always larger than the send window?

**Comment by jyellick** [comment]
@corecode @vukolic So you both support the idea of making the receive window larger than the send window? (Say, the receive window will be double the size of the send window by defualt?)  This was my 'workaround' solution, and it did seem to decrease these unnecessary view changes and increase throughput.

**Comment by vukolic** [comment]
@jyellick yes

   jyellick --- Re: [hyperledger/fabric] Fix PBFT consensus to avoid normal case view changes. (#1119) --- 
    From:"jyellick" notifications@github.comTo:"hyperledger/fabric" fabric@noreply.github.comCc:"Marko Vukolic" mvu@zurich.ibm.comDate:Mon, Apr 18, 2016 16:28Subject:Re: [hyperledger/fabric] Fix PBFT consensus to avoid normal case view changes. (#1119)

  @corecode @vukolic So you both support the idea of making the receive window larger than the send window? (Say, the receive window will be double the size of the send window by defualt?) This was my 'workaround' solution, and it did seem to decrease these unnecessary view changes and increase throughput.

**Comment by jyellick** [comment]
This has been implemented in PR #1143, closing.
