### ISSUE TITLE
Automate a system test for #756

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#1121]
We want to test that an extra peer cannot participate in a PBFT consensus network once we already have N replicas
Scenario is like this:
1. security enabled,  PBFT N=4
2. start membersrvc, peer0, peer1, peer2, peer3
3. deploy example02
4. 10 or more invokes ( anything, maybe a-1, b+1 ) 
5. verify value of a via query to peer0/1/2/3
6. start peer4
5. 10 or more invokes ( enough so that checkpoints get sent )
6. verify value of a via query to peer0/1/2/3
7. verify that peer4 did not participate in consensus ( maybe query peer4 chain height which should be 1)

Doing this in `behave` requires new Python routines to start/stop individual docker containers and to map container ip addresses to endpoints we can use for the REST api.  Docker-compose doesn't give us a way to start a container in paused mode so step 6 is would require a big update to how we set up behave.

I've talked to @RicHernandez2  @ramesh @manish-sethi  about this and they will investigate.

**Comment by jeffgarratt** [comment]
This support is already available I believe.

**Comment by tuand27613** [comment]
sorry @manish-sethi  , I meant to type Nishi's id ... stupid auto-complete ...

@jeffgarratt I'm somewhat stymied by step 6.  Peer4 can't be part of the docker-compose file that defines peer0/1/2/3. So we need a step that starts an individual docker container. Then we need to configure this container to communicate with the other containers so we get to do ip address discovery and mapping. So some amount of mucking about in the .py files required ?

**Comment by jeffgarratt** [comment]
@tuand27613. This is already done in the issue 684 test I believe.

**Comment by tuand27613** [comment]
issue_680  ?

680 start 4 VPs, stops one then restarts it.

what i'm looking for to start 4 VPs , then at a later time start a 5th one. From what i can tell, this 5th one can't be part of the docker-compose config of the other 4 VPs.

**Comment by christo4ferris** [comment]
@tuand27613 was this ever added?

**Comment by tuand27613** [comment]
This test has not been added.  Since we're rethinking #756,  I'll close this and reopen after we've had a chance to implement some of the new architecture
