### ISSUE TITLE
shim.GetRow() causes chaincode to crash (with no response returned to query CLI/API) when provided with a key that doesn't exist

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#1124]
If I pass a key that doesn't exist to shim.GetRow(), the chaincode crashes.

What is the correct way to check if a particular key is present in a table?

**Comment by prjayach** [comment]
@muralisrini Can you check on this please?

**Comment by prjayach** [comment]
Clarification: shim.GetRow() itself does not crash, but I think returns an empty message. Not sure how I can check if message is empty in my chaincode. Would be better to return an error from GetRow()?

**Comment by srderson** [comment]
@prjayach The best way to handle this today is likely

```
if len(row.Columns) == 0 {
// it's empty
}
```

The `GetRow` API probably should return `(Row, ok, error)` with `ok` being `true` or `false` to indicate if the row is present. I think `error` should only be returned if there is an unexpected error.

**Comment by prjayach** [comment]
@srderson Thanks for the tip. This works.

**Comment by ibmmark** [comment]
spoke to @prjayach and we can close based on @srderson answer
