### ISSUE TITLE
Make our GitHub docs behave more like Explorer-like format

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#1125]
Reorganize the fabric/docs directory to be more friendly to application and fabric developers:
1. The fabric/docs/README.md should contain a table of contents (links) where each points to a topic
2. Introductory material (extract from OBC whitepaper)
3. Installations and configurations
4. Tutorials (per use-case) on chaincode, APIs, SDK, events, and best practices
5. API references
6. Architecture and protocol

The focus should be on installations and tutorials where most developers need.

**Comment by binhn** [comment]
@joshhus Not sure why protocol spec.  We need to restructure our docs directory to be more structured and linked rather than a collection of individual documents. The objective is to provide a book-like like of information flow: from intro to detail.

**Comment by joshhus** [comment]
Agree, who's owning this item for LF/HL GitHub? ... If there is indeed not a quick solution (ID looked into this), then the protocol-spec is the one doc that could benefit from linking in the shorter term.

**Comment by binhn** [comment]
@joshhus I assign this to you. Nothing we can do from LF until a code-base decided. We just need to restructure existing docs or add more docs to make it more complete.  We need to organize them under fabric/docs folder with the README.md be the landing page providing a TOC like structure

**Comment by joshhus** [comment]
Okay we can work on that. Is there any dev. resource who could assist? (See related email on the other ID priorities.) @nickgaski

**Comment by binhn** [comment]
@joshhus engage with all developers identified.  I think we need to have a good toc first then we can dissect existing docs to fill in

**Comment by joshhus** [comment]
We're talking about two different things, but yes I also follow the broader initiative that you describe. TBA.

**Comment by binhn** [comment]
@joshhus please post a draft of "table of contents" here, so we can estimate the remaining workload to generate any needed new contents.

**Comment by joshhus** [comment]
I assume you only want a TOC of the doc that we already on GitHub. ... That's doable in the short-term.

**Comment by binhn** [comment]
@joshhus I really want to restructure our docs to be more amiable to new comers. The structure should start with introductory material to tutorials and advanced topics, which we have various docs today. I will rewrite the issue description to be more in line with what we need

**Comment by joshhus** [comment]
Agree, okay. I will get a TOC together for what we have today on GitHub. The pieces (topics) can be rearranged / categorized easily.

**Comment by joshhus** [comment]
Just want to note here, also, as I have on emails, that .md is not a flexible format for authoring. It's designed for fast and easy. No single-sourcing of terms, no conditional tagging (hide/show for specific outputs), and no other outputs (no PDF, ePub, future?) ... We're tied to .md + some HTML by authoring on GitHub. We can consider a proposal to the community to author in the powerful DITA/XML model instead, which then can output to .md-supported HTML (presumably) and additional / future formats. (i.e. If some future date or event results in .md no longer being acceptable, we would be faced with re-doing the entire library in XML.)

**Comment by joshhus** [comment]
Hi Joe, so let's work together to get this resolved. It seems like we want the install instructions moved out of fabric/README.md and into a new file, in fabric/docs. Then the remainder of the fabric/README.md left as-is, but without the moved install doc. ... Is that correct / do you agree? Thanks. Slack me at joshhus ...

**Comment by joshhus** [comment]
@joequant ... please see above, thanks.

**Comment by binhn** [comment]
@joshhus Joe's changes are in this PR https://github.com/hyperledger/fabric/pull/1164.  However, we want the fabric/README to contain more info about Fabric and move the installation info to a fabric/docs file. We also need a couple of installation entries: 1 for fabric developers (current one) and 1 for application developers who might just want to run the docker-image from hyperledger docker hub.

**Comment by christo4ferris** [comment]
closing this as we have deployed the readthedocs documentation

**Comment by JonathanLevi** [comment]
@joshhus and @rameshthoomu: Just to re-iterate: the [read-the-] docs look awesome!

**Comment by joshhus** [comment]
Just to summarize, we went with the Read The Docs (RTD) GitHub service instead of Python Sphinx (PS) proper, because RTD manages .md files directly, whereas PS requires an intermediate step of .md to .rst ("restructured") files. And the output is the same. @rameshthoomu deserves most of the credit for implementation. Next up: do the same thing for IBM-Blockhain docs repo (once we get that content updated).

**Comment by JonathanLevi** [comment]
Edited above with credit where credit is due!
