### ISSUE TITLE
Remove need for -o flag when compiling peer

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1131]
The documentation currently gives the following instructions for compiling the peer.
`go build -o peer`

This generates a binary named `peer`. Without the `-o` flag, the binary would be named `fabric`.

We want to remove the use of the `-o` flag as it causes confusion and ideally keep the binary named `peer`.

The proposal is to create a top level folder named `peer` and move `main.go` and `core.yaml` into this folder.

```
cd $GOPATH/src/github.com/hyperledger/fabric/peer
go build
```

would generate a binary named `peer` in this case.

**Comment by genggjh** [comment]
Why can't we just use the fabric as the binary file name or give another name? Instead of peer, after all you know './peer peer' is really a little bit confusing.
Maybe './peer -d' is another better choice. -d means run peer as daemon process.

**Comment by srderson** [comment]
The reason for not using 'fabric' as the binary name is because this encompasses other parts of the system that are not the 'peer' such as 'membership services', 'sdk', 'api', etc. I imagine the list will grow.

Agree that `./peer peer` is a bit confusing and the `./peer -d` may be a better option.

**Comment by RicHernandez2** [comment]
Please keep the documentation up do date on what you decide.  For now I'm calling ./peer peer, till documentation says otherwise.

**Comment by srderson** [comment]
@RicHernandez2 Yes, I will also update docs. For the first pass, I'm just moving peer and core.yaml. If we choose to deprecate `./peer peer` in favor of `./peer -d` we can likely keep both for a while for backwards compatibility.

**Comment by genggjh** [comment]
+1

**Comment by srderson** [comment]
Closing as main and core.yaml have been moved. @genggjh It seems there's discussion on the `peer` command taking place in issue #1158
