### ISSUE TITLE
Setting up Hyperledger

### ISSUE THREAD

**Issue by Jazzrocks** [hyperledger-archives/fabric#1135]
Has anybody tried setting up the environment directly on the Ubuntu . Can we skip the vagrant part (comment vagrant code in setup.sh ). What is the best way to start with or without vagrant ?

**Comment by Jazzrocks** [comment]
@muralisrini i just got this link https://github.com/yeasy/docker-hyperledger .
What are your views on the same . should i go ahead with this on my ubuntu machine ?

**Comment by muralisrini** [comment]
@Jazzrocks : Is this for dev/test or more prod-like situations .. or just checking things out ? I have setup directly on Ubuntu. When I want to do complex stuff (like testing with multiple peers) I quickly find the vagrant approach saves a lot of trouble.

Looking at the Docker file in the above link, you could just copy those instructions to install rocksdb on Ubuntu. That should give you everything you need to build fabric on Ubuntu and run it.

@srderson - comment/correct if you like please.

**Comment by srderson** [comment]
That docker image looks good to me. If you really want to try it the manual way, there are some instructions at https://github.com/hyperledger/fabric#building-outside-of-vagrant-

**Comment by Jazzrocks** [comment]
@muralisrini @srderson can i test my custom chaincodes ,i want to transfer strings rather than integers as mentioned inexmple-2

**Comment by srderson** [comment]
Chaincode development is beset done in the Vagrant environment, thought you can do it in standalone.

**Comment by joequant** [comment]
Yes.  There are two different shell scripts that let you do that.
https://github.com/joequant/hyperledger 

which is adapted from

https://github.com/yeasy/docker-hyperledger

**Comment by christo4ferris** [comment]
this question is perfect for stackoverflow

**Comment by christo4ferris** [comment]
@Jazzrocks you can deploy our published docker images directly to any system that supports Docker. The documentation has been [updated](http://hyperledger-fabric.readthedocs.io/en/latest/Setup/Network-setup/) accordingly to describe how to do this. Closing for now. Please feel free to reopen if you still think there's an issue.
