### ISSUE TITLE
How can I access virtual web server from Mac host?

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#1137]
I installed fabric Docker in VM by vagrant up, I created chaincode and web application in VM.
How can I check it in browser on Mac host? 

Now, in Mac host, I can not ping any of VM, Docker, even 127.0.0.1
<img width="1096" alt="2016-04-18 9 58 10" src="https://cloud.githubusercontent.com/assets/7720620/14606661/ca809414-05b0-11e6-814f-3e29611314c0.png">

I guess it should do something in network setting of virtualbox, but once I change the network setting and vagrant up, the setting was reset.
<img width="765" alt="2016-04-18 10 02 25" src="https://cloud.githubusercontent.com/assets/7720620/14606787/47ed6936-05b1-11e6-8093-41c0f8eb5636.png">

Please kindly help me what should I do?

**Comment by srderson** [comment]
You could use the REST API. It's mapped to port 3000 on your host.
https://github.com/hyperledger/fabric/blob/master/devenv/Vagrantfile#L35

**Comment by zhuang-weiming** [comment]
Finally I run my sample code. Thank you @srderson  so much for you guide!
