### ISSUE TITLE
Chaincode example2 implements function "bogus"

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1146]
*\* Initializing and deploying chaincode github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 on network with args [a 20000 b 9000]

{
    "jsonrpc": "2.0",
    "method": "deploy",
    "params": {
        "type": 1,
        "chaincodeID": {
            "path": "github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
        },
        "ctorMsg": {
            "function": **"bogus",**    <====  invalid input 
            "args": [
                "a",
                "20000",
                "b",
                "9000"
            ]
        },
        "secureContext": "diego"
    },
    "id": 2
}

**Sending Rest Request to : http://127.0.0.1:3000/chaincode/

Response from Rest Call: >>

{
    "jsonrpc": "2.0",
    "result": {
        "status": "OK",
        "message": "f55ecb8029b36994d2f08b0ca283fb71178f509a0689f42251a452d78d92587e733c4f50e789dd6f91aa3c12bcbcd762cf9e250a2dac37732084fe25f644d59a"
    },
    "id": 2
}

Shouldn't this have failed?

**Comment by srderson** [comment]
See https://github.com/hyperledger/fabric/issues/835
Calling a chaincode is asynchronous. There will be functionality in the SDK to emulate a synchronous API.
