### ISSUE TITLE
Create hyperledger table example

### ISSUE THREAD

**Issue by joequant** [hyperledger-archives/fabric#1150]
Todo: Create an hyperledger chain code that creates a database table and allows for CRUD functions against that template.

**Comment by srderson** [comment]
There's a test case at https://github.com/hyperledger/fabric/blob/master/core/behave_chaincode/go/table/table.go but I agree that a good example under https://github.com/hyperledger/fabric/tree/master/examples/chaincode/go would be much better.

**Comment by mastersingh24** [comment]
@joequant - agree here.  we started an "chaincode how-to" document (it exists in an external repo now) and want to bring that into the HL documentation.  It is currently simple, but the idea was that it should build up and explain all of the SHIM APIs and how to use them.

**Comment by himanshutyagi36** [comment]
Did you guys find any good place to get started on the same, I need a little help

**Comment by pards** [comment]
The test case seems to have moved.
New link: https://github.com/hyperledger/fabric/blob/master/bddtests/chaincode/go/table/table.go

**Comment by christo4ferris** [comment]
I think that this can be closed, please feel free to reopen if you feel otherwise
