### ISSUE TITLE
A question on Block Size

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#1154]
In yaml file "./consensus/noops/config.yaml" there is a block size defined as "500" by default, 

```
   block:
   # Number of transactions per block. Must be > 0. Set to 1 for testing
        size: 500
```

does this block size apply to only consensus=noops?
It cannot be found in "./consensus/obcpbft/config.yaml". 
Is there a similar parameter for consensus=obcpbft, batch/classic/sieve ? 

Thanks,

**Comment by binhn** [comment]
@samding01 yes, that config is for noops.  For pbft, look for batchsize
