### ISSUE TITLE
Explore tools to allow community to assist in labeling issues

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1173]
Currently, labeling of issues is limited to only maintainers of this project. Ideally, we would want all members to assist in labeling issues. This is not a permission that exists in GitHub, so we want to investigate if there are any tools/bots that may help. For example, this may be a bot that reads a slack channel or GitHub comments and applies the appropriate label to a issue when asked.

**Comment by genggjh** [comment]
http://partyline.rocks/blog/github/
http://blog.james-carr.org/2014/08/21/open-a-github-issue-from-slack/

Both above can be for our reference I believe.

**Comment by christo4ferris** [comment]
following the CI meeting we had yesterday with the LF RI engineers, if we move to Gerritt we will need to move to Jira or Bugzilla to manage issues - think this will be an improvement and obviate the need for a bot to fix GH issues.

**Comment by genggjh** [comment]
Prefer to use Gerrit which is easy to review and merge code.

**Comment by binhn** [comment]
What are the key benefits of Gerrit? I haven't used it.  Does it only provide code reviews?  Git is quite sufficient for reviewing, commenting, and updating pull requests.  

The key capability that we need is for a larger community to be able to manage issues without being a maintainer. If we had to move to Jira or Bugzilla for this then I don't see the value of Gerrit but another tool.

**Comment by christo4ferris** [comment]
Gerritt can enforce reviews and it can integrate checks from CI and that the legal bits are properly handled. It is far more effective than github in that regard, and on a project where security and quality are of paramount importance such as this, we can be far more certain of what gets merged. Also, because Gerritt is tied into LF identity, we can also be a bit more certain of who is making the contributions (because we cannot enforce TFA on github accounts).

**Comment by genggjh** [comment]
@binhn: we can reference this I think https://review.openstack.org/#/c/309610/. As @christo4ferris mentioned, the gerrit can be integrated with CI easily and we can involve more peoples to review codes. Everyone can give +/-1 on your commit and give comments, core team member can give +/-2 to approve it, CI tool will used to verified it before merge.

**Comment by christo4ferris** [comment]
@srderson closing this as we are transitioning to Jira RSN (promise;-)
