### ISSUE TITLE
Connector of Node.JS client code for Openssl

### ISSUE THREAD

**Issue by elli-androulaki** [hyperledger-archives/fabric#1177]
We need to use Openssl for performing crypto operations.

**Comment by elli-androulaki** [comment]
Taken on by @thkzrl.

**Comment by thkzrl** [comment]
Node.js fortunately already provides most of OpenSSL's functionality: https://nodejs.org/api/crypto.html We'll have to check if any primitives are missing, though, and then implement the OBC specific primitives such as ECIES.

**Comment by binhn** [comment]
dup of #1199
