### ISSUE TITLE
Client-sdk components & interactions design 

### ISSUE THREAD

**Issue by elli-androulaki** [hyperledger-archives/fabric#1178]
Effort of @zrlthk, @elli-andoulaki, @adecaro, in collaboration with @smithbk, @binhn .

**Comment by binhn** [comment]
@elli-androulaki I still can't assign this item to you because you havenot joined the fabric-contributors team. Could you check your email.

**Comment by elli-androulaki** [comment]
I think you should be able to do so now...

**Comment by GrapeBaBa** [comment]
Is this issue for native golang client SDK?

**Comment by adecaro** [comment]
Hi @GrapeBaBa, this is supposed to be generic enough to accomodate also other languages.

**Comment by ibmmark** [comment]
Hi @GrapeBaBa, Expanding on @adecaro, if you think there should be an additional language and there isn't a current issue open, would be worth creating a new issue for specific language support.

**Comment by GrapeBaBa** [comment]
@ibmmark I already created a issue #1206 , from the maillist it seems someone already contribute python and php SDK, I'd like to contribute a [java client SDK](https://github.com/GrapeBaBa/hyperledger-java), I will upload to maven center once my sonatype account is available.

**Comment by christo4ferris** [comment]
@elli-androulaki @smithbk can this be closed?

**Comment by smithbk** [comment]
@christo4ferris Yes
