### ISSUE TITLE
VP0 gacks under sieve pbft with non deterministic results returned

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1180]
Description:  VP0 stopped logging, started dumping numbers out till it was ctrl-c'd

Steps to repro:
1. Setup a CA and set of 4 VPs using pbft sieve using privacy and security
2. Login your user
3. Do a secure deploy using a version of Chaincode_02 that injects non-deterministic values

Results:

vp0 crashes

Expected results:

vp0 should handle the error gracefully
[non-deterministic-values given to sieve 4 of 4.txt](https://github.com/hyperledger/fabric/files/228423/non-deterministic-values.given.to.sieve.4.of.4.txt)
[non-deterministic-values given to sieve 3 of 4.txt](https://github.com/hyperledger/fabric/files/228424/non-deterministic-values.given.to.sieve.3.of.4.txt)
[non-deterministic-values given to sieve 2 of 4.txt](https://github.com/hyperledger/fabric/files/228425/non-deterministic-values.given.to.sieve.2.of.4.txt)
[non-deterministic-values given to sieve 1 of 4.txt](https://github.com/hyperledger/fabric/files/228426/non-deterministic-values.given.to.sieve.1.of.4.txt)
[chaincode_nondeter_example02.zip](https://github.com/hyperledger/fabric/files/228430/chaincode_nondeter_example02.zip)

Cool, relevant movie quote:

> 11:15 Restate my assumptions: 
> 1.  Mathematics is the language of nature. 
> 2.  Everything around us can be represented and understood through numbers. 
> 3.  If you graph the numbers of any system, patterns emerge. Therefore, there are patterns everywhere in nature. 
> 
> Evidence: The cycling of disease epidemics;the wax and wane of caribou populations; sun spot cycles; the rise and fall of the Nile. So, what about the stock market? The universe of numbers that represents the global economy. Millions of hands at work, billions of minds. A vast network, screaming with life. An organism. A natural organism. My hypothesis: Within the stock market, there is a pattern as well... Right in front of me... hiding behind the numbers. Always has been.

**Comment by corecode** [comment]
Can you please provide a full log, or at least the log section before that large array of numbers?

**Comment by vukolic** [comment]
@RicHernandez2 Full log needed here, pls

**Comment by RicHernandez2** [comment]
I'll try docker -v and give a location off the docker image for the logs so I can capture logs before the docker image gacks... more to come.

**Comment by RicHernandez2** [comment]
Sorry guys, spent the day running into bugs, will have to look at this tomorrow.

**Comment by corecode** [comment]
How does the attached chaincode inject nondeterministic values?

**Comment by RicHernandez2** [comment]
It's got some errors, I can't repro the issue on current code...  closing as no repro

**Comment by RicHernandez2** [comment]
Wait!  Murali helped me, who knew there is an int63?  Or is that another name for a signed int64?

In any case, I was able to capture the logs using redirect and append at the end of the commandline, and I've got a solid repro, works every time.  I'm adding the logs and the ndt (in honor of Neil deGrasse Tyson) code that causes it, and the deploy, just for kicks!

Logs:

Poop.  The files are 70 meg each, github allows only 10 meg files, lets see how much compression we get with winzip.  26.4MB, still too big, lets see if winrar does any better...

![rar](https://cloud.githubusercontent.com/assets/17052305/14929474/8b439386-0e2b-11e6-9097-a61e2f0eb6cd.png)

Great, github won't take .rar files.  

And it won't take multi-file zips... ok, here goes rar files inside zip files.

[vp0.part1.zip](https://github.com/hyperledger/fabric/files/243228/vp0.part1.zip)
[vp0.part2.zip](https://github.com/hyperledger/fabric/files/243229/vp0.part2.zip)
[vp0.part3.zip](https://github.com/hyperledger/fabric/files/243230/vp0.part3.zip)

[vp1.part1.zip](https://github.com/hyperledger/fabric/files/243233/vp1.part1.zip)
[vp1.part2.zip](https://github.com/hyperledger/fabric/files/243232/vp1.part2.zip)
[vp1.part3.zip](https://github.com/hyperledger/fabric/files/243234/vp1.part3.zip)

[vp2.part1.zip](https://github.com/hyperledger/fabric/files/243236/vp2.part1.zip)
[vp2.part2.zip](https://github.com/hyperledger/fabric/files/243237/vp2.part2.zip)
[vp2.part3.zip](https://github.com/hyperledger/fabric/files/243238/vp2.part3.zip)

Non-deterministic chaincode example02:

[nond2.zip](https://github.com/hyperledger/fabric/files/243241/nond2.zip)

Deploy payload that causes crash (Always repros):

```
{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID":{
        "path":"github.com/hyperledger/fabric/examples/chaincode/go/ndt"
    },
    "ctorMsg": {
        "function":"init",
        "args":["a", "1000", "b", "2000"]
    },
    "secureContext": "lukas"
  },
  "id": 1
}
```

**Comment by tuand27613** [comment]
I opened only vp0 but it looks like part1/2/3 all contain the same log ???  timestamp of first line is `19:59:49.708` for all 3.

In any case, the problem is an errant logger.Debug call  at https://github.com/hyperledger/fabric/blob/master/core/ledger/ledger.go#L157 which prints out the whole transaction.

after that logger.Debug call finishes, I see that the peer is still up.

So, no crash and the sieve check for non-determinism happens at line 835 in the log.

Let's try to re-run with a lesser core_logging_level ?

**Comment by RicHernandez2** [comment]
Hmmm, no, they're segmented by winrar and the filenames are automatically named after the original files by winzip.  Possibly if you unzipped them all in the same directory, whatever unrar program is smart enough to recognize the pieces are related and gives you the complete file as it unrars all the parts and stitches them together?

Will rerun with lesser logging level on Mon, or sooner if I can manage to come in this weekend.

**Comment by RicHernandez2** [comment]
Here goes with warning level logging and today's code:

Lots of "This indicates a bug" in the logs

[vp0log.txt](https://github.com/hyperledger/fabric/files/247273/vp0log.txt)
[vp1log.txt](https://github.com/hyperledger/fabric/files/247272/vp1log.txt)
[vp2log.txt](https://github.com/hyperledger/fabric/files/247270/vp2log.txt)
[vp3log.txt](https://github.com/hyperledger/fabric/files/247271/vp3log.txt)

**Comment by tuand27613** [comment]
Spent some time with @RicHernandez2 to re-configure his network and re-run his scenario. 
I don't see the "indicates a bug" messages anymore and the system stays up after the deploy/invoke of the test chaincode. 
I do see an error message on the query but this looks like some coding issue in the chaincode itself.

In any case, I've asked Ric to re-run with a commit containing PR #1325

**Comment by vukolic** [comment]
folks, what's the status on this one? can it be closed?

**Comment by christo4ferris** [comment]
@corecode @vukolic i'm closing this as it is stale and the last comment from @tuand27613 suggested it is no longer an issue.
