### ISSUE TITLE
With security+privacy enabled, CLI cannot deploy, REST can deploy but cannot query

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#1185]
commit f39bf584923ed4c5bd4a7632ddb6b948c94f8e37
Merge: 488d266 5ccf6ee
Author: Sheehan Anderson sranderson@gmail.com
Date:   Wed Apr 20 10:41:53 2016 -0400

```
Merge pull request #1162 from bcbrock/gitignore

Added a few new entries to .gitignore
```

4 nodes, security+privacy enabled. Same results whether consensus=NOOPS or PBFT. Debug level logs attached below are for NOOPS. Standard chaincode_example02 used for the tests.

With CLI, after login, deploy fails with "Registration to the Membership Service Required":

```
# ./peer login lukas
17:25:35.326 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
Enter password for user 'lukas': ************

# ./peer chaincode deploy -u lukas -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
17:25:50.383 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO

Usage:
  peer chaincode deploy [flags]

Global Flags:
  -c, --ctor="{}": Constructor message for the chaincode in JSON format
  -l, --lang="golang": Language the chaincode is written in
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax
  -n, --name="": Name of the chaincode returned by the deploy transaction
  -p, --path="": Path to chaincode
  -u, --username="": Username for chaincode operations when security is enabled

Error: Error building chaincode: rpc error: code = 2 desc = "Registration to the Membership Service required."
```

Debug level logs for all 4 peers attached. 
[cli_peer_log.zip](https://github.com/hyperledger/fabric/files/228856/cli_peer_log.zip)

With REST, deploy succeeds but query fails with

```
{"Error": "Querying Chaincode -- Error:Failed to launch chaincode spec(premature execution - chaincode (bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c) is being launched)"}
```

Debug level logs for all 4 peers attached. 
[rest_peer_log.zip](https://github.com/hyperledger/fabric/files/228863/rest_peer_log.zip)

**Comment by adecaro** [comment]
From the following lines of log:

[31m17:26:01.059 [crypto] init -> ERRO 1e7[0m [client.] Not registered yet.
[31m17:26:01.059 [crypto] Deploy -> ERRO 1e8[0m Failed client initialization []: [Registration to the Membership Service required.].

I can deduce that the CLI is not sending 'lukas' to the peer.

**Comment by adecaro** [comment]
@gongsu832, may you give more information on the setup? Was a behave test that failed?

**Comment by gongsu832** [comment]
@adecaro All 4 nodes are z/VM guests running zLinux, with 2 CPUs and 4GB memory. All of them had exactly the same one failure in the behave tests.

```
Failing scenarios:
  peer_basic.feature:440  chaincode example02 with 4 peers and 1 membersrvc, issue #567 -- @1.4 Consensus Options

0 features passed, 1 failed, 1 skipped
21 scenarios passed, 1 failed, 4 skipped
359 steps passed, 1 failed, 186 skipped, 0 undefined
Took 22m16.782s
```

It looks like a timeout from the log. I imagine increasing the timeout value may fix it. Here is the entire log.
[behave.log.zip](https://github.com/hyperledger/fabric/files/230109/behave.log.zip)

**Comment by gongsu832** [comment]
Please ignore the REST part of the problem. It's due to a bug in my test script. CLI problem still stands.

**Comment by tuand27613** [comment]
@gongsu832  @adecaro   I can reproduce the error with a vagrant/docker/4vp/pbft(classic)/security enabled/privacy enabled environment on windows7.

login works
deploy example02 works
invoke A->B 10  works
query fails with error described by Gong Su.

running commit [4506910](https://github.com/hyperledger/fabric/commit/4506910c15dcd4c4c0ead61e6d3d15a8f451bea3)

note that the scenario works if security=enabled and privacy=false

**Comment by tuand27613** [comment]
attaching log from my vp0 peer
[vp0_err.txt](https://github.com/hyperledger/fabric/files/230832/vp0_err.txt)

this is what's showing up (line 2028 in log)

> [36m22:05:02.465 [chaincode] func1 -> DEBU 5cf[0m [15a78ea8]Got state. Sending RESPONSE
> [36m22:05:02.465 [chaincode] 1 -> DEBU 5d0[0m [15a78ea8]handleGetState serial send RESPONSE
> [36m22:05:02.466 [chaincode] processStream -> DEBU 5d1[0m [15a78ea8]Received message QUERY_COMPLETED from shim
> [36m22:05:02.467 [chaincode] HandleMessage -> DEBU 5d2[0m [15a78ea8]Handling ChaincodeMessage of type: QUERY_COMPLETED in state ready
> [36m22:05:02.467 [chaincode] HandleMessage -> DEBU 5d3[0m [15a78ea8-484c-4b08-b01d-dcad284b39f8]HandleMessage- QUERY_COMPLETED. Notify
> [36m22:05:02.467 [chaincode] notify -> DEBU 5d4[0m notifying Uuid:15a78ea8-484c-4b08-b01d-dcad284b39f8
> [36m22:05:02.467 [devops] invokeOrQuery -> DEBU 5d5[0m Failed decrypting query transaction result 
> 22:05:02.467 [crypto] CloseClient -> INFO 5d6[0m Closing client [test_user0]...
> [36m22:05:02.834 [peer] SendMessage -> DEBU 5d7[0m Sending message to stream of type: DISC_GET_PEERS 
> [36m22:05:02.836 [consensus/handler] HandleMessage -> DEBU 5d8[0m Did not handle message of type DISC_PEERS, passing on to next MessageHandler

**Comment by adecaro** [comment]
@tuand27613, may you enable debug logs for the crypto layer by setting logging.crypto: debug? May you also give instruction on how to setup the environment on my machine to reproduce the issue? Thanks :)

**Comment by adecaro** [comment]
@tuand27613, a quick update: I was able to run a similar setting on my local machine following your instruction written in the file 'compose-consensus-4.md' and using the commit you were referring. Everything works there.

**Comment by tuand27613** [comment]
@adecaro yes, compose-consensus-4 will work to set up the 4vp environment.  

just to confirm,  did you modify compose-consensus-4-defaults.yml to set core_security_privacy ?

I'll re-run and add debug logs in a bit

**Comment by adecaro** [comment]
@tuand27613, I have modified directly core.yaml and checked the logs to confirm that confidentiality was used. 

Actually, I had to modify also some of the configuration files in order to make the system working. For example, the infiniteloop.sh was missing. Some paths were not aligned to the current hyperledger structure and so on...

**Comment by tuand27613** [comment]
@adecaro  logs with crypto debug on

decryption error at line 4958 in vp0_err.txt

[1185.zip](https://github.com/hyperledger/fabric/files/232019/1185.zip)

**Comment by muralisrini** [comment]
@tuand27613 : could we also get corresponding chaincode log ?

**Comment by tuand27613** [comment]
chaincode logs: 
[1185.zip](https://github.com/hyperledger/fabric/files/232051/1185.zip)

**Comment by muralisrini** [comment]
@tuand27613 don't see chaincode logs in the zip... only peer logs ?

**Comment by tuand27613** [comment]
CC logs ... really, absolutely, for sure this time
[1185_chaincode.zip](https://github.com/hyperledger/fabric/files/232072/1185_chaincode.zip)

**Comment by adecaro** [comment]
@tuand27613, thanks. From the log, I see that the transactions have confidentiality set to public.

[36m14:26:17.454 [crypto] TransactionPreExecution -> DEBU f9f[0m [validator.test_vp0] Tx confdential level [PUBLIC].

You should see [CONFIDENTIAL] rather than [PUBLIC].

This means that confidentiality is actually off. It is also the reason why I usually prefer to set the properties directly into core.yaml.

Please, may you check again this?

**Comment by tuand27613** [comment]
@adecaro I turned on security/privacy in core.yaml as you suggested in addition to setting environment  variables and I can now do deploy/invoke/query with no error.

@gongsu832 , can you check in your environment ?

**Comment by gongsu832** [comment]
@tuand27613 I normally don't touch the yaml files. I always use the env vars to override yaml settings. I pass the following env vars to peer to turn on security and privacy:

```
CORE_SECURITY_ENABLED=true
CORE_SECURITY_PRIVACY=true
```

And in the beginning of the log file on all the peers, I see:

```
15:05:27.346 [crypto] main -> INFO 001ESC[0m Log level recognized 'info', set to INFO
15:05:27.347 [main] serve -> INFO 002ESC[0m Security enabled status: true
15:05:27.347 [main] serve -> INFO 003ESC[0m Privacy enabled status: true
```

Shouldn't this mean that privacy is on?

**Comment by tuand27613** [comment]
@gongsu832 
on my run with:
- core.yaml security enabled=false/privacy=false
- env var core_security_enabled=true, core_security_privacy=true

i get the error on query and vp0 log says `security enabled\privacy enabled status: true` but also `TransactionPreExecution ... Tx confdential level [PUBLIC]` which @adecaro indicates above is the wrong setting for privacy.

If I now edit core.yaml  to enable security/privacy then login/deploy/invoke/query works and the vp0 log has `security enabled\privacy enabled status: true` and `TransactionPreExecution ... Tx confdential level [CONFIDENTIAL]` which reflects the correct security settings.

So, before I point the finger at Viper,  let's try updating core.yaml in your environment so we have confirmation

**Comment by gongsu832** [comment]
@tuand27613 I can confirm that editing core.yaml to set security:enabled:true and security:privacy:true fixes the problem. I can login/deploy/invoke/query from CLI successfully.

It doesn't seem to be a Viper problem though. Since with CORE_SECURITY_PRIVACY=true and security:privacy:false in core.yaml, the peer log does indicate that the "true" value from the env var has been picked up. But yeah, somewhere down the line the ball got dropped.

**Comment by tuand27613** [comment]
sounds good @gongsu832  can you get Pralhad/Praveen going ?

@adecaro  could you see where the disconnect between peer and crypto is ? I'll try to look over the weekend but you know that part of the code better than me.

**Comment by adecaro** [comment]
@angrbrd, I think you are in a better position to understand where the peer and the crypto layer get disconnected because you wrote that part. Please, may you give a look at it? :)

**Comment by gongsu832** [comment]
I take a quick look at the code. The problem is the client ignoring the -u parameter. In main.go: func chaincodeDeploy, when the client is building the spec, it's checking viper.GetBool("security.enabled"), which is false in this case because neither CORE_SECURE_ENABLED env var nor security.enabled in core.yaml is set to true. Instead, the "-u lukas" command line argument should imply that security has been enabled.

**Comment by angrbrd** [comment]
@gongsu832 , @tuand27613 , @adecaro 

If you're starting the peer off with security.enabled=false and security.privacy=false in core.yaml, but instead setting the environment variables like so:

CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true ./peer peer

That enables the security and privacy setting on the peer process, which is evident from the peer log:

20:21:53.380 [main] serve -> INFO 007 Security enabled status: true
20:21:53.380 [main] serve -> INFO 008 Privacy enabled status: true

Because you are doing the deploy/invoke/query from another terminal, you have to set the environment variables there also to make it recognize the appropriate security/privacy settings and include the registrationID in the transaction that it builds. The -u parameter is used to pass in the registrationID, not to assert that security/privacy is enabled. We use either the security.enabled and security.privacy in core.yaml for that OR the proper settings of the environment variables. So if you do not wish to set it in core.yaml, then the correct command with a logged in user "lukas" from another terminal would be:

> > > Deploy:

CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true ./peer chaincode deploy -u lukas -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

> > > Query:

CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true ./peer chaincode query -u lukas -n cc8ed267d3b70ef0bc26c4ca1a8ce85c6ddcd5aa5e99592befdbfd3a14e390021901874b50a43fc7697b0150ad9a9d14560b55e15ecba5d0d8584ef3ca72f743 -c '{"Function":"query", "Args": ["a"]}'

> > > Invoke:

CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true ./peer chaincode invoke -u lukas -n cc8ed267d3b70ef0bc26c4ca1a8ce85c6ddcd5aa5e99592befdbfd3a14e390021901874b50a43fc7697b0150ad9a9d14560b55e15ecba5d0d8584ef3ca72f743 -c '{"Function":"invoke", "Args": ["a","b","100"]}'

Please test this out and confirm if this works for you. Thanks.

**Comment by tuand27613** [comment]
@angrbrd  I fixed up my setup as you described and the deploy works for me as well.

@adecaro , if you're using  ./consensus/docker-consensus-files, make sure you set security and privacy env variables in the `cli:` stanza in _compose-consensus-4.yml_ ( and copy to  docker-compose.yml  ) and in _compose-consensus-4-defaults.yml_

@gongsu832  let me know when you reproduce. As Anya mentioned, we should probably doc this.

**Comment by gongsu832** [comment]
Then the API doc needs to be updated. But since -u is only meaningful when security is enabled, I don't see why you can't make -u an implicit security.enabled=true.

**Comment by gongsu832** [comment]
Or check both viper.GetBool("security.enabled") and "-u", either implicitly enable security or give some sort of warning.

I can confirm that setting the env vars fixes CLI deploy.

**Comment by tuand27613** [comment]
good news @gongsu832 

regarding handling of -u , I suggest we treat as part of the SDK design discussion.

**Comment by tuand27613** [comment]
@gongsu832   , can we close this issue ?

**Comment by gongsu832** [comment]
@tuand27613 yes go ahead.
