### ISSUE TITLE
Member services register user is insecure

### ISSUE THREAD

**Issue by smithbk** [hyperledger-archives/fabric#1186]
ECAA.RegisterUser should only be allowable by a user with special privileges.
For example, the 'hyperledger.registrar' permission in a tcert could be required.
This implies that there must be one or more users (i.e. registrars) pre-registered by including one or more enrollment entries similar to:
    {'id': 'myID', 'secret': 'xxxx', roles: ['hyperledger.registrar']}

**Comment by JonathanLevi** [comment]
Thank you@smithbk.
1. Yes, the current code does not check that an 'approver' has the privilege to approve such enrollment requests. This is indeed insecure.
2. I also really like the addition of 'roles'. 
3. My 2 cents here are that maybe we should make it clear/more explicit that the role does not really have to be a global one (say, at the heperledger or fabric level). A typical usage can be that someone from JPM, for example, can approve enrollment of JP Morgan's employees, and will have the '**hyperledger.jpm.registrar**' role... or maybe the/an institution would like to have it more granular, say: '**hyperledger.jpm.nyc.registrar**' and '**hyperledger.jpm.ldn.registrar**', etc.

While I know that these are textual fields (and their values can change), I can easily see how this flexibility is needed in such environments. Wanted to double-check and see if you'd agree? Thank you.

**Comment by smithbk** [comment]
Thanks Jonathan.  Great input.  I should have been more clear and this has also sparked some other thinking.

I totally agree that we want the ability to create a registrar that only has permission to register other users with certain permissions.  For example, a registrar should certainly not be able to registrar another user with more permissions that he/she himself has; otherwise, it is a security hole.  In fact, to follow the oauth client model, a client is registered with scopes (permissions the client itself has) and authorities (permissions that it can give to someone else).  To follow a similar model would mean that registrar 'fred' may have roles A & B, but only be allowed to register other users with role A but not B.  Or another way of saying this is that each registrar's profile would consist of two role fields, myRoles and transferrableRoles, where transferrableRoles are those the registrar can give to another user he registers and transferrableRoles is a subset (or equal to) myRoles.

This would allow building a tree of registrars with diminishing roles the further you go down the tree.  But with this alone, there would have to be a registrar at the root of the tree with all roles (i.e. superuser) which admittedly isn't decentralized from an authority perspective.  To get around this, we could allow any registrar to claim additional unclaimed root nodes in the role tree.

For example, everything in the role tree would initially begin with /fabric, and there would exist at least one user (e.g. 'fabricAdmin') who could register users with any role beginning with /fabric.  fabricAdmin could also register a user (e.g. 'JPMAdmin') with the registrar role and '/JPM' root, which allows JPMAdmin to assign roles under /JPM.

That said, given your JPM example, you would want JPMAdmin to only be allowed to register users whose enrollment ID begins with "JPM." or similar prefix.  That could be done and it would then be JPMAdmin's responsibility to ensure that he/she only gave an enrollment <id,secret> to someone who was indeed a JPM employee.

**Comment by smithbk** [comment]
The following are more design thoughts on the registrar.

A registrar is a member identity of a chain that has privilege to register other members.  Member services uses ABAC (Attribute-Based Access Control) to create decentralized registrar members.

Consider the following use case:
Alice from bank1 creates chain1 and invites Bob from bank1 and Charles from bank2 to host peers on chain1.  Alice wants both Bob and Charles to have privileges to download/install a peer to join chain1.  Furthermore, Alice wants Bob and Charles to be able to register other identities which can not host a peer but can themselves register other users to transact on chain1.
For example, bank1’s OnLineBanking app transacts on chain1 on behalf of it’s logged in users, so Bob registers member boa.app.online-banking which has privilege to register and enroll users who have authenticated to the OnLineBanking app.

After Alice creates chain1, the following attribute metadata is associated with Bob’s enrollment ID
       fabric.registrar: [{ chain: “chain1”, memberTypes: [‘peer’,’app’,’user’] ,delegateMemberTypes:[ ‘app’,’user’], attrPrefix:””}]
which reads as follows:
     Alice can register members for chain1 of types 'peer', 'app', or 'user'.  Those members in turn can register other members of type 'app' and 'user'.  The names of the attributes that the ACA can grant to a member created by Alice can begin with the empty string, which means they can have any attribute.

Alice registers Bob with the following attribute:
       fabric.registrar: [{chain:”chain1”, memberTypes: [‘app’,’user’], delegateMemberTypes: [‘user’], attrPrefix: ‘bank1.’}]
Note that Bob can only register members of type 'app' and 'user' and the members that it can create can at most register other members of type 'user'.  Further, the members that Bob registers may only have attributes which are prefixed by 'bank1.'.

Alice registers Charles with the following attribute:
       fabric.registrar: [{chain:”chain1”, memberTypes: [‘app’,’user’], delegateMemberTypes: [‘user’], attrPrefix: ‘bank2.’}]
Charles is the same as Bob except that the members that Charles registers may only have attributes which are prefixed by 'bank2.'.

Bob creates an identity for the OnLineBanking app with an enrollment ID of ‘bank1.app.online-banking’ with the following attribute. 
      fabric.registrar: [{chain:”chain1”, memberTypes: [‘user’], attrPrefix: ‘bank1.online-banking.’}] 

So the bank1.app.online-banking member can only register members of type 'user' and can only give them attributes prefixed by 'bank1.online-banking.'.

Furthermore, each enrollment certificate must have the enrollment ID of the member which registered it, unless of course it was listed in the yaml file without a parent registrar.

**Comment by mastersingh24** [comment]
@diegomasini @andresgaragiola  - as I recall, weren't affiliation groups supposed to be a way to "partition" entities into an hierarchy?   I know it is part of the design for releasing keys to auditors to link transactions.

**Comment by diegomasini** [comment]
@mastersingh24 you are right. Affiliation is included in the ECert. An ECert has only one affiliation and it provides exactly that, a partition for releasing keys to an auditor so it can link transactions if that affiliation is under its jurisdiction.
