### ISSUE TITLE
Genesis block for chaincodes

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#119]
related #120 
We need a genesis block to capture properties for chaincodes, especially system chaincodes. The chaincodes may only read the properties from the genesis block. The genesis block is created during start up and configured with a `genesis` section in the `openchain.yaml` file.

```
genesis:
    property1:
    property2:
```

**Comment by markparz** [comment]
Murali, Jeff and Sheehan to get together on call.
