### ISSUE TITLE
Behave test failed with Connection Timeout error

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1190]
Observed below behave tests are failing on latest commit: also observed `"no route to host"`error messages for the scenario#567.  Performing multiple tests to see the consistency. Will upload log file  once the test runs are finished.

Failing scenarios:
  peer_basic.feature:440  chaincode example02 with 4 peers and 1 membersrvc, issue #567 -- @1.4 Consensus Options
  peer_basic.feature:652  4 peers and 1 membersrvc, consensus still works if one backup replica fails -- @1.3 Consensus Options

commit eb15a3bc3451de205e802daff73c01dea46c4be8
Merge: f39bf58 970b894
Author: Sheehan Anderson sranderson@gmail.com
Date:   Wed Apr 20 14:55:57 2016 -0400

**Log Files**

[FailedScenarios_567_Backup_replica_fails.zip](https://github.com/hyperledger/fabric/files/229029/FailedScenarios_567_Backup_replica_fails.zip)

**Comment by rameshthoomu** [comment]
No route to error message log file:

[No route to host_error.zip](https://github.com/hyperledger/fabric/files/229058/No.route.to.host_error.zip)

**Comment by tuand27613** [comment]
I'm also seeing the `no route to host` message when running behave tests on my Thinkpad W520/windows 7/Vagrant setup.

I see the error at least once on every run but the failing test cases are different each time.

Sometimes, the error is `connection refused`

This is always when issuing the login command

**Comment by muralisrini** [comment]
@rameshthoomu @tuand27613 - I have seen this too. I'm on vagrant on Mac

**Comment by rameshthoomu** [comment]
I not seeing this issue after merge. Could see all behave tests are passing in Travis CI and inside vagrant environment. Closing this issue based on the results.
