### ISSUE TITLE
Maybe the image `openblockchain/baseimage` not so large

### ISSUE THREAD

**Issue by ckeyer** [hyperledger-archives/fabric#1194]
[Dockerfile](https://github.com/ckeyer/obc-env/blob/base/Dockerfile)

[hub docker](https://hub.docker.com/r/ckeyer/obc/tags/)

my fabric fork. https://github.com/ckeyer/fabric

**Comment by christo4ferris** [comment]
@ckeyer thanks for submitting this! I've been playing with alpine as well. I think that there's plenty that we can do to have our images go on a diet. I'll be working some of this this week in the hackfest. closing this issue though as it is based on rather dated code.
