### ISSUE TITLE
fabric/devenv/baseimage/README.md needs updating for openblockchain -> hyperledger

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1195]
The fabric/devenv/baseimage/README.md needs updating for transition from openblockchain -> hyperledger namespaces (specifically, links to atlas and dockerhub images).

**Comment by srderson** [comment]
This file has moved to https://github.com/hyperledger/fabric/tree/master/images/base. It looks like the image has been updated.
