### ISSUE TITLE
A question on source code of tag:v0.1.0

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#1198]
Notice that tag:v0.1.0 uses the old file names and paths.
Is the source code of this repository tagged v0.1.0 the same as the one of https://github.com/openblockchain/obc-peer(tag:v0.1.0)?

Do you keep the updating on https://github.com/openblockchain/obc-peer(tag:v0.1.0)?
Thanks,

**Comment by srderson** [comment]
Yes, I believe it is https://github.com/openblockchain/obc-peer(tag:v0.1.0). A new tag will be created at some point in the future.
