### ISSUE TITLE
Genesis chaincode

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#120]
Related #119 
This is a "system" chaincode responsible for "creating" other chaincodes -- chaincode factory. It will read appropriate properties from the genesis block to govern the chaincode deploying transactions. That is, certain procedure might be inserted before the transactions can be carried out. For example, one might wish to install a genesis chaincode that would require "approval" of certain transactions prior to execution of such transactions.

**Comment by muralisrini** [comment]
There is a lot of dependency and overlap with the Genesis Block work that @srderson is doing. We need to figure out what's left for chaincode framework to do.

**Comment by binhn** [comment]
@srderson is this one implemented ?

**Comment by srderson** [comment]
The ability to delay chaincodes into the genesis block via the openchain.yaml configuration is complete. There's no call from chaincode deployment to a system chaincode yet.
