### ISSUE TITLE
 'identity or token do not match' --> 'identity or token does not match'

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1200]
I see many instances of this error today: **"identity or token do not match"**

This issue is not concerned with why the error is happening. I'll write that up separately.  This issue concerns a couple grammar and spelling errors that are revealed by the error that may as well be fixed. 

I'll copy an excerpt from the log issued by ./peer peer as started from a Vagrant session.  Note two errors in the log excerpt:

1) retrieveing -> retrieving (may as well fix this spelling error while you are in the code)
2)  identity or token do not -> identify or token does not   (grammar error)

"

> 15:09:52.081 [crypto] registerCryptoEngine -> ERRO 020 [client.lukas] Failed **retrieveing** enrollment data [rpc error: code = 2 desc = "**identity or token do not match**"].
> 15:09:52.082 [crypto] register -> ERRO 021 [client.lukas] Failed registering node crypto engine [rpc error: code = 2 desc = "identity or token do not match"].
> 15:09:52.082 [crypto] Login -> ERRO 022 Failed registering client [lukas] with name [lukas] [rpc error: code = 2 desc = "**identity or token do not match**"].
> 15:09:52.083 [rest] Register -> ERRO 023 Error on client login: rpc error: code = 2 desc = '**identity or token do not match**'
> 15:09:52.112 [rest] Register -> INFO 024 REST client login...
> 15:09:52.114 [rest] Register -> INFO 025 Local data store for client loginToken: /var/hyperledger/production/client/
> 15:09:52.114 [rest] Register -> INFO 026 Logging in user 'diego' on REST interface...
> 15:09:52.114 [crypto] Login -> INFO 027 Registering client [diego] with name [diego]...
> 15:09:52.144 [crypto] getEnrollmentCertificateFromECA -> ERRO 028 [client.diego] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = "**identity or token do not match**"].15:09:52.081 [crypto] registerCryptoEngine -> ERRO 020 [client.lukas] Failed **retrieveing** enrollment data [rpc error: code = 2 desc = "identity or token do not match"].
> 15:09:52.082 [crypto] register -> ERRO 021 [client.lukas] Failed registering node crypto engine [rpc error: code = 2 desc = "**identity or token do not match**"].
> 15:09:52.082 [crypto] Login -> ERRO 022 Failed registering client [lukas] with name [lukas] [rpc error: code = 2 desc = "identity or token do not match"].
> 15:09:52.083 [rest] Register -> ERRO 023 Error on client login: rpc error: code = 2 desc = 'identity or token do not match'
> 15:09:52.112 [rest] Register -> INFO 024 REST client login...
> 15:09:52.114 [rest] Register -> INFO 025 Local data store for client loginToken: /var/hyperledger/production/client/
> 15:09:52.114 [rest] Register -> INFO 026 Logging in user 'diego' on REST interface...
> 15:09:52.114 [crypto] Login -> INFO 027 Registering client [diego] with name [diego]...
> 15:09:52.144 [crypto] getEnrollmentCertificateFromECA -> ERRO 028 [client.diego] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = "identity or token do not match"].

**Comment by joshhus** [comment]
Agree, thanks.
