### ISSUE TITLE
Unwanted viper 'feature'(?) : Configuration *prefixes* may be taken from the environment

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1205]
I wanted to quickly document a problem that I just experienced, in the event that this information may help others, or perhaps that someone might have time to investigate and fix this.

Seemly out of nowhere, the Go language tests stopped working for me. One particular set of tests kept coming back saying that the configuration variable 

```
peer.fileSystemPath
```

was not defined. I verified that the correct YAML file was being loaded which clearly defined this variable. I dumped viper's internal configuration map and saw the hierarchical definition as plain as day.

Long story short: It turns out that in certain cases (which I have not tried to understand), viper is looking at _prefixes_ of the configuration variables in the environment. The change that caused my problem was that I had defined an environment variable **PEER** (to point to the hyperldeger/fabric/peer  directory). For these particular tests, viper was finding **PEER** defined in the environment, and somehow this confused viper and it was unable to find peer.fileSystemPath in its configuration map. 

This caused me several hours of frustration that I would like to spare others who might innocently define **PEER**, **CHAINCODE**, **LEDGER** or any of the other top-level hierarchical names that appear in our YAML files.

**Comment by christo4ferris** [comment]
closing this one and tracking with #1309
