### ISSUE TITLE
Example of a chaincode implementing RBAC 

### ISSUE THREAD

**Issue by elli-androulaki** [hyperledger-archives/fabric#1207]
Labels: security, application layer
To be assigned to: @adecaro

**Comment by jeffgarratt** [comment]
Will review #1212 and look to remove go unit test and replace with behave test and simply take the chaincode only and not the yaml or test file.  @adecaro @srderson

**Comment by frankyclu** [comment]
@jeffgarratt for the record, the go test of the asset management chaincode sample only works in the first run, would require restarting image after each run

**Comment by christo4ferris** [comment]
@elli-androulaki closing this as I believe we have this now. Please reopen if you disagree.
