### ISSUE TITLE
Need help in setting up swagger-ui

### ISSUE THREAD

**Issue by PlamJ** [hyperledger-archives/fabric#1209]
We have been following instructions in this link: https://github.com/hyperledger/fabric/blob/master/docs/API/CoreAPI.md#to-set-up-swagger-ui, to setup a swagger-ui rest services. We have completed upto step 7, but getting error in step 8 i.e "go test -v -run TestServerOpenchain_API_GetBlockCount"
Error:
=== RUN   TestServerOpenchain_API_GetBlockCount
openchain.test: db/column_family.cc:412: rocksdb::ColumnFamilyData::~ColumnFamilyData(): Assertion `refs_.load(std::memory_order_relaxed) == 0' failed.
SIGABRT: abort
PC=0x7f8f66b5fcc9 m=0
signal arrived during cgo execution

goroutine 34 [syscall, locked to thread]:
runtime.cgocall(0xa64150, 0xc82020bb98, 0x10000c800000000)
    /opt/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82020bb60 sp=0xc82020bb30
github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb._Cfunc_rocksdb_close(0x1f8d620)
    github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb/_obj/_cgo_gotypes.go:610 +0x36 fp=0xc82020bb98 sp=0xc82020bb60
github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb.(_DB).Close(0xc8201e9580)
    /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/github.com/tecbot/gorocksdb/db.go:593 +0x78 fp=0xc82020bbe8 sp=0xc82020bb98
github.com/openblockchain/obc-peer/openchain/db.CreateDB(0x0, 0x0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db.go:90 +0x970 fp=0xc82020bd20 sp=0xc82020bbe8
github.com/openblockchain/obc-peer/openchain/db.(_TestDBWrapper).CreateFreshDB(0xc820128c7f, 0xc8201d41b0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/db/db_test_exports.go:51 +0x80 fp=0xc82020bda0 sp=0xc82020bd20
github.com/openblockchain/obc-peer/openchain/ledger.InitTestLedger(0xc8201d41b0, 0x16)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/ledger/ledger_test_exports.go:31 +0x31 fp=0xc82020bde8 sp=0xc82020bda0
github.com/openblockchain/obc-peer/openchain.TestServerOpenchain_API_GetBlockCount(0xc8201d41b0)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/api_test.go:183 +0x5e fp=0xc82020bf38 sp=0xc82020bde8
testing.tRunner(0xc8201d41b0, 0x154b4a8)
    /opt/go/src/testing/testing.go:473 +0x98 fp=0xc82020bf70 sp=0xc82020bf38
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82020bf78 sp=0xc82020bf70
created by testing.RunTests
    /opt/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x10316e8, 0x154b460, 0xf, 0xf, 0x1)
    /opt/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82013bee8, 0x0)
    /opt/go/src/testing/testing.go:515 +0x81
github.com/openblockchain/obc-peer/openchain.TestMain(0xc82013bee8)
    /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/api_test.go:39 +0x26
main.main()
    github.com/openblockchain/obc-peer/openchain/_test/_testmain.go:82 +0x114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /opt/go/src/runtime/asm_amd64.s:1998 +0x1

rax    0x0
rbx    0x7f8f6836d000
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x3d8d
rsi    0x3d8d
rbp    0x7f8f66ca9830
rsp    0x7ffe1a95e108
r8     0xfefefefefefefeff
r9     0xfefefefefefefeff
r10    0x8
r11    0x206
r12    0x1095358
r13    0x1096000
r14    0x1f88958
r15    0x1f88960
rip    0x7f8f66b5fcc9
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
exit status 2
FAIL    github.com/openblockchain/obc-peer/openchain    0.949s

**Comment by angrbrd** [comment]
Hi @PlamJ. This issue has been overlooked for a while unfortunately :-[... my apologies for that.

I am wondering if you are still facing this issue? I just tried stepping through the instructions at the link below and I am seeing the UT pass and create the required blocks in the local blockchain. Please let me know if you are still able to reproduce.

https://github.com/hyperledger/fabric/blob/master/docs/API/CoreAPI.md#to-set-up-swagger-ui

**Comment by srderson** [comment]
@PlamJ please re-open if you are still facing the issue. Thanks.
