### ISSUE TITLE
Can't query after successful deploy and invoke

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1218]
Description:

Deploying the default payload results in successful deploy, successful invoke, unsuccessful query

Steps to repro:
1. Build latest code
2. Register lukas
3. Send secure deploy
4.  Copy ID
5.  Send secure invoke
6.  Send secure query

Results:

An error message stating that could not decrypt query, then a timeout

Expected results:
[timeout ca.txt](https://github.com/hyperledger/fabric/files/232368/timeout.ca.txt)
[timeout 3 of 4.txt](https://github.com/hyperledger/fabric/files/232369/timeout.3.of.4.txt)
[timeout 2 of 4.txt](https://github.com/hyperledger/fabric/files/232371/timeout.2.of.4.txt)
[timeout 1 of 4.txt](https://github.com/hyperledger/fabric/files/232370/timeout.1.of.4.txt)

Query should be decrypted before timeout.

**Comment by tuand27613** [comment]
@RicHernandez2   how similar is this to #1185   ?

**Comment by RicHernandez2** [comment]
it looks very similar, I had to hack today's code to get it to run, peer was built in the peer directory before the go test -run BuildImage_Peer, but upon launching my command lines:

```
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -v /opt/logs/vp0:/go -p 5000:5000 hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.5:30303 -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=test_vp5 -e CORE_SECURITY_ENROLLSECRET=FfdvDkAdY81P -v /opt/logs/vp1:/go hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.5:30303 -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=test_vp6 -e CORE_SECURITY_ENROLLSECRET=QiXJgHyV4t7A -v /opt/logs/vp2:/go hyperledger-peer ./peer peer
docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 -e CORE_PEER_ID=vp3 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.5:30303 -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=test_vp7 -e CORE_SECURITY_ENROLLSECRET=twoKZouEyLyB -v /opt/logs/vp3:/go hyperledger-peer ./peer peer
```

I found that the peer executable was missing from the peer directory, so I built it, committed the change to the docker image, ran the 4 VPs, had trouble with 172.17.0.3, the autodetect on the first seemed to like 172.17.0.5, so I set that as the discovery node, then everything appeared to be running.

I was concerned that there were so many hacks that I had to do to get it up and running that I went to Ramesh's now finished script... it blew away the old images, downloaded the latest tested ones and I tried re-running the test, which is now passing.  Closing this bug as No Repro, possibly due to incomplete or incorrect setup of VPs.

Thanks!
