### ISSUE TITLE
README.md link to main.go needs new target

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#1222]
https://github.com/hyperledger/fabric
Under 2.0 Run: 
Encoded link for "main.go" text results in "page not found"
The target to the following URL is "page not found" - https://github.com/hyperledger/fabric/blob/master/main.go

**Comment by genggjh** [comment]
it was moved into peer subfolder, I will fix it.

**Comment by angrbrd** [comment]
I just tried this link and it seems that this has already been fixed. Closing.

**Comment by srderson** [comment]
PR #1226
