### ISSUE TITLE
Behave tests should detect and shutdown local running peer

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#1223]
Often we forget to shutdown the local running peer as part of the unit-tests, and behave tests result in errors. We should try to detect and shutdown the peer prior to running the behave tests.

**Comment by srderson** [comment]
I'd prefer that the unit tests not require a running peer. Possibly the tests that require such functionality should be moved into the behave tests.

**Comment by binhn** [comment]
@srderson ok, we need to investigate which unit-tests require peer and will report back here

**Comment by christo4ferris** [comment]
Agree that unit tests should not require a running peer.
