### ISSUE TITLE
Old rest calls were removed with no backwards compatibility

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1246]
Description:

Old deploy/\* REST calls were completely removed and replaced with /chaincode with no backwards compatibility (say a redirect from /deploy/invoke to /chaincode)

Results:

Old REST calls are completely gone

Expected results:

Perhaps a redirect or other transitional mechanism (A friendly error message?) when someone hits deprecated REST URLs.

**Comment by christo4ferris** [comment]
Agree, we should be having a more graceful deprecation policy.

**Comment by binhn** [comment]
@RicHernandez2 @christo4ferris  not sure what you guys talking about here.  If I read this correctly, these endpoints are deprecated (ie still there until next code release).  We also indicated that in the [document](https://github.com/hyperledger/fabric/blob/master/docs/API/CoreAPI.md#devops-deprecated):

```
    // The /devops endpoint is now considered deprecated and superceeded by the /chaincode endpoint
    router.Post("/devops/deploy", (*ServerOpenchainREST).Deploy)
    router.Post("/devops/invoke", (*ServerOpenchainREST).Invoke)
    router.Post("/devops/query", (*ServerOpenchainREST).Query)
```

Maybe something else?

**Comment by RicHernandez2** [comment]
Just retested with latest code, it's giving useful and helpful errors at the old REST API URLs, I kinda hacked together the version I had been testing with today... thanks!

![snakeeyes](https://cloud.githubusercontent.com/assets/17052305/14800148/e1be2940-0b0d-11e6-8f80-0060f77384ba.JPG)
