### ISSUE TITLE
Decryption error on deploy of asset_management example chaincode

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#1247]
On Vagrant/4VP/membersrvc/security enabled/privacy enabled

commit 4506910

deploy command:

> CORE_PEER_ADDRESS=vp0:30303 peer chaincode deploy -u test_user0 -l GOLANG -p github.com/hyperledger/fabric/examples/chaincode/go/asset_management -c '{"Function":"init", "Args": []}'

Fabric creates the chaincode container, chaincode then calls out a decryption error and fabric delete the container.

See line 1825 in the vp0_err.txt file.

**Comment by tuand27613** [comment]
attaching logs: 
[1247.zip](https://github.com/hyperledger/fabric/files/235180/1247.zip)

**Comment by adecaro** [comment]
@tuand27613, Unfortunately that is not the right way to deploy the asset management chaincode. In fact,  its init function requires that the metadata of the deploy transaction contains the certificate of the administrator. This cannot be specified using the CLI.

What is strange is that the chaincode should fail differently. If the metadata field is empty that the chaincode should raise the following error: "Invalid admin certificate. Empty.". I don't see it in the logs.

Btw, may you check what happens disabling confidentiality?

**Comment by adecaro** [comment]
Hi @tuand27613, I found the reason why we don't see the real reason why the chaincode is failing. 
Actually, when a chaincode tries to get a state that does not exist then the validator asks the crypto layer to decrypt an empty ciphertexts which is meaningless. Now this can be addressed on one of fronts, the validator or crypto layer side.

I pushed PR #1255 to address this at the crypto layer side. With the new code, I can finally see the error message that is coming from the chaincode that correctly reports that metadata is not set.

**Comment by tuand27613** [comment]
I tried with security enabled and privacy disabled and got the same error in the log
`[31m22:19:48.139 [chaincode] func1 -> ERRO 72d[0m [a9a5e38a]Got error (Decryption failed.) while decrypting. Sending ERROR`

@adecaro any way I can send in the deploy from cli or rest ?  I tried the asset-management_test but needed something that ran against an already running set of validating peers.

**Comment by adecaro** [comment]
Hi @tuand27613, let me point you to one of my branch where I show how to write an application that drive the asset management chaincode: https://github.com/adecaro/fabric/tree/asset_mgm_app

You will find the code at github.com\hyperledger\fabric\examples\chaincode\go\asset_management\app in the file app.go

**Comment by tuand27613** [comment]
@adecaro ,  I merged your ../examples/chaincode/go/asset-management/app code with hyperledger/master commit dcfae2a

everything built. I can run./app through login[ jim/lukas/diego], deploy, assign
query gave me this error which I think is because PR #1255 has not been merged yet ?

> 2016/04/27 20:18:09 Query....
> 2016/04/27 20:18:09 [client.jim] Get [1] certificates from the TCA...
> 2016/04/27 20:18:09 [client.jim] Getting TCA client...
> 2016/04/27 20:18:09 [client.jim] Dial to addr:[membersrvc:50051], with serverName:[tlsca]...
> 2016/04/27 20:18:09 [client.jim] TLS disabled...
> 2016/04/27 20:18:09 [client.jim] Dial to addr:[membersrvc:50051], with serverName:[tlsca]...done!
> 2016/04/27 20:18:09 [client.jim] Getting TCA client...done
> 2016/04/27 20:18:09 [client.jim] TCertIndex: [31 f3 4b 13 d3 a2 5b 70 09 00 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff].
> 2016/04/27 20:18:09 [client.jim] Sub index [0]
> 2016/04/27 20:18:09 [client.jim] Certificate [0] validated.
> 2016/04/27 20:18:09 [client.jim] Adding new Cert [30 82 02 7e 30 82 02 24 a0 03 02 01 02 02 10 49 73 48 f9 b0 8d 4b 2f 87 11 f4 01 c6 a9 b1 a5 30 0a 06 08 2a 86 48 ce 3d 04 03 03 30 29 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0c 30 0a 06 03 55 04 03 13 03 74 63 61 30 1e 17 0d 31 36 30 34 32 37 32 30 31 37 30 39 5a 17 0d 31 36 30 37 32 36 32 30 31 37 30 39 5a 30 29 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0c 30 0a 06 03 55 04 03 13 03 6a 69 6d 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48 ce 3d 03 01 07 03 42 00 04 c0 0f e1 f7 19 55 0d 23 cf aa a0 9a 3f 2b a8 b5 be 33 a5 b5 c6 d2 9a ac 26 fe c3 1c 3b 97 3a 64 99 0b 4b b7 6b f8 35 64 f3 59 79 e9 66 e1 8a ac 90 40 de f2 65 c9 55 4d 1b 4f 00 49 a2 51 49 58 a3 82 01 2c 30 82 01 28 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02 07 80 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 0d 06 03 55 1d 0e 04 06 04 04 01 02 03 04 30 0f 06 03 55 1d 23 04 08 30 06 80 04 01 02 03 04 30 0d 06 06 2a 03 04 05 06 0a 04 03 49 42 4d 30 1b 06 06 2a 03 04 05 06 0b 04 11 53 6f 66 74 77 61 72 65 20 45 6e 67 69 6e 65 65 72 30 4d 06 06 2a 03 04 05 06 07 01 01 ff 04 40 24 38 18 a9 e4 1a 0d 04 fb 3c d1 28 f9 66 39 f6 94 95 d6 20 90 ac 43 a3 d6 2d a3 22 1f 02 9d 5f 09 57 fb f0 2e e3 ec 90 c3 55 35 49 f4 d3 b6 76 10 3b 7a 1a 39 40 f0 53 38 51 8c 8c 0a 8c 2e 3e 30 4a 06 06 2a 03 04 05 06 08 04 40 f6 22 62 38 61 f6 48 00 b3 97 e1 98 e5 46 91 98 26 d3 33 a2 ac f7 33 2f 21 2c 8c 88 1d 1c 25 75 97 32 f8 ac b1 67 d6 5f 3e 18 ea cc e0 d9 96 c1 43 8a 64 35 b1 94 31 96 b8 78 7a ba c6 86 99 63 30 21 06 06 2a 03 04 05 06 09 04 17 63 6f 6d 70 61 6e 79 2d 3e 31 23 70 6f 73 69 74 69 6f 6e 2d 3e 32 23 30 0a 06 08 2a 86 48 ce 3d 04 03 03 03 48 00 30 45 02 21 00 fe 2b 17 bd 50 ba 77 a7 95 de 2a 84 fc 6a 7a e4 97 20 d7 f7 d1 43 c9 7f 6d 4e 0b 8f 94 43 3f ea 02 20 02 e0 3d 30 e8 cd 8e f0 5d a4 b9 06 ef 70 e5 22 65 13 54 7b 29 63 36 56 ff e8 42 bf 26 65 0c fa].
> 2016/04/27 20:18:09 [client.jim] Confidentiality protocol version [1.2]
> 2016/04/27 20:18:09 [client.jim] Using confidentiality protocol version 1.2
> 2016/04/27 20:18:09 [client.jim] Appending certificate [30 82 02 7e 30 82 02 24 a0 03 02 01 02 02 10 49 73 48 f9 b0 8d 4b 2f 87 11 f4 01 c6 a9 b1 a5 30 0a 06 08 2a 86 48 ce 3d 04 03 03 30 29 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0c 30 0a 06 03 55 04 03 13 03 74 63 61 30 1e 17 0d 31 36 30 34 32 37 32 30 31 37 30 39 5a 17 0d 31 36 30 37 32 36 32 30 31 37 30 39 5a 30 29 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0c 30 0a 06 03 55 04 03 13 03 6a 69 6d 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48 ce 3d 03 01 07 03 42 00 04 c0 0f e1 f7 19 55 0d 23 cf aa a0 9a 3f 2b a8 b5 be 33 a5 b5 c6 d2 9a ac 26 fe c3 1c 3b 97 3a 64 99 0b 4b b7 6b f8 35 64 f3 59 79 e9 66 e1 8a ac 90 40 de f2 65 c9 55 4d 1b 4f 00 49 a2 51 49 58 a3 82 01 2c 30 82 01 28 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02 07 80 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 0d 06 03 55 1d 0e 04 06 04 04 01 02 03 04 30 0f 06 03 55 1d 23 04 08 30 06 80 04 01 02 03 04 30 0d 06 06 2a 03 04 05 06 0a 04 03 49 42 4d 30 1b 06 06 2a 03 04 05 06 0b 04 11 53 6f 66 74 77 61 72 65 20 45 6e 67 69 6e 65 65 72 30 4d 06 06 2a 03 04 05 06 07 01 01 ff 04 40 24 38 18 a9 e4 1a 0d 04 fb 3c d1 28 f9 66 39 f6 94 95 d6 20 90 ac 43 a3 d6 2d a3 22 1f 02 9d 5f 09 57 fb f0 2e e3 ec 90 c3 55 35 49 f4 d3 b6 76 10 3b 7a 1a 39 40 f0 53 38 51 8c 8c 0a 8c 2e 3e 30 4a 06 06 2a 03 04 05 06 08 04 40 f6 22 62 38 61 f6 48 00 b3 97 e1 98 e5 46 91 98 26 d3 33 a2 ac f7 33 2f 21 2c 8c 88 1d 1c 25 75 97 32 f8 ac b1 67 d6 5f 3e 18 ea cc e0 d9 96 c1 43 8a 64 35 b1 94 31 96 b8 78 7a ba c6 86 99 63 30 21 06 06 2a 03 04 05 06 09 04 17 63 6f 6d 70 61 6e 79 2d 3e 31 23 70 6f 73 69 74 69 6f 6e 2d 3e 32 23 30 0a 06 08 2a 86 48 ce 3d 04 03 03 03 48 00 30 45 02 21 00 fe 2b 17 bd 50 ba 77 a7 95 de 2a 84 fc 6a 7a e4 97 20 d7 f7 d1 43 c9 7f 6d 4e 0b 8f 94 43 3f ea 02 20 02 e0 3d 30 e8 cd 8e f0 5d a4 b9 06 ef 70 e5 22 65 13 54 7b 29 63 36 56 ff e8 42 bf 26 65 0c fa].
> 2016/04/27 20:18:09 [client.jim] Appending signature [30 45 02 21 00 b5 59 be 92 d1 55 c9 8c d7 ed e0 7e a9 b8 7c 5a f1 bf 21 b6 2b 5d 95 e4 74 e1 c3 4e 1b 38 65 6b 02 20 62 f4 71 a8 03 e2 a0 e3 26 0a cf c7 99 e2 64 54 68 06 6d 0f 53 a7 6d b9 f0 68 b2 58 02 d3 fc a5].
> 2016/04/27 20:18:09 Resp [status:FAILURE msg:"Error:Failed to launch chaincode spec(Error starting container: no such image)" ]
> 2016/04/27 20:18:09 Query....done
> 2016/04/27 20:18:09 [client.jim] Failed decrypting query result [cipher: message authentication failed].
> 2016/04/27 20:18:09 Failed decrypting result [Decryption failed.]

**Comment by tuand27613** [comment]
Note that if you want to run @adecaro 's asset-management app with the 4vp docker environment, you need to edit ../examples/chaincode/go/asset-management/app/core.yaml to point CORE_PEER_ADDRESS to the validating peer and CORE_PEER_PKI_ECA/TCA/TLSCA_PADDR to the hostname of the membersrvc server

**Comment by adecaro** [comment]
@tuand27613 Yes, PR #1255 has been not merged yet. It will be merged soon.

Anyway, the error seems different: "Error:Failed to launch chaincode spec(Error starting container: no such image)". The validator failed in deploying the chaincode.

May you post the logs of the validators? Thanks.

**Comment by prjayach** [comment]
@adecaro Checked your code -- this is similar to the test you had. Is it possible to deploy asset_management.go using a REST call? How do we pass the admin certificate as metadata using a REST call (or is it done automatically)? Our app is in Java, so we will need REST -- we can't invoke NewChaincodeDeployTransaction directly.

**Comment by adecaro** [comment]
@prjayach that's not possible with the current REST APIs. The asset_management.go requires more complex interactions. 

A possible alternative solution would be to implement an asset_management service: a middle ware app to which your Java app submits action requests and that submits transaction to the fabric network.

The asset_management service can be just an extension of the app I have written. It accepts GRPC or REST calls and execute the submitted action requests.

**Comment by tuand27613** [comment]
@adecaro ,  #1255 was merged today.

I tried to re-run your asset-management app example but still ran into the decrypt error at the query step. Probably a configuration error on my part but can you take a look ?  Logs included here.

[1247_2.zip](https://github.com/hyperledger/fabric/files/247449/1247_2.zip)

**Comment by adecaro** [comment]
@tuand27613, please, may you set logging.crypto to debug? I see that there is a decryption error but I need debug logs. Thanks :)

**Comment by tuand27613** [comment]
Sorry @adecaro !  I keep forgetting logging_level.

New set of logs, including log of client app

[1247_3.zip](https://github.com/hyperledger/fabric/files/247512/1247_3.zip)

**Comment by muralisrini** [comment]
This seems to be relevant to #1049 as well where CreateTable issues a GetState on a non-existent key. Decrypt on that fails and throws the chaincode-handling to bail out due to an error from the fabric.

**Comment by adecaro** [comment]
@tuand27613, After some minor changes to the asset_management app, I noticed the following error:

[31m19:49:59.741 [dockercontroller] Deploy -> ERRO 355[0m Error building Peer container: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/asset_management && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/asset_management $GOPATH/bin/46ed085eb8ece7c9c4e002f93315d27b5db75e1a3359df6ae912d5e87316fbc5384059ab65fa664ce9db0b830493e2d0b6352626b30dd1a41cc974e48063aed8' returned a non-zero code: 1

The decryption error is only a side-effect.
@tuand27613, may you pull the latest version from my branch and try again to verify if you see the same error?
@muralisrini, please, may you give some feedback on this?

**Comment by muralisrini** [comment]
@adecaro : can you "go build" the asset management app and make sure it builds ? Please remove the exe from the asset_management dir after making sure it works.

**Comment by adecaro** [comment]
@muralisrini, great catch :)

Now I see the following:

[36m20:32:26.702 [crypto] getStateEncryptor1_2 -> DEBU 61b[0m [validator.test_vp0] Parsing transaction. Type [CHAINCODE_DEPLOY]. Confidentiality Protocol Version [1.2]
[36m20:32:26.704 [chaincode] encryptOrDecrypt -> DEBU 61c[0m []Payload before encrypt/decrypt: [10 15 65 115 115 101 116 115 79 119 110 101 114 115 104 105 112 18 9 10 5 65 115 115 101 116 24 1 18 9 10 5 79 119 110 101 114 16 5]
[36m20:32:26.705 [crypto] Encrypt -> DEBU 61d[0m [validator.test_vp0] Encrypting with counter [00 00 00 00 00 00 00 00].
[36m20:32:26.706 [chaincode] encryptOrDecrypt -> DEBU 61e[0m []Payload after encrypt/decrypt: [140 214 69 53 90 17 0 170 160 63 144 148 77 179 141 252 68 246 205 99 195 228 218 100 24 67 53 218 121 243 26 198 220 71 48 17 53 188 217 161 211 38 36 113 235 81 226 4 28 98 229 241 214 223 74 135 9 95 186 9 147 146 140 252 5 24 231 10 4 180 107 237 115 31 1 168 191 53 233 173 172 12 154 31 236 222 48 249 11 190 158]
[36m20:32:26.707 [state] Set -> DEBU 61f[0m set() chaincodeID=[12c45687bf13a338eae91ea7ca3caf39c167ead8fe1cb7f2a2e598dc51b2ea5b1d06be79a9bafb87f1cf224492258188d2080969d1f8c4c88ab18f7e685583c1], key=[15AssetsOwnership], value=[[]byte{0x8c, 0xd6, 0x45, 0x35, 0x5a, 0x11, 0x0, 0xaa, 0xa0, 0x3f, 0x90, 0x94, 0x4d, 0xb3, 0x8d, 0xfc, 0x44, 0xf6, 0xcd, 0x63, 0xc3, 0xe4, 0xda, 0x64, 0x18, 0x43, 0x35, 0xda, 0x79, 0xf3, 0x1a, 0xc6, 0xdc, 0x47, 0x30, 0x11, 0x35, 0xbc, 0xd9, 0xa1, 0xd3, 0x26, 0x24, 0x71, 0xeb, 0x51, 0xe2, 0x4, 0x1c, 0x62, 0xe5, 0xf1, 0xd6, 0xdf, 0x4a, 0x87, 0x9, 0x5f, 0xba, 0x9, 0x93, 0x92, 0x8c, 0xfc, 0x5, 0x18, 0xe7, 0xa, 0x4, 0xb4, 0x6b, 0xed, 0x73, 0x1f, 0x1, 0xa8, 0xbf, 0x35, 0xe9, 0xad, 0xac, 0xc, 0x9a, 0x1f, 0xec, 0xde, 0x30, 0xf9, 0xb, 0xbe, 0x9e}]
panic: State can be changed only in context of a tx.
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5b8397]

goroutine 100 [running]:
panic(0xd2fc80, 0xc82001a0a0)
    /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/core/chaincode.(_Handler).enterBusyState.func1.1(0xc820221980, 0xc820131900, 0xc8200d3be8)
    /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:947 +0x307
panic(0xbca1a0, 0xc8201aed80)
    /opt/go/src/runtime/panic.go:426 +0x4e9
github.com/hyperledger/fabric/core/ledger/statemgmt/state.(_State).Set(0xc8203d2640, 0xc820221a80, 0x80, 0xc820363d20, 0x11, 0xc8202b5c20, 0x5b, 0x60, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/ledger/statemgmt/state/state.go:146 +0x2bd
github.com/hyperledger/fabric/core/ledger.(_Ledger).SetState(0xc8203f00c0, 0xc820221a80, 0x80, 0xc820363d20, 0x11, 0xc8202b5c20, 0x5b, 0x60, 0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/ledger/ledger.go:213 +0x8a
github.com/hyperledger/fabric/core/chaincode.(_Handler).enterBusyState.func1(0xc82028dc00, 0xc820221980, 0xe505a0, 0x8)
    /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:978 +0x1364
created by github.com/hyperledger/fabric/core/chaincode.(*Handler).enterBusyState
    /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/handler.go:1033 +0x53

**Comment by adecaro** [comment]
@tuand27613 @muralisrini Good news: I found the problem. The UUID were non set properly. Now it works :)
@tuand27613, please, may you pull the latest version of branch and test again?

**Comment by cophey** [comment]
@adecaro is there some way to test asset_management Chaincode by CLI or REST or code?i got the same error "Invalid admin certificate. Empty."
thanks!

**Comment by adecaro** [comment]
Hi @cophey, unfortunately no. That's the reason why we are developing a client-sdk that will allow to do that. In the meantime, what I have in my branch is essentially an application that bootstraps a non-validating peer and can handle directly more complex interactions with the fabric network. If you like, you can have a look at it by cloning my repo git@github.com:adecaro/fabric.git and checking out branch asset_mgm_app. Everything is under the asset_management chaincode example.

**Comment by cophey** [comment]
@adecaro sorry,i did not find some app about asset_management under the asset_management chaincode example.can you say in detail?Thank you very much.
![image](https://cloud.githubusercontent.com/assets/7555270/15038166/fa2dc814-12d3-11e6-914e-4820a8f1a27d.png)

**Comment by cophey** [comment]
@adecaro I want to deploy/invoke/query the asset_management,but I got err-"Invalid admin certificate. Empty."

**Comment by adecaro** [comment]
Hi @cophey, sorry, my description was not clear enough.

Anyhow, I just submitted PR #1360 that shows how to write an application that deploys, invokes and queries the asset_management chaincode.

As I said before, the current CLI and REST Api do not allow to drive the asset_management chaincode in the proper way. That's the reason why you receive that error and the reason why I submitted the PR :)

The PR contains also two readme files that describe the asset management chaincode and the associated app. Please, may you give a look at it? Any feedback is welcome :)

**Comment by cophey** [comment]
@adecaro I see the app folders and I'll read it.Thanks very mach!

**Comment by adecaro** [comment]
Hi @tuand27613, I guess this issue can be closed now, right? :)

**Comment by tuand27613** [comment]
agreed

**Comment by rishabh1102** [comment]
What is the right way to deploy the asset management chaincode?

**Comment by romanga** [comment]
Has anyone succeeded in deploying running this example on bluemix? I ran into few issues
1. it can't find go-logging package
2. Init function requires that the metadata of the deploy transaction contains the certificate of the administrator and I found no way to pass that in the bluemix API.
