### ISSUE TITLE
build logs need to be less noisy on pass

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1260]
Currently the build logs everything to stdout which creates an enormous build log for every build. We should output the detail to a temporary file and dump it only on a failed build/test.

**Comment by christo4ferris** [comment]
suggested change for behave in .travis.yml:
behave -D logs=Y -o tmp.out || cat tmp.out
would suppress the verbose output and only print the log on a failed test

**Comment by bcbrock** [comment]
Is it possible in this CI environment to pull out the peer logs for failing tests and cache them somewhere temporarily? We don't want to print them (too big), but we do need to be able to examine them to diagnose failures.

**Comment by christo4ferris** [comment]
@bcbrock yes, I asked that we look into using object store (SL or Bluemix) which is openstack swift API. @rameshthoomu did @bmos299 discuss this with you?

**Comment by bmos299** [comment]
@bcbrock @christo4ferris @rameshthoomu This is being worked.  The Travis CI has a setting to send logs (raw logs from travis and tar'd container logs) to S3.   However, this only works for a merge request.  It does not support PRs, since the PR is from the any user and can flood S3.  Ramesh is investigating SL and Bluemix for other options.

**Comment by christo4ferris** [comment]
@bmos299 @rameshthoomu we should have a rolling object store solution that prunes logs older than X days, where X is configurable regardless of which one we choose. was just having a conversation about storage costs for CI with another project. It will be critical that a) we have a solution that the project is funding (LF) and is budgeted, and b) that we can aggressively keep in check by pruning. IMO, we should also limit log storage to failed builds. I think that LF also has existing capability for other projects that we might borrow the approach.

**Comment by bmos299** [comment]
@cbf Thanks.

**Comment by srderson** [comment]
PR #1318
