### ISSUE TITLE
Test "beautiful docs" GitHub doc display option

### ISSUE THREAD

**Issue by joshhus** [hyperledger-archives/fabric#1262]
Need a dev volunteer to help me build the "beautiful docs" feature in GitHub today ... 
https://github.com/beautiful-docs/beautiful-docs  ... 
It promises "beautiful" output for our .md GitHub doc files.

GitHub
beautiful-docs/beautiful-docs
beautiful-docs - A beautiful way to read documentation

Example output: 
https://raw.githubusercontent.com/beautiful-docs/beautiful-docs/master/docs/screenshot.png (81KB)

**Comment by christo4ferris** [comment]
@joshhus are there any live examples you can cite? Also, what assistance specifically are you seeking?

**Comment by joshhus** [comment]
Don't know. Javascript.

**Comment by JonathanLevi** [comment]
Happy to assist.

**Comment by joshhus** [comment]
The docs that we want to test this "beautiful docs" display format for are here: https://github.com/hyperledger/fabric/tree/master/docs

**Comment by christo4ferris** [comment]
@joshhus I don't believe any Javascript is required. The manifest is in JSON which is pretty straight forward. I can help if you get stuck. @JonathanLevi thanks for lending a hand, we do appreciate it!

**Comment by joshhus** [comment]
JavaScript Object Notation is more than I have in my toolbelt right now. Thanks @JonathanLevi !

**Comment by JonathanLevi** [comment]
NP. I just quickly ran bfdocs  and beautiful-docs fails at the moment if the markdown (e.g., README.md) does not have the structure it expects.

For example, https://raw.githubusercontent.com/hyperledger/fabric/master/README.md needs to also have a 'top-level' project name (/an item beginning with a single '#' prior to the '## Incubation Notice')

If you don't mind, I can create a (minor) issue and update these .md files with the top-level titles and/or whatever else is expected. Shouldn't cause any harm anyway, regardless of whether or not we choose to go ahead with beautiful-soup.

**Comment by christo4ferris** [comment]
@JonathanLevi yes, please! Thanks

**Comment by joshhus** [comment]
Yes @JonathanLevi thanks. Where are you at with this? LMK so I can step in also ... Note the single # text could be "Hyperledger Project" or whatever @christo4ferris would like to see; the same on every page for now. Is the README.md the only failure?

**Comment by joshhus** [comment]
Jonathan to update here later.

**Comment by joshhus** [comment]
Jonathan and I did a Google hangout yesterday. We've gotten our .md. to .rst. Now need to go from .rst to Sphinx to try that output. (Comparing Sphinx to Beautiful Docs). Help still wanted! 
(Note:  http://www.sphinx-doc.org/en/stable/)

**Comment by joshhus** [comment]
http://www.sphinx-doc.org/en/stable/

**Comment by JonathanLevi** [comment]
We played around with [beautiful-docs ](https://github.com/beautiful-docs/beautiful-docs) and quickly learned the following:
- It is not very forgiving if the markdown structure is not as it expects (e.g., files that didn't begin with H1 caused exceptions and errors, etc)
- We are under the impression that it is not actively developed/updated. E.g., as of this writing [Latest commit 84fcf79 on Jan 3, 2015] and unfortunately, even the website the project refers to [Checkout beautifuldocs.com for an example], does not work (anymore)
- Even after "fixing" Fabric's ".md" files locally and generating some static htmls, it still seemed to have required some more tweaking and more formatting and styling.

Unless there are strong supporters for this, we will be looking at other frameworks.

**Comment by joshhus** [comment]
@JonathanLevi and @joshhus are looking at Python / Sphinx.

**Comment by joshhus** [comment]
Volunteers always welcome!

**Comment by ijmitch** [comment]
Did you consider gitbook?
