### ISSUE TITLE
golint warnings in peer/main.go

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1266]
should fix golint warnings in main.go

**Comment by psaradhi** [comment]
I am working on this request and submitted a pull request -- Pardha Vishnumolakala

**Comment by christo4ferris** [comment]
@psaradhi, I did that yesterday... was just waiting on it being merged. Apologies for not making it more obvious, but if you look above under the first comment, you will note that I referenced this issue from a PR. However, thanks so much for your effort. I will close my PR and defer to yours.

**Comment by srderson** [comment]
These have been resolved
