### ISSUE TITLE
Could you use github mirror to replace golang.org to survive us who are in china

### ISSUE THREAD

**Issue by GrapeBaBa** [hyperledger-archives/fabric#1271]
Hi
As we have a GFW in china, we suffer this issue. Could you use github golang mirror to replace go get directly?
`==> default: + go get github.com/kardianos/govendor
==> default: + go get github.com/golang/lint/golint
==> default: package golang.org/x/tools/go/gcimporter15: unrecognized import path "golang.org/x/tools/go/gcimporter15" (https fetch: Get https://golang.org/x/tools/go/gcimporter15?go-get=1: dial tcp 216.58.217.49:443: i/o timeout)`

**Comment by JonathanLevi** [comment]
Hi @GrapeBaBa. You probably meant to 'save or assist/help to survive' ;-)

I'm not typing from China at the moment, but can you please tell me if you can access this site: https://gopm.io/download ?

**Comment by GrapeBaBa** [comment]
yes

**Comment by JonathanLevi** [comment]
Great! While I don't know enough about the cryptographic export/usage restrictions, etc... I believe that's up to the user [=you] to comply with the local/legal requirements, can you try one of these 2 suggestions?

https://github.com/northbright/Notes/blob/master/Golang/china/get-golang-packages-on-golang-org-in-china.md

[Written both in English and Chinese - which I cannot read, unfortunately! ;-)]

**Comment by GrapeBaBa** [comment]
@JonathanLevi Thank. I think this workaround can help me, I will close this issue.

**Comment by zuochuanmin** [comment]
I also encountered this issue. It's absolutely inconvenient.
