### ISSUE TITLE
we should enforce the contribution guidelines

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1284]
see https://github.com/hyperledger/fabric/blob/master/README.md#coding-golang-

we should be running golint and go vet in the CI build and flagging PRs that aren't conforming. 

Would advise we do so after we transition to Jenkins @bmos299

**Comment by JonathanLevi** [comment]
I, too, like the "treat warnings as errors" approach. Otherwise, it may be difficult to allow only X (for example) lint issues, X \neq 0 (e.g., "oh, we all know about these X acceptable lint warnings").

Better/simpler not to allow any deviation from the guidelines at all.

**Comment by bmos299** [comment]
Sure.   All enterprise grade products I have worked on classify build warnings as a failure.  Adding @rameshthoomu to the issue.

**Comment by bcbrock** [comment]
I would add **gofmt** to the list as well: Check that diff of file and 'gofmt file' is null for all changed Go files.

**Comment by christo4ferris** [comment]
@bcbrock yes, agree

**Comment by christo4ferris** [comment]
closing, we have this in place
