### ISSUE TITLE
many golint and go vet warnings in fabric/membersrvc/ca

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#1286]
fabric/membersrvc/ca contains two pages of golint and vet warnings. I'm willing to do a PR to address them but concerned that there may be active work on this package and that whomever is working it should address this in their PR.

**Comment by JonathanLevi** [comment]
While we're at it, can somebody please assign this to me? Will do it one file at a time.

**Comment by srderson** [comment]
Is it possible to run golint and vet in the CI pipeline? Sometimes they give false positives, but a list of warnings would help with review.

**Comment by christo4ferris** [comment]
@srderson yes, it is possible... agree that there can be false positives. I wonder if it can be done as informative (eg not fail the build). I'll investigate.

**Comment by christo4ferris** [comment]
@JonathanLevi it's yours!

**Comment by JonathanLevi** [comment]
As discussed, we waited with these until the end of Sprint 5 of last week. Currently there are 349 lint errors, for the interested/avid reader, we enclose the output here [2016-05-16_membersrvc_lint_errors.txt](https://github.com/hyperledger/fabric/files/268588/2016-05-16_membersrvc_lint_errors.txt)

To minimize intervention, will work to tackle them a file at a time adopting @christo4ferris's approach.

**Comment by JonathanLevi** [comment]
Following

``````
vagrant@hyperledger-devenv:v0.0.9-048fc48:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca$ git log -1
commit cb011329cd3ef5715d36eb0dff96ffad59de642c
Merge: 35e7f3e 55c9175
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Tue May 31 20:37:09 2016 -0400

    Merge pull request #1669 from JonathanLevi/issue-1558-go-vet

    Issue 1558 Fix go vet issues in fabric/membersrvc/ca```
``````

Executing:

```
vagrant@hyperledger-devenv:v0.0.9-048fc48:/opt/gopath/src/github.com/hyperledger$ golint ./fabric/membersrvc/ca/... | wc -l
0
vagrant@hyperledger-devenv:v0.0.9-048fc48:/opt/gopath/src/github.com/hyperledger$ go vet ./fabric/membersrvc/ca/... | wc -l
0
```

**Comment by JonathanLevi** [comment]
@christo4ferris, given the above, please let me know if you are OK with me closing this issue, as I believe that `membersrvc` does not have any `golint` or `go vet` issues anymore.

**Comment by christo4ferris** [comment]
closing, thanks everyone for pitching in to clean this up!

**Comment by JonathanLevi** [comment]
Thank you @christo4ferris. Yup, especially thanks to @srderson and @ghaskins for the quick turnarounds and lengthy discussions regarding the various `golint` and `go vet` fixing approaches, making sure that `membersrvcs` is not anymore the worst offender.
