### ISSUE TITLE
Use a 'seed' in the PRNGs/cryptographic layer

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1293]
Towards a more reproducible cryptographic layer behavior/interoperability, we should probably add the ability to define the 'random' seed used in the PRNGs and put together a few tests for checking this.

 This will be useful for reproducibility and better test-ability.

**Comment by JonathanLevi** [comment]
@christo4ferris et al., please feel free to assign me to this, if you will.

**Comment by christo4ferris** [comment]
@JonathanLevi is this still relevant or can it be closed?

**Comment by JonathanLevi** [comment]
Hi @christo4ferris: Yes, relevant more than ever actually... thanks for assigning and asking.

I will try to address this (at least for the AESCBC) for this week's SF Hackathon!

**Comment by JonathanLevi** [comment]
Closing this and will track as part of https://jira.hyperledger.org/projects/FAB.
