### ISSUE TITLE
2 VPs panic on Query, manual build

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1294]
Description:  Building manually as described in bug #1243, the CA comes up, the VPs come up with mixed results, login of lukas succeeds, then he deploys, invokes, and queries, that's when two of the 4 VPs panic and go down

Logs:

[panic on query 1 of 4.txt](https://github.com/hyperledger/fabric/files/241044/panic.on.query.1.of.4.txt)
[panic on query 2 of 4.txt](https://github.com/hyperledger/fabric/files/241046/panic.on.query.2.of.4.txt)
[panic on query 3 of 4.txt](https://github.com/hyperledger/fabric/files/241047/panic.on.query.3.of.4.txt)
[panic on query 4 of 4.txt](https://github.com/hyperledger/fabric/files/241045/panic.on.query.4.of.4.txt)

**Comment by tuand27613** [comment]
looking through the logs,  I see one peer started with name "jdoe", one peer started with name "vp3" and two peers started with name "vp2".

Since #756 isn't merged yet,  can you retry with names vp0/1/2/3  ?

**Comment by RicHernandez2** [comment]
I'm on it...

**Comment by RicHernandez2** [comment]
Dead on, I was relying on a text file with the CLIs and there was a duplicate commandline for vp2, but the vp0 thing, I had to make a change in the core.yaml file to rename the peer id to vp0 (from vp) and I had to change the membersrvc.yaml from vp to vp0, everyone who runs this with the default settings of vp as the peer ID will run into this problem, can we change the default peer id in the core.yaml and membersrvc.yaml files to vp0 instead of vp?

**Comment by tuand27613** [comment]
I'm a broken record ... fixed with #756 ( which I should working on instead of trolling github :) )

**Comment by RicHernandez2** [comment]
Root cause verified, closing.
