### ISSUE TITLE
Query fails on security enabled pbft classic

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1296]
Description:

Now that I have my commandlines squared away, I rebuilt the image by the book and on a VP0/1/2/3 set, I was able to login lukas, deploy, invoke on the TID and when I tried to query it failed...

Logs:

[qf 1 of 4.txt](https://github.com/hyperledger/fabric/files/241265/qf.1.of.4.txt)
[qf 2 of 4.txt](https://github.com/hyperledger/fabric/files/241264/qf.2.of.4.txt)
[qf 3 of 4.txt](https://github.com/hyperledger/fabric/files/241263/qf.3.of.4.txt)
[qf 4 of 4.txt](https://github.com/hyperledger/fabric/files/241266/qf.4.of.4.txt)

**Comment by tuand27613** [comment]
I'm seeing this error in the vp0 log
`18:55:56.030 [devops] getChaincodeBytes -> DEBU 1bc5 Received build request for chaincode spec: type:GOLANG chaincodeID:<path:"github.com/hyperledger/fabric/examples/chaincode/go/ndt/nondet_example02" > ctorMsg:<function:"init" args:"a" args:"1000" args:"b" args:"2000" > secureContext:"lukas" confidentialityLevel:CONFIDENTIAL
18:55:56.054 [devops] Deploy -> ERRO 1bc6 Error deploying chaincode spec: type:GOLANG chaincodeID:<path:"github.com/hyperledger/fabric/examples/chaincode/go/ndt/nondet_example02" > ctorMsg:<function:"init" args:"a" args:"1000" args:"b" args:"2000" > secureContext:"lukas" confidentialityLevel:CONFIDENTIAL

 error: Path to chaincode does not exist: github.com/hyperledger/fabric/examples/chaincode/go/ndt/nondet_example02
18:55:56.054 [rest] processChaincodeDeploy -> ERRO 1bc7 Error when deploying chaincode: Path to chaincode does not exist: github.com/hyperledger/fabric/examples/chaincode/go/ndt/nondet_example02`

The other logs say the chaincode container build return with rc=1

**Comment by RicHernandez2** [comment]
Problem with the example chaincode, closing.
