### ISSUE TITLE
Timeout multiplied by Millisecond at 2 places

### ISSUE THREAD

**Issue by mrshah-at-work** [hyperledger-archives/fabric#1299]
The timeout is multiplied by time.Millisecond at 2 places as mentioned below, resulting in a huge timeout

https://github.com/hyperledger/fabric/blob/master/peer/main.go#L712

https://github.com/hyperledger/fabric/blob/189e0db0e377ef8f40160fc0eac9740f11134716/core/chaincode/chaincode_support.go#L123

**Comment by mastersingh24** [comment]
is these any reason why no one has fixed this?  we'll submit a fix and PR for this, but just wondering why this was never picked up.  Basically this ends up with the default timeout being 277h46m40s rather than 1s
