### ISSUE TITLE
There are 3 loggers logging as the "chaincode" module

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1303]
Line 53 of fabric/core/chaincode/handler.go defines 'chaincodeLogger'
Line 41 of fabric/core/chaincode/chaincode_support.go defines 'chaincodeLog'
Line 47 of fabric/core/chaincode/shim/chaincode.go defines another 'chaincodeLogger' for the shim

~~1) I Suggest having the Go shim log as the "shim" module. Since the shim logger is in the 'shim' package, technically it is required to have its own logger, but it might be more informative to know its messages were coming from the shim.~~

2) The other 2 loggers are both in the 'chaincode' package so this is a redundancy. Of these, the 'chaincodeLogger' looks like to one to eliminate as it is only used a few times.

There are also 2 Loggers logging as the "container" module, but technically they are in different packages, and this probably makes sense.

**Comment by bcbrock** [comment]
On second thought, 1) above is not necessary. I will fix 2)  along with a PR I will soon submit that addresses #618.

**Comment by christo4ferris** [comment]
@bcbrock thanks for the refactor
