### ISSUE TITLE
Tabs in YAML files

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1308]
Tabs are forbidden to be used as indentation in YAML files. They cause the Go YAML parser to barf.

My test environment uses a Tcl-based YAML parser, and this parser also barfs if it finds tabs outside of comments or quoted strings.

Can we agree to disallow tabs anywhere in a YAML file, and have the CI environment check this ( @christo4ferris  @rameshthoomu )?

This issue is being prompted by tabs appearing in the latest copy of membersrvc/membersrvc.yaml

**Comment by christo4ferris** [comment]
+1

**Comment by binhn** [comment]
would this help https://gist.github.com/eevee/6721177 ?

**Comment by bcbrock** [comment]
The mechanism documented at Binh's link would work, subject to many caveats documented there. The most onerous to me being that 1) all developer's would have to modify their GIT environments in a specific way; 2) If you create a file with tabs it may look different when checked in than it does when you first create it, because the method fixes tab stops at N spaces, whereas your editor may be using M spaces. 

So I still think it is easier overall to reject certain types of files with tabs. {Interesting to note that 'gofmt' insists on using tabs for indentation}

@andresgaragiola - I see that you are "to blame" for adding tabs to membersrvc.yaml. Since I'm not sure if you were trying for something aesthetic like column alignment, would you mind submitting a PR that removes the tabs from membersrvc/membersrvc.yaml?

**Comment by christo4ferris** [comment]
closing as this seems to be resolved by #1480
