### ISSUE TITLE
"Writing Chaincode" section in README

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#1311]
This section ([link](https://github.com/hyperledger/fabric#writing-chaincode-)) doesn't actually contain any instructions or pointers as to how to write chaincode.

**Comment by kchristidis** [comment]
We should be linking to the "[How to Write Chaincode](https://github.com/IBM-Blockchain/learn-chaincode)" page.

**Comment by christo4ferris** [comment]
@kchristidis are you offering to write that up, or point to examples that could be emulated?

**Comment by kchristidis** [comment]
@christo4ferris As far as I can tell there is [a good enough write-up out there](https://github.com/IBM-Blockchain/learn-chaincode) but it belongs to a different repo. I can create PR linking to it if need be.

**Comment by joshhus** [comment]
Can we link from hyperledger to ibm-blockchain, per open source procedures? @nickgaski was working on related content for Bluemix.

**Comment by christo4ferris** [comment]
@mastersingh24 and I have discussed transferring some of the ibm-blockchain examples to Hyperledger. I am also working on a containerized approach to developing chaincode that might integrate these examples.
