### ISSUE TITLE
Question about git tag policy and build automation

### ISSUE THREAD

**Issue by jeremyeder** [hyperledger-archives/fabric#1322]
Hi -- 

Travis and Vagrant files for Fabric currrently have references to a "version".
https://github.com/hyperledger/fabric/blob/master/devenv/Vagrantfile#L33
https://github.com/hyperledger/fabric/blob/master/.travis.yml#L37

These are hard-coded.  Is there a way to make those variables that are based on the current git tag, so that build artifacts (currently we have a packer-based build tool-chain) can be automatically tied back to their specific Fabric tag/origin?

For example:  IBM/Fabric maintainers would create a new tag, and the new tag would trigger automatic rebuilds (well, at least dockerhub supports this).

@hyperledger/fabric-maintainers @ghaskins

**Comment by christo4ferris** [comment]
+1 to making this a function of a git tag

**Comment by ghaskins** [comment]
+1

**Comment by christo4ferris** [comment]
we've adopted a versioning and labeling strategy based on semver. closing this
