### ISSUE TITLE
Travis failing with unit-test platforms/car

### ISSUE THREAD

**Issue by ghaskins** [hyperledger-archives/fabric#1326]
A discrepancy between travis/vagrant provisioners coupled with a bug providing a false positive against unit-test failures allowed PR #1250 to be merged without noticing that the unit-tests were failing under the Travis environment.  The unit-test masking bug was later fixed, which caused any subsequent runs to be (correctly) reported as failing.  To fix for real, we will need to align the travis provisioner more closely with vagrant to reduce the likelihood of reoccurance

**Comment by ghaskins** [comment]
@christo4ferris @rameshthoomu

**Comment by bcbrock** [comment]
@ghaskins - This platforms/car test is also failing in my non-vagrant environment. Maybe #1329 should be generalized to never run the test unless specifically requested, or this directory should be removed altogether from the Go tests.

**Comment by ghaskins** [comment]
@bcbrock I am open to that, but I suspect we'd be papering over a broader issue: environmental prerequisites not being met within your chosen environment.  Without seeing your error logs, Im guessing you are either seeing it complaining about protoc-gen-go or chaintool binaries not being found? We probably need to find a more general solution or I fear this will keep happening over and over as more chaincode environments and other dependency driving forces are added in the future.  For now, perhaps the best solution is to invert the logic:  rather than exclude travis, I will only run the test under vagrant.

**Comment by bcbrock** [comment]
Yes, first I has to install protoc-gen-go, then figure out what "chaintool" was and get it on the path, then install java. Now it looks like you are building a Docker container and assuming that the system java executable exists in /bin?  (Mine doesn't) I would agree with your "papering over" comment if chaintool was accepted as a permanent part of the hyperledger/fabric, but it seems to be an experiment - e.g., you checked in the binary (Java JAR) instead of the source code plus build scripts. Is java only required inside the chaincode container or in general for this to work?

I agree we need to have some guidelines on how many external dependencies we want to have in the core verification suite. Java seems reasonable to me if it can be brought in in a portable way.

The current fail:

```
2016/05/03 14:36:55 Failed Chaincode docker build:
Step 1 : FROM openblockchain/baseimage
 ---> 13359bc4b3b5
Step 2 : COPY bin/* /usr/local/bin/
 ---> 002e2d97f48d
Removing intermediate container d62fa566ac39
Step 3 : COPY package.car /tmp/package.car
 ---> bbad0879f0ad
Removing intermediate container 818d7ecf8df9
Step 4 : RUN chaintool buildcar /tmp/package.car -o $GOPATH/bin/104971862e07f509d491fd457c5de115d044df95efb61433bdd117082c2b51435f351ca8366b789121495e028e29ec18067b8b389d4e422c9c90a12c17a605a9 && rm /tmp/package.car
 ---> Running in 2ffb8d0fe6ae
/usr/local/bin/chaintool: 1: exec: java: not found

--- FAIL: TestCar_BuildImage (78.64s)
    car_test.go:40: Error building Chaincode container: Error building Chaincode container: The command '/bin/sh -c chaintool buildcar /tmp/package.car -o $GOPATH/bin/104971862e07f509d491fd457c5de115d044df95efb61433bdd117082c2b51435f351ca8366b789121495e028e29ec18067b8b389d4e422c9c90a12c17a605a9 && rm /tmp/package.car' returned a non-zero code: 127
```

**Comment by ghaskins** [comment]
@bcbrock your comment is astute, I was speaking generally about the disconnect we have right now with non-vagrant, not specifically to the chaintool mod.  (apologies, I thought the PR would go through more discussion before merging...i still need to write up a proposal for where the code should go like the one you submitted earlier today).

Anyway, the _intent_ there was that if an environment was setting $PATH to include ./devenv/tools and using ./scripts/provision/docker.sh to build, it should all work to make your environment support what was needed.

Part of the challenge is we have one dynamic that wants everything as neatly packaged as possible (for simplicity when people want something to "just work" without explicit provisioning) and another that wants it to remain flexible for tweaks to be made for those who need to tinker (e.g. install JRE or update rocksdb version).  The former leans towards pushing everything to a repository (like dockerhub) and the latter leans towards JITing everything at the last minute.  The current setup is a hybrid which seems to be annoying both sides more than anything right now ;)

I agree we need to do a better job of incorporating non-vagrant envs, as well as communicating when requirements have changed.  I know people would love to see this work as simply as "git pull && go build" but I am not sure that is entirely realistic given all the moving parts involved (such as reliance on docker for isolation, protobuf tooling, etc).  Chaintool/JRE is just the latest example of the same phenomenon.  Until external dependencies are somehow encapsulated in a packaging mechanism that makes all parties happy, people are going to need to understand that the environment that surrounds the fabric needs to be kept in sync.  For anyone that works within vagrant, this happens naturally today because of the coherence we get with co-resident configuration within git .  For other environments, there is more work to be done.

We have started to move in this direction with the notion of the scripts in ./scripts/provision.  There are probably further improvements that could be made such as moving to a declarative configuration rather than an imperative script that would help reconcile a customized environment such as yours.  However, any level of improvement here would likely still need to be met with a workflow that incorporates that mechanism on a regular basis (ideally any time your git SHA is moved).  To that point, if you have ideas on any of this I would love to hear them.

**Comment by ghaskins** [comment]
@bcbrock I forgot to address your question about JRE availability.  From a core operational perspective, it is required in the docker container that builds CAR chaincode which runs in the context of a deploy at a VP.  It is also required anywhere someone would be developing chaincode via chaintool.

**Comment by ghaskins** [comment]
@bcbrock Also note, I do not believe I have any hard coded assumptions about the location of the JRE, only that it ends up on the $PATH.

**Comment by ghaskins** [comment]
I believe this issue is now fixed
