### ISSUE TITLE
protoc-gen-go can be installed from a package

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1334]
I notice that the setup.sh script that sets up Vagrant installs the Go protobug compiler from source. I don't use Vagrant, but this may not be necessary. Ubuntu provides a 'golang-goprotobuf-dev' package that includes  protoc-gen-go.

**Comment by mastersingh24** [comment]
@bcbrock - I think the issue with using the OS-specific packages is that they may be down level in terms of protocol buffer support.  Not sure about the package you mention, but it might not support PB 3.x

**Comment by ghaskins** [comment]
Related to down-level, note that what the script does now is it installs whatever was already coupled to the project via the vendoring mechanism, which is about as precise as you can be.  We would need to be careful about breaking that relationship.

**Comment by bcbrock** [comment]
@ghaskins I may have been thinking abut something else. I thought in the past it was quite time consuming to build the protobuf compiler from source. Is that no longer done?

**Comment by ghaskins** [comment]
@bcbrock there are two parts:
- protoc: this is expensive and performed at baseimage creation (https://github.com/hyperledger/fabric/blob/master/devenv/baseimage/scripts/common/setup.sh#L74)
- protoc-gen-go: this is relatively fast, and performed (today) by vagrant-up (https://github.com/hyperledger/fabric/blob/master/devenv/setup.sh#L12)

When you said "protoc-gen-go" I assumed you were referring to the latter, but now I see perhaps you just meant protoc in general.

**Comment by ghaskins** [comment]
Sorry, you just said "Go protobuf compiler" which I took to be the protoc-gen-go plugin.  You never said protoc-gen-go explicitly.

**Comment by bcbrock** [comment]
I _meant_ to mean whatever was  the time-consuming part of building the environment related to the protobuf compiler. Time was when this was not actually necessary. I have found that there is a lot of stuff in the Vagrant setup that is or was not really necessary.

It would be nice if things like this 

```
git checkout 12fb61b292d7ec4cb14b0d60e58ed5c35adda3b7
```

were better documented. Is this an actual requirement, or just what happened to be the latest thing that worked at the time the script was written? (Rhetorical question.)

**Comment by ghaskins** [comment]
@bcbrock that is a great question about the sha.  I have no idea why it was chosen.

On this topic, I _need_ to cut an s390x docker image for dockerhub.  I should _probably_ respin the entire suite (x86/vagrant and x86/docker) too to reflect the fact that @vpaprots updated the scripts.  While technically true that the x86 side should be a no-op, it seems prudent given that there was a change introduced.

Additionally, protobuf 3.0.0-beta3 was released a few days ago (https://github.com/google/protobuf/tree/v3.0.0-beta-3).

Should I upgrade the base image to this stable tag while I am at it @srderson ?

**Comment by bcbrock** [comment]
@ghaskins @srderson I think this issue has served its purpose, please close it if you agree.

**Comment by srderson** [comment]
Early on, there was no binary available. Initially it just checked out master and built that. Then everyone wound up with different versions and some people saw bugs that others did not see. So the latest at the time was chosen.

If there's a binary available now, I would totally agree that we should just download and use it instead of building from source.
