### ISSUE TITLE
PBFT Classic: Peers disagree on the structure of the blockchain

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1343]
Using the latest code

```
commit a56ad9b8e592119973d0290d70f537b628ddcf32
Merge: 1ca0c89 dad6b2a
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Tue May 3 13:41:19 2016 -0400

    Merge pull request #1325 from jyellick/consensus-threading-and-queues-rb
```

Running PBFT classic on 4 peers. Transactions targeted only to peer 0. At the end of the run, the peers disagree on the block structure of the blockchain. Here are excerpts of a simple text conversion of the blockchain from 2 peers. Peer 0 has drawn a block boundary for block 5 between 2 transactions, Peer 1 does not draw the boundary until many more transactions have been included in block 5.

Peer 0

```
i c65cb067-8b21-434c-a706-ffbc2a4aa611
i fe47c39f-4ee8-4e4e-b8f0-821921c1533a
i d5298f47-a729-40f8-a98f-ef0cb9191e94
b 5
i 2c5eb69d-53f8-4945-b22f-1b00d9c5f1eb
i da024a5b-fdb8-4221-9212-abd7a9f8e102
i bd5ea13e-e4df-40f7-b704-5e0ebdcb7d2d
```

Peer 1

```
i c65cb067-8b21-434c-a706-ffbc2a4aa611
i fe47c39f-4ee8-4e4e-b8f0-821921c1533a
i d5298f47-a729-40f8-a98f-ef0cb9191e94
i 2c5eb69d-53f8-4945-b22f-1b00d9c5f1eb
i da024a5b-fdb8-4221-9212-abd7a9f8e102
i bd5ea13e-e4df-40f7-b704-5e0ebdcb7d2d
...
b 5
```

@jyellick Is this expected/allowed?

**Comment by corecode** [comment]
with classic, every block should only contain a single transaction.

**Comment by corecode** [comment]
What tool do you use to explore the blockchain?  Could we add this to the fabric code? see also #1272.

**Comment by bcbrock** [comment]
@corecode - Thanks for the reply. I did not "get the memo" when CORE_VALIDATOR_CONSENSUS was changed to CORE_VALIDATOR_CONSENSUS_PLUGIN - So I'm actually running NOOPS where this is not a problem.

The tool I'm using is part of the _**busywork**_ project proposed yesterday. If they accept my proposal then the tool will be part of the repo.
