### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by lehors** [hyperledger-archives/fabric#1347]
The landing of PR #1341 moving install content to new file broke several links in the top README.md file.

**Comment by joshhus** [comment]
We updated the README.md also. Will investigate, thanks.

**Comment by bmos299** [comment]
I noticed in the README.md file that both the Installation: and Protocol Specification: link are broken (i.e. result in 404 Response codes).

**Comment by lehors** [comment]
@bmos299 You're right I added that to my PR.
Thanks.

**Comment by joshhus** [comment]
Thanks for looking at this, folks! (Still new to the git CLI / cloning / syncing process.)
