### ISSUE TITLE
DOC https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/install.md Cancelling peer before starting behave tests 

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1354]
On this web page: https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/install.md
This section: _3.2 Behave Tests_
mentions that you can initialize docker containers for behave by running the unit tests described in section 3.1.  

Development has advised me that if I run unit tests described in section 3.1 to set up behave, I need to cancel the peer mentioned in 3.1 before starting behave.  However, the web page doesn't mention this at all. 

Suggestion: 
3.2 Behave Tests
Behave tests will setup networks of peers with different security and consensus configurations and verify that transactions run properly. To run these tests:

1) Behave requires peer and member services docker images.  Choose one of these methods
    to create the requisite docker images for behave: 

```
 Unit test method:
   a. Run unit tests as described in section 3.1.
   b. Cancel the peer you started when you ran the unit tests.

Go test method:
  In a vagrant window, execute these commands:
go test github.com/hyperledger/fabric/core/container -run=BuildImage_Peer
go test github.com/hyperledger/fabric/core/container -run=BuildImage_Obcca
```

2) In a vagrant window, enter 
  a.    cd $GOPATH/src/github.com/hyperledger/fabric/bddtests
  b.    behave
        or 
        behave -D logs=Y  /\* captures logs from Docker containers */

**Comment by lehors** [comment]
I already changed behave to stop the local running peer before launching the tests so this should no longer be an issue any longer. See PR #1251 and please confirm or close this issue.
Also, please, update your profile and disclose your name and affiliation. Thank you.
