### ISSUE TITLE
Assertion failing in behave test scenario @issue_680 tag

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1358]
Observed below error messages in recent travis builds. This issue is inconsistent but most of the times build is failing with below scenario. This could be another timeout issue as assertion value of "a" is taking from the initial invoke value. 
**Scenario:**
_@issue_680_
  Scenario Outline: chaincode example02 with 4 peers and 1 membersrvc, issue #680 (State transfer) -- @1.3 Consensus Options
**Below are Error messages:**
Assertion Failed: For attribute OK, expected (20), instead found (130)
http://chunk.io/f/8b49ada17f5247e08b7d11da327a4d02
Exception: Max time exceeded waiting for transactions with current response map = {'bddtests_vp0_1': 404, 'bddtests_vp1_1': 0, 'bddtests_vp2_1': 0}
http://chunk.io/f/c1b62c91018342f2bf394444938d914a

**Container Log Files:**

bddtests_vp0_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)-.1.3_Consensus_Options.log
http://chunk.io/f/598ffb3c661e4f2a99f29fd858828b5c
bddtests_vp1_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_1.3_Consensus_Options.log
http://chunk.io/f/055afebd4099421fa41bbc15c8b739aa
bddtests_vp2_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_1.3_Consensus_Options.log
http://chunk.io/f/1f123a79dce040e486bb55bacce7e85e
bddtests_vp3_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_1.3_Consensus_Options.log
http://chunk.io/f/220baf46073e426ab685277a4d1c9415

**Comment by tuand27613** [comment]
I saw this "expected 20 found 130" error while looking at #1331 .
From looking at both sets of logs,  vp3 had not finished state transfer before the query came in thus the incorrect query return. I added a wait before issueing the final query in the test and have not been able to reproduce.

@jyellick @simon thoughts ?

**Comment by jyellick** [comment]
@tuand27613 Like many other Travis failure's we've seen, it seems likely that this is the timeout issue as you described.  I would have to check logs to confirm, but if tweaking the timeout up seems to solve it, then I'd be in favor of pulling it.

**Comment by tuand27613** [comment]
logs from behave run in my Vagrant setup

[1358.zip](https://github.com/hyperledger/fabric/files/252715/1358.zip)

**Comment by tuand27613** [comment]
+1 on not having 680 as part of the travis run .  
Perhaps we can tweak the travis behave call to skip this test ? Developers can still have it run when they do their manual unit tests

**Comment by jyellick** [comment]
@tuand27613 I actually wasn't proposing deleting the test, I meant "pulling (as in a PR) a timeout fix".  State transfer is one of the more complex test scenarios, but I think it's important it be tested, especially as new developers want to submit code changes which might break it in subtle ways.

**Comment by tuand27613** [comment]
I put in a PR to add the extra wait.

My issue is how to deal with the many false positives out of travis ? Maybe we should have developers attach output of a full unit tests/behave tests/sdk tests run while travis runs a smaller regression bucket.

At least until we can bend behave to our will :-)
