### ISSUE TITLE
chain/blocks/<n> return data

### ISSUE THREAD

**Issue by cophey** [hyperledger-archives/fabric#1359]
when i call http://172.0.0.193:3000/chain/blocks/251 ,and i got a block object,but i have some confusion that the transaction‘s uuid is the same to my chaincodeid and the transaction does not have cert/signature and the block NonHashData has no TransactionResults.
`{
    "transactions":[
        {
            "type":1,
            "chaincodeID":"EgdjY191c2Vy",
            "payload":"ChoIARIJEgdjY191c2VyGgYKBGluaXQqA2ppbQ==",
            "uuid":"cc_user",
            "timestamp":{
                "seconds":1462418882,
                "nanos":383523454
            }
        }
    ],
    "stateHash":"79YWhl/kRpcon6ciBL/pgGxe3SlHGTGtVR7/E9GhDMOZWo0ZqpMOx/iwNiCABXQ/xjvWsrJUpuAhKXqV75bbAw==",
    "previousBlockHash":"A/Va05B4cD9ZDNi9X9hjBMnT2aJxyBWJN2BImy2irCnO+Ml+QF+RerovhUIyLGcaP28gNsUnmnzIwO3PNRwXGw==",
    "nonHashData":{
        "localLedgerCommitTimestamp":{
            "seconds":1462418883,
            "nanos":465242769
        }
    }
}`

**Comment by cophey** [comment]
The uuid is chaincodeid when the transaction is deploying chaincode,other uuid is right.

if i want to return cert/signature and TransactionResults,what should i do?thanks.

**Comment by mastersingh24** [comment]
@cophey  - if you don't have security enabled, you will not see the signature / cert that was used when submitting the transaction.

The ledger doesn't currently show the transaction results (e.g. the state changes).  Right now it only contains the function invocation and parameters.  You can find them in the "payload" field - which is base64-endcoded

**Comment by cophey** [comment]
@mastersingh24 Thanks.

But The Uuid can repeat?when i get /chain/blocks/327 and /chain/blocks/325,they have the same uuid.Is it a bug?

![image](https://cloud.githubusercontent.com/assets/7555270/15106642/6276ce94-15fd-11e6-92b2-1057a1c8b0a2.png)
![image](https://cloud.githubusercontent.com/assets/7555270/15106665/7d28c30a-15fd-11e6-9984-a806afd95c1a.png)

In my mind, UUID should be in a format like this "3051b859-d27d-462c-b3ca-de056f9777f0".
![image](https://cloud.githubusercontent.com/assets/7555270/15107218/0cf0ec6c-1601-11e6-9bab-70fdda2a7bc9.png)

**Comment by mastersingh24** [comment]
@cophey - were you running in development mode?  And is "cc_asset" the ID you gave your chaincode?

**Comment by cophey** [comment]
@mastersingh24 yes.Am I something wrong?
