### ISSUE TITLE
Moving connection creation code to one place

### ISSUE THREAD

**Issue by gennadylaventman** [hyperledger-archives/fabric#1362]
Code contains 4 methods that create connections:
core/peer/peer.go: NewPeerClientConnectionWithAddress
events/consumer/consumer.go: newEventsClientConnectionWithAddress 
core/crypto/node_grpc.go: getClientConn
core/caincode/shim/chaincode.go: newPeerClientConnection  
and code in all methods do almost same work. 
It worth to move all same code to one place, to avoid code duplication and make code more readable. 

This change is first step in communication code consolidation to easy the introduction new capabilities such as flow control.

Inspired by Gari Singh comments.

**Comment by muralisrini** [comment]
@gennadylaventman : in the interest of loose coupling, I would suggest not having to import fabric into shim ?  I know we do some fabric imports already IMHO but we should really be finding ways to decouple more. At some point when we stop including the entire fabric with chaincode image, these will become thorny. Also there is the issue of multi-language chaincode support. Suggest we consider making shim an exception ?

**Comment by gennadylaventman** [comment]
@muralisrini 
I both agree and disagree:
Yes, it is better to not import fabric to chaincode. And yes, the multi-language issue not covered. But this was almost identical code and we can pack all communication related code as separate communication library in future, including flow control, etc. I can restore original shim code, but IMHO this way it looks better...

**Comment by muralisrini** [comment]
Wouldn't it be nice if peer and chaincode link to a common library ? Till then my vote is to grit our teeth and dup :-). But this is just _my_ opinion ...

**Comment by gennadylaventman** [comment]
Should we continue discussion in PR? [Connection code centralization](https://github.com/hyperledger/fabric/pull/1520)

**Comment by muralisrini** [comment]
OK. I'll copy my comment there (as opposed to linking :-) )
