### ISSUE TITLE
'concurrent map read and map write' panic using Sieve

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1366]
In:

```
commit a56ad9b8e592119973d0290d70f537b628ddcf32
Merge: 1ca0c89 dad6b2a
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Tue May 3 13:41:19 2016 -0400

    Merge pull request #1325 from jyellick/consensus-threading-and-queues-rb

    Consensus threading and queues rebase
```

4 peers running sieve consensus. One peer crashes with a 'concurrent map read and map write'  panic. The logs are gigantic, here is the tail of the log of the crashed peer.

[logTail.txt](https://github.com/hyperledger/fabric/files/250680/logTail.txt)

To recreate:

Install https://github.ibm.com/bcbrock/busywork
cd busywork/scripts; make images
cd busywork/counters; make issue10xx

**Comment by bcbrock** [comment]
Note that there is a chance, maybe 1 out of 4, that a run set up as above will pass.

**Comment by corecode** [comment]
Thanks!  Fix coming soon.

**Comment by vukolic** [comment]
can this one be closed?

**Comment by bcbrock** [comment]
@vukolic Yes, I haven't seen this in awhile
