### ISSUE TITLE
Chain code unit tests are failing after commit# eb287d4

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1380]
Chain code unit tests are failing after below commit: All PR's are failing with below error message.

commit eb287d4b1a29d970a40d4af28454f789ea4e474e
Author: Christopher Ferris chrisfer@us.ibm.com
Date:   Thu May 5 14:39:46 2016 -0400

**Error Log:**
FAIL: TestChaincodeInvokeChaincode (65.52s)
    exectransaction_test.go:674: Error invoking <b736a304eeda340a47c52c44367a28c8f41004518a4181eb7e8417a778ad3a4b4fe37ea149399cb7b27be88c3920025141cf4be0ebb7791e5968897bdc31d1b6>: Failed to execute transaction or query([3dc36f95-9dbb-4a28-9a1f-d91eaf9f697a]Chaincode handler FSM cannot handle message (ERROR) with payload size (237) while in state: ready)
2016/05/05 22:52:21 Chaincode support using peerAddress: 0.0.0.0:40303
getting deployment spec for chaincode spec: type:GOLANG chaincodeID:<path:"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" > 

**Log Files:**
https://s3.amazonaws.com/archive.travis-ci.org/jobs/128170910/log.txt (Search with FAIL (Match case))

Build Results:
https://travis-ci.org/rameshthoomu/fabric/builds/128214308 [ On commit# 10395e5]
https://travis-ci.org/rameshthoomu/fabric/builds/128217290 [On commit# eb287d4]

**Comment by srderson** [comment]
This is happening because the hash of chaincode_example02 changed when the license comment was changed. chaincode_example04 hard codes the hash of chaincode_example02 and it broke a test case.

**Comment by muralisrini** [comment]
Will fix this shortly. The fix also includes a comment in chaincode_example02 about relationship between chaincode_example02 and chaincode_example04.

Rather than hardcoding, chaincode_example05 shows how to pass a chaincode ID as argument.
