### ISSUE TITLE
Registration with Membership service fails

### ISSUE THREAD

**Issue by novusopt** [hyperledger-archives/fabric#1395]
I am getting an error when i start the fabric with security enabled and run the node as validator

How to reproduce:
1) enable security
2) start membership service
3) run peer as validator

**output of membership service:**
2016/05/07 08:59:21 Log level not recognized '', defaulting to DEBUG: logger: invalid log level
2016/05/07 08:59:21 Working at security level [256]
INFO: 2016/05/07 08:59:21 CA Server (0.1)
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
ERROR: 2016/05/07 08:59:21 ca.go:519: table Users has no column named enrollmentId
INFO: 2016/05/07 08:59:21 ECA started.
INFO: 2016/05/07 08:59:21 TCA started.
INFO: 2016/05/07 08:59:21 TLSCA started.

**output of peer**
08:59:30.731 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
08:59:30.731 [logging] LoggingInit -> DEBU 002 Setting default logging level to DEBUG for command 'peer'
08:59:30.732 [sysccapi] RegisterSysCC -> DEBU 003 system chaincode github.com/hyperledger/fabric/core/system_chaincode/sample_syscc registered
08:59:30.733 [eventhub_producer] AddEventType -> DEBU 004 registering block
08:59:30.733 [eventhub_producer] AddEventType -> DEBU 005 registering register
08:59:30.733 [main] serve -> INFO 006 Security enabled status: true
08:59:30.733 [main] serve -> INFO 007 Privacy enabled status: false
08:59:30.733 [main] func1 -> INFO 008 Register user vp with password f3489fy98ghf 
08:59:30.733 [main] func1 -> DEBU 00a Registering validator with enroll ID: vp
08:59:30.733 [crypto] func1 -> INFO 00b Registering validator [vp] with name [vp]...
08:59:30.733 [eventhub_producer] start -> INFO 009 event processor started
08:59:30.758 [crypto] getEnrollmentCertificateFromECA -> ERRO 00c [validator.vp] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = "no such column: enrollmentId"].
08:59:30.758 [crypto] retrieveEnrollmentData -> ERRO 00d [validator.vp] Failed getting enrollment certificate [id=vp]: [rpc error: code = 2 desc = "no such column: enrollmentId"]
08:59:30.758 [crypto] registerCryptoEngine -> ERRO 00e [validator.vp] Failed retrieving enrollment data [rpc error: code = 2 desc = "no such column: enrollmentId"].
08:59:30.758 [crypto] register -> ERRO 00f [validator.vp] Failed registering node crypto engine [rpc error: code = 2 desc = "no such column: enrollmentId"].
08:59:30.758 [crypto] register -> ERRO 010 Failed registering [vp]: [rpc error: code = 2 desc = "no such column: enrollmentId"]
08:59:30.758 [crypto] RegisterValidator -> ERRO 011 Failed registering [vp]: [rpc error: code = 2 desc = "no such column: enrollmentId"]
08:59:30.758 [crypto] func1 -> ERRO 012 Failed registering validator [vp] with name [vp] [rpc error: code = 2 desc = "no such column: enrollmentId"].

Usage: 
  peer peer [flags]

Flags:
  -h, --help[=false]: help for peer
      --peer-chaincodedev[=false]: Whether peer in chaincode development mode
      --peer-discovery-enabled[=true]: Whether peer discovery is enabled
      --peer-gomaxprocs=2: The maximum number threads excuting peer code
      --peer-port=30303: Port this peer listens to for incoming connections
      --peer-tls-cert-file="testdata/server1.pem": TLS cert file
      --peer-tls-enabled[=false]: Connection uses TLS if true, else plain TCP
      --peer-tls-key-file="testdata/server1.key": TLS key file

Global Flags:
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax

Error: rpc error: code = 2 desc = "no such column: enrollmentId"

One more point, we should handle those two errors separately, currently we don't return the error message if the readUser fails. 
https://github.com/hyperledger/fabric/blob/master/membersrvc/ca/eca.go#L221
Shall i create a pull request for that?

i added the above described error handling in my code, then you will get the error message: 
Error: rpc error: code = 2 desc = "no such column: enrollmentId"

otherwise you will get "identity or token does not match"

**Comment by adecaro** [comment]
Hi @novusopt, are you using the current master? I ask because I don't see the same error :(
Probably, I'm missing something. Please, may you give more details? Thanks :)

**Comment by mastersingh24** [comment]
@novusopt  - my guess is that you recently updated your repo / build of membership services and/or the peer.  The problem is that the schema for the sql db used in membership services has changed.  Assuming you are using the default config location, you'll want to delete everything under _/var/hyperledger/production_   (if you need to keep your peer db/state, then just delete the _crypto_ and _.membersrvc_ folders

**Comment by novusopt** [comment]
@mastersingh24 yes you are right, it is now working. Thanks!

**Comment by novusopt** [comment]
Now i am facing a new issue

I am trying to log in from the command line and i get following error:
./peer login vp -p f3489fy98ghf
16:19:19.869 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO

Usage: 
  peer login [flags]

Flags:
  -p, --password="": The password for user. You will be requested to enter the password if this flag is not specified.

Global Flags:
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax

Error: Error on client login: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @2

and the peer output:

16:19:19.917 [crypto] retrieveEnrollmentData -> ERRO 03b [client.vp] Failed unmarshalling enrollment chain key [id=vp]: [asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @2]
16:19:19.918 [crypto] registerCryptoEngine -> ERRO 03c [client.vp] Failed retrieving enrollment data [asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @2].
16:19:19.918 [crypto] register -> ERRO 03d [client.vp] Failed registering node crypto engine [asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @2].
16:19:19.918 [crypto] Login -> ERRO 03e Failed registering client [vp] with name [vp] [asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @2].

**Comment by mastersingh24** [comment]
@novusopt  - I don't think this is an issue any more?  can it be closed?

**Comment by novusopt** [comment]
@mastersingh24 Yes
