### ISSUE TITLE
The enrollID should not be included in the subject of transaction certificates

### ISSUE THREAD

**Issue by mastersingh24** [hyperledger-archives/fabric#1409]
## Description

Transaction certificates currently include the enrollID as part of the subject in the X509 public certificate.  Given that tcerts are used for unlink-ability, this needs to be fixed.  
## Describe How to Reproduce

Enable security, use transaction certificates and decode the X509 certs.  Easiest way to do this is to simply extract the cert bytes from the block/transaction API response and decode them

**Comment by adecaro** [comment]
Hi @mastersingh24, good catch. @diegomasini, please,  may you take a look at it. Thanks :)

**Comment by mastersingh24** [comment]
@diegomasini  - are you looking at this one?  Else I am happy to handle

**Comment by diegomasini** [comment]
@mastersingh24 yes, we will take care of this one. Thanks!

**Comment by JonathanLevi** [comment]
Can we please re-open this (1409) and assign to me?
[While related, these commits do not close the entire issue and are already merged]

**Comment by ghaskins** [comment]
Per request of @JonathanLevi

**Comment by diegomasini** [comment]
@JonathanLevi my suggestion is to put the encrypted TCertIndex in the X.509 subject. This requires to move the encrypted TCertIndex from the Extensions list of the certificate to the subject. It will require to change the places were that value is accessed. I think there is only one, in the client when the private key is derive. By doing so we are not bringing any likability issues with this change.

**Comment by JonathanLevi** [comment]
Sure, will take care of this. Thanks guys.

**Comment by mastersingh24** [comment]
@JonathanLevi  -  did this get handled?  I'll check myself, but if you know we can close this that would be great

**Comment by JonathanLevi** [comment]
@mastersingh24 Will close this today.

**Comment by JonathanLevi** [comment]
Just a quick one (and sorry these 2 lines change took some coordination).

The encrypted TCertIndex is an AES-CBCEncrypted `[]byte` slice that is not really usable, let alone readable, even [more so? ;-)] after Base64 Encoding:

```
NewCertificateSpec:
    id='test_user0'
    CommonName=
**9ey+oKgHNjUsRATgCNp+eBWXJfwTIvoxAyAWJhvKMR7zgV9/Mjf2ETag7mAXZXUKg1UTJmdHGMU0xyYDGAiG+w==**
```

Or even if we use the not encrypted TCertIndex (just for argument's sake)

```
NewCertificateSpec
    id='test_user0'
    CommonName=**236710024325267987903988429987708228792**
```

Neither feels like a common name field value (while the latter might still introduce some linkability issues down the line).

**Comment by JonathanLevi** [comment]
So diverging a bit from the request to move the encrypted TCertIndex from the Extensions list of the certificate to the subject:

Unless there's any objection, how about we just put a 'Transaction Certificate' text in the common name field of the TCert (yes, rather than the EnrollmentID which is currently there in the clear).

**Comment by mastersingh24** [comment]
No objection from me.  Makes sense to just use a static string here and "Transaction Certificate" makes perfect sense

**Comment by JonathanLevi** [comment]
OK, will quickly add a test to verify that we don't "release/issue" TCerts with any other `Subject.CommonName` and PR this 2 liner. Thanks again.

**Comment by yashgt** [comment]
Can the chaincode know the identify of the user that has initiated the transaction based on the certificate? What attributes of the certificate are accessible to the chaincode? I would like to use the identity of the initiator to perform authorization.
