### ISSUE TITLE
Go metallinter requirement on PRs is poorly specified and should be removed

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1414]
## Description

Over the weekend, someone unilaterally added a requirememnt for PRs that the developer must have run `gometalinter` on changed files and resolved all of the errors. This requirement should be scrapped until the following issues are addresed.

First, the `gometalinter` is a complex and highly configurable set of capabilities, yet this requirement was made _without any documentation_ of exactly how the `gometalinter` was to be installed and run to satisfy this requirement. For example, I've been trying to figure out for the last 30 minutes how to make it recognize the "vendoring" structure of our GOPATH (without success).

Ignoring that, let's take a look at some of the issues uncovered in the core/chaincode directory:

```
1. chaincode_support.go:363::warning: cyclomatic complexity 24 of function (*ChaincodeSupport).Launch() is high (> 10) (gocyclo)
2. core/chaincode/chaincode_support.go:330:1:warning: comment on exported method ChaincodeSupport.Stop should be of the form "Stop ..." (golint)
3. core/chaincode/chaincode_support.go:563:14:warning: printf-style function with dynamic first argument and no further arguments should use
```

According to this new requirement, someone suggesting a minor change to a file is now required to:
1. Refactor all complex routines in the file to satisfy an arbitrary "cyclomatic complexity" limit.
2. Correct or add documentation to all exported functions of the file.
3. Change print statements based on the arbitrary opinion that `Printf("foo")` (which is perfectly legal) should be changed to `Print("foo")`.

Clearly this wasn't the intent of the new requirement. However this leads to the question, what _was_ the intent of this new requirement? This question needs a crisp answer.

Once a crisp answer is available, in my opinion a comprehensive code cleanup should be undertaken as a separate project, rather than piecemeal as files are changed. Since the large majority of the existing code was created by IBM software development teams, to me it would natually fall to the IBM developer who was the original owner of the files or package to lead this effort, as they would be able to most efficiently and correctly refactor, document, etc. their own code.

**Comment by srderson** [comment]
I added that. The intent of the requirement is to have everyone run these tools.

[goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)
[go vet](https://golang.org/cmd/vet/)
[golint](https://github.com/golang/lint)

This ensures a minimum standard for code formatting and comments. These are standard in the Go community and help to ensure readability of code.

I thought gometalinter would make life easier as it's just one tool, but that doesn't seem to be the case. I'll open a PR to suggest these four tools instead of gometalinter.

**Comment by bcbrock** [comment]
@srderson If you can provide a script that runs the exact tools you had in mind, precisely how you have them in mind, that would be great. 

I do still have hesitations though. Every linter includes a caveat like the one included with golint:

```
The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard.
```

I agree that adherence to standards is important, but the standards have to be "decidable", like `gofmt`. What mechanism will be used to decide if a `golint` warning is allowed?

I also see that `golint` will suggest that I should fix pre-existing documentation in a file I modified, as well as rename a structure

```
chaincode_support.go:138:6: type name will be used as chaincode.ChaincodeSupport by other packages, and that stutters; consider calling this Support
chaincode_support.go:330:1: comment on exported method ChaincodeSupport.Stop should be of the form "Stop ..."
chaincode_support.go:362:1: comment on exported method ChaincodeSupport.Launch should be of the form "Launch ..."
chaincode_support.go:500:1: comment on exported method ChaincodeSupport.Deploy should be of the form "Deploy ..."
```

I don't believe it is fair or wise to require the community to clean up IBM code. So I still believe that it would be good for the IBM developers to first use these tools to clean up the codebase. Once they have had that experience, and identified and agreed on false positives and scripted them to be ignored, only then require all new submissions to adhere to a set of well-thought-out standards.

**Comment by bcbrock** [comment]
Fixed by the new PR boilerplate.
