### ISSUE TITLE
In CC to CC calls, the calling CC will get killed by FSM if called CC returns Error.

### ISSUE THREAD

**Issue by tsariounov** [hyperledger-archives/fabric#1425]
## Description

If you set up a chaincode (cc) that calls another cc, then if the called cc returns a fmt.Error (which can be common), then the cc FSM intercepts that Error and kills the calling cc.  This does not happen if you call the cc from a client (ie outside the chain).  The behavior should be consistent across calling methods (ie should not depend on who is calling the cc) and the common use case of returning a fmt.Errror should be supported.
## Describe How to Reproduce

Attached are two chaincodes: dns.go and dns-test.go that demonstrate this problem.  To reproduce follow these steps:
- Run cc dns.go and dns-test.go on the peer in dev mode in terms 1 and 2.
  - term1: `CORE_CHAINCODE_ID_NAME=dns CORE_PEER_ADDRESS=0.0.0.0:30303 ./dns`
  - term2: `CORE_CHAINCODE_ID_NAME=dns-test CORE_PEER_ADDRESS=0.0.0.0:30303 ./dns-test`
- Deploy both cc's from term3.
  - `./peer chaincode deploy -n dns -c '{"Function":"FooBar", "Args":[]}'`
  - `./peer chaincode deploy -n dns-test -c '{"Function":"FooBar", "Args":[]}'`
- Create a namespace in term3
  - `./peer chaincode invoke -l golang -n dns-test -c '{"Function": "registerNamespace", "Args":["NS1", "owner1"]}'`
- Create a name mapping in term3
  - `./peer chaincode invoke -l golang -n dns-test -c '{"Function": "register", "Args":["owner1", "NS1", "test", "1234"]}'`
- Call query for existing name (should not fail)
  - `./peer chaincode query -l golang -n dns-test -c '{"Function": "lookup", "Args":["NS1", "test"]}'`
- Call query for non-existing name (will fail)
  - `./peer chaincode query -l golang -n dns-test -c '{"Function": "lookup", "Args":["NS1", "HelloWorld"]}'`

The error seen in term2 (which is running dns-test) is:

`Query: (lookup)
Calling (dns), function (lookup) with args ([NS1 HelloWorld])
2016/05/05 22:24:13 [683d6d42]Sending INVOKE_QUERY
2016/05/05 22:24:13 [683d6d42]Received message ERROR from shim
2016/05/05 22:24:13 [683d6d42]Handling ChaincodeMessage of type: ERROR(state:ready)
Error starting dns-test: Error handling message: [683d6d42-5912-4a28-9d9e-4b8475586b46]Chaincode handler FSM cannot handle message (ERROR) with payload size (31) while in state: ready`

And the dns-test cc process exits as a result.

**Comment by tsariounov** [comment]
Attaching chaincode (github does not allow me to upload *.go files, so attached is a zip of them).
[dns-cc.zip](https://github.com/hyperledger/fabric/files/257655/dns-cc.zip)

**Comment by muralisrini** [comment]
Errors from chaincode should be distinguished from errors from the fabric. That is
       result, err := CallChaincode
could return a result that's an error from chaincode. If err != nil result should be sent to the calling chaincode. err and result-error shoud not be conflated.
