### ISSUE TITLE
asset-management chaincode fails on query with `ledger: resource not found`

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#1437]
## Description

Using examples/chaincode/go/asset-management/app  as the driver for running the asset-management chaincode. Things fails at the `bob assign ownership to charlie` step with error `ledger: resource not found` and `decryption failed`

Always fails when logging_level= info. Does NOT fail when logging_level=debug.

Also observing that chaincode deploy can occasionally take 7-8 minutes, 33 minutes once
## Describe How to Reproduce

4 validating peers
membersrvc
security enabled, privacy true
running on z platform,  on bare metal, not in docker container

[success_logs.zip](https://github.com/hyperledger/fabric/files/258208/success_logs.zip)
[error_logs.zip](https://github.com/hyperledger/fabric/files/258210/error_logs.zip)

**Comment by tuand27613** [comment]
@prjayach a couple of things from reading the logs:
- seems that the failure is always on the `assign ownership` step ( correct me if I'm wrong ) which says that it's actually the deploy that is failing or taking too long
- In both sets of logs, there are quite a few view-changes ( especially in the error_logs ). @jyellick  is tracking down a state transfer bug that _might_ be the cause ( Jason, can you post issue or pull request number ? )

**Comment by tuand27613** [comment]
@gongsu832  have you encountered any kind of deploy latency like this ?  I should ask Volodymyr as well but I can't find him on github

**Comment by prjayach** [comment]
My reading is that the deploy itself is failing (container fails to start, starts-then-crashes or is taking too long). Whenever it fails, there is no container in place. Assign ownership is the first invoke after that which then fails.

However, as you say, it could be possible that the container came up but the assign ownership step caused the container to crash.

**Comment by gongsu832** [comment]
@tuand27613 I was wondering why I didn't get an email notification and noticed that you used the wrong tag for me. Should have been gongsu832.

In any case, I have never seen deploy taking that long on my system. But of course, B**\* is a different configuration. It's RHEL with 3.10 kernel while mine is Debian with 4.5 kernel. There are a couple of things that we can do to improve docker performance:
- switch to a dynamically linked binary to get udev support. https://www.ibm.com/developerworks/linux/linux390/docker.html now has a relatively recent 1.10.1 version available for RHEL and SUSE.
- use a separate volume in the volume group for the repo instead of using loop back. This requires a second disk being added to the volume group since the current one is used up.

**Comment by tuand27613** [comment]
so github is public and we can't mention customers by names :-D   ... can you edit your comment ?
Thanks ! TTuan DangIBM BlockchainInternet: tdang@us.ibm.comphone: (919) 543-1721 T/L 441-1721
 
 
----- Original message -----From: gongsu832 <notifications@github.com>To: hyperledger/fabric <fabric@noreply.github.com>Cc: Tuan Dang/Raleigh/IBM@IBMUS, Mention <mention@noreply.github.com>Subject: Re: [hyperledger/fabric] asset-management chaincode fails on query with `ledger: resource not found` (#1437)Date: Wed, May 11, 2016 9:00 AM 
@tuand27613 I was wondering why I didn't get an email notification and noticed that you used the wrong tag for me. Should have been gongsu832.
In any case, I have never seen deploy taking that long on my system. But of course, BAML is a different configuration. It's RHEL with 3.10 kernel while mine is Debian with 4.5 kernel. There are a couple of things that we can do to improve docker performance:
        switch to a dynamically linked binary to get udev support. https://www.ibm.com/developerworks/linux/linux390/docker.html now has a relatively recent 1.10.1 version available for RHEL and SUSE.        use a separate volume in the volume group for the repo instead of using loop back. This requires a second disk being added to the volume group since the current one is used up.

**Comment by gongsu832** [comment]
@tuand27613 Oops. Just did. But somehow your comments above also includes mine. You also need to take that out.

**Comment by jyellick** [comment]
@tuand27613 Per your request, the PR for that state transfer issue is #1445

**Comment by mastersingh24** [comment]
does this work with privacy enabled = false?

**Comment by tuand27613** [comment]
security + privacy exacerbates the problem, failure to deploy went from intermittent to always failing.

From looking at the logs, normal flow was overwhelmed by view-change requests going back and forth between the peers.  By increasing the timeouts in consensus/obcpft/config.yaml,  we got the normal deploy/invoke/query path to work again.  The root problem seems to be high latency somewhere in the system which was causing the view-change timer to fire.

For next steps, @prjayach and team will get their app going with security+privacy. We're getting full debug logs and are lining up a z perf team to work on the latency issue

**Comment by tuand27613** [comment]
Latency is due to 240Meg deploy transaction buffer. This took 3 seconds to broadcast to all the validating peers which caused the consensus request timeouts to fire which caused view-changes to cascade which prevented other requests.

Increasing request timeout values took care of the immediate problem. 

Size of transactions is being handled via #1581
