### ISSUE TITLE
Add mising node sdk example

### ISSUE THREAD

**Issue by novusopt** [hyperledger-archives/fabric#1443]
## Description

It would be nice to have an example which illustrates how to to use the hyperledger client (https://github.com/hyperledger/fabric/tree/master/sdk/node) to build a basic node.js app.

**Comment by mastersingh24** [comment]
@novusopt - that is the plan for sure.  the sdk is still under major development, hence no examples at this point

**Comment by christo4ferris** [comment]
think that this can be closed as there's an example in the docs.
