### ISSUE TITLE
membersrvc server should work harder to find its yaml file

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1489]
## Description

Currently the membersrvc server fails unless it is executed from the directory that contains the membersrvc.yaml file. The peer server can be executed form anywhere because it does some extra work to make sure that it sets up paths for Viper to search for the config file. This is a simple fix that should also be made to the membersrvc server.

**Comment by lehors** [comment]
Oh right, I actually fixed that in the peer command. I can do the same for membersrvc.

**Comment by bcbrock** [comment]
@lehors If you don't mind that would be great, thanks.
