### ISSUE TITLE
validator deploys chaincode

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#150]
Called during consensus to deploy chaincode. Much of this has been completed.... this is a placeholder in case we need to modify or harden current code.

**Comment by prjayach** [comment]
Ensure initialization is completed when chaincode is deployed (pending)

**Comment by muralisrini** [comment]
@prjayach : can you remind what is left of chaincode initialization that is left to do in chaincode scope itself (as opposed to commits etc). @manish-sethi added support for ledger updates to executetransaction

**Comment by prjayach** [comment]
I think this is completed now. I mentioned this to @markparz, but he mentioned that you had something pending on this item :) I think we can close.

**Comment by muralisrini** [comment]
I just wanted to check about your comment above. ...but I think we are in agreement this can be closed. Thanks Praveen.

**Comment by binhn** [comment]
close per @prjayach
