### ISSUE TITLE
./peer peer do not work.

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#1501]
## Description

./peer peer do not work any more. 
## Describe How to Reproduce

I followed https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/install.md#2-runexecute, peer  is not in the the Available Commands list. It failed to run ./peer peer.

**Comment by srderson** [comment]
The issue is that the documentation showing the output from `./peer` is outdated. The new command is `./peer node start`

**Comment by lehors** [comment]
Hmm, somehow one of the old lines in the document didn't get removed. I'll submit a fix.
Sorry about the confusion this created.
