### ISSUE TITLE
REST API calls for invoke transactions shouldn't always return with success

### ISSUE THREAD

**Issue by frankyclu** [hyperledger-archives/fabric#1505]
## Description

Got this request from a colleague, which I think make total sense:

Currently, REST API calls for invoke transactions are always returned with success, and there are no good ways to know if the transaction actually succeeded or failed. We need a mechanism to query the transaction result.
I understand there is a discussion to use event mechanism to get notification about result. But a REST API for querying transaction result is also very useful.
A transaction could fail 1) because of the platform level issue (i.e., chancode not deployed) or at the 2) chaincode level (i.e., application logic decides that the transaction should be denied). Type of the failure as well as the detailed result should be returned on a query.

**Comment by corecode** [comment]
I believe we had an issue opened about this before.  "Success" on invoke means it has been successfully submitted, not executed.

I do agree that delaying the REST reply to return the transaction result is favorable (even if just as an option).  I believe @muralisrini has been woking on parts of this.

**Comment by srderson** [comment]
https://github.com/hyperledger/fabric/issues/588

**Comment by frankyclu** [comment]
close, duplicate with #588
