### ISSUE TITLE
Query result of a string which contains '%' (percent symbol) is converted unexpectedly in the REST API.

### ISSUE THREAD

**Issue by ryokawajp** [hyperledger-archives/fabric#1517]
## Description

When a Query method of a chaincode returns a string which includes '%' character, it causes a problem that the letters after % is converted to unexpected string, or sometimes removed.
For example, "100% yuki" becomes "100%!y(MISSING)uki".

This happens in REST API only. CLI is OK.

This behavior is similar to that of fmt.Printf(), where % is a special character.
I tried to read the Fabric source code, but I could not identify the code which causes this conversion.
Is this a known issue?
Any comments are welcome.
## Describe How to Reproduce
- Deploy the following chaincode.
- Run a query from REST API. The returned value will be "100%!y(MISSING)uki", while the expected value is "100% yuki".
- Run a query from CLI. The returned value will be "100% yuki". This is correct.
- I used --peer-chaincodedev option.
- I obtained the source code of Fabric on April 24th.
- Go version 1.6 linux/amd64
- security = off

```
package main
import (
    "fmt"
    "github.com/hyperledger/fabric/core/chaincode/shim"
)
type SimpleChaincode struct {
}
func (t *SimpleChaincode) Init(stub *shim.ChaincodeStub, function string, args []string) ([]byte, error) {
    return nil, nil
}
func (t *SimpleChaincode) Invoke(stub *shim.ChaincodeStub, function string, args []string) ([]byte, error) {
    return nil, nil
}
func (t *SimpleChaincode) Query(stub *shim.ChaincodeStub, function string, args []string) ([]byte, error) {
    response := "100% yuki"
    return []byte(response), nil
}
func main() {
    err := shim.Start(new(SimpleChaincode))
    if err != nil {
        fmt.Printf("Error starting Simple chaincode: %s", err)
    }
}
```

POST /chaincode  body

```
{
  "jsonrpc": "2.0",
  "method": "query",
  "params": {
      "type": 1,
      "chaincodeID":{
          "name":"chaincode_percentbug"
      },
      "ctorMsg": {
         "function":"query",
         "args":[]
      },
      "secureContext": "test_user0"
  },
  "id": 5
}
```

**Comment by corecode** [comment]
Yey format string bugs! Feels like the 90ies :)

**Comment by corecode** [comment]
How about something like this?

```
diff --git a/core/rest/rest_api.go b/core/rest/rest_api.go
index 1f4e425..d0695b4 100644
--- a/core/rest/rest_api.go
+++ b/core/rest/rest_api.go
@@ -1098,7 +1098,7 @@ func (s *ServerOpenchainREST) Query(rw web.ResponseWriter, req *web.Request) {
        }

        rw.WriteHeader(http.StatusOK)
-       fmt.Fprintf(rw, string(jsonResponse))
+       rw.Write(jsonResponse)
    }
 }

```

**Comment by corecode** [comment]
@angrbrd

**Comment by angrbrd** [comment]
Yikes... thanks for pointing this out @ryokawajp. I am looking into it. And thank you @corecode. Let me see if I understand any reason why I did it the original way. Not sure if this was just my oversight or some corner case. I'll update shortly.

Thanks!

**Comment by sachikoy** [comment]
@angbrd Has this been fixed or investigated further?

**Comment by ryokawajp** [comment]
Hi, @christo4ferris
I have moved the issue to JIRA. I will close this item on GitHub.
https://jira.hyperledger.org/browse/FAB-240
