### ISSUE TITLE
Query fails with message that it can't write to read only database

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#1522]
## Description

Performed a deploy on a 5 VP + 1 ca, then attempted a query, got the following error message:

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: attempt to write a readonly database"
  },
  "id": 5
}
## Describe How to Reproduce

After sending a deploy and attempting to send a query on the TUID, I get the above error message plus some crypto errors on Peer0

[crypto 1 of 5.txt](https://github.com/hyperledger/fabric/files/273250/crypto.1.of.5.txt)
[crypto 2 of 5.txt](https://github.com/hyperledger/fabric/files/273253/crypto.2.of.5.txt)
[crypto 3 of 5.txt](https://github.com/hyperledger/fabric/files/273252/crypto.3.of.5.txt)
[crypto 4 of 5.txt](https://github.com/hyperledger/fabric/files/273251/crypto.4.of.5.txt)
[crypto 5 of 5.txt](https://github.com/hyperledger/fabric/files/273254/crypto.5.of.5.txt)

**Comment by corecode** [comment]
Please provide complete debug logs.

**Comment by RicHernandez2** [comment]
I did a vagrant destroy and vagrant up and the problem went away, closing as no repro
