### ISSUE TITLE
Forward host REST port to 5000 instead of 3000

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#1528]
## Description

Forward the REST host port to 5000 instead of 3000 so that it matches to REST port defined by the peer. The different ports has led to confusion.
## Describe How to Reproduce

Start the peer in Vagrant and from your host try to access http://localhost:5000. There is no response because you must use http://localhost:3000 instead.

**Comment by mastersingh24** [comment]
@srderson  - I always wondered about this.  This should definitely eliminate some unnecessary confusion
