### ISSUE TITLE
shim.GetRow() fails in chaincode query chaincode context, but succeeds in normal query context

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#1530]
## Description

shim.GetRow() returns the row successfully when querying a chaincode directly. But, when the same chaincode is queried from another chaincode, shim throws an error.
## Describe How to Reproduce

Running in dev mode, single node, vagrant setup, security on, privacy off (but I dont think its related to security).
Implement a query function that does a GetRow for a table. Call the query directly -- this succeeds. Call the query from another chaincode using shim.QueryChaincode, this throws an error.
[GetRow_Fail.txt](https://github.com/hyperledger/fabric/files/273897/GetRow_Fail.txt)
[GetRow_Success.txt](https://github.com/hyperledger/fabric/files/273898/GetRow_Success.txt)

**Comment by mastersingh24** [comment]
@prjayach :  from the logs, it appears as if you are trying to do access control within the chaincode you are trying to invoke from the other chaincode.  Currently, this won't actually work as I don't believe that the caller's context is passed when chaincode invokes chaincode.

```
4:36:10.101 [shim] DEBU : [932b2d41]Handling ChaincodeMessage of type: QUERY(state:ready)
04:36:10.101 [access_control_helper] DEBU : Inside isCallerParticipant
04:36:10.102 [access_control_helper] DEBU : Inside isCallerParticipant
04:36:10.102 [shim] DEBU : [932b2d41]Sending GET_STATE
04:36:10.103 [shim] DEBU : [932b2d41]Received message ERROR from shim
```

I am just guessing since I have not seen the actual chaincode

**Comment by prjayach** [comment]
@mastersingh24 Gari, you are partly right. We are trying to do access control, but we are passing the necessary context (sigma, payload and binding) needed for verifying the callers signature. The call where its failing is a routine access of a GetRow. Are you saying that chaincode calling chaincode and GetState wont work when security is turned on?

**Comment by prjayach** [comment]
I just confirmed that the same chaincode with security turned off, passes this GetRow() call and is able to retrieve the row from the table. So, the issue is with security turned on. Why should GetRow() fail and cause both the chaincode to crash for a GetRow() call? The context should only be needed for other calls such as VerifySignature? What am I missing?

**Comment by prjayach** [comment]
chaincode_example05 calling chaincode_example02 with security on (privacy off) causes chaincode_example02 to crash with the GetState() call. Hasn't chaincode invoking chaincode been handled with security turned on? We can't build any reasonable applications without this capability. I hope I am doing something wrong and not a limitation of the fabric.

**Comment by prjayach** [comment]
@binhn @adecaro @tuand27613 @mastersingh24 Help needed please

**Comment by tuand27613** [comment]
@muralisrini  as well

**Comment by muralisrini** [comment]
@prjayach : looking at it... Will post comment soon.

**Comment by muralisrini** [comment]
@prjayach . @mastersingh24 is right. Security context is not handled in chaincode-chaincode scenario's. Will work with @adecaro to see what can be done.

**Comment by prjayach** [comment]
As I mentioned earlier, I dont need metadata passed through for things like access control. But, I need basic GetState, PutState working in query and invoke context. Thanks for taking this up on priority!

**Comment by prjayach** [comment]
@ghaskins Should we leave this issue open as the PRIVACY=true case isn't handled yte by #1549 ?

**Comment by ghaskins** [comment]
@prjayach sounds reasonable to me.  I think github automated the closing anyway.
