### ISSUE TITLE
How to create pending transaction ? 

### ISSUE THREAD

**Issue by kamraanki** [hyperledger-archives/fabric#1531]
## Description

Hi i want to create pending transaction that's block must not be added to blockchain. After two validator users approve that transaction than that block must be added to blockchain. How to achieve the same ?

**Comment by corecode** [comment]
In the current design there is no mempool like in bitcoin.  What do you want to achieve exactly?  You could either collect signatures in your application and have the chaincode check the signatures, or you could write a (second) chaincode and once you received enough signatures, trigger the original transaction.
