### ISSUE TITLE
Block hash values become inconsistent after running hundreds of invoke transactions

### ISSUE THREAD

**Issue by sachikoy** [hyperledger-archives/fabric#1545]
## Description

Hash values in the blocks become inconsistent across the nodes, after running hundreds of invoke transactions without having internal between each transaction.  Sometimes, even the block height become inconsistent.
## Describe How to Reproduce

Environment used is a network with 4 peers with PBFT batch, and security/privacy enabled.
1. Deploy the chaincode, e.g., https://github.com/masterDev1985/hyperledger_chaincode/chaincode_example02
2. login to the peer using the "/registrar" end point.
3. Using the REST API, send  invoke transactions for 200 times or so, without adding interval between each transaction. Below is an example REST body that I used for invoking the transactions.(nothing special)
{
  "jsonrpc": "2.0",
  "method": "invoke",
  "params": {
      "type": 1,
      "chaincodeID":{
          "name":"c86de893fe7203e09add8c47237ffa377814311d9c3cb21ca4d3d5c4eeca65294d801a1f2e5a2d6b22b91096d9c8e42910046d2ab02d295ad0a0fb0b716e9a69"
      },
      "ctorMsg": {
         "function":"invoke",
         "args":["b", "a", "1"]
      },
      "secureContext": "test_user0"
  },
  "id": 3
}
4. Check the block hash values using the "/chain" REST end point on each of the four peers. Hash of some peer become inconsistent.

**Comment by mastersingh24** [comment]
@bmos299 - have you guys seen this in your testing as well?

**Comment by bmos299** [comment]
@sachikoy what commit level are you running?  We have been working on reproducing #1331 with the code you sent and it is working for us.
Can you tell us if this causes an outage?  What is your environment (using vagrant or not using vagrant, running the peer in a docker container)?  Does the peer lagging behind every catch up?

@mastersingh24 we have forced pauses on the docker container (not stop) causes a hang in the fabric #1478 due to hung serialized calls.  There is also #933, where if deploys are done while a peer is stopped, it causes panics when brought back into the fabric.   As far as this issue, I'm hoping to hear a little bit more (questions above).  There are some detailed discussions on this topic going on in issue #1331 (see the last few comments).

**Comment by sachikoy** [comment]
@bmos299 @mastersingh24 We are using the peers running in Docker containers that @mrshah-at-ibm has set up for us. I cannot see the commit level but it was updated on May 16, so I think we are using the latest code as of May 16.
After hash values become inconsistent, then eventually the block height become inconsistent, and some nodes lagging behind start behaving strangely. I have captured block data and logs and will send you by e-mail.

**Comment by mrshah-at-work** [comment]
@bmos299 - @sachikoy's setup is running `9a8f55f37aff7b34a6d18e88702e04a3d1bc60cf`

**Comment by sachikoy** [comment]
@bmos299 @mastersingh24 We have modified our chain code and it seems that the new code does not reproduce the problem so far. Still trying to figure out what was wrong with the chain code, but looks like we are ok on. Thank you very much for your support!

**Comment by bmos299** [comment]
@sachikoy thanks for the information.  We will continue to work #1331 with you.

**Comment by vukolic** [comment]
@sachikoy perhaps this one can be closed?

**Comment by sachikoy** [comment]
@vukolic I'd like to confirm the cause of this problem before closing this issue. There is a potential issue in HL that allows non-deterministic behavior of chain code.

**Comment by mastersingh24** [comment]
@sachikoy - it is a known fact that it is possible to write non-deterministic chaincode at this point.  Not that we want to push people in that direction in this point, but the "sieve" consensus was created in order to try to handle this.   In the new consensus proposal, non-deterministic behavior would be "detected" in the endorsement stage (detected meaning the transaction would not be endorsed if the value don't match up).

**Comment by sachikoy** [comment]
@mastersingh24 @vukolic @bmos299 The issue occurred again, after we ran the code for a couple of days. This time, some errors as follows are recorded in the block data. Block hash become inconsistent at block 590 and later.

```
"transactionResults": [
         {
           "uuid": "e20b7bc9-2a8c-4ae5-b82e-07f9163789f3", 
           "errorCode": 1,
           "error": "Failed to execute transaction or query(Timeout expired while executing transaction)"         }
 ]
```

There are some differences on the data in the world state as well. Some data was missing on vp0 where transaction error was recorded in the blocks.
This time, problematic chaincode was not included.

**Comment by tuand27613** [comment]
blockchain hashes as observed by @sachikoy and team

[block-investigate.xlsx](https://github.com/hyperledger/fabric/files/300644/block-investigate.xlsx)

**Comment by vukolic** [comment]
do we have the logs as well?

**Comment by sachikoy** [comment]
@vukolic I've sent a link to log file by e-mail. (A bit nervous about sharing the log on a public git hub)

**Comment by bmos299** [comment]
@mastersingh24 :  @ratnakar-asara is making some changes to his go toolkit.   He is changing from 5 nodes to 4 nodes and adding checks to include the state and hash value.  We were looking only at the height before.   This will be done today.

**Comment by vukolic** [comment]
@sachikoy - are you _sure_ your chaincode is deterministic? Can we obtain chaincode source (private channels ok)?

**Comment by sachikoy** [comment]
@vukolic I believe it is deterministic. How do you verify if it is deterministic? I sent you the chain code via e-mail. If anybody needs access, please contact me.

**Comment by sachikoy** [comment]
@bmos299 @ratnakar-asara @mrshah-at-ibm Hi, may I ask what is the status now? Were you able to reproduce the problem? I sent you guys the logs and block dump data. If you need more information, please let me know.

**Comment by ratnakar-asara** [comment]
@sachikoy , we couldn't reproduce this issue on vagrant environment, We see one of the peer lags behind and it catches up after some delay (5 seconds) 
We ran three iterations 500 , 600 , 650 Invokes and we see StateHash is same across nodes.
Logs attached for the same
[#1545_toolkit_containerlogs.zip](https://github.com/hyperledger/fabric/files/303234/1545_toolkit_containerlogs.zip)

We have Mihir's envronment setup ready, we shall continue reproducing on that environment

**Comment by sachikoy** [comment]
@corecode and @vukolic had kindly investigated the chaincode, and found that it is non-deterministic. I.e., the chaincode is not thread-safe, and uses some member variables to store data not only in Invoke but also in Query transactions. This causes the problem because Invoke and Query may be executed in parallel. 
We are fixing our chain code. But on the other hand, I think fabric should prevent this type of errors from happening  by improving  management of lifecycleand and scope of the chaincode object. I.e., chaincode object itself should be stateless, and execute in a new and identical context every time, and should not carry over its "member variables" between chaincode invocations/queries.
Or at least they should be thread safe, so that developer does not have to worry about thread safety.

**Comment by tuand27613** [comment]
@sachikoy , could you update on how your revised chaincode is working ?

As @vukolic mentioned,  #1751 can be used for more generic handling of thread safe cc.

**Comment by sachikoy** [comment]
@tuand27613 We have revised the chaincode and now testing it to see if the problem is reproduced.

**Comment by sachikoy** [comment]
I think this one can be closed. The issue was mainly in non-determinism in chaincode.
