### ISSUE TITLE
what to give in mycreds.json ?

### ISSUE THREAD

**Issue by kamraanki** [hyperledger-archives/fabric#1550]
## Description

Hi all i have created blockchain network on my local environment by following below URL:-

`https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md`

I have setup security setup(CA Server), Validator1and Validator2. I want to setup cp-web IBM blockchain sample node js app on my local. For that i need to modify mycreds.json file. What to give in that file ?
## Describe How to Reproduce

-  Follow below URL and setup Blockchain development environment.

`https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md`
- Clone following git repo.
  https://github.com/IBM-Blockchain/cp-web.git
- Now we have to modify mycreds.json to connect with our local network. So what to give in that file ?

**Comment by srderson** [comment]
This looks specific to IBM-Blockchain. Please ask on Stackoverflow or their repository.
