### ISSUE TITLE
Chaincode calls chaincode

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#156]
push on stack and call chaincode. pop when called chaincode returns and return response to callee

**Comment by markparz** [comment]
move milestone 4

**Comment by binhn** [comment]
closed per @muralisrini

**Comment by muralisrini** [comment]
well, lets close this after the merge of #326 (hopefully tomorrow)

**Comment by muralisrini** [comment]
Merged #326. Closing this issue
