### ISSUE TITLE
Error while initializing chaincode

### ISSUE THREAD

**Issue by softlore** [hyperledger-archives/fabric#1560]
I am trying to pass multiple arguments in the chaincode example 2 instead of 2 (a and b), 4 (a, b, c and d). On init I got an error from the chaincode registration terminal as follows:

05:30:19.966 [shim] DEBU : [mycc]Received message INIT from shim
05:30:19.966 [shim] DEBU : [mycc]Handling ChaincodeMessage of type: INIT(state:established)
05:30:19.967 [shim] DEBU : Entered state init
05:30:19.967 [shim] DEBU : [mycc]Received INIT, initializing chaincode
05:30:19.969 [shim] DEBU : [mycc]Init failed. Sending ERROR
05:30:19.970 [shim] DEBU : [mycc]Move state message ERROR
05:30:19.970 [shim] DEBU : [mycc]Handling ChaincodeMessage of type: ERROR(state:init)
05:30:19.970 [shim] DEBU : [mycc]send state message ERROR

The "go build" didn't throw any error. Need help on this.

**Comment by corecode** [comment]
Can you show your code?

**Comment by softlore** [comment]
@corecode The code I used was : 

in init function: 
A = args[0]
Aval = args[1]
err = stub.PutState(A, []byte((Aval)))
    if err != nil {
        return nil, err
    }
in CLI:
./peer chaincode deploy -n mycc -c '{"Function":"init", "Args": ["a","Pen", "b", "Ink", "c", "Eraser", "d" , "Box"]}'
It is repeated for all the four variables. All the variables are declared as strings. When I use only two arguments i.e a and b, it is working. But when I modify it for 4, I am getting this error.

**Comment by corecode** [comment]
i suggest logging some progress in your chaincode to understand where it fails

**Comment by softlore** [comment]
I have no idea about logging. Can you help me with that?

**Comment by corecode** [comment]
Sorry, I don't have any chaincode experience.  Furthermore, this doesn't seem to be a bug in fabric, so using an issue for programming troubleshooting is not the right thing.  Please close this issue and join the hyperledger slack to get help.

**Comment by ghaskins** [comment]
I think you are hitting this conditional: 

https://github.com/hyperledger/fabric/blob/master/examples/chaincode/go/chaincode_example02/chaincode_example02.go#L42

**Comment by binhn** [comment]
@gmk292 look [here](https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/logging-control.md) for logging in chaincode
