### ISSUE TITLE
Marshall viper configure

### ISSUE THREAD

**Issue by GrapeBaBa** [hyperledger-archives/fabric#1561]
## Description

Shall we marshal the viper configure(include environment, core.yaml etc) in a struct to avoid raw string key?

**Comment by corecode** [comment]
I'd prefer not to use viper in the first place, but use a configuration file package which allows direct reading into a struct.

**Comment by GrapeBaBa** [comment]
@corecode You mean use viper for command line flag and environment and use another pkg to load yaml config, right? Does it exist one better than viper?

**Comment by corecode** [comment]
There are plenty of config file packages - and it is becoming clear that viper isn't the one we really want.

**Comment by corecode** [comment]
Related #1309 #1128

**Comment by christo4ferris** [comment]
closing this one and tracking the issue with #1309
