### ISSUE TITLE
Error while running unit test

### ISSUE THREAD

**Issue by softlore** [hyperledger-archives/fabric#1562]
When running the 'make unit-test', I got an error message "**make: **\* [unit-test] Error 1**".
 Will this be affecting my environment?
I have attached the log file.
[UnitTest_Errorlogs.txt](https://github.com/hyperledger/fabric/files/278926/UnitTest_Errorlogs.txt)

**Comment by corecode** [comment]
This is not a bug, but some network configuration problem on your side.  It seems that the baseimage cannot be built or fetched, and github cannot be accessed.  Please make sure that your network connection is working correctly.

**Comment by ghaskins** [comment]
In addition to the observation made by @corecode, I also see this in the first few lines of the log:

```
Error starting userland proxy: listen tcp 0.0.0.0:30303: bind: address already in use
```

This implies you may have already had a peer running when you tried to launch the unit-tests.
