### ISSUE TITLE
implement TestChaincodeQueryChaincodeWithSec unit test as a behave test

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#1565]
## Description

The unit test was added for PR #1530. However, it adds "chaincodetest.yaml" as a dependency. This is an overkill and highlights the need for a behave test for this test. At this time of implementation behave framework does not have ability to deal with multiple chaincode instances in a test. We should move the unit test to a behave test, remove chaincodetest.yaml and point to core.yaml instead

**Comment by mastersingh24** [comment]
@muralisrini  - I don't have a problem with adding a behave test, but we really need to have unit tests.  Packages must be self-testable

**Comment by christo4ferris** [comment]
@muralisrini agree with @mastersingh24 on his observation. That said, is this still open or can it be closed?

**Comment by muralisrini** [comment]
@christo4ferris I too agree with @mastersingh24's observation. If the unit test is permanent, no need for a behave test. I'll close this for now. We can reopen if necessary
