### ISSUE TITLE
'peer.port' variable in 'core.yaml

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#1567]
## Description

Is the `peer.port` variable in `core.yaml` used anywhere? As far as I can tell, it isn't.
## Action to take

If it's not needed, I suggest removing it from the config file.

**Comment by bcbrock** [comment]
I agree #1401 If you have the time please remove it

**Comment by kchristidis** [comment]
Ah, hadn't seen your #1401 issue - sorry.

I'll go ahead and create a PR tomorrow that takes care of this and #1548.

**Comment by lehors** [comment]
I did some digging around this last night and peer/main.go also defines a flag peer-port on [line 242](https://github.com/hyperledger/fabric/blob/master/peer/main.go#L242) which doesn't seem to be used anywhere and have any actual interaction with the parameter set up in core.yaml, although I think it should if it were to be useful at all.

`flags.Int("peer-port", 30309, "Port this peer listens to for incoming connections")`

**Comment by bcbrock** [comment]
@lehors @kchristidis I don't believe any of those flags actually work. VIPER does not equate command line flags to YAML variables. I had an issue on this that I closed because I couldn't remember what the issue was - now you've reminded me #578

**Comment by lehors** [comment]
Interesting. I was tempted to dive deeper into this Viper setup so I would really understand and kind of decided not to but now you've got me even more interested...
