### ISSUE TITLE
syntax checks for execute transaction and query

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#157]
Need to figure out a a syntax first - (context, funcname, args...). 

Validate the request for syntax

Are we adding this to deployment spec for some level of static checking ?

**Comment by prjayach** [comment]
@muralisrini, I believe this is now complete. Can we close this?

**Comment by muralisrini** [comment]
We are probably not going to do type checks or parameter checks outside of chaincode - for now at least. We will leave checks to the chaincode. We can open an issue in future if we want to do that.

@binhn , @markparz ... I believe this can be closed as well.
