### ISSUE TITLE
security checks for execute transaction and query

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#158]
authentication and authorization. Need this at different points - at the time of request submission via CLI on peer, validator and also at the time of actual invocation through consensus

**Comment by muralisrini** [comment]
Don't think we need this any more... covered by security integration in general

**Comment by muralisrini** [comment]
Also, placeholder just like (dup) #279

**Comment by corecode** [comment]
I cannot find the part of code that makes sure that `CHAIN_QUERY` transactions are executed read only.  Is that functionality in place, or was this issue closed prematurely?

**Comment by muralisrini** [comment]
Its in place.look for "isTransaction" under chaincode folder (while the protection is right in the shim, validator does not trust that and implements the check again).
