### ISSUE TITLE
chaincode networkmode cannot be changed

### ISSUE THREAD

**Issue by yeasy** [hyperledger-archives/fabric#1582]
## Description

Container supports various network mode, and may even change in future. Currently, the chaincode only supported a fixed networkmode of "host" in the code, while this will prevent using coe (e.g., swarm) that supports overlay networking. 
## Describe How to Reproduce

Using coe to start the cluster, and deploy chaincode

**Comment by corecode** [comment]
Is this about allowing chaincode to talk to the network?

**Comment by yeasy** [comment]
@corecode It's about allowing chaincode to talk with its sourced peer node.

**Comment by yingfeng** [comment]
In this configuration

```
# The NetworkMode in HostConfig when starting a chaincode container
containerNetworkmode: host
```

Could I use some other kinds of docker networks such as flannel/calico ? 

For example, I plan to use calico networks to deploy fabric images across machines, and I create a network with name of `net1`, therefore I could start docker images in this way:

```
docker run --net net1 -tid imagename
```

However, when I configured `net1` in the `containerNetworkmode` part, I still get the chaincode deploy error:

```
07:47:43.958 [dockercontroller] Deploy -> ERRO 01c Error building Peer container: dial unix /var/run/docker.sock: connect: no such file or directory
07:47:44.029 [dockercontroller] Start -> ERRO 01d start-could not recreate container Post http://unix.sock/containers/create?name=dev-vp0-7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b: dial unix /var/run/docker.sock: connect: no such file or directory
```

**Comment by yeasy** [comment]
@yingfeng Actually, when u use overlay, you will meet this problem.
You need to config carefully the networkmode base on your SDN options.
calico also provide his own libnetwork plugin type.

**Comment by mastersingh24** [comment]
https://github.com/hyperledger/fabric/pull/1269  should cover this
