### ISSUE TITLE
Error while vagrant up

### ISSUE THREAD

**Issue by softlore** [hyperledger-archives/fabric#1585]
**Description**
      Getting a error message when vagrant up :-
==> default: Get:8 http://us.archive.ubuntu.com/ubuntu/ trusty/main cgroup-lite                                                                                                                 all 1.9 [3,918 B]
==> default: Err https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.11.1-0~trusty
==> default:   Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
==> default: Fetched 37.0 MB in 5min 37s (110 kB/s)
==> default: E
==> default: :
==> default: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.11.1-0~trusty_amd64.deb  Operation too slow. Less than 10 bytes/sec transferred the last 120 seconds
==> default: E
==> default: :
==> default: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Steps done:**
1) Installed Virtual Box
2) Installed Vagrant
3) Run "Vagrant up"

**Comment by muralisrini** [comment]
@gmk292 errors suggest slow/bad network ?

**Comment by srderson** [comment]
agree with @muralisrini. Try again and it may resolve the issue.

**Comment by softlore** [comment]
@muralisrini @srderson : you are correct. It worked.
