### ISSUE TITLE
hyphens in configuration are invalid for environment variables

### ISSUE THREAD

**Issue by rennman** [hyperledger-archives/fabric#1588]
Is it possible to change the hyphens in yaml config items to a character that is supported by the shell? In particular, bash does not support the use of '-' in variable names, so in core.yaml:
   `peer : validator : validity-period : verification`
   `ledger : blockchain : deploy: system-chaincode`

cannot be represented as a valid environment variable:
   `CORE_PEER_VALIDATOR_VALIDITY-PERIOD_VERIFICATION`
   `CORE_LEDGER_BLOCKCHAIN_DEPLOY-SYSTEM-CHAINCODE`

# CORE_PEER_VALIDATOR_VALIDITY-PERIOD_VERIFICATION=true
CORE_PEER_VALIDATOR_VALIDITY-PERIOD_VERIFICATION=true: command not found

**Comment by christo4ferris** [comment]
I would consider this a bug, as there's no means of over-riding these properties as advertised. I am closing this one in deference to #1309 which is the tracking issue for fixing and refactoring the whole configuration scheme.
