### ISSUE TITLE
System hangs under stress testing

### ISSUE THREAD

**Issue by yingfeng** [hyperledger-archives/fabric#1627]
## Description

I setup a simple stress testing environment, and use jmeter to perform the stress testing.  When I set the number of clients to a relative large number, the system hung and would not accept any request. Even if I stopped jmeter and wait for a long time, the system could still not recover.
### Setup the environment

Start up a single peer node

```
docker run --rm -it --name peer1 -e CORE_LOGGING_LEVEL=debug  -e CORE_VM_ENDPOINT=http://172.17.0.1:25 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger-peer peer node start
```

Deploy a chain code

```
{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID":{
        "path":"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
    },
    "ctorMsg": {
        "function":"init",
        "args":["a", "1000", "b", "2000"]
    }
  },
  "id": 1
}
```

Verify the chaincode could work correctly:

```
{
  "jsonrpc": "2.0",
  "method": "query",
  "params": {
      "type": 1,
      "chaincodeID":{
          "name":"7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b",
          "path":"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
      },
      "ctorMsg": {
         "function":"query",
         "args":["a"]
      }
  },
  "id": 5
}
```
### Setup Jmeter

Use http post to send the query json data as above.  So it's a very simple stress test. 
### Benchmark Result

When the number of Jmeter clients is set to 1000, the throughput of that single peer is relative ok: 2100 TPS, although not that high.
When the number of Jmeter clients is enlarged to 2000, the system will hang.

**Comment by bcbrock** [comment]
@yingfeng This report is incomplete - you need to provide more information before anyone can help you. For example, have you grep-ed the logs for error messages that might give a clue as to what happened? How long did the run take? Note that DEBUG logging generates so much output is it possible that your disks filled up or your system started to swap? How do you know it's hung? etc.

We recently added the fabric/tools/busywork directory. The busywork tools can be used for stress testing as well as correctness checking. You may want to give them a try as well.

**Comment by yingfeng** [comment]
Hi, @bcbrock there are no error outputs to the console. The system is hung no matter if `DEBUG` has been set, and you can not get any responses from other rest api clients until the process is restarted. Actually, reproducting is so easy since the hang happens immediately if the number of Jmeter clients is set to a large number.  If necessary, I could provide the JMX file here.

**Comment by muralisrini** [comment]
@yingfeng Two suggestions...
1. capture output in log file 
`
docker run --rm -it --name peer1 -e CORE_LOGGING_LEVEL=debug  -e CORE_VM_ENDPOINT=http://172.17.0.1:25 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger-peer peer node start 1>/tmp/peer.dbg.out 2>&1
`
2. after recreating SIQQUIT on the peer process would dump stack and quit. May provide some info. 
![image](https://cloud.githubusercontent.com/assets/14361488/15627631/1f8a074e-24b8-11e6-985c-5114b8621229.png)

/tmp/peer.dbg.out may help with more info.

**Comment by yingfeng** [comment]
@muralisrini 
This is the output snippet FYI:

```
02:55:12.656 [chaincode] Launch -> DEBU 1d60f chaincode is running(no need to launch) : 7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b
02:55:12.657 [rest] ProcessChaincode -> INFO 1d610 REST processing chaincode request...
02:55:12.657 [rest] processChaincodeInvokeOrQuery -> INFO 1d611 REST query chaincode...
02:55:12.657 [devops] createExecTx -> DEBU 1d612 Creating invocation transaction (bdc07d13-a40a-4115-874c-7984064df7f4)
02:55:12.657 [devops] invokeOrQuery -> DEBU 1d613 Sending invocation transaction (bdc07d13-a40a-4115-874c-7984064df7f4) to validator
02:55:12.657 [peer] sendTransactionsToLocalEngine -> DEBU 1d614 Marshalling transaction CHAINCODE_QUERY to send to local engine
02:55:12.657 [peer] sendTransactionsToLocalEngine -> DEBU 1d615 Sending message CHAIN_TRANSACTION with timestamp seconds:1464576912 nanos:657659841  to local engine
02:55:12.657 [chaincode] Launch -> DEBU 1d616 chaincode is running(no need to launch) : 7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b
02:55:12.657 [rest] ProcessChaincode -> INFO 1d617 REST processing chaincode request...
02:55:12.657 [rest] processChaincodeInvokeOrQuery -> INFO 1d618 REST query chaincode...
02:55:12.657 [devops] createExecTx -> DEBU 1d619 Creating invocation transaction (725a206d-ac0b-40ab-8b21-ab72783c87fd)
02:55:12.657 [devops] invokeOrQuery -> DEBU 1d61a Sending invocation transaction (725a206d-ac0b-40ab-8b21-ab72783c87fd) to validator
02:55:12.657 [peer] sendTransactionsToLocalEngine -> DEBU 1d61b Marshalling transaction CHAINCODE_QUERY to send to local engine
02:55:12.657 [peer] sendTransactionsToLocalEngine -> DEBU 1d61c Sending message CHAIN_TRANSACTION with timestamp seconds:1464576912 nanos:657889608  to local engine
02:55:12.657 [chaincode] Launch -> DEBU 1d61d chaincode is running(no need to launch) : 7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b
```

**Comment by yingfeng** [comment]
According to the tracking, I've found the system is hung due to the `createTxContext` within `sendExecuteMessage` of `core/chaincode/handler.go`

```
func (handler *Handler) sendExecuteMessage(msg *pb.ChaincodeMessage, tx *pb.Transaction) (chan *pb.ChaincodeMessage, error) {
    chaincodeLogger.Debug("[%s]Inside sendExecuteMessage1. Message %s", shortuuid(msg.Uuid), msg.Type.String())
    txctx, err := handler.createTxContext(msg.Uuid, tx)
    if err != nil {
        return nil, err
    }
    chaincodeLogger.Debug("[%s]Inside sendExecuteMessage2. Message %s", shortuuid(msg.Uuid), msg.Type.String())
```

Within the function of `createTxContext`, after I add some debug logs, I've found that there's a deadlock at `handler.Lock`, since only `createTxContext1` appear in the debug outputs

```
func (handler *Handler) createTxContext(uuid string, tx *pb.Transaction) (*transactionContext, error) {
    if handler.txCtxs == nil {
        return nil, fmt.Errorf("cannot create notifier for Uuid:%s", uuid)
    }
    chaincodeLogger.Debug("createTxContext1")
    handler.Lock()
    defer handler.Unlock()
    chaincodeLogger.Debug("createTxContext2")

```

**Comment by muralisrini** [comment]
@yingfeng thanks. Can you also provide /tmp/peer.dbg.out (containing logs and stack trace) as described from my previous comment please ?

**Comment by muralisrini** [comment]
@yingfeng just saw the instruction to produce stack trace was incorrect... should be SIGQUIT not "-9"

![image](https://cloud.githubusercontent.com/assets/14361488/15658532/7f6d958e-268b-11e6-90f0-ab39ce338c97.png)

Can you recreate the problem and attach /tmp/peer.dbg.out please ? Thanks!

**Comment by yingfeng** [comment]
@muralisrini The error outputs are the same without stack trace if SIGQUIT is sent. So this bug could not be defined as a `dead lock` since the program could exit normally, but it is blocked at the `handler.Lock()`

**Comment by muralisrini** [comment]
@yingfeng I'm confused... I assume you do get the stack with SIGQUIT captured in /tmp/peer.dbg.out ? If so can you attach it here please ?

**Comment by yingfeng** [comment]
@muralisrini 
Here are the three files attached:
I generate `peer.dbg.out` using `1.patch`, you could see the extra logging I added.  The `fabric.jmx` is the jmeter stress testing I was using.  Thanks~

PS, no Varant is used. The docker is started in baremetal.

[fabric.jmx.zip](https://github.com/hyperledger/fabric/files/290311/fabric.jmx.zip)
[1.patch.zip](https://github.com/hyperledger/fabric/files/290308/1.patch.zip)
[peer.dbg.out.zip](https://github.com/hyperledger/fabric/files/290310/peer.dbg.out.zip)

**Comment by yingfeng** [comment]
In golang programming language, double lock will lead to dead lock, and the system will quit with a panic error, for example:

```
package main  

import (  
    "fmt"  
    "sync"  
)  

func main() {  
    var l *sync.Mutex  
    l = new(sync.Mutex)  
    l.Lock()  
    fmt.Println("1")  
    l.Lock()  
}
```

This simple program will quit with panic error of `fatal error: all goroutines are asleep - deadlock!`

However, in fabric, there seems no panic error at all, for example, within the function of createTxContext, if I add double lock as following:

```
func (handler *Handler) createTxContext(uuid string, tx *pb.Transaction) (*transactionContext, error) {
    if handler.txCtxs == nil {
        return nil, fmt.Errorf("cannot create notifier for Uuid:%s", uuid)
    }
    chaincodeLogger.Debug("createTxContext1")
    handler.Lock()
    handler.Lock()
    chaincodeLogger.Debug("createTxContext2")
    defer handler.Unlock()
    .....
}
```

the system could even run with logs of `createTxContext1` only.
Such kind of hanging is just the same as what I met during the stress testing above.

**Comment by yingfeng** [comment]
@muralisrini This is another debug outputs after I sent SIGQUIT signal

[peer.dbg.out.zip](https://github.com/hyperledger/fabric/files/290907/peer.dbg.out.zip)

**Comment by muralisrini** [comment]
@yingfeng : can you verify/confirm the fix in the above PR please ? Btw, I think you suspected a problem in the send... though a little more involved, the suspicion was right on target :-) (assuming you can confirm the fix, that is.)

**Comment by yingfeng** [comment]
@muralisrini Confirmed, this PR has fixed this issue, thank you~

**Comment by muralisrini** [comment]
Perfect, thank you!
