### ISSUE TITLE
What is the audience for the Travis CI README?

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#1636]
## Description

It seems like the first three quarters of the document are addressed to the repo maintainers. I can't figure out why the developers are exposed to this info, but I may be missing something.

I'd argue that the only relevant info to them is towards the end, in the "How to skip Travis Build execution for PRs" section (which probably belongs to either `CONTRIBUTING.md` or `docs/dev-setup/install.md`).

**Comment by christo4ferris** [comment]
agree, especially as Travis is effectively deprecated at this point. As we transition to Jenkins, this sort of information (the first 3/4 of the readme sort) really should be captured in the CI repo in Gerritt. https://github.com/hyperledger/fabric/blob/master/docs/TravisCI_Readme.md

**Comment by christo4ferris** [comment]
@kchristidis I've left the TravisCI_Readme but removed it from the documentation. It is deprecated anyway as we will be affecting full transition to Jenkins soon. Closing
