### ISSUE TITLE
CoreAPI.md needs more detailed request/response examples

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#1638]
## Description

The CoreAPI.md document currently doesn't contain comprehensive REST request/response examples for all the endpoints. The required examples already exist within the fabric protocol-spec.md document in section "6.2 REST API".

https://github.com/hyperledger/fabric/blob/master/docs/protocol-spec.md

As pointed out by @kchristidis it would be beneficial to rework CoreAPI.md doc to make these examples more accessible for our users.

**Comment by christo4ferris** [comment]
@angrbrd you still on this?

**Comment by angrbrd** [comment]
I have created a matching issue in Jira here: https://jira.hyperledger.org/browse/FAB-123

Closing. Thanks!
