### ISSUE TITLE
API Inconsistency: REST /network/peers vs. CLI network list [Also, result is not very useful]

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1647]
## Description

I noticed just now that there is an inconsistency between two ways of getting what should be the same information:
- REST API `/network/peers` returns info for all peers
- CLI `peer network list` excludes the peer running the request.

I prefer the REST API's way of giving back all known information, even if seemingly redundant.

**Comment by christo4ferris** [comment]
+1 Especially as currently the CLI is baked into the peer... at some point, they will be distinct (one would hope).

**Comment by yeasy** [comment]
+1, should return all nodes!

**Comment by bcbrock** [comment]
I would also add that the addresses returned by this call are the gRPC ports. I understand that this is how the peers communicate with each other, but these addresses are not very useful for HTTP-based applications. Related to issue #1646.

**Comment by christo4ferris** [comment]
seems like what we need is some sort of network status monitor, with the peers registering themselves and then periodically either phoning home or being polled for their status and possibly some metrics.

**Comment by angrbrd** [comment]
I have opened a matching bug in Jira here: https://jira.hyperledger.org/browse/FAB-122

@christo4ferris please close out this issue. Thanks!
