### ISSUE TITLE
Implement broadcast mechanism among validating peers

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#166]
If I'm reading Jeff's code right, the current `broadcast()` implementation is a unicast with the leader (`leaderHandler.SendMessage()`).

Add the required logic in the `consensus` layer so that each VP maintains a set of streams to the rest of the VPs (including the leader). Then have the `broadcast()` function (that is part of the `CPI` interface) send a message on all of these streams.

**Comment by binhn** [comment]
This function should be on the new communication layer that will take care of the actual sending of the message. The consensus service should just call that function.

**Comment by kchristidis** [comment]
You are right. Will close this issue.
