### ISSUE TITLE
cannot run membersrvc after modifying ca.proto file.

### ISSUE THREAD

**Issue by nitesh7sid** [hyperledger-archives/fabric#1661]
I added one more method inside ECAA service: rpc RegisterAffiliationGroup(RegisterAffiliationGroupReq) returns (CAStatus);
after i build the go file ca.proto.go and start my membersrvc it gives me error saying 
# github.com/hyperledger/fabric/membersrvc/ca

ca/eca.go:193: undefined: "github.com/hyperledger/fabric/membersrvc/protos".Regi
sterECAPServer. How to resolve that?

**Comment by JonathanLevi** [comment]
If you check-in your work to a branch, I can take a (brief) look.

**Comment by JonathanLevi** [comment]
@nitesh7sid Let me know if you require any further assistance here, otherwise, can we close this item?

**Comment by srderson** [comment]
Closing. @nitesh7sid please reopen if you have more info. Not sure if you worked with @JonathanLevi directly to resolve.

**Comment by JonathanLevi** [comment]
Thank you @srderson.
