### ISSUE TITLE
LoZ Install GRPC

### ISSUE THREAD

**Issue by xbh2015** [hyperledger-archives/fabric#1695]
## Description

As it is shown in the  fabric/images/base/scripts/common/setup.sh file, when we run it in LoZ ,there is a tip that protobufs wont compile on 390, missing atomic call .Is that mean we can not use it in LoZ ?

**Comment by christo4ferris** [comment]
@xbh2015 @vpaprots is this still an issue for s390x? My understanding is that you have resolved the issue with #2228. I'm going to close this (since it won't be closed automatically) Please reopen if you disagree.
