### ISSUE TITLE
Inconsistent state after writing transactions to multiple peers concurrently

### ISSUE THREAD

**Issue by yingfeng** [hyperledger-archives/fabric#1701]
## Description

According to the definition of consensus, each fabric peer should have a consistent state at all time, or else, the decentralized ledger could not work at all. However, after I setup a fabric network, and perform the stress test, I've found the state of all fabric peer nodes are inconsistent at all.
## Describe How to Reproduce
- Setup N fabric peer nodes, and I've tried N=2, N=3, N=4, each of the peer adopts the default consensus plugin---classic PBFT
- Deploy a chaincode `chaincode_example02`:

```
{
  "jsonrpc": "2.0",
  "method": "deploy",
  "params": {
    "type": 1,
    "chaincodeID":{
        "path":"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
    },
    "ctorMsg": {
        "function":"init",
        "args":["a", "1000", "b", "2000"]
    }
  },
  "id": 1
}
```
- The initial state of each peer is consistent:

```
{
  "jsonrpc": "2.0",
  "method": "query",
  "params": {
    "type": 1,
    "chaincodeID":
    {
        "name":"7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b",
        "path":"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
    },
    "ctorMsg": {
        "function":"query",
        "args":["a"]
    }
  },
  "id": 5
}
```

The initial status for all peer nodes is:

```
{"jsonrpc":"2.0","result":{"status":"OK","message":"1000"}
```
- Perform stress invoking tests to two peer nodes concurrently, say peer2 and peer4:

```
{
  "jsonrpc": "2.0",
  "method": "invoke",
  "params": {
    "type": 1,
    "chaincodeID":
    {
        "name":"7b07c59e9b9405c1aef33493b63b9a766d9bb836989ded1730052de650aa8ce5654274d148ceff96a4e5bd43bca26aba099f55c400e4befdc8b2ee4c0a94e30b",
        "path":"github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02"
    },
    "ctorMsg": {
        "function":"approach",
        "args":["a", "1000", "b", "2000"]
    }
  },
  "id": 3
}
```
- Stop the stress invoking test, wait for some time, and query each peer's status, then I've got 4 different result using the same query request as above:

```
{"jsonrpc":"2.0","result":{"status":"OK","message":"-507530"}
{"jsonrpc":"2.0","result":{"status":"OK","message":"-465020"}
{"jsonrpc":"2.0","result":{"status":"OK","message":"-518570"}
{"jsonrpc":"2.0","result":{"status":"OK","message":"-500030"}
```

I could see some errors in the outputs of each peer:

```
09:13:04.063 [peer] handleChat -> ERRO 11f95 Error handling message: Message channel for name:"vp1"  full, rejecting
09:13:04.063 [consensus/handler] HandleMessage -> ERRO 11f96 Failed to queue consensus message because: Message channel for name:"vp1"  full, rejecting
09:13:04.063 [peer] handleChat -> ERRO 11f97 Error handling message: Message channel for name:"vp1"  full, rejecting
```

**Comment by corecode** [comment]
@jyellick I don't think we should be dropping messages when the channel is full - this basically turns TCP back into UDP.  We need a solid story for flow control.

One way would be to block there and run state transfer over a different GRPC stream (could be the same GRPC connection).  That way we don't buffer much, and any slowness in processing propagates back to the senders.

**Comment by corecode** [comment]
@yingfeng could you provide a debug log for all the peers?

**Comment by tuand27613** [comment]
Nishi has reproduced the issue and will be adding the debug logs soon.

The test program pushed 10K invokes ( 2 threads doing 5K each ). We're seeing that in some cases not all 10K invokes are being processed. Not seeing as much divergence in the results from the 4 peers, usually 1 of the 4 peers is showing a smaller chain height.

**Comment by 2016Nishi** [comment]
During my run query results matched in 3 peers and PEER3 had a slightly higher number for a and b values. Please find attached log files for this run here.

Results in a and b PEER0 :  99066 90934
Results in a and b PEER1 :  99066 90934
Results in a and b PEER2 :  99066 90934
Results in a and b PEER3 :  99063 90937

In this particular run only 934 requests were processed even though we programmed for 10K invokes as Tuan mentioned. In other instances ~400-1000 requests were processed.

To add to Tuan's comments: It was also observed that few times peers (once a single peer, once two peers) did not return results on query at the end of invokes with the following message:
"POST /chaincode returned code =-32003 message=Query failure
    data=Error when querying chaincode: Error: state may be inconsistent, cannot query"

[PEER3_PEER2_LOGS.zip](https://github.com/hyperledger/fabric/files/298523/PEER3_PEER2_LOGS.zip)
[PEER1_PEER0_LOGS.zip](https://github.com/hyperledger/fabric/files/298524/PEER1_PEER0_LOGS.zip)

Ran test with codebase: 0a7f3e2

**Comment by jyellick** [comment]
@corecode With respect to dropping transactions when the channel fills, this was discussed extensively with @jeffgarratt, @binhn, and others.  The argument loosely, was that some portion of the system needs to push back, we cannot buffer indefinitely.  If we were to block on channel writes here, then the gRPC buffer would back up, and eventually gRPC would have to start discarding requests.  I'm not a gRPC expert, so maybe I am missing some feature here, but it seems like separate gRPC streams would only shift the point of the problem (from our buffer, into gRPCs).

**Comment by vukolic** [comment]
What @2016Nishi got is expected behavior w/o proper flow control - requests may be dropped but not more than 1 VP response/state should be inconsistent (1 is very much ok - for the moment).

That said, what @yingfeng reported is really worrysome (state inconsistency) - so since this issue was not reproduced yet - we still need logs from that run.

**Comment by tuand27613** [comment]
@vukolic  a similar inconsistent state issue #1545

**Comment by vukolic** [comment]
ack - just saw that

**Comment by tuand27613** [comment]
@yingfeng  could you retry with N=4 and logging_level=debug and attach the logs for all peers ?

**Comment by yingfeng** [comment]
Hi, I've started 4 peers on 4 machines and reproduce it. Logs are attached, and the fabric.jmx is the jmeter performance test file

```
docker run --rm -it --net net1 --name peer10 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true hyperledger-peer peer node start 1>/tmp/peer0.out 2>&1

docker run --rm -it --net net1 --name peer11 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp1 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=192.168.0.41:30303 hyperledger-peer peer node start 1>/tmp/peer1.out 2>&1

docker run --rm -it --net net1 --name peer12 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp2 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=192.168.0.41:30303 hyperledger-peer peer node start 1>/tmp/peer2.out 2>&1

docker run --rm -it --net net1 --name peer13 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp3 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_PEER_DISCOVERY_ROOTNODE=192.168.0.41:30303 hyperledger-peer peer node start 1>/tmp/peer3.out 2>&1
```

[logs.zip](https://github.com/hyperledger/fabric/files/301658/logs.zip)

**Comment by yingfeng** [comment]
These are logs after `CORE_LOGGING_LEVEL=debug` has been set. They are much larger

[peer0.out.zip](https://github.com/hyperledger/fabric/files/301805/peer0.out.zip)

**Comment by yingfeng** [comment]
[peer1.out.zip](https://github.com/hyperledger/fabric/files/301806/peer1.out.zip)

**Comment by yingfeng** [comment]
[peer2.out.zip](https://github.com/hyperledger/fabric/files/301808/peer2.out.zip)

**Comment by yingfeng** [comment]
The logs are so big and each time only 10MB is permited to upload
[peer3.out.zip](https://github.com/hyperledger/fabric/files/301811/peer3.out.zip)

**Comment by corecode** [comment]
You are running with noops "consensus".  Please switch to pbft batch consensus.

**Comment by vukolic** [comment]
@yingfeng in the meantime pls close the issue - as it is not an issue to get different states with NOOPS. Feel free to reopen if the problem reappears with pbft batch

**Comment by yingfeng** [comment]
The above result is based on the configuration of `config:noops`, as a result, `pbft` is not enabled as a consensus plugin.   When `pbft` is enabled, this issue does not appear.
