### ISSUE TITLE
Error querying chaincode: Failed to launch chaincode spec when running chaincode in dev environment 

### ISSUE THREAD

**Issue by arjhunthiagarajan** [hyperledger-archives/fabric#1706]
I was able to set up the development environment successfully based on the instructions provided here - https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devenv.md

When I try to run the chaincode_example02 in the dev environment based on the instructions here - I get an error message - _Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode mycc))"_

**Steps to replicate:**
1. Vagrant terminal 1 - make and start peer node

![screen shot 2016-06-04 at 1 03 13 am](https://cloud.githubusercontent.com/assets/19144163/15783131/3cc77a0c-29f0-11e6-8fc6-3620dcd62651.png)
1. Vagrant terminal 2 - register chaincode with validating peer

![screen shot 2016-06-04 at 1 05 43 am](https://cloud.githubusercontent.com/assets/19144163/15783187/7cd604c4-29f0-11e6-9e92-70ab7a28857e.png)
1. Vagrant terminal 3 - Issue a deploy command via CLI

When issuing a deploy command, I do get a response back on Vagrant terminal 1 but the console (terminal 3) does not update. 

![screen shot 2016-06-04 at 1 09 07 am](https://cloud.githubusercontent.com/assets/19144163/15783299/f4d6c2ce-29f0-11e6-9f3c-af77a4898662.png)

This occurs for the invoke function as well

![screen shot 2016-06-04 at 1 11 42 am](https://cloud.githubusercontent.com/assets/19144163/15783397/52660d78-29f1-11e6-9a2f-69be949d26b7.png)

When I issue a query function call, it throws an error. 
_Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode mycc))"_

Please note that this is just a simple dev environment set up and not the devnet set up.

![screen shot 2016-06-04 at 1 14 04 am](https://cloud.githubusercontent.com/assets/19144163/15783473/a75a3642-29f1-11e6-8304-5741023c9bd2.png)

Any clues on troubleshooting this issue will be very much appreciated.

Thanks!
Arjhun

**Comment by himanshutyagi36** [comment]
I'm facing a similar issue. Did you find out what was wrong ?

**Comment by muralisrini** [comment]
@arjhunthiagarajan @tortuga90 typo in env variable... should be CORE_CHAINCODE_ID_NAME=mycc (not CODE_CHAINCODE_ID_NAME=mycc)

**Comment by himanshutyagi36** [comment]
@muralisrini I'm using bluemix network and Swagger API to deploy,invoke and query my chaincode. The deploy and invoke requests are working fine, but when I run queryspec, I keep getting the following error 
<img width="1119" alt="screen shot 2016-07-10 at 11 00 20 am" src="https://cloud.githubusercontent.com/assets/5171506/16714362/71893f2c-468e-11e6-8330-c1171de4657e.png">
Validating peer log
<img width="1127" alt="screen shot 2016-07-10 at 11 01 29 am" src="https://cloud.githubusercontent.com/assets/5171506/16714363/7194a0f6-468e-11e6-9a21-d098c99aa8df.png">

Is this a network issue or some problem with my chaincode. ([link](https://github.com/tortuga90/chaincode/blob/master/test/test.go) to chaincode)

**Comment by arjhunthiagarajan** [comment]
@muralisrini that was it mate. Thanks for the pointer

**Comment by arjhunthiagarajan** [comment]
@tortuga90 the typo was the issue
