### ISSUE TITLE
ERRO 03c Error building Peer container: cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by rajaduggimpudi** [hyperledger-archives/fabric#1707]
## Description

I was trying to deploy chaincode using the following command after logging in with username 'jim'

`peer chaincode deploy -p ../src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function": "init", "Args": ["a", "100", "b", "200"]}' -u jim`

and noticed the (Error building Peer container: cannot connect to Docker endpoint) error in validating peer log. 

Brief summary of vp0 log: 

15:50:03.823 [crypto] Login -> INFO 024 Registering client [jim] with name [jim]...
15:50:03.951 [crypto] register -> INFO 025 [client.jim] Register crypto engine...
15:50:03.953 [crypto] register -> INFO 026 [client.jim] Register crypto engine...done.
15:50:03.953 [crypto] Login -> INFO 027 Registering client [jim] with name [jim]...done!
15:50:47.977 [devops] getChaincodeBytes -> DEBU 028 Received build request for chaincode spec: type:GOLANG chaincodeID:<path:"../src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" > secureContext:"jim" confidentialityLevel:CONFIDENTIAL
15:50:47.990 [container] WriteGopathSrc -> INFO 029 rootDirectory = /opt/gopath/src
15:50:53.029 [devops] Deploy -> DEBU 02a Initializing secure devops using context jim
15:50:53.030 [crypto] Deploy -> INFO 02b Initializing client [jim]...
15:50:59.174 [crypto] Deploy -> INFO 02c Initializing client [jim]...done!
15:50:59.174 [devops] Deploy -> DEBU 02d **Creating secure transaction** 5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
15:50:59.506 [devops] Deploy -> DEBU 02e **Sending deploy transaction** (5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5) to validator
15:50:59.507 [peer] sendTransactionsToLocalEngine -> DEBU 02f **Marshalling transaction CHAINCODE_DEPLOY to send to local engine**
15:50:59.525 [peer] **sendTransactionsToLocalEngine** -> DEBU 030 **Sending message** CHAIN_TRANSACTION with timestamp seconds:1464969059 nanos:525195839  to local engine
15:50:59.525 [consensus/noops] RecvMsg -> DEBU 031 **Handling Message of type: CHAIN_TRANSACTION**
15:50:59.530 [consensus/noops] broadcastConsensusMsg -> DEBU 032 **Broadcasting CONSENSUS**
15:50:59.551 [consensus/noops] RecvMsg -> DEBU 033 Sending to channel tx uuid: %!(EXTRA string=5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5)
15:50:59.551 [crypto] CloseClient -> INFO 034 Closing client [jim]...
15:51:00.566 [consensus/noops] handleChannels -> DEBU 035 Process block due to time
15:51:00.566 [consensus/noops] processTransactions -> DEBU 036 Starting TX batch with timestamp: seconds:1464969060 nanos:566702054
15:51:00.566 [consensus/noops] processTransactions -> DEBU 037 Executing batch of 1 transactions with timestamp seconds:1464969060 nanos:566702054
15:51:00.784 [chaincode] getArgsAndEnv -> DEBU 038 Executable is /opt/gopath/bin/5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
15:51:00.784 [chaincode] DeployChaincode -> DEBU 039 **deploying chaincode** 5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5(networkid:dev,peerid:vp0)
15:51:00.784 [container] lockContainer -> DEBU 03a **waiting for container**(dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5) lock
15:51:00.785 [container] lockContainer -> DEBU 03b **got container** (dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5) lock
**#15:51:00.785 [dockercontroller] Deploy -> ERRO 03c Error building Peer container: cannot connect to Docker endpoint**
15:51:00.785 [container] unlockContainer -> DEBU 03d **container lock deleted**(dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5)
15:51:00.786 [state] TxBegin -> DEBU 03e txBegin() for txUuid [5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5]
15:51:00.793 [chaincode] getArgsAndEnv -> DEBU 03f Executable is /opt/gopath/bin/5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
15:51:00.793 [chaincode] launchAndWaitForRegister -> DEBU 040 **start container**: 5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5(networkid:dev,peerid:vp0)
15:51:00.793 [container] lockContainer -> DEBU 041 **waiting for container**(dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5) lock
15:51:00.793 [container] lockContainer -> DEBU 042 **got container** (dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5) lock
15:51:00.794 [dockercontroller] Start -> DEBU 043 **Cleanup container** dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
15:51:00.794 [dockercontroller] stopInternal -> DEBU 044 **Stop container** dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5(cannot connect to Docker endpoint)
15:51:00.794 [dockercontroller] stopInternal -> DEBU 045 **Kill container** dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5 **(cannot connect to Docker endpoint)**
15:51:00.795 [dockercontroller] stopInternal -> DEBU 046 **Remove container** dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5 (**cannot connect to Docker endpoint**)
15:51:00.795 [dockercontroller] Start -> DEBU 047 **Start container** dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
15:51:00.795 [dockercontroller] createContainer -> DEBU 048 **Create container**: dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5
**# 15:51:00.796 [dockercontroller] Start -> ERRO 049 start-could not recreate container cannot connect to Docker endpoint**
15:51:00.796 [container] unlockContainer -> DEBU 04a container lock deleted(dev-vp0-5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5)
15:51:00.796 [chaincode] LaunchChaincode -> DEBU 04b launchAndWaitForRegister failed Error starting container: cannot connect to Docker endpoint
15:51:00.797 [state] TxFinish -> DEBU 04c txFinish() for txUuid [5b748f65c2a101da043cdd1448d84dbdcee7bb814a3f13994a270e26d5e8aa791b8c031c14d0578512b988891394f01f6fb0a4a63119c171868713aad1a9f3d5], txSuccessful=[false]
15:51:00.797 [state] GetHash -> DEBU 04d Enter - GetHash()
15:51:00.797 [buckettree] ComputeCryptoHash -> DEBU 04e Enter - ComputeCryptoHash()
15:51:00.797 [buckettree] ComputeCryptoHash -> DEBU 04f Returing existing crypto-hash as recomputation not required
15:51:00.797 [state] GetHash -> DEBU 050 Exit - GetHash()
15:51:00.797 [consensus/noops] processTransactions -> DEBU 051 Committing TX batch with timestamp: seconds:1464969060 nanos:566702054
15:51:00.797 [state] GetHash -> DEBU 052 Enter - GetHash()
15:51:00.798 [buckettree] ComputeCryptoHash -> DEBU 053 Enter - ComputeCryptoHash()
15:51:00.798 [buckettree] ComputeCryptoHash -> DEBU 054 Returing existing crypto-hash as recomputation not required
15:51:00.798 [state] GetHash -> DEBU 055 Exit - GetHash()
15:51:00.950 [indexes] addIndexDataForPersistence -> DEBU 056 Indexing block number [1] by hash = [7b11740b20e0abb29d7839aa92bcd554817317ea532438e4407a06852c21e4534a163d743566c3dce1a04941a0711e43b5b15b587e3e9884859239d7dfc4b1de]
15:51:00.950 [state] AddChangesForPersistence -> DEBU 057 state.addChangesForPersistence()...start
15:51:00.950 [state] AddChangesForPersistence -> DEBU 058 Adding state-delta corresponding to block number[1]
15:51:00.951 [state] AddChangesForPersistence -> DEBU 059 Not deleting previous state-delta. Block number [1] is smaller than historyStateDeltaSize [500]
15:51:00.951 [state] AddChangesForPersistence -> DEBU 05a state.addChangesForPersistence()...finished
15:51:00.988 [ledger] resetForNextTxGroup -> DEBU 05b resetting ledger state for next transaction batch
15:51:00.988 [buckettree] ClearWorkingSet -> DEBU 05c Enter - ClearWorkingSet()
**15:51:00.988 [ledger] sendProducerBlockEvent -> ERRO 05d Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group**
15:51:01.019 [consensus/noops] getBlockData -> DEBU 05e Preparing to broadcast with block number 2
15:51:01.038 [consensus/noops] getBlockData -> DEBU 05f Got the delta state of block number 2
15:51:01.038 [consensus/noops] notifyBlockAdded -> DEBU 060 Broadcasting Message_SYNC_BLOCK_ADDED to non-validators
## Describe How to Reproduce

To reproduce the issue, make the following changes in core.yaml file
mode: net
privacy:true
security enabled:true

Use the tlsca.cert file generated by CA under  /var/hyperledger/production/.membersrvc

Run the following commands from within validating peer container

export CORE_PEER_ADDRESS=172.17.0.3:30303
peer login jim
peer chaincode deploy -p ../src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function": "init", "Args": ["a", "100", "b", "200"]}' -u jim

This successfully returns the computed hash, however validating peer log appears to have docker container end-point error. 

Please advice. 

Thanks in advance !!

**Comment by mastersingh24** [comment]
@rajaduggimpudi  - can you share the start command you used for the validating peer?  Likely you don't have the vm endpoint (aka docker host) parameter configured correctly or your docker daemon is not configure correctly to listen on a remote port.

**Comment by rajaduggimpudi** [comment]
@mastersingh24 ~ Thanks for the follow-up. Following is the command

```
docker run --name=vp0 \
       --restart=unless-stopped \
       -v $SCRIPT_DIR:/local-dev \
       -p 5000:5000 \
       -p 30303:30303 \
       -e CORE_PEER_ID=vp0 \
       -e CORE_VM_ENDPOINT=http://172.17.0.1:4243\
       -e CORE_PEER_ADDRESS=http://172.17.0.3:30303 \
       joequant/hyperledger peer peer >& vp0.log &
```

**Comment by bcbrock** [comment]
@rajaduggimpudi We switched to using the standard Docker port 2375 several weeks ago. Try changing 4243 to 2375.

**Comment by rajaduggimpudi** [comment]
Sure, i'll give this a try

**Comment by rajaduggimpudi** [comment]
@bcbrock That doesn't seem to work either. I changed 4243 port to 2375 and ran the command but still see the same issue. Please advice !

**Comment by bcbrock** [comment]
Are you sure Docker is running? If so, how is it configured?

**Comment by rajaduggimpudi** [comment]
@bcbrock: Actually, i tried mounting with the following parameter in docker run command and that seem to have worked.

`-v /var/run/docker.sock:/var/run/docker.sock \`

Thanks for the help !

**Comment by christo4ferris** [comment]
closing this as resolved. thanks
