### ISSUE TITLE
Test using ConfidentialityProtocolVersion 1.1

### ISSUE THREAD

**Issue by andresgaragiola** [hyperledger-archives/fabric#1718]
I have fixed #1702 in #1717 but test using ConfidentialityProtocolVersion 1.1 fails. 
## Description

Added tests in crypto_test.go using ConfidentialityProtocolVersion 1.1 fails. Is required fix ConfidentialityProtocolVersion 1.1 errors. 
## Describe How to Reproduce

Enable commented test to ConfidentialityProtocolVersion 1.1 included in #1717 a run test on crypto_test.go

**Comment by christo4ferris** [comment]
@andresgaragiola the commented test scenario 3 (and the uncommented scenario 2) are no longer in the code base. Are there still plans to address this missing coverage? @JonathanLevi

**Comment by andresgaragiola** [comment]
@christo4ferris In the case of commented test scenario 3 is not more required since confidentiality 1.1 was removed. The scenario 2 was removed due to problems with CI build (MT tests are very long and travis fails), in the other hand MT is currently not used. From my point of view this issue should be closed and a new issue should be open to address the clean up of MT code.

**Comment by christo4ferris** [comment]
awesome, thanks closing
