### ISSUE TITLE
node hlc-tester.js module.js:338     throw err;           ^ Error: Cannot find module './lib/hlc'

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1759]
## Description

When trying to execute hlc-tester.js, it fails:

vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t$ node hlc-tester.js
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/hlc'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/t/node_modules/hlc/index.js:20:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Here is the console:
$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Wed Jun  8 18:39:40 UTC 2016
  
  System load:  0.0                Processes:              103
  Usage of /:   11.1% of 38.75GB   Users logged in:        1
  Memory usage: 9%                 IP address for eth0:    10.0.2.15
  Swap usage:   0%                 IP address for docker0: 172.17.0.1
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/

**\* System restart required ***
Last login: Wed Jun  8 18:39:40 2016 from 10.0.2.2
vagrant@hyperledger-devenv:v0.0.10-738866c:~$ pwd
/home/vagrant
vagrant@hyperledger-devenv:v0.0.10-738866c:~$ cd $GOPATH/src/github.com/hyperledger/fabric
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric$ pwd
/opt/gopath/src/github.com/hyperledger/fabric
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric$ cd sdk/no de
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric/sdk/node$  cd test/system
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/t est/system$ ls
hlc-tester.js  test.json
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/t est/system$ mkdir /tmp/t
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/t est/system$ cp \* /tmp/t
vagrant@hyperledger-devenv:v0.0.10-738866c:/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/t est/system$ cd /tmp/t
vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t$ npm install hlc

> sleep@3.0.1 install /tmp/t/node_modules/hlc/node_modules/sleep
> node-gyp rebuild

make: Entering directory `/tmp/t/node_modules/hlc/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/obj.target/node_sleep.node
  COPY Release/node_sleep.node
make: Leaving directory`/tmp/t/node_modules/hlc/node_modules/sleep/build'
/

> grpc@0.13.2-pre1 install /tmp/t/node_modules/hlc/node_modules/grpc
> node-pre-gyp install --fallback-to-build

[grpc] Success: "/tmp/t/node_modules/hlc/node_modules/grpc/src/node/extension_binary/grpc_node.node " is installed via remote
hlc@0.0.2 node_modules/hlc
├── fs@0.0.2
├── uuidv4@0.3.1
├── json-stringify-safe@5.0.1
├── js-sha3@0.5.2
├── crypto@0.0.3
├── asn1@0.2.3
├── jssha@2.1.0
├── node-uuid@1.4.7
├── events@1.1.0
├── bn.js@4.11.4
├── node.extend@1.1.5 (is@3.1.0)
├── jsrsasign@5.0.12
├── util@0.10.3 (inherits@2.0.1)
├── asn1js@1.2.12
├── debug@2.2.0 (ms@0.7.1)
├── elliptic@6.2.8 (brorand@1.0.5, inherits@2.0.1, hash.js@1.0.3)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── sleep@3.0.1 (nan@2.3.5)
├── aes-js@1.0.0
├── pkijs@1.3.23
├── tape@4.5.1 (inherits@2.0.1, has@1.0.1, defined@1.0.0, resumer@0.0.0, deep-equal@1.0.1, through@ 2.3.8, function-bind@1.1.0, object-inspect@1.1.0, minimist@1.2.0, resolve@1.1.7, glob@7.0.3, string .prototype.trim@1.1.2)
├── sjcl@1.0.3
└── grpc@0.13.2-pre1 (nan@2.3.5, lodash@3.10.1, protobufjs@4.1.3)
vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t$ pwd
/tmp/t
vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t$ ls
hlc-tester.js  node_modules  test.json
vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t$ node hlc-tester.js
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/hlc'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/t/node_modules/hlc/index.js:20:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t/node_modules/hlc$ node --version
v0.12.7
vagrant@hyperledger-devenv:v0.0.10-738866c:/tmp/t/node_modules/hlc$
## Describe How to Reproduce

1.Install hlc in /tmp/t
2.Invoke it:   node hlc-tester

**Comment by adecaro** [comment]
@jjjjibm, I have searched in the current master and I haven't found any file called _hlc-tester.js_. Am I missing something?

**Comment by jjjjibm** [comment]
@adecaro,@keithsmith can point you to the code.  He was executing his code on my laptop when we saw this error.

**Comment by jjjjibm** [comment]
Hi Angelo,
I replied in the issue.  Here is one version of the code, but may not be
the one Keith was executing on my laptop:

https://github.com/smithbk/fabric/tree/issue-1186/sdk/node/test/system

Janet C. Wolf
Websphere Cloud Development and Test

**Comment by adecaro** [comment]
@jjjjibm Sorry for the late reply. That file is not available anymore in the current master.

**Comment by smithbk** [comment]
Janet, you simply need to:
    npm install -g hlc
And then type
    hlc test <test.json>
A sample test.json file is at fabric/sdk/node/bin/test.json

hlc-tester.js no longer exists.

**Comment by christo4ferris** [comment]
@jjjjibm seems like this can be closed with @smithbk's last comment. Please reopen if you disagree
