### ISSUE TITLE
Transactions are not invoked in network with 4 validation peers (pbft consensus plugin)

### ISSUE THREAD

**Issue by grbulat** [hyperledger-archives/fabric#1767]
## Description

I am trying to setup environment with 4 validation peers ( **pbft** consensus plugin ) in plain virtual machines (without any Docker) and follow the descriptions described [here](https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md.).
But when I do 'query' (after deploy and invoke operations of course) I have got an error 'Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Could not get deployment transaction for mycc - LedgerError - ResourceNotFound: ledger: resource not found)"'.  
I have just the following log messages from chaincode_example02:
`10:58:22.549 [shim] DEBU : Peer address: 0.0.0.0:30303
10:58:22.550 [shim] DEBU : os.Args returns: [./chaincode_example02]  
10:58:22.550 [shim] DEBU : Registering.. sending REGISTER  
10:58:22.552 [shim] DEBU : []Received message REGISTERED from shim  
10:58:22.552 [shim] DEBU : []Handling ChaincodeMessage of type: REGISTERED(state:created)  
10:58:22.552 [shim] DEBU : Received REGISTERED, ready for invocations  
`
Logs from peer:  
`11:03:40.713 [devops] Deploy -> DEBU 27f Creating deployment transaction (mycc)
11:03:40.713 [devops] Deploy -> DEBU 280 Sending deploy transaction (mycc) to validator
11:03:40.713 [peer] sendTransactionsToLocalEngine -> DEBU 281 Marshalling transaction CHAINCODE_DEPLOY to send to local engine
11:03:40.714 [peer] sendTransactionsToLocalEngine -> DEBU 282 Sending message CHAIN_TRANSACTION with timestamp seconds:1465470220 nanos:714045682  to local engine
11:03:40.714 [consensus/obcpbft] RecvMsg -> INFO 283 New consensus request received
11:03:40.714 [peer] SendMessage -> DEBU 284 Sending message to stream of type: CONSENSUS 
11:03:40.714 [peer] func1 -> DEBU 285 Sending 72 bytes to 0.0.0.0:30303 took 133.771µs
11:03:40.714 [peer] Broadcast -> DEBU 286 Broadcast took 185.31µs
11:03:40.714 [consensus/obcpbft] ProcessEvent -> DEBU 287 Replica 0 processing event
11:03:40.714 [consensus/obcpbft] ProcessEvent -> DEBU 288 Replica 0 received incoming message from 0
11:03:40.714 [consensus/obcpbft] ProcessEvent -> DEBU 289 Replica 0 processing event
11:03:40.714 [consensus/obcpbft] recvRequest -> DEBU 28a Replica 0 received request: KSh6+6VJvSzr+olDe8LZ1vK8KieVtU1jcqUAP67Jr/Th1Zpg7omBBdn2jKdRx1OFUYMhgRBox31E9sEAO7Guqw==
11:03:40.714 [consensus/obcpbft] softStartTimer -> DEBU 28b Replica 0 soft starting new view timer for 2s: new request KSh6+6VJvSzr+olDe8LZ1vK8KieVtU1jcqUAP67Jr/Th1Zpg7omBBdn2jKdRx1OFUYMhgRBox31E9sEAO7Guqw==
11:03:40.714 [consensus/obcpbft] sendPrePrepare -> DEBU 28c Replica 0 is primary, issuing pre-prepare for request KSh6+6VJvSzr+olDe8LZ1vK8KieVtU1jcqUAP67Jr/Th1Zpg7omBBdn2jKdRx1OFUYMhgRBox31E9sEAO7Guqw==
11:03:40.714 [consensus/obcpbft] sendPrePrepare -> DEBU 28d Primary 0 broadcasting pre-prepare for view=0/seqNo=1 and digest KSh6+6VJvSzr+olDe8LZ1vK8KieVtU1jcqUAP67Jr/Th1Zpg7omBBdn2jKdRx1OFUYMhgRBox31E9sEAO7Guqw==
11:03:40.715 [peer] SendMessage -> DEBU 28e Sending message to stream of type: CONSENSUS 
11:03:40.715 [peer] func1 -> DEBU 28f Sending 167 bytes to 0.0.0.0:30303 took 128.206µs
11:03:40.715 [peer] Broadcast -> DEBU 290 Broadcast took 174.276µs
11:03:40.715 [consensus/obcpbft] prepared -> DEBU 291 Replica 0 prepare count for view=0/seqNo=1: 0
11:03:40.715 [consensus/obcpbft/events] loop -> DEBU 292 Starting timer
11:03:40.715 [consensus/obcpbft/events] loop -> WARN 293 Attempting to stop an unfired idle timer
11:03:40.716 [consensus/obcpbft/events] loop -> DEBU 294 Stopping timer for
11:03:40.719 [consensus/obcpbft] ProcessEvent -> DEBU 295 Replica 0 processing event
11:03:40.719 [consensus/obcpbft] ProcessEvent -> DEBU 296 Replica 0 received incoming message from 1
11:03:40.719 [consensus/obcpbft] ProcessEvent -> DEBU 297 Replica 0 processing event
11:03:40.719 [consensus/obcpbft] recvPrepare -> DEBU 298 Replica 0 received prepare from replica 1 for view=0/seqNo=1
11:03:40.719 [consensus/obcpbft] prepared -> DEBU 299 Replica 0 prepare count for view=0/seqNo=1: 1
11:03:40.719 [consensus/obcpbft] prepared -> DEBU 29a Replica 0 prepare count for view=0/seqNo=1: 1
11:03:42.715 [consensus/obcpbft/events] loop -> DEBU 29b Event timer fired
11:03:42.715 [consensus/obcpbft/events] loop -> DEBU 29c Timer event delivered
11:03:42.715 [consensus/obcpbft] ProcessEvent -> DEBU 29d Replica 0 processing event
11:03:42.715 [consensus/obcpbft] ProcessEvent -> INFO 29e Replica 0 view change timer expired, sending view change: new request KSh6+6VJvSzr+olDe8LZ1vK8KieVtU1jcqUAP67Jr/Th1Zpg7omBBdn2jKdRx1OFUYMhgRBox31E9sEAO7Guqw==
11:03:42.715 [consensus/obcpbft] stopTimer -> DEBU 29f Replica 0 stopping a running new view timer
11:03:42.715 [consensus/obcpbft] prepared -> DEBU 2a0 Replica 0 prepare count for view=0/seqNo=1: 1
11:03:42.716 [consensus/handler] Sign -> DEBU 2a1 Security is disabled
11:03:42.716 [consensus/obcpbft] sendViewChange -> INFO 2a2 Replica 0 sending view-change, v:1, h:0, |C|:1, |P|:0, |Q|:1
11:03:42.716 [peer] SendMessage -> DEBU 2a3 Sending message to stream of type: CONSENSUS 
11:03:42.716 [peer] func1 -> DEBU 2a4 Sending 227 bytes to 0.0.0.0:30303 took 182.973µs
11:03:42.716 [peer] Broadcast -> DEBU 2a5 Broadcast took 253.413µs
11:03:42.716 [consensus/obcpbft] recvViewChange -> INFO 2a6 Replica 0 received view-change from replica 0, v:1, h:0, |C|:1, |P|:0, |Q|:1
11:03:42.716 [consensus/handler] Verify -> DEBU 2a7 Security is disabled
11:03:42.716 [consensus/obcpbft] recvViewChange -> DEBU 2a8 Replica 0 now has 1 view change requests for view 1
11:03:42.716 [consensus/obcpbft/events] loop -> WARN 2a9 Attempting to stop an unfired idle timer
11:03:42.716 [consensus/obcpbft/events] loop -> DEBU 2aa Stopping timer for
11:03:42.723 [consensus/obcpbft] ProcessEvent -> DEBU 2ab Replica 0 processing event
11:03:42.723 [consensus/obcpbft] ProcessEvent -> DEBU 2ac Replica 0 received incoming message from 1
11:03:42.723 [consensus/obcpbft] ProcessEvent -> DEBU 2ad Replica 0 processing event
11:03:42.723 [consensus/obcpbft] recvViewChange -> INFO 2ae Replica 0 received view-change from replica 1, v:1, h:0, |C|:1, |P|:0, |Q|:3
11:03:42.723 [consensus/handler] Verify -> DEBU 2af Security is disabled
11:03:42.723 [consensus/obcpbft] recvViewChange -> DEBU 2b0 Replica 0 now has 2 view change requests for view 1
11:03:43.805 [devops] createExecTx -> DEBU 2b1 Creating invocation transaction (fd8d9db9-d6dd-4f2a-9793-818add210936)
11:03:43.805 [devops] invokeOrQuery -> DEBU 2b2 Sending invocation transaction (fd8d9db9-d6dd-4f2a-9793-818add210936) to validator
11:03:43.806 [peer] sendTransactionsToLocalEngine -> DEBU 2b3 Marshalling transaction CHAINCODE_INVOKE to send to local engine
11:03:43.806 [peer] sendTransactionsToLocalEngine -> DEBU 2b4 Sending message CHAIN_TRANSACTION with timestamp seconds:1465470223 nanos:806155453  to local engine
11:03:43.806 [consensus/obcpbft] RecvMsg -> INFO 2b5 New consensus request received
11:03:43.806 [peer] SendMessage -> DEBU 2b6 Sending message to stream of type: CONSENSUS 
11:03:43.806 [peer] func1 -> DEBU 2b7 Sending 100 bytes to 0.0.0.0:30303 took 408.96µs
11:03:43.807 [peer] Broadcast -> DEBU 2b8 Broadcast took 541.243µs
11:03:43.807 [consensus/obcpbft] ProcessEvent -> DEBU 2b9 Replica 0 processing event
11:03:43.807 [consensus/obcpbft] ProcessEvent -> DEBU 2ba Replica 0 received incoming message from 0
11:03:43.808 [consensus/obcpbft] ProcessEvent -> DEBU 2bb Replica 0 processing event
11:03:43.808 [consensus/obcpbft] recvRequest -> DEBU 2bc Replica 0 received request: fb9DXPg3u3DSCGdU4WWm8dgKeCNYWq9V0/gmQxYjapM/1kCRytMR2OQaVu68hYytwPkKvfMuUXM6ggh/aIQ+Lw==
11:03:43.808 [consensus/obcpbft] recvRequest -> DEBU 2bd Replica 0 is backup, not sending pre-prepare for request fb9DXPg3u3DSCGdU4WWm8dgKeCNYWq9V0/gmQxYjapM/1kCRytMR2OQaVu68hYytwPkKvfMuUXM6ggh/aIQ+Lw==
11:03:43.866 [peer] SendMessage -> DEBU 2be Sending message to stream of type: DISC_GET_PEERS 
11:03:43.869 [consensus/handler] HandleMessage -> DEBU 2bf Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
11:03:43.869 [peer] HandleMessage -> DEBU 2c0 Handling Message of type: DISC_GET_PEERS 
11:03:43.869 [peer] beforeGetPeers -> DEBU 2c1 Sending back DISC_PEERS
11:03:43.869 [peer] SendMessage -> DEBU 2c2 Sending message to stream of type: DISC_PEERS 
11:03:43.870 [consensus/handler] HandleMessage -> DEBU 2c3 Did not handle message of type DISC_PEERS, passing on to next MessageHandler
11:03:43.870 [peer] HandleMessage -> DEBU 2c4 Handling Message of type: DISC_PEERS 
11:03:43.870 [peer] beforePeers -> DEBU 2c5 Received DISC_PEERS, grabbing peers message
11:03:43.870 [peer] beforePeers -> DEBU 2c6 Received PeersMessage with Peers: peers:<ID:<name:"vp0" > address:"0.0.0.0:30303" type:VALIDATOR > peers:<ID:<name:"vp2" > address:"0.0.0.0:30303" type:VALIDATOR > 
11:03:43.870 [peer] chatWithSomePeers -> DEBU 2c7 Skipping my own address(0.0.0.0:30303)`

Everething is ok when **noops** is activated (I have a lot of logs in chaincode terminal and **height** and **currentBlockHash** values are changed
## Describe How to Reproduce

I have changed only **peer.validator.consensus.plugin** from noops to pbft and **chaincode.mode** from net to dev.

**Comment by corecode** [comment]
I think you need to pass the chaincode id as returned from the deploy transaction.

**Comment by muralisrini** [comment]
@grbulat : I'm assuming you are following (and modifying) the SandboxSetup instructions so you can eliminate docker for running in VMs ? (Basically run peer and chaincode in the VMs without any docker dependencies so you don't run into VM issues doced in https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devenv.md.)

 I'll note that those instructions were meant for dev mode/noops/single peer only ... however the fact you made it work for `noops` does beg the question why it does not run for `pbft`.

The error ""Error:Failed to launch chaincode spec(Could not get deployment transaction for mycc - LedgerError - ResourceNotFound: ledger: resource not found)"' says the original deploy transaction was not found in the ledger for some reason.

By the way, before you switched to PBFT, I assume you cleared the old database with 

```
rm -rf /path/to/hyperledger/*

In vagrant this would be 
rm -rf /var/hyperledger/*

```

few questions
- what level of code are you on ?
- what is the command line for peers and chaincode in the VMs ?
- can you attach logs from all 4 peers you are sending the query and invokes to ?
- can you attach logs from all 4 chaincodes ?

Zip/tar of the logs work as well.

**Comment by muralisrini** [comment]
@corecode : didn't see your comment when I added mine. Does mine make sense ?

**Comment by grbulat** [comment]
@muralisrini Yes, I don't use docker. Is it wrong?

>  I assume you cleared the old database with

Yes, of course I clear it before switching.

> what level of code are you on ?

hmm..what do you mean?

> what is the command line for peers and chaincode in the VMs ?

for the base peer: `CORE_PEER_ID=vp0 ./peer node start --logging-level=debug`.
for the other peers (vp value change of course): `CORE_PEER_ID=vp1 CORE_PEER_DISCOVERY_ROOTNODE=172.16.5.180:30303 ./peer node start --logging-level=debug`
for the chaincode: `CORE_CHAINCODE_ID_NAME=mycc CORE_PEER_ADDRESS=0.0.0.0:30303 ./chaincode_example02`

> can you attach logs from all 4 peers you are sending the query and invokes to ?

My issue description contains logs for vp0 and chaincode. I attach log file from another vp now.
[vp_logs.txt](https://github.com/hyperledger/fabric/files/307046/vp_logs.txt)

> can you attach logs from all 4 chaincodes ?

hmm...I installed only 1 chaincode and it is running with vp0. Log from this chaincode is in my issue description. Nothing else.

I used following set of commands then:
`./peer chaincode deploy -n mycc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`
`./peer chaincode invoke -l golang -n mycc -c '{"Function": "invoke", "Args": ["a", "b", "10"]}'`
`./peer chaincode query -l golang -n mycc -c '{"Function": "query", "Args": ["b"]}'`

**Comment by muralisrini** [comment]
@grbulat 

> hmm...I installed only 1 chaincode and it is running with vp0. Log from this chaincode is in my issue description. Nothing else.

If you are running 4 peers, each of them should be running the chaincode. In non-dev mode this is done automatically for you by the peer by starting the chaincode in docker.

However that still does not explain why you are getting the error only in PBFT classic (although stricter, I'd expect the executions to succeed on vp0 at least).  BTW, I'm assuming the requests were directed to vp0 that's running the chaincode and the error is from that peer.

The attached vp_logs.txt has only the tail of the logs. Would need the entire log to debug.

**Comment by grbulat** [comment]
@muralisrini 

> BTW, I'm assuming the requests were directed to vp0 that's running the chaincode and the error is from that peer.

yes, that is right.

I've attached new log files: 
[chaincode_vp0.txt](https://github.com/hyperledger/fabric/files/308505/chaincode_vp0.txt)
[vp0.txt](https://github.com/hyperledger/fabric/files/308506/vp0.txt)
[vp1.txt](https://github.com/hyperledger/fabric/files/308504/vp1.txt)

**Comment by grbulat** [comment]
@muralisrini 

Unfortunately, I still have the same errors with 'no docker' environment. There are no any added data.
But I installed 4 validation peers in docker container as you suggest [here](https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md). **currentBlockHash** and **height** are changed, but query command still raise an error 'Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Error starting container: cannot connect to Docker endpoint)"'. And the second problem is when I terminate one peer and launch another peer container with empty database, the sync process is not started and **height** value equal to 1 (another peers **height** > 1).
However, I am wondering to install environment without docker. Is there any reason to not do so? I can provide new logs from peers if it helps. Thank you!

**Comment by grbulat** [comment]
Eventually, I have done it with 'partial' docker environment (peers in theirs own virtual machines, but chaincode run in docker container).
Commands to start peers: 
`CORE_VM_ENDPOINT=http://172.17.0.1:2375 CORE_PEER_ADDRESSAUTODETECT=true CORE_PEER_ID=vp0 ./peer node start --logging-level=debug`

`CORE_VM_ENDPOINT=http://172.17.0.1:2375 CORE_PEER_ADDRESSAUTODETECT=true CORE_PEER_ID=vp1 CORE_PEER_DISCOVERY_ROOTNODE=172.16.5.193:30303 ./peer node start --logging-level=debug`

and so forth.
For the chaincode:
`CORE_PEER_ADDRESS=172.16.5.193:30303 ./peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`
`CORE_PEER_ADDRESS=172.16.5.193:30303 ./peer chaincode invoke -l golang -n bb54ee9752ee3742b52f4a204a4eb0693c364cf10540127c75b0ca119fb8db1e2130a73287469ed2341d19f146f58d0572d1a00a79e6f5834946b0e04e53920b -c '{"Function": "invoke", "Args": ["a", "b", "10"]}'`

**Comment by ngogia20** [comment]
This still doesnt work on pbft on different machines (different vms on different cloud) but works on noops
