### ISSUE TITLE
PUB : cd ./peer ==> cd peer 

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1771]
## Description

On this web page:
https://github.com/hyperledger/fabric/blob/master/docs/API/SandboxSetup.md

In this section: 
_Writing, Building, and Running Chaincode in a Development Environment
Vagrant Terminal 1 (validating peer)_

In this list of commands: 
_cd $GOPATH/src/github.com/hyperledger/fabric
make peer
cd ./peer_  <=== seems wrong

cd into ./peer seems incorrect.  Did you mean 'cd peer'?
## Describe How to Reproduce

Not applicable

**Comment by corecode** [comment]
`cd peer` is the same as `cd ./peer`.

**Comment by srderson** [comment]
Resolved in PR #1774
