### ISSUE TITLE
Membership Services CA env settings: "OBCCA_" -> "MEMBERSRVC_CA_"

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1797]
## Description

The `membersrvc` process allows the configuration of environment variables that can override the YAML configuration settings.

Here's an excerpt from `docs/dev-setup/obcca-setup.md` ["perm"-linked](https://github.com/hyperledger/fabric/blob/f7b0b5c0a2fc98c898cd1972cc18c811d42c355e/docs/dev-setup/obcca-setup.md)

> Alternatively, these fields can be set via environment variables, which---if set---have precedence over entries in the yaml file. The correspnding environment variables are named as follows:
> 
> OBCCA_SERVER_GOMAXPROCS
> OBCCA_SERVER_ROOTPATH
> OBCCA_SERVER_CADIR
> OBCCA_SERVER_PORT
## Proposed Change

Currently we have other libraries using `HYPERLEDGER` `CORE_NOOPS`, `CORE_PBFT` as a prefix. We could possibly use `HLF_CA_` as a prefix, which is also in line with the entire Certificate Authority (CA) functionality of `Membership Services`.

> HLF_CA_SERVER_GOMAXPROCS
> HLF_CA_SERVER_ROOTPATH
> HLF_CA_SERVER_CADIR
> HLF_CA_SERVER_PORT
## Good First Bug

I consider this a **Good First Bug** especially for those in the community who would like to pick up a simple coding task and get involved in fabric, build it, test it, and learn how to contribute to it. Need this done quickly and will be happy to spend some time guiding (pointing to the right Wiki's mostly ;-)), and verifying this all the way to submitting the PR [ usually at the modest tuition charge of 1-2 `MoreTests` digital currency ;-) ]

Interested? Hit me/us up here, or on [HL's Slack](http://hyperledgerproject.slack.com/jonathanlevi)
## How to Fix

1. The good ol' `membersrvc/ca/util...` should use the new updated prefix (and not the `OBC...`)
2. Use `viper`'s `config.SetEnvPrefix(configPrefix)` (in one location) instead of manual string concatenations.
3. Rename `dev-setup/obcca-setup.md` to `dev-setup/ca-setup.md` and related references
   and of course,
4. Update  `dev-setup/ca-setup.md` content

**Comment by GrapeBaBa** [comment]
@JonathanLevi I would like to take this one

**Comment by JonathanLevi** [comment]
Hi @GrapeBaBa! Great, all yours, thanks. Let me know how/if I can assist...

**Comment by GrapeBaBa** [comment]
I start to do this one. @JonathanLevi Could you assign it to me?

**Comment by JonathanLevi** [comment]
@GrapeBaBa: combining recent feedback from @mastersingh24, @ghaskins @lehors, seems as if we should use the `MEMBERSRVC_CA_` prefix. Mainly so as to not make the `CORE_`/peer side look inconsistent, in case that will take longer to change in the coming days), as it may take time to align it with `membersrvc`.

**Comment by GrapeBaBa** [comment]
@JonathanLevi Changed.

**Comment by JonathanLevi** [comment]
Many thanks. PR #1810 might require an explicit `rebase`, but the changes look great!
