### ISSUE TITLE
Travis Build failures: After PR# 1765 merge

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1803]
## Description

All Travis Builds are failing with error message `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` after merging PR#1765.
## Describe How to Reproduce

All Travis Builds are failing after PR#1765 merge. This happens most often while running core/crypto unit-tests. It seems the core/crypto test suite is hanging or taking more than 10 mins time without producing output to stdout.

Travis waits for 10 mins by default to receive the output from an command, If it doesn't receive any input for more than 10 mins it exits with error message as **No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself**
Reference: https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out
Below is the time taken to run core/crypto unit-tests **after 1765 PR Merge**. Below log has been taken from Jenkins:
?  github.com/hyperledger/fabric/core/container/util    [no test files] 
20:20:11 ok github.com/hyperledger/fabric/core/crypto **594.213s** coverage: 62.6% of statements
_From another build:_
ok      github.com/hyperledger/fabric/core/crypto   **602.844s**    coverage: 62.6% of statements
**_Before 1765 Merge:**_
github.com/hyperledger/fabric/core/crypto   **18.192s** coverage: 63.7% of statements

**Comment by muralisrini** [comment]
@rameshthoomu I'm guessing this is why PR #1795 is failing ? Will this problem go away if core/crypto test cases just write something to stdout periodically to keep Travis happy ? If so, that could be a workaround if we want to debug root cause for the long duration of core/crypto test.

**Comment by diegomasini** [comment]
@rameshthoomu I'm trying to reproduce it locally with no luck. Could be a travis problem? I willl continue trying to reproduce and I will let you know if I succeed. If in the meantime you can check if you can reproduce it locally I will appreciate it.

**Comment by muralisrini** [comment]
@diegomasini I looked at this a bit with @rameshthoomu (while working on my PR).  Its not that the core/crypto itself is hanging or stuck. Its just that if it takes more than 600 secs, Travis will _think_ the "go test" is not responding. 

The problem appears to be that core/crypto now could take more than 600 seconds (on my laptop it took 568 seconds). If that happens the "go test" stdout to Travis will not be updated after 

`
?       github.com/hyperledger/fabric/core/container/util   [no test files]
`

 for 600+ seconds and will result in the error shown below.

![image](https://cloud.githubusercontent.com/assets/14361488/15987738/edc8ee78-3001-11e6-9b74-2c29cbc77d5b.png)

We could split up the tests into multiple tests to keep the "go test" window active. Or make the tests take less than 10mins (much less than 10 to be safe).

**Comment by rameshthoomu** [comment]
It's a limitation in Travis. Please check reference link mentioned above but we can fix this issue with the approach mentioned by @muralisrini.  Adding @andresgaragiola
