### ISSUE TITLE
no command  peer  found

### ISSUE THREAD

**Issue by b01213231** [hyperledger-archives/fabric#1814]
I ran the peer command and got the correct response several days ago , but today it shows No command 'peer' found , how to resolve it ? it didn't show any error when run make peer
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ peer
No command 'peer' found, did you mean:
 Command 'beer' from package 'gerstensaft' (universe)
 Command 'peel' from package 'ears' (universe)
 Command 'pee' from package 'moreutils' (universe)
 Command 'pear' from package 'php-pear' (main)
peer: command not found
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$

**Comment by b01213231** [comment]
resolved , the instruction is not correct ,the command should be run in peer folder as ./peer

**Comment by GrapeBaBa** [comment]
@b01213231 Refer #1807, you need update code and rebuild your vagrant environment by vagrant destroy/up.

**Comment by ramarahul** [comment]
@b01213231  I am also facing similar error. And I am not able to resolve it the way you said above. Can you be more specific and help me please?

**Comment by lehors** [comment]
Beware that this project has moved to Gerrit and issues are being tracked on JIRA: https://jira.hyperledger.org
Please, consider the new documentation at http://hyperledger-fabric.readthedocs.io/en/latest/index.html
And for quick response I suggest you seek help on one of the RocketChat channels at: https://chat.hyperledger.org/

I'm not clear on which version of Fabric you're trying to use, in the latest version, in the developer environment the peer binary is in build/bin directory (after you've run make).
