### ISSUE TITLE
Behave test (680 scenario) is failing after PR#1758 merge  -Build#1039

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1820]
Behave test scenario (680 test scenario) is failing consistently after PR#1758 merge.
## Description

Behave tests are failing after PR#1758 merge and below is the error message observed:
  Assertion Failed: Failed to POST to http://172.17.0.47:5000/devops/query:  {"Error": "Error: state may be inconsistent, cannot query"}
## Describe How to Reproduce

Ran behave tests on PR#1758 merge (Commit#4acd488) in Travis and inside vagrant environment:

Below is the log file:
http://chunk.io/f/20947ea0ceb243aa8fa1893c568a2ef7
Vagrant Log file:
[PR#1758_Behave test fail.txt](https://github.com/hyperledger/fabric/files/312741/PR.1758_Behave.test.fail.txt)

**Comment by srderson** [comment]
@jyellick so this test is now disabled via PR #1825. Do you want to keep this issue open for re-enabling the test when you're ready?

**Comment by jyellick** [comment]
@srderson Please leave open (and assign to me if that is still process).

**Comment by rameshthoomu** [comment]
Below are the observations while re-testing this issue:

Tested this issue on `commit#8301c00` (merge of pull request #1785) and it worked as expected. Below are test results: Seems this issue is fixed in the above commit.

Hyperledger/fabric build result before disable 680 scenario:
https://travis-ci.org/hyperledger/fabric/builds/137508890

Travis: 
https://travis-ci.org/rameshthoomu/fabric/builds/137621124

Vagrant: 
[680_issue.txt](https://github.com/hyperledger/fabric/files/316358/680_issue.txt)

**Comment by christo4ferris** [comment]
@rameshthoomu so can the test be re-enabled? (or has it?) Is this issue still relevant or can it be closed? @srderson @jyellick

**Comment by rameshthoomu** [comment]
I ran 3-4 test runs on this scenario and didn't observe any test failures. Seems this is fixed now and we can re-enable this scenario.

**Comment by rameshthoomu** [comment]
looks like scenario@680 is working as expected after re-enable this in gerrit code base. Closing this.
