### ISSUE TITLE
need help, not able to open the json in local browser

### ISSUE THREAD

**Issue by b01213231** [hyperledger-archives/fabric#1828]
My sandbox is run in vagrant , I can open the json file with "curl http://localhost:5554/rest_api.json" command ,that means the server run in vagrant is fine , but I am  not able to open the json in local browser ,seems it is the network problem , anyone got the same issue ?

**Comment by srderson** [comment]
Did you edit the REST port in core.yaml? If so, you likely need to edit the Vagrantfile. By default the REST port is forwarded to port 5000 outside of Vagrant. https://github.com/hyperledger/fabric/blob/master/devenv/Vagrantfile#L37
