### ISSUE TITLE
Jenkins z slave machines went into offline mode

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1847]
## Description

CI build results are showing as failed as master Jenkins is not able to trigger builds on z slaves. We observed all z machines are in offline mode and unable to reach out to these machines. 
All builds of PR and merge requests are showing as failed in github.

**Comment by rameshthoomu** [comment]
@vpaprots: could you please comment on this..

**Comment by vpaprots** [comment]
Jason Kirke/Kathy can we have somebody look at this?

**Comment by jkirke** [comment]
Is this still an issue? It was opened two days ago and I thought is was resolved the same day. If we want me to be able to look at these issues, I need the connection information for the z systems. If the systems are down, I do not have the systems on my LinuxONE dashboard and cannot restart them .

**Comment by rameshthoomu** [comment]
This issue has been fixed by @vpaprots: Could you please mention what is the issue and steps to fix the issue. Thanks

**Comment by rameshthoomu** [comment]
Fixed this issue by deleting docker logs and unused docker containers and images. Closing this issue.
