### ISSUE TITLE
Chaincode container should communicate over TLS with the peer

### ISSUE THREAD

**Issue by mrshah-at-work** [hyperledger-archives/fabric#1848]
## Description

The chaincode containers do not communicate over TLS. Thus, if TLS is turned on on the peer, the chaincode container will fail to connect to the peer.
## Describe How to Reproduce

1. Turn TLS on on the peer
2. Deploy chaincode
## Proposal

Ref: https://github.com/masterDev1985/fabric/commit/263dcc3dabf0c71821b3c2d4f505a6fb658b5b0f
In addition to above, we need to modify the chaincode Dockerfile in core.yaml to copy the certs into the chaincode container in the folder provided at peer.tls.cert.file & peer.tls.key.file.

**Comment by corecode** [comment]
Why?  For localhost connections I don't think this is required.

**Comment by mrshah-at-work** [comment]
If TLS is enabled on the peer and the Peer is listening over TLS, the chaincode container will try to connect to it over a non-TLS connection and it will fail.

**Comment by muralisrini** [comment]
@corecode to add to @mrshah-at-ibm ... as we are sharing the same grpc port for both chaincode and the peer, TLS/no-TLS rules have to apply to both

**Comment by corecode** [comment]
Oh I see.  Is that a good idea?  Is it possible for an attacker to impersonate a chaincode?

**Comment by muralisrini** [comment]
@corecode if the peer is compromised all bets are off. However, it may be good to use a seperate listener for chaincode for isolation/performance. Will open an issue for that for discussion
