### ISSUE TITLE
Need fix the go vet errors

### ISSUE THREAD

**Issue by genggjh** [hyperledger-archives/fabric#1858]
## Description

There are still some go vet errors from Go Report Card.
Some errors will result in problem when write logs.
Like this:
https://github.com/hyperledger/fabric/blob/master/core/crypto/peer_impl.go#L67

Maybe we need consider to add the go_vet examines as a necessary condition in our CI verification. The go vet examines must 100% green before run other tests.

**Comment by srderson** [comment]
I took care a most of them (if not all) in PR #1855. Apologies for not creating a matching issue.

**Comment by genggjh** [comment]
Great, will close this issue.

**Comment by genggjh** [comment]
Duplicate #1855
