### ISSUE TITLE
Change the install.md documentation about how to build peer and membersvc image

### ISSUE THREAD

**Issue by ibmamnt** [hyperledger-archives/fabric#1860]
## Description

The [install documentation](https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/install.md#building-the-fabric-core-) instruct us to build the image using this procedure.

```
go test github.com/hyperledger/fabric/core/container -run=BuildImage_Peer
go test github.com/hyperledger/fabric/core/container -run=BuildImage_Obcca
```

This is no longer valid, as these methods have been removed from vm_test.go file. Please change the documentation appropriately.

**Comment by nickgaski** [comment]
@muralisrini @ghaskins - With regards to the behave tests:  are the above parameters still correct when using the "go test" function to build the peer and member services images.  I would have imagined that all instances of OBC had been deprecated by now.

**Comment by JonathanLevi** [comment]
Thank you @nickgaski.

@ibmamnt Are there still related documentation corrections/suggestions that should be submitted under this issue?

**Comment by ibmamnt** [comment]
Looks like the original install documentation has been refactored into several .md files. If I picked up one of them, it correctly described how to build image. So I think this issue can be closed.
