### ISSUE TITLE
Peer should support multiple ledgers

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#188]
The ledger is currently a singleton. It needs to be modified so that a peer can support multiple independent ledgers. These ledgers should not share a DB, but instead use independent DB locations.

**Comment by muralisrini** [comment]
Assuming a key use of multiple independent ledgers is multichain (for confidentiality etc) with each chain using its own ledger, using a map of chain name - > ledger might be a possibility ? So users would do ledger.GetLedger(name) - where "name" is a chain name -  to get handle to the chain's ledger.

Reason to bring this up :  chaincode.ExecuteTransactions takes a "chain name" as a parameter and would be hook in nicely with this implementation.

This implementation is not specific to a chain. A ledger not associated with a chain could use the same implementation by associating and accessing a ledger with a name.

**Comment by binhn** [comment]
Move to backlog as we will manually set up multichain
