### ISSUE TITLE
Build failures with 41414 port conflict error

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1884]
## Description

Builds are failing with port conflict error. We are not getting this issue every time but it is observed in couple of the CI builds. Below is the error message:

```
FAIL: TestChaincodeQueryChaincode (0.00s)
    exectransaction_test.go:1098: Error registering user  Error starting peer listener listen tcp 0.0.0.0:41414: bind: address already in use
```

Port Range in Travis:
$ cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
## Describe How to Reproduce

We observed this while running unit-tests but not reproducing every time. Below are builds effected with this issue:

Build 1124 #https://travis-ci.org/hyperledger/fabric/builds/138105735 (Travis)
Build#192 (Jenkins)

**Comment by muralisrini** [comment]
thanks @rameshthoomu
