### ISSUE TITLE
Behave scenario "chaincode example02 with 4 peers, two stopped" failing

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1886]
## Description

Behave test "chaincode example02 with 4 peers, two stopped" is failing in travis CI with the below error message:

`File "steps/peer_basic_impl.py", line 388, in step_impl raise Exception("Max time exceeded waiting for transactions with current response map = {0}".format(respMap)) Exception: Max time exceeded waiting for transactions with current response map = {'bddtests_vp0_1': 404, 'bddtests_vp1_1': 0, 'bddtests_vp3_1': 0}`

Log File: http://chunk.io/f/cbe316f50cf04e6c87d3b4c635fdbf64
Build# 1143 Result: https://travis-ci.org/hyperledger/fabric/builds/138198022#L2310
commit# 5637838
Reference PR#1867
Referenced Failed Travis Builds#
Build#1148, 1149

 ## Describe How to Reproduce

Run Behave tests on commit# 5637838

**Comment by corecode** [comment]
I cannot replicate this problem.

**Comment by rameshthoomu** [comment]
@corecode: Could be timing issue in Travis. All the above mentioned builds (# 1148,1149,1143,1142) failed in travis with the same error. But today I saw Build# 1156 passed in Travis on top of  Commit# `5637838`. I think we have to increase the wait time after invoke. We observed this kind of issue with behave 680 scenario.

**Comment by rameshthoomu** [comment]
Observed the same issue in Build#1201. Below is the log:

```
Then I wait up to "60" seconds for transaction to be committed to peers                                                     # steps/peer_basic_impl.py:354
  | vp0 | vp1 | vp3 |
When I query chaincode "example2" function name "query" with value "a" on peers                                             # steps/peer_basic_impl.py:422
  | vp0 | vp1 | vp3 |
Then I should get a JSON response from peers with "OK" = "0"                                                                # steps/peer_basic_impl.py:466
  | vp0 | vp1 | vp3 |
  Assertion Failed: For attribute OK, expected (0), instead found (10)
```

**Comment by rameshthoomu** [comment]
This issue is not reproducible on latest commit. Closing this issue.
