### ISSUE TITLE
Validation peer never invoke transactions after restart (pbft)

### ISSUE THREAD

**Issue by grbulat** [hyperledger-archives/fabric#1889]
## Description

Need help in state transfer in pbft consensus plugin. I have 4 validation peers and everything is all right when...everything is all right (sorry), i.e. transactions are invoked and **height** and **currentBlockHash** are changed. But when I shutdown one peer, then invoke some transactions and start that peer again, it will never invoke any transaction (it has old values for **height** and **currentBlockHash**). 
I have the same situation like described here in #933 by @harrijk: 

> Observations:
> - The chain height of the peers (including the peer that was restarted) before injecting "invoke" transactions was approximately 10.
> - The chain of the peer that was down finally synced when the chain height of the peers that stayed up reached 61

and so forth.
Started peer sync the state only when another peers height reached 61. Furthermore, it is sync to height = 58 (not to 61). The second time when this peer will update its value is when other peers height reached 388. And once again it doesn't invoke any transactions.
As @corecode mentioned in #933: 

> I think what you're seeing is normal PBFT behavior: 2f+1 replicas are making progress, and f replicas are lagging slightly behind, and catch up occasionally.

Is it my situation too? Is it right that this lagging node will never invoke transactions?

**Comment by corecode** [comment]
You can only expect 2f+1 nodes to be up to date.

**Comment by grbulat** [comment]
ok, thank you!
