### ISSUE TITLE
State is not sent in network with 4 validation peers after numerous invocation transactions (pbft)

### ISSUE THREAD

**Issue by grbulat** [hyperledger-archives/fabric#1896]
## Description

I need an advice in the following situation:
I load peers with numerous invocation transactions (near about 3500; 50 per second), but after 1 hour of working peers stopped to share the state and stuck in different values of chains height. Situation is not changed even after rebooting all peers.
Is it a known issue, or it is not an issue at all and I must not to invoke so many transactions?

**Comment by corecode** [comment]
please provide a debug log or code to replicate.  The system is supposed to keep accepting invokes.

**Comment by grbulat** [comment]
Logs from all peers:
[vp0.txt](https://github.com/hyperledger/fabric/files/320404/vp0.txt)
[vp1.txt](https://github.com/hyperledger/fabric/files/320402/vp1.txt)
[vp2.txt](https://github.com/hyperledger/fabric/files/320405/vp2.txt)
[vp3.txt](https://github.com/hyperledger/fabric/files/320403/vp3.txt)

Log of invocations: 
[loop invoke log.txt](https://github.com/hyperledger/fabric/files/320410/loop.invoke.log.txt)

**Comment by grbulat** [comment]
and I use a simple bash script to invoke:

`#!/bin/bash
while true; do
        CORE_PEER_ADDRESS=172.16.5.193:30303 ./peer chaincode invoke -l golang -n bb54ee9752ee3742b52f4a204a4eb0693c364cf10540127c75b0ca119fb8db1e2130a73287469ed2341d19f146f58d0572d1a00a79ae6f5834946b0e04e53920b -c '{"Function" : "invoke", "Args" : ["a", "b", "10"]}'
done`

**Comment by grbulat** [comment]
I forgot to say that it was a commit `fcc6a7dc599f20d632fdb87beb785f73fa8796bd`

**Comment by corecode** [comment]
unfortunately the logs are incomplete.  Please provide complete logs from the beginning.

**Comment by grbulat** [comment]
If there is no any option that save logs to any directory by default, I guess I lost other parts of my log. 
I will try to repeat this situation.

**Comment by grbulat** [comment]
@corecode 
Repository is updated to commit `35326c2`

### Steps to reproduce:
1. Start all 4 peers and start to invoke transactions (and don't stop invoking to end of the test)
2. Stop v3, wait for some time (5s) and start it again
3. Stop v1, wait, start it again, wait, stop it again, wait, start it
4. All peers stuck and don't invoke any transaction
5. Continue
6. Stop all peers and start again 
7. They receive some transactions, then stop them
8. Start peers again and now they are absolutely stuck

[vp_logs.zip](https://github.com/hyperledger/fabric/files/322953/vp_logs.zip)

**Comment by corecode** [comment]
could you please retry with batch?  classic will be removed soon.

**Comment by grbulat** [comment]
Same in the batch mode.
Repository is updated to commit `1550075`
Steps are the same too, but peers are completely stuck after step 4 and reboot is not helping at all.
Height is 271 even after 13890 invocations.

[logs.zip](https://github.com/hyperledger/fabric/files/327275/logs.zip)

**Comment by corecode** [comment]
Your system never manages to create a chaincode docker container.

**Comment by grbulat** [comment]
I run peers with the following commands in their own virtual machines (Docker is installed in all of them):
`CORE_VM_ENDPOINT=http://172.17.0.1:2375 CORE_PEER_ADDRESSAUTODETECT=true CORE_PEER_ID=vp0 ./peer node start --logging-level=debug`
`CORE_VM_ENDPOINT=http://172.17.0.1:2375 CORE_PEER_ADDRESSAUTODETECT=true CORE_PEER_ID=vp1 CORE_PEER_DISCOVERY_ROOTNODE=172.16.5.193:30303 ./peer node start --logging-level=debug`
I missed some parameters?

**Comment by grbulat** [comment]
After fixing some issues connected with docker it is not reproducible anymore
