### ISSUE TITLE
Nodejs Client SDK chain-tests.js - registrar not working

### ISSUE THREAD

**Issue by th-ei** [hyperledger-archives/fabric#1897]
## Description

The test [chain-tests.js](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js) uses an undefined registrar because [line 117](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js#L117) refers to the wrong field (should be 'name' according to [line 33](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js#L33)
## Describe How to Reproduce

Run chain-tests.js - the test will succeed despite registrar being undefined.
There are two issues here:
- the test code is broken ('user' should be 'name' in line 117)
- why is the test succeeding despite no registrar name being supplied?

**Comment by angrbrd** [comment]
@th-ei thank you for pointing this out. The confusion was inside the usage of the `registrar` variable inside the test file. 

The chain registrar is in fact being set inside the 'Set chain registrar test' [here](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js#L234). And when the `getUser` method triggers the `user.registerAndEnroll` [here](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js#L122), we actually end up using the `chain.getRegistrar()` as shown [here](https://github.com/hyperledger/fabric/blob/master/sdk/node/src/hlc.ts#L903). The `registrar` field that is being passed inside the [registrationRequest](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js#L116) is completely irrelevant. In fact, the [RegistrationRequest](https://github.com/hyperledger/fabric/blob/master/sdk/node/src/hlc.ts#L153) structure does not even expect a string, it expects an object and for a completely different purpose. This is why the test is still passing, as inside we are using `self.chain.getRegistrar()`.

I have submitted a change to remove the confusing `registrar` variable from the chain-tests.js file. Please review this and let me know if this makes sense to you.

Thanks!
