### ISSUE TITLE
Consolidate all google_protobuf import aliases (across the board)

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1899]
## Description

We found out last night that various sections of fabric import "google/protobuf" with different aliases.
## Describe How to Reproduce

Looking at the various import "google/protobuf" statements and see the various different import aliases (including `protobuf, google_protobuf, google_protobuf1`).
## Proposed Solution

Remove all import aliases and use the original/default package name.

**Comment by christo4ferris** [comment]
yes, please

**Comment by christo4ferris** [comment]
also good first project!
