### ISSUE TITLE
PBFT transient network failure tolerance

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#1917]
## Description

In my testing of #1877 I encountered a scenario which, to my best reading of the Castro paper does not seem to be handled by the PBFT protocol.  I'd appreciate comments from @vukolic and @cca88 in particular, but @corecode, @kchristidis, and @tuand27613 might have some insight as well.

Scenario:
1. Start a network of 4 replicas, vp0, vp1, vp2, vp3
2. Have vp0 successfully establish a link to vp1, vp2, vp3
3. Broadcast request to all VPs, via vp0
4. Request fails to prepare (because vp1, vp2, vp3 are not linked to eachother)
5. All replicas send view change, vp0 has 4 view change messages, all other replicas have 2
6. vp0 has its new-view timer expire because after receiving 3+ view change messages it did not receive a new view in time
7. vp1, vp2, vp3 are not in an active view, and do not have enough view change messages to start the new view timer.
8. Network connectivity is established between vp1, vp2, vp3
9. The network will never process another request, even if more are submitted, or periodic null request, or periodic view changes are enabled.

I think the simple answer is 'Failure to connect between vp1, vp2, vp3, counts are more than 1 fault, and the PBFT promises are off'.  However, permanently failing because of this transient error seems like a serious problem.

Proposed fix: In addition to the 'new-view timer', we could start a 'view change rebroadcast timer', so that, for as long as a replica is in a view change, but does not have sufficient view change messages to start the new view timer, it will periodically rebroadcast its view-change message, in case for whatever reason its previous view change message was not delivered to all replicas.

**Comment by corecode** [comment]
No, once the network is back, any broadcast request will start the outstanding request timer, which will lead to a view change.

**Comment by jyellick** [comment]
@corecode The replicas have already sent their view change, so they do not send another.  We purposefully do not start the request timer while in a view change, as it would both negate having a separate new view processing timeout, as well as the doubling of the new view timeout.

**Comment by corecode** [comment]
Oh I misread then.  The view change timer starts when sending a view change message.  so the replicas should send a view change for the next view after their timeout fires, etc.  Once the network is back, the replicas will success in the view change.

**Comment by jyellick** [comment]
See page 415: (the view change timer does not start when we send the VIEW-CHANGE message, only when we receive 2f+1)

"... until some operation executes. We achieve these goals by several means. First, to avoid starting a view change too soon, a replica that multicasts a VIEW-CHANGE message for view v + 1 waits for 2 f + 1 VIEW -CHANGE messages for view v + 1 before starting its timer. Then, it starts its timer to expire after some ..."

**Comment by corecode** [comment]
Okay, that seems like a protocol bug then.  Or something about queuing assumptions?

**Comment by jyellick** [comment]
Yes, I agree, it seems like a protocol bug, or perhaps based on some assumption that messages will be delayed, but not discarded.  What do you think of the proposal to resend the view-change message periodically?

**Comment by corecode** [comment]
Seems like a reasonable thing to do.

**Comment by jyellick** [comment]
Thanks @corecode, let's see what @vukolic and or @cca88 thinks, and then I will start implementing.

**Comment by vukolic** [comment]
ack that's fine - Castro/Liskov assumed reliable channel (if two communicating nodes are correct a message sent will eventually be delivered) there so they expect a message to eventually go through. In a lossy network (e.g., in your example with channels temporarily down) this requires retransmission. 

So periodic retransmission of view-change msgs is in place here. Good catch.

**Comment by corecode** [comment]
Should we then not discard messages and queue them instead?

**Comment by jyellick** [comment]
Thanks for the input, re-transmitting view change messages periodically seems like a simple change which should address this problem.

@cca88 @vukolic Do you see any other corner cases like this where PBFT is depending on reliable message transmission?

**Comment by vukolic** [comment]
as a rule of thumb - you need reliable channels wherever you block waiting for reception of n-f messages

**Comment by vukolic** [comment]
or, more generally, wherever you block on receiving messages

**Comment by kchristidis** [comment]
Fixer with #1939, this can be closed. @srderson

**Comment by srderson** [comment]
@kchristidis There's still an open PR on the master branch which I assume needs to be merged before we can close this.

**Comment by kchristidis** [comment]
Got it.
