### ISSUE TITLE
Where is the chaincode after it deployed to networks?

### ISSUE THREAD

**Issue by huhaiqing** [hyperledger-archives/fabric#1925]
Hi,

After deploy a chaincode in docker environment, there will be a new image.
For example,
1. peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}' -u lukas
1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66
1. In the docker host server, execute 'docker images'
   root@peernode:~# docker images
   REPOSITORY                                                                                                                                 TAG                 IMAGE ID            CREATED             SIZE
   **dev-vp0-1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66**   latest              3ce90061ac22        11 minutes ago      993.9 MB
   dev-vp3-1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66   latest              0ad6d99a77fb        11 minutes ago      993.9 MB
   dev-vp2-1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66   latest              71589c1e7892        12 minutes ago      993.9 MB
   dev-vp1-1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66   latest              ce7fba8878ae        12 minutes ago      993.9 MB

Can you tell us where is the chaincode after it be deployed?
If it saved in a peer node, what's the path?

Thanks in advance.

Regards
Harry

**Comment by mastersingh24** [comment]
@huhaiqing - not sure I understand the question?  Are you trying to figure out where the physical files for the image and the container instance are located?  If that's the question, depending on your OS you'll typically find them in directories under `/var/lib/docker` (for Linux)

**Comment by srderson** [comment]
@huhaiqing you may also want to ask on Stackoverflow if @mastersingh24's response is not clear.
http://stackoverflow.com/questions/tagged/hyperledger
