### ISSUE TITLE
consensus abstraction should be unaware of communication primitives such as stream

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#194]
Consensus is a pluggable component which deals with messages from users and other validators. Validators can "come and go" and messages it sends are not guaranteed to be delivered. The key point is unlike other protocols whose state directly on whether the protocol KNOWS the message has reached the other side, consensus just sends it out and decides state movement asynchronously (via messages received later). Indeed, a "broadcast" could be a true TCP broadcast if possible. We implement it via peer-peer connections. Basically communications is an implementation detail as far as consensus is concerned. Having Cosennsus abstraction be aware of streams and communication primitives is leaky. Managing communications (error handing, validators enter/leave, etc) will become harder as more layers become aware of it. We should organize code such that there's a clear communication layer, however we implement it (the object oriented model provides one such organization).

**Comment by kchristidis** [comment]
This should be taken care of by #212.
