### ISSUE TITLE
PBFT Batch: Queries on a bounced peer returned deployed values after another peer is stopped

### ISSUE THREAD

**Issue by scottz64** [hyperledger-archives/fabric#1942]
## Description

REGRESSION-FAILURE: Testcase:  Consensus_S2_5I_R2_S1_2I_20I.go 
- passes on June 9th a94f5a7 
- fails on June 20 35326c2 
  Note:  a Behave test will be uploaded shortly.

Actually, it seems "consensus" resumes, because the other peers continue to process additional invokes, but the queries from the bounced peer are wrong.
## Describe How to Reproduce

In vagrant, docker start 4 validating peers with security. K=10, Batchsize=2.
PEER_IMAGE=rameshthoomu/peer:35326c2
MEMBERSRVC_IMAGE=rameshthoomu/membersrvc:35326c2
1. Deploy A=100000, B=90000.  (Sleep 2 mins.)
2. Stop VP2.  (Sleep 1 min.)
3. Invoke 5 times.  (Sleep 1 min.)
4. Restart VP2.  (Sleep 2 mins.)
5. Stop VP1.  (Sleep 1 min.)
6. Invoke 2 times. (Sleep 1 min.) And query. Observe the queried values from VP2 are stuck at "deployed/init" values:

Results in a and b match with Invoke values on PEER0: PASS
 curra : 99993, currb : 90007, resa : 99993 , resb : 90007
RESULTS DO NOT MATCH on PEER2 : FAIL
 curra : 99993, currb : 90007, resa : 100000 , resb : 90000
Results in a and b match with Invoke values on PEER3: PASS
 curra : 99993, currb : 90007, resa : 99993 , resb : 90007
1. Invoke 20 times more. (Sleep 1 min.) And query... and observe no change in status.
   Observe VP0 and VP3 have processed all 27 Invoke Requests correctly.
   Observe VP2 shows the init/deployed values for A and B (but should match VP0 and VP3).

Results in a and b match with Invoke values on PEER0: PASS.
  curra : 99973, currb : 90027, resa :  99973 , resb : 90027
RESULTS DO NOT MATCH on PEER2 : FAIL.
  curra : 99973, currb : 90027, resa : 100000 , resb : 90000
Results in a and b match with Invoke values on PEER3: PASS.
  curra : 99973, currb : 90027, resa :  99973 , resb : 90027
# 

For reference, this test passes on June 09 images:
PEER_IMAGE=rameshthoomu/peer:a94f5a7
MEMBERSRVC_IMAGE=rameshthoomu/membersrvc:a94f5a7
Tue Jun 21 15:43:24 UTC 2016 (11 minutes elapsed)

Results in a and b match with Invoke values on PEER0: PASS
  curra : 99973, currb : 90027, resa : 99973 , resb : 90027
Results in a and b match with Invoke values on PEER2: PASS
  curra : 99973, currb : 90027, resa : 99973 , resb : 90027
Results in a and b match with Invoke values on PEER3: PASS
  curra : 99973, currb : 90027, resa : 99973 , resb : 90027

**Comment by lhaskins** [comment]
The behave test below failed at the final step with the following error:

```
      Assertion Failed: For attribute OK, expected (977), instead found (1000)
```

It should be noted that while vp2 came back up, it did not look as though transactions were being processed.

```
Container bddtests_vp0_1 enrollID = =test_vp0
      22:13:52 POSTing path = http://172.17.0.3:5000/devops/query
      RESULT from query of chaincode from peer bddtests_vp0_1
      {
          "OK": "977"
      }
Container bddtests_vp2_1 enrollID = =test_vp2
      22:13:52 POSTing path = http://172.17.0.6:5000/devops/query
      RESULT from query of chaincode from peer bddtests_vp2_1
      {
          "OK": "1000"
      }
Container bddtests_vp3_1 enrollID = =test_vp3
      22:13:52 POSTing path = http://172.17.0.4:5000/devops/query
      RESULT from query of chaincode from peer bddtests_vp3_1
      {
          "OK": "977"
      }
```

The behave test:

```
@issue_1942
Scenario: chaincode example02 with 4 peers, stop and start alternates, reverse
    Given we compose "docker-compose-4-consensus-batch.yml"
    And I register with CA supplying username "binhn" and secret "7avZQLwcUe9q" on peers:
                                  | vp0  |
    And I use the following credentials for querying peers:
                            | peer |   username  |    secret    |
                          | vp0  |  test_user0 | MS9qrN8hFjlE |
                          | vp1  |  test_user1 | jGlNl6ImkuDo |
                          | vp2  |  test_user2 | zMflqOKezFiA |
                          | vp3  |  test_user3 | vWdLCE00vJy0 |

    When requesting "/chain" from "vp0"
    Then I should get a JSON response with "height" = "1"

    When I deploy chaincode "github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02" with ctor "init" to "vp0"
                          | arg1 |  arg2 | arg3 | arg4 |
                          |  a   |  1000 |  b   |   0  |
    Then I should have received a chaincode name
    Then I wait up to "60" seconds for transaction to be committed to peers:
                          | vp0  | vp1 | vp2 | vp3 |

    When I query chaincode "example2" function name "query" with value "a" on peers:
                          | vp0 | vp1  | vp2 | vp3 |
    Then I should get a JSON response from peers with "OK" = "1000"
                          | vp0 |  vp1 | vp2 | vp3 |

    Given I stop peers:
                          | vp2 |
    And I register with CA supplying username "test_user3" and secret "vWdLCE00vJy0" on peers:
                          | vp3  |

    When I invoke chaincode "example2" function name "invoke" on "vp3" "3" times
                          |arg1|arg2|arg3|
                          | a  | b  | 1  |
    Then I should have received a transactionID
    Then I wait up to "180" seconds for transaction to be committed to peers:
                          | vp0 | vp1 | vp3 |

    When I query chaincode "example2" function name "query" with value "a" on peers:
                          | vp0  | vp1 | vp3 |
    Then I should get a JSON response from peers with "OK" = "997"
                          | vp0  | vp1 | vp3 |

    Given I start peers:
                          | vp2  |
    And I wait "120" seconds

    Given I stop peers:
                          | vp1  |
    When I invoke chaincode "example2" function name "invoke" on "vp3" "20" times
                          |arg1|arg2|arg3|
                          | a  | b  | 1  |
    Then I should have received a transactionID
    Then I wait up to "300" seconds for transaction to be committed to peers:
                          | vp0  | vp2 | vp3 |

    When I query chaincode "example2" function name "query" with value "a" on peers:
                          | vp0  | vp2 | vp3 |
    Then I should get a JSON response from peers with "OK" = "977"
                          | vp0  | vp2 | vp3 |
```

**Comment by corecode** [comment]
I don't get this divergence, but some sort of request duplication.

**Comment by tuand27613** [comment]
running with commit 35326c2,  seeing the same issue as @corecode,  got result of "973" instead of "977",  very consistent but definitely some sort of duplication

If I set CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST=1s then the test case runs perfectly.
@jyellick @corecode, set nullrequest as default ?

**Comment by jyellick** [comment]
@tuand27613 commit 35326c2 does not include PR #1943 / #1941 (for 0.5 or master respectively).  Request duplication is possible and expected at that code level, but should be fixed with the relevant PR applied.

**Comment by scottz64** [comment]
Kostas, with your commit 6524f7c, for the original scenario (stop 2 nodes, invokes, restart 2 nodes, invokes), the behavior is improved: the consensus resumes and all peers are in sync and process additional invokes. However, the requests that were queued while only 2 peers were running appear to be lost. Another thing we cannot explain yet: our behave test for the same original scenario (attached with other logs) passes.
[june22_bug1874_repro_6524f7c.tar.gz](https://github.com/hyperledger/fabric/files/328718/june22_bug1874_repro_6524f7c.tar.gz)

**Comment by scottz64** [comment]
@kcrhistidis The retesting of 1942 showed no change when using commit  6524f7c, The problem behavior remains.

**Comment by kchristidis** [comment]
@scottz64 Understood. Not surprised, the nature of this problem seems to be different.

**Comment by scottz64** [comment]
=== OBSERVATION (No change with image de2c77e. Same as when originally reported on 35326c2):
===     After stopping and starting PEER2, and then stopping PEER1,
===     PEER2 must be part of the consensus, as the others process more invokes, but
===     PEER2 does not show the correct value (it shows the "init" values) when queried.
=== NEW OBSERVATION:
===     After requesting an additional large number of invokes (200 in this testcase),
===     PEER2 does catch up and all 3 peers are in sync - HOWEVER it looks like
===     they processed TOO MANY (33 more than the 227 that were requested)!!!

$ go run Consensus_S2_4IQ_R2_2IQ_S1_1IQ_20IQ_200IQ.go
Using nullrequest=1s
Using default batchsize=2, K=10
PEER_IMAGE=rameshthoomu/peer:de2c77e
MEMBERSRVC_IMAGE=rameshthoomu/membersrvc:de2c77e
CONSENSUS=pbft
PBFT_MODE=batch
Number of PEERS are 4
Is Security and Privacy enabled Y

**Comment by scottz64** [comment]
[june23_de2c77e_1942_repro.tar.gz](https://github.com/hyperledger/fabric/files/330491/june23_de2c77e_1942_repro.tar.gz)

**Comment by scottz64** [comment]
I guess I could have provided this too. Our GoSDK uses local_fabric.sh script to start docker images, and normally passes the following parms to override the defaults:  
    docker run  -d --name=PEER$peer_id -it \
               -e CORE_VM_ENDPOINT="http://$IP:$PORT" \
               -e CORE_PEER_ID="vp"$peer_id \
               -e CORE_SECURITY_ENABLED=true \
               -e CORE_SECURITY_PRIVACY=true \
               -e CORE_PEER_ADDRESSAUTODETECT=true -p $REST_PORT:5000 -p `expr $USE_PORT + 1`:30303 \
               -e CORE_PEER_DISCOVERY_ROOTNODE=$IP:30001 \
               -e CORE_PEER_PKI_ECA_PADDR=$IP:50051 \
               -e CORE_PEER_PKI_TCA_PADDR=$IP:50051 \
               -e CORE_PEER_PKI_TLSCA_PADDR=$IP:50051 \
               -e CORE_PEER_LISTENADDRESS=0.0.0.0:30303 \
               -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft \
               -e CORE_PBFT_GENERAL_MODE=batch \
               -e CORE_PBFT_GENERAL_N=4  \
               -e CORE_PBFT_GENERAL_TIMEOUT_REQUEST=10s \
               -e CORE_PBFT_TIMEOUT_NULLREQUEST=1s \
               -e CORE_PEER_LOGGING_LEVEL=error \    ### but I set debug for attaching data
               -e CORE_VM_DOCKER_TLS_ENABLED=false \
               -e CORE_SECURITY_ENROLLID=$USER_NAME \
               -e CORE_SECURITY_ENROLLSECRET=$SECRET_KEY $PEER_IMAGE peer node start

**Comment by jyellick** [comment]
There appears to be an unrelated CI failure, but the behave test is working for me locally after #1987

**Comment by scottz64** [comment]
I reran tests using 9f5666f. 
[1942repro9f5666f.tar.gz](https://github.com/hyperledger/fabric/files/332536/1942repro9f5666f.tar.gz)
See attached logs, and refer to my comments yesterday for test scenario I used today. Although it is working much better now, there is still a temporary time period where querying peer2 provides inaccurate results. From a user's perspective, this seems wrong.

Consensus_S2_5I_R2_S1_2I_20I.go:
After restarting peer2 and sleeping a minute, and 2 Invokes, querying the values for peer2 produces the init values. In other words, it seems to be functional but peer2 is not caught up with the other 3 peers. That seems wrong, but maybe we need more invokes? The parameters I was using: K=10, batchsize=2, and CORE_PBFT_TIMEOUT_NULLREQUEST=1s.
Then after stopping peer1, and after just 2 Invokes, peer2 should be sync'd with vp0 and vp3, but querying peer2 still gives me the "init" values, even though vp0 and vp3 have correctly processed the transactions (apparently with consensus working amon **That seems wrong.** g vp0 vp3 and vp2). **Getting back incorrect values is wrong.**  However, after 22 invokes, the 3 peers are all in sync AND have correct values for A & B (no duplicates).  

In a similar test, the problem with "peer2 showing init values" was still prevalent after 22 invokes - although all 3 peers did look perfect after 40.

Hmmm. Since the two tests seemed inconsistent soon after stopping peer1, I modified the testcase to increase sleep times immediately after stopping peer1 (20 secs) and also after the first two subsequent invokes (60 secs) before any queries. That extra time allowed the 3 peers to sync up and look correct for my first query after stopping peer1. Hooray! So it wasn't the number of transactions, but rather time that healed the wound.  :) 

Thus, although things seem to settle correctly after a minute or so (when no traffic) or longer (with more traffic), any peer2 queries within that interval produce an inaccurate response. At that time, Peer2 is one of the 3 peers in a functioning consensus network, so it should never provide inaccurate query responses.

**Comment by jyellick** [comment]
@scottz64 I think we need to define what **incorrect value** means. My strong suspicion is that the value is not in fact at all incorrect, but I would more accurately say it is **stale**.

In any asynchronous distributed system, it is perfectly normal and expected that some nodes will have more recent information than others.

In this case, when the node rejoins the network, it has missed some transactions, but it cannot know whether it has truly missed them, or they have not arrived yet.  So, it continues to help the network make progress by participating and ordering requests, even though it cannot execute them.  Eventually, the new replica's PBFT log size is exhausted, and it realizes that the network is moving on without it (or in this case, the network cannot make progress without the new node, and must view change), so, it must perform state transfer to retrieve whatever information it is missing.  At this point, the node will actually mark itself as out of date, and respond with an error to queries until the state transfer completes.  Once the state transfer is complete (assuming some other parameters are correct), then the node will be up to date and start participating once more.

**Comment by scottz64** [comment]
Issues 1942 and 1874 are fixed. We tested v0.5 commit 5efed61 (images built today 6/27 after noon, including PRs 2007 and 2016), and confirmed using testcases in both Behave and GO SDK.
