### ISSUE TITLE
Create glossary of terms

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#195]
Create a  glossary of terms describing the terms used in Openchain. This includes terms such as

Peer
Validating peer
Non-validating peer
Leader
Chaincode
etc.

There glossary should be linked to from the readme in a prominent location.

**Comment by srderson** [comment]
I defined some of these terms in https://github.com/openblockchain/obc-peer/blob/master/docs/Network%20Setup.md. I think we can add glossary.md to the docs folder and link to it from the main README.md.

**Comment by seanbarclay** [comment]
@angrbrd @binhn please create a separate repo for API Documentation. Have Getting Started link to primer content in docs that describes OBC overview, basics, etc. Terms should go in the basics section.

**Comment by angrbrd** [comment]
@frankyclu already has a very detailed glossary of terms. He just needs to move that information from the wiki space to GitHub. We touched base and he will finish that. Reassigning.

**Comment by seanbarclay** [comment]
FYI- I committed this so you can see WIP. I'm still working on the formatting to match @frankyclu's word doc. 
https://github.com/openblockchain/obc-website/blob/master/docs/Terms_and_Definitions.md

**Comment by frankyclu** [comment]
re-posted here with appropriate format

https://github.com/openblockchain/obc-getting-started/blob/master/glossary.md

**Comment by muralisrini** [comment]
The second "Chain Transactor" should be "Chain Auditor"

**Comment by frankyclu** [comment]
@muralisrini  nice catch, corrected the error
