### ISSUE TITLE
make: *** No rule to make target `sdk/node/doc/assets/js/modernizr.js', needed by `build/image/src/.dummy'.  Stop.

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1950]
## Description

My environment:
windows 7 -> virtualbox Version 5.0.16 r105871 -> gitbash -> vagrant 1.8.1 
While running 'make all' on a new VM, I see this message: 
make: **\* No rule to make target `sdk/node/doc/assets/js/modernizr.js', needed by`build/image/src/.dummy'.  Stop.

At that point, the Make stops. 
## Describe How to Reproduce

1.Open a gitbash window.
2.Destroy any existing Vagrant VMs.  
3.vagrant up
4.vagrant ssh
5.cd to 'fabric' directory, for example, cd  $GOPATH/src/github.com/hyperledger/fabric
6.Make all 

As an alternative, it might be possible to simply start an existing vagrant vm, run 'make clean', and then run 'make all'.

Workaround:  git checkout modernizr.js  and enter 'make all' again.  A new message appears:

$ make all
make: **\* No rule to make target `sdk/node/doc/modules/_typedoc_special_d_.html', needed by`build/image/src/.dummy'.  Stop.
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric$ cd sdk/node/doc/modules

YOu can enter 'git checkout _typedoc_special_d_.html 

AT that point, you have to 'sudo make all'

**Comment by angrbrd** [comment]
This issue is addressed with PR #1982, which is now merged. Please verify and close. Thanks.

**Comment by jjjjibm** [comment]
I ran 'make all' with today's latest, and did not encounter this error.  Thanks!
