### ISSUE TITLE
make all:  panic: runtime error: invalid memory address or nil pointer dereference [signal 0xb code=0x1 addr=0x8 pc=0x4c36af]

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1952]
## Description

I am running 'make all' and encountered this panic in the section that starts the unit 

RACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
--- FAIL: TestReadUserSet (0.00s)
        eca_test.go:341: Failed to read user set: [Identity or token does not match.]
        eca_test.go:367: Failed to read user set: [Signature verification failed.]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4c36af]

goroutine 124 [running]:
panic(0xb25fc0, 0xc82000e120)
        /opt/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8202a9320)
        /opt/go/src/testing/testing.go:467 +0x192
panic(0xb25fc0, 0xc82000e120)
        /opt/go/src/runtime/panic.go:426 +0x4e9

Here is the full stdout for context: 
start serving...
Running tests....
test_user0 [0xc820279380 0xc8202794a0 0xc8202795c0 0xc820279680]**********************\* ATTR test_user0 company ACompany
**********************\* ATTR test_user0 position Software Staff
**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
test_user0 [0xc820139860 0xc820139980 0xc820139a40 0xc820139b00]**********************\* ATTR test_user0 position Software Staff
**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
**********************\* ATTR test_user0 company ACompany
test_user0 [0xc820326ba0 0xc820326cc0 0xc820326de0 0xc820326ea0]**********************\* ATTR test_user0 company ACompany
**********************\* ATTR test_user0 position Software Staff
**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
test_user0 [0xc820349140 0xc820349260 0xc820349380 0xc820349440]**********************\* ATTR test_user0 company ACompany
**********************\* ATTR test_user0 position Software Staff
**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
test_user0 [0xc82039e960 0xc82039ea20 0xc82039eae0 0xc82039ec00]**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
**********************\* ATTR test_user0 company ACompany
**********************\* ATTR test_user0 position Software Staff
test_user0 [0xc820409380 0xc820409440 0xc820409500 0xc820409620]**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
**********************\* ATTR test_user0 company ACompany
**********************\* ATTR test_user0 position Software Staff
test_user0 [0xc82044aba0 0xc82044acc0 0xc82044ad80 0xc82044ae40]**********************\* ATTR test_user0 position Software Staff
**********************\* ATTR test_user0 position Software Engineer
**********************\* ATTR test_user0 business_unit Sales
**********************\* ATTR test_user0 company ACompany
2016/06/22 18:20:04 Log level not recognized '', defaulting to DEBUG: logger: invalid log level
2016/06/22 18:20:04 Working at security level [256]
TRACE: 2016/06/22 18:20:04 ca.go:332: Reading CA private key.
TRACE: 2016/06/22 18:20:04 ca.go:373: Reading CA certificate.
TRACE: 2016/06/22 18:20:04 eca.go:309: gRPC ECAP:CreateCertificate
TRACE: 2016/06/22 18:20:04 ca.go:754: Reading token for admin.
TRACE: 2016/06/22 18:20:04 eca.go:327: id or token mismatch: id=admin
--- FAIL: TestCreateCertificatePairAdmin (0.00s)
        eca_test.go:235: Failed to enroll testAdmin: [Identity or token does not match.]
TRACE: 2016/06/22 18:20:04 eca.go:521: gRPC ECAA:RegisterUser
TRACE: 2016/06/22 18:20:04 eca.go:549: ECAA.checkRegistrarSignature
TRACE: 2016/06/22 18:20:04 ca.go:492: Reading certificate for admin and usage 1
TRACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
TRACE: 2016/06/22 18:20:04 eca.go:587: ECAA.checkRegistrarSignature: failure for admin
--- FAIL: TestRegisterUser (0.00s)
        eca_test.go:245: Signature verification failed.
TRACE: 2016/06/22 18:20:04 eca.go:309: gRPC ECAP:CreateCertificate
TRACE: 2016/06/22 18:20:04 ca.go:754: Reading token for testUser.
TRACE: 2016/06/22 18:20:04 eca.go:327: id or token mismatch: id=testUser
--- FAIL: TestCreateCertificatePairTestUser (0.00s)
        eca_test.go:256: Failed to enroll testUser: [Identity or token does not match.]
TRACE: 2016/06/22 18:20:04 eca.go:521: gRPC ECAA:RegisterUser
TRACE: 2016/06/22 18:20:04 eca.go:549: ECAA.checkRegistrarSignature
TRACE: 2016/06/22 18:20:04 ca.go:492: Reading certificate for admin and usage 1
TRACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
TRACE: 2016/06/22 18:20:04 eca.go:587: ECAA.checkRegistrarSignature: failure for admin
--- FAIL: TestRegisterDuplicateUser (0.00s)
        eca_test.go:266: Expected error was not returned when registering user twice: [Signature verification failed.]
TRACE: 2016/06/22 18:20:04 eca.go:521: gRPC ECAA:RegisterUser
TRACE: 2016/06/22 18:20:04 eca.go:549: ECAA.checkRegistrarSignature
TRACE: 2016/06/22 18:20:04 ca.go:492: Reading certificate for admin and usage 1
TRACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
TRACE: 2016/06/22 18:20:04 eca.go:587: ECAA.checkRegistrarSignature: failure for admin
--- FAIL: TestRegisterAuditor (0.00s)
        eca_test.go:277: Signature verification failed.
TRACE: 2016/06/22 18:20:04 eca.go:521: gRPC ECAA:RegisterUser
TRACE: 2016/06/22 18:20:04 eca.go:549: ECAA.checkRegistrarSignature
TRACE: 2016/06/22 18:20:04 ca.go:492: Reading certificate for testUser and usage 1
TRACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
TRACE: 2016/06/22 18:20:04 eca.go:587: ECAA.checkRegistrarSignature: failure for testUser
TRACE: 2016/06/22 18:20:04 eca.go:246: gRPC ECAP:ReadCACertificate
TRACE: 2016/06/22 18:20:04 eca.go:475: gRPC ECAP:ReadCertificate
TRACE: 2016/06/22 18:20:04 ca.go:514: Reading certificatess for testUser.
TRACE: 2016/06/22 18:20:04 eca.go:309: gRPC ECAP:CreateCertificate
TRACE: 2016/06/22 18:20:04 ca.go:754: Reading token for testAuditor.
TRACE: 2016/06/22 18:20:04 eca.go:327: id or token mismatch: id=testAuditor
TRACE: 2016/06/22 18:20:04 eca.go:600: gRPC ECAA:ReadUserSet
TRACE: 2016/06/22 18:20:04 ca.go:772: Reading role for testAuditor.
TRACE: 2016/06/22 18:20:04 ca.go:492: Reading certificate for testAuditor and usage 1
TRACE: 2016/06/22 18:20:04 ca.go:497: err <nil>
--- FAIL: TestReadUserSet (0.00s)
        eca_test.go:341: Failed to read user set: [Identity or token does not match.]
        eca_test.go:367: Failed to read user set: [Signature verification failed.]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4c36af]

goroutine 124 [running]:
panic(0xb25fc0, 0xc82000e120)
        /opt/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8202a9320)
        /opt/go/src/testing/testing.go:467 +0x192
panic(0xb25fc0, 0xc82000e120)
        /opt/go/src/runtime/panic.go:426 +0x4e9
github.com/hyperledger/fabric/membersrvc/ca.TestReadUserSet(0xc8202a9320)
        /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca/eca_test.go:370 +0x79f
testing.tRunner(0xc8202a9320, 0x1183480)
        /opt/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /opt/go/src/testing/testing.go:582 +0x892
FAIL    github.com/hyperledger/fabric/membersrvc/ca     10.274s
?       github.com/hyperledger/fabric/membersrvc/protos [no test files]
ok      github.com/hyperledger/fabric/peer      0.085s  coverage: 11.0% of statements
ok      github.com/hyperledger/fabric/protos    0.118s  coverage: 5.8% of statements
?       github.com/hyperledger/fabric/tools/busywork/benchmarks [no test files]
ok      github.com/hyperledger/fabric/tools/busywork/busywork   2.424s   coverage: 88.9% of statements
?       github.com/hyperledger/fabric/tools/busywork/counters   [no test files]
ok      github.com/hyperledger/fabric/tools/dbutility   0.144s  coverage: 32.4% of statements
Stopping peer..
make: **\* [unit-test] Error 1
vagrant@ubuntu-1404:/opt/gopath/src/github.com/hyperledger/fabric

Here are all logs from /var/logs: 
[logs.zip](https://github.com/hyperledger/fabric/files/328573/logs.zip)
## Describe How to Reproduce

1.Start vagrant
2.Go to 'fabric' directory, for example $GOPATH/src/github.com/hyperledger/fabric
3.Make all

**Comment by JonathanLevi** [comment]
Thanks for the detailed reporting! Can provide a fix momentarily...

**Comment by JonathanLevi** [comment]
@jjjjibm Please let me/us know if anything/more stuff comes up that we can help you from the 'code'/master end... esp. crashes!
