### ISSUE TITLE
Jenkins Builds are failing with grpcio package error

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1956]
## Description

We are observing CI Builds are failing in Jenkins (X86 and Z) node machines with the below error messages 
 `0:41:59     from google.protobuf import descriptor as _descriptor
00:41:59 ImportError: No module named google.protobuf.` 
or 
 `9:43:41 sudo pip install -q 'grpcio==0.13.1'
19:43:41 sudo: unable to resolve host hyp-x86-64-915
19:43:41 sudo: no tty present and no askpass program specified` We are also facing the similar issue in Z machines. We are tracking work in-progress comments in issue #1922.

Issue introduced on commit# 057b83a
## Describe How to Reproduce

All Jenkins builds are failing with the above error messages. Please verify the Jenkins build console output for reference.

**Comment by rameshthoomu** [comment]
This issue fixed in X86 Jenkins machines after installing grpcio package. We are still seeing the same error message in Z machines. @jkirke: Is working on this.

**Comment by gregmisiorek** [comment]
i noticed Jenkins failures in many other issue resolutions.

**Comment by rameshthoomu** [comment]
This issue is fixed with PR #1940. Issue has been resolved after installing python grpcio package in Jenkins build machines.

@gregmisiorek : Most of the Jenkin build failures are resolved but still we have couple of known issues (car_test.go unit test is failing and Behave test is failing) in Linux on Z machine and observed behave tests are failing in x86. We have PR's open for the above fixes. 

Closing this issue.
