### ISSUE TITLE
Remove all redundant command-line flags from the Hyperledger Fabric Peer

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#1962]
## Description

All command-line flags that overlap variables in the YAML files should be removed from the peer. Why? Because both the command line flags and the YAML files define defaults for the options. Unless these options are identical, one or the other will be selected, and in fact, the YAML file does not override the command-line defaults in main.go. This is a maintenance nightmare and a severe usability bug. (I have just lived through this nightmare with the fact that GOMAXPROCS is now silently being set to 2 based on the command-line default, which now overrides the -1 default in the YAML file.)

All of the redundant command line flags should be removed until we implement a better way of handling configuration options, e.g. as discussed in #1309

**Comment by mastersingh24** [comment]
Plus you can actually achieve the same goal by setting environment variables on the command line which do override the values set in the YAML files

**Comment by vmorris** [comment]
I agree to a point, having both command line switches and environment variables to dynamically control launch configuration is non-orthogonal. Operlapping the options means that the switch cli defaults have to keep up with the static defaults in the config file... it's too much to try and map them all across and @mastersingh24 is right, environment variables achieve the same result.

I'd like to see some cli switches kept in or added though:
- help
- version
- verbose
- config file

**Comment by bcbrock** [comment]
@vmorris Your point is well-taken, there are some useful flags. I changed the title and my initial comments to suggest that we remove all flags that are redundant in the sense that they overlap YAML configuration options.

**Comment by JonathanLevi** [comment]
I really like being able to specify a config/YAML file so that we can ignore the one picked up from the default location - not just for easier configuration, but also for making it easier to reproduce/report issues (still worrying about another GOMAXPROCS-like 'incident' that is lurking behind some other 'default' behavior).
