### ISSUE TITLE
node-sdk: hlc.ts:  rolesToMask: incorrect iteration over roles array

### ISSUE THREAD

**Issue by rennman** [hyperledger-archives/fabric#1968]
commit b1ef2c909d8b3bb5a37044c111615c3f37b3e88e v0.5-developer-preview.

Using the sdk I was attempting to register a user with something other that the default, 'client', but was not able to get the registrationRequest to recognize the 'roles' attribute.

According to hlc.js:RegistrationRequest, roles is a string array. The switch in hlc.js:rolesToMask the switch is incorrectly iterating over the indexes of roles[] and not the values of roles[].

for (let role in roles) {
   switch (role) {

should be 

for (let role in roles) {
   switch (roles[role]) {

**Comment by rennman** [comment]
@angrbrd  @binhn @ghaskins
Spoke briefly with Anya. I fixed my local copy and am willing to submit a pull request for this, but I'm not sure where it should go. 

Should this be in v0.5-developer-preview, or master?

**Comment by srderson** [comment]
You'll need to submit two PRs, one for each branch. It sounds like this issue is a good one for consideration in the v0.5-developer-preview branch.
