### ISSUE TITLE
GetTempStateHash gives undefined error

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#197]
Calling `GetTempStateHash()` (for example from the `ExecTXs()` function in the new consensus package) results in an `undefined` error.

May have to do with the fact that it's an entirely new chain (no blocks); checking for that condition within the body of the function may be necessary.

**Comment by srderson** [comment]
@manish-sethi Could you take a look? I tried to replicate the problem in a test case, but haven't had any luck yet.

@kchristidis Is there an existing test case which shows this error or a set of commands on the CLI that we could run?

**Comment by kchristidis** [comment]
@srderson: It is an error that I get upon compiling the `newconsensus` package (if I uncomment the call to that function).

No test case since the stack below consensus hasn't been adapted to the new package. This was pushed yesterday so that Binh can work on #179, see [this comment](https://github.com/openblockchain/obc-peer/pull/175#issuecomment-153519930). You may want to defer until a test case is written.

**Comment by srderson** [comment]
Sorry, I didn't realize this was a compile time error. You need to change your code to something like

```
theLedger, hashErr := ledger.GetLedger()
if hashErr == nil {
  stateHash, hashErr = theLedger.GetTempStateHash()
}
```

The ledger is a singleton. `ledger.GetLedger()` gets the instance of the ledger and `theLedger.GetTempStateHash()` calls `GetTempStateHash()` on the instance.

**Comment by kchristidis** [comment]
Gotcha. Did the edit and works fine now. Will close this with an upcoming pull request.
