### ISSUE TITLE
make node-sdk-unit-tests fails: panic: Cannot parse block timeout: time: invalid duration

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1975]
## Description

Environment:  windows 7 -> virtualbox -> gitbash -> vagrant 
Ramesh Thoomu and I both see this failure running make node-sdk-unit-tests:

_<lines deleted>_ 
member services is started
Begin running tests in net mode ...
**ERROR: peer failed to start; see /tmp/node-sdk-unit-test/peer.log**

So we find this in peer.log:
=============================begin peer.log excerpt==============================
18:20:06.401 [consensus/controller] NewConsenter -> INFO 013^[[0m Creating default consensus plugin (noops)
panic: Cannot parse block timeout: time: invalid duration

goroutine 1 [running]:
panic(0xd2f5e0, 0xc8203e0d20)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/consensus/noops.newNoops(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/consensus/noops/noops.go:76 +0x956
github.com/hyperledger/fabric/consensus/noops.GetNoops(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/consensus/noops/noops.go:55 +0x48
github.com/hyperledger/fabric/consensus/controller.NewConsenter(0x2ac81e8506a0, 0xc8203ca200, 0x0, 0x0)
                                               28,2-9        42%
===================end peer.log excerpt =================================

Ramesh switched to an earlier commit, and the tests succeeded.  This is the commit that seems to cause the error: 2ad27bd

Entire peer.log  
[peer.zip](https://github.com/hyperledger/fabric/files/330639/peer.zip)
## Describe How to Reproduce

1.From Gitbash, synchronize your laptop with the latest level 
2.vagrant up
3.vagrant ssh
4.cd into 'fabric'.  For example, cd /opt/gopath/src/github.com/hyperledger/fabric
5.make node-sdk-unit-tests

**Comment by bmos299** [comment]
@jjjjibm does this occur with the latest npm install (assuming they are in sync).  Does @ratnakar-asara hit this on ubuntu?  Can you have someone else running windows with Vagrant try and reproduce asap?
Thanks.

**Comment by angrbrd** [comment]
@bmos299 

@diegomasini and I are investigating this now. We see it now on latest master as well. We are both in Vagrant on Mac. Error is below:

`panic: Cannot parse block timeout: time: invalid duration`

Will update shortly.

**Comment by bmos299** [comment]
Thanks @angrbrd.  I think this command only exist on the master branch?

**Comment by jjjjibm** [comment]
@bmos299, I'm in the midst of re-cloning my fabric to see if that eliminates the other issue.  By npm install, I take it you want me to try 'hlc' instead of make node-sdk-unit-tests?  Not sure how that works.

**Comment by angrbrd** [comment]
OK @diegomasini and I just tested a fix for this locally. Will require two PRs. I will submit momentarily.

**Comment by bmos299** [comment]
Wow! Thanks @angrbrd !

**Comment by angrbrd** [comment]
@ghaskins is also aware that PR is ready. Thanks.
