### ISSUE TITLE
make unit-tests fails after first run

### ISSUE THREAD

**Issue by jeffgarratt** [hyperledger-archives/fabric#1995]
## Description

if you run the 'make unit-test' command more than once, you will get a failure with 'text file busy' for ca.go test. I found I had to manually delete the following folder to have the unit-test pass.

> rm -rf membersrvc/ca/.ca/
## Describe How to Reproduce

Issue the command:

> make unit-test 

Then issue the command again, and you should get the following failure.

> TRACE: 2016/06/24 15:00:09 ca.go:397: Creating certificate for test_user0.
> FAIL
> coverage: 62.4% of statements
> End running tests....
> Failed removing [.ca] [remove ./.ca/aca.db: text file busy]

**Comment by jeffgarratt** [comment]
@diegomasini Hey Diego.  Ran into this after syncing with master this morning.  Seems like a simple fix.  Let me know if any questions.

**Comment by diegomasini** [comment]
Thanks @jeffgarratt! Fixing it now.
