### ISSUE TITLE
Ability to deploy the same chaincode multiple times

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#200]
Currently if a developer/user wants to deploy the same piece of code multiple times, either the URL or the version has to be distinct. These are used to construct the chaincode ID.

Other alternatives considered (perhaps to be revisited in the future):
1. Have the user specify a unique name at the time of deploy and use it as part of the chaincodeID - need to manage collisions
2. Add the init args/constructor message or timestamp also as part of the chaincodeID

**Comment by prjayach** [comment]
For now we have decided that chaincode URL and version will uniquely identify a chaincode deployment. If a user wants to deploy the same piece of code with possibly different initial args, they need to use different version numbers. I don't think we are going to support anything more at least until MVP.

**Comment by prjayach** [comment]
@markparz Can be closed for now as we have a reasonable implementation for this. Any further enhancements will be post-MVP.

**Comment by muralisrini** [comment]
closing per above comments
