### ISSUE TITLE
Support ability to build code (chaincode) from local folder or remote repository

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#201]
Current implementation only permits chaincode to be placed in a local folder. No support for specifying a remote location where the chaincode is available. This is needed for multi-validator scenario where each validator builds the code themselves.

**Comment by binhn** [comment]
@prjayach which milestone should this one be in?

**Comment by prjayach** [comment]
Lets put it for Milestone 4 (milestone 3 ends in a week, right?). Next week we'll focus on query and chaincode-invoke-chaincode as those are higher priority. Will get to this the week after that.

**Comment by muralisrini** [comment]
merged. Closing.
