### ISSUE TITLE
Panic: "invalid memory address or nil pointer dereference" in response to /chain/blocks/<N> API

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#2012]
## Description

This is a panic that appears to be coming from the /chain/blocks/<N> API.  The panic is not fatal, but is being caught by the gocraft/web stuff, which carries on. However it does cause the test to fail (or, I assume this is what's causing it to fail.)

Here is the log file of the failing peer. The panic is buried in the middle of it.

[stderr.txt](https://github.com/hyperledger/fabric/files/332807/stderr.txt)
## Describe How to Reproduce

I am not yet sure if this is reproducible. Here is the context:

```
commit 2aeddd6929d7108bda6a498d1d64e771177c5270
Merge: ef5c8c7 99bf9b3
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Fri Jun 24 17:41:14 2016 -0400

    Merge pull request #1915 from frankyclu/issue-1844-workaround

    Issue 1844 (multi-account with TCert attributes) workaround
```

This is the soon-to-be "official" form of the busywork `stress2b` test I was trying to run:

```
STRESS2 = ./driver \
        -transactions 10000 \
        -peerBurst 10000 \
        -interlock \
        -keepLog \
        -checkAgreement -dupCheck

STRESS2_CONFIG = \
    @CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST=3s \
    CORE_PEER_VALIDATOR_CONSENSUS_BUFFERSIZE=100000 

stress2b: 
    @$(STRESS2_CONFIG) \
    $(NETWORK) -batch 4
    @echo "makefile: Sleeping 10 seconds to allow peers to interlock"; sleep 10
    @$(STRESS2)

```

**Comment by bcbrock** [comment]
Yes, this failure mode is reproducible on my system. Unfortunately I have never seen the test described above pass on my system at the documented commit level. Note that this is only one of the failure modes.

**Comment by bcbrock** [comment]
@jyellick @dubek If I understand the backtrace correctly, I believe the error is originating in core/rest/rest_api.go around line 636. It looks like this is code that you guys touched last, probably in part to fix errors I was seeing with bogus responses coming back from the chain/blocks/<N> API calls.

**Comment by dubek** [comment]
I looked at the flow. It can happen when ledger's GetBlockByNumber returns block=nil AND err=nil. This can happen when you fetch a block whose number is less than the chain height, but the block doesn't exist in the DB.

The fix in rest_api.go should be better handling of the different cases of err and block values. I'll be able to craft a PR on Monday.

A quick fix if you want to keep working on your scenarios (that's not the proper code change I'm suggesting) is:

```
diff --git a/core/rest/rest_api.go b/core/rest/rest_api.go
index ea9be2e..3e6dc69 100644
--- a/core/rest/rest_api.go
+++ b/core/rest/rest_api.go
@@ -633,7 +633,11 @@ func (s *ServerOpenchainREST) GetBlockByNumber(rw web.ResponseWriter, req *web.R
                        default:
                                rw.WriteHeader(http.StatusInternalServerError)
                        }
-                       encoder.Encode(restResult{Error: err.Error()})
+                       if err == nil {
+                               encoder.Encode(restResult{Error: ErrNotFound.Error()})
+                       } else {
+                               encoder.Encode(restResult{Error: err.Error()})
+                       }
                } else {
                        // Success
                        rw.WriteHeader(http.StatusOK)

```

**Comment by dubek** [comment]
And, if we're in the "fix everything twice" mood, maybe `fetchBlockFromDB` (`core/ledger/blockchain.go:290`) should not return nil,nil when a block is not found, but rather `return nil, fmt.Errorf("Block number %d not found in DB", blockNumber)` . I'm not familiar with that area of that code so I'm not sure my suggestion makes sense.

**Comment by jyellick** [comment]
@dubek This has been the subject of some debate and was flagged in #1610

**Comment by dubek** [comment]
The fix to rest_api.go to deal with the `nil,nil` response is in PR #2027.
