### ISSUE TITLE
Validators needs to ensure that the code they are executing is the code that was originally deployed

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#202]

**Comment by muralisrini** [comment]
Talked to @binhn ... 
- currently docker maintains images. If image is not found, we would need to recreate
- to recreate image we'll have to fetch chaincode from block
- at that time we might do another hash comparison to assure chaincode hasn;t changed

This work is dependent upon creating transactions on blocks. Moving it to sprint 3 for now.

**Comment by binhn** [comment]
@prjayach @muralisrini Do we hash the chaincode source code today by itself somewhere? I know it is hased as part of the whole tx, but I think that we need to be very specific about what constitutes an instance of chaincode and hash that. When we deploy a chaincode today, we have the path, version, and optionally constructor.  Could we assume all of them + code making up a unique hash for an instance of chaincode?  

chaincodeID = Hash(code+path+version+constructor)

We further assume that the chaincode can't be modified in the container (big assumption), so the only time we have to check is when we need to rebuild the image or restart the container. At this point, we compare the chaincodeID (from the requested transaction) and the hash reHash(code+path+version+constructor)

**Comment by prjayach** [comment]
@binhn We do not hash the chaincode source code today. I agree with this proposal. About a month back we had this discussion about what should constitute a chaincodeID - I had suggested to include the constructor then (issue #200), to allow the same piece of code to be instantiated (deployed) multiple times with different constructors. Adding the code makes sense to address this issue, as well as issue #200 

Is there someway the chaincode can be modified inside the container? The process is already running, so if someone tried to modify it, they need to kill the process, recompile the go code and start it again to reflect the change. Killing the process will end the bidirectional stream and the only way back for the chaincode is to restart the container - we will include the check proposed in this issue when we restart the container. Why arent we protected against the assumption you mention - am I missing something?

**Comment by binhn** [comment]
Some feels that the version in chaincodeID = Hash(code+path+version+constructor) might semantically troublesome. We could call it anything, say tag -- something to allow differentiation when the code and path are the same, and constructor is also the same or not implemented (constructor is optional).

I think we should proceed with the implementation of this issue.

**Comment by muralisrini** [comment]
related #373 @ghaskins
