### ISSUE TITLE
Add log-level support for chaincode

### ISSUE THREAD

**Issue by zuowang** [hyperledger-archives/fabric#2023]
## Description

Docker daemon has a very high cpu usage when run performance test.
Profile shows that the high cpu usage is caused by verbose logging in chaincode container.
When docker daemon started with option --log-driver="none", the problem gone.
## Describe How to Reproduce

1. Start 4 validator peer nodes on single node.
2. Deploy chaincode_example02, start 20 clients to invoke chaincode_example02
3. Use top to see docker daemon's cpu usage

**Comment by zuowang** [comment]
I will add an option log-level for chaincode to fix this issue.

**Comment by christo4ferris** [comment]
@zuowang I'm closing this issue since there are documented means of configuring the logging as discussed in #2024. If you disagree and think that this still needs to be addressed, please re-open with a comment.
