### ISSUE TITLE
need to change acronym

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#2026]
## Description

The HLC acronym should be changed to reflect that this SDK applies to the Fabric, not to Hyperledger generally.
## Describe How to Reproduce

N/A - this needs to be changed throughout the code and documentation

**Comment by christo4ferris** [comment]
@smithbk ^^ we should rename this 'fabric-node-sdk' to be consistent with other components (fabric-peer, fabric-membersrvc, fabric-chaintool, etc)

**Comment by christo4ferris** [comment]
or maybe 'fabric-sdk-node' so that they all sort together assuming we have other SDKs.

**Comment by smithbk** [comment]
@christo4ferris I'll change the acronym to "hfc" for "Hyperledger Fabric Client".  OK?

**Comment by smithbk** [comment]
@christo4ferris In the fabric/sdk/node/README.md or anything under fabric/sdk/node, the acronym of course refers to the HLC node SDK.  The "hfc" npm module is of course node.  If there is documentation outside of the context of the node SDK, of course the acronym "hlc" will need to be qualified by saying the "node hlc" or "node hlc SDK".

**Comment by smithbk** [comment]
Yikes, old habits die hard.   I meant to say ...
 If there is documentation outside of the context of the node SDK, of course the acronym "hfc" will need to be qualified by saying the "node hfc" or "node hfc SDK".

**Comment by christo4ferris** [comment]
@smithbk 'hfc' is fine, I suppose, but not very descriptive. I think I would prefer fabric-sdk (ok, I can be convinced that the npm module by definition means it is the node sdk). Basically, it should be something that when a dev does a search on NPM returns the obvious result. The problem with a TLA is that you need to know what it means before you run into it. Search on 'hyperledger' and which of the results do you think is the correct one? https://www.npmjs.com/search?q=hyperledger If we have a hyperledger account and publish a 'fabric-sdk' then it is crystal clear which one you want.
