### ISSUE TITLE
Ledger GetState needs argument to return committed DB state only

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#203]
Today, Ledger.GetState always looks in memory first (the state delta) and returns the value found in the delta if one exists.

It's possible that a caller wants to only fetch the committed state. They could use GetStateSnapshot today, but this is very heavy. There should be an option in Ledger.GetState to retrieve the state only from the DB. This corresponds to the most recently committed state.

Ledger.GetState(chaincodeID string, key string, committed boolean)

**Comment by binhn** [comment]
closed per manish
manishsethi [9:13 AM] 
BTW, you can close #203 as well

​[9:14] 
You assigned it to me but it is same as #206
