### ISSUE TITLE
HostConfig will be deprecated since Docker 1.12

### ISSUE THREAD

**Issue by yeasy** [hyperledger-archives/fabric#2044]
## Description

With Docker 1.12, the following error will happens when deploying chaincode with hyperledger fabric.

```
[dockercontroller] Start -> ERRO 02e start-could not start container API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
```
## Describe How to Reproduce

Use Docker 1.12, and deploy chaincode with hyperledger fabric.

**Comment by christo4ferris** [comment]
for clarity, this is the deprecated feature that is currently being used https://docs.docker.com/engine/deprecated/#hostconfig-at-api-container-start

The offending code is here: https://github.com/hyperledger/fabric/blob/master/core/container/dockercontroller/dockercontroller.go#L109

**Comment by mastersingh24** [comment]
So it looks like we just need to move this to the create call rather than the start call I think

**Comment by christo4ferris** [comment]
@mastersingh24 I believe so

**Comment by yeasy** [comment]
Since no one claims working on this, I will try to fix it.

**Comment by christo4ferris** [comment]
@yeasy thanks!

**Comment by stylixboom** [comment]
In this mean time, to make the patch #2263 works, we also need to get 

github.com/fsouza/go-dockerclient
github.com/docker/docker
github.com/docker/engine-api
github.com/docker/go-units
github.com/hashicorp/go-cleanhttp
github.com/Sirupsen/logrus
github.com/opencontainers/runc

into the vendor directory.

**Comment by yeasy** [comment]
@stylixboom 
The `github.com/fsouza/go-dockerclient` is already inside the vendor.json.

You mean the current vendor.json does not work? 
If so, we may update it in another patch.
Thanks!

**Comment by stylixboom** [comment]
@yeasy 
Yes, the go-dockerclient probably outdated after a fresh git clone of hyperledger/fabric.
So, manually fetch the recent version with it's dependencies above make this patch #2263 works fine for me.

BTW, thank you for your patch.

**Comment by muralisrini** [comment]
@yeasy thanks from me too.
