### ISSUE TITLE
node SDK automatically generated files should not be checked into git

### ISSUE THREAD

**Issue by smithbk** [hyperledger-archives/fabric#2050]
## Description

fabric/sdk/node/doc and fabric/sdk/node/lib (and maybe other directories?) contain automatically generated files and should not be checked into git.  The reason this was done initially was because we want these files to be part of each "npm publish" for the "hfc" node module and it was thought that the only way to do this was to NOT have these directories in .gitignore files.  However, after further investigation, it is possible to put these directories in .gitignore files and also create .npmignore files which do NOT contain these directories.  npm will then ignore the .gitignore files and use .npmignore file instead.   See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

So I think the following steps will solve this and should be done:
1) Copy fabric/sdk/node/.gitignore to fabric/sdk/node/.npmignore
2) Add "doc/" and "lib/" to fabric/sdk/node/.gitignore
3) Delete the doc and lib directories
4) Create a fabric/sdk/node/bin/build script which does everything currently done in the fabric/Makefile under the "node-sdk" target, which is:
        cp ./protos/_.proto ./sdk/node/lib/protos
        cp ./membersrvc/protos/_.proto ./sdk/node/lib/protos
        cd ./sdk/node && sudo apt-get install npm && npm install && sudo npm install -g typescript && sudo npm install typings --global && typings install
        cd ./sdk/node && tsc
        cd ./sdk/node && ./makedoc.sh
5) Edit fabric/Makefile to call fabric/sdk/node/bin/build and remove the above from Makefile
6) Create a fabric/sdk/node/bin/npm-publish script which does the following:
    a) calls the 'build' script from step #4
    b) performs an npm update according to https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package, which means this script should require the <update-type> argument (i.e. patch, minor, or major).  Note that the "npm version <update-type" actually updates the package.json file and must be done from the fabric/sdk/node directory.

We should always invoke the npm-publish script just before creating a pull request.
## Describe How to Reproduce

Check github to see these files

**Comment by angrbrd** [comment]
I have opened PR #2147 in order to address points 1-3 above. Points 4-5 have already been addressed by the time this issue was opened. And point 6 is being tracked in issue #2066.
