### ISSUE TITLE
Bring up a fully-connected network of at least 4 validators

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#208]
We cannot do meaningful tests on consensus unless we have the ability to bring up a fully-connected network of at least 4 validators and a couple of clients.

Bonus points for making this a process with as few steps as possible, as this will make consensus testing much faster.

**Comment by kchristidis** [comment]
@binhn Any idea whom should this be assigned to?

**Comment by binhn** [comment]
This is almost done except the CLI, which I am not clear at the moment how it sends msg to the network. Assigning this to @jeffgarratt

**Comment by binhn** [comment]
close per @kchristidis
