### ISSUE TITLE
goimports is broken with vendor support

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#210]
goimports puts invalid import paths when using with "vendor" support (GO15VENDOREXPERIMENT). 

For now suggestion would be to either (1) not run goimports or (2) accept all changes from goimports but fix the import statements by hand. 

You'd want to disable running goimports in your editor (if you have it so configured)

**Comment by binhn** [comment]
@muralisrini how to fix it if you already ran goimports and now go build no longer works?

**Comment by muralisrini** [comment]
What we had to do was this 
- run goimports to get all its goodness into my file (in addition to "imports" it does other cleanup)
- then go just fix the "imports" section by hand

For instance when I do "goimports config.go" it will mess up this import by adding vendor prefix
    "github.com/openblockchain/obc-peer/vendor/github.com/op/go-logging"
I'll edit the line to say
    "github.com/op/go-logging"

This could be a workaround for now.

**Comment by binhn** [comment]
How I fixed my goimports problem:  I use Atom editor with go-plus, which enables goimports  (Preferences->Packages->go-plus->Settings  and look under Run Format Tool On Save). Change goimports to gofmt.
In your $GOPATH/src  delete everything but github.com, and in github.com, delete everything except openblockchain. 
Rebuild the proto files:
  protoc --go_out=plugins=grpc:. *.proto
Rebuild openchain:
  go build

**Comment by binhn** [comment]
@muralisrini Can we close this issue give the method mentioned above?

**Comment by muralisrini** [comment]
Agreed...closing
