### ISSUE TITLE
[CRYPTO CLEANUP] Rijndael/AES-256 GSM mode?

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#2111]
## Description

Taking a look at some of the crypto, I just noticed an AES256 **GSM** mode(?) set of functions implemented in a bespoke `aes` package on `master` in [core/crypto/primitives/aes/gcm.go](https://github.com/hyperledger/fabric/blob/3916a6269779c2cf01d0221dde90592802746496/core/crypto/primitives/aes/gcm.go)

I know AES in Galois Counter Mode (**GCM**), what's **GSM**? Do we need this?
## Proposed Solution

Unless I'm missing something (feedback welcome), how about we remove this?

**Comment by adecaro** [comment]
@JonathanLevi Good point, the name is just misspelled. The GCM mode is currently not used but it will be in the next version of transaction processing. I had introduced it in the past as a first step. A refactoring of the code would be sufficient then.

**Comment by JonathanLevi** [comment]
Hi @adecaro, thanks for renaming the GSM --> GCM so quickly/overnight!

Other than calling it GCM, **I am actually of the opinion that the right approach here was/is to remove this unused piece of code altogether**, at this stage.

I intended to submit the Pull Request (PR) for review myself, but we can wait for Monday, etc. no need to do this overnight/weekend. Waiting to agree/discuss this here first.

**Comment by JonathanLevi** [comment]
Have just discussed this with Angelo... we'll remove this temporarily and will re-visit this when this is re-introduced, probably in the next round of Confidentiality. 

@hyperledger/fabric-maintainers, can we please re-open this issue (and kindly assign to @adecaro)? Thanks.

**Comment by JonathanLevi** [comment]
Thank you @adecaro, @srderson (, @gabre, @tamasblummer, ...]
