### ISSUE TITLE
Member services fails under load with "database is locked" error

### ISSUE THREAD

**Issue by smithbk** [hyperledger-archives/fabric#2120]
## Description

The following error occurs when running load against memberservices
      ERROR: 2016/06/07 22:27:53 eca.go:252: database is locked

I'm not sure if this is it, but see http://stackoverflow.com/questions/32479071/sqlite3-error-database-is-locked-in-golang which was fixed by closing all rows.  Perhaps the same?
## Describe How to Reproduce

```
From inside vagrant:
   start membersrvc
   start peer
   cd fabric/sdk/node/bin
   node main.js test.json 
```

**Comment by andresgaragiola** [comment]
@srderson can you assign me this issue?
