### ISSUE TITLE
chaincode return error does not work

### ISSUE THREAD

**Issue by cophey** [hyperledger-archives/fabric#2122]
a chaincode has this code:

> func (t *ChaincodeUser) Invoke(stub *shim.ChaincodeStub, function string, args []string) ([]byte, error) {
> 
>   // 处理不同的方法
>   if function == "insert" {
>       return t.insert(stub, args)
>   } else if function == "delete" {
>       return t.delete(stub, args)
>   }
> 
>   return nil, errors.New("Received unknown function invocation")
> }

when i call this chaincode with an undefined function,it expected to be error,but it success.
request:

> {
>   "jsonrpc": "2.0",
>   "method": "invoke",
>   "params": {
>       "type": 1,
>       "chaincodeID":{
>           "name":"unionuser"
>       },
>       "ctorMsg": {
>          "function":"ssss",
>          "args":["1","2"]
>       },
>       "secureContext": "binhn"
>   },
>   "id": 3
> }

response:

> {
>     "jsonrpc":"2.0",
>     "result":{
>         "status":"OK",
>         "message":"5ffccb9b-ce68-4c81-88d9-5bd3aceca847"
>     },
>     "id":3
> }

I want to response a error message,how to do?

**Comment by cophey** [comment]
http://127.0.0.1:5000/chain/blocks/57
I call the block,the transactionResults has error,as this:

> {
>     "transactions":[
>         {
>             "type":2,
>             "chaincodeID":"Egl1bmlvbnVzZXI=",
>             "payload":"CiQIARILEgl1bmlvbnVzZXIaDAoEc3NzcxIBMRIBMioFYmluaG4=",
>             "uuid":"5ffccb9b-ce68-4c81-88d9-5bd3aceca847",
>             "timestamp":{
>                 "seconds":1467945779,
>                 "nanos":74715682
>             }
>         }
>     ],
>     "stateHash":"LBojiYkeyQxaNLglKwj9cR2m6DcxkhAsMSfuuEXFIMi0XD0dX2qATqh15+rB3wJqDR7AWPLi09P/nkA4LfY1xA==",
>     "previousBlockHash":"ilZUhviSFN7ePaPB1QugYSfE2A/FFAuuTZmZJzyHG+JUG8LFnDRH6Wx3IH/TdrZQFj9WBBZQHulfH5Uvipoztw==",
>     "nonHashData":{
>         "localLedgerCommitTimestamp":{
>             "seconds":1467945780,
>             "nanos":78175557
>         },
>         **"transactionResults":[
>             {
>                 "uuid":"5ffccb9b-ce68-4c81-88d9-5bd3aceca847",
>                 "errorCode":1,
>                 "error":"Transaction or query returned with failure: Received unknown function invocation"
>             }
>         ]**
>     }
> }

**Comment by cophey** [comment]
This is ProcessTransactionMsg Definition.I find that when tx.Type is invoke or deploy,the response is all success.Is that a bug?Or is it designed so?

```
// ProcessTransactionMsg processes a Message in context of a Transaction
func (eng *EngineImpl) ProcessTransactionMsg(msg *pb.Message, tx *pb.Transaction) (response *pb.Response) {
    //TODO: Do we always verify security, or can we supply a flag on the invoke ot this functions so to bypass check for locally generated transactions?
    if tx.Type == pb.Transaction_CHAINCODE_QUERY {
        if !engine.helper.valid {
            logger.Warning("Rejecting query because state is currently not valid")
            return &pb.Response{Status: pb.Response_FAILURE,
                Msg: []byte("Error: state may be inconsistent, cannot query")}
        }

        // The secHelper is set during creat ChaincodeSupport, so we don't need this step
        // cxt := context.WithValue(context.Background(), "security", secHelper)
        cxt := context.Background()
        //query will ignore events as these are not stored on ledger (and query can report
        //"event" data synchronously anyway)
        result, _, err := chaincode.Execute(cxt, chaincode.GetChain(chaincode.DefaultChain), tx)
        if err != nil {
            response = &pb.Response{Status: pb.Response_FAILURE,
                Msg: []byte(fmt.Sprintf("Error:%s", err))}
        } else {
            response = &pb.Response{Status: pb.Response_SUCCESS, Msg: result}
        }
    } else {
        // Chaincode Transaction
        response = &pb.Response{Status: pb.Response_SUCCESS, Msg: []byte(tx.Uuid)}

        //TODO: Do we need to verify security, or can we supply a flag on the invoke ot this functions
        // If we fail to marshal or verify the tx, don't send it to consensus plugin
        if response.Status == pb.Response_FAILURE {
            return response
        }

        // Pass the message to the consenter (eg. PBFT) NOTE: Make sure engine has been initialized
        if eng.consenter == nil {
            return &pb.Response{Status: pb.Response_FAILURE, Msg: []byte("Engine not initialized")}
        }
        // TODO, do we want to put these requests into a queue? This will block until
        // the consenter gets around to handling the message, but it also provides some
        // natural feedback to the REST API to determine how long it takes to queue messages
        err := eng.consenter.RecvMsg(msg, eng.peerEndpoint.ID)
        if err != nil {
            response = &pb.Response{Status: pb.Response_FAILURE, Msg: []byte(err.Error())}
        }
    }
    return response
}
```

**Comment by corecode** [comment]
it just means that submitting the transaction succeeded, not that the transaction was executed.  Transactions are executed asynchronously.

**Comment by cophey** [comment]
@corecode But I called invoke transaction,Whether to execute the right or wrong,it returned success.
It returned transaction-uuid,not transaction results.
How do I know the transaction invoke result?

**Comment by corecode** [comment]
you wait until the transaction with result appears on the blockchain

**Comment by cophey** [comment]
@corecode 
When i rest api invoke transaction,I can not know the transaction invoke success or not.
I must query transaction to see the invoke transaction execute right or wrong?

**Comment by kchristidis** [comment]
@cophey Yes.

**Comment by cophey** [comment]
@corecode @kchristidis thanks!
