### ISSUE TITLE
The Jenkins/Z Build is not succeeding

### ISSUE THREAD

**Issue by juliancarrivick-ibm** [hyperledger-archives/fabric#2136]
## Description

The Jenkins/Z build has not passed in 17 days at the time of writing. Looking at the logs it seems to be missing the `protoc` executable:
`01:54:32 [91mException in thread "main" java.io.IOException: Cannot run program "protoc": error=2, No such file or directory`

I was unsure if there was a better place to put this but thought it was important that it be tracked.
## Describe How to Reproduce

Reverify any open pull requests.

**Comment by rameshthoomu** [comment]
@juliancarrivick-ibm : Please refer issue #2035. @s390xlinux created PR #2083 to fix this issue. Review is in-progress.
