### ISSUE TITLE
REST API could not be invoked in Vagrant or host(mac)

### ISSUE THREAD

**Issue by mingjinc** [hyperledger-archives/fabric#2138]
## Description

I set up the fabric env according to the link https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md
The CLI command could run successfully.
But while I invoked the REST API such as http://127.17.0.2:5000/network/peers, it will occur the following error. 
curl -v http://127.17.0.2:5000/network/peers
- Hostname was NOT found in DNS cache
-   Trying 127.17.0.2...
- connect to 127.17.0.2 port 5000 failed: Connection refused
- Failed to connect to 127.17.0.2 port 5000: Connection refused
- Closing connection 0
  curl: (7) Failed to connect to 127.17.0.2 port 5000: Connection refused
  vagrant@hyperledger-devenv:v0.0.10-6db5a24:~$ 

Also, while I invoke the REST API in my host(mac), it will occur the error as below 
curl -v http://localhost:5000/network/peers
-   Trying ::1...
- connect to ::1 port 5000 failed: Connection refused
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 5000 (#0)
  > GET /network/peers HTTP/1.1
  > Host: localhost:5000
  > User-Agent: curl/7.43.0
  > Accept: _/_
  > 
- Empty reply from server
- Connection #0 to host localhost left intact
  curl: (52) Empty reply from server

Does anybody know how to help me out of it?

**Comment by bryan-huangyan** [comment]
looks like the ip address should be 172.17.0.2 not 127

**Comment by mingjinc** [comment]
@bryan-huangyan , Thanks. I could invoke REST API inside Vagrant now. But, still happen error in the host. Do you know how to resolve it?

curl -v http://localhost:5000/network/peers Error info as below. 
Trying ::1...
connect to ::1 port 5000 failed: Connection refused
Trying 127.0.0.1...
Connected to localhost (127.0.0.1) port 5000 (#0) > GET /network/peers HTTP/1.1 > Host: localhost:5000 > User-Agent: curl/7.43.0 > Accept: / >
Empty reply from server
Connection #0 to host localhost left intact curl: (52) Empty reply from server

**Comment by guidosantos** [comment]
Having the same problem here, any help?

**Comment by mingjinc** [comment]
@guidosantos , this issue could be resoved after you add -p 5000:5000 in the docker run command.

**Comment by guidosantos** [comment]
@mingjinc I was using docker-compose to start multiple peers, what was missing was the ports part in each peer, thanks though!

**Comment by christo4ferris** [comment]
looks like this can be closed... the docs don't reflect that address presently. Please reopen if you think this incorrect
