### ISSUE TITLE
docs for building dev env and setting up a network are very confusing

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#2144]
## Description

There are redundant descriptions of how to install, build and configure the development environment and/or a peer network for developing and testing chaincode or applications. As such, it is rather confusing to people as to where and how to start. It is unnecessary to actually install the vagrant development environment to develop and test the fabric. Hence, this should be made clearer to lower the barrier to entry for new people to the platform.
## Describe How to Reproduce

Just try to read and follow the docs

**Comment by joshhus** [comment]
Are we talking about all sections under the "Dev setup" heading in the TOC here: http://hyperledger-fabric.readthedocs.io/en/latest/
