### ISSUE TITLE
CertificateSpec doesn't include Organization and Country ... why not?

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger-archives/fabric#2168]
## Description

in https://github.com/hyperledger/fabric/blob/master/membersrvc/ca/ca.go#L55
CertificateSpec doesn't include Organization and Country ... why not? There are accessor functions for these values that return the value from viper, which is inefficient to say the least.
https://github.com/hyperledger/fabric/blob/master/membersrvc/ca/ca.go#L164
https://github.com/hyperledger/fabric/blob/master/membersrvc/ca/ca.go#L170

Think that these values should be cached on initialization. Will yield a significant performance gain in creating certificates if we aren't reading the config twice for each certificate we create.
## Describe How to Reproduce

read the code

**Comment by genggjh** [comment]
I can cover this, pls assign to me.
