### ISSUE TITLE
Byzantine flag for PBFT testnet

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#217]
We'll need this for testing and hardening.

Use Jason's (upcoming) work on #171 ([see details](https://github.com/openblockchain/obc-peer/issues/171#issuecomment-155238175)) to set a validating peer as byzantine.

Tasks:
1. Define byzantine behaviors that this byzantine peer may exhibit.
2. Update the `pbft` and `consensus` packages accordingly.
3. Write unit tests to confirm that our implementation is fault tolerant.

Example byzantine behaviors:
1. Send the wrong global hash in `ExecTXs()`, or errors for requests that run just fine.
2. If you are the leader, assign an incorrect sequence number.
3. If you are the leader, send different batches to the validating peers of the network.

**Comment by kchristidis** [comment]
Feel free to break down this task into smaller tasks if necessary.

**Comment by vukolic** [comment]
In this context, it would be good to be able to manually specify values of some data structures (in particular P and Q sets before view change) and let the execution/test run from there. I discussed this with @corecode, not sure what is the status on this one.

**Comment by corecode** [comment]
Oh, I assumed this issue was about testnet, which is entirely different from the tests we run in our mocknet.

**Comment by kchristidis** [comment]
This is indeed about the testnet.

Let's try to implement @vukolic's idea on the mocknet.

**Comment by tuand27613** [comment]
Potential tests for byzantine behavior
1. Loss of _**f**_ replicas: system continues to function
2. Loss of _**f+1**_ replicas: no completed transactions after loss
3. _**f**_ backup replicas turn byzantine: broadcast randomly does not send to a random replica: system continues to function
4. Loss of primary: view change and system continues to function
5. Primary randomly does not send a message to random backup replica: system continues to function

**Comment by tuand27613** [comment]
have added behave tests for cases 1-3 above. PR #740

**Comment by binhn** [comment]
it seems safe to close
