### ISSUE TITLE
HLC sdk file stats.ts. The ResponseTime class prohibit concurrent request from a user.  

### ISSUE THREAD

**Issue by zhoyy007** [hyperledger-archives/fabric#2174]
## Description

I am trying to query the ledger from a user concurrently. The error occurs as following:
      throw Error("started twice without stopping");
Look at the stats.ts file. We find the definition of ResponseTime. It is clear that ResponseTime would expect the query to get response before starting the next one. So, concurrent execution is prohibited. 
/**
- Class to keep track of an average response time.
  */
  export class ResponseTime {
  
  private avg: Average = new Average();
  private startTime: number;
  
  constructor() {
  }
  
  start(): void {
      if (this.startTime != null) {
          throw Error ("started twice without stopping");
      }
      this.startTime = getCurTimeInMs();
  }
  
  stop(): void {
      if (this.startTime == null) {
          throw Error ("stopped without starting");
      }
      let elapsed = getCurTimeInMs() - this.startTime;
      this.startTime = null;
      this.avg.addSample(elapsed);
  }
  
  cancel(): void {
      if (this.startTime == null) {
          throw Error ("cancel without starting");
      }
      this.startTime = null;
  }
  
  // Get the average response time
  getValue(): number {
      return this.avg.getValue();
  }
  }
  ## Describe How to Reproduce
  
  
  
  After starting membersrvc and 4 peer in net mode, I did the following test to test the concurrency based on the Nodejs event-driven asynchronous programming.
  
  var queryTxarr = new Array(1001);
      for(i =0; i<500;i++){
          reqarr[i]={
              // Name (hash) required for query
              chaincodeID: testChaincodeID,
              //chaincodeID: "jflsdjf",
              // Function to trigger
              fcn: "query",
              // Existing state variable to retrieve
              args: ["a"]
          };
      }
  var concurrentexec = function(){
      for(i =0; i<300;i++){
          queryTxarr[i] = test_user_Member1.query(reqarr[i]);
          wait(10);
          // Print the query results
          queryTxarr[i].on('complete', function (results) {
              // Query completed successfully
              //t.pass(util.format("Successfully number: %d",id));
              id=id+1;
              t.pass(util.format("Successfully number: %d ;queried existing chaincode state: value=%s", id, results.result.toString()));
          });
          queryTxarr[i].on('error', function (err) {
              // Query failed
              t.fail(util.format("Failed to query existing chaincode state: request=%j, error=%j", queryRequest1, err));
          });
      }
  };
  concurrentexec();

**Comment by ghaskins** [comment]
@bren3582 and I have seen this issue too.  We have a client that by default will allow 10 concurrent requests to be outstanding at a time and this issue has suddenly popped up.  I'll defer to @bren3582 but I believe it does go away if we artificially restrict the parallelism to 1

**Comment by ghaskins** [comment]
BTW: we are using HLC v0.0.12 from NPM.

**Comment by srderson** [comment]
The new version if HFC. https://www.npmjs.com/package/hfc
I'm not sure which one is compatible with the 0.5 branch.

**Comment by ghaskins** [comment]
@srderson yeah, I haven't had a chance to migrate to the renamed client, but I can give that a whirl and see if its improved.

**Comment by angrbrd** [comment]
Hi @zhoyy007 @ghaskins

Just wondering if this is still an issue for you? If so, could you please open a Bug in Jira and tag with "node-SDK", then close this one out?

Thanks!
