### ISSUE TITLE
HLC sdk. The member class doesn't support issue transaction on specified peer. 

### ISSUE THREAD

**Issue by zhoyy007** [hyperledger-archives/fabric#2176]
## Description

Currently, the hlc sdk member class has a the deploy/invoke/query method which would try all peers to see which one can succeed on the transaction. It doesn't provide interface/method to appoint one peer. While, testing on specific peer would be needed in some cases. For example, we want to test on sending query on all peers concurrently. 
## Describe How to Reproduce

N/S

**Comment by bmos299** [comment]
@zhoyy007 agreed. I am chatting with @rennman and we just had the same thought.  For testing, we need more granular controls.  Also, some customers may also want more granular control on prioritizing peers used to access the fabric.

**Comment by smithbk** [comment]
The hfc APIs allow you to specify multiple peers, but it only sends to the 2nd if it fails to connect to the 1st, to the 3rd if it fails to connect to the 1st and 2nd, etc.  If you want to change the order, then you can simply create a newChain and add the peers in a different order.

Regarding sending transactions concurrently to different peers, I don't understand the desire to do this.  If you want to do this, then you can create multiple chain instances with the peers added in different orders.

**Comment by zhoyy007** [comment]
@smithbk Good idea. Your solutions can satisfy the needs. Concurrently invoking multiple peers is useful to simulate and estimate the performance with distributed users' usages. I think this is needed for testing.

**Comment by angrbrd** [comment]
I have created a matching feature entry in Jira here: https://jira.hyperledger.org/browse/FAB-121

@christo4ferris please close out this issue. Thanks!
