### ISSUE TITLE
Unhelpful messages from Docker when chaincode building fails

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#2195]
## Description

If a chaincode you are trying to deploy has a bug, you will get messages like

```
The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/a995a211c45d5fb0070ae23fa64993a15728bb5f30e11b08a70da93a97b745a736068edbc5908f16567073d513d5e9a5ec721e54cf6dd79c245b7fdacf53ffae' returned a non-zero code: 2
```

This is always frustrating to me, since you have to guess what happened. 

Is there any way to recover the stdout/stderr from the failed command of Docker build and inject it into the logs? 

Or maybe the solution is to modify the chaincode Dockerfile to be a little less "efficient" and call out these steps separately so at least you will know which of the &&-connected commands failed.
## Describe How to Reproduce

But a compile error in a chaincode and try to deploy it.

**Comment by ghaskins** [comment]
I have made that same hack to split them out numerous times for this very reason, but never organized it well enough to PR it.  I agree this needs to be improved, though.
