### ISSUE TITLE
Can Fabric integrate Sawtooth Lake's consensus?

### ISSUE THREAD

**Issue by gaoweibin** [hyperledger-archives/fabric#2206]
## Description

I want to call Sawtooth Lake's consensus in Fabric, any ideas?

I also would like to know more about collaboration between Fabric and Sawtooth Lake.

**Comment by srderson** [comment]
They do not integrate today. One of the goals of the next architecture at https://github.com/hyperledger/fabric/wiki/Next-Consensus-Architecture-Proposal is to be able to support additional consensus algorithms such as PoET.

I would hope in the future that the projects evolve towards a common protocol.
