### ISSUE TITLE
Occur error while deploy example02 chaincode with security + 4 peers + BFTP

### ISSUE THREAD

**Issue by mingjinc** [hyperledger-archives/fabric#2221]
## Description

I started 4 peers(test_vp0,test_vp1,test_vp2,test_vp3) and one CA. While I deployed example02 chaincode, it will occur the following warn message in the peer log, and occur error while execute query. 

1) Peer Log: 09:37:56.790 [consensus/pbft] recvViewChange -> WARN 1689 Replica 0 found incorrect signature in view-change message: Could not verify message from vp0 (unknown peer)

2) Query Error: Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Could not get deployment transaction for a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb - LedgerError - ResourceNotFound: ledger: resource not found)"

This error does not happen if I disable security. 

How to resolve it?
## Describe How to Reproduce

1) membersrvc
2) docker run --rm -it -p 5000:5000 -p 30303:30303 -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=test_vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=test_vp0 -e CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT hyperledger/fabric-peer peer node start 
3) Start other 3 peers one by one
4) Login, CORE_PEER_ADDRESS=172.17.0.2:30303 peer network login test_user0
5) Deploy CORE_PEER_ADDRESS=172.17.0.2:30303 CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true peer chaincode deploy -u test_user0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
6) Query, then will happen the following error in console
Error: Error querying chaincode: rpc error: code = 2 desc = "Error:Failed to launch chaincode spec(Could not get deployment transaction for a5389f7dfb9efae379900a41db1503fea2199fe400272b61ac5fe7bd0c6b97cf10ce3aa8dd00cd7626ce02f18accc7e5f2059dae6eb0786838042958352b89fb - LedgerError - ResourceNotFound: ledger: resource not found)"

**Comment by iiiLiQuiDiii** [comment]
CORE_PEER_ID must be vpN where N starts from 0 
https://github.com/hyperledger/fabric/blob/master/docs/Setup/Network-setup.md#using-a-consensus-plugin

**Comment by mingjinc** [comment]
@iiiLiQuiDiii , already fixed using vp0 -> vp4. Thanks.
