### ISSUE TITLE
Clarify attribute passing in CLI and REST APIs

### ISSUE THREAD

**Issue by iiiLiQuiDiii** [hyperledger-archives/fabric#2236]
## Description

The documentation does not specify how to pass attributes to chaincode invocations and queries

Rest Example

{
  "jsonrpc": "2.0",
  "method": "query",
  "params": {
      "type": 1,
      "chaincodeID":{
          "name":"db6b2ab34eaf272a08a3a2c4fba0efd448e0f12139309bba8d541123327242375c8f8b13467284082fcbb856fd54a9102ccd092470aaf3d125b5b5a82960a75f"
      },
      "ctorMsg": {
         "function":"read",
         "args":[""]

```
  },
  "attributes": ["position"]
  "secureContext": "diego"
```

  },
  "id": 5
}

CLI Example:
 peer chaincode invoke -u diego -p github.com/hyperledger/fabric/examples/chaincode/go/authorizable_counter/  -c '{"Function":"increment", "Args": []}' -a '["position"]'

**Comment by andresgaragiola** [comment]
@srderson  please assign me this issue. @iiiLiQuiDiii what document are you seeing?

**Comment by iiiLiQuiDiii** [comment]
An example like "authorizable_counter" could be useful at https://github.com/hyperledger/fabric/blob/master/docs/API/CoreAPI.md
