### ISSUE TITLE
How can I add a new user without using  the membersrvc.yaml 

### ISSUE THREAD

**Issue by CocoaWang** [hyperledger-archives/fabric#2249]
## Description

I know I can use ca-setup method provided in ca-setup file to get a number of preloaded  users where each user's name roles password are specified already.But how can I add a new user?

**Comment by CocoaWang** [comment]
If I want to use a user role like validating peer,I must add it into the membersrvc.yaml file ?

**Comment by smithbk** [comment]
A user with registrar authority can dynamically register other users of the allowable type(s).   See fabric/sdk/node/test/unit/registrar.js for an example of doing this using the node SDK.
