### ISSUE TITLE
How to enable tls for rest api in fabric ?

### ISSUE THREAD

**Issue by kamraanki** [hyperledger-archives/fabric#2270]

**Comment by dshuffma-ibm** [comment]
looks like you should set [core.yaml](https://github.com/hyperledger/fabric/blob/master/peer/core.yaml#L158) line 158 to true. this will use tls for peer to peer comm AND ultimately use tls for the peer's rest API. 

![image](https://cloud.githubusercontent.com/assets/16085295/17061853/7739fcd0-4ffe-11e6-9c76-0182de420712.png)
you should also provide the certs listed nearby

the setting gets consumed here in `rest_api.go`: https://github.com/hyperledger/fabric/blob/master/core/rest/rest_api.go#L1767

**Comment by kamraanki** [comment]
@dshuffma-ibm  Thanks !!! But i have already done this but still peers not accepting TLS enabled request.

**Comment by GrapeBaBa** [comment]
https://github.com/hyperledger/fabric/blob/master/bddtests/docker-compose-2-tls-basic.yml, this is an example

**Comment by christo4ferris** [comment]
@kamraanki would you please provide us with the error messages and relevant execution context to enable us to reproduce? Thanks

**Comment by kamraanki** [comment]
@christo4ferris  Please check issue #2320

**Comment by christo4ferris** [comment]
so do we need both issues? can we close one?

**Comment by kamraanki** [comment]
@christo4ferris  Yes we can close this one.
