### ISSUE TITLE
Cann't use hfc to deploy chaincode

### ISSUE THREAD

**Issue by huhaiqing** [hyperledger-archives/fabric#2285]
Hi,

When I use the unit test code under github.com/hyperledger/fabric/sdk/node/test/unit to test, I find that hfc can't deploy the chaincode, but hfc can query from the existed chaincode.

After hfc send deploy request, hyperledger returans OK to client side, but use the 'docker ps -a ' command to see, the deployed chaincode can't start up successfully.

And when do invoke operation on the not start up chain code, it returns OK to client side.

HFC do query and invoke operation on an existed chaincode is OK.

Could you help to tell us how to fix the hfc can't deploy chaincode?

Thanks in advance.

Regards
Harry

**Comment by christo4ferris** [comment]
Can you please share more about your environment? What platform? Did you use the [fabric developer setup](http://hyperledger-fabric.readthedocs.io/en/latest/dev-setup/devenv/) to create your environment? What is the most recent commit sha?

**Comment by smithbk** [comment]
@huhaiqing Any update on this one?  Is it still an issue?  If so, please provide details on how to reproduce.  Thanks

**Comment by angrbrd** [comment]
Hi @huhaiqing 

It seems to me, that you're having trouble deploying a chaincode to the network. Am I correct? Is this still an issue? To get the basic test case working, please follow the instructions here:

http://hyperledger-fabric.readthedocs.io/en/latest/Setup/NodeSDK-setup/

Specifically, you need the section titled "Getting Set Up". Get the member services node and peer node up and running and then deploy the chaincode_example02 with the [chain-tests.js](https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/chain-tests.js) test file. Let me know if this helps you progress.

Thanks.

**Comment by christo4ferris** [comment]
@huhaiqing we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, if you think this issue should be re-opened, please open an issue there. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks
