### ISSUE TITLE
Identify Transaction Invoker

### ISSUE THREAD

**Issue by heshansp** [hyperledger-archives/fabric#2299]
## Description

Hi All,
I have been using the `stub.GetCallerCertificate()` method to retrieve the invoker's certificate and parsing it using `x509.ParseCertificate()` to determine the Invoker mentioned under `Subject.CommonName`. Recently I upgraded to the latest fabric version and I am unable to use this method to get the invoker name as the certificate does not carry the Invoker's name under the said parameter anymore. 

I have no preference to one way on another but I would like to know if there is a suitable alternative for identifying the invoker within the chaincode.

Any help is greatly appreciated.
## Describe How to Reproduce

As mentioned above.

**Comment by andresgaragiola** [comment]
Hi @heshansp,

This is correct. The EnrollmentID was removed from the TCert’s Subject.CommonName in order to avoid link-ability and to preserve anonymity where it is applicable (see also #1409).

The right approach is to encrypt the EnrollmentID and provide it through the X.509 extension (that is, as an attribute). This is a requested feature that we are working to support in the near future.

In the meantime, we would rather not have the identity in the clear in each TCert.

**Comment by heshansp** [comment]
Hi @andresgaragiola ,
Thank you for the clarification. So if I'm understanding you correctly, currently there is no way I can retrieve the EnrollmentID of the transaction invoker within the chaincode (assuming the X.509 extention is not built yet)? 

In my project I have to ensure the user has access the a certain affiliation prior to allowing access to a transaction in the blockchain. Without identifying the invoker I am not sure how I can achieve this.

Appreciate if you can shed some light on this.

**Comment by iiiLiQuiDiii** [comment]
I use an attribute associated to that EnrollmentID, it's value holds the EnrollmentID. Is this advisable in  real scenarios?

**Comment by heshansp** [comment]
Hi @iiiLiQuiDiii ,
That's an interesting solution. So within the chaincode do you use something like
`attrValue,error:=stub.ReadCertAttribute("EnrollmentID")`?

**Comment by andresgaragiola** [comment]
Yes that is a solution. You can found a similar approach in the example "asset_management_with_roles", in this case we are using an attribute "account".

**Comment by iiiLiQuiDiii** [comment]
@heshansp I guess that would do.  In my chaincode I enforce that a certain EnrollmentID can extract from a table only tuples which contain that EnrollmentID. 
`isMatchingSender, _      := stub.VerifyAttribute("id", []byte(r.Columns[Sender].GetString_()))`

**Comment by heshansp** [comment]
Thanks guys,
I will try this out and see.

**Comment by heshansp** [comment]
Hi @iiiLiQuiDiii , @andresgaragiola 
Guys still this issue is not resolved for me. For some reason it seems that `stub.GetCallerCertificate()` does not return the attributes along with the caller certificate hence `attr.GetValueFrom()` or  `stub.ReadCertAttribute()` fails to fetch the attribute I require.

To verify this I printed the certificate returned by `stub.GetCallerCertificate()` method and I got this.

> &{Raw:[48 130 2 81 48 130 1 248 160 3 2 1 2 2 17 0 187 55 123 35 90 55 74 194 177 157 111 179 166 158 37 166 48 10 6 8 42 134 72 206 61 4 3 3 48 49 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 12 48 10 6 3 85 4 3 19 3 116 99 97 48 30 23 13 49 54 48 55 50 57 49 48 49 52 49 54 90 23 13 49 54 49 48 50 55 49 48 49 52 49 54 90 48 69 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 32 48 30 6 3 85 4 3 19 23 84 114 97 110 115 97 99 116 105 111 110 32 67 101 114 116 105 102 105 99 97 116 101 48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4 239 10 231 172 225 3 93 251 229 17 122 16 205 77 34 245 192 115 60 250 146 253 198 239 39 202 192 45 71 26 37 141 167 209 58 173 200 211 33 62 43 210 184 65 85 130 148 188 80 12 87 122 3 58 97 15 191 222 0 48 104 43 125 240 163 129 220 48 129 217 48 14 6 3 85 29 15 1 1 255 4 4 3 2 7 128 48 12 6 3 85 29 19 1 1 255 4 2 48 0 48 13 6 3 85 29 14 4 6 4 4 1 2 3 4 48 15 6 3 85 29 35 4 8 48 6 128 4 1 2 3 4 48 77 6 6 42 3 4 5 6 7 1 1 255 4 64 120 71 18 56 21 9 85 232 134 10 128 18 160 247 92 211 62 249 21 196 195 214 39 242 255 104 86 121 45 161 93 117 120 189 70 40 62 146 185 75 23 80 160 168 58 68 225 242 69 104 218 159 21 235 76 193 63 159 129 6 192 143 96 140 48 74 6 6 42 3 4 5 6 8 4 64 61 222 76 0 179 151 34 44 9 57 76 5 24 206 127 60 59 49 81 221 56 215 96 151 140 110 9 129 121 29 232 122 225 229 26 85 134 197 114 203 13 205 80 244 207 32 216 151 9 201 241 80 53 6 83 215 23 193 254 117 43 9 131 170 48 10 6 8 42 134 72 206 61 4 3 3 3 71 0 48 68 2 32 91 59 66 165 176 45 124 165 222 96 66 51 200 122 167 10 37 185 39 23 78 12 57 190 184 128 222 198 229 42 132 86 2 32 72 89 20 202 71 31 102 75 169 85 44 34 40 100 235 55 141 57 165 78 100 48 73 9 183 223 13 140 50 199 120 31] RawTBSCertificate:[48 130 1 248 160 3 2 1 2 2 17 0 187 55 123 35 90 55 74 194 177 157 111 179 166 158 37 166 48 10 6 8 42 134 72 206 61 4 3 3 48 49 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 12 48 10 6 3 85 4 3 19 3 116 99 97 48 30 23 13 49 54 48 55 50 57 49 48 49 52 49 54 90 23 13 49 54 49 48 50 55 49 48 49 52 49 54 90 48 69 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 32 48 30 6 3 85 4 3 19 23 84 114 97 110 115 97 99 116 105 111 110 32 67 101 114 116 105 102 105 99 97 116 101 48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4 239 10 231 172 225 3 93 251 229 17 122 16 205 77 34 245 192 115 60 250 146 253 198 239 39 202 192 45 71 26 37 141 167 209 58 173 200 211 33 62 43 210 184 65 85 130 148 188 80 12 87 122 3 58 97 15 191 222 0 48 104 43 125 240 163 129 220 48 129 217 48 14 6 3 85 29 15 1 1 255 4 4 3 2 7 128 48 12 6 3 85 29 19 1 1 255 4 2 48 0 48 13 6 3 85 29 14 4 6 4 4 1 2 3 4 48 15 6 3 85 29 35 4 8 48 6 128 4 1 2 3 4 48 77 6 6 42 3 4 5 6 7 1 1 255 4 64 120 71 18 56 21 9 85 232 134 10 128 18 160 247 92 211 62 249 21 196 195 214 39 242 255 104 86 121 45 161 93 117 120 189 70 40 62 146 185 75 23 80 160 168 58 68 225 242 69 104 218 159 21 235 76 193 63 159 129 6 192 143 96 140 48 74 6 6 42 3 4 5 6 8 4 64 61 222 76 0 179 151 34 44 9 57 76 5 24 206 127 60 59 49 81 221 56 215 96 151 140 110 9 129 121 29 232 122 225 229 26 85 134 197 114 203 13 205 80 244 207 32 216 151 9 201 241 80 53 6 83 215 23 193 254 117 43 9 131 170] RawSubjectPublicKeyInfo:[48 89 48 19 6 7 42 134 72 206 61 2 1 6 8 42 134 72 206 61 3 1 7 3 66 0 4 239 10 231 172 225 3 93 251 229 17 122 16 205 77 34 245 192 115 60 250 146 253 198 239 39 202 192 45 71 26 37 141 167 209 58 173 200 211 33 62 43 210 184 65 85 130 148 188 80 12 87 122 3 58 97 15 191 222 0 48 104 43 125 240] RawSubject:[48 69 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 32 48 30 6 3 85 4 3 19 23 84 114 97 110 115 97 99 116 105 111 110 32 67 101 114 116 105 102 105 99 97 116 101] RawIssuer:[48 49 49 11 48 9 6 3 85 4 6 19 2 85 83 49 20 48 18 6 3 85 4 10 19 11 72 121 112 101 114 108 101 100 103 101 114 49 12 48 10 6 3 85 4 3 19 3 116 99 97] Signature:[48 68 2 32 91 59 66 165 176 45 124 165 222 96 66 51 200 122 167 10 37 185 39 23 78 12 57 190 184 128 222 198 229 42 132 86 2 32 72 89 20 202 71 31 102 75 169 85 44 34 40 100 235 55 141 57 165 78 100 48 73 9 183 223 13 140 50 199 120 31] SignatureAlgorithm:ECDSA-SHA384 PublicKeyAlgorithm:3 PublicKey:0xc820511f00 Version:3 SerialNumber:+248853709076286115757881510833157973414 Issuer:{Country:[US] Organization:[Hyperledger] OrganizationalUnit:[] Locality:[] Province:[] StreetAddress:[] PostalCode:[] SerialNumber: CommonName:tca Names:[{Type:2.5.4.6 Value:US} {Type:2.5.4.10 Value:Hyperledger} {Type:2.5.4.3 Value:tca}] ExtraNames:[]} Subject:{Country:[US] Organization:[Hyperledger] OrganizationalUnit:[] Locality:[] Province:[] StreetAddress:[] PostalCode:[] SerialNumber: CommonName:Transaction Certificate Names:[{Type:2.5.4.6 Value:US} {Type:2.5.4.10 Value:Hyperledger} {Type:2.5.4.3 Value:Transaction Certificate}] ExtraNames:[]} NotBefore:2016-07-29 10:14:16 +0000 UTC NotAfter:2016-10-27 10:14:16 +0000 UTC KeyUsage:1 Extensions:[{Id:2.5.29.15 Critical:true Value:[3 2 7 128]} {Id:2.5.29.19 Critical:true Value:[48 0]} {Id:2.5.29.14 Critical:false Value:[4 4 1 2 3 4]} {Id:2.5.29.35 Critical:false Value:[48 6 128 4 1 2 3 4]} {Id:1.2.3.4.5.6.7 Critical:true Value:[120 71 18 56 21 9 85 232 134 10 128 18 160 247 92 211 62 249 21 196 195 214 39 242 255 104 86 121 45 161 93 117 120 189 70 40 62 146 185 75 23 80 160 168 58 68 225 242 69 104 218 159 21 235 76 193 63 159 129 6 192 143 96 140]} {Id:1.2.3.4.5.6.8 Critical:false Value:[61 222 76 0 179 151 34 44 9 57 76 5 24 206 127 60 59 49 81 221 56 215 96 151 140 110 9 129 121 29 232 122 225 229 26 85 134 197 114 203 13 205 80 244 207 32 216 151 9 201 241 80 53 6 83 215 23 193 254 117 43 9 131 170]}] ExtraExtensions:[] UnhandledCriticalExtensions:[1.2.3.4.5.6.7] ExtKeyUsage:[] UnknownExtKeyUsage:[] BasicConstraintsValid:true IsCA:false MaxPathLen:-1 MaxPathLenZero:false SubjectKeyId:[1 2 3 4] AuthorityKeyId:[1 2 3 4] OCSPServer:[] IssuingCertificateURL:[] DNSNames:[] EmailAddresses:[] IPAddresses:[] PermittedDNSDomainsCritical:false PermittedDNSDomains:[] CRLDistributionPoints:[] PolicyIdentifiers:[]}

As you can see this does not contain any attributes.

**Comment by smithbk** [comment]
When you get a batch of tcerts from the TCA, you must request attributes by name to be in the tcerts.  Are you doing this?

If you are using the node client SDK, which is the recommended way to do this, see fabric/sdk/node/test/unit/asset-mgmt-with-roles.js as an example.  See the assignOwner function below.  It is requesting the 'role' attribute in tcerts.

function assignOwner(user,owner,cb) {
    var req = {
        chaincodeID: chaincodeID,
        fcn: "assign",
        args: ["MyAsset",owner],
        **attrs: ['role']**
    };
    console.log("assign: invoking %j",req);
    var tx = user.invoke(req);
    tx.on('submitted', function (results) {
        console.log("assign transaction ID: %j", results);
    });
    tx.on('complete', function (results) {
        console.log("assign invoke complete: %j", results);
        return cb();
    });
    tx.on('error', function (err) {
        console.log("assign invoke error: %j", err);
        return cb(err);
    });
}

**Comment by iiiLiQuiDiii** [comment]
There's also new documentation available about the CLI and REST interfaces
https://github.com/hyperledger/fabric/blob/master/docs/API/AttributesUsage.md

**Comment by heshansp** [comment]
Guys,
It worked like a charm. Thanks a lot for the help !!

Cheers!
