### ISSUE TITLE
.YAML vs .YML

### ISSUE THREAD

**Issue by brad-gorman** [hyperledger-archives/fabric#2304]
## Description

The file naming is inconsistent between YAML files. Some files have a .yaml extension, others use .yml. If there is a good reason for this, please close the issue, otherwise I feel that one set should be renamed purely for consistency.
## Describe How to Reproduce

vagrant@ubuntu-1404:/hyperledger$ find . -name *.yaml
./consensus/noops/config.yaml
./consensus/pbft/config.yaml
./core/chaincode/chaincodetest.yaml
./core/crypto/crypto_test.yaml
./core/ledger/benchmark_scripts/ledger/test.yaml
./core/ledger/genesis/genesis_test.yaml
./core/ledger/statemgmt/buckettree/test.yaml
./core/ledger/statemgmt/state/test.yaml
./core/ledger/statemgmt/trie/test.yaml
./core/ledger/test/test.yaml
./core/ledger/test.yaml
./core/rest/rest_test.yaml
./examples/chaincode/chaintool/example02/chaincode.yaml
./examples/chaincode/go/asset_management02/asset.yaml
./examples/chaincode/go/asset_management_with_roles/asset.yaml
./membersrvc/ca/ca_test.yaml
./membersrvc/membersrvc.yaml
./peer/core.yaml

vagrant@ubuntu-1404:/hyperledger$ find . -name *.yml
./.travis.yml
./bddtests/compose-defaults.yml
./bddtests/docker-compose-1-exp.yml
./bddtests/docker-compose-1-profiling.yml
./bddtests/docker-compose-1.yml
./bddtests/docker-compose-2-tls-basic.yml
./bddtests/docker-compose-2.yml
./bddtests/docker-compose-3.yml
./bddtests/docker-compose-4-consensus-base.yml
./bddtests/docker-compose-4-consensus-batch-1-byzantine.yml
./bddtests/docker-compose-4-consensus-batch.yml
./bddtests/docker-compose-4-consensus-noops.yml
./bddtests/docker-compose-4-consensus-nvp0.yml
./bddtests/docker-compose-4-consensus-vp3-byzantine.yml
./bddtests/docker-compose-4.yml
./bddtests/docker-compose-5.yml
./bddtests/docker-compose-sdk-node.yml
./bddtests/docker-membersrvc-attributes-enabled.yml
./bddtests/docker-membersrvc-attributes-encryption-enabled.yml
./mkdocs.yml
./vendor/github.com/looplab/fsm/wercker.yml

**Comment by christo4ferris** [comment]
Docker Compose expects .yml for default. You can specify file directly, just more typing. Travis expects .yml and you cannot change that. suggest leaving things as they are. Thanks
