### ISSUE TITLE
Running Hyperledger at scale

### ISSUE THREAD

**Issue by stylixboom** [hyperledger-archives/fabric#2316]
I'm trying to run Hyperledger/Fabric with Docker swarm.
## Description

Generally, Hyperledger use an internal /var/hyperledger/ to store the database within each container. And we actually need to mount this directory outside of the container. This mount parameter can be predefined in the core.yaml, dockercompose, and docker run -v x:y. Also, this directory must not be shared between other Hyperledger containers.
## Question

I'm not sure if Docker swarm mode provides us the individual mount parameter for each container. Is there any other way to handle this database path dynamically with docker swarm?

E.g. by using this command
`$ docker service create ...`
## Idea

Should we have some prefix/postfix/identical database name, generated internally to handle this situation?

Around this file:
`core/db/db.go --> getDBPath()`

Note:
I also posted this question to
http://stackoverflow.com/questions/38580344/how-to-assign-separated-volumes-to-each-container-docker-swarm-hyperledger
just in the case the Docker guy have some work around on this.

**Comment by corecode** [comment]
I don't think we should write our code specifically for docker swarm.  How do other docker swarm deployments implement out-of-container persistent storage?  Why do you say that storage needs to happen outside the container?

**Comment by stylixboom** [comment]
Well, it's about my docker configuration problem. I found when the containers grown up with in-container storage, the overall transaction performance drop significantly. This is due to the storage is just a loop-device. That's why I try to mount the database to outside the container.

Right now, the storage is overlay, so the problem seems to be solved, and in-container persistent storage seems to be fine, this time.

Note:
Sorry for late, I try to confirm if both in and out storage effect the performance. The result is, NO, with overlayfs.

**Comment by christo4ferris** [comment]
@stylixboom seems like you've resolved your issue. Closing this one. Note though that we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, if you think this issue should be re-opened, please open an issue there. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks
