### ISSUE TITLE
Could you public a sample of docker-compose.yml?

### ISSUE THREAD

**Issue by zhuang-weiming** [hyperledger-archives/fabric#2318]
Could you public a sample of docker-compose.yml?

I read some about docker-compose.yml, but seems no sample document about it.
Like 
[https://github.com/hyperledger/fabric/blob/f7d932108d1e339d3371b6e8e922d09ecf913e9a/docs/Setup/Network-setup.md](https://github.com/hyperledger/fabric/blob/f7d932108d1e339d3371b6e8e922d09ecf913e9a/docs/Setup/Network-setup.md)

[https://github.com/hyperledger/fabric/blob/89d570470573c6cfb2faebe7b38832256de2e8c3/pub/fabric-peer.md](https://github.com/hyperledger/fabric/blob/89d570470573c6cfb2faebe7b38832256de2e8c3/pub/fabric-peer.md)

[https://github.com/hyperledger/fabric/blob/dab545d0ae91389e92561945992fe14bdcdcd13a/docs/Setup/Chaincode-setup.md](https://github.com/hyperledger/fabric/blob/dab545d0ae91389e92561945992fe14bdcdcd13a/docs/Setup/Chaincode-setup.md)

They wrote a lot about "docker-compose.yml file"........

**Comment by iiiLiQuiDiii** [comment]
Look in fabric/bddtests .

**Comment by christo4ferris** [comment]
As @iiiLiQuiDiii said https://github.com/hyperledger/fabric/tree/v0.5-developer-preview/bddtests and also in the [documentation](http://hyperledger-fabric.readthedocs.io/en/latest/Setup/Network-setup/) for setting up a network. There are an abundance of examples.
