### ISSUE TITLE
Update The README.md to better describe where the hyperledger fabric documentation is located

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#2324]
The README.md file in hyyperledger/fabric is not making it simple for the reader to find our formatted documentation using readthedocs.  The only to get to the site is to click the docs tab.   I suggest adding some documentation similar to what is  below:

Documentation & guides live here: http://hyperledger-fabric.readthedocs.io/en/latest.  For a quick start guide of the fabric see the section http://hyperledger-fabric.readthedocs.io/en/latest/#getting-started.

**Comment by joshhus** [comment]
I second the motion ... (thanks @bmos299!)

**Comment by bmos299** [comment]
Later in the page there is a link to the page, but I really like it right up front as well.   The work you guys and @rameshthoomu did is great and we need to steer people to use it.

**Comment by christo4ferris** [comment]
closing as we will be making this more prominent but in a different manner. Thanks
