### ISSUE TITLE
Error building images: Tag latest not found in repository docker.io/hyperledger/fabric-baseimage

### ISSUE THREAD

**Issue by ghost** [hyperledger-archives/fabric#2325]
## Description

I want to deploy a chaincode to a network.

1) Create a docker compose file to set up a network with one member service and 4 peers:
membersrvc:
  image: hyperledger/fabric-membersrvc
  ports:
    - "50051:50051"
  command: membersrvc

vp:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  command: sh -c "sleep 5; peer node start"

vp0:
  extends:
    service: vp
  ports:
      - "5000:5000"
      - "30303:30303"
      - "30304:30304"
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc

vp1:
  extends:
    service: vp
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
  links:
    - membersrvc
    - vp0

vp2:
  extends:
    service: vp
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
  links:
    - membersrvc
    - vp0

vp3:
  extends:
    service: vp
  environment:
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
  links:
    - membersrvc
    - vp0

2) Start the network with command:
docker-compose up

3) Containers after starting netwotk:
$docker ps -a

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                          NAMES
74177b219e92        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   11 minutes ago      Up 11 minutes                                                                      linux_vp1_1
01caaf796cbc        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   11 minutes ago      Up 11 minutes                                                                      linux_vp3_1
594be86bbcc1        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   11 minutes ago      Up 11 minutes                                                                      linux_vp2_1
3db01ae449f8        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   11 minutes ago      Up 11 minutes       0.0.0.0:5000->5000/tcp, 0.0.0.0:30303-30304->30303-30304/tcp   linux_vp0_1
fb122dcc4234        hyperledger/fabric-membersrvc   "membersrvc"             11 minutes ago      Up 11 minutes       0.0.0.0:50051->50051/tcp                                       linux_membersrvc_1
8ca80f95e850        hyperledger/fabric-peer         "sh -c 'sleep 5; peer"   11 minutes ago      Up 11 minutes                                                                      linux_vp_1

4) I deploy a chaincode using sdk/node. Then I issue command 'docker ps -a'. I don't see any docker chaincode.

5) I view log of peer 3db01ae449f8. I see an error:

20:54:54.111 [dockercontroller] deployImage -> ERRO 814 Error building images: Tag latest not found in repository docker.io/hyperledger/fabric-baseimage
20:54:54.111 [dockercontroller] deployImage -> ERRO 815 Image Output:

---

Step 1 : FROM hyperledger/fabric-baseimage
Pulling repository docker.io/hyperledger/fabric-baseimage

---

Could you please give an idea about the problem?

**Comment by rameshthoomu** [comment]
@scorpiovn: You should have hyperledger/fabric-baseimage:latest image in your system. Build fabric-baseimage:latest, before execute above script.

**Comment by ghost** [comment]
@rameshthoomu Thanks
