### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by CocoaWang** [hyperledger-archives/fabric#2329]
I am making a gRPC client to  register a new client .And I use the function registerUser in eca_test.go file . The code shows as below:
## Description

//create req
    req := &pb.RegisterUserReq{
        Id:          &pb.Identity{Id: user.enrollID},
        Role:        pb.Role(user.role),
        Account:     user.affiliation,
        Affiliation: user.affiliationRole,
        Registrar: &pb.Registrar{
            Id:            &pb.Identity{Id: registrar.enrollID},
            Roles:         user.registrarRoles,
            DelegateRoles: user.registrarDelegateRoles,
        },
        Sig: nil}
    log.Print(req)

```
//sign the req
hash := primitives.NewHash()
raw, _ := proto.Marshal(req)
hash.Write(raw)

r, s, err := ecdsa.Sign(rand.Reader, registrar.enrollPrivKey, hash.Sum(nil))
if err != nil {
    msg := "Failed to register user. Error (ECDSA) signing request: " + err.Error()
    return errors.New(msg)
}
R, _ := r.MarshalText()
S, _ := s.MarshalText()
req.Sig = &pb.Signature{Type: pb.CryptoType_ECDSA, R: R, S: S}
log.Print(req)

// 使用gprc 远程调用接口调用远程 server 端register new user 方法
conn, err := grpc.Dial(address, grpc.WithInsecure())
if err != nil {
    log.Fatalf("did not connect: %v", err)
}
defer conn.Close()
c := pb.NewECAAClient(conn)

token, err := c.RegisterUser(context.Background(), req)
if err != nil {
    return err
}

if token == nil {
    return errors.New("Failed to obtain token")
}

//need the token for later tests
user.enrollPwd = token.Tok
```

Then I get the error  :   panic:runtime error : invalid memory address or nil pointer dereference.By making breakpoints ,I find it  crashed at   hash :=primitives.NewHash()

**Comment by CocoaWang** [comment]
Here is my error log.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x476016]

goroutine 1 [running]:
panic(0x931180, 0xc82000a110)
    /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/core/crypto/primitives.NewHash(0x0, 0x0)
    /opt/gopath/src/github.com/hyperledger/fabric/core/crypto/primitives/hash.go:41 +0x26
main.registerUser(0x9dc8a0, 0x5, 0xc90610, 0xc, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca_client/main.go:169 +0x357
main.main()
    /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ca_client/main.go:209 +0x40
exit status 2

**Comment by andresgaragiola** [comment]
@CocoaWang can you describe how reproduce this error? It sounds as if you haven't initialized the default hash.  You can use [this](https://github.com/hyperledger/fabric/blob/master/core/crypto/primitives/init.go#L63#L79) to initialize the security level before invoke `hash := primitives.NewHash()` in your code. For example to use SHA3 and length 256 bits you can use `primitives.SetSecurityLevel("SHA3", 256)`. I understand that you are developing a custom client, you can see how this is initialized in the regular client [here](https://github.com/hyperledger/fabric/blob/master/peer/main.go#L339#L341l).

**Comment by CocoaWang** [comment]
@andresgaragiola  Hi!Thanks you first.I tried  hash:=primitives.SetSecurityLevel("SHA3",256) ,but get  the  same error .
It's true that  I am developing a custom client to register a new user which is not in the membersrvc.yaml 

#Reproduce 
I follow the  registerUser method in  eca_test.go file.And I changes 
token, err := ecaa.RegisterUser(context.Background(), req)   
to 
conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewECAAClient(conn)

	token, err := c.RegisterUser(context.Background(), req)

So I can use grpc service to register a new user.

**Comment by CocoaWang** [comment]
@andresgaragiola  Hi ,thanks for you answer.You are right. My problem is that the Initialization is not sufficient.
I am working on registering a new user.And I found I can make a grpc client.Then I follow the eca_test.go 's  registerUser method separately in a new go file.Then I get the panic error.How should I make the initialization properly?

**Comment by CocoaWang** [comment]
@andresgaragiola  Thanks again! I have found my error. I add some initialization in my code.Now I get some other errors.When I send my request to member service server / ecaa.go/RegisterUser method  like this : 
  token, err := c.RegisterUser(context.Background(), req)  
I get: rpc error : code=2 desc = "sql: no rows in result set "

**Comment by andresgaragiola** [comment]
@CocoaWang can you send us the variable "req" attributes? Does this error occurs in the first RegisterUser invocation?

**Comment by CocoaWang** [comment]
@andresgaragiola  Here is my code that I generate  my req : 

////registerUser(testAdmin, &testUser)
	hash := primitives.NewHash()
	raw, _ := proto.Marshal(req)
	hash.Write(raw)

	//初始化 ecdsa
	curve := primitives.GetDefaultCurve()
	fmt.Printf("Default Curve %v \n", curve)
	signPriv, err := primitives.NewECDSAKey()
	testAdmin.enrollPrivKey = signPriv
	r, s, err := ecdsa.Sign(rand.Reader, testAdmin.enrollPrivKey, hash.Sum(nil))
	if err != nil {
		msg := "Failed to register user. Error (ECDSA) signing request: " + err.Error()
		log.Print(msg)
		//return errors.New(msg)
	}
	R, _ := r.MarshalText()
	S, _ := s.MarshalText()
	req.Sig = &pb.Signature{Type: pb.CryptoType_ECDSA, R: R, S: S}
	log.Print(req)

The req result is   
id:<id:"testUser" > role:CLIENT account:"institution_a" affiliation:"00001" registrar:<id:<id:"admin" > > sig:<r:"65574467999467688793422813304123357906562740277044923147984373162931017635525" s:"34880349115322446274243610531576160277660463394208669959616610631163344889105" >

Then I run  : 
conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
	c := pb.NewECAAClient(conn)
token, err := c.RegisterUser(context.Background(), req)
Then I get the error log.

**Comment by CocoaWang** [comment]
@andresgaragiola   By checking the source code,I find that the error occurs  in here

raw, err := ecaa.eca.readCertificateByKeyUsage(registrar, x509.KeyUsageDigitalSignature)

This queries the ca database to inquire registar ,but find nothing which led to a error. The registar I use  is   User{enrollID: "admin", enrollPwd: []byte("Xurw3yU9zI0l")}

**Comment by CocoaWang** [comment]
@andresgaragiola  Hi! I just solved this error.It's because that I did not enroll my registar before registering my new user.
Thanks for your help!I just finish registering a new user  by using the gRPC method.

**Comment by JonathanLevi** [comment]
@CocoaWang, @andresgaragiola: great. Can we close this issue (if all is well...) ?

**Comment by CocoaWang** [comment]
@JonathanLevi  Sure.Eeverything is ok.
