### ISSUE TITLE
How to register a user to memberservice which membersrvc.yaml doesn't contain the user before?

### ISSUE THREAD

**Issue by huhaiqing** [hyperledger-archives/fabric#2332]
Hi,

Currently, We only know register a user to memberservice should make sure the membersrvc.yaml file contains the user before.　For example, lukas is alreday existed in membersrvc.yaml file, and we can register the user lukas to memberservice. 

If we want to register a new user which the membersrvc.yaml files does not contain its name and secret, could you tell us how to implement this scenera.

**Comment by CocoaWang** [comment]
Hi , I am doing the same thing now!For  member service using gRPC framework,I  am making a gRPC client to interact with gRPC server. You can see eca_test.go  file in membersrvc/ca folder.There you can see TestRegisterUser method.This tells how to make new user in local.

**Comment by CocoaWang** [comment]
Now I am making a gRPC client using the memersrvc API showed in   docs/API/MemberServicesAPI.md

**Comment by ghost** [comment]
@huhaiqing 
You can take a look at this:
https://github.com/hyperledger/fabric/blob/master/sdk/node/test/unit/registrar.js

**Comment by christo4ferris** [comment]
@huhaiqing what @scorpiovn said. Assume this can be closed. Thanks
