### ISSUE TITLE
How to reset my local environment of fabric?

### ISSUE THREAD

**Issue by qubing** [hyperledger-archives/fabric#2333]
## Description

I'm working in my local fabric blockchain environment, because I need to lots' of deployment for testing, the folder size is bigger and bigger. 
## Describe How to Reproduce

Is there any method to reset my fabric environment? How? I want to clear all blocks. Is it same for production mode and dev mode?

**Comment by iiiLiQuiDiii** [comment]
Are you not using a docker container? I just delete the container and make a new one, saves me a lot of headaches when I need a fresh environment. 
The peer stores data in /var/hyperledger/production by default, you can configure the location via the core.yaml file (make a copy of the default one and place it in the same folder as the peer executable)

**Comment by christo4ferris** [comment]
We've migrated to use of JIRA https://jira.hyperledger.org you will need an LFID https://identity.linuxfoundation.org/ to login. It seems as if your question has been addressed. Note that you can also simply rebuild your development environment if you are using the vagrant build approach with: `vagrant halt && vagrant destroy && vagrant up`. Closing

**Comment by qubing** [comment]
@iiiLiQuiDiii  Thank you. I got it.
