### ISSUE TITLE
Tag latest not found in repository docker.io/hyperledger/fabric-baseimage

### ISSUE THREAD

**Issue by alkopnin** [hyperledger-archives/fabric#2336]
Hi everyone,
I have the issue with latest base image version. I set up docker with installed environment, and inside I run network (3 peers with pbft + CA). When I deployed chaincode via REST I have got an issue:

**Request is:**

var sc_deployConfig = {
       "jsonrpc": "2.0",
        "method": "deploy",
                "params": {
                        "type": 1,
                        "chaincodeID": { 
                            "name": chaincode_example02,
                            "path": github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
                        },
                        "ctorMsg": {
                                "function": "init",
                                "args":[ "a", "1000", "b", "20"]
                        },
                        "secureContext": account
                },
        "id": 1
    };

**Response is**

successful deployment:  { jsonrpc: '2.0',
  result: 
   { status: 'OK',
     message: '2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8' },
  id: 1 }

**However, peers log is:**

10:05:40.353 [state] TxBegin -> DEBU 240 txBegin() for txUuid [2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8]
**vp1_1 | 10:05:40.354 [dockercontroller] deployImage -> ERRO 21a Error building images: Tag latest not found in repository docker.io/hyperledger/fabric-baseimage**
vp1_1 | 10:05:40.354 [dockercontroller] deployImage -> ERRO 21b Image Output:
vp1_1 | ******************
vp1_1 | Step 1 : FROM hyperledger/fabric-baseimage
vp1_1 | Pulling repository docker.io/hyperledger/fabric-baseimage
vp1_1 |
vp1_1 | **********************
vp1_1 | 10:05:40.354 [container] unlockContainer -> DEBU 21c container lock deleted(dev-vp1-2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8)

**I built base image from the source and put it inside the docker. Now error looks like**

13:15:59.160 [consensus/pbft] startTimerIfOutstandingRequests -> DEBU 12a Replica 2 not starting timer because all outstanding requests are pending
**vp0_1 | 13:15:59.227 [dockercontroller] deployImage -> ERRO 12c Error building images: Container command '/bin/sh' not found or does not exist.**
vp0_1 | 13:15:59.227 [dockercontroller] deployImage -> ERRO 12d Image Output:
vp0_1 | ********************
vp0_1 | Step 1 : FROM hyperledger/fabric-baseimage
vp0_1 | ---> 91d9651c2e1b
vp0_1 | Step 2 : COPY src $GOPATH/src
vp0_1 | ---> Using cache
vp0_1 | ---> c4dfde6a49bc
vp0_1 | Step 3 : WORKDIR $GOPATH
vp0_1 | ---> Using cache
vp0_1 | ---> 4f505c692d2d
vp0_1 | Step 4 : RUN go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8
vp0_1 | ---> Running in 46d8fefb53fa
vp0_1 |
vp0_1 | ********************
vp0_1 | 13:15:59.227 [container] unlockContainer -> DEBU 12e container lock deleted(dev-vp0-2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8)
vp0_1 | 13:15:59.227 [chaincode] Launch -> ERRO 12f launchAndWaitForRegister failed Error starting container: Container command '/bin/sh' not found or does not exist.
vp0_1 | 13:15:59.227 [state] TxFinish -> DEBU 130 txFinish() for txUuid [2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8], txSuccessful=[false]

**Thanks advance**

**Comment by zamrokk** [comment]
👍

**Comment by ghost** [comment]
What were commands that you used to start peers and CA?
Additionally, you need at least 4 peers to apply PBFT. I believe.

**Comment by alkopnin** [comment]
@scorpiovn Thanks for answer. 
I use docker-compose up. My config in attachments. In my opinion, it's doesn't matter how much peers, because they can't download baseimage.

[docker-compose.txt](https://github.com/hyperledger/fabric/files/388871/docker-compose.txt)
[peer-template.txt](https://github.com/hyperledger/fabric/files/388873/peer-template.txt)

**Comment by vmorris** [comment]
@kopnin You have two different approaches here, with two different problems.

I cannot say why in your first approach the peer container cannot find the base image, but in your second approach, the error is related to your image not finding /bin/sh, which is needed to launch the chaincode container.

**Comment by alkopnin** [comment]
@vmorris Let's try to solve the first one. I tried to pull image directly and I have the same issue:
$ docker pull hyperledger/fabric-baseimage 
"Tag latest not found in repository docker.io/hyperledger/fabric-baseimage"

**Comment by vmorris** [comment]
Okay, can you run the `make images` command inside the fabric source directory instead?
After that, what is the output of `docker images | grep fabric` ?

**Comment by ghost** [comment]
@kopnin @vmorris 
For first problem, on vagrant environment:
1) cd $GOPATH/src/github.com/hyperledger/fabric
2) make or make peer-image

**Comment by ghaskins** [comment]
FYI, this is FAD for now.  The system is not yet prepared to be launched purely in a docker flow:  The entire system is predicated on doing a build from source.  The base-image is synthesized from the build as noted here:

https://github.com/hyperledger/fabric/blob/master/scripts/provision/docker.sh#L3

What needs to happen going forward to support a pure docker deployment:

1) The build should produce versioned docker images (e.g. peer:v1.0.0 fabric:v1.0.0 ccenv:v1.0.0) and those should be pushed to dockerhub).  (Actually, they should have the $arch in the tag too, but I don't want to overcomplicate the thread right now).
2) Nothing at runtime should reference "baseimage".  It was intended for use by the build system to cache artifacts, but it has been abused as a runtime target.  Chaincode should use something like ccenv, not baseimage
3) The configuration should include the proper target:  e.g. "peer:v1.0.0" should depend on "ccenv:v1.0.0"

**Comment by ghost** [comment]
@ghaskins Thank you for your information.

**Comment by alkopnin** [comment]
@ghaskins Thanks for response. 
Is it mean that at this moment I have only one possibility to setup fabric network: I should install full dependency (e.g RocksDB) directly on the host, build source and run outside of the docker container, isn't it? What about samples with docker-compose, doesn't work?

**Comment by ghaskins** [comment]
@kopnin To be clear, what I mean is that you cannot just do "docker pull hyperledger/fabric-peer" et. al. and expect it to work.  Currently, "hyperledger/fabric-peer" would expect to find "hyperledger/fabric-baseimage:latest" in your docker image catalog or things won't work since we (intentionally) do not have baseimage:latest in dockerhub.  You can work around this by ensuring that baseimage:latest exists locally.  One way to do that would be to build from source (specifically, "make images").  However, if you are creative enough, you could do it other ways too.

So, I am not saying you need to run outside of docker, or that docker-compose won't work.  I am merely saying that trying to do the full suite of operation by relying solely on "docker pull" type functions won't work (yet).  We need to (and will) fix this, but that is the state it is in right now.

**Comment by ghost** [comment]
@ghaskins I understand what you said that we should use 
https://github.com/hyperledger/fabric/blob/master/scripts/provision/docker.sh#L3
to create hyperledger/fabric-baseimage. Right?

**Comment by ghaskins** [comment]
@scorpiovn I would advocate "make images" over running the script directly so that any prerequisites may be processed.  That said, I think that baseimage doesn't have any (at least currently) so running that script alone will likely work, YMMV.

**Comment by ghost** [comment]
@ghaskins I got it.

**Comment by ghost** [comment]
@kopnin 
For second problem, you should copy core.yml to chaincode directory:
$ go get -u github.com/kardianos/govendor
$ cd $GOPATH/src/github.com/chaincode_dir
$ govendor init
$govendor add +external
$ govendor fetch github.com/hyperledger/fabric
Then, copy core.yml to $GOPATH/src/github.com/chaincode_dir./vendor/github.com/hyperledger/fabric/peer/

**Comment by alkopnin** [comment]
@scorpiovn thanks, I can't understand were I have to do it. Let's do it by step:
1) I build images with vagrant: peer, membersrvc, baseimage
2) run docker-compose and start peers and membersrvc
All fine, they works and exchange data. 

3) Run nodejs script and connect over rest to peer
4) Send request to run deployment process
5) Recv response to client: success - message have chaincode address
6) Peers begin build images and fail after:

18:54:26.870 [dockercontroller] deployImage -> ERRO f88 Error building images: Container command '/bin/sh' not found or does not exist.

> > > vp2_1        | 18:54:26.871 [dockercontroller] deployImage -> ERRO f89 Image Output:
> > > vp2_1        | ********************
> > > vp2_1        | Step 1 : FROM hyperledger/fabric-baseimage
> > > vp2_1        |  ---> 59395b2af9c7
> > > vp2_1        | Step 2 : COPY src $GOPATH/src
> > > vp2_1        |  ---> Using cache
> > > vp2_1        |  ---> 03f90d085f2d
> > > vp2_1        | Step 3 : WORKDIR $GOPATH
> > > vp2_1        |  ---> Using cache
> > > vp2_1        |  ---> 7d63e9372360
> > > vp2_1        | Step 4 : RUN go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8
> > > vp2_1        |  ---> Running in 89c34250679b

I can't understand, how I can change this situation? Peers works with baseimage. In my opinion, normally it should work. When, where and why I should use this instructions? Could you help me and clarify, please.

Baseimage I built with vagrant: make images. 
Only one note: all activities are happened inside the docker (not directly on the host).

**Comment by ghost** [comment]
@kopnin Did you copy core.yml to $GOPATH/src/github.com/YOUR_CHAINCODE_DIR/vendor/github.com/hyperledger/fabric/peer/ ?

**Comment by ghost** [comment]
@kopnin Did you install latest version of HFC(sdk/node) ?

**Comment by alkopnin** [comment]
Thanks you, @scorpiovn
I don't use HFC, I have begun with node-rest-client just to try simple transactions. Chaincode is chaincode_example02. I provide path to source on github, like in example (github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02). Is it correct? Or I have to build it as you wrote above and thereafter upload to the public repo? 

**Upd**: Follow steps where I have a fail, chaincode have to be build on the ledger inside the baseimage:
Step 4 : RUN **go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02** && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/2a273ea93d64d1d793581ea35d82e99cb14d0593eb1f289899a744dbb41efe2043ec385911181e5c44eabd7be20b5e5e383ccd38a6234c9c1318209247321cf8

**Comment by tribbloid** [comment]
+1, affect me too. Also REST API returns 200 while it should return 401/5xx.
vein attempt to cover the failure :-<

**Comment by ghost** [comment]
@kopnin It is not a path to source on github. It is on $GOPATH.
You should copy that source to $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02.

**Comment by alkopnin** [comment]
@scorpiovn Ok, thanks a lot! I'll try today, is it path should be on the peer?
If I understand, clients should send chaincode directly to the peers, isn't it? I this case all clients have to know at least one peer with possibility to upload chaincode, isn't it?
Let's imagine real example. I'm a client. I have only an application have written on nodejs/java/.. (doesn't matter). App connects to the remote peer (validator and non validators) to make transactions and to get a ledger info. 

I would like to deploy my own chaincode to the remote ledger. To do it I have to:
1) Send chaincode to peer (validator/non validator) with any suitable method (from email to  webservice). 
2) Peer will put contract locally to the path.
$GOPATH/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02. 
3) I can send "deploy and init" to this peer from my nodejs/java/.. application.

**UPD:** On each peer I copied core.yaml, but doesn't work:
cp peer/core.yaml $GOPATH/src/github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/

**Comment by ghaskins** [comment]
@kopnin If you use the SDK, your deployment comes from either a URL or your local filesystem.  It is then packaged up and deployed directly to all of the validating peers.  If you are _not_ using the SDK, it is expected that you have an NVP that is under your control and considered part of your client stack.  IOW, the REST interface to an NVP is meant to be an extension of your client.  So, while it is accurate to say that, when using the REST API + private deployments, you do need to somehow get the file to the peer OOB, it is not accurate to treat it as any random peer in the network.  It's a very special peer (to you) as it's part of your own stack.  I hope this helps.

**Comment by alkopnin** [comment]
@ghaskins Thanks you, Gregory. It's very helpful.
