### ISSUE TITLE
Node SDK documentation is broken on NPM

### ISSUE THREAD

**Issue by ghaskins** [hyperledger-archives/fabric#2339]
## Description

The links within the documentation on NPM do not work properly.
## Describe How to Reproduce

Go to https://www.npmjs.com/package/hfc#going-deeper and click on some of the links like "Member".  A 404 is returned.

Workarounds: build the doc locally from fabric.git and open with a file:// URL

**Comment by christo4ferris** [comment]
opened issue on jira, closing https://jira.hyperledger.org/browse/FAB-211
