### ISSUE TITLE
peer_basic.Network of Peers.chaincode example02 with 4 peers and 1 membersrvc, test crash fault -- @1.1 Consensus Options - failed with timeout issue

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#2346]
## Description

behave test case (peer_basic.Network of Peers.chaincode example02 with 4 peers and 1 membersrvc, test crash fault -- @1.1 Consensus Options) failed while waiting invoke transaction to be committed to all peers. Observed below is the root cause for the above failure:

Build Failing step: Then I wait up to **"60"** seconds for transaction to be committed to peers ... failed in **60.259s**.  Build Reference# 84
Build Failing step: Then I wait up to **"60"** seconds for transaction to be committed to peers ... failed in **60.272s** - Build Reference# 82
## Describe How to Reproduce

Jenkins failed build references:
https://jenkins.hyperledger.org/view/fabric/job/fabric-verify-x86_64/84/
https://jenkins.hyperledger.org/view/fabric/job/fabric-verify-x86_64/82/

**Comment by tuand27613** [comment]
The test in question stops and restarts peers vp1/vp2. 
The peers come back up with different IP addresses while the peer code tries to re-establish connections using the old IP addresses ( as it should , imho ).

The behave test runs fine in my vagrant with docker v1.11.2

**Comment by rameshthoomu** [comment]
Interesting..  Docker version in Jenkins build machine is 1.8.2

```
+ docker version
00:00:36.920 Client:
00:00:36.920  Version:      1.8.2
00:00:36.920  API version:  1.20
00:00:36.920  Go version:   go1.4.2
00:00:36.920  Git commit:   0a8c2e3
00:00:36.920  Built:        Wed Oct  7 17:48:28 UTC 2015
00:00:36.920  OS/Arch:      linux/amd64
00:00:36.920 
00:00:36.920 Server:
00:00:36.920  Version:      1.8.2
00:00:36.920  API version:  1.20
00:00:36.920  Go version:   go1.4.2
00:00:36.920  Git commit:   0a8c2e3
00:00:36.920  Built:        Wed Oct  7 17:48:28 UTC 2015
00:00:36.920  OS/Arch:      linux/amd64
```

**Comment by rameshthoomu** [comment]
Not observed this issue after merge below patch set in gerrit
https://gerrit.hyperledger.org/r/#/c/371/ --

Will reopen or create a new issue if we observe this issue again.. Closing now.
