### ISSUE TITLE
ACA service console log should reflect its enablement

### ISSUE THREAD

**Issue by jimthematrix** [hyperledger-archives/fabric#2348]
## Description

The membersrvc console log outputs the following statements of the ACA service regardless of whether it's enabled or not (as per aca.enabled settings):

INFO: 2016/08/01 18:32:11 Staring ACA services...
INFO: 2016/08/01 18:32:11 ACA PUBLIC gRPC API server started
INFO: 2016/08/01 18:32:11 ACA services started

should print a different message if the service is not enabled to avoid confusion

@diegomasini

**Comment by andresgaragiola** [comment]
@srderson can you assign me this issue?

**Comment by srderson** [comment]
@andresgaragiola I lost the ability to assign/close issues with the move to Gerrit. Maybe @christo4ferris still has this power, but he is on vacation until next week.

**Comment by JonathanLevi** [comment]
@andresgaragiola, same here.

But it's totally fine to just submit a Gerrit patch, referring to this issue.

**Comment by JonathanLevi** [comment]
@andresgaragiola that was fast!

@jimthematrix Andres' changes are merged to master. Please can you confirm that this is resolved and we'll close?

**Comment by JonathanLevi** [comment]
@jimthematrix The log correctly reflected that the ACA started. @andresgaragiola's fix was to actually not start the ACA when it was not needed. I think we can safely close this issue.

**Comment by jimthematrix** [comment]
verified.

**Comment by JonathanLevi** [comment]
Thank you.
