### ISSUE TITLE
Implement validator flow for basic PBFT

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#235]
Consider a fixed leader, and a network of 4 validating peers overall.

Upon receiving a `PRE_PREPARE` from the leader, a validator should go ahead with the speculative execution and the transfer of `PrepareResult` and `CommitResult` messages.

Once a commit certificate is acquired, the validator should adopt its candidate global hash.

The data structures of #168 should be used. (A PR for those should be up by the end of the week.)

Pre-requisites:
- A working `Broadcast()` function
- An easy way to bring up a network of 4 validating peers (#208).

**Comment by vukolic** [comment]
Re: "An easy way to bring up a network of 4 validating peers." @elli-androulaki gave a good idea that the metadata needed to make this happen might be carved into the genesis block (Block no.0).

**Comment by kchristidis** [comment]
Simon, if I got any details wrong on the issue description, feel free to post corrections here.
