### ISSUE TITLE
getNextTCert API in member class in Node SDK fetched tcert even when we pass a non-exiting attibute

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#2351]
Passed in a non-existing attribute for user alice to getNextTCert by calling
    alice.getNextTCert(['fail'],function(err, tcert) in the test.
## Expected Result:

Test to fail since 'fail' is not an attribute defined for alice in membersrvc.yaml
## Actual Result:

Test passed and generated a TCert.

commit 346f9fb448140e931fed73b46f528de6dacbc0d0

**Comment by JonathanLevi** [comment]
Thank you @2016Nishi.

What's the relation to commit [346f9fb](https://github.com/hyperledger/fabric/commit/346f9fb448140e931fed73b46f528de6dacbc0d0) ?

**Comment by 2016Nishi** [comment]
That was the commit on fabric source used in testing.

**Comment by JonathanLevi** [comment]
- assign @JonathanLevi

[I'll take a look ;-)]

**Comment by christo4ferris** [comment]
@2016Nishi we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks

**Comment by 2016Nishi** [comment]
Created issue FAB-219 in JIRA.
