### ISSUE TITLE
getAffiliation API in member class in Node SDK fails to fetch affiliation of a user

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#2352]
Call alice.getAffiliation() in my test to verify getAffiliation for user alice failed.
## Expected Result:

getAffiliation to return 'bank_a' for user alice as in membersrvc.yaml 
## Actual Result:

Test failed returned [undefined]

commit level on fabric source code: 346f9fb448140e931fed73b46f528de6dacbc0d0

**Comment by christo4ferris** [comment]
@2016Nishi we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks

**Comment by 2016Nishi** [comment]
Created issue FAB-218 in JIRA.
