### ISSUE TITLE
getRoles API in member class in Node SDK fails to fetch getRoles of a user

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#2353]
Call alice.getRoles() in my test to verify roles for user alice retrieved successfully from membersrv.yaml failed.

Expected Result:

attributes as defined in membersrvc.yaml
"attribute-entry-7: alice;bank_a;role;client;2016-01-01T00:00:00-03:00;;
 attribute-entry-8: alice;bank_a;account;12345-56789;2016-01-01T00:00:00-03:00;;"

getRoles to return attribute keys: 'role' and 'account' for user alice as in membersrvc.yaml

Actual Result:

Test failed returned [undefined]

commit level on fabric source code: 346f9fb

**Comment by christo4ferris** [comment]
@2016Nishi we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks

**Comment by 2016Nishi** [comment]
Created issue FAB-217 in JIRA.
