### ISSUE TITLE
Fork off the hyplerledger-client tree

### ISSUE THREAD

**Issue by EvanCarroll** [hyperledger-archives/fabric#2354]
It would certainly ease packing with NPM and also doc references if this tree was relocated to it's own repository. I could easily rewrite the tree into another repo if you want to do it. Then it could be installed with npm, and referenced on the [official index.](https://www.npmjs.com/package/hfc)

https://github.com/hyperledger/fabric/tree/master/sdk/node

**Comment by christo4ferris** [comment]
@EvanCarroll the client SDK can indeed be retrieved from npm. The module name is ['hfc'.](https://www.npmjs.com/package/hfc). Closing.
