### ISSUE TITLE
Access control for chaincode deployment?

### ISSUE THREAD

**Issue by iiiLiQuiDiii** [hyperledger-archives/fabric#2355]
## Description

Is there a way to limit who can deploy chaincode to the network? In my scenario any client can submit a smart contract and I'd like more control over that aspect.

**Comment by muralisrini** [comment]
@iiiLiQuiDiii currently there is no ACL support for chaincode lifecycle. Its on the roadmap.

**Comment by iiiLiQuiDiii** [comment]
Thank you for the info.
