### ISSUE TITLE
sdk/node Peer constructor url description is incomplete 

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#2358]
## Description

The constructor description for the peer object has a couple problems:
1.config --> did you mean 'configuration'?
2.Parameter 'url' is described as 'the url of'.   The url of what?  Not very helpful!

Here is an excerpt from the generated documentation

_constructor
new Peer(url: string, chain: Chain, pem: string): Peer

Defined in src/hfc.ts:2042

Constructor for a peer given the **endpoint config** for the peer.

Parameters

◾url: string

**The URL of**_
## Describe How to Reproduce

1,From fabric directory, run  make node-sdk-unit-tests
2.In a web browser, navigate to file:///C:/go/src/github.com/hyperledger/fabric/sdk/node/doc/classes/_src_hfc_.peer.html   which describes class peer.
3.Scroll down to Constructor then inspect new Peer(...

**Comment by christo4ferris** [comment]
@jjjjibm we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks

**Comment by jjjjibm** [comment]
The Jira equivalent defect is FAB-233.
