### ISSUE TITLE
Identity or token does not match when relogin

### ISSUE THREAD

**Issue by zuowang** [hyperledger-archives/fabric#2359]
## Description

Identity or token does not match when relogin.
## Describe How to Reproduce

1.login bob

curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d '
{ "enrollId": "bob", "enrollSecret": "NOE63pEQbL25" }
' "http://localhost:7050/registrar"
{"OK":"Login successful for user 'bob'."}

2.logout bob

curl -X DELETE --header 'Accept: application/json' 'http://localhost:7050/registrar/bob'
{"OK":"Deleted login token and directory for user bob."}

3.relogin bob

curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d '
{ "enrollId": "bob", "enrollSecret": "NOE63pEQbL25" }
' "http://localhost:7050/registrar"
{"Error":"rpc error: code = 2 desc = \"Identity or token does not match.\""}
Attachments

**Comment by mastersingh24** [comment]
@zuowang  - see my comment here:   https://jira.hyperledger.org/browse/FAB-2

**Comment by CocoaWang** [comment]
Password  will change after your login.

**Comment by christo4ferris** [comment]
@zuowang closing this as I believe that @mastersingh24 comment above should cover this. Note also that we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, If you need to re-open, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks
