### ISSUE TITLE
Failed to deploy chaincode when security is enabled

### ISSUE THREAD

**Issue by hanhzf** [hyperledger-archives/fabric#2361]
### I start fabric with:
- pbft consensus with 4 nodes
- security enabled
  
  docker run -it --net=host --name vp0 \
    -e CORE_PEER_ID=vp0 \
    -e CORE_PBFT_GENERAL_N=4 \
    -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 \
    -e CORE_LOGGING_LEVEL=INFO\
    -e CORE_PEER_ADDRESSAUTODETECT=true \
    -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft \
    -e CORE_PBFT_GENERAL_MODE=batch \
    -e CORE_PBFT_GENERAL_BATCHSIZE=1 \
    -e CORE_PBFT_GENERAL_TIMEOUT_REQUEST=20s \
    -e CORE_SECURITY_ENABLED=true \
    -e CORE_SECURITY_ENROLLID=test_vp0 \
    -e CORE_SECURITY_ENROLLSECRET=zhu88jie \
    -e CORE_PEER_PKI_ECA_PADDR=vp0:7054 \
    -e CORE_PEER_PKI_TCA_PADDR=vp0:7054 \
    -e CORE_PEER_PKI_TLSCA_PADDR=vp0:7054 \
    -v /hyperledger/build/bin:/opt/gopath/bin \
    -v /var/hyperledger:/var/hyperledger \
    -p 7050:7050 \
    -p 7051:7051 \
    hyperledger/fabric-peer peer node start
  ### After peer node is started, I can see following logs from peer's log:

**08:27:21.291 [nodeCmd] serve -> INFO 003 Security enabled status: true**
**08:27:21.291 [nodeCmd] serve -> INFO 004 Privacy enabled status: true**
### Then I login with the admin user on vp0:

curl -X POST -H "Content-Type: application/json" -d '{"enrollId": "admin","enrollSecret": "Xurw3yU9zI0l"}' http://vp0:7050/registrar/
### Then deploy chaincode with following cmd from vp0:

peer chaincode deploy -u admin -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
### Then following warning and error were met:

16:35:36.871 [chaincodeCmd] chaincodeDeploy -> WARN 001 Username supplied but security is disabled.

Usage:
  peer chaincode deploy [flags]

Global Flags:
  -a, --attributes="[]": User attributes for the chaincode in JSON format
  -c, --ctor="{}": Constructor message for the chaincode in JSON format
  -l, --lang="golang": Language the chaincode is written in
      --logging-level="": Default logging level and overrides, see core.yaml for full syntax
  -n, --name="": Name of the chaincode returned by the deploy transaction
  -p, --path="": Path to chaincode
      --test.coverprofile="coverage.cov": Done
  -t, --tid="": Name of a custom ID generation algorithm (hashing and decoding) e.g. sha256base64
  -u, --username="": Username for chaincode operations when security is enabled
  -v, --version[=false]: Display current version of fabric peer server

Error: Error building chaincode: rpc error: code = 5 desc = "open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory"

**Comment by andresgaragiola** [comment]
Hello @hanhzf it sounds as if you have enabled security in peers but not in the client. Can you try this in your client console?: 

`$ export CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=true`
`$ ./peer network login admin`

And then: 
`$ peer chaincode deploy -u admin -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`

**Comment by hanhzf** [comment]
@andresgaragiola, yes it works, thank you. And I see this part of doc has been added to Network-setup.md but was commented for the time being: "This needs to be sorted out with a revamped security section". Thus I missed it

**Comment by christo4ferris** [comment]
@hanhzf sounds like resolved. Closing. Thanks!
