### ISSUE TITLE
Error building images: cannot normalise nothing

### ISSUE THREAD

**Issue by cophey** [hyperledger-archives/fabric#2362]
Building outside of Vagrant
My system is ubuntu.
I install go、docker、behave、rocksdb;
I pull docker-images：
- busybox:latest
- hyperledger/fabric-baseimage:x86_64-0.0.10
- hyperledger/fabric-membersrvc
- hyperledger/fabric-peer
- yeasy/hyperledger-peer:latest
    (can not find hyperledger/hyperledger-peer?)

when i run a chaincode in running-mode,Peer logs as this:

> 10:46:55.518 [dockercontroller] deployImage -> ERRO 020 Error building images: cannot normalise nothing
> 10:46:55.830 [dockercontroller] deployImage -> ERRO 021 Error building images: cannot normalise nothing
> 10:46:55.830 [chaincode] Launch -> ERRO 022 launchAndWaitForRegister failed Error starting container: cannot normalise nothing

**Comment by OiCMudkips** [comment]
Hi, I'm running into this same issue. Since you closed this, I'm wondering if you found a way to fix this? Thanks!

**Comment by tengsun** [comment]
I got the same error, @cophey do you have any idea about the solution for this error?

**Comment by OiCMudkips** [comment]
@tengsun I figured out the issue for myself. The issue was that the default Dockerfile used to launch the chaincode's Docker container was broken. To fix it, I overrode the chaincode found in peer/core.yaml. If you're using Docker Compose to launch, here's the environment variable to fix it:

```
environment:
  - |
    CORE_CHAINCODE_GOLANG_DOCKERFILE=
    FROM hyperledger/fabric-baseimage
    ENV GOPATH=/opt/gopath
    COPY src $${GOPATH}/src
    WORKDIR $${GOPATH}
```

Basically, I've explicitly define the GOPATH variable to point to the gopath inside hyperledger/fabric-baseimage.

**Comment by cophey** [comment]
@tengsun @OiCMudkips I run `make all`  command at ${GOPATH}/src/github.com/hyperledger/fabric/,and then it is ok.

**Comment by tengsun** [comment]
@cophey Thanks, the `make all` command works, but have to install the docker manually.
@OiCMudkips I didn't make it run successfully, appreciate if you could attach your docker-compose.yml file here and I'll have a try.
