### ISSUE TITLE
Using a timer inside a chaincode 

### ISSUE THREAD

**Issue by ghost** [hyperledger-archives/fabric#2370]
## Description

Is it possible if we create a timer on a chaincode and it will invoke the chaincode after every timer's interval?

**Comment by muralisrini** [comment]
@scorpiovn : the chaincode should not initiate transactions. The application stack should be organized in such a way as to make the chaincode just manages ledger states. Things like timers, accessing external data etc increase the probability of non-determinism in the chaincode.

**Comment by christo4ferris** [comment]
seems like this can be closed. we've migrated to using [Jira](https://jira.hyperledger.org/secure/RapidBoard.jspa?projectKey=FAB&rapidView=7&view=planning) for issue tracking, if you would like to re-open, please open an issue there and close this one. You'll need a [Linux Foundation ID](https://identity.linuxfoundation.org/) to login. 
Thanks
