### ISSUE TITLE
Receive customized Chaincode Events

### ISSUE THREAD

**Issue by heshansp** [hyperledger-archives/fabric#2371]
## Description

Hi All,
I am trying to receive chaincode custom defined events on a listener I created. I have defined the custom events on the chaincode using `stub.SetEvent`. 

To receive the events I have created an adapter that listens to `0.0.0.0:31315`. The adapter has the following `GetInterestedEvents()` function to interface for registering interested events. 

```
func (a *adapter) GetInterestedEvents() ([]*pb.Interest, error) {
return []*pb.Interest{
    &pb.Interest{EventType: pb.EventType_CHAINCODE, RegInfo: &pb.Interest_ChaincodeRegInfo{ChaincodeRegInfo: &pb.ChaincodeReg{ChaincodeID: chaincodeName, EventName: "*"}}},
    &pb.Interest{EventType: pb.EventType_BLOCK},
}, nil
}
```

The received events are caught by the following function.

```
func (a *adapter) Recv(msg *pb.Event) (bool, error) {

if o, e := msg.Event.(*pb.Event_ChaincodeEvent); e {
    a.chaincode <- o
    return true, nil
}
if o, e := msg.Event.(*pb.Event_Block); e {
    a.notify <- o
    return true, nil
}
return false, nil
}
```

The above seems to work well for receiving block events but so far I have had no luck with receiving chaincode events. Can someone please shed some light on this?

**Comment by heshansp** [comment]
Hi Guys,
Anyone who can help me with this?

**Comment by muralisrini** [comment]
@heshansp This should work with the latest code on gerrit.

**Comment by christo4ferris** [comment]
@heshansp Thanks for submitting this. Note that we have migrated to [Gerrit](https://gerrit.hyperledger.org/r/#/admin/projects/) and [Jira](https://jira.hyperledger.org/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all) for Hyperledger development. See also http://cbf-fabric-docs.readthedocs.io/en/latest/Gerrit/gerrit/. As @muralisrini suggest, this is resolved in the master branch under Gerrit. Closing.
