### ISSUE TITLE
Is the source code of TransactionProcessor in the project?

### ISSUE THREAD

**Issue by CocoaWang** [hyperledger-archives/fabric#2372]
## Description

I want to check the source code of transaction process in TransactionProcessor.But I searched the whole project and found nothing but  two files  helper.a and peer.a.

**Comment by CocoaWang** [comment]
type TransactionProccesor interface {
    ProcessTransactionMsg(*pb.Message, *pb.Transaction) *pb.Response
}
I track the process of invoking a transaction.Finally,I meet this method processTransactionMsg.Can  any one tell me where I can find it?

**Comment by JonathanLevi** [comment]
Hi @CocoaWang, please can you take a look at `/fabric/consensus/helper/engine`... and let me know if that's what you were/are after?

**Comment by JonathanLevi** [comment]
Hi @CocoaWang, please can you take a look at `/fabric/consensus/helper/engine.go`... and let me know if that's what you were/are after?

**Comment by CocoaWang** [comment]
@JonathanLevi  That is exactly what I am looking for!I am wondering why I can't find it.So stupid...
Well，thank you!
