### ISSUE TITLE
Behave tests are failing after merge the commit# `ead0af7 `

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#2374]
## Description

Following behave tests are failing in Jenkins build after merge commit# ead0af7 in master repo. 

```
peer_logging.Peer Logging.Invoke is attempted after deploy in Dev Mode
peer_logging.Peer Logging.Query is attempted after deploy in Dev Mode
```

error log: 

```
File "steps/peer_logging_impl.py", line 61, in step_impl
          assert logHasError(stderr) is False
      AssertionError
```

Jenkins Build reference log files:

https://jenkins.hyperledger.org/view/fabric/job/fabric-merge-x86_64/12/
https://jenkins.hyperledger.org/view/fabric/job/fabric-merge-x86_64/13/
https://jenkins.hyperledger.org/view/fabric/job/fabric-merge-x86_64/14/
## Describe How to Reproduce

Run behave tests in Jenkins..

**Comment by rameshthoomu** [comment]
@jeffgarratt @tuand27613 : Could you please check this?

**Comment by juliancarrivick-ibm** [comment]
@rameshthoomu I wrote these tests. For these tests the Chaincode is deployed manually and I suspect the containers aren't ready in time. I'm working on a more robust method of starting the containers which will fail fast and give a better logging of the container state: https://gerrit.hyperledger.org/r/#/c/421/. 
I hope this helps.

**Comment by rameshthoomu** [comment]
@juliancarrivick-ibm thanks for the fix. Will re-verify once this patch set is merged in master.

**Comment by christo4ferris** [comment]
@rameshthoomu @juliancarrivick-ibm can this be closed?

**Comment by juliancarrivick-ibm** [comment]
The patch-set in question was the one that was reverted because it broke master. Since I have rebased it on the latest master a test has started failing. I am working on a fix now. The new change request is https://gerrit.hyperledger.org/r/#/c/563/

**Comment by christo4ferris** [comment]
ok, closing this then since we have it being worked in Gerrit thanks
