### ISSUE TITLE
Chaincode that was deployed using NodeSDK  Becomes Unusable

### ISSUE THREAD

**Issue by ratnakar-asara** [hyperledger-archives/fabric#2377]
## Description

Chaincode that was deployed using NodeSDK becomes unusable.  This occurs after you deploy/invoke/query the chaincode with the Node SDK.  The next step is the user takes the chaincode id and does a query using the REST API with a different enrolled user.  The query fails using the REST API.  If you then go back to the Node SDK using this chaincode ID, it fails doing invokes and queries as well. 
## How to Reproduce
1. setup a 4-peer network with pbft-batch, security and privacy enabled
2. Registered test_user0 and test_user1 and Deployed chaincode_example02, with values a=100 and b=200, using nodesdk apis (attached node program used to test this scenario)
3. Once deploy is successful through NodeSdk , Register test_user2 and use chaincodeID from previous deployment and make a REST call to Query on A , using PostMan (Or any REST Client)

It fails with below error:

```
'Error:Failed to execute transaction or query(Timeout expired while executing transaction)'
```
1. Now this time, try to Query chaincode from the node program, this time it fails too with a different error

```
"Error:Failed to launch chaincode spec(Could not get deployment transaction for 9c5ceb563bbb5240450f4c0ae77bc6c4b6c069f976433dce6b78cc95651494ab - LedgerError - ResourceNotFound: ledger: resource not found)
```

NOTE: 
- Logs of all peers attached for reference. 
  [logs.zip](https://github.com/hyperledger/fabric/files/409973/logs.zip)
- Node program used for testing. (rename it to helloblockchain.js)
  [helloblockchain.txt](https://github.com/hyperledger/fabric/files/409975/helloblockchain.txt)
- Logs from node program execution, 
  [node_logs.txt](https://github.com/hyperledger/fabric/files/409976/node_logs.txt)
- PostMan Rest client screenshots, 
  ![postman_query](https://cloud.githubusercontent.com/assets/18034452/17535424/539080d0-5e5c-11e6-90f3-c149e755525c.png)
  ![postman_registrar](https://cloud.githubusercontent.com/assets/18034452/17535425/53a338d8-5e5c-11e6-9eab-0766329f2d6f.png)

**Comment by christo4ferris** [comment]
@ratnakar-asara please transfer this to Jira. Thanks!

**Comment by ratnakar-asara** [comment]
transfered issue to Jira JIRA  https://jira.hyperledger.org/browse/FAB-191.
Closing this issue
