### ISSUE TITLE
busywork: Performance timer overflows

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#2379]
## Description

 Sam Ding reported an issue showing that on longs runs, the busywork timer would overflow, and busywork would report negative throughput. This makes sense because the current timer is a microsecond timer, which will overflow (at 32 bits) after a couple thousand seconds. The timing methodology needs to be improved.

**Comment by christo4ferris** [comment]
@bcbrock Thanks for submitting this issue. However, we have transitioned issue tracking to Jira https://jira.hyperledger.org/ Please transfer this issue there and then close this one. Thanks!

**Comment by bcbrock** [comment]
Transferred to Jira (as link)
