### ISSUE TITLE
create new user

### ISSUE THREAD

**Issue by learner4** [hyperledger-archives/fabric#2382]
I am trying to create a new user and stuck at this point....
Any help is appreciated.
step1: npm install hfc (passed)

var hfc=require('hfc')
var chain=hfc.newChain('testchain')
chain.setKeyValStore(hfc.newFileKeyValStore('tmp/kvstore'));
chain.setMemberServicesUrl("grpc://xxxxxxxxx_ca-api.blockchain.ibm.com:30303")
var reguser = {roles:["testrole"], enrollmentID: "someuserid01",account:"acct_1",affiliation:"00001",registrar:null};

so from here I tried 2 ways, both ended up with errors:
Method 1:
chain.registerAndEnroll(reguser, function(err){ console.log (err)})
Error: Registar is not set. (sure, bcos I passed null, so how do I set registrar?, I am only trying to add new user to the network)

Method 2:
chain.enroll("testuser","secret123", function (err,usr){console.log(err); console.log(usr);})

Error: Error:{"created":"@1470967403.041000000","description":"End of TCP stream","file:":""......., "grpc_status":14}]
undefined

**Comment by 2016Nishi** [comment]
Enroll WebAppAdmin and set this user as Registrar, you need a registrar in the system to enroll new or any subsequent users.

`var registrar = {
    name: 'WebAppAdmin',
    secret: 'DJY27pEnl16d'
};
chain.getUser(registrar.name, function (err, userAdmin) {
      if (err) {
          process.exit(1);
      }
      // Enroll the WebAppAdmin user with the certificate authority using
       userAdmin.enroll(registrar.secret, function (err) {
          if (err) {
              process.exit(1);
          }
          chain.setRegistrar(userAdmin);
        })
      })`

Thanks!

**Comment by christo4ferris** [comment]
@learner4 Thanks for submitting this issue. However, we have transitioned issue tracking to Jira https://jira.hyperledger.org/ Please transfer this issue there and then close this one. Thanks!
