### ISSUE TITLE
sdk/node :  chain.DeployWaitTime() -- anything goes 

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#2384]
## Description

I called chain.setDeployWaitTime() to set the wait time to various values: 0, 6000, -1.  The sdk accepted
these values.    A value of 6000 (seconds) is acceptable I suppose but the meanings of 0 and -1 
are not described in the documentation.

I then called chain.setDeployWaitTime("as long as it takes") in the test case
...sdk/node/test/unit/chain-test.js "Deploy a chaincode by enrolled user". 

"as long as it takes" is not a number as required in the documentation:
setDeployWaitTime(secs: number): void

and yet the call succeeded.  Not only did the call succeed, the value did not impact
the deploy: 
_# Deploy a chaincode by enrolled user
setting bogus wait time prior to deploy
deploy results: {"uuid":"mycc1","chaincodeID":"mycc1","result":"TODO: get actual results; waited **as long as it takes** seconds and assumed deploy was successful"}_

Here it is again using -1 as the value:

_# Deploy a chaincode by enrolled user
setting bogus wait time prior to deploy
deploy results: {"uuid":"mycc1","chaincodeID":"mycc1","result":"T ODO: get actual results; waited **-1** seconds and assumed deploy was  successful"}_
## Describe How to Reproduce

In vagrant, 
1.Edit fabric/sdk/node/test/unit/chain-tests.js 
2.Add this call before a valid deploy:  chain.setDeployWaitTime("as long as it takes")
3.Run 'make node-sdk-unit-tests'.

**Comment by christo4ferris** [comment]
@jjjjibm Thanks for submitting this issue. However, we have transitioned issue tracking to Jira https://jira.hyperledger.org/ Please transfer this issue there and then close this one. Thanks!

**Comment by jjjjibm** [comment]
I have duplicated this issue in Jira, so I am closing this one.
