### ISSUE TITLE
Query function does not work for deployed chaincode

### ISSUE THREAD

**Issue by sanachiit** [hyperledger-archives/fabric#2385]
I am trying to query the chaincode example 02 that I have deployed in the local blockchain installation.
I have tried both inside and outside vagrant setup as described by hyperledger-fabric docs. The chaincode go file build successfully and the deployed seems to word. The invoke function generates the transaction hash, however as soon as I query the state of variable A using the chaincode hash id, it always indicates an error indicating that the chaincode is not deployed successfully.

**Comment by christo4ferris** [comment]
@sanachitmehra Thanks for submitting this issue. However, we have transitioned issue tracking to Jira https://jira.hyperledger.org/ Please transfer this issue there and then close this one. Thanks!

**Comment by cyu021** [comment]
@sanachitmehra @christo4ferris, I encountered the same issue and just transferred this to jira.
https://jira.hyperledger.org/browse/FAB-208

**Comment by christo4ferris** [comment]
Thanks! closing
