### ISSUE TITLE
Multi-channel TCert pool making pool's communication with TCA parallel.

### ISSUE THREAD

**Issue by akihikot** [hyperledger-archives/fabric#2387]
## Description

I think client_tcert_pool_mt.go can be further improved, by making communication with TCA parallel.  The measurement with my prototype shows better performance, by utilizing CA-side concurrency. 

![authorizable_counter_20160714](https://cloud.githubusercontent.com/assets/7088462/17673488/4c08f4f0-635c-11e6-9a74-9bd3d6f00df8.png)

In this measurement, I followed the suggestion by @bcbrock in Issue #996 and disabled CloseClient(). 

Here are some points for discussions. 
- whether this option should be made default for mt pool.
- whether a similar idea should be implemented in sdk/node. 
## Describe How to Reproduce

This option can be enabled by security.multithreading.multichannel=true in the corresponding gerrit change https://gerrit.hyperledger.org/r/#/c/511/.

**Comment by christo4ferris** [comment]
@akihikot Thanks for submitting this issue. However, we have transitioned issue tracking to Jira https://jira.hyperledger.org/ Please transfer this issue there and then close this one. Thanks!
