### ISSUE TITLE
stub.InvokeChaincode invoke a chaincode function,GetCallerCertificate() returns nil 

### ISSUE THREAD

**Issue by cophey** [hyperledger-archives/fabric#2390]
## Description

security enabled and privacy disabled
chaincode_example04.go invoke funtion call stub.InvokeChaincode(chaincode_example02,invoke,[]string{"a", "b", "10"})

in chaincode_example04.go invoke function print cert:
`b, _ := stub.GetCallerCertificate()`
`fmt.Println("cert", hex.EncodeToString(b))`

in chaincode_example02.go invoke function print cert:
`b, _ := stub.GetCallerCertificate()`
`fmt.Println("cert", hex.EncodeToString(b))`

But it print differently.
chaincode_example04 log:
`cert 3082024a308201f1a003020102021100c261f3e7841540e9887f82956ac7f8ab300a06082a8648ce3d0403033031310b300906035504061302555331143012060355040a130b48797065726c6564676572310c300a06035504031303746361301e170d3136303830383038353734325a170d3136313130363038353734325a303e310b300906035504061302555331143012060355040a130b48797065726c65646765723119301706035504030c106a696d5c62616e6b5f615c30303030343059301306072a8648ce3d020106082a8648ce3d03010703420004d7d3d9573a42b752faf9a57307e2adc5d8d94eb2f6ec341e89dcd5fbcc52f78b8bd85aed57a80371c79a4ae95cd1f9e6c520f4d98de659c95ae82810d5197b0fa381dc3081d9300e0603551d0f0101ff040403020780300c0603551d130101ff04023000300d0603551d0e0406040401020304300f0603551d2304083006800401020304304d06062a03040506070101ff04404e4ba64e7bd2be8e53ade8b4acf9bc0e8911196d6624418d7464499d8b4caf45b133271c0a2eb587872d578d5e68b12f7088a14cb60459c007288e0d6b8a41ee304a06062a03040506080440bb27869d69613f3b051b98b2018b2f212fb0a3f18911d99345a0bc6af1ed875db8b7b38f48d3a90f31c9b41e9f11d88f85a813a46065616fa97a4c11142c8f4f300a06082a8648ce3d0403030347003044022002fa157a7e2618ba517dd203089580916358cc5cc79774576cd60e4d77d9c583022048aae53949463b27fc6ade2c4181c525bda17c5958d0bc47161bd30d55376016`
chaincode_example02 log:
`cert`

The stub has some loss with executing invoke chaincode manually.

**Comment by christo4ferris** [comment]
@cophey we've transitioned to using [Gerrit](https://gerrit.hyperledger.org/r/#/admin/projects/) and [Jira](https://jira.hyperledger.org/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all) for development of the various Hyperledger projects.
