### ISSUE TITLE
Error when start pbft mode and create node

### ISSUE THREAD

**Issue by Abigale001** [hyperledger-archives/fabric#2393]
## Description

I want to test the chaincode_example02.go in my docker. But when I `docker-compose up` , I get following error.

> vp3_1  | 01:09:51.128 [peer] handleChat -> ERRO 0d4 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
> 
> vp3_1  | 01:09:53.055 [peer] ensureConnected -> WARN 0d5 Touch service indicates dropped connections, attempting to reconnect...
> 
> vp3_1  | 01:09:56.128 [peer] handleChat -> ERRO 0d6 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
> 
> vp3_1  | 01:09:59.056 [peer] ensureConnected -> WARN 0d7 Touch service indicates dropped connections, attempting to reconnect...

And I don't know why, so I ignore it and continue.

I typed

```
$ docker exec -it vp0 bash
$ peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
```

 I get following error.

> Error: Non-empty JSON chaincode parameters must contain exactly 1 key: 'Args'
## Describe How to Reproduce

I have search the error on google, and I only get answer of `Non-empty JSON chaincode parameters must contain exactly 2 keys: Function and Args`, that is, I can't find the source code of my error(exactly 1 key). I think it's so strange. 

Maybe my mistake is from the beginning where I typed `docker-compose up`. 

Anyone can help me? It got me crazy.

**Comment by Abigale001** [comment]
Now, I only get this error: `Error: Non-empty JSON chaincode parameters must contain exactly 1 key: 'Args'`. Anyone can help me?

**Comment by ashnur** [comment]
What was the solution for the "non-empty" issue?

**Comment by bingge1** [comment]
_

> `[# _**`_`funcion`****_`**_](

- [ ] @

- [1. url](

> [url](**url**)

)

)`

_

**Comment by LiangyuChan** [comment]
@Abigale001 May I ask you how do you solve the first "handleChat" error?
