### ISSUE TITLE
Occur path not found while deploy a new chaincode. 

### ISSUE THREAD

**Issue by mingjinc** [hyperledger-archives/fabric#2399]
## Description

I added a new chaincode in the folder github.com/hyperledeger/fabric/examples/chaincode/go, while I deploy it, it occurs not found error. How to resolve it?

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Deployment failure",
    "data": "Error when deploying chaincode: Path to chaincode does not exist: github.com/hyperledeger/fabric/examples/chaincode/go/newchaincode"
  },
  "id": 1
}

**Comment by mingjinc** [comment]
My environment is using Vagrant.

**Comment by smithbk** [comment]
Are you using the node.js SDK to deploy?  If yes, are you sure that github.com/hyperledeger/fabric/examples/chaincode/go/newchaincode directory exists on your client machine?

**Comment by mingjinc** [comment]
@smithbk , I am using REST API to deploy.
newchaincode is located in the directory /$GOPATh/src/github.com/hyperledeger/fabric/examples/chaincode/go

**Comment by smithbk** [comment]
@minginc Trying to contact you directly on slack or other but couldn't find you online, so I sent email to follow up.

**Comment by mingjinc** [comment]
@smithbk , I am online on ST now. Could you touch me now? Thanks.

**Comment by mingjinc** [comment]
@smithbk  Thanks a lot for your support. Has fixed now.

**Comment by raderio** [comment]
Any details here?

**Comment by liuwenru** [comment]
@mingjinc  i have the same problem , can you help me?
