### ISSUE TITLE
erro : Failed invoking CreateCertficatePair

### ISSUE THREAD

**Issue by bellaj** [hyperledger-archives/fabric#2411]
I've got the error below when i change the CORE_VM_ENDPOINT from unix:///var/run/docker.sock to any other address 127.* or 172.* or whatever

```
 19:22:34.267 [crypto] Debug -> DEBU 02c [validator.test_vp0]  Getting ECA client...done
 19:22:34.304 [crypto] Errorf -> ERRO 02d [validator.test_vp0] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = Identity or token does not match.].
 19:22:34.304 [crypto] Errorf -> ERRO 02e [validator.test_vp0] Failed getting enrollment certificate [id=test_vp0]: [rpc error: code = 2 desc = Identity or token does not match.]
 19:22:34.304 [crypto] Errorf -> ERRO 02f [validator.test_vp0] Failed retrieving enrollment data [rpc error: code = 2 desc = Identity or token does not match.].
 19:22:34.304 [crypto] Errorf -> ERRO 030 [validator.test_vp0] Failed registering node crypto engine [rpc error: code = 2 desc = Identity or token does not match.].
 19:22:34.304 [crypto] Errorf -> ERRO 031 [validator.test_vp0] Failed registering peer [test_vp0]: [rpc error: code = 2 desc = Identity or token does not match.]
 19:22:34.304 [crypto] Errorf -> ERRO 032 [validator.test_vp0] Failed registering [test_vp0]: [rpc error: code = 2 desc = Identity or token does not match.]
 19:22:34.304 [crypto] RegisterValidator -> ERRO 033 Failed registering validator [test_vp0] with name [test_vp0] [rpc error: code = 2 desc = Identity or token does not match.].
```

**Comment by Shreeparna** [comment]
Why was this discussion closed? Even i am getting the same error. Besides when i am trying to build the app2_internal.go, i get the following error:
app2.go:23:2: no buildable Go source files in /Users/Apple/Documents/go/src/github.com/hyperledger/fabric/core/crypto
app2.go:24:2: no buildable Go source files in /Users/Apple/Documents/go/src/github.com/hyperledger/fabric/protos

**Basically I am  trying to register new users. How do i do it? Get certificates for them?**
**Can you give some useful links?**

**Comment by lehors** [comment]
Hi,
the discussion was closed because we've moved from github to gerrit+jira. Please, see https://gerrit.hyperledger.org/r/#/admin/projects/fabric and https://jira.hyperledger.org/projects/FAB/issues
As for your question the basic answer is that you need to register and enroll the user. But you're welcome to join us on rocketchat and get live help from the community at: https://chat.hyperledger.org
Cheers.
Arnaud
