### ISSUE TITLE
Experiment and measure performance of crypto-hash computation

### ISSUE THREAD

**Issue by manish-sethi** [hyperledger-archives/fabric#245]
This issue is a break-up of #41 
Experiment with performance characteristics of crypto-hash computation (see #242 , #243 , and #244 ) with some synthetic data.

**Comment by ghaskins** [comment]
If it would be helpful, I could more formally submit the performance-measurement harness (https://github.com/ghaskins/rtt-go) that @srderson and myself put together.  Perhaps within obc-sandbox?

**Comment by srderson** [comment]
Hi Greg - yes, it would be interesting to test the different hash functions against our actual data structures. In utils.go there is a ComputeCryptoHash function. At some point we may choose to make the hash function this uses a configuration parameter.

**Comment by markparz** [comment]
Not required for Jan run-at
