### ISSUE TITLE
on timeout validator should rollback transaction

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#249]
Per discussion with @manish-sethi we will implement this via APIs to mark transaction boundary and rollback to be made available on ledger

**Comment by markparz** [comment]
Need to verify hooks from Ledger and work with Consensus to understand rollback.

**Comment by manish-sethi** [comment]
related issue - #122

**Comment by prjayach** [comment]
@markparz:  @manish-sethi and @muralisrini have completed this item. Can be closed in my opinion.

**Comment by markparz** [comment]
@prjayach Thanks Praveen, I think you are right.... want to verify
@muralisrini @manish-sethi Guys, do you agree? if so can you close? I want to make sure.

**Comment by manish-sethi** [comment]
@markparz yes, OK from my side. I'll let @muralisrini decide... I think he was planning to add some tests around this.

**Comment by muralisrini** [comment]
we have ledger tests from @manish-sethi outside of chaincode. I'll enhance existing tests in chaincode to check for state and then close this EOB

**Comment by markparz** [comment]
Thank you

**Comment by muralisrini** [comment]
Implemented additional negative testcase to test transaction state has been removed on transaction failure. Closing
