### ISSUE TITLE
Integrate Validator getID with the consensus package

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#252]
Use this commit as a starting point: https://github.com/openblockchain/obc-peer/commit/cc536b464442f95b1092633425d49b96ca98c414

**Comment by corecode** [comment]
How do we know the IDs of peers?

**Comment by tuand27613** [comment]
PeerEndpoint  struct has ID and Address.  Each peer has a map of all other endpoints, planning on using  method GetPeers() to get the list and retrieve the IDs.

Need to figure out where exactly in the code I should set the ID

**Comment by kchristidis** [comment]
Waiting to see the actual code in `memserv` before I close this.

**Comment by kchristidis** [comment]
Addressed in: `d81e3a86`
