### ISSUE TITLE
Peer should use stream for all API calls (including "self" calls in dev mode/validator mode)

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#253]
CLI deploy, invoke and query calls are grpc driven and land as a devops service call. Currently, the service directly drives chain code execution in devmode whereas in true "peer" mode (where the validator is on a different node) the grpc call is sent over a stream to the validator. We should not have two methods but just have one so we can leverage the full functionality on the pipeline(such as any security mechanisms we'd implement on the validator).

**Comment by muralisrini** [comment]
The code for this issue is complete (devops streams CLI grpc requests both "locally" (dev mode) or "remote" (non-validating peer mode). Will close it after making sure TestServer_Chat test case works (issue #256)

**Comment by markparz** [comment]
sprint 4, related to issue #300

**Comment by muralisrini** [comment]
TestServer_Chat test case (#256) is fixed. Plus this code has been in the works for a while. Closing
