### ISSUE TITLE
Implement Unicast

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#265]
The function signature should be: `Unicast(msg *pb.OpenchainMessage, receiver int)`

The required pieces for it are already in place; look for the `coordinator` and the `To()` function in `consensus/helper/handler.go`.

**Comment by corecode** [comment]
This is probably more of a communication stack issue than a consensus issue?

**Comment by kchristidis** [comment]
^^ Correct. (We'll be the ones coding it though.)

**Comment by binhn** [comment]
@jeffgarratt I believe this issue implmeneted in the msg handler send() function.  @kchristidis Anything else to be done here?

**Comment by kchristidis** [comment]
@binhn: I believe we need to be done with #382 first so that we can address a node by their cryptographic ID.

**Comment by kchristidis** [comment]
As things stand today, the [`handlerMap`](https://github.com/openblockchain/obc-peer/blob/299f124d62dd52bbce394f6ed070cdfe2844f94e/openchain/peer/peer.go#L162) is keyed by [the `peer.id` value](https://github.com/openblockchain/obc-peer/blob/8bed954ca9b7285336236926602c0a6f5b760777/openchain/peer/peer.go#L121) that we're reading from the `openchain.yaml` config file.

VPs and NVPs should be addressable [by their `IDs`](https://github.com/openblockchain/obc-peer/blob/cc5e58a0f346d989ff8c9b964f8b4a210adb5066/openchain/crypto/peer_impl.go#L41), i.e. [their hashed `rawEnrollCert`](https://github.com/openblockchain/obc-peer/blob/cc5e58a0f346d989ff8c9b964f8b4a210adb5066/openchain/crypto/node_keys.go#L149).

Have done the required changes to support this, and coded `Unicast()`.

#399 prevents me from testing; withholding on pushing until this is resolved.
