### ISSUE TITLE
Switch to an opaque interface for CPI

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#272]
- Use byte slices as arguments for the `CPI` functions
- Add a `Request()` method in the Consenter interface

Noting this down so that we don't forget, but it's probably best to start working on it once `noops` goes live.

**Comment by corecode** [comment]
I'll defer this until pbft is fully functional

**Comment by kchristidis** [comment]
Roger. Removing the "Spring 1" label.

**Comment by corecode** [comment]
Essentially implemented internally in pbft.
