### ISSUE TITLE
pbft: add client (requesting peer) timestamps

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#288]
PBFT `t`, `last-rep`, `last-rep-t` (`lrt`)

Needed in REQUEST messages and garbage collection of them.

**Comment by kchristidis** [comment]
Good one. Unless I'm mistaken, this shouldn't block us from developing view-change. If that's the case, we can tackle it when we have spare cycles during this sprint or the next one.

**Comment by kchristidis** [comment]
@corecode: Shall we put that in for Sprint 2?

**Comment by corecode** [comment]
I don't know.  We'll have to chat with @vukolic and the rest of the stack to understand who even can be a client, and what (stable) identity a client has.

**Comment by corecode** [comment]
We will have to deal with an essentially infinite number of clients.  Therefore maintaining state per client is unfeasible.  Instead, we will rely on the crypto layer to validate requests for authenticity and against replays.

**Comment by vukolic** [comment]
What we will need to do have per request (perhaps only in the worst case) is fairness timers per request. So, given a request that validator knows of, a validator needs timers to ensure that requests are committed and that the primary is not dropping the requests selectively (if such timer expires for a given requests - trigger view change). This does not hinge on client ids however.

**Comment by corecode** [comment]
Right.  These timers are the topic of #332.

**Comment by kchristidis** [comment]
What's the status of this issue then?

**Comment by corecode** [comment]
I think we can close this.
