### ISSUE TITLE
Create monitor web page off peer REST service

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#293]
We have REST API living off peer node https://github.com/openblockchain/obc-peer/blob/master/docs/Openchain%20API.md

The monitor would be like another URI off the same port  /stats, which will serve up the monitor if the ContentType="text/html"; otherwise it will return the json data structure containing the openchain network stats. The stats are pending #80, which @frankyclu is working on.

Contact @angrbrd (Anya) for more info on the endpoint mechanism.

**Comment by seanbarclay** [comment]
FYI- I'll be on holiday next week. Ping Meeta for support here

**Comment by seanbarclay** [comment]
Please create a label called "testnet" and another for "story". Then please either close the ticket, or remove the "sprint1" label (it can be closed at the conclusion of milestone 4). Thanks
