### ISSUE TITLE
Use godep or or gom to handle dependencies

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#30]
Currently, dependencies are listed in a file called Gomfile, but a developer must run 'go get' manually for each dependency. We need to
- [x] Pick a dependency manager that supports versions
- [x] Add all dependencies including versions

**Comment by binhn** [comment]
Can we do this during "vagrant up" so that we wouldn't have to run it manually? Could it be done with a sed command on the Gomfile

**Comment by srderson** [comment]
Yes, I agree we should add all `go get` commands to `vagrant up`. Some are already there like rocksdb. I will do this tomorrow.

**Comment by srderson** [comment]
Using https://github.com/kardianos/govendor to manage the vendor folder and the Go 1.5 vendor experiment
