### ISSUE TITLE
chaincode testcases need updating to take parameters to NewChaincodeSupport

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#306]
Chaincode support now takes a func parameter to get peer address. Need to modify test cases to accept the new param as well.

In addition, this approach to passing parameters should be done for other chaincode support parameters such as chaincode startup timeout, user runs chaincode etc. Currently these are global parameters and will hinder move to multichain environment. Will fix those as well as these are all related issues.

**Comment by binhn** [comment]
closed per @muralisrini
