### ISSUE TITLE
Query-only transaction architecture

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#31]
Imagine the following chaincode

```
chaincode {
   var x;
   function setA(v) {
      x=v;
   }
   function getA() {
      return x;
   }
}
```

The `setA` function modifies the state and a call to this function must be recorded on the blockchain as a transaction. The `getA` function does not modify the state and therefore does not need to be recorded on the blockchain as a transaction. There is also no consensus necessary because we can assume that the client trusts the peer it is calling.

Requiring chaincode developers or client developers to understand this subtlety leads to a great deal of confusion as we have observed in other smart contract blockchain implementations. If you are familiar with Ethereum, you know the developer is provided both a `sendTransaction` and `call` API depending on how they want the invocation to be handled. Ideally, this would be abstracted away from developers, allowing for just one API to invoke a chaincode function.

Proposed solution
1. A client calls a chaincode function via the API on a non-validating peer.
2. The non validating peer must send the transaction to a validating peer. Each non-validating peer communicates with exactly 1 validating peer.
3. The validating peer sends the transaction to a leader for block packaging.
4. The block packaging peer runs all transactions it has received.
5. If the transaction modifies the state, it is placed in the block's array of transactions.
6. If the transaction does not modify the state, it is placed in a discarded transaction data structure in the block [1] that contains 3 pieces of information. 1) The transaction 2) The order in which the transaction was run (after element N in the transactions array) 3) The reason why the transaction was discarded, in this case, the fact that it did not modify the state. Other reasons could be 'error' or 'invalid transaction.'
7. The block packager sends the block to the validating peers
8. Most validating peers can ignore the discarded transactions. However, in the case of the validating peer from step 3, it recognizes the transaction that it sent in step 3.
9. The validating peer runs the transaction in the correct order and responds to the client with the return value
10. All validating peers remove the discarded transaction structure from the block before adding the block to their blockchain.

[1] A peer may disagree with the reason for a transaction being discarded. For example, the leader may say the transaction does not modify the state, but the validator thinks it does modify the state. This is the same problem as a block packager choosing to ignore a transaction. In existing blockchain implementations, this problem is solved by paying a fee to the block packager, giving them an incentive not to ignore transactions. Because there is no coin in Openchain, there must be a way for a peer to alert other peers that a transaction is being ignored and obtain consensus that the transaction should be run in a future block.

**Comment by kchristidis** [comment]
We therefore need to add logic that determines whether a transaction changes the state or not. I like the proposed solution.

PS: When you say "discarded transaction data structure", do you maybe mean temporary/transient?

**Comment by srderson** [comment]
I mean transactions that we can remove from the block before adding it to the blockchain.

**Comment by binhn** [comment]
@muralisrini let's have this discussed in your chaincode services workgroup. I agreed with Sheehan argument that having 2 different APIs to run a function causing confusion, but it seems that's the most effective once understood. The proposed solution here doesn't sound efficient. 

We discussed the possibility of using some convention, like get\* on the function name will automatically result in a none transaction call, and any validator can serve the request without broadcasting to the rest. Would such model offer a sound solution?  How would the client send such requests?

**Comment by prjayach** [comment]
How about this - all state changes that a chaincode wishes to make are made via the validator (using gRPC). Validator provides a readState API that executes the chaincode to read state; during this time, validator does not accept requests from chaincode to update/delete state. This will by-pass transactions and consensus. In contrast, an executeTransaction API on validator will invoke a chaincode execution where state updates are allowed. Will discuss with @muralisrini and come up with a more fleshed-out proposal.

**Comment by srderson** [comment]
Instead of two APIs, I'd rather have one API with a flag to skip consensus. The default should be consensus. I think that's the best way to reduce confusion for new users. Once you know what you are doing, you can turn off consensus.

**Comment by prjayach** [comment]
Yes, sounds good. That should be workable.

**Comment by srderson** [comment]
Implementation is in issue #153
