### ISSUE TITLE
SetLevel for package-level loggers

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#310]
- [ ] Create package-level loggers
- [ ] Register them in `main.go`'s `Set.Level()` block

_If_ we agree that this is a good practice, can we adopt it? Should make debugging more manageable.

If it's not the best practice, feel free to edit this issue accordingly.

I need to be able to go through the logs while selectively silencing several packages.

**Comment by srderson** [comment]
I agree with this approach.

**Comment by binhn** [comment]
It would also be better if we can control it with both flags on command and specific CLI during runtime
