### ISSUE TITLE
Error on query tx when a VP disconnects with others

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#318]
Follow the instruction here 
https://github.com/openblockchain/obc-peer/blob/master/docs/DevnetSetup.md
to set up the test network of 2 VPs (172.17.0.2 and 172.17.0.3) then follow these steps to reproduce:

1) Deploy the sample chaincode as in the document
2) Send invoke and query tx's
3) Kill the first VP
4) Send a query tx to the 2nd VP

Result on CLI terminal:

vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.3:30303 ./obc-peer chaincode deploy -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -v 0.0.1 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
15:53:08.192 [main] chaincodeDeploy -> INFO 001 Build result: type:GOLANG chaincodeID:<url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" > ctorMsg:<function:"init" args:"a" args:"100" args:"b" args:"200" > 
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.3:30303 ./obc-peer chaincode query -l golang -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -v 0.0.1 -c '{"Function": "query", "Args": ["b"]}'
15:53:47.477 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" > ctorMsg:<function:"query" args:"b" > > 
15:53:47.478 [main] chaincodeInvokeOrQuery -> INFO 002 Trying to print as string: {"Name":"b","Amount":"200"}
15:53:47.478 [main] chaincodeInvokeOrQuery -> INFO 003 Raw bytes 7b224e616d65223a2262222c22416d6f756e74223a22323030227d
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode query -l golang -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -v 0.0.1 -c '{"Function": "query", "Args": ["b"]}'
15:54:09.093 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<url:"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02" version:"0.0.1" > ctorMsg:<function:"query" args:"b" > > 
15:54:09.095 [main] chaincodeInvokeOrQuery -> INFO 002 Trying to print as string: {"Name":"b","Amount":"200"}
15:54:09.095 [main] chaincodeInvokeOrQuery -> INFO 003 Raw bytes 7b224e616d65223a2262222c22416d6f756e74223a22323030227d
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.3:30303 ./obc-peer chaincode query -l golang -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -v 0.0.1 -c '{"Function": "query", "Args": ["b"]}'

Error querying chaincode: rpc error: code = 2 desc = "Error sending transactions to peer address=172.17.0.2:30303:  grpc: timed out trying to connect"

Result on 2nd peer 172.17.0.3

15:54:21.902 [peer] GetPeerEndpoint -> WARN 101 AutoDetected Peer address: 172.17.0.3:30303
2015/11/25 15:54:24 transport: http2Client.notifyError got notified that the client transport was broken EOF.
15:54:24.150 [peer] handleChat -> ERRO 102 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
15:54:24.150 [peer] DeregisterHandler -> DEBU 103 Deregistered handler with key: vp1
15:54:24.151 [peer] start -> DEBU 104 Stopping discovery service
2015/11/25 15:54:24 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2015/11/25 15:54:24 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2015/11/25 15:54:25 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: connection refused"; Reconnecting to "172.17.0.2:30303"
2015/11/25 15:54:25 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: connection refused"; Reconnecting to "172.17.0.2:30303"
2015/11/25 15:54:25 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: connection refused"; Reconnecting to "172.17.0.2:30303"
2015/11/25 15:54:27 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
2015/11/25 15:54:27 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
2015/11/25 15:54:27 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
15:54:39.505 [devops] invokeOrQuery -> DEBU 105 Sending invocation transaction (295843a8-e484-4e9b-922f-dd1f58e9f049) to validator

**Comment by muralisrini** [comment]
This may have been fixed by changes to peer.go done for the PR https://github.com/openblockchain/obc-peer/pull/325

**Comment by binhn** [comment]
it appears to have been fixed
