### ISSUE TITLE
Event Hub

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#32]
To enable integration with various systems, we need an event infrastructure that any components may emit events, and external or internal components may consume the events.

We need the following:
1. Define what events we want to produce
2. How to emit the events
3. What mechanism to deliver the events
### Events

The list of events may be added over time, but we may start with block-added, block-removed (rollback), chaincode-deployed.
### Event-Stream

Events are emitted on a gRPC stream from VP, where any gRPC client can listen to. An NVP may be an event client, who will listen to events from the connected VP. The event client implementation on NVP follows the adapter pattern such that a event-adapter may be plugged in to deliver the events to external systems.
### Event-Adapter

Event-Adapter implements gRPC stream receiver on one end and event delivery on the other end. Event delivery, such as [webhooks](https://en.wikipedia.org/wiki/Webhook), [Apache Kafka](http://kafka.apache.org) or [websocket](https://en.wikipedia.org/wiki/WebSocket), enables external systems to subscribe to interesting events.

**Comment by binhn** [comment]
I am assuming that POST /hook sent to a specific peer node and won't be further broadcast to the network, so that only 1 peer node would process that event hook. I think that's what is implied but just want to make sure.

**Comment by srderson** [comment]
Yes, that is correct. A client creates, deletes, and manages their hooks on a single peer.

**Comment by binhn** [comment]
move to sprint 3 as we've just agreed on a design

**Comment by binhn** [comment]
@muralisrini We need to rewrite this issue description per discussion. I'll attempt the first stab... 

I copied the previous description here for historical purposes and also keeping the design on webhook as a delivery mechanism for adapter:
The Event Hub provides [webhooks](https://en.wikipedia.org/wiki/Webhook) that clients can use to listen for events occur on the blockchain or state. Clients create a hook by specifying a URL and event type. When the event occurs, they are sent an HTTP POST payload from Event Hub with information about the event.

The Event Hub itself resides on each peer (both validating and non-validating) and uses the peer's local blockchain and state to watch for events.

Event examples that a client can create a hook for include
- Change in the state for a specified contract ID.
- Change in the state for a specified key and contract ID.
- Block added to the chain.

## Proposed REST API

### Create a new webhook

POST /hook
Body

```
{
    "url": "https://example.com/openchain_callback",
    "event_type": "state_change",
    "event_filter": {"contract_id": "foo", "key": "bar"}
}
```
- url: The URL that will be sent a POST with a payload when the specified event occurs. 
- event_type: The type of event. Valid events are `state_change` and `block_add`.
- event_filter:
  - For a `state_change` event, the `contract_id` is required and `key` is optional. If a `key` is not specified, a POST is sent for every state change in the specified contract.
  - For a `block_add` event, there will be no `event_filter` option. The entire block will be sent in the payload. In the future, we will likely want to offer filters for this event type.

Response

```
{"hook_id": "23"}
```

### Delete an existing webhook

DELETE /hook/:id

## Hook payload examples

### state_change

POST

```
{
   "contract_id": "chain://contract8",
   "key": "pet",
   "event_type": "update",
   "new_value": "dog",
   "old_value": "cat"
}
```
- contract_id: The contract ID for which the state was modified.
- key: The key that was modified.
- event_type: Valid values are create, update, and delete.
- new_value: The key's new value.
- old_value: The key's old value.

### block_add

POST

```
{
   "block_number": 5,
   "transactions": [...],
   "state_hash": "dj32jx",
   "previous_block_hash: "wlkjsf324"
}
```
- block_number: The number of the block that was added.
- transactions: An array of transactions in the block.
- state_hash: The hash of the state for this block.
- previous_block_hash: The hash of the previous block.

## Future

The above two APIs are just to get started. In the future we will need
- Authentication when creating a hook.
- Ability to list all hooks for the current user.
- Ability to edit a hook.
- Ping event after a hook is created.
- A UI for creating hooks.
- Ability to turn a hook on/off.
- Ability to get a specific hook by ID.
- Additional events and filters.

This API is inspired by [GitHub webhooks](https://developer.github.com/webhooks/) which we should look to as an example for building a great webhook API.

**Comment by muralisrini** [comment]
Implementation of events framework completed. It is basically a pub/sub model with validator being the producer of events.

A grpc client on the consumer receives events. The consumer specifies an "adapter" to
- specify interests on events (one time at the time of handshake)
- receive events from consumer

The "events" property in openchain.yaml exposes properties for the events system on the producer side (validator).
