### ISSUE TITLE
Clear requests from earlier views in view-change

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#324]
When we're sending a `view-change` message, we have to clear from the `reqStore` all the messages that correspond to earlier views.

We cannot do that today since the `reqStore` simply maps digests to `Request` Messages.

One solution could be to change the `reqStore` definition to a `map[view]hashReqPair` where `hashReqPair` is a `digest string, req *Request` structure.

**Comment by vukolic** [comment]
In fact clearing msgs should happen only after a stable checkpoint, not after sending view-change msg (see Fig. 22 of the PBFT TOCS paper)

**Comment by kchristidis** [comment]
@vukolic: Correct, lazy typing on my part above. We have a placeholder in our current code for request clearing that happens exactly at the point that you suggest.
