### ISSUE TITLE
errors from within chaincode should not be treated as "Success"

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#329]
When  a transaction is executed, 3 results are possible : 
- error/nil-response
- successful completion from chaincode with response
- error completion from chaincode with response. 

The first two categories are handled correctly with 500 error code and 200 error code respectively.  The last category also reports 200.  This should report a non-200 error code (501?) so APIs can report correctly

**Comment by prjayach** [comment]
@angrbrd Can you confirm that this is fixed? We are returning error from chaincode correctly after my PR #326

**Comment by muralisrini** [comment]
@angrbrd confirmed bad query returns error correctly. @angrbrd did note that that as invoke does not actually run the transaction but just submits and returns the transaction uuid, results of an incorrect invoke would have to be obtained via a separate call.
