### ISSUE TITLE
Handle timeouts correctly for chaincode invocation and query

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#330]
Currently timeout for chaincode invocation and query is hard-coded. We need to do the following:
1. When a chaincode is invoked as a transaction or query, we need to fetch the deploy transaction for the chaincode and get the timeout value.
2. When a chaincode invokes another chaincode, the timeout for the invoked chaincode needs to be set to the timeout of the calling chaincode or that of the invoked chaincode, whichever is smaller.

**Comment by muralisrini** [comment]
talked to @srderson about this..

chaincode.getTimeout(chaincodeid) will get the time out using ledger functions. However it is dependent on transaction existing on block to fetch the code for the transaction. Chaincode cannot use getTimeout till commit is complete in noops and PBFT.

Moving this to a next sprint 3 for now.
