### ISSUE TITLE
Timers to ensure liveness

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#332]
I think we need these two to begin with:
- [x] A backup starts a timer when it receives a request and the timer is not already running. It stops the timer when it is no longer waiting to execute the request, but restarts it if at that point it is waiting to execute some other request.
- [x] To avoid starting a view change too soon, a replica that multicasts a `VIEW-CHANGE` message for view `v+1` waits for 2f+1 `VIEW-CHANGE` messages for view `v+1` before starting its timer. Then, it starts its timer to expire after some time T. If the timer expires before it receives a valid NEW-VIEW message for v+1 or before it executes a request in the new view that it had not executed previously, it starts the view change for view v+2.

@corecode, @vukolic: feel free to add more timers here, or correct the ones listed above.

For this milestone, let's not worry about optimizing the timer values. Responsiveness may not be optimal, but that's OK.

**Comment by corecode** [comment]
Need to check with the rest of the stack if we can call it from a timer context (goroutine).

**Comment by corecode** [comment]
Timer work partially done in d239859.

**Comment by kchristidis** [comment]
Great, left some comments on that commit for the second timer.

For the first timer, I'd argue that it should be set right after receiving the `CHAIN_TRANSACTION` message. Or better yet, right after `Broadcast()`-ing this `CHAIN_TRANSACTION` message (wrapped in an `OpenchainMessage_CONSENSUS` message)  to the network of VPs. What do you say?

**Comment by corecode** [comment]
That's not sufficient.  All replicas need to run a timer, so that they all can trigger a view change.  I'll have to think about how to determine whether there are outstanding requests.

**Comment by kchristidis** [comment]
Hm, not sure how this contradicts what I wrote above. What am I missing when parsing the  "when it receives a request" clause from the paper?

**Comment by corecode** [comment]
Only one replica broadcasts the `Request` message (acting as proxy for the client).  The other replicas only receive the `Request` and don't broadcast.

**Comment by kchristidis** [comment]
Got it, it'll need to be handled differently then.

**Comment by corecode** [comment]
Request timers in 841b6aa.
