### ISSUE TITLE
Consensus should use the BeginTxBatch/ExecTXs/CommitTxBatch scheme

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#340]
We should switch to this scheme to have the blockchain and state updated:
1. `ledger.BeginTxBatch()`
2. `chaincode.ExecuteTransactions()`
3. `ledger.CommitTxBatch()`
4. `ledger.RollbackTxBatch()`

**Comment by corecode** [comment]
Most certainly `cpi.ExecTXs` should take care of the begin/exec/commit sequencing?

**Comment by muralisrini** [comment]
Currently chaincode.ExecuteTransactions called by ExecTxs returns the hash and error array for the transactions. Do you need anything else ? For instance we could return transaction payload (bytes).

**Comment by kchristidis** [comment]
@corecode: Yes, `chaincode.ExecuteTransactions()` what I was going for in item 2 of the list above; updated.

**Comment by binhn** [comment]
We keep the transaction scope outside of transaction execution for flexibility. We know our implementation of byzantine behaves this way, but other plugins might want to call execTXs a bunch before wrapping the transaction scope.

**Comment by kchristidis** [comment]
Code added in: `da45ede2`.

Commented out for now cause it'll break our unit tests, but it's good to go.

**Comment by kchristidis** [comment]
In `2d2e14f5`, uncommented, and added to CPI.
