### ISSUE TITLE
Write view-change logic

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#341]
As described in the appendix of [the TOCS paper](http://research.microsoft.com/en-us/um/people/mcastro/publications/p398-castro-bft-tocs.pdf), with the modifications RE: `view-change-ack` that @vukolic suggested.

**Comment by kchristidis** [comment]
This is taken care of in #343.

**Comment by corecode** [comment]
Let's keep this open to remind us to add cryptographic signatures + checks.

**Comment by corecode** [comment]
On second thought, let's close this now that we have #273.
