### ISSUE TITLE
Implement SIEVE

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#348]
Modify the PBFT implementation according to the protocol that @vukolic and Christan have suggested.

**Comment by ghaskins** [comment]
Is ND-PBFT documented somewhere?

**Comment by vukolic** [comment]
Not yet (it will be soon). It is however, sketched in Sec 4.6 of PBFT OSDI paper (not TOCS), and will roughly look similar to Eve (Kapritsos et al., OSDI'12).

**Comment by corecode** [comment]
Implemented in 8d1b015

**Comment by corecode** [comment]
Still some liveness/correctness issues to resolve with the protocol.

**Comment by kchristidis** [comment]
#291 and #452 still open, but the protocol has been turned into code and merged with the master branch in PR https://github.com/openblockchain/obc-peer/pull/472. Closing this.
