### ISSUE TITLE
Add field to block for consensus to store additional data

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#349]
An additional field needs to be added to the block for consensus to store additional data. For example, this is needed by PBFT consensus to store the PBFT sequence number in the block.

@kchristidis Can we just provide a string field or array of bytes?

**Comment by srderson** [comment]
@vukolic @corecode Please add any additional details that I may have missed.

**Comment by kchristidis** [comment]
@srderson: We're using b64-encoded strings.

**Comment by corecode** [comment]
opaque `[]byte` or `string` is good.

**Comment by binhn** [comment]
We should also think about if any stats important to keep them readily available without much additional work. For example, the cumulative number of transactions since genesis, number of chaincodes = number of deploying transactions, etc.

**Comment by srderson** [comment]
Added as a []byte.
