### ISSUE TITLE
Implement TxVolume API

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#354]
The testnet monitor UI will display transaction volume on the network. This issue is to implement the TxVolume API and REST endpoint to return the transaction volume recorded on a peer node.

TxVolume(startTime, endTime, interval), where endTime (currently) will be the present moment, startTime is some time before the present moment, and interval is either in minutes, hours, or days. Maximum duration for minute interval is 1 hr, for hour interval is 24 hrs, and for day is 7 days or a week.

Must walk backwards through the blockchain, starting at the head until startTime. Count up the number of transactions in each interval. Return an array of intervals and transaction count in each interval.

**Comment by binhn** [comment]
@srderson @manish-sethi Is there a better way to do this than what @angrbrd described here? I ask because I thought of the way we store the data in db might help such time-based query

**Comment by angrbrd** [comment]
@srderson @manish-sethi @binhn 

As I described in #353 , this data would likewise be computed by the statistics service in the background. The statistics service would be notified whenever a new block is committed to the blockchain to update the statistics data currently stored in memory.

I propose we compute the volume as total number of transactions for the total duration of 1 hr, 1 day, and 1 week. The user would be able to modify the UI view to either display the data for the hour, the day, or the week, by modifying the graph unit through a drop down box or similar.

If the UI view is set to per hour, we may keep track of total number of transactions for some number of minutes. I think doing it every minute is too granular, considering blocks may not even be available every minute and we are not expecting massive numbers of transactions. We could do every 2 minutes, 5 minutes or even 10 minutes for example. For the day view we could display the total number of transactions within an hour for each of the 24 hrs. And for the week view, we can display the total number of transactions for each day of the week. For a REST call that would be returned as an array of interval:value pairs.

Please let me know what you think. Thanks.

**Comment by srderson** [comment]
I think 1 hour, 1 day, and 1 week is reasonable to start.

**Comment by angrbrd** [comment]
Issue #393 must be completed first before this one may be addressed.
