### ISSUE TITLE
Implement ChaincodeVolume API

### ISSUE THREAD

**Issue by angrbrd** [hyperledger-archives/fabric#355]
The testnet monitor UI will display transaction volume on the network for the top 4 or 5 chaincodes. This issue is to implement the ChaincodeVolume API and REST endpoint to return the transaction volume recorded on a peer node for the top N chaincodes.

ChaincodeVolume(last X seconds, top N chaincodes), where X is the number of seconds leading up to the current moment, and N is the top number of chaincodes to display.

Must walk backwards through the blockchain, starting at the head until X has passed. Count up the number of transactions for each chaincode. Maximum X is 1hr = 3600 seconds. Return an array of chaincode name and volumes.

**Comment by binhn** [comment]
@srderson @manish-sethi Is there a better way to do this than what @angrbrd described here? I ask because I thought of the way we store the data in db might help such time-based query

**Comment by angrbrd** [comment]
@srderson @manish-sethi @binhn 

As described in both #353 and #354 , this data would likewise be computed by the statistics service in the background. The statistics service would be notified whenever a new block is committed to the blockchain to update the statistics data currently stored in memory.

The UI needs to display a ranked list of approximately 5 chaincodes that have incurred the most transactions for some period of time going back. I suggest we stick to a similar approach as in #353, where we put the limit at 1 hour and compute the transaction volume per chaincode for the following intervals: 10 sec, 30 sec, 1 min, 10 min, 30 min, 60 min. This data could be kept for the top maybe 10 or 20 most active chaincodes internally and the UI can decide how many it wants to display.

Please let me know what you think. Thanks.

**Comment by angrbrd** [comment]
Issue #393 must be completed first before this one may be addressed.
