### ISSUE TITLE
Transaction success rate

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#359]
On the monitor, we want to show the success rate of the transactions on a VP over a period of time. 
This might be calculated as  100*(number of committed TXs)/(number of executed TXs).  We have this data between the Ledger and the Chaincode shim layer. 

@srderson @manish-sethi @muralisrini @prjayach Is there anything related to this recorded on the blocks that we may use?

**Comment by angrbrd** [comment]
@srderson @manish-sethi @muralisrini @prjayach

If I understand correctly, the number of committed TXs is just the number of transactions in the last committed block. Could one of you who has more knowledge of how to obtain the number of executed (or started) transactions let me know where I may find that information? I am not sure where to start looking.

Thank you!

**Comment by prjayach** [comment]
If we have #328 in place, where we maintain error transactions separately, we should be able to handle this. For each block, we will have the successful txs and the failed txs. This should be sufficient for the monitor to query and find out. ExecTransactions returns error from transaction execution - we just need to capture it within the block.
If we want to optimize for interval queries, we can have the ledger maintain additional info perhaps?

**Comment by angrbrd** [comment]
@srderson and @prjayach 

If I understand correctly, #328 will introduce an additional field within the Block message structure to hold all the transactions that have failed. The Block structure below (in openchain.proto) will be modified accordingly.

message Block {
    string proposerID = 1;
    google.protobuf.Timestamp Timestamp = 2;
    repeated Transaction transactions = 3;
    bytes stateHash = 4;
    bytes previousBlockHash = 5;
}

In that case, it will be as easy as determining the number of the "transactions" entries and the "failedTransactions" elements and computing the success rate based on these two numbers. Please correct if this is not accurate. I do not believe we need to do this for specific interval queries, at least not at this time. We could compute the running success rate for each validating peer by incorporating the values of successful and failed transactions for each newly committed block into the existing value. Basically, computing the success rate across all blocks. I think that should be sufficient at this time.

Please keep me posted per the status of #328.
Thanks!

**Comment by angrbrd** [comment]
Issue #393 must be completed first before this one may be addressed.
