### ISSUE TITLE
Support different scenarios of when a chaincode is executed

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#36]
This relates to how/when a call to execute a particular chaincode is made.

I see 3 scenarios (there could be more):
1. A peer requests execution of a chain code - this is the simplest case
2. An external event is the trigger for chain code execution (the authority to initiate execution of the chain code does not reside with one peer) - for instance, time triggered
3. A set of peers need to sign (possibly at different times), and once all have signed off the chaincode executes 

At the time of deploying a chaincode, we also need a way to specify rules for how/when the chaincode is to be executed.

**Comment by binhn** [comment]
@prjayach @muralisrini This one doesn't look like an executable issue. Would you mind rewriting it or close if no longer applicable?  All 3 cases, I see, at the end, a tx invoke will be carried out.

**Comment by prjayach** [comment]
The cases are applicable if at some point we support events natively. An event can be a signed message that signifies a real-world occurrence (e.g., shipment delivery). Multiple contracts may be interested in an event and may trigger transactions based on them. I think this will greatly simplify development of smart contracts, as events are a fundamental notion in any smart contract. With this support, a smart contract can just say 'On event E, invoke chaincode X'; no single entity will be in charge of invoking the transaction, but the system as a whole will automate that execution.

**Comment by prjayach** [comment]
To continue the shipment example, when shipment is completed (an event occurs), neither the buyer nor the seller needs to explicitly invoke the payment transaction. It will be automatically triggered; in fact, neither the buyer nor the seller will have the ability to refuse initiation of the payment transaction once the contract has been agreed upon and deployed on the ledger.

**Comment by binhn** [comment]
@muralisrini it can't go to milestone 2, which has been over 2 weeks ago. I am putting this issue back to backlog until someone can work on it. It is not MVP
