### ISSUE TITLE
Need to support output consensus

### ISSUE THREAD

**Issue by ghaskins** [hyperledger-archives/fabric#364]
Consensus algorithms such as PBFT tend to be structured as "agree-execute" algorithms, where the total order of messages/events is negotiated but the result of processing those events is assumed deterministic.  Certain use cases mandate that the result of execution needs to be included in the consensus as well (often referred to as "execute-verify" algorithms).  We need to ensure that execute-verify can be supported as an abstract mode of operation, even if only certain consensus plugins implement it.

**Comment by kchristidis** [comment]
Thanks for creating this issue Greg. Let's keep tabs on the progress of `Sieve` (#348) to see if it matches exactly what you're asking for.

And if not, given that consensus is a pluggable framework, we will use this issue to make sure we can plug in the module with the implementation you are referring too.

**Comment by kchristidis** [comment]
@ghaskins Does Sieve (whose source code you've checked I think) satisfy this requirement?

**Comment by ghaskins** [comment]
Greetings @kchristidis.  I haven't had a chance to review the implementation, but I believe it does yes.  I'll try to do a review of the actual implementation to make sure its consistent with my understanding.

**Comment by vukolic** [comment]
With inclusion of Sieve on the main fork few days ago (obcpbft/obc-sieve.go), I believe we can close this one.

**Comment by kchristidis** [comment]
Done.

**Comment by ghaskins** [comment]
better late than never:  I finally got around to reviewing the impl.   It does in fact seem to support the basic notion of execute-verify so I agree that closing this is the right thing to do.  Thank you
