### ISSUE TITLE
Allow chaincode to get both committed and dirty state

### ISSUE THREAD

**Issue by prjayach** [hyperledger-archives/fabric#366]
State API allows read of both committed and dirty state. We should expose this to the chaincode. Advice developer that query should ideally only fetch committed state.

**Comment by corecode** [comment]
Is this about chaincode query or chaincode invoke?

Is "dirty state" the current state as modified by the current chaincode, or the state as modified by all chaincodes in the current transaction block?

Probably the state a "invoke" chaincode requests should be the mutated state, while a "query" chaincode must only see the committed state.
