### ISSUE TITLE
Add utility to verify blockchain correctness

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#367]
Since many consumers will want to test for faults in replicating the blockchain (whether they be byzantine nodes, disk errors, network errors, or some other failure), verifying the correctness of the blockchain is likely to be a common operation.

Therefore, we need a utility function which will perform this verification.

The verification should proceed as follows.
1. Take as a parameter the block index to verify from (call it the 'current block')
2. Compute the hash of the current block's previous block.
3. If the current block's `Block.PreviousBlockHash` does not match that hash, return failure and the index of the failed block.
4. If the previous block is the genesis block (whose hash was just verified), return success.
5. Proceed from 2. with the previous block as the 'current block'.

In utilizing this new function, the caller would typically invoke the function with the latest block as a parameter.  If the blockchain does not verify successfully, it would then retrieve a new copy of the block at the failed index, and then invoke the function once more at index faulty+1.  This would repeat until the function returned success.

This was discussed with @srderson and @kchristidis and is necessary to implement issue #299 .

**Comment by jyellick** [comment]
For efficiency, we should probably add a second parameter, the block number to verify through.  In the scenario that a replica has verified its blockchain integrity through block number n, and synchronizes to block n+m, it should be unnecessary to check the full chain, instead, only the integrity from n+m through n is necessary.  Essentially treating block n as the genesis block.

**Comment by srderson** [comment]
Complete. See ledger.VerifyChain
