### ISSUE TITLE
Deploy chaincodes as they are needed

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#372]
It may be possible that a transaction requires a chaincode that is in a previous transaction, but not deployed on the local system. This is because synchronization between peers may transfer the full state or state deltas without actually running transactions.

In these cases, the chaincodes should be deployed as they are needed.

**Comment by prjayach** [comment]
@srderson We do start the chaincode container for each transaction invocation, if its not already running (to handle container crash issues). I think this case will be covered.

**Comment by srderson** [comment]
Say I invoke a chaincode with the ID 'foo' and the version '1.0'. Now, the peer needs to find the chaincode associated with this ID and version which is in a deploy transaction so we need a mapping of ID/version to transaction UUID. I see where this lookup is performed in exectransaction.go using the key 'github.com_openblockchain_obc-peer_chaincode_id'. However, I can no longer find where it is set in the state. Does that code still exist somewhere or was it removed?

**Comment by prjayach** [comment]
You are right. If the container has been started once before and needs to be restarted, we do that. If the container has never been started, we need to build the image again by looking at the deploy transaction. We are yet to do this - we also need to handle #202 when we do this.
Yes, I believe we have lost the code that inserted this in the state. @muralisrini can you confirm?

**Comment by muralisrini** [comment]
@srderson , @prjayach , to summarize, two things need to be done
1. do the SetState code that got lost when we moved away from validator.go  
   ![image](https://cloud.githubusercontent.com/assets/14361488/11692328/080f76f2-9e6d-11e5-8056-381de8a17b38.png)
   This will make sure we can find the "deploy transaction" if we need to resurrect the image from scratch
2. build the image from scratch when needed. Two immediate cases for this
   - when a node syncs and discovers new chaincodes to be built
   - when image gets destroyed for some reason (ie, if starting a container fails, we'd need an additional check-image-retry step)

(1) can be done immediately but would need (2) to make use of it. 
(2) is dependent upon the commit/sync work

Can you confirm the above ? Will then create issues for them.

**Comment by srderson** [comment]
Yes, that looks correct.

**Comment by binhn** [comment]
I move this issue to sprint4 as we need it to complete our sync process

**Comment by muralisrini** [comment]
I'm going to break this, out into two parts
- store chaincode ID <->  deploy transaction UUID map
- ability to build chaincode image from scratch when necessary

**Comment by muralisrini** [comment]
This issue will be used to handle the "ability to build chaincode image from scratch when necessary"
