### ISSUE TITLE
Combine DB path and crypto path

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#375]
Currently the DB path is defined in openchain.yaml by peer.dbPath. A yaml in the crypto folder defines the crypto path with client:crypto:path. These should be combined into one setting.
- In openchain.yaml, create a peer.fileSystemPath
- Set the default file system path in openchain.yaml to /var/openchain/production
- The DB should write to [peer.fileSystemPath]/db
- Crypto should write to [peer.fileSystemPath]/crypto
- Test cases should use /var/openchain/test

**Comment by binhn** [comment]
@adecaro Have you implemented this one for obcca ?  The current code still stores on ./

**Comment by adecaro** [comment]
I think this issue can be closed, right?

**Comment by srderson** [comment]
It's complete on the DB side, so if the crypto side is now complete, yes.

**Comment by binhn** [comment]
yes completed
