### ISSUE TITLE
Crypto errors when starting up VP with security enabled

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#384]
Procedure to reproduce:
- get the current code and set the security.enabled = true in openchain.yaml;  also change id and secret as appropriate
- start obcca server
- start obcpeer  ./obc-peer peer --peer-chaincodedev
- error below:
  22:32:21.495 [main] serve -> DEBU 002 Running as validator - installing consensus noops
  22:32:21.497 [CRYPTO] RegisterValidator -> INFO 003 Registering [nepumuk] with id [nepumuk]...
  22:32:21.499 [CRYPTO] register -> ERRO 004 Failed ini configuration [nepumuk]: Property not specified in configuration file. Please check that property is set: validator.crypto.path
  22:32:21.500 [CRYPTO] RegisterValidator -> ERRO 005 Failed registering [nepumuk] with id [nepumuk]: Property not specified in configuration file. Please check that property is set: validator.crypto.path
  22:32:21.503 [chaincode] NewChaincodeSupport -> INFO 006 Chaincode support using peerAddress: 0.0.0.0:30303

Further investigation, it looks like the code is expecting properties that are not defined in openchain.yaml

@angrbrd

**Comment by adecaro** [comment]
I gave a look at the issue. It is related to Issue #375 for which I have just submitted a PR with the fix.

Now, to setup security you need to following properties on the peer side (valid for the client, peer and validator)

```
peer:
    pki:
          eca:
              paddr: localhost:53051
          tca:
              paddr: localhost:53551
    fileSystemPath: /var/openchain/production
```

On the obcca side you need to configure the enrollment for all the parties
you need. The configuration goes as follow:

```
eca:
        users:
                # enrollID: enrollPWD
                nepumuk: 9gvZQRwhUq9q
                jim: AwbeJH2kw9qK
                lukas: NPKYL39uKbkj
```

**Comment by binhn** [comment]
@adecaro I am not clear.  Are you saying we need to define these properties in the openchain.yaml file to set up security?  
We currently have peer.fileSystemPath,  so we need:
1)  peer.pki.eca.paddr = localhost:53051
2)  peer.pki.tca.paddr = localhost:53551
I am guessing the hierarchical order since your text above doesn't come with the indentation.

Should the port be the same as the one defined in obcca.yaml?

```
ports:
        ecaP: ":50051"
        ecaA: ":50052"
        tcaP: ":50551"
        tcaA: ":50552"
```

**Comment by adecaro** [comment]
You are right. You need also those properties set. Don't forget to setup also the obcca.
Sorry for the missing indentation. Now, it should be more clear.

**Comment by binhn** [comment]
i am not sure how it works in docker container when the IP is dynamically assigned.
We need to talk with @jeffgarratt on how the peer handles the discovery of IP as I don't see localhost being used in yaml.

**Comment by binhn** [comment]
It's a bit better, but I still see errors. Here is my set up (I merged the PRs that you can pull to run this scenario):

openchain.yaml:

```
    # PKI member services properties
    pki:
        eca:
            paddr: localhost:53051
        tca:
            paddr: localhost:53051

security:
    enabled: true
    enrollID: nepumuk
    enrollSecret: 9gvZQRwhUq9q
    privacy: false
```

obcca.yaml

```
ports:
        ecaP: ":53051"
        ecaA: ":50052"
        tcaP: ":53551"
        tcaA: ":50552"
```

Start up obcca and obcpeer

```
$ ./obc-ca
INFO: 2015/12/13 16:14:49 new CA, creating database, key pair, and certificate
INFO: 2015/12/13 16:14:49 ECA started.
INFO: 2015/12/13 16:14:49 TCA started.
```

```
$ ./obc-peer peer --peer-chaincodedev
16:16:00.301 [main] serve -> DEBU 001 In chaincode development mode [consensus - noops, chaincode run by - user, peer mode - validator]
16:16:00.302 [main] serve -> DEBU 002 Running as validator - installing consensus noops
16:16:00.303 [CRYPTO] RegisterValidator -> INFO 003 Registering [nepumuk] with id [nepumuk]...
16:16:00.304 [CRYPTO.validator.nepumuk] register -> INFO 004 Registering [nepumuk]...
16:16:00.322 [CRYPTO.validator.nepumuk] retrieveECACertsChain -> INFO 005 Register:ECAcert MIIBwTCCAUegAwIBAgIBATAKBggqhkjOPQQDAzApMQswCQYDVQQGEwJVUzEMMAoGA1UEChMDSUJNMQwwCgYDVQQDEwNPQkMwHhcNMTUxMjEzMTYxNDQ5WhcNMTYwMzEyMTYxNDQ5WjApMQswCQYDVQQGEwJVUzEMMAoGA1UEChMDSUJNMQwwCgYDVQQDEwNPQkMwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAStfrFbkIsI9aDo1/SHseE3JiNX8dCe+wSSXSfdVcTqb0D2JtH1wZfnqKCnk6Wcycr+PnvSItlVnGFQQlILQGM74Z5XoybWUgmzJYi5hOjKO7ORrii7WkuNHL+HjatGjhajQzBBMA4GA1UdDwEB/wQEAwIHgDAPBgNVHRMBAf8EBTADAQH/MA0GA1UdDgQGBAQBAgMEMA8GA1UdIwQIMAaABAECAwQwCgYIKoZIzj0EAwMDaAAwZQIxAIkqS71HF8FpVbftxNpui/C4hWnnSFjezE79N6LlYTAp/7VRwiSqVcsgb3Ov4XfTFgIwWWM26RR08SBagWBYrefCxnOwejlsv4nq5v+oxlFpn1tM6THnN8GJR01REvlVCdjy
16:16:00.324 [CRYPTO.validator.nepumuk] retrieveECACertsChain -> INFO 006 Storing ECA certificate for validator [nepumuk]...
16:16:00.325 [CRYPTO.validator.nepumuk] getTCACertificate -> INFO 007 getTCACertificate...
16:16:00.326 [CRYPTO.validator.nepumuk] callTCAReadCertificate -> ERRO 008 Failed requesting tca read certificate: rpc error: code = 12 desc = "unknown service protos.TCAP"
16:16:00.327 [CRYPTO.validator.nepumuk] getTCACertificate -> ERRO 009 Failed requesting tca certificate: rpc error: code = 12 desc = "unknown service protos.TCAP"
16:16:00.327 [CRYPTO.validator.nepumuk] retrieveTCACertsChain -> ERRO 00a Failed getting TCA certificate rpc error: code = 12 desc = "unknown service protos.TCAP"
16:16:00.327 [CRYPTO.validator.nepumuk] register -> ERRO 00b Failed retrieveing ECA certs chain: rpc error: code = 12 desc = "unknown service protos.TCAP"
16:16:00.327 [CRYPTO] RegisterValidator -> ERRO 00c Failed registering [nepumuk] with id [nepumuk]: rpc error: code = 12 desc = "unknown service protos.TCAP"
16:16:00.328 [chaincode] NewChaincodeSupport -> INFO 00d Chaincode support using peerAddress: 0.0.0.0:30303
16:16:00.329 [db] createDBIfDBPathEmpty -> DEBU 00e Is db path [/var/openchain/production/db] empty [false]
16:16:00.338 [buckettree] Initialize -> INFO 00f Initializing bucket tree state implemetation with configurations &{maxGroupingAtEachLevel:10 lowestLevel:5 levelToNumBucketsMap:map[2:11 1:2 0:1 5:10009 4:1001 3:101] hashFunc:0x927910}
16:16:00.339 [server] NewOpenchainServer -> INFO 010 
Creating new OpenchainServer...
16:16:00.341 [main] serve -> INFO 011 Starting peer with id=name:"jdoe" , network id=dev, address=0.0.0.0:30303, discovery.rootnode=, validator=true
```

**Comment by adecaro** [comment]
Yes. This is a configuration issue. 

paddr: localhost:53051

should be

paddr: localhost:53551

**Comment by adecaro** [comment]
Okay, once the configuration is fixed. You will see an error related to sqlite3.
It is fixed by adding this import

_ "github.com/mattn/go-sqlite3"

to the file: node_ks.go

What's strange is that this error doesn't show up executing the tests. Really annoying.

I will issue a new PR just to fix this issue.

**Comment by adecaro** [comment]
Issue can be closed!
