### ISSUE TITLE
Ability to configure state storage implementation

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#385]
There are currently two state storage implementations

1) Bucket tree #244 
2) Trie #243 

Currently, OBC is hard coded to use the bucket tree. We should add a configuration setting that allows us to choose an implementation before the genesis block is created.

We need to decide
1) Should this be a configuration setting managed by the user?
2) What recommendations do we provide?

These questions may be answered by issue #245

**Comment by binhn** [comment]
Do we have an explanation/recommendation of when to use bucket versus trie?  And which should be the default?

**Comment by srderson** [comment]
Not yet. See issue #245. The default is currently the bucket tree.
