### ISSUE TITLE
Consensus abstraction framework

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#39]
Create a consensus framework to process all consensus related messages from peer. Also provide access functions to the consensus algorithms.

**Comment by srderson** [comment]
This seems to be a catch all issue. Can we close because we have more specific issues?

**Comment by binhn** [comment]
Our current abstraction is not what we want but gets the work done, so we need to refactor to have a clear abstraction layer to plug other consensus algo's. We can close this as part of milestone 2, and open a new one for milestone 3 on refactoring of the consensus implementation
