### ISSUE TITLE
produce block events 

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#392]
The events framework will be merged shortly. We need to use the producer.Send API to send block events

**Comment by srderson** [comment]
Should we emit block events during sync? I vote yes, but just wanted to hear other's opinion.

**Comment by muralisrini** [comment]
I'm not sure.... wouldn't the monitor think of them as new transactions ? for example, it would influence the transaction rate for peer - computed based on syncing as opposed to live block creation. 

Or does the block contain some structure that differentiates a sync from a creation ?

**Comment by srderson** [comment]
There is no differentiator in the block today.

**Comment by binhn** [comment]
@srderson I agreed with emitting the event every time we get a block, whether from sync or self create. This is important since some adapters (analytics) might want to accumulate, whereas the monitor is much more ephemeral and will not care.

**Comment by angrbrd** [comment]
@srderson I agree with @binhn . If the statistics monitor does not receive a block event on sync, how would it know to incorporate new transactions into the computation when they are made available? That becomes more complicated to differentiate.

**Comment by ghaskins** [comment]
I second @binhn position...i think there are transactions that might need to be enacted after being confirmed into a block (such as launching a new chaincode instance) that would need to happen regardless of whether the block was observed live or during a sync

**Comment by muralisrini** [comment]
ok. The current monitor reporting transaction stats such as new transaction rate.... would the "transaction rate" semantic apply to stats computed from blocks recieved on sync ?

**Comment by binhn** [comment]
@muralisrini the rate computation is time dependent
