### ISSUE TITLE
Load genesis checkpoint

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#400]
Needed in `pbft-core`.

Implemented in: https://github.com/kchristidis/obc-peer/commit/ee41928fd788315ec29fac53d87fb510a37d2c05

@jyellick, feel free to modify the functions I introduced to `innerCPI` and `CPI` as you see fit for your state transfer work.

**Comment by kchristidis** [comment]
@jyellick Can we close this?

**Comment by jyellick** [comment]
@kchristidis Yes, this was address in commit c9bf138f and tweaked for new apis in commits 0ef06114 and 9f7aa2c.

**Comment by kchristidis** [comment]
Great, thanks!
