### ISSUE TITLE
Select hashing algorithm - potential issues with SHA3

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#408]
Select a hashing algorithm. This is the hashing algorithm used for
1. The blockchain (hash of the previous block and global state hash)
2. Security features
They don't have to be the same.

There's a lot of background discussion here which I will not be able to fit into summary, so feel free to add your thoughts.

Originally, we were using SHA3 SHAKE 256 for hashing. This is a reasonable choice, but the problem is Go's implementation of SHA3. As @jjustj pointed out, "a1 sha3 does not exist in go. what they have is what i call "sha2.999" .. this is easily tested by doing sha3("") and googling the resulting hash (it is in the nist spec) it will return the pre-final-spec expected values, just as cryptopp5.6.2 and earlier do. cryptopp 5.6.3 sha3("") returns the hash specified in the final nist spec"

SHA2 has potential length-extension attacks. These are sometimes mitigated by hashing twice.

@elli-androulaki and @adecaro have suggested "the safest feasible solution today is using HMAC with SHA-2 as the underlying hash function"

Here are the steps I'm going to take
1. Undo the merges that switched from SHA3 to SHA2 as these were done without first giving @elli-androulaki and @adecaro proper time to comment. Apologies that this happened.
2. Make sure @jjustj has time to comment on the HMAC with SHA2 proposal.
3. Investigate if there are any changes coming to the Go SHA3 implementation in Go 1.6.

**Comment by srderson** [comment]
I have reverted the merge in PR #409.

**Comment by srderson** [comment]
@jjustj I wrote a very simple test case for the golang.org/x/crypto/sha3 package at https://github.com/srderson/go-sha3-test. As far as I can tell, the package is giving the correct outputs. The "correct outputs" that I'm using are coming from http://csrc.nist.gov/groups/ST/toolkit/examples.html and http://www.di-mgt.com.au/sha_testvectors.html [1]. Which sha3("") variant is failing for you and what is the expected output you have?

[1] I used this site because it was a bit easier to parse. I didn't match up every expected output to the actual NIST papers.

**Comment by binhn** [comment]
There is a interesting discussion how Factom uses sha2  https://github.com/FactomProject/FactomDocs/blob/master/factomDataStructureDetails.md#entry-hash

**Comment by srderson** [comment]
We have decided to use SHA3 for now as we have found Go's implementation to be complete. One important outcome from this discussion is captured in issue #431. Recording the hash algorithm used in the block will allow us to potentially change hashing algorithms in the future.
