### ISSUE TITLE
Improve state hash calculation

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#41]
Here's how the state hash calculation is currently implemented
1. Get list of chaincodes that modified their state
2. Hash all the state data for each chaincode that modified its state
3. Store the hash in the DB (chaincode ID -> hash)
4. Hash all chaincode hashes to get the global hash

This is obviously quite inefficient for generating the global hash if there are either a large number of chaincodes or if a chaincode's state contains a large number of key/value paris. Our current DB structure does allow fast lookup of key/value pairs.

Our goals are
1. Fast lookup of key/value pairs
2. Fast global hash calculation
3. Avoid storing the global state in memory. It may be too large

I hypothesize that Openchain networks are likely to have a small number of active chaincodes each with a large number of key/value paris, but the code must still performant in other situations such as in networks that contain a large number of chaincodes.

We are considering some form of a Merkle tree to accomplish our goals.

**Comment by binhn** [comment]
close per discussion with @manish-sethi he will open separate related issues
