### ISSUE TITLE
GetPeerEndpoint "Auto detect peer address" message should be an info

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#410]
The GetPeerEndpoint function logs the warning message `"AutoDetected Peer address: %s", peerAddress`. This warning message is confusing to users as they may think it indicates a problem.

We should change it to info and change the message to  `"Auto detected peer address: %s", peerAddress`

**Comment by binhn** [comment]
@srderson thanks for scrubbing the log. I agreed with your suggestion.
