### ISSUE TITLE
Chaincode context contains transaction certificate

### ISSUE THREAD

**Issue by frankyclu** [hyperledger-archives/fabric#421]
Chaincode needs to have access to the TCerts invoking them, so that chaincode can use these TCerts as tokens representing digital assets

**Comment by frankyclu** [comment]
web applications also need to have access to ecerts and tcerts so they can create a wallet managing them

**Comment by bmos299** [comment]
@muralisrini I'll work you on this one.

**Comment by bmos299** [comment]
@muralisrini let me know when you have something for me to try.   I can help too.
Thanks, Barry
