### ISSUE TITLE
Removing encrypted* fields from Transaction message

### ISSUE THREAD

**Issue by adecaro** [hyperledger-archives/fabric#427]
For confidential transactions, the payload and the chaincodeID must be encrypted.
Currently, the protobuf Transaction message, defined in openchain.proto, has two fields to store the encrypted chaincodeID and payload. In order to simplify the structure of the Transaction message, we want to remove these additional fields and reuse existing fields.

For the encrypted payload this is straightforward because payload and encrypted payload have the same type (bytes). This is not the case for the chaincodeID, the types there are different. 

The required modifications are following:
1. change chainodeID's type to bytes
2. update the crypto layer to support the new structure.

**Comment by binhn** [comment]
@adecaro do we need to encrypt the chaincode id if it is a hash (instead of a struct {path, version})?
My limited knowledge on security would say no as a hash doesn't review anything meaningful

**Comment by muralisrini** [comment]
@adecaro : I've changed Transaction's ChaincodeID to be bytes in https://github.com/muralisrini/obc-peer/tree/remove_encrypted_fields_from_xaction_message/issue%23427.

**Comment by adecaro** [comment]
@binhn We do as long as the pair {path, version} is predictable. If the probability distribution of {path, version} has low min-entropy then the hash can be used to learn {path, version} by brute forcing.

**Comment by muralisrini** [comment]
@adecaro : the hash is not computed from {path, version}. it is computed from {path, init function name, init function args, code bytes from all the code in path}. I'd say its hard to predict the tuple from the hash.

However the ChaincodeID struct has both hash and path fields in it. If we find we can get away with Transaction's "chaincodeID" field can just have the hash part of the struct (which I suspect is true), then we can just call it "hash" field and copy just the hash.

More ideally, perhaps we don't need the chaincodeID field in the Transaction structure at all ? If the transaction's payload is always there then we should be able to extract the chaincodeID as needed from the chaincode spec therein. Although, having the chaincode ID (or hash) in the structure could prove to be a nice optimization if it is accessed often.

My vote, for now, is to go with this first step of converting to chaincodeID to bytes. It is a good logical step for either path above which we should investigate in future.

**Comment by adecaro** [comment]
@muralisrini : It's hard but not unfeasible. Among the arguments you listed I don't see one that contains a random string, for example. So, given some auxiliary information, an attacker could enumerate all the possible tuples and test against the hash, that the attacker has, to see which tuple hashes to the target hash. So, to be more general, the hash function doesn't increase the entropy of the source. If the source is predictable, then the hash can be used to check which string was hashed by brute force. Encryption solves this problem.

**Comment by adecaro** [comment]
The issue can be considered closed. The PR that fixed it has been accepted.
