### ISSUE TITLE
REST API Query changes double quote to single quote

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#435]
Close to the end of function Query in rest_api.go, the following line changes double quote to single quote:

// Replace " characters with '
respVal := strings.Replace(string(resp.Msg), "\"", "'", -1)

This breaks JSON response since single quote is an invalid character in JSON.

**Comment by angrbrd** [comment]
Thanks for bringing this up, someone else ran into this as well. The reason this was there in the first place was that we have no way to force the chaincode to return a particular response format at this time. And If I expect it to be JSON and the returned string is also JSON in ", it would include " inside of ". This is also invalid. Thus the confusion. I will look into this.

**Comment by corecode** [comment]
How about using the `encoding/json` package to take care of all JSON production, instead of open-coding using `fmt`?  Maybe a pattern like this will prevent JSON encoding errors and enforce "correctly typed" JSON:

``` go
package main

import "encoding/json"

type restResult struct {
    OK    string `json:",omitempty"`
    Error string `json:",omitempty"`
}

func main() {
    msg := "message with \" quote"
    j, _ := json.Marshal(restResult{OK: msg})
    result := string(j)
    println(result)
}
```

Run at https://play.golang.org/p/1lyb8_mXpl
