### ISSUE TITLE
Setting Up a Network For Development - Errors in examples

### ISSUE THREAD

**Issue by dileban** [hyperledger-archives/fabric#451]
It looks like a few things have been overlooked following recent changes.

Examples under section "Deploy, Invoke, and Query a Chaincode":

1)  Support for "-v" flag appears to have been removed in favour of chaincode names. This isn't reflected in the examples.
2) The last two examples don't set the "OPENCHAIN_PEER_ADDRESS" environment variable prior to invocation.

**Comment by binhn** [comment]
fixed
