### ISSUE TITLE
CLI should print outputs, not indirectly via logger

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#453]
In order to automate operations via CLI (and testing), the CLI should print results in a consistent way.  The logger is not useful for this purpose.

Additionally, logger messages produce interference with output parsing.  For CLI operations, logger messages should probably be suppressed below the `Error` level, and also go to `stderr` instead of `stdout`.

**Comment by bcbrock** [comment]
I agree. This should be a top priority as it will quickly enable simple automated testing, and should not be hard (for an experienced GO/JSON programmer) to implement.

**Comment by bcbrock** [comment]
Hi @angrbrd, @binhn I am about to submit a PR that fixes this. I should have commented when I started working it.

**Comment by angrbrd** [comment]
@bcbrock , OK thanks for letting me know. I can review the PR if you would like. Thanks.

**Comment by bcbrock** [comment]
@angrbrd - Please see pull request #613. Thanks.

**Comment by angrbrd** [comment]
@bcbrock , my understanding is that the usage of logger was supposed to be changed for Error level messages only, correct? The Info level messages remain as they are. If I am understanding this correctly, I just want to make sure that all logger.Error instances have been modified accordingly. What about lines 430 and 447? Should those also be changed?

**Comment by angrbrd** [comment]
Closed by pull request #613 in commit 2d59bcb3047894be789e3267b3017f72f726b25c
