### ISSUE TITLE
Chaincode deployments hang in certain cases, need timeouts

### ISSUE THREAD

**Issue by masterDev1985** [hyperledger-archives/fabric#455]
When using the REST API to deploy chaincode.  Clients pass in the url to a repository that contains their chaincode.  The peer initiates a "go get <path>" command to pull the code and its dependencies before building it.  If the chaincode repo or any of its dependency repos are private (hint hint obc-peer), then this command will hang, because the command will attempt to ask a user for credentials in the terminal.  The consequence of this is that the REST deploy request never comes back.  Also, this causes the deploy process to hang, which leaves the state of the peer in a bad place.  We need some way to resolve this.

**Comment by masterDev1985** [comment]
I've created a pull request that changes the 'go get' code to have a timeout and adds a parameter to openchain.yaml which controls that timeout.

**Comment by corecode** [comment]
This is somewhat related to #452

**Comment by binhn** [comment]
@masterDev1985 I kind of lost track of this issue. Since no reference here, have you submitted a pull request to address this?

**Comment by masterDev1985** [comment]
Yeah, looks like I forgot to close the issue associated with it.  This has been fixed by using the local copy of the obc-peer code and keeping chaincode in public repositories, as a policy.
