### ISSUE TITLE
Use `consensusMetadata` field

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#461]
For consensus-related values that we may want to record in a block.

Will set this up for our PBFT variants and Sieve.

Goes along with #459, #460.

**Comment by kchristidis** [comment]
Fixed in https://github.com/kchristidis/obc-peer/commit/8608411f72542d9119ae7a02d414f855ed2b1ffc, waiting confirmation from @jyellick to check if it's working as he expects it to, before I close this.

**Comment by jyellick** [comment]
It looks to me like there's some work left here.

As a quick background, the signature of the `execute` function is `(txRaw []byte, opts ...interface{})`, and is currently only invoked by `pbft-core.go` as `instance.consumer.execute(req.Payload, idx.n)`, where `req.Payload` is an arbitrary `[]byte` determined by the pbft implementation, and `idx.n` is the sequence number.

I'm not sure what the motivation is for defining a varargs `opts ...interface{}` parameter to `execute`, as ~~none of the pbft implementations appear to even inspect the `opts`~~ it only appears to be referenced by `obc-classic.go` and `obc-batch.go` for consensus metadata.   Maybe there is some longer-term architectural purpose for this?

I am operating under the assumption that individual pbft implementations will not need to have custom consensus metadata, if this is not the case, then the structure below need to be changed.

I would propose we simply modify the `execute` signature to be `(txRaw []byte, consensusMetadata []byte)`.  

When `pbft-core.go` invokes this method, it would take a struct containing the sequence number, serialize it using protobuf, and pass it in as the `consensusMetadata` parameter.

Then, at the completion of state transfer, `pbft-core.go` could be able to deserialize the metadata, and continue.

If you agree, and would like to assign this to me, I can complete this, as issue #299 is still blocked.

**Comment by kchristidis** [comment]
I defined `execute` as a variadic function so that it's easier for us to add more fields to the metadata if needed. For example, if you want to include the view, all you need to is `instance.consumer.execute(req.Payload, idx.n, idx.v)` in `pbft-core.go`, and modify your wrapper (e.g. `obc-classic`) accordingly so that it creates the the respective `consensusMetadata` message.

> Then, at the completion of state transfer, pbft-core.go could be able to deserialize the metadata, and continue.

This is what I was missing, and what makes your suggestion the right one. Feel free to modify it accordingly.

**Comment by jyellick** [comment]
This has been implemented in commit 8cdf97c1ede23d3b44d59ccb6101bd2e1ced925c.

It has also been tested and verified via state transfer in commit 76f6e40b849ab3cbc76ce4801f8638f65b6198c1.
