### ISSUE TITLE
Drop dependency from VP whitelist when generating a VP's ID

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#462]
As things stand right now, and following our previous discussion and decision on the matter (see [here](https://github.com/openblockchain/obc-peer/issues/220#issuecomment-158283089) and [here](https://github.com/openblockchain/obc-peer/issues/220#issuecomment-158345393)), we maintain a whitelist of validating peers in `openchain.yaml`. This carries the cryptographic handles (hashed raw enrollment certificates) of the validating peers that we expect to see in the fully-connected VP network upon booting. We load that list in our PBFT-based variants to figure out a VP's ID. This is the unique unsigned integer that each VP is associated with upon booting, and which is used throughout the PBFT protocol to coordinate the view-change, etc.

Apparently, this creates issues when attempting to automatically deploy a network of VPs using Swarm.

Therefore, we need to remove that whitelist, and consequently our dependency from it, when generating VP IDs. A _possible_ approach would be to:
1. Record the number or expected VPs in the network in the consensus config file, let's call this value `x`.
2. Defer the instantiation of the `Consenter` object (that needs the ID) until the VP has established connection with `x` peers, i.e. until `len(VP.handlerMap) == x`.

**Comment by binhn** [comment]
@kchristidis I am not clear on 2 "Defer the instantiation of the Consenter object (that needs the ID) until the VP has established connection with x peers, i.e. until len(VP.handlerMap) == x".  Could you elaborate a bit more.

We know that PBFT should run whenever TX arrives and fail if x < 2f+1 as part of the algorithm.

**Comment by kchristidis** [comment]
- For PBFT to run, each VP needs to have an ID set.
- For an ID to be set, each VP needs to have the same list of peers.
- For all VPs to have the same list of peers, we need to check when `vp.handlerMap == x` for every VP.

If you try to submit a TX before the fully connected network is formed, it will fail. This is admittedly an edge case, as all of the steps above will take place shortly after the network is booted.

What it comes down is that we cannot fully execute [this function](https://github.com/kchristidis/obc-peer/blob/devel/openchain/consensus/obcpbft/obc-pbft.go#L45) that instantiates the consenter until we have an `ID`. Or we can (maybe we should), by setting up a temp ID and defer on doing any actual consensus until the proper ID is set (when `len(VP.handlerMap) == x`). I will investigate to figure out the best approach.

**Comment by binhn** [comment]
What is the ID used in PBFT?  If it is crypto.peer.GetID(), it is available upon initialization;  however, note that if security is off, the security context is nil, and crypto is not available. Perhaps we should discuss f2f for efficiency.  I want to see that PBFT can function with the number of validators >= x - f

**Comment by kchristidis** [comment]
Correct, I know how the `crypto` package works, and I also have a patch in my `devel` branch (following the comment [here](https://github.com/openblockchain/obc-peer/issues/265#issuecomment-166004929) and our conversation on Slack on 12/19) so that the PeerEndpoint message carries a replica's cryptographic handle (the result of `crypto.peer.GetID()`, and also the handler map is keyed by the cryptographic handle, when `security.enabled == true`. (See https://github.com/kchristidis/obc-peer/commit/bfa38064aae0f4e5b99b1570a77036798df4e61a and https://github.com/kchristidis/obc-peer/commit/9af52bfe974723ecc729b048038251e9b10a925b for more.)

I can meet with you tomorrow to discuss this further, but I'm writing this here (a) for reference, and also (b) to invite corrections/suggestions from others.

Going back to your question, here's an example: You're under a certain view. You suspect something goes wrong. You need to switch to another view. This other view that you suggest switching to cannot be randomly picked. There is a certain order that needs to be maintained so that the network is reconfigured back to a working setting as fast as possible. How do we make sure that every (non-Byzantine) node follows the same order?

What we do is, we order the cryptographic handles and the index of each handle in that ordered set is what we use for`ID`. So when we're in view `i`, if two non-Byzantine nodes suspect something is wrong with the current primary `i`, they'll both suggest switching to new view `i+1`, i.e. the cryptographic handle that corresponds to index `i+1` in the ordered set of cryptographic handles they maintain.

If the set of cryptographic handles that VP1 maintains is different than the one that VP2 maintains, VP1 will suggest that the new primary is the replica with cryptographic handle `foo`, while VP2 will suggest switching to `bar`. This is _not_ what we want.

Therefore it is important that all VPs have the same set of cryptographic handles (validating peers), and we hold off on any PBFT operations until this set is formed.

You can drop the `ID` construct entirely if you're so inclined, but you're still going to be using it under the cover, via an index on the set of the cryptographic handles that I just described. _The key is that all VPs refer to that same set._

So, for MVP at least, you either preload the set in the config file (which is what we did until now) or wait until the fully-connected network is formed (which is what I'm thinking of switching to).

Ideally, whenever we wanted to get that set we would ping the certificate authority and get the list of all the hashed raw enrollment certificates it has issued for all the validators in the network (similar to Greg's comment [here](https://github.com/openblockchain/obc-peer/issues/220#issuecomment-159005885)). That ensures that every VP refers to the same set. (With the current implementation, if you drop the MVP assumption of a fully connected network, VP1 may see a different VP set than VP2, so they're referring to different sets and things will break for the reason I mentioned at the beginning of this post.)

Indeed, I had discussed with Angelo the possibility of having such a function in `obc-ca` back when we were using the previous repo. But again, you need to wait for all of these certificates to be issued (which I think is equivalent to: wait for the network to be formed, the way our registration process works) before you do that call to `obc-ca` for the set, and initiate `consensus`.

**Comment by kchristidis** [comment]
What was asked today essentially boils down to this:

> For MVP, when you create a network you set the number of validators `N` and you make sure that each validator's `peer.id` is set to `vpX` where `X` is a unique number between `0` and `N-1`.

This is taken care of in https://github.com/kchristidis/obc-peer/commit/44719d3874b928f87ada86db1b765b112342be2c.

**Comment by kchristidis** [comment]
Missing check added in https://github.com/kchristidis/obc-peer/commit/f25b59b8eba0fc930200a934c74b53eb9e16fad1.

**Comment by kchristidis** [comment]
I'm re-opening this as a reminder for us that we need to address this issue _eventually_ in a less flaky way.
