### ISSUE TITLE
Replicate PBFT demo with all the PBFT variants in our `obcpbft` package

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#463]
Use `classic`, `batch`, and `sieve`.

@corecode's work on `Docker Compose` (already in our `devel` branches) should come handy.

**Comment by tuand27613** [comment]
I can create a docker-compose network consisting of 4 validating peers, 1 obc-ca server and 1 container to do CLI commands from.

I've run the pbft demo using the various pbft plugin variants and can show via logs that we're getting the correct pre-prepare msgs sent and that the prepare and commit counts are being processed correctly

**Comment by tuand27613** [comment]
There's still a bunch of problems related to, I think, Docker and Vagrant configuration that I need to walk through
1. placing obcpbft/config.yaml in the right directory in the docker image
2. a CLI login throws an error , cannot create /var/openchain/production/client (workaround is to create the dir manually and re-run the command)
3. the CLI chaincode query dies with error `unable to find image`

**Comment by kchristidis** [comment]
@tuand27613 confirms that the happy path works on the live network with all three PBFT variants. Closing this.
