### ISSUE TITLE
BuildImage_Peer fails if using local custom Docker base images

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#466]
In openchain/container/vm.go [lines 134 and 155] the options passed to the
Docker remote API include the "pull" option. According to the Docker docs.:

```
   https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/
```

this means

```
 "Attempt to pull the image even if an older image exists locally."
```

What happens however is that the image build fails unless the named image is
available remotely - it seems to ignore the local image in this case. This
means that it is not possible to use private local Docker images as the basis
for OBC Docker images - at least if they are built as documented via invoking

```
go test -run BuildImage_Peer
```

I think the option here should be changed to "Pull: false". It's not clear why
one would want to re-pull an image from Docker Hub if a local copy exists, and
there are several reasons why one might want to start from custom Docker
images. (In my case, because I'm porting to POWER and experimenting with
GCCGO).

**Comment by muralisrini** [comment]
+1 ... we ran into this with work done by @gongsu832  as well.  @jeffgarratt, thoughts please ?

**Comment by srderson** [comment]
This is resolved now. We no longer use `Pull: true`
