### ISSUE TITLE
repo: correct file mode (execute) introduced in a287fb1b

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#470]
a287fb1b introduced a repo-wide change in file modes, adding a +x.  We should remove these +x again.

**Comment by christo4ferris** [comment]
@corecode @prjayach - this is odd... any idea why the permissions were changed? Agree they should be changed back

**Comment by prjayach** [comment]
Not sure what happened here. I agree +x should not be there.

**Comment by lehors** [comment]
I'll put a PR together for this.
