### ISSUE TITLE
obc-peer dies unexpectedly

### ISSUE THREAD

**Issue by vpaprots** [hyperledger-archives/fabric#473]
On my laptop:
- one docker peer: `docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer`
- one 'local' peer: `OPENCHAIN_PEER_LOGGING_LEVEL=DEBUG OPENCHAIN_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303  ./obc-peer peer`
- chaincode: `OPENCHAIN_CHAINCODE_ID_NAME=mycc3 OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 ./chaincode_example02`
- chaincode calls: `while true; do OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 ./obc-peer chaincode invoke -n mycc3 -c '{"Function": "invoke", "Args": ["a", "b", "10"]}'; done`

The 'local' peer dies after ~30 seconds

**Comment by vpaprots** [comment]
I do get blocks in my blockchain:

```
curl 172.17.0.2:5000/chain/blocks/501
 {"proposerID":"proposerID","transactions":[{"type":3,"chaincodeID": {"name":"mycc3"},"payload":"Ch8IARIHEgVteWNjMxoSCgZpbnZva2USAWESAWISAjEw","uuid":"3745d063-f6df-4c49-b9da-d23e81964b93","timestamp":{"seconds":1452629767,"nanos":176837471}}],"previousBlockHash":"nvX9QiAiwa0nR+Xcbxc9XQihGjWg+9NaXyWKqQP63gRbHb48kULJDhdraUmAW+KAdXtPM/iBGdgrlHCI/i4/Pw==","nonHashData":{"localLedgerCommitTimestamp":{"seconds":1452629767,"nanos":181661238}}}
```

and the chaincode is happily executed it appears:

```
...
2016/01/12 15:16:07 Received RESPONSE. Payload: 37420, Uuid 3745d063-f6df-4c49-b9da-d23e81964b93
Aval = -37320, Bval = 37430
2016/01/12 15:16:07 Inside putstate, isTransaction = true
...
```

(i.e. the invoke function was called >3700... got 500 blocks in the blockchain)

**Comment by muralisrini** [comment]
This looks like a file descriptor leak. From preliminary investigations likely from grpc client socket. Assigning to self for further investigation.
