### ISSUE TITLE
Chaincode shim table API

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#477]
Provide an API to emulate tables/rows/columns in the chaincode shim. This has been proposed as a way to hide low level state key/value store API from chaincode developers.

API
createTable(name, []columnDefinition)
insertRow(row)
getRow(key)
deleteRow(key)
replaceRow(row)

**Comment by markparz** [comment]
Not required for Jan... true run-at

**Comment by frankyclu** [comment]
can we add API to query by column value?

**Comment by srderson** [comment]
Today the API has
`GetRow(tableName string, key []Column) (Row, error)`

and for partial keys
`GetRows(tableName string, key []Column) (<-chan Row, error)`
See comment at https://github.com/openblockchain/obc-peer/blob/master/openchain/chaincode/shim/chaincode.go#L459 for details.

are you asking about querying via non-key column values?

**Comment by bmos299** [comment]
@srderson I'll work on this one with you.  Please let me know when you have some time.
