### ISSUE TITLE
Peer crashes when CLI using the same enrollment ID as peer or nil

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#479]
Follow the instruction here https://github.com/openblockchain/obc-peer/blob/master/docs/SandboxSetup.md  to set up:

1) start validator with nepumuk in openchain.yaml
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_SECURITY_ENABLED=true ./obc-peer peer --peer-chaincodedev 

2) start cli to log in 
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_SECURITY_ENABLED=true ./obc-peer login nepumuk

3) cli to deploy chaincode
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ OPENCHAIN_SECURITY_ENABLED=true ./obc-peer chaincode deploy -u nepumuk -n mycc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

4) peer crashes (see log below)

Note that validator also crashes when the enroll id is nil or empty string.  I think we should return error rather than panic and exit

...
20:34:07.150 [CRYPTO.client.nepumuk] loadEnrollmentCertificate -> DEBU 174 Loading enrollment certificate at [/var/openchain/production/crypto/client/nepumuk/enrollment.cert]...
20:34:07.173 [CRYPTO.client.nepumuk] loadEnrollmentCertificate -> ERRO 175 Failed checking enrollment certificate against enrollment key [Signature not valid.].
20:34:07.173 [CRYPTO.client.nepumuk] init -> ERRO 176 Failed initiliazing crypto engine [Signature not valid.].
20:34:07.173 [CRYPTO] InitClient -> ERRO 177 Failed client initialization [nepumuk]: [Signature not valid.].
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x816385]

when the enrollment id is nil:
19:35:48.865 [CRYPTO.client.nepumuk] retrieveTLSCertificate -> INFO 05f Storing enrollment key and certificate for user [nepumuk]...
19:35:48.865 [CRYPTO.client.nepumuk] register -> INFO 060 Registering [nepumuk]...done!
19:35:48.865 [CRYPTO] RegisterClient -> INFO 061 Registering client [nepumuk] with name [nepumuk]...done!
19:35:56.405 [devops] Deploy -> DEBU 062 Initializing secure devops using context 
19:35:56.405 [CRYPTO] InitClient -> INFO 063 Initializing client []...
19:35:56.406 [CRYPTO.client.] init -> ERRO 064 Not registered yet.
19:35:56.406 [CRYPTO] InitClient -> ERRO 065 Failed client initialization []: [Registration to the Membership Service required.].
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x8162a5]

@angrbrd @elli-androulaki @adecaro

**Comment by adecaro** [comment]
This has been fixed.
