### ISSUE TITLE
Investigate state management delta (de)serialization

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#480]
Presently, the statemgmt deltas use a custom serialization process.  In `state_delta.go`, there is a comment

```
// marshalling / Unmarshalling code
// We need to revisit the following when we define proto messages
// for state related structures for transporting. May be we can
// completely get rid of custom marshalling / Unmarshalling of a state delta
```

Now that the message protos are defined, unless there is a compelling reason to continue to use the custom serialization, it would make the message protocol specification more clear, and would also simplify the state transfer API in issue #299 

Assuming this can be done, the CPI interface and associated plugin usage will need to be fixed as well, feel free to assign to me (@jyellick) if needed for the CPI related work.

**Comment by christo4ferris** [comment]
@jyellick @srderson I presume this is still relevant? If so, please transfer to Jira and close this one. Thanks

**Comment by jyellick** [comment]
@christo4ferris Actually, I think this is dead in the new architecture, as we will only be moving blocks, and not state deltas.

**Comment by christo4ferris** [comment]
ok, closing thanks @jyellick
