### ISSUE TITLE
Configuration files for the `consensus` package

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#481]
With `obcpbft` about to turn into a separate project, we need to rethink our approach on the consensus-related config files. Following a discussion with @jyellick here's a couple of issues that stand out:

(Replace `plugin` with `obcpbft` throughout this text if you want to make it specific to `obcpft`.)

One, we need to move some consensus-related settings out of `plugin/config.yaml` and into a new `consensus/config.yaml` file. For example `general.name` (plugin that'll be used), and `general.N` (number of validators). We may even need to bring `peer.id` from `openchain.yaml` here.

Two, configuration for `statetransfer` (see #291). (Note that the `statetransfer` package will remain within `consensus`.) We can argue that `statetransfer` should have its own `config.yaml`, but as @jyellick points there might be instances where the plugin wants to modify the state transfer config variables over time. Also, we don't want the user editing the `statetransfer/config.yaml` file and have this behavior overridden by the consensus plugin. Therefore, it seems best to keep the state transfer-related config variables in `plugin/config.yaml` file (as we do now with `obcpft`).

@binhn, @corecode feel free to chime in with your thoughts on this.

**Comment by kchristidis** [comment]
Assume you write your own consensus plugin. Let's call it `test`.

As things stand now, in order to run `test` you need to:
1. Modify `openchain.yaml` in the `main` package. Set the `peer.validator.consensus` value to `test`.
2. Modify `controller.go` in the `controller` package. Add an extra if-clause in `NewConsenter()` along these lines:

```
if plugin == "test" {
   consenter = test.GetPlugin(cpi)
}
```

We have to improve that.

First of all, as I wrote in the opening note above we will be creating a `config.yaml` file in the `consensus` package that'll carry the `name` of the active plugin, and the maximum number `N` of validators in the network. So the `peer.validator.consensus` reference in `main`'s `openchain.yaml` needs to be dropped. (It's only used [here](https://github.com/openblockchain/obc-peer/blob/master/main.go#L307).)

Removing Step 2 above or replacing it with a better process seems tricky though.

It would be great if we could:
1. Read the plugin's `name` from the `consensus`'s `config.yaml` and store it in say a `pkg` variable
2. Then do `pkg.(reflection-fu-goes-here).GetConsenter()`

**But** Go [prevents us from doing that](http://stackoverflow.com/a/8076673/2363529).

Another approach could be to (credit to @jyellick for the idea today & @muralisrini 5 months back :grin:):
1. Have a `RegisterConsenter(pkgName string, func(consensus.CPI) consensus.Consenter)` function in `controller` that populates a `plugins` map in `controller`, whose type is `map[string]func(consensus.CPI) consensus.Consenter`.
2. Each plugin would have an `init()` function that calls `RegisterConsenter` to register their constructor.
3. When the system calls `controller.NewConsenter`, we'd read the `config.yaml` file from `consensus`, load the value the corresponds to the `name` key, and run the corresponding constructor function in the `plugins` map for the `name` key.

**But** the plugin's `init()` function would never run in the first place because the plugin is not imported anywhere. (We could solve this by asking plugin developers to place their plugins in a fixed package (say `plugin` and load `plugin` similar to how it's done [here](https://stackoverflow.com/questions/24125652/golang-auto-including-extensible-application) with `extensions`), but that would mean placing _all_ of their plugins there and having to deal with namespace clashing.)

So we're still stuck. I'll revisit this tomorrow but if you have any thoughts on this, please let me know.

**Comment by binhn** [comment]
I think it would be fruitless to try something else. Go is so static that we can't avoid having people modify the file. The only other integration that I could think of would be gRPC, but that would be a bigger effort

**Comment by kchristidis** [comment]
@binhn:
1. Regarding [your comment above](https://github.com/openblockchain/obc-peer/issues/481#issuecomment-172849946), you're most probably right.
2. Do you agree with the idea of a `config.yaml` in the `consensus` package? I've described the thinking [here](https://github.com/openblockchain/obc-peer/issues/481#issue-126522308) (3rd paragraph) and coded it [here](https://github.com/kchristidis/obc-peer/commit/6c20cbdcc3b72ab1b42f885d14a338ec0973eaa4#diff-f797a77ce33166ea5b67a7e229432ae9). If you agree, we'll have to remove the `plugin` setting from `openchain.yaml` as it is redundant.

**Comment by kchristidis** [comment]
Discussed this with @binhn today, we'll stick with two config files (as we used to): `openchain.yaml` in `main`, and `config.yaml` in `obcpbft`.
