### ISSUE TITLE
Expose to the application a function of signing meesages/Transactions with ECert

### ISSUE THREAD

**Issue by elli-androulaki** [hyperledger-archives/fabric#484]

**Comment by binhn** [comment]
We also want a function (crypto.go) to get the client ecert. The application can use it in whichever way it needs.

@angrbrd

**Comment by angrbrd** [comment]
@adecaro just gave me a preview of the coming changes. The interface that will be exposed will also include a method to retrieve the raw representation of the ECert.

**Comment by adecaro** [comment]
I close this issue because #471 can handle it directly.
