### ISSUE TITLE
TLS integration

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#508]
Enable TLS connections using TLS-CA

**Comment by jeffgarratt** [comment]
Working in parallel to test tls, will keep aligned with #534.

**Comment by jeffgarratt** [comment]
I had issues with cert/key files from Binh.  Asked Diego for another pair, he is working to give me certs/keys that will allow me to complete and checkin TLS testing samples.  @binhn @diegomasini

**Comment by jeffgarratt** [comment]
@binhn @diegomasini @adecaro #559 has been merged and tests basic TLS setup with cert/key provided by @diegomasini.  I am not sure if this closes this issue yet.  What do you think @binhn?

**Comment by binhn** [comment]
@jeffgarratt we should run it with security on and test the TLS produced by the crypto layer on each entity at fileSystemPath (eg /var/openchain/production/crypto/validator/binhn/ks/raw/)

**Comment by binhn** [comment]
@jeffgarratt have we done with this?  Tuan created a bug  #580 on TLS and I marked it "blocker"

**Comment by jeffgarratt** [comment]
@binhn I am working on the behave test for security right now, plan to complete shortly,  Should then be able to close this.
