### ISSUE TITLE
Support for chaincode versioning

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#51]
@jeffgarratt and I were discussing this today.

When sending a deploy chaincode transaction, there must be both an ID and version defined for the chaincode. 

Anyone calling the chaincode must reference the ID, and optionally, they can reference the version. We'd like to use the the same rules defined by NPM https://docs.npmjs.com/misc/semver

This would allow chaincode writers to update their chaincodes while allowing chaincode callers to choose the versions they will work with.

For example, an execute chaincode transaction would include an ID and a version such as `>=1.0.2 <2.1.2`

**Comment by binhn** [comment]
When we update chaincode, do we use the same CLI/API as deploying chaincode or a different one?
Is there a default version?  ie, we automatically assign 1.0.0 and next 1.01, and so on

**Comment by srderson** [comment]
I think it should be the same CLI/API. Like NPM, there would be a package.json type file describing your chaincode. If it's missing the name, version, etc. the deployment fails with a message that you must supply these values. If you try to deploy and the version in your package.json already exists, it would also fail with a message stating that you must change the version. I haven't published to NPM in a bit, but I believe this is the same approach they take. I don't think they auto increment version numbers for you.

**Comment by jeffgarratt** [comment]
This makes sense to me.  I pulled in a semver library for NPM style version making, but have not added the npm style config file as of yet.

**Comment by markparz** [comment]
moving to Milestone 4 at best

**Comment by muralisrini** [comment]
We have a a reasonable mechanism to distinguish both chaincode as wells the docker artifacts (images and containers) associated with them based on chaincode id, peer id, version numbers and urls. What else do we need to close this issue ?

**Comment by binhn** [comment]
This seems to be lated to #202 . I think the issue in my mind is that the combination of path+version is ok for end user to type on CLI, but we haven't worked it out for API @angrbrd -- how would we address a chaincode on API? If the representation of CLI defers from API, then we failed -- it needs to be consistent.

Also related to security #202 , we need a better chaincodeID to be included in the tx for the backend. We know some other blockchains trying to map between a user friendly name to a backend hash/id. It might come to that, or we would say hash/id for now; ie a chaincodeID that not easy to type and remember, but at least it is consistent through out. And, we can always build up higher abstraction later on.

**Comment by angrbrd** [comment]
Currently, when we deploy, invoke, or query a chaincode we utilize the same mechanism as we do on the CLI. It is expecting an element of type ChaincodeID, which contains both a path and version string. See below (sorry, somehow the indentation is not working properly when I am copy/pasting this).

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
message ChaincodeSpec {
    enum Type {
        UNDEFINED = 0;
        GOLANG = 1;
        NODE = 2;
    }
    Type type = 1;
    ChaincodeID chaincodeID = 2;
    ChaincodeInput ctorMsg = 3;
    int32 timeout = 4; 
}

// Carries the URL where the chaincode resides and the chaincode version.
// TODO: Merge with ChaincodeIDentifier.
message ChaincodeID {
    string url = 1;
    string version = 2;
}

**Comment by srderson** [comment]
Decided to remove versioning support as part of MVP per issue #373. Versioning will still be possible though different chaincode patters such as passing in the ID of the chaincode to call or adding hashes of old versions to a chaincode constructor.
