### ISSUE TITLE
checkGolangSpec() doesn't fails even if it is a valid http(s) path

### ISSUE THREAD

**Issue by mrshah-at-work** [hyperledger-archives/fabric#510]
Chaincode Deployment with a valid git repository path (github.com / hub.jazz.net) fails as the checkGolangSpec() function returns error.

**Comment by muralisrini** [comment]
We check remote paths parameter as a local path and fail. Rather than failing remote paths immediately, we will allow remote paths through but be strict with local path. Invalid or non-existing remote paths will fail during generating the targz.
