### ISSUE TITLE
Transaction ID usage in CPI is inconsistent

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#523]
The `CPI` interface presently exposes the methods

``` go
BeginTxBatch(id interface{}) error
ExecTXs(txs []*pb.Transaction) ([]byte, []error)
CommitTxBatch(id interface{}, transactions []*pb.Transaction, transactionsResults []*pb.TransactionResult, metadata []byte) error
RollbackTxBatch(id interface{}) error
PreviewCommitTxBatchBlock(id interface{}, transactions []*pb.Transaction, metadata []byte) (*pb.Block, error)
```

Notably, the `ExecTXs` method does not accept an `id interface{}` like the remainder of the transaction functions.

This is apparently because the current ledger implementation does not support concurrent transactions against the ledger, although the `id` was included in the API to allow concurrent support in the future without breaking the API compatibility.

I would propose that `ExecTXs` be modified to have the following signature.

``` go
ExecTXs(id interface{}, txs []*pb.Transaction) ([]byte, []error)
```

As a related thought, the state delta API in `CPI` looks like:

``` go
ApplyStateDelta(id interface{}, delta *statemgmt.StateDelta) error
CommitStateDelta(id interface{}) error
RollbackStateDelta(id interface{}) error
```

It seems that possibly this API should include a `BeginStateDeltaBatch` or some such so that its usage more closely mirrors the transaction API. 

In particular, input from @binhn and @srderson would be appreciated.

**Comment by kchristidis** [comment]
Closed with #605.
