### ISSUE TITLE
Move run-time artifacts out of obc-ca code folder

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#528]
The folder .obcca is default to where the code is, which causes git and editor to show them. We should use the same convention as openchain.yaml fileSystemPath: /var/openchain/production.  This includes unit test yaml files.
@srderson

**Comment by thkzrl** [comment]
Can you please elaborate a bit on this as I'm not sure what the issue is.  We can rename “rootpath” in "obcca.yaml" to “SystemPath” for the sake of consistency and default it to “/var/openchain/production”, but aside from that the CAs need their own subdirectory.  Thanks.
