### ISSUE TITLE
Query shows the current value of "a" (or "b") is not changed after issuing a few "invoke" commands

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#542]
Following the instruction at https://github.com/openblockchain/obc-peer/blob/master/docs/DevnetSetup.md, we can replicate the problem as:

1) start  a docker container:
   docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer
2) start a local obc-peer:
  OPENCHAIN_PEER_LOGGING_LEVEL=DEBUG OPENCHAIN_PEER_DISCOVERY_ROOTNODE=172.17.0.2:30303  ./obc-peer peer
3) Deploy the example 2
   OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode deploy -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
then get container's name, use this name to replace the <name_value_returned_from_deploy_command> in the next "invoke" and "query" command
4) OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode invoke -n <name_value_returned_from_deploy_command> -c '{"Function": "invoke", "Args": ["a", "b", "1"]}'

5) OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode query -l golang -n <name_value_returned_from_deploy_command> -c '{"Function": "query", "Args": ["a"]}'
Then we can observe that the value of "a" is 99.
So far all is good. 
However,  if put (4) and (5) commands into a while loop  and run it, after loop for around 20 times, the query command shows the value of "a" no long change. 

This seems a bug.
Thanks,

**Comment by vpaprots** [comment]
Just pulled upstream code (tag 77658f9) since I saw a fix for 'invoke'. Launched two peers, deployed example02. Individual invoke commands now execute on both peers.

Trying to push as many invokes as possible:

```
while true; do 
     OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode invoke -n $NAME1 -c '{"Function": "invoke", "Args": ["a", "b", "3"]}'; 
     OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode query -l golang -n $NAME1 -c '{"Function": "query", "Args": ["a"]}'; 
done
```

Invokes stop being executed rather quickly. And now they are out of sync:

```
vpapro@vpaprots:~/git/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.3:30303 ./obc-peer chaincode query -l golang -n $NAME1 -c '{"Function": "query", "Args": ["a"]}'
14:59:06.380 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"8449eb0b31176a6d2dc188b845a338fadd1f825de0212eaf2b7df39458b93441e6886a50201c3031bcf645d2ff9c4b41e5cbf7f233fdca488a5648900049cec5" > ctorMsg:<function:"query" args:"a" > > 
14:59:06.380 [main] chaincodeInvokeOrQuery -> INFO 002 Trying to print as string: 73
14:59:06.380 [main] chaincodeInvokeOrQuery -> INFO 003 Raw bytes 3733
vpapro@vpaprots:~/git/src/github.com/openblockchain/obc-peer$ OPENCHAIN_PEER_ADDRESS=172.17.0.2:30303 ./obc-peer chaincode query -l golang -n $NAME1 -c '{"Function": "query", "Args": ["a"]}'
14:59:09.599 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"8449eb0b31176a6d2dc188b845a338fadd1f825de0212eaf2b7df39458b93441e6886a50201c3031bcf645d2ff9c4b41e5cbf7f233fdca488a5648900049cec5" > ctorMsg:<function:"query" args:"a" > > 
14:59:09.599 [main] chaincodeInvokeOrQuery -> INFO 002 Trying to print as string: 64
14:59:09.599 [main] chaincodeInvokeOrQuery -> INFO 003 Raw bytes 3634
```

**Comment by vpaprots** [comment]
Another error that didnot show before is:

```
20:21:15.289 [peer] HandleMessage -> DEBU 8334e Handling OpenchainMessage of type: DISC_GET_PEERS 
20:21:15.289 [peer] handleChat -> ERRO 8334f Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
20:21:20.287 [peer] SendMessage -> DEBU 83350 Sending message to stream of type: DISC_GET_PEERS 
20:21:20.288 [consensus/handler] HandleMessage -> DEBU 83351 Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
20:21:20.288 [peer] HandleMessage -> DEBU 83352 Handling OpenchainMessage of type: DISC_GET_PEERS 
20:21:20.288 [peer] handleChat -> ERRO 83353 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
20:21:25.287 [peer] SendMessage -> DEBU 83354 Sending message to stream of type: DISC_GET_PEERS 
20:21:25.288 [consensus/handler] HandleMessage -> DEBU 83355 Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
20:21:25.288 [peer] HandleMessage -> DEBU 83356 Handling OpenchainMessage of type: DISC_GET_PEERS 
20:21:25.288 [peer] handleChat -> ERRO 83357 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
``
```

**Comment by vpaprots** [comment]
More data..

After killing the first peer, the one that got all the invokes, the second peer resumed executing! And answers to queries are decreasing as instructed. Alright... that made me suspect if one peer is now working with a while loop...

Not quite..

```
20:33:10.490 [consensus/noops] doTransactions -> DEBU 300ec Executing transactions
20:33:10.490 [consensus/noops] doTransactions -> DEBU 300ed Starting TX batch with timestamp: seconds:1453926790 nanos:489771727 
20:33:10.490 [chaincode] processStream -> DEBU 300e9 [edae9a0c]Received message PUT_STATE from shim
20:33:10.490 [peer] handleChat -> ERRO 300ee Error handling message: Failed to begin transaction with the ledger: Another TxGroup [seconds:1453926781 nanos:414697800 ] already in-progress
20:33:10.490 [chaincode] HandleMessage -> DEBU 300ef [edae9a0c]Handling ChaincodeMessage of type: PUT_STATE in state transaction
20:33:10.490 [chaincode] afterPutState -> DEBU 300f0 Received PUT_STATE in state busyxact, invoking put state to ledger
20:33:10.490 [peer] func1 -> DEBU 300f1 Received RESPONSE message as expected, exiting out of receive loop
20:33:10.490 [chaincode] func1 -> DEBU 300f2 [edae9a0c]state is busyxact

...
20:33:10.516 [chaincode] processStream -> DEBU 30283 [0e283ad8]Received message QUERY_COMPLETED from shim
20:33:10.516 [chaincode] HandleMessage -> DEBU 30284 [0e283ad8]Handling ChaincodeMessage of type: QUERY_COMPLETED in state busyxact
20:33:10.516 [chaincode] HandleMessage -> DEBU 30285 [0e283ad8-8f6b-4286-ae4e-1be3cd9997c9]HandleMessage- QUERY_COMPLETED. Notify
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4df5b6]

goroutine 31466 [running]:
github.com/openblockchain/obc-peer/openchain/chaincode.(*Handler).enterBusyState.func1(0xc828ea23f0, 0xc82012c500, 0xd32660, 0x8)
    /go/src/github.com/openblockchain/obc-peer/openchain/chaincode/handler.go:681 +0xc3
created by github.com/openblockchain/obc-peer/openchain/chaincode.(*Handler).enterBusyState
    /go/src/github.com/openblockchain/obc-peer/openchain/chaincode/handler.go:788 +0x53

goroutine 1 [chan receive, 1 minutes]:
main.serve(0x137e1d8, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/main.go:415 +0x1703
main.glob.func1(0x133a580, 0x137e1d8, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/main.go:75 +0x35
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).execute(0x133a580, 0x137e1d8, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:501 +0x869
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(*Command).Execute(0x133a3c0, 0x0, 0x0)
    /go/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra/command.go:584 +0x46a
main.main()
    /go/src/github.com/openblockchain/obc-peer/main.go:250 +0x14bc

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fbc54c86d30, 0x72, 0xc820010150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82013ff70, 0x72, 0x0, 0x0)
...
```

Meanwhile the while loop of invokes:

```
15:33:10.452 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"8449eb0b31176a6d2dc188b845a338fadd1f825de0212eaf2b7df39458b93441e6886a50201c3031bcf645d2ff9c4b41e5cbf7f233fdca488a5648900049cec5" > ctorMsg:<function:"query" args:"b" > > 
15:33:10.453 [main] chaincodeInvokeOrQuery -> INFO 002 Trying to print as string: 221
15:33:10.453 [main] chaincodeInvokeOrQuery -> INFO 003 Raw bytes 323231
15:33:10.491 [main] chaincodeInvokeOrQuery -> INFO 001 Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"8449eb0b31176a6d2dc188b845a338fadd1f825de0212eaf2b7df39458b93441e6886a50201c3031bcf645d2ff9c4b41e5cbf7f233fdca488a5648900049cec5" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (67dfdeb4-90ea-41a6-8e00-f17101960ede)
2016/01/27 15:33:10 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/01/27 15:33:11 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: connection refused"; Reconnecting to "172.17.0.2:30303"
2016/01/27 15:33:13 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
Error querying chaincode: rpc error: code = 13 desc = "transport is closing"

Usage: 
  openchain chaincode query [flags]

Global Flags:
  -c, --ctor="{}": Constructor message for the chaincode in JSON format
  -l, --lang="golang": Language the chaincode is written in
  -n, --name="": Name of the chaincode returned by the deploy transaction
  -p, --path="": Path to chaincode
  -u, --username="": Username for chaincode operations when security is enabled
15:33:16.804 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:19.827 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:22.848 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:25.866 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:28.889 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:31.909 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
15:33:34.928 [main] chaincodeInvokeOrQuery -> ERRO 001 Error building chaincode: Error trying to connect to local peer: grpc: timed out trying to connect
2016/01/27 15:33:37 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: no route to host"; Reconnecting to "172.17.0.2:30303"
```

Alright, will try stopping posting wall of text.

**Comment by vpaprots** [comment]
Hmm.. except I forgot to mention that I modified example02:

```
    // Write the state back to the ledger
    err = stub.PutState(A, []byte(strconv.Itoa(Aval)))
    if err != nil {
        return nil, err
    }

    err = stub.PutState(B, []byte(strconv.Itoa(Bval)))
    if err != nil {
        return nil, err
    }

    for i := 0; i < 1000; i++ {
        err = stub.PutState(fmt.Sprintf("%c%d", A, i), []byte(strconv.Itoa(Aval)))
       if err != nil {
           return nil, err
       }

       err = stub.PutState(fmt.Sprintf("%c%d", B, i), []byte(strconv.Itoa(Bval)))
       if err != nil {
           return nil, err
       }
    }

    return nil, nil
} 
```

**Comment by muralisrini** [comment]
@vpaprots : I ran the last 1 peer scenario with your chaincode changes for a bout 7 minutes in dev mode using the invoke/query loop from above.

Start :
01:07:38.616 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"mycc" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (25b39358-89a7-4ed6-a4ac-0fdbbbfbd206)
01:07:38.723 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"mycc" > ctorMsg:<function:"query" args:"a" > >
01:07:38.725 [main] chaincodeInvokeOrQuery -> INFO 002^[[0m Trying to print as string: 97
01:07:38.725 [main] chaincodeInvokeOrQuery -> INFO 003^[[0m Raw bytes 3937
01:07:38.821 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"mycc" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (be5fa335-375c-4077-b0bf-c1d531b0786d)

End :
01:14:21.492 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"mycc" > ctorMsg:<function:"query" args:"a" > >
01:14:21.493 [main] chaincodeInvokeOrQuery -> INFO 002^[[0m Trying to print as string: -179
01:14:21.493 [main] chaincodeInvokeOrQuery -> INFO 003^[[0m Raw bytes 2d313739
01:14:21.613 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"mycc" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (61dfecc2-a3b3-4623-bdef-0727680fc123)

I then tried to recreate it in non-dev env with 1 peer running the modified chaincode_example02. I ran the loop test for over 10 mins and it chugged along just fine:

Start:
11:30:04.887 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (2348d5e8-faf5-4ad2-9c5c-d54bb2a617e8)
11:30:05.092 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"query" args:"a" > >
11:30:05.092 [main] chaincodeInvokeOrQuery -> INFO 002^[[0m Trying to print as string: 94
11:30:05.092 [main] chaincodeInvokeOrQuery -> INFO 003^[[0m Raw bytes 3934
11:30:05.215 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (f1aeedac-49c0-421d-8cba-33c8141aff9b)

End:
11:40:18.366 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (2e280e0e-050f-436c-88ce-c1427caf6949)
11:40:18.566 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully queried transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"query" args:"a" > >
11:40:18.567 [main] chaincodeInvokeOrQuery -> INFO 002^[[0m Trying to print as string: -623
11:40:18.567 [main] chaincodeInvokeOrQuery -> INFO 003^[[0m Raw bytes 2d363233
11:40:18.718 [main] chaincodeInvokeOrQuery -> INFO 001^[[0m Successfully invoked transaction: chaincodeSpec:<type:GOLANG chaincodeID:<name:"a06cf5664962807752cce0230e60d51d829e350f1d1e8d7d433532a195a81d049d88c47e7a9d34387f4a3fcc45fd3ff2b352966c1d45772bafddc458c52bd1b6" > ctorMsg:<function:"invoke" args:"a" args:"b" args:"3" > > (c97bba37-6211-4a0c-b405-db823842842d)

Perhaps there's some difference between our tests....

**Comment by vpaprots** [comment]
Bizarre.. I tried Murali's master branch... and it worked.. so, out of pure paranoia.. I wiped my fork completely, created it again, wiped docker, everything... and now single peer works.

Sam is right now trying same 'trick'.

**Comment by muralisrini** [comment]
if you assume for a moment the code is identical in both cases, can you think of any other differences ?

**Comment by samding01** [comment]
After getting the latest code form Murali, now multiple nodes on Z is working. 
Thanks!

**Comment by muralisrini** [comment]
Thanks @samding01 : for reference this code is the PR #576 for issue #520
