### ISSUE TITLE
Consensus does not work between nodes running on multiple SoftLayer instances

### ISSUE THREAD

**Issue by frankyclu** [hyperledger-archives/fabric#546]
Reported by Masanobu Takagi

**Comment by muralisrini** [comment]
Can we make sure latest code is in use please ? We can then eliminate #520 as the cause.

**Comment by takagimasanobu** [comment]
I tested by using the latest obc-peer (commit 290e744ba7f7af0fb4e9a30fde3df6e56e36fc12 ) with noops consensus, and the same error as #520 happened with the following error log.

<pre>
...
03:08:53.845 [peer] SendMessage -> DEBU 946 Sending message to stream of type: DISC_GET_PEERS 
03:08:53.845 [consensus/handler] HandleMessage -> DEBU 947 Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
03:08:53.846 [peer] HandleMessage -> DEBU 948 Handling OpenchainMessage of type: DISC_GET_PEERS 
03:08:53.846 [peer] handleChat -> ERRO 949 Error handling message: Peer FSM cannot handle message (DISC_GET_PEERS) with payload size (0) while in state: created
03:08:54.310 [peer] SendMessage -> DEBU 94a Sending message to stream of type: DISC_GET_PEERS 
03:08:54.312 [consensus/handler] HandleMessage -> DEBU 94b Did not handle message of type DISC_GET_PEERS, passing on to next MessageHandler
03:08:54.312 [peer] HandleMessage -> DEBU 94c Handling OpenchainMessage of type: DISC_GET_PEERS 
...
</pre>

After this issue has been solved, Im going to test PBFT consensus again.

**Comment by kchristidis** [comment]
Thank you for updating the issue with more details.

If I get this right, this happens when running `noops`, so PBFT consensus doesn't come into play. Is that correct?

@muralisrini, @binhn: could we give this a second look?

**Comment by vukolic** [comment]
We seem to be desperately in need to convey that consensus should not be expected if noops plugin is used.

**Comment by binhn** [comment]
@takagimasanobu could you please include more info as specified here https://github.com/openblockchain/obc-test/blob/master/BugTemplate.md

The segment of logs you posted above looks normal...

**Comment by binhn** [comment]
closed as insufficient info provided to reproduce

**Comment by Abigale001** [comment]
Hey, did you solve your problem? I meet the same problem with you. @takagimasanobu
