### ISSUE TITLE
Sandbox Setup Link is Returning an http 404.

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#549]
The link to the "Sandbox Setup" is returning an http response code of 404 (Not Found).  The sandbox will be a highly used link. 

Writing Chaincode

Since chaincode is written in Go language, you can set up the environment to accommodate the rapid edit-compile-run of your chaincode. Follow the instructions on the Sandbox Setup page, which allows you to run your chaincode off the blockchain.

**Comment by angrbrd** [comment]
Closed by pull request #554
