### ISSUE TITLE
How to set logging level?

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#550]
Hi
According to the instruction, the  environment variable  OPENCHAIN_PEER_LOGGING_LEVEL can override the logging level defined in openchain.yaml. However, When I start a container like:

`docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_LOGGING_LEVEL=INFO -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer`
I still get DEBUG log info as follows:
`....
21:41:37.899 [genesis] func1 -> INFO 00f No genesis block chaincodes defined.
21:41:37.899 [state] GetHash -> DEBU 010 Enter - GetHash()
21:41:37.900 [buckettree] ComputeCryptoHash -> DEBU 011 Enter - ComputeCryptoHash()
21:41:37.900 [buckettree] ComputeCryptoHash -> DEBU 012 Returing existing crypto-hash as recomputation not required
21:41:37.900 [state] GetHash -> DEBU 013 Exit - GetHash()
21:41:37.900 [indexes] addIndexDataForPersistence -> DEBU 014 Indexing bl...
.....

How do I set the logging level correctly?

Thanks,

Sam

**Comment by bcbrock** [comment]
See issue #569

**Comment by binhn** [comment]
@samding01  assuming resolved;  if not , reopen
