### ISSUE TITLE
Sandbox Instructions

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#551]
In the sandbox,

Problem 1:
At the point of this statement:
Run the chaincode query transaction through the REST API:

POST localhost:5000/devops/query

....this does not work,  it has to be: POST localhost:3000/devops/query.  Most people will bring up a browser outside of Vagrant to run this.

Problem 2:
The display from POST localhost:5000/devops/query

Are as follows:
POST localhost:5000/devops/query

{
  "chaincodeSpec":{
      "type": "GOLANG",
      "chaincodeID":{
          "name":"mycc"
      },
      "ctorMsg":{
          "function":"query",
          "args":["a"]
      }
  }
}

200 OK
{
    "OK": {
        "Name": "a",
        "Amount": "70"
    }
}

Comment: Let's make this clear and separate the request and response.  This gives the impression everyone the 200 OK is the part of the request.   Let's really separate the request and response. 

For example,
REST Request:
POST localhost:5000/devops/query

{
  "chaincodeSpec":{
      "type": "GOLANG",
      "chaincodeID":{
          "name":"mycc"
      },
      "ctorMsg":{
          "function":"query",
          "args":["a"]
      }
  }
}

REST Response:
200 OK
{
    "OK": {
        "Name": "a",
        "Amount": "70"
    }

---

Problem 3:
It needs to be very clear that each of these windows is started in a Vagrant environment.  It is a little unclear when I go into: vagrant ssh or when I do not go into this environment.

**Comment by kletkeman** [comment]
@bmos299 Agreed. The vague "in a new window" got me for a while until I understood that you simply had to be in the same folder as the Vagrantfile in order to ssh into the running default vm. These are all nuances that would be better spelled out early on in the docs. And the fact that it is intended that the peer be built inside the vm is not all that clear until you get to the bottom of the document where it suggests that you can follow another set of instructions for building outside of vagrant. 

A wee tutorial up front would eliminate all these gotchas.

**Comment by binhn** [comment]
I 've made this priority 1 due to usability for beginners

**Comment by angrbrd** [comment]
OK, will complete by end of day. Thanks!

**Comment by angrbrd** [comment]
@bmos299 , @kletkeman 

I have made the required changes on my branch here. Please review and let me know if this addresses the concerns stated in this issue. If so, I will go ahead and merge. Thank you!

https://github.com/angrbrd/obc-docs/blob/angrbrd-doc-edits/api/SandboxSetup.md

**Comment by angrbrd** [comment]
I went ahead and merged the change to obc-docs repo. Please take a look and tell me if you have any other comments or suggestions. Thanks!

https://github.com/openblockchain/obc-docs/blob/master/api/SandboxSetup.md
