### ISSUE TITLE
Integrate state transfer into Sieve

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#566]
Related: #291

As was discussed in the scrum call today, what's blocking this integration right now has to do with rewriting the tests to accommodate the fact that execute now runs in a separate goroutine. (The path after that seems clear.)

@corecode is working on this, and @jyellick is working on the changes needed in `statetransfer`. Please use this thread to post updates.

**Comment by corecode** [comment]
Implemented in 1472ab1509a079fe9e935e09ed25cebba0b7d97c in my branch.  However, tests fail because the mock ledger is not quite behaving like the real ledger.  #579 should fix this.

**Comment by corecode** [comment]
Fixed in 5426006a0b10ee68edd985d92475f09a75c5f253.

**Comment by corecode** [comment]
PR in #597

**Comment by kchristidis** [comment]
Closed with #605.
