### ISSUE TITLE
Numerous components do not respect peer.logging.level

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#569]
Numerous components do not respect the peer.logging.level setting in openchain.yaml. The ones I have identified so far are 

```
devops, state, container, genesis, indexes, statemgmt, consensus/handler, ledger, db, buckettree, rest, eventhub_producer
```

Simply adding them to the correct place in main.go fixes the problem. If you'd like I can submit a PR with the fix. 

I wonder if it would be better to make the default in the code ERROR or CRITICAL instead of DEBUG, which would probably force/remind developers to level-set their components since they wouldn't be able to see their debug messages until they did so.

**Comment by kchristidis** [comment]
I agree with this. Raised the same issue in #310.

Please go ahead with a PR.

**Comment by bcbrock** [comment]
Closing this now that the new logging control has been implemented.
