### ISSUE TITLE
Ability to drop invalid transactions

### ISSUE THREAD

**Issue by frankyclu** [hyperledger-archives/fabric#571]
to support utxo model, there need to be an mechanism to drop invalid transactions (i.e. transactions marked invalid by chaincode execution will not get added to the ledger). this may require a separate consensus implementation, but chaincode may also need to have a mechanism to signal that to the consensus layer

**Comment by binhn** [comment]
Because of auditability, we need to keep the txs, but perhaps in a different structure; it's up to the consensus plugin to decide after validation what is valid and what is not valid. We could assume that if a call to rollback on a tx, it must mean that tx is not valid.

**Comment by frankyclu** [comment]
Auditability wouldn't really be an issue since invalid transactions will get dropped and never affect the state of the network. To fully support utxo obc need to support at least 3 things:

1) consensus module need to know whether a tx is valid - obc supports that today as consensus module can read the return value of chaincode, so we are good here 

2) consensus module need to be able to decide which transaction can be added to the block - below is the note I got from Sheehan:
_noops uses helper.go which hides some of the ledger details. noops calls CommitTxBatch which looks like i.cpi.CommitTxBatch(msg.Timestamp, txarr, nil, nil); . txarr is an array of transactions which is used to create the block. It could remove specific transactions from that array if it wanted to do so. In that case, they would not end up in the block. it looks like helper.go does not make the chaincode return value easily visible to consensus. Consensus may have to call some lower level APIs to see that return value_

3) may need to add additional APIs to shim for querying past transactions

**Comment by corecode** [comment]
What is the utxo model?

What part of the system would classify the transaction as invalid?

If the chaincode itself rejects the transaction (e.g. transfer with insufficient funds), then I would consider this a (formally) valid transaction.  To me, chaincode "rejecting" a transaction means that chaincode is processing a transaction, with a defined result.  Possibly not the result that the creator of the transaction intended, but a result that the author of the chaincode intended.

I do not see how consensus is related to this at all.  All VPs execute the chaincode in the same way, and all VPs obtain the same side effects when running the chaincode.

**Comment by kchristidis** [comment]
If there are disagreements with what @corecode suggests, can we please use this space to document them? @frankyclu @binhn

**Comment by frankyclu** [comment]
bitcoin blockchain model, in this case account balances are embedded in the (past) transactions and nothing is stored in chaincode-state.  chaincode validate and reject a spending txs if past (unspent) txs don't provide enough fund to support it. In another word, every txs in the chain represent a legal unspent balance at a point in time, so invalid txs must not be added to the chain 

This issue is on-hold due to on-going discussion with LF on how to better support bitcoin blockchain
@corecode @kchristidis

**Comment by binhn** [comment]
@frankyclu @corecode @kchristidis We rollback tx if chaincode returns errors. If that's not how it works, it should be a bug. I am closing this issue. Reopen if you think more to be discussed.
