### ISSUE TITLE
handleChat Error: Another TxGroup already in-progress

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#572]
**Summary:**

Simple stress-testing 1 validating peer with chaincode_example02 gives
numerous (putative) errors:

```
15:31:35.618 [peer] handleChat -> ERRO 619 Error handling message: Failed to begin transaction with the ledger: Another TxGroup [seconds:1454016695 nanos:616416922 ] already in-progress
```

I say putative errors because in the end, all transactions appear
to have executed correctly.

**Observed in:**

```
Commit 6844f4804c3b863e8c825af761113a6b1e594317
Merge: 1b87df0 fcaab3b
Author: Sheehan Anderson <sranderson@gmail.com>
Date:   Tue Jan 26 16:58:49 2016 -0500
```

**Priority:**

Unknown

**Keywords:**

Protocol, Dropped Transactions

**Abstract:**

Basic stress test: Can the system handle non-stop streams of transactions from
multiple clients?

**Configuration:**

1 validating peer running standalone on either an X86 or POWER8 server. I.e.,
the peer is not running in Vagrant and not running in Docker. The problem
appears in both architectures. Using the default openchain.yaml (NOOPS
consensus). 

X86 server is Ubuntu 15.10, golang 1.5.1, Docker 1.6.2
POWER8 server is Ubuntu 15.10 LE, golang 1.5.1, Docker 1.6.2 

I'm driving the peer over the network from POWER clients (which
should not be relevant).

**Scenario:**

Start the peer. Deploy the chaincode. Invoke "a gives b 1 unit"
as fast as possible a few hundred/thousand times, using one or
more driving clients. Do a final query to see if all trasfers
occurred.

It may take running 2 or 3 simultaneous instances of the stress test below to
excite the issue.

**Recreate:**

Start the peer on the server

```
cd $PEER
OPENCHAIN_PEER_ID=vp1 OPENCHAIN_PEER_ADDRESSAUTODETECT=true ./obc-peer peer
```

Deploy chaincode ($1 = target)

```
cd $PEER
OPENCHAIN_PEER_ADDRESS=$1:30303 ./obc-peer chaincode deploy -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -c '{"Function":"init", "Args":["a", "1", "b", "1"]}'
```

Stress test ($1 = target, $2 = 1000, $3 = <name of chaincode>)

```
target=$1
n=$2
name=$3

cd $PEER
export OPENCHAIN_PEER_ADDRESS=$target:30303

# Move 1 from A to B, <n> times

echo "*******************"
echo "* Initial Query   *"
echo "*******************"
./obc-peer chaincode query -n $name -c '{"Function": "query", "Args": ["a"]}'
./obc-peer chaincode query -n $name -c '{"Function": "query", "Args": ["b"]}'
echo "*******************"
echo "* Benchmark       *"
echo "*******************"
for i in `seq 1 $n`; do
    ./obc-peer chaincode invoke -n $name -c '{"Function": "invoke", "Args": ["a", "b", "1"]}'
done
echo "*******************"
echo "* Final Query     *"
echo "*******************"
./obc-peer chaincode query -n $name -c '{"Function": "query", "Args": ["a"]}'
./obc-peer chaincode query -n $name -c '{"Function": "query", "Args": ["b"]}'
```

**Comment by bcbrock** [comment]
Now that I have been able to automate this test I can now see that in many cases the system is actually dropping a few transactions.

**Comment by binhn** [comment]
@bcbrock I'll run your script above.  Have you noticed any patterns?

**Comment by bcbrock** [comment]
@binhn - The error messages are certain to appear if you run multiple clients simultaneously for more than a few transactions. The fact that an error is printed does not mean that a count is dropped, but I do not know of a pattern related to when the system actually drops the transactions and they don't appear in the state. The more clients you run the more likely this is to happen. For example I just did a run with 8 clients each sending 100 invokes: The peer printed 374 error messages but only actually dropped/missed 6 transactions. As far as I can see there is no error message specific to when the transaction is actually missed.

**Comment by binhn** [comment]
It looks like the problem is synchronization of the calls to ledger and chaincode. I am going to introduce a couple of things in noops:
1. Serialize doTransaction
2. Batch transactions based on time and size

**Comment by bcbrock** [comment]
@binhn , @muralisrini - I can't agree that this issue is fixed yet. The behavior is much more reliable, however when I run with 8 clients I am still seeing a few dropped transactions, with no logs from the obc-peer suggesting that there are errors. When it works (which is often) the peer is processing ~215 transactions/second.

When I run with 16 clients the failure is catastrophic. These message are from the peer:
2016/02/09 16:27:37 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 9.3.158.178:30303: connect: cannot assign requested address"; Reconnecting to "9.3.158.178:30303"
2016/02/09 16:27:37 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 9.3.158.178:30303: connect: cannot assign requested address"; Reconnecting to "9.3.158.178:30303"
2016/02/09 16:27:39 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 9.3.158.178:30303: connect: cannot assign requested address"; Reconnecting to "9.3.158.178:30303"
2016/02/09 16:27:39 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 9.3.158.178:30303: connect: cannot assign requested address"; Reconnecting to "9.3.158.178:30303"

I'm going to switch to using the REST API now instead of the CLI to see what happens.

**Comment by binhn** [comment]
@bcbrock I ran 6 client, each per terminal window with 1001 txs, but I didn't see any dropped txs.  Is that how you run the test?  

the connection error is interesting 
@muralisrini @jeffgarratt any thoughts?

**Comment by muralisrini** [comment]
@bcbrock : can you get the peer's container logs after the errors ?

**Comment by muralisrini** [comment]
@bcbrock : just read your summary on top and realized you are not running obc-peer in container. So scratch above comment please. 

Can you get logs from the peer ?

Also, can you try cleaning up all docker artifacts and also remove the db (rm -rf /var/openchain/production)

**Comment by bcbrock** [comment]
@binhn @muralisrini 
I did run after cleaning up Docker (see my latest comments in #614) - I had to as these errors seem to have the potential to make Docker permanently unusable.

When I run multiple clients, I run using a master script that spawns client scripts in the background. I found that by using 8 clients each doing 1000 TX that it would fail most times; but not always. I have a DEBUG-level log file from a run of 8 X 1000 that dropped 7 transactions but it is too big to attach here (5+ MB compressed). I put it on GSA: /gsa/ausgsa/home/b/c/bcbrock/web/public/log.tgz

You can run the script that I run, but it depends on the changes in PR 613 which has not been accepted yet. 
[driveEx02.txt](https://github.com/openblockchain/obc-peer/files/124101/driveEx02.txt)
Rename to driveEx02 and make executable [GITHUB is finicky about file extensions it will upload]

You also need Tcl and TclX

```
 sudo apt-get install -y tcl tclx
```

Assume <peer> is your peer's IP address (port 30303 assumed)

```
eval `driveEx02 <peer> -deployOnly` # Sets CHAINCODE_NAME for later use
# Wait until 'top' shows all obc-peer and Docker activity is gone
driveEx02 <peer> -n 1000 -multi 8
```

**Comment by binhn** [comment]
@bcbrock we count up the number of txs processed to be 8009 from the log, screenshot below. The deploy tx is not in here either.  Did you not clear out the db prior to running this test?

We would expect that 8*1000 = 8000 txs, so we don't understand where the extra 9 txs from. We don't see any info on tx processing errors either.

Could you run the CLI with debug flag  `--logging-level=debug`

```
binhn$ grep "Executing batch of " vp1_log1 
19:16:06.620 [consensus/noops] processTransactions -> DEBU a4a Executing batch of 200 transactions with timestamp seconds:1455066966 nanos:620701378 
19:16:08.232 [consensus/noops] processTransactions -> DEBU 425c Executing batch of 303 transactions with timestamp seconds:1455066968 nanos:231415142 
19:16:10.041 [consensus/noops] processTransactions -> DEBU 90c6 Executing batch of 323 transactions with timestamp seconds:1455066970 nanos:41303723 
19:16:11.886 [consensus/noops] processTransactions -> DEBU e16c Executing batch of 287 transactions with timestamp seconds:1455066971 nanos:886093578 
19:16:13.657 [consensus/noops] processTransactions -> DEBU 12c25 Executing batch of 314 transactions with timestamp seconds:1455066973 nanos:657431135 
19:16:20.456 [consensus/noops] processTransactions -> DEBU 179e2 Executing batch of 266 transactions with timestamp seconds:1455066980 nanos:456394662 
19:16:22.198 [consensus/noops] processTransactions -> DEBU 1be0a Executing batch of 269 transactions with timestamp seconds:1455066982 nanos:198535579 
19:16:23.941 [consensus/noops] processTransactions -> DEBU 202b4 Executing batch of 267 transactions with timestamp seconds:1455066983 nanos:941100432 
19:16:25.688 [consensus/noops] processTransactions -> DEBU 24633 Executing batch of 252 transactions with timestamp seconds:1455066985 nanos:688041907 
19:16:27.371 [consensus/noops] processTransactions -> DEBU 286da Executing batch of 256 transactions with timestamp seconds:1455066987 nanos:370936783 
19:16:29.076 [consensus/noops] processTransactions -> DEBU 2c7d5 Executing batch of 246 transactions with timestamp seconds:1455066989 nanos:76155138 
19:16:30.752 [consensus/noops] processTransactions -> DEBU 30793 Executing batch of 262 transactions with timestamp seconds:1455066990 nanos:752692265 
19:16:32.459 [consensus/noops] processTransactions -> DEBU 34be8 Executing batch of 289 transactions with timestamp seconds:1455066992 nanos:459773954 
19:16:34.258 [consensus/noops] processTransactions -> DEBU 3960e Executing batch of 295 transactions with timestamp seconds:1455066994 nanos:258143335 
19:16:36.059 [consensus/noops] processTransactions -> DEBU 3df35 Executing batch of 251 transactions with timestamp seconds:1455066996 nanos:59772052 
19:16:37.793 [consensus/noops] processTransactions -> DEBU 41fc7 Executing batch of 258 transactions with timestamp seconds:1455066997 nanos:793162918 
19:16:39.529 [consensus/noops] processTransactions -> DEBU 4624c Executing batch of 269 transactions with timestamp seconds:1455066999 nanos:529315695 
19:16:41.253 [consensus/noops] processTransactions -> DEBU 4a64a Executing batch of 254 transactions with timestamp seconds:1455067001 nanos:253747785 
19:16:42.996 [consensus/noops] processTransactions -> DEBU 4e803 Executing batch of 269 transactions with timestamp seconds:1455067002 nanos:996612780 
19:16:46.427 [consensus/noops] processTransactions -> DEBU 525d8 Executing batch of 132 transactions with timestamp seconds:1455067006 nanos:427199079 
19:16:47.889 [consensus/noops] processTransactions -> DEBU 550bb Executing batch of 308 transactions with timestamp seconds:1455067007 nanos:889066783 
19:16:49.751 [consensus/noops] processTransactions -> DEBU 59ebc Executing batch of 295 transactions with timestamp seconds:1455067009 nanos:750817868 
19:16:51.595 [consensus/noops] processTransactions -> DEBU 5e8cb Executing batch of 269 transactions with timestamp seconds:1455067011 nanos:595167977 
19:16:53.390 [consensus/noops] processTransactions -> DEBU 62f12 Executing batch of 299 transactions with timestamp seconds:1455067013 nanos:390484418 
19:16:55.241 [consensus/noops] processTransactions -> DEBU 67b72 Executing batch of 298 transactions with timestamp seconds:1455067015 nanos:241442172 
19:16:57.082 [consensus/noops] processTransactions -> DEBU 6c6f7 Executing batch of 287 transactions with timestamp seconds:1455067017 nanos:82715278 
19:16:58.879 [consensus/noops] processTransactions -> DEBU 7112c Executing batch of 304 transactions with timestamp seconds:1455067018 nanos:879049016 
19:17:00.716 [consensus/noops] processTransactions -> DEBU 75f2c Executing batch of 311 transactions with timestamp seconds:1455067020 nanos:716333204 
19:17:02.587 [consensus/noops] processTransactions -> DEBU 7ae85 Executing batch of 309 transactions with timestamp seconds:1455067022 nanos:587364812 
19:17:04.384 [consensus/noops] processTransactions -> DEBU 7f122 Executing batch of 67 transactions with timestamp seconds:1455067024 nanos:384657884 
```

**Comment by bcbrock** [comment]
@binhn @muralisrini - I have egg on my face...

The reason you were seeing 8009 TX is that each of my 8 background jobs was re-initializing the database. So if one thread had already done an increment and another thread re-initialized, it would appear as if transactions were being "dropped". Once I fixed this, I no longer see any dropped transactions under extreme stress.

I'm running on a 4-socket, 60-core X86 machine - the peer and all clients are local to this machine. I can drive a single peer with 64 clients using the REST API for the invokes, without error. The REST API gives much better throughput than the CLI. Throughput in this simple example tops out at about 330 TX/second once there are at least 8 clients. [The GRPC errors I mentioned before only occur with the CLI]. 

So this fix looks pretty solid to me now. Sorry for the confusion.

**Comment by binhn** [comment]
@bcbrock great, thank you for verifying and the stress test with 64 clients !
