### ISSUE TITLE
Fix naming inconsistencies in state transfer

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#577]
State transfer began life as a core part of `obcpbft`, but as its complexity grew, it was factored out, and put into its own `statetransfer` package in `consensus`.

The original names from state transfer such as `AsynchronousStateTransferValidHash` are long and cumbersome, and no longer necessary because of the package scoping.

All names including `StateTransfer` need to be modified to drop this prefix.

Additionally, the addition of error notifications in asynchronous operation has superseded the function provided by `SynchronousStateTransfer`.  This method should be removed, and any existing consumers (currently only test) migrated to the asynchronous API.

Because all calls are now based on the asynchronous API, references to `Asynchronous` should also be dropped.

**Comment by jyellick** [comment]
This is implemented as of commit https://github.com/jyellick/obc-peer/commit/2402340c07ffbb02740894765c4bce23913771f6

Waiting to generate pull request as the needed commits will not rebase cleanly onto master.  Will generate PR once Sieve integration stabilizes.

**Comment by kchristidis** [comment]
Closed with #605.
