### ISSUE TITLE
Executor interface signatures and contract must be modified

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#579]
The `CPI` defines the `Executor` interface, which includes

```
BeginTxBatch(id interface{}) error
ExecTXs(txs []*pb.Transaction) ([]byte, []error)
CommitTxBatch(id interface{}, transactions []*pb.Transaction, transactionsResults []*pb.TransactionResult, metadata []byte) error
RollbackTxBatch(id interface{}) error
PreviewCommitTxBatchBlock(id interface{}, transactions []*pb.Transaction, metadata []byte) (*pb.Block, error)
```

Today, it is not possible for `CPI` users to correctly invoke `CommitTxBatch` or `PreviewCommitTxBatchBlock` as they each require a `[]*pb.TransactionResult` which cannot be generated.

Further, `ExecTXs` currently returns the global state hash, which is computationally expensive and unnecessary, as well as an `[]error` corresponding to chaincode execution results, on which consensus should not be making decisions.

This issue is a bug, which prevents the consensus implementations from correctly executing requests.  It is intended to capture the following changes.
1. Remove the `[]*pb.Transaction` and `[]*pb.TransactionResults` parameters from `CommitTxBatch` and `PreviewCommitTxBatchBlock`
2. Update `chaincode.ExecuteTransactions` to accept the `id interface{}`, and to return a hash of the state delta produced by the transaction.  Additionally this method should track the transactions being included in the transaction batch (identified by the now supplied `id`), build the resulting `[]*pb.TransactionResult`, and supply it to the ledger for use during `CommitTxBatch`.
3. Potentially modify the chaincode execution to not return a `[]byte`.  This `[]byte` is currently not consumed by anyone.  If there is no utility to it, it should be removed.
4. Remove the `ErrorCode` from the `TransactionResult` message.
5. Convert any method signatures which uses `TX` to be `Tx`.
6. Rename `CPI` to be `Stack`
7. Update the `ExecTX` signature to accept an id, this an overlap from issue #523 
8. Rename `PreviewCommitTxBatchBlock` to simply `PreviewCommitTxBatch` and add a `*pb.Block` to the return of `CommitTxBatch`.
9. Fix all existing plugins which depend on the above, including `noops` and all of the `obcpbft` variants, as well as test.

I'm happy to tackle 1,5,6,7,8,9.  There will likely need to be a little coordination around `helper.go`, but I think @srderson has volunteered to handle 2,3,4, though these might included other side-effect tasks that I'm unaware of.

**Comment by jyellick** [comment]
@srderson Pull request #605 satisfies 1,5,6,7,8,9 above.

There are `TODO` statements in `helper.go` which should be fixed after you complete the work in 2,3,4.  I can fix those, or it should be pretty obvious if you want to take a swing at them.

**Comment by tuand27613** [comment]
After discussion with @srderson and @jyellick 
- in upcoming architecture proposals, state hash and TransactionResult might no longer be used, so item 2 and others might no longer apply 
- consensus code is being refactored via #751 

Given that, we're closing this issue. We will revisit once the team has worked through proposed architecture changes.
