### ISSUE TITLE
create image from deploy transaction if necessary

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#583]
If chaincode startup fails with "image not found", we need to create the image from the transaction and retry. This is especially needed if there's no replay on validators.

**Comment by christo4ferris** [comment]
@muralisrini is this still an issue? Or can it be closed?

**Comment by muralisrini** [comment]
@christo4ferris This can be closed...we attempt to recreate the image if not found when launching a chaincode.
