### ISSUE TITLE
Broadcast consensus messages to only VPs

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#584]
Reference: #520 and related issues

The broadcast function now accept a param to indicate either VPs, NVPs, or all.

@muralisrini

**Comment by kchristidis** [comment]
For our consensus plugins (`pbft`, `sieve`), the second argument to the `Broadcast` function should target the VPs instead of all the peers as it does now.

**Comment by binhn** [comment]
@kchristidis has this been updated that we may close this issue?

**Comment by kchristidis** [comment]
Correct. I fixed it.
