### ISSUE TITLE
Move example folder out of openchain folder

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#585]
We need to fix up our samples to be more meaningful than just chaincode_exampleXX, and move them out of openchain folder

**Comment by muralisrini** [comment]
Good to consolidate all codechain changes to cause minimum disuption. The other ones we talked about as possibly doing
- don't use "invoke" as function name in example02 (whatever it gets renamed to)
- API changes
  - naming consistency - Run method renamed to Invoke
  - Run method should not return bytes (we don't do anything with them)

@binhn should we treat everything under this issue ?

**Comment by binhn** [comment]
pre-req: #582 
@muralisrini yes, including documents where we use the chaincode examples

**Comment by srderson** [comment]
Some more suggestions
1. Give the example chaincodes and functions meaningful names. "Hello world", "Bank", "Token Transfer", etc.
2. Use a switch statement to call different functions instead of if/else blocks.

I have a "Bank" chaincode I use for testing. It has `deposit`, `withdraw`, `createAccount`, etc. functions. As we don't expose security in chaincodes yet, it may not make sense, but I could contribute as an example.

**Comment by srderson** [comment]
@muralisrini some additional thoughts after talking with you today. Here's how I think we should proceed.
1. Move the examples folder to `/obc-peer/openchain/chaincode`
2. Rename the examples folder to test and the examples to test_xx.go
3. Change tests to point to the new chaincode test location
4. Create an `/examples/chaincode/go` folder under `obc-peer`.
5. Populate it with some real examples.
6. Change documentation to point to the examples.

The reason for this is that some of the "examples" makes sense as tests, but not examples. Take 03.
`// This program is an erroneous chaincode program that attempts to put state in query context - query should return error`
Good test, bad example.

I've started on 4. and 5. I created a hello_world.go and map.go. @muralisrini do you mind if I process with these two steps?

**Comment by muralisrini** [comment]
@srderson : please do.

Also, the point about 03 is a good one. As it stands it got more a "negative test" feel than an example. However it does let the chaincode developer know what is allowed and shows what errors to look for. Such chaincode could be good examples too I think (of course with the right name, comments and so on...).

**Comment by markparz** [comment]
@muralisrini, looks like this should be closed, agree?

**Comment by srderson** [comment]
yes, can be closed now.
