### ISSUE TITLE
Node Crash Due To Memory Leak

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#589]

**Comment by bmos299** [comment]
Summary: Running a REST Query on a Single Node in a Concurrency Loop Caused A Memory Leak 

Observed in:  commit 1e08f4b767d7b84425c80916cddbe94afbc075b4

Priority:  Highest

Keywords: crash memoryleak

Description:  

 The test team was running a basic Query loop on a single node and the peer crashed due to memory exhaustion.  Murali does not believe the concurrency caused the memory leak, it only caused the crash to occur sooner. 

Abstract: 

https://github.com/openblockchain/obc-test/issues/4

Configuration: 

Scenario: 
https://github.com/openblockchain/obc-test/issues/4

== Recreate Steps ==

https://github.com/openblockchain/obc-test/issues/4

== Expected Output ==

I expected the Query loop to run for 1 hour. 

== Observed/Actual Output ==
Crash after five minutes. 

Debug:
      Basic Debug steps undertaken.   Murali was very helpful in watching the recreate.  He showed us a powerful memory profiler we can use in Go.  Dongming is going to work on setting up the profiler and will update the bug and work with Murali.

Log Data/Other Information attached
{Anything necessary to re-create the scenario and help analyze the problem.}

```
- used the default yaml file
- see attached log starting with panic
```

Verifying /Closing defects

```
  Identify which commit is used to verify the fix.
  Who and when the bug was verified.
  Root cause analysis for the bug
  New test cases written (brief summary) and is the test automated
```

[crash-reduce.txt](https://github.com/openblockchain/obc-peer/files/114523/crash-reduce.txt)

**Comment by bmos299** [comment]
Here is the YouTube video Murali showed us for setting up the memory profiler in Go.
https://www.youtube.com/watch?v=ydWFpcoYraU

**Comment by muralisrini** [comment]
I think I have a fix we can try... rather than checkin the fix, lets try to use this defect to ramp up new testers tomorrow.

**Comment by muralisrini** [comment]
some mem leak fixes in #607.

(At least) one issue still remains. gRPC NewClientStream and friends created in sendTransactionsToThisPeer are not getting GCed. All relevent transport clean up calls (in particular, Close and CloseSend) and channel notifications are in place and appear to be working as expected. One (remote and startling) possibility is local gRPC is suspect and somehow keeps references to these data structures.

**Comment by srderson** [comment]
Assuming that you are accessing the state in your chaincode query function, your scenario is affected by the memory leak described in issue #608. PR #619 has a fix and is awaiting review.

**Comment by muralisrini** [comment]
@srderson : will try the fix (will let @manish-sethi review).

**Comment by muralisrini** [comment]
@srderson : PR #619 appeared to have fixed bug #608. However it does not resolve the one issue mentioned above.  This is expected as that issue is seen when issuing chaincode queries through gRPC (current bug does not do chaincode query but goes to the ledger directly). In particular, we still see one remaining issue, we see an accumulation of objects of the following type

goroutine 178 [chan receive, 18 minutes]:
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.NewClientStream.func1(0xc8204f0000, 0xc8204c6380)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/stream.go:136 +0x7c
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.NewClientStream
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/stream.go:138 +0x869
accumulation of objects of the following type

goroutine 178 [chan receive, 18 minutes]:
github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.NewClientStream.func1(0xc8204f0000, 0xc8204c6380)
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/stream.go:136 +0x7c
created by github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.NewClientStream
        /opt/gopath/src/github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc/stream.go:138 +0x869

Bug #608 can be closed after PR #619 is is accepted.

**Comment by muralisrini** [comment]
I think there are two issues with the NewClientStream leaks...
1. we are running back level gRPC missing at least 1 relevant fix for triggering a done channel
2. possible a gRPC programming model issue where we need to  wait for EOF to trigger the aforementioned done channel

Either of the above fixes alone does not solve the issue. Together, they do. 

@jeffgarratt : can we go over this tomorrow ?

**Comment by muralisrini** [comment]
@bmos299 : @jeffgarratt accepted  PR #607. Please let us know if the mem leak is gone.

**Comment by dongmingh** [comment]
Test with the code level

commit 79c14423bf4bd0fdc0a4b427daed01f07e8fbe4b
Merge: f651e0e 9397a3a
Author: jeffgarratt garratt.jeff@gmail.com
Date:   Mon Feb 8 18:02:31 2016 -0500

```
Merge pull request #607 from muralisrini/mem_leak_fixes/issue#589

Mem leak fixes/issue#589
```

The chaincode is example02 with one peer from Vagrant.
The test case: query a, then b repeatedly.  
Use SoupUI to deploy, invoke, and query
The results show that the memory is still leaking but much slower, see below for the memory usage from command "top"

Before test run
top - 15:19:14 up 10:01,  3 users,  load average: 0.00, 0.07, 0.11
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.2 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4048232 total,  1691208 used,  2357024 free,    70200 buffers
KiB Swap:        0 total,        0 used,        0 free.  1083648 cached Mem

after run for 2 min
top - 15:23:18 up 10:05,  3 users,  load average: 2.90, 1.28, 0.55
Tasks:  92 total,   2 running,  90 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.0 us,  3.7 sy,  0.0 ni, 91.9 id,  0.2 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem:   4048232 total,  1777744 used,  2270488 free,    70204 buffers
KiB Swap:        0 total,        0 used,        0 free.  1156664 cached Mem

idle for 10 min
top - 15:33:27 up 10:15,  3 users,  load average: 0.08, 0.20, 0.30
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.5 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4048232 total,  1684460 used,  2363772 free,    70204 buffers
KiB Swap:        0 total,        0 used,        0 free.  1156664 cached Mem

after run for 20 min
top - 15:54:03 up 10:35,  3 users,  load average: 3.90, 3.61, 2.67
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.2 us,  3.4 sy,  0.0 ni, 93.0 id,  0.0 wa,  0.0 hi,  0.4 si,  0.0 st
KiB Mem:   4048232 total,  2547948 used,  1500284 free,    71136 buffers
KiB Swap:        0 total,        0 used,        0 free.  1868336 cached Mem

idle for 10 min
top - 16:03:45 up 10:45,  3 users,  load average: 0.01, 0.53, 1.44
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4048232 total,  2451868 used,  1596364 free,    71144 buffers
KiB Swap:        0 total,        0 used,        0 free.  1868336 cached Mem

idle for another 10 min
top - 16:13:11 up 10:54,  3 users,  load average: 0.00, 0.08, 0.78
Tasks:  92 total,   1 running,  91 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4048232 total,  2451836 used,  1596396 free,    71144 buffers
KiB Swap:        0 total,        0 used,        0 free.  1868336 cached Mem

**Comment by muralisrini** [comment]
its a lot better (as expected) but there still seems to be some leak. There's other ongoing leak investigation( #608 ).  

However its good to look for other mem leak instead of waiting for #608 resolution. Can you instrument the code with pprof and check ?

**Comment by dongmingh** [comment]
Attach two memory profile graphs using go pprof
memleak.pdf: after deploy and before invoke
memleak2.pdf: 5 min after test run

[memleak.pdf](https://github.com/openblockchain/obc-peer/files/123864/memleak.pdf)
[memleak2.pdf](https://github.com/openblockchain/obc-peer/files/123865/memleak2.pdf)

Crash occurs after about one hour run.

**Comment by muralisrini** [comment]
thanks @dongmingh. As discussed, will take a look.... good to know the it ran for over an hour, just doing queries...100 threads correct ?

**Comment by muralisrini** [comment]
The time.After objects are not really mem leaks. They expire after 30 secs and will be GCed at some point. I verified this in an independent test by forcing GC in a similar usage.

Can we run the test with latest code please ?

**Comment by dongmingh** [comment]
test with code level:
commit 2d59bcb3047894be789e3267b3017f72f726b25c
Merge: c62c296 0b538a6
Author: Mr. Angry adderbak@us.ibm.com
Date:   Wed Feb 10 17:52:26 2016 -0500

chaincode: example02
test scenarios:
1. invoke transaction a to b
2. query b
3. invoke transaction b to a
4 query a
repeat the above steps

The command top shows that the memory is stable.  The memory leaking issue in this bug shows that the obc-peer used to crash in about 5 minutes.
Now obc-peer runs for 9.5 hours run with no problem. 
It shows that the memory leaking is fixed at this level of code.

We do get another error message after 9.5 hour run: too many open files.
This is a different issue  and #651 is open to track this issue.

**Comment by muralisrini** [comment]
Thanks @dongmingh .... @bmos299, ok to close ?

**Comment by bmos299** [comment]
Closing.  Thanks!!
