### ISSUE TITLE
running 4 VP + security, getting GetEnrollmentCert() asn.1 parse error

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#592]
running sieve consensus of 4 validating peers with security on.

I'm getting " transport is closing"  and "GetEnrollmentCert() asn.1 parse error, truncated"

@adecaro  has the logs and is investigating

**Comment by adecaro** [comment]
Hi @tuand27613, may you run again the tests using the current master. The crypto layer shouldn't crash anymore. I'm trying to setting up docker-compose but it is taking more time than what I was expecting. Thanks.

**Comment by adecaro** [comment]
So, I got the docker-compose up and running, and, as I thought, Validator#Verify method is invoked with an empty id. Now, the validator doesn't crash anymore because the crypto layer signals correctly the error. Why id is nil, I really don't know!

**Comment by tuand27613** [comment]
thanks much @adecaro  !  I'll rebuild and see what's going on previous to the Verify() call.

**Comment by tuand27613** [comment]
I'm closing this issue as @adecaro has fixed the panic fail on GetEnrollmentCert().

Seems to be a problem in consensus regarding missing replicaIDs and pkIDs. I'll open another issue for that
