### ISSUE TITLE
Request for Profiling Services

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#596]
I would like to add an HTTP service to obc-peer, obc-ca and others (?) to support profiling. This is very easy to set up and use as documented here: https://golang.org/pkg/net/http/pprof/
I would propose to add a command line flag to enable this service, e.g.,

```
./obc-peer peer --pprof-service=localhost:6060
```

The above would spawn an HTTP server thread listening on localist:6060, using the default 'request router'. Since the current REST API services use a non-default router this shouldn't interfere with REST APIs.

Here's an example of a profile I collected this morning of the obc-peer running with security enabled:

[pprof.pdf](https://github.com/openblockchain/obc-peer/files/116610/pprof.pdf)

**Comment by muralisrini** [comment]
+1
We used pprof while debugging some memory issues.

**Comment by jeffgarratt** [comment]
@bcbrock #1179 was the re-submission of #1157.  It has been merged so this function is now present.  You can refer to https://github.com/hyperledger/fabric/blob/master/bddtests/docker-compose-4-consensus-batch.yml#L14-L18 as the mechanism for configuring through docker compose.  Perhaps this issue can now be closed?

**Comment by bcbrock** [comment]
Thanks @jeffgarratt
