### ISSUE TITLE
Security setup for testing purposes

### ISSUE THREAD

**Issue by jeffgarratt** [hyperledger-archives/fabric#598]
Wanted to start this topic to gather the proper information for settings and usage of security for testing purposes.  @binhn @elli-androulaki @adecaro @diegomasini @tuand27613

**Comment by markparz** [comment]
@jeffgarratt @adecaro can you point to a design doc at this point?

**Comment by binhn** [comment]
@jeffgarratt can we close this issue?

**Comment by christo4ferris** [comment]
closing this, think we are well on the path
