### ISSUE TITLE
Document use cases for chaincode development

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#6]
Chaincode development needs to be easy from the point of view of a chaincode developer. We need to document the use cases from the chaincode developers point of view.

**Comment by srderson** [comment]
@smkrame2 - I believe @jeffgarratt provided you with additional details about what needs to be done here. Feel free to update the task

**Comment by KramerTech** [comment]
I'm in the process of creating user stories / requirements for an ideal chailet dev experience at five levels: setup, development, testing, deployment, and maintenance.

**Comment by binhn** [comment]
@smkrame2 where are we on this issue?

**Comment by binhn** [comment]
back to backlog as Sean Kramer can't work due to time constraint on school work
