### ISSUE TITLE
Need README specifically for obc-ca

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#600]
as mentioned at the end of #580 ,  obc-ca should have its own documentation to detail user/cert configuration and any other specific security workflows.

**Comment by binhn** [comment]
@adecaro  any chance to move obc-ca to a different project that has been created? The readme that would be a natural part of that

**Comment by adecaro** [comment]
@binhn we still have the issue with the vendoring but probably it is less severe than that for the consensus part. I will try on my local machine to split obc-peer and obc-ca to see what happens.

**Comment by markparz** [comment]
Is this still valid @tuand27613 ?
