### ISSUE TITLE
OBC-CA: Ability to set configurations using environment variables

### ISSUE THREAD

**Issue by mrshah-at-work** [hyperledger-archives/fabric#621]
Like obc-peer, we should be able to configure obc-ca using environment variables. This enables us to run separate obc-ca for each network using the same docker image.

**Comment by adecaro** [comment]
@mrshah-at-ibm isn't this already provided by viper directly? For obc-ca, given that the configuration file is called obcca.yaml, you can set properties like OBCCA_SERVER_PORT, no?

**Comment by thkzrl** [comment]
That's precisely how it is implemented in the latest PR.

**Comment by markparz** [comment]
@mrshah-at-ibm are we ok to close this?

**Comment by srderson** [comment]
Closing. @mrshah-at-ibm - reopen if this is still an issue. Thanks.
