### ISSUE TITLE
Unit test github.com/openblockchain/ocb-peer/openchain/chaincode fails

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#626]
Summary: 

The README.md in the obc-peer repo. gives a procedure for running tests:

To run all tests, in one window, run ./obc-peer peer. In a second window

```
cd $GOPATH/src/github.com/openblockchain/obc-peer
go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)
```

When I do this test in github.com/openblockchain/ocb-peer/openchain/chaincode fails on my system.

I don't know if this is an issue with the docs or the code. For example, maybe more setup is assumed/required, or maybe there are other unspecified dependencies.

Observed in: 

commit 79c14423bf4bd0fdc0a4b427daed01f07e8fbe4b
Merge: f651e0e 9397a3a
Author: jeffgarratt garratt.jeff@gmail.com
Date:   Mon Feb 8 18:02:31 2016 -0500

Priority: 2

Configuration:

I'm not using Vagrant. Simply running OBC on an X86 server, Ubuntu 15.10.

The output of the entire test suite is attached.

[chaincode_test_fail.txt](https://github.com/openblockchain/obc-peer/files/122440/chaincode_test_fail.txt)

**Comment by markparz** [comment]
@bcbrock is this still valid? probably needs to be altered if so

**Comment by bcbrock** [comment]
Closing, will try again with HyperLedger
