### ISSUE TITLE
Bug in Ledger CommitTxBatch error case handling

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#632]
I believe there is a programming error in the `CommitTxBatch` function of `ledger.go`.

```
success := true
defer ledger.resetForNextTxGroup(success)
defer ledger.blockchain.blockPersistenceStatus(success)
stateHash, err := ledger.state.GetHash()
if err != nil {
  success = false
  return err
}
```

The intent of this code is to have the defer functions run with `false` as the input parameter, but that will not happen according to the following example https://play.golang.org/p/7pQHdeDp-l

**Comment by binhn** [comment]
I think it is closure;  we can change `success` to a pointer and pass that; ie

```
psuccess := &success
defer ledger.resetForNextTxGroup(psuccess)
```

we have to change `ledger.resetForNextTxGroup` signature to `ledger.resetForNextTxGroup(p *bool)`

**Comment by srderson** [comment]
Yes, the problem is other locations call it using `ledger.resetForNextTxGroup(true)` or `false` directly and I don't think there's an easy way to turn those into a pointer without creating a variable.

@muralisrini also suggested using a function so the closure is evaluated lazily. https://play.golang.org/p/Z8dQTaEkVz. While I think this is another clean approach, I also want to call those functions before `producer.Send` executes at the end of the function to ensure the ledger is fully updated before sending a block event.

I guess you could have some kind of if statement in the defer closure so it only ran on error conditions, but that felt less readable to me as opposed to just duplicating the code in a few spots.
