### ISSUE TITLE
chaincode container recreation fails with invoke or query

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#648]
We create containers at the time of deploy and used the last element of the path name for the executable name as that's the name "go" gives to the executable. 

As long as the container is not deleted everything is fine.

If the container is deleted (say for "cleaning up") the next invoke or query will attempt to create one.  At that point, the code tries to name the executable based on the path (as during deploy) but now the path field is empty. So the chaincode executable build fails and the container cannot run the chaincode.

The proposed solution is to use the generated chaincode ID for the executable name instead of generating it from path name. This is both unique and natural. It IS long and unreadable but that should not matter as this is totally internal. It affects neither users nor docs. And we can clean up with impunity as the next invoke or query will create the container and find the executable in the image.

thanks to @ragupta2 for working with me on this...

**Comment by kletkeman** [comment]
One thing I have been hoping for, and this looks like an ideal time to consider it, is bringing back the name field on deploy. But this time using it as a nickname. This allows an application developer to choose a reasonable moniker (mandated to have a high chance of uniqueness) by which the contract is known, allowing app developers to not have to worry about storing and disseminating the magical handle globally. 

It also solves this problem elegantly with readable container names, which will greatly aid in debugging contracts, and probably the fabric ...

**Comment by muralisrini** [comment]
@kletkeman : sure, we can consider that but wanted make sure we understand the chaincode name (external) is different from the chaincode exec name (internal). This issue is about chaincide exec name.

**Comment by kletkeman** [comment]
@muralisrini Ah, ok, makes sense. I assumed that they could perhaps be the same name, but of course we need something entirely unique, which the UUID provides. The nickname does not necessarily have to be unique, since the peer would be able to match nickname and credentials / API key or some such.

**Comment by christo4ferris** [comment]
@muralisrini is this still relevant/an issue? or can it be closed?

**Comment by muralisrini** [comment]
@christo4ferris this can be closed as the original issue was fixed. @kletkeman 's point of allowing for names will be addressed with naming service in next release.
