### ISSUE TITLE
Hash function

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#65]
We need a utility function to hash an array of bytes or a string and return the hash value

**Comment by manish-sethi** [comment]
@binhn there are already in-built functions in 'go' package golang.org/x/crypto/sha3 for computing hash of data. 
@srderson and me are using ShakeSum256 in hash computation. Is it something else that you want on top?

**Comment by binhn** [comment]
@manish-sethi yes, my motivation is to encapsulate 1 function for all of us to use, whichever strength level we decide to use, so that we can be consistent.  And if problems discovered later on, we would only need to fix at 1 place.
