### ISSUE TITLE
Error: grpc server exited with error: accept tcp [::]:30303: accept4: too many open files

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#651]
Code level:

commit 2d59bcb3047894be789e3267b3017f72f726b25c
Merge: c62c296 0b538a6
Author: Mr. Angry adderbak@us.ibm.com
Date:   Wed Feb 10 17:52:26 2016 -0500

Chaincode: example02

Test scenarios:
invoke transaction from a to b
query b
invoke transaction from b to a
query a
repeat continuously

It runs for about 9.5 hours then stops with error message (obc-peer screen message):

09:51:29.365 [rest] Invoke -> INFO a7acb0 REST invoking chaincode...
09:51:29.366 [rest] Invoke -> INFO a7acb1 REST invoking chaincode...
09:51:29.366 [rest] Invoke -> INFO a7acb2 REST invoking chaincode...
09:51:29.367 [rest] Invoke -> INFO a7acb3 REST invoking chaincode...

Usage:
  openchain peer [flags]

Flags:
  -h, --help[=false]: help for peer
      --peer-chaincodedev[=false]: Whether peer in chaincode development mode
      --peer-discovery-enabled[=true]: Whether peer discovery is enabled
      --peer-gomaxprocs=2: The maximum number threads excuting peer code
      --peer-port=30303: Port this peer listens to for incoming connections
      --peer-tls-cert-file="testdata/server1.pem": TLS cert file
      --peer-tls-enabled[=false]: Connection uses TLS if true, else plain TCP
      --peer-tls-key-file="testdata/server1.key": TLS key file

Global Flags:
      --logging-level="": Default logging level and overrides, see openchain.yaml for full syntax

Error: grpc server exited with error: accept tcp [::]:30303: accept4: too many open files

**Comment by srderson** [comment]
Is this within the Vagrant image? `ulimit -a` reports that the open files limit is 1024 which seems low. We may just want to consider increasing this.

**Comment by srderson** [comment]
Can you use the `lsof` command and get a list of the open files so we can see who is responsible?

**Comment by muralisrini** [comment]
moving to @srderson (thanks!)

**Comment by srderson** [comment]
@dongmingh Also, can you let me know the size of your DB after running this test?

**Comment by bcbrock** [comment]
I just got a similar error running on a POWER system. My test is very similar to the original poster's, driving example 02 with the REST API. My file limit is also 1024. The `lsof` shows that I have 852 files open after the crash (wow - never knew it was so many - I will up my file limit). Here is the database size:

```
[bcbrock@pgpu2]$ du /var/openchain
86196   /var/openchain/production/db
86200   /var/openchain/production
86204   /var/openchain
```

**Comment by srderson** [comment]
Thanks @bcbrock. With default settings, RocksDB says the expectation is one file open per 2mb. There's also a `max_open_files` configuration in RocksDB that defaults to 1000. I'm not positive what happens if (size of your DB in mb / 2) > 1000. Maybe there's just a performance degradation? If you could up your max file limit to 2048 I'd be curious if the problem goes away or if you hit the issue at a larger DB size.

**Comment by srderson** [comment]
For reference, @dongmingh mentioned that his DB size was 1.6GB.

**Comment by binhn** [comment]
RocksDB works for a very big website (i would guess hundreds of terabytes?), so max_open_files should be much higher than 1000

**Comment by srderson** [comment]
For the RocksDB max_open_option default option, I was looking at an old comment. In the version we're using it says "Default: 5000 or ulimit value of max open files (whichever is smaller)"

So we should test with max open file limits of > 5000. Perhaps 10,000

**Comment by bcbrock** [comment]
I've set the open file limit on my POWER server to 64K. I looked in the RocksDB log and saw that it was using 5000:

```
2016/02/11-15:18:37.526042 3fffa9bb90b0           Options.max_open_files: 5000
```

**Comment by srderson** [comment]
Current status:
1. I've updated the vagrant image so the max open file limit will be 10,000. See https://github.com/openblockchain/obc-dev-env/pull/43
2. I've updated the documentation for building outside of vagrant to note this setting. https://github.com/openblockchain/obc-peer/pull/655
3. @dongmingh is running a test overnight with max open files for his OS set to 7000 to make sure the issue is not encountered.
4. @mrshah-at-ibm will increase the file size limit is his environment.

@bcbrock Let me know if the problem is gone now that you've increased the file limit on your system.

**Comment by bcbrock** [comment]
@srderson - I have not seen the issue again since increasing the open file limit

**Comment by srderson** [comment]
Thanks @bcbrock for the update. @dongmingh also reports that he was able to run for 13+ hours overnight. I'm going to close this issue as increasing the file limit appears to have resolved the problem.

**Comment by dongmingh** [comment]
According to Sheehan:
In the Vagrant image, the limit will now be set higher  
For people running outside of Vagrant, I added some documentation:
https://github.com/openblockchain/obc-dev-env/pull/43/files
https://github.com/openblockchain/obc-peer/pull/655/files

**Comment by corecode** [comment]
Changing ulimits only obscures this bug, but does not fix it.  Ultimately, we need to handle the grpc error gracefully, instead of shutting down the peer.
