### ISSUE TITLE
Error msg occurs when one peer processing "invoke" requests

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#654]
When running a single peer without docker and let it process invoke requests, it is observed that the throughput (processed  invokes/seconds ) as well as cpu utilization decrease with the time. Error message is output as:

> taskset 0x01 ./o-peer peer --peer-chaincodedev
> 2016/02/11 15:17:08 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30303: connect: cannot assign requested address"; Reconnecting to "0.0.0.0:30303"
> 2016/02/11 15:17:08 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30303: connect: cannot assign requested address"; Reconnecting to "0.0.0.0:30303"
> ...
> 2016/02/11 16:07:36 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30303: connect: cannot assign requested address"; Reconnecting to "0.0.0.0:30303"

Replication steps:

1) set the logging level = CRITICAL;
2) start obc-peer `taskset 0x01 ./o-peer peer --peer-chaincodedev`
3) start example02:  `OPENCHAIN_CHAINCODE_ID_NAME=obc OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 taskset 0x01 ./chaincode_example02 >/dev/null`
4) Deploy: `./obc-peer chaincode deploy -n obc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`
5 using jmeter to send invoke requests, 20 theads, forever loop:

> POST http://x.x.x.x:5000/devops/invoke 
> POST data:
> { "chaincodeSpec": { "type": "GOLANG", "chaincodeID": { "name":    "obc" }, "ctorMsg": { "function": "invoke", "args": [ "a", "b", "2" ] } } } 

Then the error message occurs periodically. Would like to know if this is related to configuration.

**Comment by muralisrini** [comment]
@samding01 : there have been several recent fixes. If you have not already done so, can you try with latest please ?

Also how long does it take for the error messages to start showing up ?

**Comment by samding01** [comment]
@muralisrini : Tested with the latest master code, get the same error msg periodically and the behavior similar to the before.

> 2016/02/11 16:53:06 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30303: connect: cannot assign requested address"; Reconnecting to "0.0.0.0:30303"

Thanks,

**Comment by samding01** [comment]
The error msg  starts to show after it run less than 1 minutes in my Z machine

**Comment by bcbrock** [comment]
@muralisrini @samding01 - This may be similar to something I mentioned in passing in #572 

When one is running with multiple clients as here, are multiple versions of chain codes running simultaneously? Are multiple GRPC connections being made between chain codes and the peer? It seemed to me that GRPC was very fragile in the face of multiple connections. As I mentioned there (#572) running 16 CLI clients (16 GRPC connections to the peer) always caused this failure, and sometimes I even saw it with only 8 CLI clients.

**Comment by samding01** [comment]
[obc3.zip](https://github.com/openblockchain/obc-peer/files/127194/obc3.zip)
attached is jmeter plan. 
@bcbrock: in my case, I started only one peer and one chaincode (example02).

**Comment by bcbrock** [comment]
@samding01 - Yes, but I understood that you had 20 threads driving traffic simultaneously

**Comment by muralisrini** [comment]
@bcbrock : there is 1 grpc connection between chaincode and peer. I'm not sure where that connection error is coming from. Could it be related to the open file issue #651 ? 

@samding01 : can you try the test after "rm -rf /var/openchain/*" and restarting peer ?

**Comment by binhn** [comment]
The only connection that gets re-established is between the rest API and the peer in this case.

This error msg comes directly from `google.golang.org/grpc/clientconn.go`:

```
grpclog.Printf("grpc: ClientConn.resetTransport failed to create client transport: %v; Reconnecting to %q", err, cc.target)
```

and it retries.  So I guess the retry was successful b/c it didn't return the error to us.

The question is why.  I guess too many connections since the processing is async ?

**Comment by samding01** [comment]
Updated:
1) Got the latest master code and removed the /var/openchain/*, run the same scenario and got the same error msg.
2) It gets error msg also if I send invoke request in 10 threads from jmeter

**Comment by muralisrini** [comment]
@samding01 : lets eliminate issue #651 by increasing fd limit with "ulimit -n 10000" and try please. Also remove /var/openchain/*

**Comment by muralisrini** [comment]
After playing with the system and test case for a bit in @samding01 environment, we found the requests were queing up and the tcp stack wasn't cleaning up stale connections fast enough. @bmos299 suggested tuning TIME_WAIT interval (using /proc/sys/net/ipv4/tcp_tw_recycle) and sure enough that stopped the TCP connection errors and system was stable and processing for more than 10 mins ( @samding01 : can you fill test parameters for records please ?)

@bmos299 : we may want to have a policy/bestpractice around this setting ? Will move this to you.

**Comment by samding01** [comment]
Thank @muralisrini  for debugging and solving this issue. 
The test plan is in https://github.com/openblockchain/obc-peer/files/127194/obc3.zip.
Invoke requests are sent in 20 threads, no wait time between requests, loop forever.

**Comment by samding01** [comment]
One question:
It is observed that the CPU utilization and the throughput of invoke  are going down with the time. The  CPU utilization changes from 100% at the beginning to 35%, and the  throughput of invoke   from 350/s to  220/s in 10 minutes even the memory of  obc-peer and chaincode is not found changing.
This may implicate other issue.
As there is much communication between peer and chaincode, it seems TCP/socket is not reused as we observed open socket number growing up if   the WAIT_TIME is kept as default (2 minutes). Do you use connection pool ( that allows reuse opened sockets ) in the communication?

**Comment by muralisrini** [comment]
@samding01 there is no connection pool at the obc-peer level. There might be at grpc level (@jeffgarratt might know).

Can you do an experiment with a small delay (say 50ms) and see if the CPU keeps steady ?

I suggest we create a new issue to track the CPU going down.

**Comment by samding01** [comment]
will open a new issue on CPU utilization going down, and close this.
