### ISSUE TITLE
Transaction functions

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#66]
We need the following functions on ledger to manage the block transaction
- begin(ID) – begin transaction for block number ID
- commit(ID, proof) – write block and changes to ledger; write proof to audit
- rollback(ID) – remove all changes within transaction scope ID

**Comment by manish-sethi** [comment]
@binhn I need a few clarifications...

I am assuming ID here to be block number. please correct me if you meant something else here by ID.

1) begin(ID) – begin transaction for block number ID 
I am just wondering does ledger even need to know the beginning of next block processing. What do you intend to do in the ledger when this gets invoked on ledger?

2) commit(ID, proof)
This method needs to have the block as well. Also, I need to understand the proof part... What is the proof here?

3) Assuming block#20 gets rolled back then next block ID is going be 20 or 21? In other words, can there be holes in block numbers in block chain?

**Comment by kchristidis** [comment]
Chiming in here, @binhn will correct me if I'm wrong.

A2: Let's go with PBFT. `proof` is the so called certificate in the [PBFT paper](http://research.microsoft.com/en-us/um/people/mcastro/publications/p398-castro-bft-tocs.pdf), i.e. a collection of at least 2f+1 signed messages (from an equal number of validators) that are exchanged during the COMMIT phase. We'll keep these in a temporary datastore in the PBFT module (I got an issue on this one coming up), and pass them along to you when we're done with the COMMIT phase.

A3: Next sequence number is going to be 21. Though we're striving for dense numbering, there will be holes when there are disagreements or faults.

A1: I'm not clear on the use of `begin(ID)` either. Just a function that's used in the `while` loop that processes the transactions within block `ID`?

**Comment by binhn** [comment]
First of all, the sequence begin, commit, rollback is a transactional scope pattern, and a good pattern to keep. On the begin(), I thought the Ledger needs to know to set up the scope; eg preparing the temp space, struct, etc. Even if we don't have anything to do, I still think it's a good pattern to follow for now. We might need it later :-)

**Comment by binhn** [comment]
@manish-sethi about the ID, for our BFT implementation, it is the block number, but other algorithms might not use block number, so we shouldn't build dependency on that, and the block structure would be something that we create, not the algorithms. Let me know if this might cause problem.

**Comment by manish-sethi** [comment]
@binhn so, "number" in API "Get block by number" in issue #42 should be independent of consensus algorithm?
This means that we have an internal block number (always increments without holes) and we have a separate identification (which could be block number or  something not even a number) of the block specific to the consensus algorithm?

**Comment by binhn** [comment]
@manish-sethi right, the fact that blockchain is a chain of blocks via crypto is to ensure immutability of the content, and we can build it any how we want to independence of the batching of the transactions during consensus. We are kind of treating that block on the blockchain the same as the batch of transactions for conveniences and influenced by bitcoin protocol.  The fintec calls it ledger since they can careless about blocks. Therefore, we should treat a unit of work produced by a consensus round (whether a batch of tx's or individual tx) as an immutable and auditable unit.

**Comment by srderson** [comment]
@manish-sethi To answer our questions, the interface should look like

begin(ID) – ID is consensus ID
Chaincode is executed by @muralisrini. He will be updating the state during execution.

commit(ID, transactions[], proof) – write block and changes to ledger; write proof to audit
At this point, we create a block with array of transactions, and commit the block. For m2, we ignore proof.

rollback(ID) – remove all changes within transaction scope ID
If this is called, we clear the state

begin(ID) will always be followed by a call to either commit(...) or rollback(...) with the same ID. If this order is not maintained, we can return an error. For example, begin(...) will never be called twice in a row with two different IDs.

The ID does not need to be stored in the DB. It's only help in memory to match the ID used for begin() and either commit() or rollback(). There is no API to ask about the ID after commit() or rollback() is called. We can throw it away after one of those functions is called.
