### ISSUE TITLE
Error message on validating peer after sending a 'deploy' command from command line

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#660]
## Steps executed:
1. Setup up security before running chain code commands.
2. Launched validating peer, chain code window and another terminal to run CLI commands to execute transactions successfully.
3. Ran the following 'deploy' command
   "./obc-peer chaincode deploy -n mycc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'" 
   from third terminal (to to test chaincode commands).
## Actual Result:

On the chaincode window I see message as expected
"2016/02/12 15:36:04 [mycc]Received INIT, initializing chaincode
Aval = 100, Bval = 200"

On the validating peer around the same time following error message was displayed:

15:36:02.640 [CRYPTO] InitClient -> INFO 03c Initializing client [jim]...done!
15:36:02.644 [CRYPTO.client.jim] selectNextTCert -> **_## ### ERRO 03d No TCert in cache found_**.
15:36:03.583 [CRYPTO] closeClientInternal -> INFO 03e Closing client [jim]...
15:36:03.584 [CRYPTO.client.jim] close -> INFO 03f Closing keystore...
15:36:03.584 [CRYPTO.client.jim] close -> INFO 040 Closing keystore...done!
15:36:03.585 [CRYPTO] closeClientInternal -> INFO 041 Closing client [jim]...done! [<clean>].
15:36:04.618 [ledger] sendProducerBlockEvent -> ERRO 042 Error unmarshalling deployment transaction for block event: proto: can't skip unknown wire type 6 for protos.ChaincodeD
## Expected Result:

No error messages to be seen on validating peer window.

**Comment by 2016Nishi** [comment]
Also at the end of executing deploy, invoke and query commands I see the following messages on validating peer:

---

15:46:41.269 [CRYPTO.client.jim] close -> INFO 05c Closing keystore...
15:46:41.270 [CRYPTO.client.jim] close -> INFO 05d Closing keystore...done!
15:46:41.270 [CRYPTO] closeClientInternal -> INFO 05e Closing client [jim]...done! [<clean>].
_15:57:31.208 [chaincode] processStream -> ERRO 05f Error handling chaincode support stream: connection error: desc = "transport is closing"

## _

Looks like chaincode has run into issue while processingstream before closing the connection.

P.S. This is after running commands as a secured user.

**Comment by adecaro** [comment]
I see the same lines. Regarding the following line

15:36:02.644 [CRYPTO.client.jim] selectNextTCert -> ## ### ERRO 03d No TCert in cache found.

This is not really an error. I will downgrade to debug.

**Comment by 2016Nishi** [comment]
Tested with latest commit level f309b74 from command line:
1. Launched member services server from terminal-1.
2. Started peer in dev mode on terminal-2
     ./peer node start --peer-chaincodedev
3. Opened chaincode for requests from terminal-3 using:
       CORE_CHAINCODE_ID_NAME=mycc CORE_PEER_ADDRESS=0.0.0.0:30303 ./chaincode_example02
4. Finally issues a deploy command from CLI successfully from terminal-4:
   peer chaincode deploy -n mycc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
5. Following messages were verified on terminal-3 to ensure deploy in step4 was good.
   
   20:19:14.903 [shim] DEBU : Entered state init
   20:19:14.903 [shim] DEBU : [mycc]Received INIT, initializing chaincode
   Aval = 100, Bval = 200
   20:19:14.903 [shim] DEBU : [mycc]Inside putstate, isTransaction = true
   20:19:14.904 [shim] DEBU : [mycc]Sending PUT_STATE
   20:19:14.905 [shim] DEBU : [mycc]Received message RESPONSE from shim
   20:19:14.905 [shim] DEBU : [mycc]Handling ChaincodeMessage of type: RESPONSE(state:init)
   20:19:14.905 [shim] DEBU : [mycc]before send
   20:19:14.905 [shim] DEBU : [mycc]after send
   20:19:14.906 [shim] DEBU : [mycc]Received RESPONSE, communicated (state:init)
   20:19:14.906 [shim] DEBU : [mycc]Received RESPONSE. Successfully updated state
   20:19:14.906 [shim] DEBU : [mycc]Inside putstate, isTransaction = true
   20:19:14.906 [shim] DEBU : [mycc]Sending PUT_STATE
   20:19:14.906 [shim] DEBU : [mycc]Received message RESPONSE from shim
   20:19:14.906 [shim] DEBU : [mycc]Handling ChaincodeMessage of type: RESPONSE(state:init)
   20:19:14.906 [shim] DEBU : [mycc]before send
   20:19:14.906 [shim] DEBU : [mycc]after send
   20:19:14.907 [shim] DEBU : [mycc]Received RESPONSE, communicated (state:init)
   20:19:14.907 [shim] DEBU : [mycc]Received RESPONSE. Successfully updated state
   20:19:14.907 [shim] DEBU : [mycc]Init succeeded. Sending COMPLETED
   20:19:14.907 [shim] DEBU : [mycc]Move state message COMPLETED
   20:19:14.907 [shim] DEBU : [mycc]Handling ChaincodeMessage of type: COMPLETED(state:init)
   20:19:14.907 [shim] DEBU : [mycc]send state message COMPLETED

**Comment by 2016Nishi** [comment]
Deployed as user "test_user0" with security enables and did not see the messages as described in original bug:

Following messages were seen on peer - terminal2
20:47:52.352 [crypto] Login -> INFO 022 Registering client [test_user0] with name [test_user0]...
20:47:52.413 [crypto] register -> INFO 023 [client.test_user0] Register crypto engine...
20:47:52.414 [crypto] register -> INFO 024 [client.test_user0] Register crypto engine...done.
20:47:52.414 [crypto] Login -> INFO 025 Registering client [test_user0] with name [test_user0]...done!
20:47:52.414 [rest] Register -> INFO 026 Storing login token for user 'test_user0'.
20:47:52.414 [rest] Register -> INFO 027 Login successful for user 'test_user0'.
20:48:29.161 [crypto] Deploy -> INFO 028 Initializing client [test_user0]...
20:48:31.463 [crypto] Deploy -> INFO 029 Initializing client [test_user0]...done!
20:48:31.465 [crypto] CloseClient -> INFO 02a Closing client [test_user0]...

Since no error similar to : "15:36:02.644 [CRYPTO.client.jim] selectNextTCert -> ## ### ERRO 03d No TCert in cache found."  was reported closing this bug as Not Reproducible anymore.
