### ISSUE TITLE
CPU utilization and inovoke processing rate going down in load test

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#663]
Following #654,  it is observed that CPU utilization and invoke processing rate going down. 
Attached snapshots in [obc4.zip](https://github.com/openblockchain/obc-peer/files/128619/obc4.zip) 
shows cpu utilization from 100% down to 29% and invoke processing rate from 313/s to 212/s after 13 minutes. 

Replication step: (same as that in #654 )
1) Set the logging level to CRITICAL on both peer and chaincode_example02;
2) start peer , chaincode_example02 and deploy, individually. use `taskset <mask>` to put the both on a cpu:

> $  taskset 0x01 ./obc-peer peer --peer-chaincodedev
> 
> $ OPENCHAIN_CHAINCODE_ID_NAME=obc OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 taskset 0x01 ./chaincode_example02 

3) Start jmeter, open attached jmeter plan (obc4.jmx), update the IP and start;
Note in jmeter plan, invoke requests are sent by 20 threads, 50ms interval (tested different intervals and get the similar result)

**Comment by muralisrini** [comment]
@samding01 : does it stay at 29% CPU level or processing stops completely at some point ?

what happens if you don't tie to 1 cpu

**Comment by binhn** [comment]
It sounds like io bound.  Could someone look into perf profile.

**Comment by samding01** [comment]
@muralisrini Actually both cpu utilization and request rate went  down gradually. Finally Jmeter got crash as out of memory on windows

If not bind to a single cpu, CPU utilization is from 17% (8 cpu cores) to 5.4%, and invoke processing rate from 550/s to 280/s in 10 minutes. Here is snapshot nmon after 10 minutes
[nmon.zip](https://github.com/openblockchain/obc-peer/files/128685/nmon.zip)

**Comment by muralisrini** [comment]
jmeter got crash with OOM ? Perhaps problem with jmeter and not obc :-) ?

**Comment by muralisrini** [comment]
@samding01 : did a scaled down version testing with 10 clients (as opposed to your 20) doing invoke in a tight loop. But changed the internal buffer from 100 to 1 to really stress the system (and compensate for the smaller number of clients). I also made sure to set the TIME_WAIT interval to a low value tcp stack is not a bottleneck.

CPU remained steady and no errors.  Could you perhaps try with a different tool just for another datapoint ?

**Comment by samding01** [comment]
@muralisrini :  Tested again. When found cpu utilization goes down, started a new instance of jmeter, and found that  CPU utilization goes up again. Yes, you are right, this seems problem of jmeter. 
Thanks,

**Comment by muralisrini** [comment]
thanks, @samding01 . Appreciate your taking the time and effort !
