### ISSUE TITLE
NOTICE!! Repo to go public soon.

### ISSUE THREAD

**Issue by markparz** [hyperledger-archives/fabric#665]
Hello everyone, thank you very much for your participation in this repo. This is a message to let each person know that the repo will soon become public via the Linux Foundation's Hyperledger project. In order to make this public we will remove all the users currently in the repo, as it will no longer be required. If you have any questions feel free to reach out to me via comment. 

Again, thank you and see you in the open community!

@adecaro @ajuels @akindakind @akohli @AlbertHristov @baronsz @bartfaitamas @Bartman250 @bcbrock @beaufort2015 @cblsjtu @cboulangfr @cca88 @ccorley @chaean @dan-turner @DanielFeichtinger @danoprey @danteguintu @dazraf @e27185 @ebuchman @ecb @edelsohn @efeg @Findekind @flashgorman @frankyclu @frosenberg @Fukunaga42 @gdhh @gendal @genecyber @gerrith3 @ghaskins @hagbard5235 @hampsonm @harrika1982 @harrisondkurtz @hdiedrich @ibmjerry @igortmp @ijmitch @isramos @ItsMathU @jachtermann @jafaeldon @jafaeldon @jamescarlyle @jcahue @jeaha @jeffgarratt @JerryCuomo @jyellick @kchalla123 @kchristidis @keishsen @kevinSuttle @kk-melbourne @kletkeman @klm42 @ItsMathU @hudsont @ale-aso @alexmnguyen @alohr51 @alrung17 @amiller @arikundu @arner @Andreayurei @andresgaragiola @angrbrd @annemariedevries @ant2221 @benjsmi @benksmillie @bhaesler @binhn @biaohao @benksmillie @billotosyr @bmandler @bmos299 @bobcallaway @brgopal @bryanpkc @ChrisBaroque @burrowsg21 @AtsushiKawamura @awjh @chenyux @chetan @chetmurthy @ChrisBaroque @chrisfranko @chrispoole643 @christo4ferris @dco-bot @denzilmenezes @devrandom @diegomasini @dileban @dongmingh @DonnaDillenberger @dsbaars @dubek @dulcep @dwk3 @el33th4x0r @elli-androulaki @EmmanuelViale @entiq @expsam @esgott @erbens @erikschaberg @esgott @expsam @gitwouter @GiuseppeGiordano @guikarai @GwilymNewton @gnailuh @guikarai @gnailuh @gongsu832 @gitwouter @hironori-jp @hmckinne @hudsont @ItsMathU @jyg007 @jpayne23 @johncohn @johndydo @jhallen @jimthematrix @jjustj @jkbbwr @jkoibm @jln95 @JohnP261 @jonasnick @joncmu @JoostVanT @jwolpert @joshhus @josroling @JulienGueguen @JustinPainter @justmoon @knoid @latone @lc82lc82 @lehors @leninmehedy @lgennady @liebera @liujed @lowry1515 @LucaSchiatti @manish-sethi @mansweet @masterDev1985 @mastersingh24 @mcenatie @meetayadav @michaeldowling @michaelrowe01 @mikesmo @mitaD @mitar @mkayaalp @mkdolan @mkohari @mmartinsca @movee2016 @mqmatt @mrhornsby @mrshah-at-ibm @muralisrini @nickgaski @nimmaj @nitingaur6817 @nitingaur6817 @nobleg @novusopt @odaira @ODOWDAIBM @oflondontown @Ohsaworks @ozzyathome @pbournho @phedny @phylecypher @pinkgrass @pkodeswaran @pmullaney @pralhdes @prjayach @ragupta2 @rajones27 @rakeshm100 @rameshgopinath @rameshthoomu @raullaprida @raymundl @rbrinkma @retroeater @rguikers @ricegchen @RicHernandez2 @rsram10 @ruslan120101 @sachikoy @sagmeister1 @sajarvis @samding01 @sanaziauddin @sbrakev @sdsen @seanbarclay @sehagens @shaulkf @shmul @sictune @Sjvandam @slgarkea @smithbk @smkrame2 @sngovi @Souptacular @spipes @srderson @StephaneC @steveg192 @StevenYangChina @sumanair @svloosbroek @takagimasanobu @tamasblummer @tenc @theathibm @thkzrl @toddarnold @tonyhickman @troyronda @tsariounov @unrealutkarsh @vitabortnikov @vpaprots @VRamakrishna @vugranam @vukolic @weedcocco @winghong @Y-Ushiro @yateeshk @yinzhuca @ymchee

**Comment by seanbarclay** [comment]
Nice! What's the new repo URL going to be when it moves?

**Comment by seanbarclay** [comment]
@markparz @binhn^^

**Comment by christo4ferris** [comment]
@seanbarclay it isn't moving, just going public.

**Comment by seanbarclay** [comment]
Sounds great and thanks @christo4ferris. Just wanted to make sure.

**Comment by guikarai** [comment]
Nice! It sounds like imminent?

**Comment by kevinSuttle** [comment]
Right, but isn't the name going to change?

**Comment by kletkeman** [comment]
@kevinSuttle The latest comments I've seen on the OBC slack channels is that it goes public under the same name for now.

**Comment by kevinSuttle** [comment]
That seems in direct contradiction to the message posted, though?

**Comment by chenyux** [comment]
https://www.hyperledger.org/

**Comment by chenyux** [comment]
https://github.com/hyperledger/hyperledger

**Comment by binhn** [comment]
OBC has gone public since yesterday. Check it out https://github.com/openblockchain

**Comment by kletkeman** [comment]
EDIT: Ok, I am not a ninja-level git user, so I was unaware that my clones would be made private by definition. All is well now that I made them public again.

**Comment by kletkeman** [comment]
@kevinSuttle So it looks like both will exist, for now ...

**Comment by jyellick** [comment]
@kletkeman 

Because the clones were private, github does not automatically make them public, in case you had some private work in them.  You should be able to recover by simply going to your github page, and for each clone, go to settings, then delete (in the 'danger zone' near the bottom).  Then return to the openblockchain page for that piece, and click fork again.  This will restore the links, and your local git repositories should all remain working, as the remote URLs will not have changed (though they were deleted and recreated).

**Comment by kletkeman** [comment]
Thanks @jyellick I made mine public this morning to get going again as I have not been pushing my code to the repo anyway.

**Comment by lehors** [comment]
I confirm what @jyellick said. I just went through this process and it worked for me.

**Comment by angrbrd** [comment]
The repo has been public for two weeks now. Closing this notice. Thanks.
