### ISSUE TITLE
ChainCode 'Invoke' via Rest request failed

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#668]
## Steps executed:

When I ran 'Query POST Request' on chaincodeexample02 as documented in 'SandboxSetup.md'

my post request failed with following message 

{
  "Error": "Error:Failed to launch chaincode spec(Failed to init chaincode(handler not found for chaincode mycc))"
}

Tested on SOAPUI and POSTMAN. It failed on both tools with the same message.

Used code from yesterday(02/10/2016):
i.e.  git rev-parse HEAD = 4dc4718780efb066155a4bbe8c082a3665d08319

**Comment by kletkeman** [comment]
Not much detail there ... so let me take you through the steps I used (on yesterday's code) ... I'll show the actual deploy using the devnet setup instead, but you just substitute the name field with "mycc" for the path field in the deploy, and then use the same name field in the invoke and query commands.

For devnet-setup style testing, I use Advaced REST Client plugin on Chrome:

Send to:

http://localhost:3000/devops/deploy

This message:

{
    "type":"GOLANG",
    "chaincodeID":{
            "path":"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
        },
        "ctorMsg":{
                "function":"init",
            "args":["a","100", "b", "200"]
        }
}

Result:

{
    "OK": "Successfully deployed chainCode."
    "message": "bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c"
}

Then send to:

http://localhost:3000/devops/invoke:

{
  "chaincodeSpec": {
    "chaincodeID":{      "name":"bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c"
    },
    "ctorMsg":{
      "function":"invoke",
      "args":["a", "b", "50"]
    }
  }
}

Result:

{
    "OK": "Successfully invoked chainCode."
    "message": "df5fb9cb-acf7-4c4f-90fc-50b5f03c9919"
}

And finally:

http://localhost:3000/devops/query

{
  "chaincodeSpec": {
    "chaincodeID":{      "name":"bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c"
    },
    "ctorMsg":{
      "function":"query",
      "args":["a"]
    }
  }
}

Result:

{
    "OK": "50"
}

**Comment by binhn** [comment]
@kletkeman thanks for the detail.  So it looks like cc-id (hash) works but not the name.

**Comment by muralisrini** [comment]
Ran tests (both REST and CLI) by copy-pasting instructions from SandboxSetup.md and it worked fine

Peer : 
 ./obc-peer peer --peer-chaincodedev

chaincode : 
OPENCHAIN_CHAINCODE_ID_NAME=mycc OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 ./chaincode_example02

REST calls : 

curl -X POST -d@deploy.json http://localhost:3000/devops/deploy
{"OK": "Successfully deployed chainCode.","message":"mycc"}

 curl -X POST -d@invoke.json http://localhost:3000/devops/invoke
{"OK": "Successfully invoked chainCode.","message": "52451d0d-2f80-4243-b40f-98eaa536f9d5"}

curl -X POST -d@query.json http://localhost:3000/devops/query
{"OK":"90"}

where the *.json files were created by copy-pasting json snippets from SandboxSetup.md.

I suspect user error (either not running in dev mode, or not providing the right env variable in starting up chaincode_example02).... can't tell without test details (hint, hint :-) )

**Comment by binhn** [comment]
@muralisrini thanks!
It works with POSTMAN in Chrome too:
![image](https://cloud.githubusercontent.com/assets/3342057/13028879/235e4436-d24a-11e5-92ed-3aa0ba949259.png)

**Comment by 2016Nishi** [comment]
Quick update, here is the query command I had given:

{
  "chaincodeSpec":{
      "type": "GOLANG",
      "chaincodeID":{
          "name":"mycc"
      },
      "ctorMsg":{
          "function":"query",
          "args":["a"]
      },
    "secureContext": "lukas"
  }
}

Difference what I see from what @kletkeman had posted is "name" argument having "mycc" in my case vs "messageString"  in his Rest request.

@muralisrini I tried to follow what is given in SandboxSetup.md. Not sure what dev mode is. I was using security enabled used to run my query.

Will build the code and run the commands again and will update

**Comment by muralisrini** [comment]
ok. I'll try Security steps too. thanks @2016Nishi .

**Comment by muralisrini** [comment]
Following the security steps, worked as well. @2016Nishi, still suspect user error. Can you try again please ?

**Comment by 2016Nishi** [comment]
Tried security steps with today's code, Sent Registrat/Deploy/Invoke and Query requests successfully through POSTMAN.

**Comment by muralisrini** [comment]
Closing the bug. Thanks for going thru security path.
