### ISSUE TITLE
Crash - When Starting A Peer with Security Enabled and the obcca Server Is Not Yet Started

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#669]
^Cvagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc                                                                         eer$ docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPEN                                                                         CHAIN_PEER_ID=vp1 -p 5000:5000 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchai                                                                         n-peer obc-peer peer
23:13:33.040 [main] serve -> INFO 001 Security enabled status: true
23:13:33.041 [main] serve -> INFO 003 Privacy enabled status: true
23:13:33.040 [eventhub_producer] start -> INFO 002 event processor started
23:13:33.044 [CRYPTO] RegisterValidator -> INFO 004 Registering validator [binhn                                                                         ] with name [binhn]...
23:13:33.046 [CRYPTO.validator.binhn] register -> INFO 005 Registering [binhn]..                                                                         .
23:13:33.046 [CRYPTO.validator.binhn] register -> INFO 006 Init keystore...
23:13:33.047 [CRYPTO.validator.binhn] register -> INFO 007 Init keystore...done.
23:13:33.047 [CRYPTO.validator.binhn] registerCryptoEngine -> INFO 008 Registeri                                                                         ng node crypto engine...
2016/02/12 23:13:34 grpc: ClientConn.resetTransport failed to create client tran                                                                         sport: connection error: desc = "transport: dial tcp 172.17.0.4:50051: getsockop                                                                         t: connection refused"; Reconnecting to "172.17.0.4:50051"
2016/02/12 23:13:35 grpc: ClientConn.resetTransport failed to create client tran                                                                         sport: connection error: desc = "transport: dial tcp 172.17.0.4:50051: getsockop                                                                         t: connection refused"; Reconnecting to "172.17.0.4:50051"
2016/02/12 23:13:35 Failed to dial 172.17.0.4:50051: grpc: timed out trying to c                                                                         onnect; please retry.
23:13:35.718 [CRYPTO.validator.binhn] callECAReadCACertificate -> ERRO 009 Faile                                                                         d requesting read certificate [rpc error: code = 2 desc = "grpc: the client conn                                                                         ection is closing"].
23:13:35.718 [CRYPTO.validator.binhn] getECACertificate -> ERRO 00a Failed reque                                                                         sting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection i                                                                         s closing"].
23:13:35.718 [CRYPTO.validator.binhn] retrieveECACertsChain -> ERRO 00b Failed g                                                                         etting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection                                                                          is closing"].
23:13:35.718 [CRYPTO.validator.binhn] registerCryptoEngine -> ERRO 00c Failed re                                                                         trieveing ECA certs chain [rpc error: code = 2 desc = "grpc: the client connecti                                                                         on is closing"].
23:13:35.718 [CRYPTO.validator.binhn] register -> ERRO 00d Failed registering cr                                                                         ypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"                                                                         ].
23:13:35.718 [CRYPTO] register -> ERRO 00e Failed registering [binhn]: [rpc erro                                                                         r: code = 2 desc = "grpc: the client connection is closing"]
23:13:35.718 [CRYPTO] register -> ERRO 00f Failed registering [binhn]: [rpc erro                                                                         r: code = 2 desc = "grpc: the client connection is closing"]
23:13:35.718 [CRYPTO] RegisterValidator -> ERRO 010 Failed registering validator                                                                          [binhn] with name [binhn] [rpc error: code = 2 desc = "grpc: the client connect                                                                         ion is closing"].
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4cd710]

goroutine 1 [running]:
main.serve(0x13b82d8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openblockchain/obc-peer/main.go:363 +0x1800
main.glob.func2(0x1374580, 0x13b82d8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openblockchain/obc-peer/main.go:78 +0x41
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(_Command).exec                                                                         ute(0x1374580, 0x13b82d8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra                                                                         /command.go:497 +0x63b
github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra.(_Command).Exec                                                                         ute(0x13743c0, 0x0, 0x0)
        /go/src/github.com/openblockchain/obc-peer/vendor/github.com/spf13/cobra                                                                         /command.go:584 +0x46a
main.main()
        /go/src/github.com/openblockchain/obc-peer/main.go:255 +0x13f9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 4 [chan receive]:
github.com/openblockchain/obc-peer/events/producer.(*eventProcessor).start(0xc82                                                                         01d3c80)
        /go/src/github.com/openblockchain/obc-peer/events/producer/events.go:72                                                                          +0xbe
created by github.com/openblockchain/obc-peer/events/producer.initializeEvents
        /go/src/github.com/openblockchain/obc-peer/events/producer/events.go:120                                                                          +0x178

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82015dc20)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-p                                                                         eer$

**Comment by binhn** [comment]
@bmos299 this is as designed -- obc-ca is a pre-req when security is enabled

**Comment by bmos299** [comment]
Can't we just come down gracefully thought and really help cut log messages what the issue is? 
Seeing this... 23:13:35.718 [CRYPTO] RegisterValidator -> ERRO 010 Failed registering validator [binhn] with name [binhn] [rpc error: code = 2 desc = "grpc: the client connect ion is closing"].
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4cd710]

I guarantee this will have many users adding comments. Thanks.

**Comment by mastersingh24** [comment]
there is no reason to crash here.  should exit gracefully with an error not a runtime error

**Comment by adecaro** [comment]
PR #682, addressing this issue, has been merged.

**Comment by bmos299** [comment]
@adecaro the fix looks good and does not crash.   Is it possible to add some info level messages saying something like 'attempting to connect membership services at xxx.yyy.zzz:port'....try try ... 'failed attempting to connect to membership services at xxx.yyy.zzz:port'?  
I am just trying to help the sys admin for the fabric clearly see the failed connection information.  
Thanks, Barry

**Comment by adecaro** [comment]
@bmos299 Sure, I will add it.

**Comment by bmos299** [comment]
@adecaro.  Thank you.

**Comment by adecaro** [comment]
@bmos299, is this issue still to be considered opened?

**Comment by bmos299** [comment]
Closing.
