### ISSUE TITLE
Invoke chaincode transaction

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#67]
We need a util function to run a transaction on a chaincode and keep the state temporarily until commit
exec(ID, tx) -> hash of result
The ID is the transaction ID from begin() function on the Ledger

**Comment by srderson** [comment]
Blocked by issue #9

**Comment by muralisrini** [comment]
This "invoke transaction" that was part of the "basic pbft milestone 2" was to start a container and have docker exec the transaction. This has been implemented (executeTransactions in validator.go)

However, the final "invoke transaction" will not be "docker exec transaction" but to send chaincode (function, args,..) over an established stream between validator and peer. This has been captured in issue#151 and issue#152 for milestone 3. 

If agreed, we should close this issue as a dup of 151 and 152

**Comment by binhn** [comment]
I close this based on @muralisrini 's comment above
