### ISSUE TITLE
4 failures when running behave tests

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#674]
Using the documentations given in
https://github.com/openblockchain/obc-peer
1. Ran unit tests:
   cd $GOPATH/src/github.com/openblockchain/obc-peer
   go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)
2. Ran the following command:
   cd $GOPATH/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests
   behave
## Expected Results:

All unit tests and Behave tests to pass successfully.
## Actual Result:

There were failures in unit test.

4 failures in behave tests. Final Test Report after running behave tests:

Failing scenarios:
  peer_basic.feature:17  chaincode example 02 single peer
  peer_basic.feature:58  chaincode example02 with 5 peers, issue #520
  peer_basic.feature:139  basic startup of 3 validating peers
  peer_basic.feature:146  basic startup of 2 validating peers using TLS

0 features passed, 1 failed, 0 skipped
4 scenarios passed, 4 failed, 0 skipped
70 steps passed, 4 failed, 30 skipped, 0 undefined
Took 2m45.247s

P.S. Attached is a zip file that has output from running unit tests and behave tests.
[obc-peer-unittests-behavetests-output.zip](https://github.com/openblockchain/obc-peer/files/131089/obc-peer-unittests-behavetests-output.zip)

**Comment by tuand27613** [comment]
@2016Nishi  could you pull the latest master and re-run ?  I ran unit tests and behave tests at commit d0dd6cc and all tests ran ok.

**Comment by 2016Nishi** [comment]
Ran with ver: 3c5fbcdf8a288b7d5ed5aa0dae5d570472169e73

Right now I see 1 failure 
Failing scenarios:
  peer_basic.feature:257  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
10 scenarios passed, 1 failed, 0 skipped
229 steps passed, 1 failed, 1 skipped, 0 undefined
Took 5m44.307s
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests$

**Comment by tuand27613** [comment]
I ran the behave tests with version [438f73](https://github.com/openblockchain/obc-peer/commit/438f73652d69523be63216e1ac26ba07f22cfbd3) and all scenarios passed.

what does the behave log say ?

**Comment by 2016Nishi** [comment]
where can I check for behave logs?  

redirected my behaveTests output to a file and attaching here.
[behaveTestsOutput.zip](https://github.com/openblockchain/obc-peer/files/138287/behaveTestsOutput.zip)

**Comment by jyellick** [comment]
@2016Nishi Could you also double check to make sure that you do not still have the peer running?  For the go tests, you should have started a peer with `./obc-peer peer`.  If you leave this peer executing, it is already bound to a port which is utilized in the behave tests and can cause a failure.

**Comment by 2016Nishi** [comment]
You are right. I had ./obc-peer peer running earlier. Currently I do not have it running anymore. Let me run my behave tests again

**Comment by 2016Nishi** [comment]
This time all my behave tests passed:

1 feature passed, 0 failed, 0 skipped
11 scenarios passed, 0 failed, 0 skipped
231 steps passed, 0 failed, 0 skipped, 0 undefined
Took 4m39.292s

Thanks!

**Comment by jyellick** [comment]
@2016Nishi Is everything working for you? Can this be closed?

**Comment by 2016Nishi** [comment]
Sure it can be closed.
Thanks!
