### ISSUE TITLE
state transfer fails with `panic: Our blockchain is already higher than a sync target, this is unlikely, but unimplemented` message

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#676]
Scenario is
- 4 validating peers
- security enabled
- VP0-2 start at beginning of test,  VP3 manually started after VP0-2 have processed chaincode deploy and 5 TXs
- after VP3 starts, invoke 5 more TXs. This will cause VP3 to initiate state transfer

Result:
- VP3 initiates state transfer, tries to sync with VP1,VP2 but stops on panic message.

Attaching VP3 debug log:
[vp3_err.txt](https://github.com/openblockchain/obc-peer/files/131339/vp3_err.txt)

**Comment by jyellick** [comment]
Have a fix pending, waiting for PR #677 to fix failing behave tests before submitting PR.
