### ISSUE TITLE
Unmarshaling error during state transfer SYNC_STATE_SNAPSHOT processing

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#680]
getting this message while initiating a state transfer request to other validating peers:
`
[33m20:19:56.769 [consensus/statetransfer] tryOverPeers -> WARN 719[0m name:"vp3"  in tryOverPeers loop trying name:"vp2"  : name:"vp3"  received a corrupt delta from name:"vp2"  : Error unmarashaling size: unexpected EOF
`

state transfer code will keep retrying, send out SYNC_STATE_GET_SNAPSHOT, get the same error and loop forever

**Comment by tuand27613** [comment]
@jeffgarratt  taking a look.

**Comment by tuand27613** [comment]
not sure if it's related but look at #686

**Comment by tuand27613** [comment]
@jeffgarratt  @jyellick ,   not seeing the error when running with security.enabled=false

**Comment by jyellick** [comment]
@tuand27613 Great work, I think that narrows down the problem considerably.  This means that state transfer without security completes successfully?

@srderson It seems that something in the state delta is encrypted before marshaling when security is enabled, causing unmarshaling to fail?  Do you have any thoughts or insight into what that might be?

**Comment by tuand27613** [comment]
@jyellick  @jeffgarratt   I take it back.  got the latest code from obc-peer  including PR 677,681, 690 , run again with security.enabled=false  and I _still_ get the `unmarshalling unexpected EOF` error

**Comment by jeffgarratt** [comment]
@jyellick @tuand27613 @srderson It appears to be working as designed, the last message will have an empty slice for the Delta field, indicating end of snapshot.  Be sure to check the length prior to attempting to Unmarshal with state_deltas.Unmarshal.  I will update the comment to be more explicit about the mechanism of indicating termination.

**Comment by jyellick** [comment]
@jeffgarratt Yes, thanks for figuring this out, this was not how our mock implementation functioned which is why we did not catch it in earlier testing.  I'll fix that up now and put a PR together.

**Comment by jyellick** [comment]
@tuand27613 You should be able to verify that this issue is fixed now.  Simply execute the new behave tests without decomposing.  If you grep the vp3 log for `obcpbft\|statetransfer` you will see state transfer be initiated, transfer blocks, then state deltas, then finish after transfering to block 8, and pbft will execute the outstanding 9th request.

**Comment by tuand27613** [comment]
state transfer working for batch/classic/sieve

start vp0-2 , deploy, invoke tx, start vp3,  invoke tx, see in log that vp3 initiates and completes state transfer.

thanks @jyellick  @jeffgarratt
