### ISSUE TITLE
performance issue with security and privacy enabled

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#684]
code level:
commit e338d6a25865db96c4e6374168473965a2b39054
Merge: 67e2a10 15dcc91
Author: Binh Q Nguyen binhn@us.ibm.com
Date:   Mon Feb 15 12:10:54 2016 -0500

```
Merge pull request #675 from bcbrock/docs

A couple of comments for outside-of-Vagrant builds
```

security and privacy: enabled
test: invoke a to b, then invoke b to a, then repeat continuously
chaincode can only process 5 invoke transactions per second.

Below is the information I collected during the test.  Detailed log is in the attached file, sec_test0216.txt
[sec_test0216.txt](https://github.com/openblockchain/obc-peer/files/133048/sec_test0216.txt)
1. There are many selectNextCert messages through out the log:
   15:53:53.548 [CRYPTO.client.lukas] selectNextTCert -> ERRO 03f No TCert in cache found.
2. an error message when deploy after successfully deploy and creating VM

15:53:54.543 [rest] Deploy -> INFO 044 Successfuly deployed chainCode: bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c.
15:53:55.627 [container] newDockerClient -> INFO 045 Creating VM with endpoint: unix:///var/run/docker.sock
15:54:03.169 [container] newDockerClient -> INFO 046 Creating VM with endpoint: unix:///var/run/docker.sock
15:54:03.358 [ledger] sendProducerBlockEvent -> ERRO 047 Error unmarshalling deployment transaction for block event: proto: can't skip unknown wire type 7 for protos.ChaincodeDeploymentSpec
1. it spends 12 seconds on selectNextCert from 15:59:48 to 16:00:00

15:59:48.222 [rest] Invoke -> INFO 1bff REST invoking chaincode...
15:59:48.223 [rest] Invoke -> INFO 1c00 Local user 'lukas' is already logged in. Retrieving login token.
15:59:48.224 [CRYPTO] InitClient -> INFO 1c01 Initializing client [lukas]...
15:59:48.224 [CRYPTO] InitClient -> INFO 1c02 Client already initiliazied [lukas]. Increasing counter from [149]
15:59:48.224 [CRYPTO] InitClient -> INFO 1c01 Initializing client [lukas]...
15:59:48.224 [CRYPTO] InitClient -> INFO 1c02 Client already initiliazied [lukas]. Increasing counter from [149]
15:59:49.114 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c03 No TCert in cache found.
15:59:49.971 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c04 No TCert in cache found.
15:59:50.963 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c05 No TCert in cache found.
15:59:51.816 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c06 No TCert in cache found.
15:59:52.775 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c07 No TCert in cache found.
15:59:53.711 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c08 No TCert in cache found.
15:59:54.595 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c09 No TCert in cache found.
15:59:55.533 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0a No TCert in cache found.
15:59:56.410 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0b No TCert in cache found.
15:59:57.344 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0c No TCert in cache found.
15:59:58.246 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0d No TCert in cache found.
15:59:59.199 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0e No TCert in cache found.
16:00:00.078 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c0f No TCert in cache found.
16:00:00.956 [CRYPTO.client.lukas] selectNextTCert -> ERRO 1c10 No TCert in cache found.
1. Then it creates VM repeatedly

16:00:18.351 [container] newDockerClient -> INFO 1c11 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.485 [container] newDockerClient -> INFO 1c12 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.487 [container] newDockerClient -> INFO 1c13 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.489 [container] newDockerClient -> INFO 1c14 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.490 [container] newDockerClient -> INFO 1c15 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.491 [container] newDockerClient -> INFO 1c16 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.493 [container] newDockerClient -> INFO 1c17 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.495 [container] newDockerClient -> INFO 1c18 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.496 [container] newDockerClient -> INFO 1c19 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.498 [container] newDockerClient -> INFO 1c1a Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.499 [container] newDockerClient -> INFO 1c1b Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.501 [container] newDockerClient -> INFO 1c1c Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.502 [container] newDockerClient -> INFO 1c1d Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.504 [container] newDockerClient -> INFO 1c1e Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.506 [container] newDockerClient -> INFO 1c1f Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.507 [container] newDockerClient -> INFO 1c20 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.509 [container] newDockerClient -> INFO 1c21 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.511 [container] newDockerClient -> INFO 1c22 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.513 [container] newDockerClient -> INFO 1c23 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.514 [container] newDockerClient -> INFO 1c24 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.515 [container] newDockerClient -> INFO 1c25 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.517 [container] newDockerClient -> INFO 1c26 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.519 [container] newDockerClient -> INFO 1c27 Creating VM with endpoint: unix:///var/run/docker.sock
16:00:18.522 [container] newDockerClient -> INFO 1c28 Creating VM with endpoint: unix:///var/run/docker.sock
1. There are 56 seconds between two invoke requests, see 

15:59:48.222 [rest] Invoke -> INFO 1bff REST invoking chaincode...
and 
16:00:44.684 [rest] Invoke -> INFO 1c29 REST invoking chaincode...
16:00:44.686 [rest] Invoke -> INFO 1c2a Local user 'lukas' is already logged in. Retrieving login token.
16:00:44.687 [CRYPTO] InitClient -> INFO 1c2b Initializing client [lukas]...
1. the top 150 cpu users are listed below by using go pprof
   (pprof) top 150
   7.93s of 8.31s total (95.43%)
   Dropped 143 nodes (cum <= 0.04s)
     flat  flat%   sum%        cum   cum%
    1.94s 23.35% 23.35%      1.94s 23.35%  runtime._ExternalCode
    0.82s  9.87% 33.21%      0.82s  9.87%  math/big.divWW
    0.60s  7.22% 40.43%      2.76s 33.21%  math/big.nat.divLarge
    0.48s  5.78% 46.21%      0.70s  8.42%  runtime.scanobject
    0.37s  4.45% 50.66%      1.29s 15.52%  runtime.makeslice
    0.35s  4.21% 54.87%      0.35s  4.21%  math/big.addMulVVW
    0.29s  3.49% 58.36%      0.86s 10.35%  runtime.mallocgc
    0.24s  2.89% 61.25%      0.24s  2.89%  math/big.subVV
    0.23s  2.77% 64.02%      0.23s  2.77%  runtime.readvarint
    0.21s  2.53% 66.55%      0.61s  7.34%  math/big.basicMul
    0.19s  2.29% 68.83%      0.19s  2.29%  math/big.mulAddVWW
    0.19s  2.29% 71.12%      0.19s  2.29%  runtime.heapBitsForObject
    0.17s  2.05% 73.16%      0.97s 11.67%  runtime.gentraceback
    0.16s  1.93% 75.09%      0.31s  3.73%  runtime.scanblock
    0.13s  1.56% 76.65%      0.36s  4.33%  runtime.step
    0.12s  1.44% 78.10%      0.92s 11.07%  runtime.newarray
    0.11s  1.32% 79.42%      0.18s  2.17%  runtime.greyobject
    0.10s  1.20% 80.63%      0.10s  1.20%  runtime.memclr
    0.09s  1.08% 81.71%      1.12s 13.48%  math/big.nat.mul
    0.08s  0.96% 82.67%      0.08s  0.96%  math/big.mulWW
    0.08s  0.96% 83.63%      0.08s  0.96%  runtime.mSpan_Sweep.func1
    0.07s  0.84% 84.48%      0.07s  0.84%  math/big.nat.norm
    0.07s  0.84% 85.32%      0.07s  0.84%  math/big.shlVU
    0.07s  0.84% 86.16%      0.07s  0.84%  runtime.futex
    0.06s  0.72% 86.88%      0.06s  0.72%  math/big.subVW
    0.05s   0.6% 87.48%      1.17s 14.08%  math/big.(_Int).Mul
    0.05s   0.6% 88.09%      0.05s   0.6%  math/big.shrVU
    0.05s   0.6% 88.69%      0.41s  4.93%  runtime.pcvalue
    0.05s   0.6% 89.29%      0.05s   0.6%  runtime.usleep
    0.05s   0.6% 89.89%      0.05s   0.6%  syscall.Syscall
    0.04s  0.48% 90.37%      1.16s 13.96%  math/big.nat.make
    0.04s  0.48% 90.85%      0.08s  0.96%  math/big.nat.shl
    0.04s  0.48% 91.34%      0.21s  2.53%  math/big.nat.sub
    0.04s  0.48% 91.82%      0.60s  7.22%  runtime.scanframeworker
    0.03s  0.36% 92.18%      2.79s 33.57%  math/big.(_Int).Mod
    0.03s  0.36% 92.54%      0.15s  1.81%  math/big.nat.add
    0.03s  0.36% 92.90%      2.80s 33.69%  math/big.nat.div
    0.03s  0.36% 93.26%      0.11s  1.32%  runtime.heapBitsSweepSpan
    0.02s  0.24% 93.50%      2.82s 33.94%  math/big.(_Int).QuoRem
    0.02s  0.24% 93.74%      0.07s  0.84%  math/big.nat.clear
    0.02s  0.24% 93.98%      0.20s  2.41%  runtime.funcspdelta
    0.02s  0.24% 94.22%      0.14s  1.68%  runtime.mCentral_CacheSpan
    0.01s  0.12% 94.34%      2.66s 32.01%  crypto/elliptic.(_CurveParams).doubleJacobian
    0.01s  0.12% 94.46%      0.15s  1.81%  math/big.(_Int).Add
    0.01s  0.12% 94.58%      0.23s  2.77%  math/big.(_Int).Sub
    0.01s  0.12% 94.71%      0.08s  0.96%  math/big.nat.mulAddWW
    0.01s  0.12% 94.83%      0.98s 11.79%  runtime.gcscan_m
    0.01s  0.12% 94.95%      0.05s   0.6%  runtime.mHeap_Alloc.func1
    0.01s  0.12% 95.07%      0.08s  0.96%  runtime.mProf_Malloc
    0.01s  0.12% 95.19%         1s 12.03%  runtime.markroot
    0.01s  0.12% 95.31%      0.07s  0.84%  runtime.newobject
    0.01s  0.12% 95.43%      0.93s 11.19%  runtime.scanstack
        0     0% 95.43%      0.97s 11.67%  crypto/ecdsa.Sign
        0     0% 95.43%      2.73s 32.85%  crypto/ecdsa.Verify
        0     0% 95.43%      3.22s 38.75%  crypto/elliptic.(_CurveParams).ScalarBaseMult
        0     0% 95.43%      4.55s 54.75%  crypto/elliptic.(_CurveParams).ScalarMult
        0     0% 95.43%      1.81s 21.78%  crypto/elliptic.(_CurveParams).addJacobian
        0     0% 95.43%      0.11s  1.32%  crypto/elliptic.(_CurveParams).affineFromJacobian
        0     0% 95.43%      0.96s 11.55%  crypto/x509.(_CertPool).findVerifiedParents
        0     0% 95.43%      0.96s 11.55%  crypto/x509.(_Certificate).CheckSignature
        0     0% 95.43%      0.96s 11.55%  crypto/x509.(_Certificate).CheckSignatureFrom
        0     0% 95.43%      0.96s 11.55%  crypto/x509.(_Certificate).Verify
        0     0% 95.43%      0.96s 11.55%  crypto/x509.(_Certificate).buildChains
        0     0% 95.43%      0.96s 11.55%  crypto/x509.checkSignature
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/openchain.(_Devops).Invoke
        0     0% 95.43%      3.78s 45.49%  github.com/openblockchain/obc-peer/openchain.(_Devops).createExecTx
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/openchain.(_Devops).invokeOrQuery
        0     0% 95.43%      0.89s 10.71%  github.com/openblockchain/obc-peer/openchain/consensus/helper.(_ConsensusHandler).HandleMessage
        0     0% 95.43%      0.89s 10.71%  github.com/openblockchain/obc-peer/openchain/consensus/helper.(_ConsensusHandler).doChainTransaction
        0     0% 95.43%      2.77s 33.33%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).(github.com/openblockchain/obc-peer/openchain/crypto.getTCertsFromTCA)-fm
        0     0% 95.43%      3.78s 45.49%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).NewChaincodeExecute
        0     0% 95.43%      2.77s 33.33%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).getNextTCert
        0     0% 95.43%      2.77s 33.33%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).getTCertsFromTCA
        0     0% 95.43%      1.01s 12.15%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).newChaincodeExecuteUsingTCert
        0     0% 95.43%      1.01s 12.15%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).signUsingTCertDER
        0     0% 95.43%         1s 12.03%  github.com/openblockchain/obc-peer/openchain/crypto.(_clientImpl).signUsingTCertX509
        0     0% 95.43%      2.77s 33.33%  github.com/openblockchain/obc-peer/openchain/crypto.(_keyStore).GetNextTCert
        0     0% 95.43%      0.46s  5.54%  github.com/openblockchain/obc-peer/openchain/crypto.(_nodeImpl).sign
        0     0% 95.43%      0.86s 10.35%  github.com/openblockchain/obc-peer/openchain/crypto.(_nodeImpl).verify
        0     0% 95.43%      0.86s 10.35%  github.com/openblockchain/obc-peer/openchain/crypto.(_peerImpl).TransactionPreValidation
        0     0% 95.43%      0.86s 10.35%  github.com/openblockchain/obc-peer/openchain/crypto.(_validatorImpl).TransactionPreValidation
        0     0% 95.43%      0.96s 11.55%  github.com/openblockchain/obc-peer/openchain/crypto/utils.CheckCertAgainRoot
        0     0% 95.43%      0.94s 11.31%  github.com/openblockchain/obc-peer/openchain/crypto/utils.ECDSASign
        0     0% 95.43%      1.77s 21.30%  github.com/openblockchain/obc-peer/openchain/crypto/utils.ECDSAVerify
        0     0% 95.43%      1.39s 16.73%  github.com/openblockchain/obc-peer/openchain/crypto/utils.VerifySignCapability
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/openchain/peer.(_PeerImpl).Chat
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/openchain/peer.(_PeerImpl).handleChat
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/openchain/rest.(_ServerOpenchainREST).Invoke
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/openchain/rest.(_ServerOpenchainREST).SetOpenchainServer
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/openchain/rest.(_ServerOpenchainREST).SetResponseType
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/protos._Peer_Chat_Handler
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/vendor/github.com/gocraft/web.(_Router).ServeHTTP
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/vendor/github.com/gocraft/web.(_middlewareHandler).invoke
        0     0% 95.43%      3.81s 45.85%  github.com/openblockchain/obc-peer/vendor/github.com/gocraft/web.middlewareStack.func1
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(_Server).Serve.func2.1.1
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(_Server).handleStream
        0     0% 95.43%      0.90s 10.83%  github.com/openblockchain/obc-peer/vendor/google.golang.org/grpc.(_Server).processStreamingRPC
        0     0% 95.43%      0.12s  1.44%  math/big.(_Int).GCD
        0     0% 95.43%      0.08s  0.96%  math/big.(_Int).Lsh
        0     0% 95.43%      0.12s  1.44%  math/big.(_Int).ModInverse
        0     0% 95.43%      3.81s 45.85%  net/http.(_conn).serve
        0     0% 95.43%      3.81s 45.85%  net/http.serverHandler.ServeHTTP
        0     0% 95.43%      3.81s 45.85%  reflect.Value.Call
        0     0% 95.43%      3.81s 45.85%  reflect.Value.call
        0     0% 95.43%      1.90s 22.86%  runtime._System
        0     0% 95.43%         1s 12.03%  runtime.backgroundgc
        0     0% 95.43%      3.81s 45.85%  runtime.call32
        0     0% 95.43%      3.81s 45.85%  runtime.call64
        0     0% 95.43%      0.07s  0.84%  runtime.callers
        0     0% 95.43%      0.07s  0.84%  runtime.callers.func1
        0     0% 95.43%      0.07s  0.84%  runtime.futexwakeup
        0     0% 95.43%         1s 12.03%  runtime.gc
        0     0% 95.43%      0.98s 11.79%  runtime.gc.func1
        0     0% 95.43%      0.22s  2.65%  runtime.gcAssistAlloc
        0     0% 95.43%      0.22s  2.65%  runtime.gcAssistAlloc.func1
        0     0% 95.43%      0.48s  5.78%  runtime.gcBgMarkWorker
        0     0% 95.43%      0.22s  2.65%  runtime.gcDrainN
        0     0% 95.43%      0.48s  5.78%  runtime.gcDrainUntilPreempt
        0     0% 95.43%      6.26s 75.33%  runtime.goexit
        0     0% 95.43%      0.14s  1.68%  runtime.mCache_Refill
        0     0% 95.43%      0.11s  1.32%  runtime.mSpan_Sweep
        0     0% 95.43%      0.14s  1.68%  runtime.mallocgc.func2
        0     0% 95.43%      0.07s  0.84%  runtime.notewakeup
        0     0% 95.43%         1s 12.03%  runtime.parfordo
        0     0% 95.43%      0.23s  2.77%  runtime.pcdatavalue
        0     0% 95.43%      0.08s  0.96%  runtime.profilealloc
        0     0% 95.43%      0.94s 11.31%  runtime.scang
        0     0% 95.43%      0.60s  7.22%  runtime.scanstack.func1
        0     0% 95.43%      0.07s  0.84%  runtime.schedule
        0     0% 95.43%      0.06s  0.72%  runtime.startm
        0     0% 95.43%      1.52s 18.29%  runtime.systemstack
        0     0% 95.43%      0.05s   0.6%  runtime.wakep
        0     0% 95.43%      0.05s   0.6%  syscall.Write
        0     0% 95.43%      0.05s   0.6%  syscall.write

**Comment by dongmingh** [comment]
The issue concerning "error unmarshalling deployment transaction" is tracked in #686

**Comment by binhn** [comment]
@adecaro  we slacked about the first part of this log

@muralisrini please look at why we try to recreate the VM repeatedly

**Comment by dongmingh** [comment]
I captured logs for two invokes and calculate the time for each step based on the timestamp.

21:09:28.449 [rest] Invoke -> INFO 05f REST invoking chaincode...
21:09:28.453 [rest] Invoke -> INFO 060 Local user 'lukas' is already logged in. Retrieving login token.
21:09:28.455 [CRYPTO] InitClient -> INFO 061 Initializing client [lukas]...
21:09:28.459 [CRYPTO.client.lukas] init -> INFO 062 Init keystore...
21:09:28.463 [CRYPTO.client.lukas] init -> INFO 063 Init keystore...done.
21:09:28.464 [CRYPTO.client.lukas] initCryptoEngine -> INFO 064 Initializing node crypto engine...
21:09:28.525 [CRYPTO.client.lukas] initCryptoEngine -> INFO 065 Initializing node crypto engine...done!
21:09:28.525 [CRYPTO.client.lukas] init -> INFO 066 Initialization...done.
21:09:28.525 [CRYPTO.client.lukas] init -> INFO 067 Init keystore...
21:09:28.525 [CRYPTO.client.lukas] init -> INFO 068 Init keystore...done.
21:09:28.525 [CRYPTO.client.lukas] init -> INFO 069 Initialization...done.
21:09:28.525 [CRYPTO] InitClient -> INFO 06a Initializing client [lukas]...done!
21:09:28.554 [CRYPTO] closeClientInternal -> INFO 06b Closing client [lukas]...
21:09:28.554 [CRYPTO.client.lukas] close -> INFO 06c Closing keystore...
21:09:28.555 [CRYPTO.client.lukas] close -> INFO 06d Closing keystore...done!
21:09:28.555 [CRYPTO] closeClientInternal -> INFO 06e Closing client [lukas]...done! [<clean>].
21:09:28.555 [rest] Invoke -> INFO 06f Successfuly invoked chainCode with txuuid (90cd17ed-71c9-41ee-8196-ee4a085d26d7)

total: 555 - 449 = 106 ms
crypto: 555 - 455 = 100 ms
     init crypto engine: 525 - 464 = 61 ms
     InitClient:  554 - 525 = 31 ms

21:09:38.644 [rest] Invoke -> INFO 070 REST invoking chaincode...
21:09:38.647 [rest] Invoke -> INFO 071 Local user 'lukas' is already logged in. Retrieving login token.
21:09:38.650 [CRYPTO] InitClient -> INFO 072 Initializing client [lukas]...
21:09:38.657 [CRYPTO.client.lukas] init -> INFO 073 Init keystore...
21:09:38.659 [CRYPTO.client.lukas] init -> INFO 074 Init keystore...done.
21:09:38.660 [CRYPTO.client.lukas] initCryptoEngine -> INFO 075 Initializing node crypto engine...
21:09:38.709 [CRYPTO.client.lukas] initCryptoEngine -> INFO 076 Initializing node crypto engine...done!
21:09:38.709 [CRYPTO.client.lukas] init -> INFO 077 Initialization...done.
21:09:38.710 [CRYPTO.client.lukas] init -> INFO 078 Init keystore...
21:09:38.710 [CRYPTO.client.lukas] init -> INFO 079 Init keystore...done.
21:09:38.711 [CRYPTO.client.lukas] init -> INFO 07a Initialization...done.
21:09:38.711 [CRYPTO] InitClient -> INFO 07b Initializing client [lukas]...done!
21:09:38.741 [CRYPTO] closeClientInternal -> INFO 07c Closing client [lukas]...
21:09:38.741 [CRYPTO.client.lukas] close -> INFO 07d Closing keystore...
21:09:38.741 [CRYPTO.client.lukas] close -> INFO 07e Closing keystore...done!
21:09:38.741 [CRYPTO] closeClientInternal -> INFO 07f Closing client [lukas]...done! [<clean>].
21:09:38.741 [rest] Invoke -> INFO 080 Successfuly invoked chainCode with txuuid (57e59623-ad27-4d77-9428-b25c66ba375f)

total: 741 - 644 = 97 ms
crypto: 741 - 650 = 91 ms
     init crypto engine: 709 - 660 = 49 ms
     InitClient: 741 - 711 = 30 ms

In both cases, CRYPTO uses 94% of time, and initCryptoEngine + initClient uses 92% and 87% respectively of total CRYPTO time. It will be worthy to look initCryptoEngine and initClent first.

**Comment by muralisrini** [comment]
Worked with @dongmingh on this. Basically requests to the chaincode resulted in encrypt/decrypt errors causing the chaincode to go down. This explains why the vms were getting restarted.

Before we go deeper into actual "performance" issue with security, we need to fix the basic security problems.

We know approximately where the encrypt/decrypt errors are coming from but it may or may not be related to the #686 ... will dig deeper.

@dongmingh : please feel free to add any missing details

**Comment by dongmingh** [comment]
@muralisrini recreates the VM crash on his system.  We can fix the encrypt/decrypt first. And see if this is related to the selectNextTCert no TCert in cache found issue.  If the no TCert issue still remains after encrypt/decrypt is resolved, then we have to fix it.  After the two issues resolved, we can have more accurate performance study with security.

**Comment by dongmingh** [comment]
Test with security disabled, the VM crash issue is not seen.

**Comment by muralisrini** [comment]
There are a couple of security related fixes needed in chaincode
- don't store path from deploy tx in  security context as other transaction contexts only use names
- resurrect security context from saved deployment transaction (long overdue) if init hasn't been called yet

The second fix can also be used to prevent queries and invokes from starting up container (another long overdue fix).

**Comment by dongmingh** [comment]
work with @muralisrini  with a sandbox code with the fixes he mentioned in above comment.  The VM crash is fixed but the error message of "no TCert in cache found" is still seen.  While this error message is shown on the log, the test traffic becomes very slow.  The chaincode can only do 10 query per second, tps = 10.  It seems we are making SQL query for every request for get certificate.

Run another quick test with storing the query cert for the very first time and then reuse it for the subsequent query, the tps improves to 50.  This is just for test purpose.

We will continue to work to improve the performance.

**Comment by adecaro** [comment]
@dongmingh @muralisrini working on a fix for the "no TCert in cache found" issue. I'm in the test face. The PR will be ready soon.

**Comment by dongmingh** [comment]
I work with @muralisrini today to pick up the TCertPool fix from #705 and do not see the message of "No TCert in cache found".  But the tps goes down to 0.5 query per second.  Then we did a test of commenting out closeClientInternal(), i.e. not close client, then the tps increases to 30 per second.

**Comment by adecaro** [comment]
Please, @dongmingh, may you give me more information on the tests that you run in such a way I can replicate them and analyze what happens to the crypto layer?

Regarding closeClientInternal(), rather than commenting out that call, please, comment out the call to CloseClient(). Also, I would suggest to call InitClient() right after RegisterCliert(.) and then keep the Client instance somewhere ready to be used in order to avoid repeated call also to InitClient(). 

Regarding the 30 tps, do you mean transaction creation or transaction validation?

**Comment by dongmingh** [comment]
I run it on vagrant using SoupUI to drive the query transaction. The thread is set to 1.  Let me know if you need any information on the test.  I can show you in person.
30 tps means 30 queries per second.

**Comment by adecaro** [comment]
@dongmingh Yeah, actually, it would be useful to have a call on Monday to talk about this. 
Btw, may you increase the number of thread to at least 2 and see if the tps increases? 
Actually, one key element of the new code in the PR is to use multi-threading to have the TCerts loaded in background.

**Comment by dongmingh** [comment]
with threads = 20, after 3 min runs, the tps = 20.
Here are some log, see ERROR messages of "Failed inserting TCert":

20:49:06.857 [crypto] InitClient -> INFO 595f Client already initiliazied [lukas]. Increasing counter from [19]
20:49:06.864 [crypto] closeClientInternal -> INFO 5960 Closing client [lukas]...
20:49:06.874 [crypto] InitClient -> INFO 5961 Initializing client [lukas]...
20:49:06.875 [crypto] InitClient -> INFO 5962 Client already initiliazied [lukas]. Increasing counter from [19]
20:49:07.571 [crypto.client.lukas] storeUsedTCert -> ERRO 5963 Failed inserting TCert to UsedTCert: [database is locked].
20:49:07.574 [crypto.client.lukas] storeUsedTCert -> ERRO 5964 Failed inserting TCert to UsedTCert: [database is locked].
20:49:07.629 [crypto] closeClientInternal -> INFO 5965 Closing client [lukas]...
20:49:07.629 [crypto] closeClientInternal -> INFO 5966 Closing client [lukas]...
20:49:07.633 [crypto] InitClient -> INFO 5967 Initializing client [lukas]...
20:49:07.633 [crypto] InitClient -> INFO 5968 Client already initiliazied [lukas]. Increasing counter from [18]
20:49:07.637 [crypto] InitClient -> INFO 5969 Initializing client [lukas]...
20:49:07.638 [crypto] InitClient -> INFO 596a Client already initiliazied [lukas]. Increasing counter from [19]
20:49:07.914 [crypto] closeClientInternal -> INFO 596b Closing client [lukas]...
20:49:07.914 [crypto] closeClientInternal -> INFO 596c Closing client [lukas]...
20:49:07.917 [crypto] closeClientInternal -> INFO 596d Closing client [lukas]...
20:49:07.917 [crypto] InitClient -> INFO 596e Initializing client [lukas]...
20:49:07.918 [crypto] InitClient -> INFO 596f Client already initiliazied [lukas]. Increasing counter from [17]
20:49:07.927 [crypto] InitClient -> INFO 5970 Initializing client [lukas]...
20:49:07.927 [crypto] InitClient -> INFO 5971 Client already initiliazied [lukas]. Increasing counter from [18]
20:49:07.942 [crypto] InitClient -> INFO 5972 Initializing client [lukas]...
20:49:07.943 [crypto] InitClient -> INFO 5973 Client already initiliazied [lukas]. Increasing counter from [19]
20:49:07.957 [crypto] closeClientInternal -> INFO 5974 Closing client [lukas]...
20:49:07.959 [crypto] closeClientInternal -> INFO 5975 Closing client [lukas]...
20:49:07.967 [crypto] closeClientInternal -> INFO 5976 Closing client [lukas]...

Please ping me on slack to talk about this.

**Comment by adecaro** [comment]
Okay, I now see too the message "Failed inserting TCert". It is related to sqlite3. Adding an external lock fix the issue. 

Then, how do you count the number of tps?

**Comment by dongmingh** [comment]
The SoupUI shows the tps.

If I change the thread to 100, the log shows the other error message:
21:11:19.919 [crypto] InitClient -> INFO 6139 Initializing client [lukas]...
21:11:19.919 [crypto] InitClient -> INFO 613a Client already initiliazied [lukas]. Increasing counter from [100]
21:11:21.023 [crypto] closeClientInternal -> INFO 613b Closing client [lukas]...
21:11:21.027 [crypto] InitClient -> INFO 613c Initializing client [lukas]...
21:11:21.027 [crypto] InitClient -> INFO 613d Client already initiliazied [lukas]. Increasing counter from [100]
21:11:21.605 [crypto.client.lukas] GetNextTCert -> ERRO 613e Failed getting a new TCert. Buffer is empty!
21:11:21.605 [crypto.client.lukas] GetNextTCert -> ERRO 613f Failed getting a new TCert. Buffer is empty!
21:11:21.646 [crypto.client.lukas] GetNextTCert -> ERRO 6140 Failed getting a new TCert. Buffer is empty!
21:11:21.661 [crypto.client.lukas] GetNextTCert -> ERRO 6141 Failed getting a new TCert. Buffer is empty!
21:11:22.017 [crypto] closeClientInternal -> INFO 6142 Closing client [lukas]...
21:11:22.019 [crypto] InitClient -> INFO 6143 Initializing client [lukas]...
21:11:22.020 [crypto] InitClient -> INFO 6144 Client already initiliazied [lukas]. Increasing counter from [100]
21:11:22.843 [crypto.client.lukas] GetNextTCert -> ERRO 6145 Failed getting a new TCert. Buffer is empty!
21:11:23.629 [crypto.client.lukas] GetNextTCert -> ERRO 6146 Failed getting a new TCert. Buffer is empty!
21:11:23.820 [crypto.client.lukas] GetNextTCert -> ERRO 6147 Failed getting a new TCert. Buffer is empty!

**Comment by adecaro** [comment]
Yes, make sense this. I have a better picture now. Let's continue the investigation. Is there a document that describes how to use SoapUI?

**Comment by dongmingh** [comment]
with the latest code from @adecaro, it performs 20 tps.

**Comment by adecaro** [comment]
@dongmingh If you have already moved to go1.6, may you pull again and test how tps you get? I have modified a few lines to take advantage of the new optimized elliptic curve provided by go1.6. Thanks.

**Comment by dongmingh** [comment]
With the latest code from @adecaro this afternoon, the tps = 235 for query and 130 for invoke with both security and privacy enabled, threads = 100.
However, I observed a crash which is not crypto related, see detail in bug #714

**Comment by dongmingh** [comment]
With the latest code from PR #705, crash is not seen and the performance as follow
The setting and results are as follow with your latest PR code.
test setting:
 security enabled
 privacy enabled
 TLS enabled
 rootcert: file: "/var/openchain/production/.obcca/tlsca.cert"
 logging: peer and crypto : error

results:
 batch = 200, tps (query/invoke) = 236/147
 batch = 500, tps (query/invoke) = 236/135
where batch is the number of TCerts obtained for at a given time from obcca. 

This is an improvement of 30 times from the tps = 4 invoke we observed when the bug was opened.

**Comment by muralisrini** [comment]
Thanks, @dongmingh @adecaro ... will merge PR #705

**Comment by bmos299** [comment]
Closing as per Murali and Dongming.
