### ISSUE TITLE
Don't have crypto sign()/verify() methods print out all message content in debug log.

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#692]
for example ,  [here](https://github.com/openblockchain/obc-peer/blob/master/openchain/crypto/node_sign.go#L43)  or [here](https://github.com/openblockchain/obc-peer/blob/master/openchain/crypto/node_sign.go#L28)

If you run with logging level=debug,  this increases log size by 10x or more, (e.g. it will print out a 17MB chaincode) and throw off readability of that log.

I'd say only print on error.

**Comment by adecaro** [comment]
@tuand27613 what do you think if I rather introduce the property logging.crypto (openchain.yaml) to setup the logging level of the crypto module?

**Comment by tuand27613** [comment]
@adecaro , logging.crypto will work for me. Thanks !

**Comment by adecaro** [comment]
This has been addressed by PR #705.
