### ISSUE TITLE
Make PBFT log size multiplier configurable

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#694]
Today, the PBFT log size is fixed at `L=2*K` as prescribed in the paper.

However, the choice of `2` is arbitrary, as the log size `L` is used as parameter and no special properties about it (other than its size being at least `2*K` is relied upon.

For certain deployments, especially high volume high latency ones, the default log multiplier of 2 may be insufficient.  As seen in issue #687, we are observing behavior where replicas in a normally functioning pbft network are occasionally receiving sequence numbers outside of the watermarks, increasing the log size `L` could help improve the operation of such networks.

Therefore, we should introduce a configuration variable, maybe `logMultiplier`, which will default to 2.

@kchristidis Can you tag as appropriate and possibly assign to me?

**Comment by jyellick** [comment]
@kchristidis @tuand27613 if @tuand27613 wants this one, it's fine by me

**Comment by tuand27613** [comment]
merged pull request #694
