### ISSUE TITLE
State transfer should retrieve defaultPeerIDs from Stack

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#695]
State transfer currently expects a list of PeerIDs in its constructor.  This makes testing more difficult, and is especially problematic for the `N=1` PBFT case.

Instead, state transfer should interrogate the stack to discover the IDs of other validating peers that it can sync from.

@kchristidis Could you tag with statetransfer, and assign to me?

**Comment by tuand27613** [comment]
all yours @jyellick

**Comment by jyellick** [comment]
This was included in PR #833
