### ISSUE TITLE
Classic PBFT hangs under stress

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#699]
Observed in

```
commit 7abd041f5b9e5ce346d1608f26b6880f6e235a77
Merge: 5077256 4fd8ae5
Author: Binh Q Nguyen <binhn@us.ibm.com>
Date:   Wed Feb 17 13:29:30 2016 -0500

    Merge pull request #682 from adecaro/crash_issue669

    Fix for issue #669
```

Same setup and irritation as in #687. I have a 4-peer docker-compose network running classic PBFT using all default parameters. I send 1000 transactions as fast as possible. The good news is that the network usually does not crash (#696 is rare) and eventually arrives at the correct answer. The issue is that it takes 8 or 9 minutes after I send in the last transaction for the database to correctly record the last transaction. 

You can see in this trace that the network is only processing 20 or 40 transactions every 30 seconds after the last transaction has been sent over the REST API. Note that security is _not_ enabled in this network (#684).

```
[bcbrock@arlab178]$ driveEx02 172.17.0.1 -rest -n 1000 -wait 30 -reCheck
Waiting 30 seconds for chain state to stabilize
 A: Got -638, expected -1000 B: Got 638, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -658, expected -1000 B: Got 658, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -678, expected -1000 B: Got 678, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -698, expected -1000 B: Got 698, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -738, expected -1000 B: Got 738, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -758, expected -1000 B: Got 758, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -778, expected -1000 B: Got 778, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -798, expected -1000 B: Got 798, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -838, expected -1000 B: Got 838, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -858, expected -1000 B: Got 858, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -878, expected -1000 B: Got 878, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -898, expected -1000 B: Got 898, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -938, expected -1000 B: Got 938, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -958, expected -1000 B: Got 958, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -978, expected -1000 B: Got 978, expected 1000
Waiting 30 seconds for chain state to stabilize
 A: Got -998, expected -1000 B: Got 998, expected 1000
Waiting 30 seconds for chain state to stabilize
Runtime: 4.519867 seconds
Rate   : 221.2 transactions/second
```

Note 221 TX/sec is only for the initial send of 1000 TX.

Looking at `top`, the peers/chaincode are practically idle during this 8-9 minute period. Thinking this might be due to I/O I took a `dstat` visualization; I/O is nominal during this period.
![screen shot 2016-02-17 at 5 59 11 pm](https://cloud.githubusercontent.com/assets/11968347/13129475/d71efa3c-d5a2-11e5-96ea-a3bc28c40c3d.png)

Here are the full DEBUG -level logs from the 4 peers.
[logs.tgz.zip](https://github.com/openblockchain/obc-peer/files/135403/logs.tgz.zip)

**Comment by corecode** [comment]
This is likely a combination of multiple bugs.

One is that because of null request pruning, the new primary does not include any requests in the xset, and therefore does not update its own `seqNo`.  This prevents the new primary to assign sequence numbers to the outstanding requests, which in turn renders it useless.  Once `N=4` view changes have occurred, vp0 becomes primary again and manages to pick up where it left off.

**Comment by corecode** [comment]
The other bug is that `moveWatermarks` needs to trigger processing of outstanding requests that have queued up, because we ran out of sequence numbers.  We should revisit all functions that use the _UPON_ term in the PBFT paper.

**Comment by vukolic** [comment]
while this is being fixed - it might be wise to drop "eventual" from the name of the issue

**Comment by tuand27613** [comment]
@bcbrock , please verify.

**Comment by bcbrock** [comment]
It is difficult to know if this issue has been resolved or not, since the OBC protocol documentation does not address what is supposed to happen when a network is flooded with more legitimate transactions than it can process in real time. 
In my latest test I used 64 clients to each send 1000 transactions as fast as possible. The 64K transactions were all accepted by the network in 216 seconds. However, 30 seconds later we see that only 1500 have actually been processed. The network then proceeds to process the backlog at an average rate of about 5 TX/seconds. It would have taken this system about 3.5 hours to process the backlog if it had not failed. This is much faster than before, where we saw the backlog processed at about 1 TX/second.
After 10 minutes working the backlog the network stopped processing transactions. As far as I can tell, none of the peers or chaincodes crashed, they simply appear to have stopped working on the backlog. I don't see any obvious "smoking gun" error message in the logs, but peer 1 does report some errors that I have never seen before:

```
/home/bcbrock/vp1_logs/stderr:14:40:56.231 [consensus/statetransfer] stateThread -> ERRO 18de65 name:"vp1"  could not retrieve blocks as recent as 4360 as the block hash advertised
/home/bcbrock/vp1_logs/stderr:14:40:56.233 [consensus/statetransfer] stateThread -> ERRO 18de89 name:"vp1"  believed its state for block 4360 to be valid, but its hash (58c3abaf01657c5a08e2c303d719db683a87a329898cf84d4e72c08f6d665f3d892e47cd6ad5a0b2b37023f6e1be4665ed5f6881f01997f5d5433c6d1e6202bf) did not match the recovered blockchain's (5b6900f1ce29b19d3d2d00350b0ff9f6e6707a3f2b9f49b7044f8acd6637161a38cd5e4add7707074d179b3342966be21ae6c2bc17154258eb780f49544c06f4)
/home/bcbrock/vp1_logs/stderr:14:40:56.620 [consensus/statetransfer] stateThread -> ERRO 192241 name:"vp1"  recovered to an incorrect state at block number 4701, (62e5208d8efd9fbb2a574d77e7bff5fef464975008f671cd33d9a0a77cf05b17a400212be5349f65da2678cef3aa96680225a6443db4578f2e50e7f0582beb54 47ccc4cf8d69ac32e69284d359fa34f908e20d013d9973d5b2138366fff00db6327a626f83dc194ff05bd9fbb2241bdf66229ade2eb5d9ad61f354ce3c450e39) retrying
```

Following this there are 100's of messages like the last one with increasing block numbers.

**Comment by jyellick** [comment]
@bcbrock I'll investigate those stateThread errors, that pattern of log messages indicates a bug.

**Comment by jyellick** [comment]
The merge request referenced above should fix some of the behavior you are observing in the logs.  It may not fix the originating issue, but may allow recovery to complete whereas the recovery was stalled indefinitely before.

**Comment by bcbrock** [comment]
The system is still failing/locking up. It appears to be less stable than before. Previously it would fail while trying to clear up the backlog. Now it appears to fail/hang during processing of the original burst of transactions.  I have attached the ERRO/WARN messages from the logs.

[errors.txt](https://github.com/openblockchain/obc-peer/files/146957/errors.txt)

One change, which may or not be relevant: I removed the restriction of GOMAXPROCS=2, the system can now use as many threads as it likes.

**Comment by bcbrock** [comment]
I tried @corecode 's closed-loop-rest patch with a timeout of 60. For small numbers (1 - 4) of concurrent clients it seems to works. With 8 or 16 it fails. The failures now are all seen as "hangs" - processing stops. Here are the error messages from a 16-client run that failed almost immediately.

[errors.txt](https://github.com/openblockchain/obc-peer/files/149165/errors.txt)

**Comment by bcbrock** [comment]
@bmos299 - This issue should be marked as a bug

**Comment by jyellick** [comment]
This code path is being overhauled via issue #751, that work will hopefully resolve this issue.

**Comment by bmos299** [comment]
@bcbrock @jyellick . Thanks Jason.  Added sev2 to the bug as well.

**Comment by tuand27613** [comment]
verify when #751 is merged

**Comment by bmos299** [comment]
@bcbrock.  Are you going to merge this?  Can you coordinate with @RicHernandez2 on this?  We want to ensure thorough testing on this one. 
Thanks.

**Comment by bcbrock** [comment]
@bmos299 - Not sure what you mean. I am not aware that a fix is available.

**Comment by tuand27613** [comment]
Bishop, now that PR #833 is done, can you re-run ?

**Comment by bcbrock** [comment]
OK, I am now at

```
commit f08ccce33b13f23eb1af97a43bf654aa48129794
Merge: ab0e167 bfecc0f
Author: tuand27613 <tdang@us.ibm.com>
Date:   Thu Mar 24 17:30:24 2016 -0400

    Merge pull request #833 from jyellick/executor-split

    obcpbft Executor split
```

I'm running a network of 4 validating peers with multiple chain codes, sending transactions to peers randomly.  The test failed when a couple of the transactions never appeared in the blockchain. I've attached a summary of all of the errors. This one looks like  a smoking gun - everything seems to have stopped working after this.:

```
/home/bcbrock/vp1_logs/stderr:13:45:27.099 [consensus/obcpbft] Checkpoint -> ERRO 19b1 Attempted to checkpoint a sequence number (44) which is not a multiple of the checkpoint interval (10)
```

[errors.txt](https://github.com/openblockchain/obc-peer/files/189580/errors.txt)

**Comment by bcbrock** [comment]
I reran the same test, here are the errors from that run

```
/home/bcbrock/vp1_logs/stderr:[31m14:04:02.516 [peer] handleChat -> ERRO 061[0m Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp3"  172.17.0.4:30303 VALIDATOR }
/home/bcbrock/vp1_logs/stderr:[31m14:06:43.856 [consensus/obcpbft] Checkpoint -> ERRO 16aa6[0m Attempted to checkpoint a sequence number (564) which is not a multiple of the checkpoint interval (10)
/home/bcbrock/vp1_logs/stderr:[31m14:06:47.915 [consensus/statetransfer] stateThread -> ERRO 1a6ec[0m name:"vp1"  could not retrieve blocks as recent as 780 as the block hash advertised
/home/bcbrock/vp1_logs/stderr:[31m14:06:47.917 [consensus/statetransfer] stateThread -> ERRO 1a702[0m name:"vp1"  believed its state for block 780 to be valid, but its hash (b069036525d965e352e84c3f8435b853ed7615c768480e05c3f51e9ddbf7cef191c95583e7a47d3c32cc889a20b0ff3151213c17166b31d20a442a853d076a4c) did not match the recovered blockchain's (b265fc5744deb0ea0ae90bcb4aa96b31fad9b85646be1be7304d784863427bfbb08c0b6818ea01f0db5c1fccde87ae95b09e5d4f8cf964fe355a937438efdfc4)
/home/bcbrock/vp2_logs/stderr:[31m14:04:02.920 [peer] handleChat -> ERRO 060[0m Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp3"  172.17.0.4:30303 VALIDATOR }
/home/bcbrock/vp3_logs/stderr:[31m14:04:02.517 [peer] handleChat -> ERRO 05e[0m Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp1"  172.17.0.3:30303 VALIDATOR }
/home/bcbrock/vp3_logs/stderr:[31m14:04:02.920 [peer] handleChat -> ERRO 069[0m Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp2"  172.17.0.5:30303 VALIDATOR }
```

When I get back next week I'll post my test suite on a Github so you guys can run it yourselves.

**Comment by jyellick** [comment]
The `Checkpoint` and `stateThread` errors are interesting (although perhaps they should be warnings, as they are non-fatal, and based on the lack of other errors, the recovery mechanisms seem to be working), I'll take a look at the code to see how those might arise.

I have frequently seen the `handleChat` errors as well, I suspect that these arise when there is a disruption of network connectivity between peers, and on renegotiation the peers have already been discovered, maybe @jeffgarratt can weigh in on those.

**Comment by jeffgarratt** [comment]
@jyellick there is a modification that needs to be made wrt to chat termination.  I can take a look at this shortly.

**Comment by jyellick** [comment]
@bcbrock Can you confirm whether you are still seeing the original slow transaction rate?

Can you also confirm that this is still 'classic' PBFT? (Not batch, or Sieve)

**Comment by bcbrock** [comment]
@jyellick Unfortunately the system is no longer able to process the type of test that led to the original performance report without experiencing fatal errors (#879). Yes this is "classic" PBFT.

**Comment by binhn** [comment]
@jyellick any progress on this one?

**Comment by bcbrock** [comment]
@binhn @jyellick I can close this. The original issue is no longer observed. I do still see hangs, but I am waiting for #1091 to be resolved before digging deeper.
