### ISSUE TITLE
State transfer always fails to verify existing blockchain

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#700]
It has been observed in PBFT testing that a peer with an existing blockchain will always fail to validate its chain, causing a loop where it attempts to retrieve corrupt blocks which are apparently not corrupt.

This is not apparent in mock testing, so may be a bug in the underlying ledger verification utilities or a difference in the mock vs. real API.

@kchristidis Could you tag this as a bug, for state transfer, and assign to me?

**Comment by tuand27613** [comment]
all yours @jyellick 

ah, the power of being a committer :)
