### ISSUE TITLE
chaincode logging fills up system drive

### ISSUE THREAD

**Issue by corecode** [hyperledger-archives/fabric#709]
I ran an invoke loop over night, and the chaincode logging inside the docker container filled up my (host) filesystem; 9GB of JSON logs.  This may also explain why I observe high CPU utilization of the docker process.

**Comment by corecode** [comment]
log sample:

```
2016/02/20 13:47:57 [9b79d09d]before send
2016/02/20 13:47:57 [9b79d09d]after send
2016/02/20 13:47:57 [9b79d09d]Received RESPONSE, communicated (state:transaction)
2016/02/20 13:47:57 [9b79d09d]Received RESPONSE. Successfully updated state
2016/02/20 13:47:57 [9b79d09d]Transaction completed. Sending COMPLETED
2016/02/20 13:47:57 [9b79d09d]Move state message COMPLETED
2016/02/20 13:47:57 [9b79d09d]Handling ChaincodeMessage of type: COMPLETED(state:transaction)
2016/02/20 13:47:57 [9b79d09d]send state message COMPLETED
2016/02/20 13:47:57 [f5c6aa36]Received message TRANSACTION from shim
2016/02/20 13:47:57 [f5c6aa36]Handling ChaincodeMessage of type: TRANSACTION(state:ready)
2016/02/20 13:47:57 [f5c6aa36]Received TRANSACTION, invoking transaction on chaincode(Src:ready, Dst:transaction)
2016/02/20 13:47:57 [f5c6aa36]Sending GET_STATE
2016/02/20 13:47:57 [f5c6aa36]Received message RESPONSE from shim
2016/02/20 13:47:57 [f5c6aa36]Handling ChaincodeMessage of type: RESPONSE(state:transaction)
```

**Comment by kletkeman** [comment]
Looks like debug info. Some components have been slow to respect the logging levels. The peer remains pretty chatty by default.

**Comment by mastersingh24** [comment]
this is not hard to avoid.  Docker actually has a parameter for controlled the size of maintained logs.  We should add this as part of the config parameters.

**Comment by muralisrini** [comment]
following up on @mastersingh24 suggestion.

Docker itself has log file control params. Needs investigation on the how these are exposed in the go docker client we use for controlling logging. https://github.com/fsouza/go-dockerclient/blob/master/container.go has "LogConfig" struct that's probably a good starting point. If we find something useful we can add parameter(s) core.yaml under chaincode to control log size.

**Comment by genggjh** [comment]
This is log related opt: https://github.com/docker/docker/pull/11485
And related document: https://docs.docker.com/engine/admin/logging/overview/

So basically, we need following two options:
--log-opt max-size=[0-9+][k|m|g]
--log-opt max-file=[0-9+]

**Comment by mastersingh24** [comment]
https://github.com/hyperledger/fabric/pull/1269  should allow this to be handled now since the HostConfig actually contains LogConfig

**Comment by genggjh** [comment]
ok, cool, should be easy to just update the core.yaml to fix this. I think we need provide a default value of max-size to avoid the log file fills up the disk space.
