### ISSUE TITLE
Error: No such image or container: bddtests_vp0_1...

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#715]
Observed "**Error: No such image or container: bddtests_vp0_1...**" while running Behave tests using TRAVIS Continuous Integration tool (Outside Vagrant).

Successfully ran the "go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)" command and then ran the behave test.
[Travis CI_logfile_parse_error.txt](https://github.com/openblockchain/obc-peer/files/141246/Travis.CI_logfile_parse_error.txt)

**Log File:**:
The command "go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)" exited with 0.
$ behave

Feature: lanching 3 peers # peer_basic.feature:11
  As an openchain developer
  I want to be able to launch a 3 peers
  Scenario: chaincode example 02 single peer                                                                                               # peer_basic.feature:17
    Given we compose "docker-compose-1.yml"                                                                                                # steps/peer_basic_impl.py:78
Given we compose "docker-compose-1.yml"                                                                                                # steps/peer_basic_impl.py:78 0.503s
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1903, in run
          self.func(context, _args, *_kwargs)
        File "steps/peer_basic_impl.py", line 89, in step_impl
          parseComposeOutput(context)
        File "steps/peer_basic_impl.py", line 44, in parseComposeOutput
          bdd_test_util.cli_call(context, ["docker", "inspect", "--format",  "{{ .NetworkSettings.IPAddress }}", containerName], expect_success=True)
        File "/home/travis/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests/steps/bdd_test_util.py", line 27, in cli_call
          raise subprocess.CalledProcessError(p.returncode, arg_list, output)
      CalledProcessError: Command '['docker', 'inspect', '--format', '{{ .NetworkSettings.IPAddress }}', 'bddtests_vp0_1...']' returned non-zero exit status 1  
      Captured stdout:
      ['Creating', 'bddtests_vp0_1...']
      ['bddtests_vp0_1...']
      Output: 

```
  Error Message:
  Error: No such image or container: bddtests_vp0_1...
```

**Comment by jyellick** [comment]
Can you verify that docker compose is installed?

```
$ docker-compose --version
docker-compose version 1.5.2, build 7240ff3
```

If it is not, you can most likely install it via:

```
curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
service docker restart
```

**Comment by rameshthoomu** [comment]
@jyellick above mentioned issue is working fine after installing the docker-compose version 1.5.2.

**Comment by jyellick** [comment]
@rameshthoomu Can this issue be closed then?

**Comment by rameshthoomu** [comment]
Yes. Please close this issue.

**Comment by jyellick** [comment]
Thanks @rameshthoomu !
