### ISSUE TITLE
CA in Bluemix under low load keeps giving "Not available yet" message

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#716]
Description:  CA in Bluemix with Security turned on gives a "Not available yet..." message over and over in logs under light load.

Steps to repro:

 1   Provision a set of blockchain servers with security enabled (CA, Va1, Va2) on Bluemix.com
 2  Copy the name of that blockchain set to your manifest.yml file on the app.js home directory
 3   Ensure the package.json contains a unique name for your app.js
4    Create a Node.js app
5    Bind the app to the blockchain set
6    cf push app.js
7    Select your blockchain set
8    Click launch
9    View logs
10    View CA logs Note the following:

Results:

2016-02-16T15:08:36.091052024Z Not available yet...

2016-02-16T15:08:36.091052024Z Not available yet...

2016-02-16T15:08:36.091052024Z Not available yet... 

Expected Results:

The CA should be able to keep up with certificate requests from traffic from two validating peers, or there should be more CAs provisioned per validating peer and some sort of load balancing implemented between CAs.

**Comment by thkzrl** [comment]
It is not clear where that log message is coming from. The OBC-CA does NOT generate this log message, and neither can I find it in the peer code base.  Will investigate further...

**Comment by RicHernandez2** [comment]
![ca messages](https://cloud.githubusercontent.com/assets/17052305/13255615/e4254026-da14-11e5-8cd2-a59ade807de0.JPG)

**Comment by RicHernandez2** [comment]
Here's what's happening on the VPs at the time, essentially the CA is giving no useful information at all in its logs.

![vp1vp2](https://cloud.githubusercontent.com/assets/17052305/13255891/4b5789a6-da16-11e5-8cb4-8bd83ab2bb51.JPG)

**Comment by thkzrl** [comment]
You may enable the trace log level to make the CA more verbose (set logging.trace to 1 in obcca.yaml) but, as said, the log message is not from the CA itself.

I'm waiting for my Bluemix account to become active so that I can start investigating.

**Comment by bmos299** [comment]
Closed, moving to appropriate location
