### ISSUE TITLE
CA not reporting percentages and stats to logs

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#717]
Details:

CA in Bluemix cloud not giving out percentage stats in logs

Steps to repro:

1 Provision a set of blockchain servers with security enabled (CA, Va1, Va2) on Bluemix.com
2 Copy the name of that blockchain set to your manifest.yml file on the app.js home directory
3 Ensure the package.json contains a unique name for your app.js
4 Create a Node.js app
5 Bind the app to the blockchain set
6 cf push app.js
7 Select your blockchain set
8 Click launch
9 View logs
10 View CA logs Note the following:

2016-02-16T15:08:37.706862941Z % Total % Received % Xferd Average Speed Time Time Time Current

2016-02-16T15:08:37.706997172Z Dload Upload Total Spent Left Speed

Results:

% Stats are ostensibly written to logs with no values

Expected Results:

% Stats must have number values attached to them when written to log.

**Comment by bmos299** [comment]
Closing.
