### ISSUE TITLE
Double messages in log?

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#721]
Description:

There are two messages in a Validating Peer's logs when closing the Keystore

Steps to Repro:
1.  Start a blockchain service in bluemix with security on
2.  bind to cloud foundry node.js app service running IBM-blockchain-js
3.  Run example02 code
4.  Perform invokes on the blockchain service
5.  View logs on blockchain service for VP1

Results:

2016-02-23T17:23:40.841356618Z 17:23:40.841 [CRYPTO.client.user_512503759c] close -> INFO 134ee5[0m Closing keystore...

2016-02-23T17:23:40.841391573Z 17:23:40.841 [CRYPTO.client.user_512503759c] close -> INFO 134ee6[0m Closing keystore...done! 

There are two messages generated about closing the Keystore, it is not clear if this is on purpose and due to the time it takes that the message is repeated with the additional information "done!" or if it's an accidental double message.

Expected Results:

If this activity is going to span multiple messages in the log, then the first should perhaps end with "start", differentiating it from in progress "..." and end "done!"

**Comment by bmos299** [comment]
Closed and moved
