### ISSUE TITLE
Assertion failed - behave tests are failing outside of vagrant environment (through Travis ci)

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#722]
Issue: Observed an **Assertion failed** message in the behave test logs while running the Behave test scripts outside of the vagrant environment (Using TRAVIS CI).

The output of the "**ip addr show**" and "**ps -ef | grep docker**" of Travis CI environment is mentioned below:

**ip addr show** for **docker0** inteface
docker0: <BROADCAST,MULTICAST,UP> mtu 1460 qdisc noqueue state UP group default 
link/ether 02:42:3a:a4:d6:cd brd ff:ff:ff:ff:ff:ff
inet 172.17.42.1/16 scope global docker0
valid_lft forever preferred_lft forever

**ps -ef | grep docker**
root      3307     1  5 17:00 ?        00:00:46 /usr/bin/docker daemon -H tcp://127.0.0.1:**2375**-H unix:///var/run/docker.sock
travis   12597  2247  0 17:13 pts/0    00:00:00 grep docker

Below is the Error message displaying in the Behave test log:

**Assertion Failed: Failed to POST to http://172.17.0.13:5000**/devops/query:  {"Error": "Error:Failed to launch chaincode spec(Error starting container: Post http://172.17.0.1:4243/containers/dev-vp0-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c/start: dial tcp 172.17.0.1:4243: getsockopt: no route to host)"}

I have changed the OPENCHAIN_VM_ENDPOINT to "http://172.17.42.1:2375" in compose-defaults.yml and ran the tests but still getting the above error message.

Attached error log file:
[Assertion Failed_BehaveTests.txt](https://github.com/openblockchain/obc-peer/files/143127/Assertion.Failed_BehaveTests.txt)

**Comment by muralisrini** [comment]
assuming this is a simple matter of making sure ip addresses are set in the right places. Working with @rameshthoomu ....

**Comment by rameshthoomu** [comment]
Facing the same issue even after changing the "OPENCHAIN_VM_ENDPOINT" value in "compose-defaults.yml" and "compose-consensus-4.yml" file to OPENCHAIN_VM_ENDPOINT=http://172.17.42.1:2375. Attached the behave log file and "netstat", "ip addr".
[docker0 interface_travisci.txt](https://github.com/openblockchain/obc-peer/files/147385/docker0.interface_travisci.txt)
[Defect#722 - Assertion Failed_OPENCHAIN_VM_ENDPOINT.txt](https://github.com/openblockchain/obc-peer/files/147387/Defect.722.-.Assertion.Failed_OPENCHAIN_VM_ENDPOINT.txt)

**Comment by tuand27613** [comment]
@rameshthoomu , a couple of things to try:
1. in my vagrant environment, `ps -ef | grep docker` says 
   `root       883     1  0 Feb25 ?        00:04:04 /usr/bin/docker daemon -s=aufs -r=true --api-enable-cors=true -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock`
as opposed to `root 3307 1 5 17:00 ? 00:00:46 /usr/bin/docker daemon -H tcp://127.0.0.1:2375-H` in your environment.
try setting the -H option to the actual docker0 interface or to 0.0.0.0
2. this [discussion](http://serverfault.com/questions/710837/port-inside-linked-docker-container-is-not-accessible-to-the-other-container/711585) seems to say that you need to disable **_firewalld_** and **_iptables_**

**Comment by rameshthoomu** [comment]
Below are the steps added to my .travis.yml file and issue got resolved. Thanks @tuand27613  

sudo stop docker
sudo docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &

Please close the defect.

**Comment by tuand27613** [comment]
close #722
