### ISSUE TITLE
Add REST API interrogation of state hash

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#723]
As discussed with @jeffgarratt, in order to validate some of the mechanisms of state transfer, it is necessary that certain properties of the state be able to be interrogated via the REST API for the behave tests.

In particular, the following two pieces of information should be exposed.
1. The current / temporary state hash.  This is the value of `ledger.GetTempStateHash()`, and it is a hash of the current state, including the result of transactions which have not been committed into a block.  For the state hash after committed transactions the existing infrastructure to retrieve block info is sufficient.
2. The set of key values for the current state.  This is the output of `Coordinator.GetStateSnapshot()`.  There is some concern that this could be very large, so some mechanism to mitigate this could be advisable.

**Comment by jyellick** [comment]
I can see this as generally useful, but the bug this would have been useful to debug has been fixed, so feel free to close.

**Comment by angrbrd** [comment]
Closing for now as it sounds like this was needed solely to debug a very specific issue. If this comes up again, please reach out to me and I will address. Thanks.
