### ISSUE TITLE
Remove existing containers for chaincode if NOT already connected.

### ISSUE THREAD

**Issue by jeffgarratt** [hyperledger-archives/fabric#724]
In the case of VP restart, it is possible (and more likely expected) that the VP will be assigned a new IP address. In this case any existing chaincode containers (which will have exited due to disconnect) should be removed instead of re-statred, as the peer.address info may be inaccurate.  Assigning this to @muralisrini

**Comment by jeffgarratt** [comment]
@jyellick this will cause us problems if we stop more than 1 VP and start it again.

**Comment by muralisrini** [comment]
@jeffgarratt : I believe this is fixed with https://github.com/openblockchain/obc-peer/commit/3362078d75dff4a50efee8c669c8fda7e9b6e596 can we close this please ?

**Comment by jeffgarratt** [comment]
indeed it can :)
