### ISSUE TITLE
Inconsistency between docker environment and dev-env

### ISSUE THREAD

**Issue by ghaskins** [hyperledger-archives/fabric#741]
It was discovered that the docker environment was inadvertently based on debian:jessie rather than ubuntu trusty.  This should be based on ubuntu to match the vagrant environment, ideally driven by the same configuration

**Comment by ghaskins** [comment]
@jeffgarratt @srderson @muralisrini @jyellick

**Comment by ghaskins** [comment]
Gah, I started with opening an issue and then seem to have become confused and wrote it like a PR...

**Comment by srderson** [comment]
@ghaskins closing as I believe you have resolved this issue with the openblockchain/baseimage image.
