### ISSUE TITLE
Logging issue in Validating Peer regarding consensus

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#744]
Description:

Consensus in openchain.yaml file can be set to any value

Steps to repro:
1.  Edit openchain.yaml file
2.  Set consensus to "Whoops"
3.  Do a Vagrant up
4.  Do a Vagrant ssh
5.  VP comes up, no mention of consensus setting

Results:

Consensus is not mentioned at all in the logs, no error is thrown due to invalid value

Expected results:

The consensus value should be written to log, an invalid value should cause an error

**Comment by tuand27613** [comment]
We default to `noops` if _peer.validator.consensus_ is not recognized.  I'll update the description in openchain.yaml to make that clearer.

Also, the consensus code logs its settings but peer does lazy evaluation so we don't instantiate the consensus handler until we have a stream.

**Comment by tuand27613** [comment]
PR #746

**Comment by RicHernandez2** [comment]
openchain.yaml change verified
