### ISSUE TITLE
starting peers failed with security enabled

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#747]
Following the [instruction](https://github.com/openblockchain/obc-peer/blob/master/compose-consensus-4.md), set up 4 peers with security enabled.  The peer container exists with errors:

```
log of peer vp0:
  18:08:30.239 [crypto] getECAClient -> DEBU 01f [validator.test_vp0] Getting ECA client...done
  2016/02/26 18:08:31 grpc: ClientConn.resetTransport failed to create client transport: connection     error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused";   Reconnecting to "localhost:50051"
   2016/02/26 18:08:32 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
  2016/02/26 18:08:32 Failed to dial localhost:50051: grpc: timed out trying to connect; please retry.
  18:08:32.908 [crypto] callECAReadCACertificate -> ERRO 020 [validator.test_vp0] Failed requesting read certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
  18:08:32.908 [crypto] getECACertificate -> ERRO 021 [validator.test_vp0] Failed requesting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
    18:08:32.908 [crypto] retrieveECACertsChain -> ERRO 022 [validator.test_vp0] Failed getting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
   18:08:32.908 [crypto] registerCryptoEngine -> ERRO 023 [validator.test_vp0] Failed retrieveing ECA certs chain [rpc error: code = 2 desc = "grpc: the client connection is closing"].
    18:08:32.908 [crypto] register -> ERRO 024 [validator.test_vp0] Failed registering crypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"].
     18:08:32.908 [crypto] register -> ERRO 025 Failed registering [test_vp0]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
    18:08:32.908 [crypto] RegisterValidator -> ERRO 026 Failed registering [test_vp0]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
    18:08:32.908 [crypto] NewPeerWithHandler -> ERRO 027 Failed registering validator [test_vp0] with name [test_vp0] [rpc error: code = 2 desc = "grpc: the client connection is closing"].
    18:08:32.908 [main] serve -> CRIT 028 Failed creating new peer with handler rpc error: code = 2 desc = "grpc: the client connection is closing"
```

Attached zip is the configuration and logs
[config.zip](https://github.com/openblockchain/obc-peer/files/148691/config.zip)

After setting the configuration:
- 1) docker build -t openchain-peer  -f <docker_file> .
- 2) docker build -t obcca -f obc-ca/<docker_file>  .
- 3) in openchain/container folder:
    go test -timeout=20m -run BuildImage_Peer
- 4) docker-compose -f docker-compose.yml -f compose-consensus-4-links.yml -f compose-consensus-4-sieve.yml up --force-recreate -d
- 5) docker exec -it obcpeer_cli_1 bash
- 6) OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer login jim

login failed.

Is there missed something?

**Comment by tuand27613** [comment]
@samding01  in openchain.yaml,  do you have the pki.eca/tca/tlsca addresses as locahost or obcca ? Should be obcca

**Comment by samding01** [comment]
@tuand27613;  Thank for your message. Indeed I forget to update pki part after git pull.

Now it can start all peer containers. However it is still failed to login inside  cli container:

```
 $ docker exec -it obcpeer_cli_1 bash 
  # obc-peer login test_vp3
 19:28:04.411 [crypto] main -> INFO 001 Log level recognized 'debug', set to DEBUG
 19:28:04.411 [crypto] main -> DEBU 002 Working at security level [256]
 19:28:04.411 [logging] LoggingInit -> DEBU 003 Setting default logging level to DEBUG for command 'login'
 19:28:04.411 [main] login -> INFO 004 CLI client login...
 19:28:04.411 [main] login -> INFO 005 Local data store for client loginToken: /var/openchain/production/client/
 Enter password for user 'test_vp3': ************
 19:28:34.608 [main] login -> INFO 006 Logging in user 'test_vp3' on CLI interface...
 2016/02/26 19:28:35 grpc: ClientConn.resetTransport failed to create client transport: connection  error: desc = "transport: dial tcp 0.0.0.0:30303: getsockopt: connection refused"; Reconnecting to "0.0.0.0:30303"
 2016/02/26 19:28:37 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 0.0.0.0:30303: getsockopt: connection refused"; Reconnecting to "0.0.0.0:30303"

 Usage:
  openchain login [flags]

 Global Flags:
      --logging-level="": Default logging level and overrides, see openchain.yaml for full syntax

 Error: Error trying to connect to local peer: grpc: timed out trying to connect
```

No error msg found from logs of obcca and test_vp[0-3].

**Comment by tuand27613** [comment]
you have to specify which peer to login to .  Try something like `OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer login test_user0`

I'd say always use vp0 when doing requests as it's the primary for the peers doing consensus.  There's an existing issue ( I think, too lazy to check ) about sending requests to non-primary replicas

**Comment by samding01** [comment]
After rebuild image: openchain_peer and obcca, now it is OK to login some users.

For a user id defined in other than  docker-compose.yaml, it is OK to login, but if a user id is used
in `docker-compose.yaml`, it cannot login:

```
 # OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer login test_vp0
 21:52:50.724 [crypto] main -> INFO 001 Log level recognized 'debug', set to DEBUG
 21:52:50.725 [crypto] main -> DEBU 002 Working at security level [256]
  21:52:50.725 [logging] LoggingInit -> DEBU 003 Setting default logging level to DEBUG for command 'login'
 21:52:50.725 [main] login -> INFO 004 CLI client login...
 21:52:50.725 [main] login -> INFO 005 Local data store for client loginToken: /var/openchain/production/client/
 Enter password for user 'test_vp0': ************
 21:53:12.488 [main] login -> INFO 006 Logging in user 'test_vp0' on CLI interface...

Usage:
     openchain login [flags]

 Global Flags:
     --logging-level="": Default logging level and overrides, see openchain.yaml for full syntax

 Error: Error on client login: rpc error: code = 2 desc = "identity or token do not match"
```

Here is definition in `docker-compose.yaml`:

> vp0:
>   extends:
>     file: compose-consensus-4-defaults.yml
>     service: vp
>   environment:
>     - OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243
>     - OPENCHAIN_SECURITY_ENABLED=true
>     - OPENCHAIN_SECURITY_PRIVACY=true
>     - OPENCHAIN_PEER_ID=vp0
>     - OPENCHAIN_OBCPBFT_GENERAL_N=4
>     - OPENCHAIN_PEER_VALIDATOR_REPLICAS_IPS=vp0:30303 vp1:30303 vp2:30303 vp3:30303
>     - OPENCHAIN_SECURITY_ENROLLID=test_vp0
>     - OPENCHAIN_SECURITY_ENROLLSECRET=MwYpmSRjupbT

the PW matchs to the one in `obcca.yaml`.
Tried  `test_vp[0-3]`, all cannot login

**Comment by tuand27613** [comment]
The validating peers vp0-3 logged themselves in using the test_vp[0-3] IDs so you can't re-use them for client login. Use the test_user**_X_** IDs instead. All the IDs are defined in `obc-ca/obcca.yaml`

Also, the CA server defines a role for each ID. More details in the [obcca setup doc](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/obcca-setup.md) and in the [devnet setup doc](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devnet-setup.md)

**Comment by samding01** [comment]
@tuand27613 : Thank you for your explanation.  now it is OK to send REST insider cli. I think this issue can be closed.

 One question on how to send REST outside of cli container.
I use cmd:
     curl -X POST -d @register.json     localhost:5000/registrar

and `register.json` has:

```
{
 "enrollId": "jim",
 "enrollSecret": "6avZQLwcUe9b"
}
```

The response is:

```
  {"Error": "rpc error: code = 2 desc = 'identity or token do not match'"}
```

The PW matches, what is the problem here?

Thanks,

**Comment by samding01** [comment]
@tuand27613 

Found the reason,  because I had use "jim" to login inside of cli, so it cannot  re-login outside of cli container. Change another user id. It works fine.

Thanks,

**Comment by muralisrini** [comment]
@tuand27613, @samding01  : sounded like there's some room to make doc clearer to help other who might run into similar issues ?

**Comment by tuand27613** [comment]
good point @muralisrini 

@samding01 could you post your comments over on obc-docs , expecially on the dev-setup docs ? What should we make clearer ?

**Comment by samding01** [comment]
@tuand27613 :

From Doc on 4 peers with security enabled: https://github.com/openblockchain/obc-peer/blob/master/compose-consensus-4.md

1) For each peer defined in `compose-consensus-4.yml`, add or change:

```
   OPENCHAIN_SECURITY_ENABLED=true
   OPENCHAIN_SECURITY_PRIVACY=true
```

2) Each user id defined in `obc-ca/obcca.yml` can be login ( `OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer <user_id\>`) in only place;
For example,  a user_id  used in  `compose-consensus-4.yml`, cannot be used with command
`OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer <user_id\>`

3) Can you change the error msg to show the a user-id cannot be logined in different places?

```
  (Error: Error on client login: rpc error: code = 2 desc = "identity or token do not match")
```

**Comment by samding01** [comment]
@tuand27613 

Hi Tuan,
I do not know your email address, so send you message via this.

I try to setup more peers (8)  by updating all  `yml` files and `openchain.yaml`, `obc-ca/obcca.yaml`. 
here is the zip of all the files 
[config8.zip](https://github.com/openblockchain/obc-peer/files/151728/config8.zip).

Build two images of `openchain_peer` and `obcca`.  Then

```
  cd openchain/container/
  go test -timeout=20m -run BuildImage_Peer
```

Starting docker-compose:

```
   docker-compose -f docker-compose.yml -f compose-consensus-4-links.yml -f compose-consensus-4-sieve.yml up --force-recreate -d
```

The first 4 peers (vp0-vp3) and `cli`, `obcca`  are running, however other 4 peers (vp4-vp7) exit:

```
  38825cf9d409        openchain-peer      "obc-peer peer"       2 hours ago         Exited (1) 2 hours ago                       obcpeer_vp4_1
```

How do I start more than 4 peers? Do I miss something here?

Thanks,
