### ISSUE TITLE
Chaincode termination if OPENCHAIN_SECURITY_PRIVACY = false

### ISSUE THREAD

**Issue by exactproskl** [hyperledger-archives/fabric#749]
Chaincode termination if OPENCHAIN_SECURITY_PRIVACY = false

**Version:** b6ea3b0

**Conditions**
- A single peer works in chaincode-dev mode with enabled security and privacy
- The example_chaincode02 and the obc-ca server are also run on the same host inside the vagrant dev environment
- The only one user user Jim has logged in the system via CLI

**Steps to reproduce**

_Deploy_

```
OPENCHAIN_SECURITY_ENABLED=true OPENCHAIN_SECURITY_PRIVACY=true obc-peer chaincode deploy -u jim -n mycc -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
```

_Query_

```
OPENCHAIN_SECURITY_ENABLED=true OPENCHAIN_SECURITY_PRIVACY=true obc-peer chaincode query -u jim -n mycc -c '{"Function":"query", "Args": ["a"]}'
```

_Query with missed OPENCHAIN_SECURITY_PRIVACY variable_

```
OPENCHAIN_SECURITY_ENABLED=true obc-peer chaincode query -u jim -n mycc -c '{"Function":"query", "Args": ["a"]}'
```

**Result**

Chaincode terminates with the message:

```
Error starting Simple chaincode: Error handling message: [b8ab7ea7-913f-4685-b3cb-06b6e91cde11]Chaincode handler FSM cannot handle message (ERROR) with payload size (52) while in state: ready
```

An encryption error on the peer's side:

```
17:30:57.241 [chaincode] func1 -> ERRO 023 [b8ab7ea7]Got error (error getting crypto encryptor Invalid invoke nonce.) while decrypting. Sending ERROR
17:30:57.245 [chaincode] processStream -> ERRO 024 [b8ab7ea7]Error handling message, ending stream: [b8ab7ea7-913f-4685-b3cb-06b6e91cde11]Chaincode handler validator FSM cannot handle message (ERROR) with payload size (134) while in state: ready
```

Could you please clarify whether this is expected behavior or not?

Thank you

**Comment by muralisrini** [comment]
It is expected behavior (as implemented, that is). The key is this error "Got error (error getting crypto encryptor Invalid invoke nonce.) while decrypting". Peer is unable to decrypt as the OPENCHAIN_SECURITY_PRIVACY is not set.
