### ISSUE TITLE
running parallel requests to /chain endpoint crashes peer

### ISSUE THREAD

**Issue by alexmnguyen** [hyperledger-archives/fabric#750]
I've been writing a node.js application to analyze the performance of obc-peer. I've run into an issue when running parallel requests. The steps are:

1) Start up peer with the following command:

```
docker run --rm -it -p 5000:5000 -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer --logging-level=debug
```

2) Run 500 GET requests to the /chain endpoint of the REST API in parallel. This works fine.
3) Deploy contract through the REST API using the /devops/deploy endpoint:

```
{
  "type": "GOLANG",
  "chaincodeID": {
    "path": "github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
  },
  "ctorMsg": {
    "function": "init",
    "args": [
      "a","100","b","200"
    ]
  },
  "secureContext": "string",
  "confidentialityLevel": "PUBLIC"
}
```

4) Run 500 requests against the /chain REST API endpoint in parallel again. This will actually crash the peer. 

I've seen that the performance goal is 100,000 requests per second, but it seems this is an easy way to force a peer to crash.

**Comment by angrbrd** [comment]
Hi, @alexmnguyen. Any stack trace or output that you see on the console during this crash that you could share here? Thanks.

**Comment by alexmnguyen** [comment]
Hi @angrbrd. Here is the stack trace:
[crashLog.txt](https://github.com/openblockchain/obc-peer/files/151445/crashLog.txt)

If you'd like to see the node.js application itself to see how the requests were created, you can search for the following project in the internal github repository:

```
obc-performance-monitor
```

**Comment by christo4ferris** [comment]
@bcbrock have you observed this behavior with busywork? @alexmnguyen is this still an open issue or can it be closed?

**Comment by bcbrock** [comment]
@alexmnguyen  @christo4ferris This issue is so old (based on openblockchain) that I believe it should either be reproduced on the current codebase or closed.
