### ISSUE TITLE
Factor out and implement split `Orderer` and `Executor` services

### ISSUE THREAD

**Issue by jyellick** [hyperledger-archives/fabric#751]
The design of `obcpbft` attempts to separate the core pbft functions from the specific implementations, ie `obc-batch`, `obc-classic`, and `obc-sieve`.

However, a greater level of abstraction is required to isolate the ordering from the execution.
## API

This issue proposes a new `Executor` service with the following simple API:

```
ValidState(seqNo uint64, checkpointID []byte, sources []interface{})
Execute(seqNo uint64, request []byte, execInfo ExecuteInfo)
```

The `ValidState` call is invoked whenever the `Orderer` becomes aware of a state which the network has determined to be valid.  This call is not to be replied to.  In the PBFT standard case, this would be invoked when `f+1` checkpoint certificates have been received, but could also be invoked during a view change.  The `checkpointID` is discussed below, but is an opaque `[]byte` supplied by other `Executor`s.   The `sources` parameter indicates a list of locations which the `Executor` can retrieve the state from.  Note, for now this is labeled as `[]interface{}`, because it is not obvious whether this should be the replica ID, peer ID, or some other abstraction.

The `Execute` call is invoked for a request that should be executed with a particular sequence number.  The request is passed as an opaque `[]byte`.  The `ExecuteInfo` indicates what sort of response the `Executor` should deliver to the `Orderer` (presently only one response `Checkpoint` is proposed), and any other useful metadata, such as if the `Orderer` realizes there is going to be a gap in the sequence numbers (indicating a state transfer is necessary).

In the event that an execution request is tagged as requesting a `Checkpoint` response, after the request is invoked, then the `Executor` would invoke on the `Orderer`

```
Checkpoint(seqNo uint64, id []byte)
```

Where `id` is an opaque `[]byte`.  This should include at least, the a hash of the state corresponding to the sequence number, and optionally any metadata (such as in the case of `obc`, the block number). 
## State Transfer

It would be the executor's sole responsibility to perform state transfer.  The `Orderer` is frequently informing the `Executor` of known valid states, and so the `Executor` should never be stuck in an inconsistent state for any long amount of time.  Because it is the `Executor` which supplies the opaque `id []byte`, the executor can ensure that the checkpoint value contains all necessary information to recover the state.

Because execution requests contain sequence numbers, the `Executor` can detect if it is missing a transaction and optionally choose to initiate state transfer to a later point.

The `Executor` may choose to implement its execution queueing in whatever way it desires.  Typically the queue size would be expected to be configured to match the PBFT log size.  If the queue runs out of space, then it would be anticipated that the `Executor` would initiate state transfer.

Finally, in the case of the backing PBFT replica falling out of date, or in the case of a view change, the `ExecuteInfo` would contain a flag indicating that there are skipped sequence numbers prior to this requests sequence number, and the `Executor` should perform state transfer to a point beyond that sequence number.

I'm particularly interested in input from @corecode, as well as @kchristidis and @tuand27613.

**Comment by tuand27613** [comment]
@jyellick , let's decide today how we want to merge this

**Comment by tuand27613** [comment]
close via #833
