### ISSUE TITLE
Error handling and panics

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#752]
This started out as an email thread but I'm creating an issue so we can discuss some of the design questions that came up.

**Comment by tuand27613** [comment]
comments from @corecode 

We could just rename it to "ASSERT()".

It seems we're lacking a user friendly way of aborting if something is wrong (e.g. config file is inconsistent).

On a broader level, the project overall should define what constitutes an error, and how errors need to be handled.  Right now most functions return an error, even though for some of those function no error can ever happen, or the error would be fatal.  Ideally we would define for every function which conditions cause an error, and whether the error can be transient and the operation can be retried later.

For example:  if GetLedger() fails, what are we supposed to do?  To me, that's a fatal condition, if you can't get the ledger.  Something must be seriously wrong.

Or, what does it mean that Broadcast() failed?  Did one peer Send() not succeed?  Are there no peers?  Did no Send() succeed?  Right now, consensus tends to return these errors, when the called function is the last function in the consensus function.  But essentially, during operation, consensus returning an error does not make any sense.

**Comment by tuand27613** [comment]
more from @corecode 

what we should do if:
1. there is a configuration error, which prevents us from operating (e.g. number of nodes is negative)
2. there is a programming error (e.g. invalid argument or return value, which should have been prevented by the interfacing code).

Typically I would handle (1) by printing an error and exiting the application, or using a generic function somewhere which does exactly that.
I would handle (2) by adding ASSERT()s, which then turn into panic() or some other form of abort.
I guess this would apply across OBC

**Comment by kchristidis** [comment]
@binhn Can we have your take on this one? Specifically @corecode's comments ([one](https://github.com/openblockchain/obc-peer/issues/752#issuecomment-190377184), [two](https://github.com/openblockchain/obc-peer/issues/752#issuecomment-190377674)).

**Comment by binhn** [comment]
For recoverable conditions, obviously we don't want to abort the peer. 

For irrecoverable conditions,  we should recycle the peer.  We know some conditions, such as the peer being compromised, we may not want to recycle, but kill it and wait for service. Obviously we need ability to notify someone about this situation.

To recycle, I found this [Graceful Restart in Golang](http://grisha.org/blog/2014/06/03/graceful-restart-in-golang) that could help.

**Comment by bmos299** [comment]
@movee2016 please see @kchristidis on this issue.

**Comment by tuand27613** [comment]
will wait until @jyellick gets his arms around #751.

**Comment by kchristidis** [comment]
@tuand27613: Can you provide a few details on the plan of attack for this one?

Based on a short conversation with @jyellick earlier today, his work will practically move these panics elsewhere but won't really deal with the problem described here. (Jason, let me know if I'm misunderstanding things.)

**Comment by tuand27613** [comment]
So, a loose categorizations of the panics in consensus code :
1.unable to read configuration values : if the configuration calls don't work, we have no choice but to stop. If a specific configuration value cannot be read or is wrong, we can use the default ( maybe the timeout values ) or stop ( e.g. mode is not a valid pbft mode )
2. An input argument is wrong : we do not process and return with error (e.g. invalid replica id )
3. A call to the stack fails: the way the code is now, we don't know anything about the returned error so we ignore, e.g. sign() doesn't work, the message is bad and will get rejected by the other replicas ). If the failure is truly irrecoverable, the stack should stop rather than returning an error. e.g. ledger can't commit

I don't think we should try to recycle the peer. If something is wrong with the system or the OS, recycling will just put us into a loop. 

And, I assume that we have some eventing mechanism that we can push alarms onto.

**Comment by tuand27613** [comment]
move to sprint2 as we want #751 to be merged 1st

**Comment by kchristidis** [comment]
@tuand27613: For the stack-related errors, can we get in touch with whomever is sending these errors our way so that they can be caught and handled at a lower level? This should happen on a project-wide basis, but let's start from somewhere. I started [here](https://github.com/openblockchain/obc-peer/commit/246d4311ef50f1e845fea15fb3b9914669b74995#commitcomment-16896253).

Basically, as things stand right now, I'm not sure what steps we're taking for category 3, [as described in your earlier post](https://github.com/openblockchain/obc-peer/issues/752#issuecomment-195093281).

**Comment by tuand27613** [comment]
agree. and thanks for getting the ball rolling with ledger @kchristidis. I'll open an issue against ledger so we don't lose it in the noise

We're just going to have to go through the category 3's and open issues against the stack.  And I'll talk to @binh about error handling protocols for all of obc-peer as we're definitely not consistent right now.

**Comment by tuand27613** [comment]
opened issue #904 for error processing in ledger

**Comment by tuand27613** [comment]
linking to #710 for error processing in chaincode component

**Comment by christo4ferris** [comment]
@tuand27613 @kchristidis @binhn is this still an issue? rather stale. please close if no longer relevant.

**Comment by tuand27613** [comment]
issue is still relevant imho.  It's good timing since we're all looking at coding up the new arch. I'll get folks to see how we should handle.

**Comment by christo4ferris** [comment]
https://jira.hyperledger.org/browse/FAB-216 opened, closing this one
