### ISSUE TITLE
view-change does not occur when primary validating peer crashes

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#754]
Test scenario:
1. start network of 4 validating peers vp0-3
2. Deploy and invoke 5 transactions on vp0 - all good
3. shut down vp0 which is the primary for consensus
4. invoke 5 transactions on vp2 - none are executed

**Comment by tuand27613** [comment]
The issue is that a view change is not triggered when one of the backup replicas receives a request.

From a chat with @corecode:
so if the primary fails,  we stop consensus ?

simon [11:29 AM] 
no, we need a way to trigger a view change

[11:30] 
but in a way that doesn't produce a large DoS surface

[11:30] 
by eating all memory

[11:31] 
maybe this:

[11:31] 
we retain one request

[11:31] 
and if that request does not appear within some time,

[11:32] 
we broadcast it (instead of unicasting it to the primary (which we should do))

[11:32] 
and we flag it special

[11:33] 
when a replica receives such a special request, it starts its view change timer

[11:33] 
and that will trigger a view change, if the primary fails

[11:33] 
the problem: what if multiple replicas are broadcasting at the same time?

[11:34] 
some replicas will wait for request a, others for request b

[11:34] 
if the primary is byzantine, maybe it will process only one request, but not the other

**Comment by vukolic** [comment]
This may be related to #394. If vp2 just attempts to send those 5 transactions to vp0 (which is dead) - these transactions will not be delivered (as vp0 is dead). Even if the later on view change elects a new leader these transactions will not be executed as they are not retransmitted.

**Comment by kchristidis** [comment]
@tuand27613 Do we have a course of action for this one?

**Comment by corecode** [comment]
Isn't this the same as #796?

**Comment by tuand27613** [comment]
I forgot to type this in last night !  

Agree Simon, #796 will handle this as well

**Comment by tuand27613** [comment]
dup of #796

**Comment by tuand27613** [comment]
close as dup
