### ISSUE TITLE
Starting 8 validating peers with security enabled fails

### ISSUE THREAD

**Issue by tuand27613** [hyperledger-archives/fabric#755]
@samding01,

https://github.com/openblockchain/obc-peer/issues/747#issuecomment-190387682

creating new issue so we can track.

**Comment by tuand27613** [comment]
looks like the `enrollsecret` values for vp4-7 are not correct. I cut&pasted from obcca.yaml to docker-compose.yml and all the peers come up now.

**Comment by samding01** [comment]
@tuand27613 : Thank Tuan.   I took the wrong pw. (from user_test[4-7] )
Now all peers start

**Comment by tuand27613** [comment]
Good news !  A small reminder to open issues against a component if behavior and/or error message is confusing  and against the obc-docs documents if they are not clear.
