### ISSUE TITLE
Consensus should run with whitelisted VPs when security is enabled

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#756]
This is a follow-up to #462.

We currently require that VPs are named as `vp0`, `vp1`, ...`vpX` where `X+1` is the maximum number of validating nodes that we have set in the config file.  [As noted in #462](https://github.com/openblockchain/obc-peer/issues/462#issuecomment-173421403), this approach is flaky and needs to go.

The proper way to do this is: create a whitelist of hashed raw enrollment certificates that will be allowed to connect to the network. We dropped this because it was causing issues when automatically deploying a network through Swarm.

@adecaro: Can we modify the CA so that it pre-generates a list of N enrollment certificates. We could then use them to populate the network's whitelist. Later on, as each VP signs up, we'll have the CA return one of these pre-generated certificates. Are there any security implications we need to be aware of in this approach?

Another way to do this is: Wait for the first N validating nodes to connect to the network, and don't kick off consensus until this happens. These are your validators, this is your whitelist. (Chet is thinking along these lines as well IIRC.)

**Comment by kchristidis** [comment]
@adecaro Can you have a look at the question above and give me your take? Let's see if we can maybe tackle this during Sprint 1.

**Comment by binhn** [comment]
I would prefer to wait for N rather listing pre-generated certs, which would be harder to handle in configuration

**Comment by kchristidis** [comment]
Got it. (@adecaro we're good then, I can work on this without being blocked.)

**Comment by bmos299** [comment]
@RicHernandez2 can you talk to @kchristidis about this Issue.

**Comment by kchristidis** [comment]
Consider the scenario where a VP disconnects and reconnects, i.e. it has a whitelist installed already.

This VP will:
1. Attempt to connect to the peers in the whitelist, and reject any connections from validators not in that list.
2. It'll wait until 2f such connections are formed before it starts consensus.

Sounds right? @corecode @jyellick @tuand27613

**Comment by tuand27613** [comment]
Should that vp wait until 2f connections ?

**Comment by kchristidis** [comment]
@tuand27613 That's right. 2f, so that you can have 2f+1 PREPARE messages, etc.

**Comment by kchristidis** [comment]
There is an issue where `GetWhitelist()` doesn't produce the proper unmarshaled protobuf. See code [here](https://gist.github.com/kchristidis/232b6954b0d0857c4401); 87 bytes are read, but the unmarshaled protobuf comes up blank.

**Comment by tuand27613** [comment]
@kostas, should we move to sprint2 ? or are you close ?

**Comment by kchristidis** [comment]
Work ongoing on this, no estimated completion date.

The original problem has been expanded to deal with closely-related issues that we're better off tackling now, instead of revisiting later. Whitelist is formed dynamically during initialization, persists crash faults, and it now forms the basis for the assignment of PBFT IDs. I'm also making it work with security off through the same common path. (Even though its use in this case is debatable since PeerIDs can be forged, it's good to be consistent in how we deal with this.)

**Comment by kchristidis** [comment]
The `Inquirer` interface is changing quite a bit during my work on this. Been spending the weekend adjusting my work to Jason's refactoring in #833, and fixing the merge conflicts that came up.

@jyellick: I'm getting `Failing with (Timeout, Corrupt)` messages starting from the `TestCatchupSyncBlocksErrors` test and onward. The only test that actually fails is `TestCatchupLaggingChainsErrors` with the following message:

> statetransfer_test.go:474: TestCatchupLaggingChainsErrors Corrupt short chain with timeout failure: Timed out waiting for blocks to replicate for blockchain

I suspect this might have something to do with my `GetConnectedValidators()` call in `tryOverPeers()` ([link](https://github.com/kchristidis/obc-peer/blob/issues/756/openchain/consensus/statetransfer/statetransfer.go#L410)). The mock `GetConnectedValidators()` method is defined [here](https://github.com/kchristidis/obc-peer/blob/issues/756/openchain/consensus/obcpbft/statetransfer_mock_test.go#L98). Let me know what you think.

**Comment by jyellick** [comment]
@kchristidis The messages `Failing with (Timeout, Corrupt)` are  benign.  Perhaps they are not terribly clear, but they are intended to say that the test is deliberately causing a particular call to fail, either by refusing to return data (Timeout) or returning deliberately invalid data (Corrupt).

The `TestCatchupLaggingChainsErrors` failure looks to be a bug in `GetConnectedValidators()`.

 https://github.com/kchristidis/obc-peer/blob/issues/756/openchain/consensus/obcpbft/statetransfer_mock_test.go#L101

Here, `k` is initialized once with scope for the whole loop, so `&k` returns the same value every iteration through the loop while the contents of that memory address is overwritten each time. This bites me more often than I'd like to admit.

**Comment by kchristidis** [comment]
@jyellick Perfect, that was it indeed. Thanks. Tests pass now.

**Comment by kchristidis** [comment]
You can follow the progress of this in: https://github.com/kchristidis/obc-peer/commits/issues/756

Switched to a `whitelist` proto message to avoid dealing with `gob` registration issues. Whitelist is persisted and loaded properly, working on the filtering part.

**Comment by kchristidis** [comment]
Update: Filtering bug has been fixed (thanks @jeffgarratt) but we need to drop the dependence from the `PeerID` when identifying a peer. Instead it should be the `Endpoint` -- and from that, we go with `Endpoint.ID.Name` when security is off, and `Endpoint.pkiID` when security is on. These are the two keys I'm using for the whitelisted mapping. Working on this change.

**Comment by kchristidis** [comment]
Code is up, passes all tests, but I'd like to have a couple of `behave` tests written for it and some rigorous testing in general before it's merged.

Here's the main logic:
- Launch and wait until you're connected to the first `N-1` peers
- When that happens, records the PeerIDs in a whitelist and persist that list on disk
- Reject any connections from peers not on the whitelist
- If you reboot, connections will be allowed only with peers in the whitelist

A few other things I fixed while at it:
- Dropped dependency for `vpX` naming scheme
- Inquirer interface has been revamped and I've dropped all the errors from the signature, in line with the changes we're trying to introduce in #752
- Peer stopping reconnections if another whitelisted peer goes down (thanks @jeffgarratt)

TODO:
- Augment `peer` logic so that the stream closes gracefully (@jeffgarratt)
- Modify existing logic so that `PeerID.Name` is set to the base-64 encoded version of the hashed raw enrollment certificate (`pkiID`) if security is on (@jeffgarratt)

Please note that:
- Whitelisting is not meant for non-secure environments. In that case, whitelisting records the IDs of each of the first N peers that connect to the network. If a peer disconnects, a different peer that will guess that peer's ID _will_ get through. This is expected.
-  When we get the `PeerID.Name` logic modification (see TODO above), whitelisting in a secure environment will work as expected. It will allow a peer in only if its raw enrollment certificate belongs in the list.

**Comment by tuand27613** [comment]
@RicHernandez2 let's start thinking about testcases. Would also like to some tests to the `behave` bucket for fvt when we build the system

**Comment by chetmurthy** [comment]
> Whitelisting is not meant for non-secure environments. In that case, whitelisting records the IDs of each of the first N peers that connect to the network. If a peer disconnects, a different peer that will guess that peer's ID will get through. This is expected.

This is a problem.  just b/c an environment isn't "secure", doesn't mean we basically ditch all the guarantees of PBFT.  Otherwise, you're really saying "the insecure version isn't BFT, period".

In which case, you should cease testing with the insecure mode.

**Comment by kchristidis** [comment]
@chetmurthy: [The PBFT paper](http://research.microsoft.com/en-us/um/people/mcastro/publications/p398-castro-bft-tocs.pdf) describes an operating environment that makes heavy use of cryptographic keys. The non-secure environment (whereby non-secure I mean running the blockchain network with the `security enabled` [flag](https://github.com/hyperledger/fabric/blob/master/core.yaml#L370) set to `false`) means we are not using any keys. Therefore, yes, the insecure version isn't PBFT, and I see zero use in testing in it.

**Comment by chetmurthy** [comment]
Even in an environment where security is not enforced on all
operations, it should be enforced on the identification of peers.
You're using TCP, for pete's sake: we're talking about
one-time-per-connection cost.  And should require NO comms with any
CA.

**Comment by chetmurthy** [comment]
Might be time to read Ohad Rodeh's thesis about all this .....

**Comment by corecode** [comment]
With `security=false` there are no keys to check against.  This setting is exclusively for development mode, and no deployment should ever use it.  With `security=false`, the network is no longer permissioned.

**Comment by tuand27613** [comment]
I've edited the `behave` docker-compose files to use names v0p, v1p, v2p, v3p and the `behave` tests are running as expected.

There is one specific that's difficult to do in `behave` and I've asked @RicHernandez2  @ramesh and Nishi to take a look.

**Comment by tuand27613** [comment]
Currently running into other issues in obc-executor that should be fixed by @jyellick latest PR  but  it's taking a while to merge @kostas' branch with fabric/master.

I will update once I get through all the merge conflicts

**Comment by kchristidis** [comment]
@tuand27613: thank you for the update on this.

**Comment by binhn** [comment]
I am moving this to sprint 4 to continue

**Comment by corecode** [comment]
Feedback in general:
- Whitelist should be maintained by consensus plugin, not by stack
- Whitelist should be configured using certificates, not by first come first trust

As this is a stopgap fix, we anticipate these issues to be resolved during refactoring and when the stack can expose the right information.

Feedback for the current patch:
- do not store whitelist in file, use persistence instead
- do not use loop + timer to wait for whitelist set to be complete; instead, use peer connection (handshake) events to trigger processing
- have engine not service peer messages until whitelist is complete

@jyellick did I forget anything?

**Comment by jyellick** [comment]
@corecode That includes all of my concerns, thanks for writing that up.
