### ISSUE TITLE
Crash When Running with Crypto Debug

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#762]
In obc-peer I am running with cyrpto debug enabled.  When I do depoy of sample chaincode 2, I crash around 75% of the time.  I have a file I an send you if needed.  
I worked with @muralisrini and had me change the following value:

---

  crypto:    debug  
 tcert:
      batch:
        # The size of the batch of TCerts (changed to 1 for recreate)
        size:  1

---

I am assigning to @adecaro .  If you aren't the correct person, please let me know.
Thanks, Barry

Snippet of the obc-peer log just before the OOM.  
6:39:44.539 [crypto] encryptTx -> DEBU 0c7^[[0m [client.barry] Encrypted Metadata [].
^[[36m16:39:44.540 [crypto] newChaincodeDeployUsingTCert -> DEBU 0c8^[[0m [client.barry] Appending certificate [30 82 01 c2 30 82 01 68 a0 03 02 01 02 02 01 01 30 0a 06 08 2a 86 48 ce 3d 04 03 03 30 29 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0c 30 0a 06 03 55 04 03 13 03 74 63 61 30 1e 17 0d 31 36 30 33 30 31 31 36 33 38 34 30 5a 17 0d 31 36 30 35 33 30 31 36 33 38 34 30 5a 30 2b 31 0b 30 09 06 03 55 04 06 13 02 55 53 31 0c 30 0a 06 03 55 04 0a 13 03 49 42 4d 31 0e 30 0c 06 03 55 04 03 13 05 62 61 72 72 79 30 59 30 13 06 07 2a 86 48 ce 3d 02 01 06 08 2a 86 48 ce 3d 03 01 07 03 42 00 04 54 59 f3 2e 7f 6d 26 e6 c6 d6 4c c2 7f 0e 12 1e ba 06 6a 85 ba 92 9d 4b 6a bb e2 a4 a8 7d 8f ff f0 4e a3 dd fa 0c 6d 9a a0 6c e8 33 ad eb fb f7 a7 a4 71 5d f2 71 69 05 34 1c 7c a5 fc c4 2f d9 a3 7f 30 7d 30 0e 06 03 55 1d 0f 01 01 ff 04 04 03 02 07 80 30 0c 06 03 55 1d 13 01 01 ff 04 02 30 00 30 0d 06 03 55 1d 0e 04 06 04 04 01 02 03 04 30 0f 06 03 55 1d 23 04 08 30 06 80 04 01 02 03 04 30 3d 06 06 2a 03 04 05 06 07 01 01 ff 04 30 2a d0 62 45 88 80 48 3b 55 5c 96 6b 37 87 c3 c2 ed 2c e3 31 1b 2c 35 8c 19 c3 e3 f5 6e 8b 22 a0 fc 9b 27 b0 06 6a 85 4f 38 f5 24 96 0a 7d af ae 30 0a 06 08 2a 86 48 ce 3d 04 03 03 03 48 00 30 45 02 21 00 8a 5e c0 08 33 81 ec 84 2e e8 d6 c5 b4 f6 36 5e 30 df 6e 5f 17 dc 51 14 4e 10 97 42 03 52 f9 fb 02 20 60 eb e1 98 e2 d1 72 f1 26 82 1c 47 fb b4 a5 b1 2a 58 a1 97 92 f5 93 62 1b 99 e1 bb 73 41 c6 bb].
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xdec880, 0x16)
        /opt/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc8d4ff0000, 0x27590000, 0x508f00, 0x13cf6d8)
        /opt/go/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x13af540, 0x27590000, 0x0)
        /opt/go/src/runtime/malloc.go:423 +0x160

**Comment by adecaro** [comment]
@bmos299, please, if you have the complete log file, send it to me. Thanks.

**Comment by bmos299** [comment]
@adecaro please go to $ sftp root@169.55.4.106 and 'get loop.txt' loop.txt.

I will send you an e-mail message as well.

**Comment by adecaro** [comment]
@bmos299 Thanks, I'm downloading the logs. I will have a look at them asap.

**Comment by adecaro** [comment]
@bmos299, please, may you give me some instructions on hot to replicate the error? Thanks.

**Comment by bmos299** [comment]
@adecaro I am here with @dongmingh and we did not reproduce.   I am confident the crash was a dup of https://github.com/openblockchain/obc-peer/issues/764.  Closing.
