### ISSUE TITLE
Confusion about or new specification of module-level logging setup [re: crypto]?

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#769]
Recently a `logging.crypto` key was added to openchain.yaml, which is interpreted in the file

```
obc-peer/openchain/crypto/crypto_settings.go
```

"crypto" here is what the logging package refers to as logging _module_. The other `logging.*` keys in openchain.yaml refer to _subcommands_ of the `obc-peer` command. Module-level logging control in obc-peer subcommands is already implemented and documented - it is not necessary to add new configuration keys to control module-level logging.

Currently a module-level override specification is potentially required for each peer subcommand. However if the desire is to add a way to specify module-level overrides that apply to all obc-peer subcommands that would also be easy to do in a way that would not require defining a unique configuration key for each logging module.

**Comment by kchristidis** [comment]
I'm not sure I follow @bcbrock's phrasing here as closely as I'd like to (sorry Bishop...), and apologies in advance if I'm derailing this thread, but the issue that I'm seeing is this:

If you launch the `membersrvc` binary, the config file that `viper` reads is the `membersrvc/membersrvc.yaml` one. Then when we call into the `crypto` package, then `Init()` function attempts to read the key `logging.crypto` which is **NOT** present in `membersrvc.yaml`. (It is however present in `core.yaml`, but that config file is not loaded when running the `membersrvc` binary.)

As a result, we get a "Log level not recognized" error.

Would it be easy to have the `membersrvc` binary run on the same logic as the `peer` one when it comes to control its logging modules? (I _believe_ that this is what Bishop is referring to.)

If not, can we at least add a `logging.crypto` key to `membersrvc.yaml` to make the error message go away?

Copying @adecaro who may be able to help on this.

**Comment by kchristidis** [comment]
I think I see the other issue that Bishop noted.

When running the `peer` binary, the `crypto` package does not respect the value set via the `logging-level` flag, and instead logs at the level set by the `logging.crypto` key.

This behavior is inconsistent with the other modules. Any way we could fix this?

**Comment by bcbrock** [comment]
@kchristidis Yes, your second point was my point. The YAML entries were supposed to provide default logging levels for 'peer' subcommands, and the syntax of the entry then allowed individual module level control. After this mechanism was introduced the "crypto" system was subsequently modified to take its logging level directly from the YAML file.

**Comment by juliancarrivick-ibm** [comment]
@kchristidis @bcbrock I can fix this (i.e. Make the crypto package follow the defined logging level).

**Comment by bcbrock** [comment]
@juliancarrivick-ibm Hi Julian, it would be great if you could fix this. Even better, if you have the time, would be to fix #653.

**Comment by juliancarrivick-ibm** [comment]
I'm currently having some environment issues which I'll hopefully resolve today, but yes I can look at #653 too.

As per @GrapeBaBa suggestion, I will probably just remove the explicit retrieval of the logging level in `crypto_settings.go` and `core.yaml`. If we want an override for module level logging then we can always add it later but this will make it consistent for now.

**Comment by kchristidis** [comment]
@juliancarrivick-ibm Thanks for looking into it!

**Comment by juliancarrivick-ibm** [comment]
There also seems to be some Docker logging which is not respecting the logging level set:
`2016/07/12 03:57:08 Load docker HostConfig: &{Binds:[] CapAdd:[] CapDrop:[] ContainerIDFile: LxcConf:[] Privileged:false PortBindings:map[] Links:[] PublishAllPorts:false DNS:[] DNSSearch:[] ExtraHosts:[] VolumesFrom:[] NetworkMode:host IpcMode: PidMode: UTSMode: RestartPolicy:{Name: MaximumRetryCount:0} Devices:[] LogConfig:{Type: Config:map[]} ReadonlyRootfs:false SecurityOpt:[] CgroupParent: Memory:0 MemorySwap:0 MemorySwappiness:0 OOMKillDisable:false CPUShares:0 CPUSet: CPUSetCPUs: CPUSetMEMs: CPUQuota:0 CPUPeriod:0 BlkioWeight:0 Ulimits:[]}`
 I am going to look into that too.

**Comment by GrapeBaBa** [comment]
@juliancarrivick-ibm that can be fixed if #2140 merged.

**Comment by juliancarrivick-ibm** [comment]
Ah, great! I was just about to say that it would probably be best fixed in another pull request so that saves me the trouble!
