### ISSUE TITLE
archive/tar: write too long BuildImage_Peer and BuildImage_Obcca

### ISSUE THREAD

**Issue by andreaMWork** [hyperledger-archives/fabric#771]
Hi I a facing an error archive/tar: writing too long when I run :
`go test github.com/openblockchain/obc-peer/openchain/container -run=BuildImage_Peer
go test github.com/openblockchain/obc-peer/openchain/container -run=BuildImage_Obcca`

So I am basically not eblo to create the cotainer and running the test,

thanks
Andrea

Log:
`vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ go test github.com/openblockchain/obc-peer/openchain/container -run=BuildImage_Peer
2016/03/03 16:07:18 Log level not recognized '', defaulting to ERROR: logger: invalid log level
2016/03/03 16:07:18 setting Number of procs to 2, was 2
2016/03/03 16:07:18 Creating VM with endpoint: unix:///var/run/docker.sock
2016/03/03 16:07:18 rootDirectory = /opt/gopath//src
2016/03/03 16:07:19 Error walking rootDirectory: Error copy (path: /opt/gopath/src/github.com/cockroachdb/c-lz4/lz4.c, oldname:lz4.c,newname:srcgithub.com/cockroachdb/c-lz4/lz4.c,sz:0) : archive/tar: write too long
--- FAIL: TestVM_BuildImage_Peer (0.04s)
    vm_test.go:75: Error building Peer container: Error getting package bytes: Error writing Peer package contents: Error copy (path: /opt/gopath/src/github.com/cockroachdb/c-lz4/lz4.c, oldname:lz4.c,newname:srcgithub.com/cockroachdb/c-lz4/lz4.c,sz:0) : archive/tar: write too long
FAIL
FAIL    github.com/openblockchain/obc-peer/openchain/container  0.062`

**Comment by muralisrini** [comment]
@andreaMWork can u try the fix in branch https://github.com/muralisrini/obc-peer/tree/invalid_gopath/issue%23771 please

**Comment by bcbrock** [comment]
I just had the same problem and traced it down to the fact (I'm 99% sure) that I had an open file (a log file) in the chaincode directory. It makes sense that `tar` might have problem in this case, although the error message could be better.

**Comment by muralisrini** [comment]
@bcbrock : yes, that'd also do it ... but the log from @andreaMWork did not appear to point to a changing file.

**Comment by christo4ferris** [comment]
@andreaMWork @bcbrock @muralisrini this is rather stale, is it still an issue or can it be closed?

**Comment by bcbrock** [comment]
I'm OK with closing

**Comment by christo4ferris** [comment]
ok, closing for now... can be reopened if anyone feels like it should remain open
