### ISSUE TITLE
obc-peer should auto-discover the OPENCHAIN_VM_ENDPOINT

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#772]
It should not be necessary to specify the OPENCHAIN_VM_ENDPOINT in most test and development systems - the peer should be able to discover/compute this itself unless explicitly overridden. The fact that this setting is currently required complicates development, e.g, the Travis CI procedure described today requires that several files be changed _for testing only_ to modify the OPENCHAIN_VM_ENDPOINT.

Unfortunately I have not been able to find a Docker command that explicitly returns this information, however there are workarounds.

First, note that the official (unsecured) TCP port for Docker is 2375: 

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=docker

All of the development environment setup should be changed to use this port. According to the Docker documentation this TCP port is the default so it is not actually necessary to specify it (the port, that is).

Next, on Linux systems at least you can find the IP address of the Docker bridge using `ifconfig` or `ip addr`.

So I would propose that if OPENCHAIN_VM_ENDPOINT is not specified, the code assumes that it should use the IP address of the `docker0` interface and port 2375.

@rameshthoomu - Since this would simplify the use of Travis CI, would you be able to provide this fix?

**Comment by rameshthoomu** [comment]
Fixed this issue: Now, i am updating `Docker01 interface ip address` and `port number` dynamically in `compose-defaults.yml` file in bddtests folder.

`sed -i -e 's/172.17.0.1:4243\b/'"$ip:$port"'/g' $HOME/gopath/src/github.com/openblockchain/obc-peer/openchain/peer/bddtests/compose-defaults.yml`

**Comment by bcbrock** [comment]
Thanks Ramesh - Looking forward to trying CI once these changes are all committed.

**Comment by rameshthoomu** [comment]
@bcbrock I have made changes in .travis.yml file and now it is available in obc-peer repo.

**Comment by bcbrock** [comment]
@rameshthoomu - What happened? The compose-defaults.yaml still hard-codes the Docker VM endpoint.

**Comment by rameshthoomu** [comment]
@bcbrock. changing IP and Port number dynamically in compose-defaults.yml file in Travis. Which file you are referring?

**Comment by bcbrock** [comment]
@rameshthoomu I'm talking about the main  @compose-defaults.yml in the bddtests directory. Do you plan to modify that one as well?

**Comment by rameshthoomu** [comment]
Changes already made in travis.yml file to dynamically change IP and Port in compose-defaults.yml on fly. So, every time when i execute behave tests from Travis, above code snippet change the values dynamically. This is already in place.

**Comment by bcbrock** [comment]
I was hoping you would modify the whole infrastructure so that it would apply to all users under all conditions.

**Comment by rameshthoomu** [comment]
This has been implemented and merged in fabric repo. Closing this issue.

**Comment by bcbrock** [comment]
@rameshthoomu This issue is about the fabric in general, and is not restricted to the CI environment. I won't consider this issue closed until either:

1) All occurrences of 

```
CORE_VM_ENDPOINT=172.17.0.1:2375
```

are removed from the codebase; or 

2) Someone convinces me that I am wrong to want 1).

For an existence proof of why 1) is feasible, see the procedure `busywork::dockerEndpoint` in fabric/tools/busywork/tcl/busywork.tcl.

**Comment by bcbrock** [comment]
It turns out that I am the one that that convinced myself that I am wrong to want 1) above.

The problem is not the explicit specification of `CORE_VM_ENDPOINT` in a Docker-compose script, it is that these scripts should be generated automatically, and the script-writing script needs to auto-discover the `CORE_VM_ENDPOINT`.
