### ISSUE TITLE
Load test on range query functionality

### ISSUE THREAD

**Issue by jeffgarratt** [hyperledger-archives/fabric#780]

**Comment by bmos299** [comment]
@jeffgarratt and @srderson I slacked you both some performance information.  Ping me and we can chat.

**Comment by bmos299** [comment]
@dongmingh we discussed the results and I sent you the bare bones chaincode.  Please let us know your thoughts.  Thanks, Barry

**Comment by dongmingh** [comment]
@bmos299 thanks for the POSTMAN

test scenarios: 
security and privacy disabled, peer set to error, threads=200, run for 5 min using SoapUI

code commit level:
3ef73d319b01fe84c0c88973350a240fc490d82e

if 50 keys, tps = 253
the output of keys is
{"OK": "[\"a34\",\"a38\",\"a15\",\"a1\",\"a11\",\"a5\",\"a22\",\"a9\",\"a19\",\"a26\",\"a46\",\"a42\",\"a31\",\"a35\",\"a39\",\"a16\",\"a12\",\"a4\",\"a21\",\"a8\",\"a25\",\"a29\",\"a45\",\"a41\",\"a49\",\"a50\",\"a32\",\"a36\",\"a17\",\"a3\",\"a13\",\"a7\",\"a20\",\"a24\",\"a28\",\"a44\",\"a40\",\"a48\",\"a33\",\"a37\",\"a14\",\"a2\",\"a10\",\"a6\",\"a23\",\"a18\",\"a27\",\"a47\",\"a43\",\"a30\"]"}

if 1 key, tps = 254
