### ISSUE TITLE
Remove transactions from blocks

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#785]
In the DB we need to pull transactions from blocks. The primary reason behind this is performance. Having to read the entire block to fetch a single transaction can be very heavy. As we support a utxo model, reading single transactions from the DB will be more important.

**Comment by chetmurthy** [comment]
Why?  For UTXO, you have the UTXO as a table -- why would you ever need to look at the blockchain trans?

**Comment by bmos299** [comment]
@2016Nishi please see @srderson for this issue.

**Comment by srderson** [comment]
Decided not to implement this for S1. The plan is that blocks/transactions will eventually be sent to a data warehouse (via the EventHub mechanism) at which point they will be queryable
