### ISSUE TITLE
There should be a way of replaying the transactions already in the chain against a chaincode

### ISSUE THREAD

**Issue by zmanian** [hyperledger-archives/fabric#787]
Kill the chain code and restart.

Would be it desirable obc-peer should replay all the transactions for that chaincode to the chaincode on restart to resync state?

There ought to be a way to do this.

**Comment by christo4ferris** [comment]
@zmanian is this still an issue or can it be closed. Thanks

**Comment by zmanian** [comment]
This should be closed. I didn't understand how the state db worked at this time.
