### ISSUE TITLE
inconsistent naming of chaincode transaction types across layers

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#788]
In Transaction proto
        deploy is CHAINCODE_NEW 
        invoke is CHAINCODE_EXECUTE
        query is CHAINCODE_QUERY

In OpenchainMessage proto
        deploy and invoke are CHAIN_TRANSACTION
        query is CHAIN_QUERY

In Chaincode interface
       deploy and invoke call Run 
        // Query is to be used for read-only access to chaincode state
       query calls Query

We need to provide meaningful and consistent names to transaction types.

**Comment by binhn** [comment]
I would propose the following changes to Transaction:

```
Transaction
    enum Type {
        UNDEFINED = 0;

// deploy a chaincode to the network and call `init` function
        CHAINCODE_DEPLOY = 1;  

// call a chaincode `invoke` function as a transaction
        CHAINCODE_INVOKE = 2;  

// call a chaincode `query` function
        CHAINCODE_QUERY = 4;  

// terminate a chaincode; chaincode no longer accepts tx
        CHAINCODE_TERMINATE = 6;  
    }
```

**Comment by binhn** [comment]
The `OpenchainMessage` should abstract the message (eg Transaction) such that handler may look at the payload to further discriminate.

```
message OpenchainMessage {
    enum Type {
        ...
        CHAIN_TRANSACTION = 6;
        ...
```

This means we need to change consensus framework event handler.

The chaincode interface should define functions according to the transaction types, including:
- Init (called as part of deploy)
- Invoke
- Query

**Comment by muralisrini** [comment]
The original PR is closed but not the issue. Reopening the issue. Related new PR is #1012

**Comment by binhn** [comment]
pr #1012 has been merged, so close this issue
