### ISSUE TITLE
Travis CI only: raise Exception("Max time exceeded waiting for transactions with current response map = {0}"

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#793]
**Failing scenarios:**

peer_basic.feature:391  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
peer_basic.feature:477  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
20 scenarios passed, 2 failed, 1 skipped
470 steps passed, 2 failed, 36 skipped, 0 undefined
Took 10m5.521s
The command "behave" exited with 1.

Above mentioned two behave test scenarios are failing in outside of vagrant environment (Using Travis) and observed @1.1 Consensus Options test scenario failed in inside the vagrant environment. 

Attached are the log files:

[peer_basic feature 477.txt](https://github.com/openblockchain/obc-peer/files/159442/peer_basic.feature.477.txt)
[peer_basic features 391.txt](https://github.com/openblockchain/obc-peer/files/159443/peer_basic.features.391.txt)

Full log file from Travis:
[Behave script_Failed.txt](https://github.com/openblockchain/obc-peer/files/159445/Behave.script_Failed.txt)

Full log file from Inside vagrant env:
[inside_vagrant_log_file.txt](https://github.com/openblockchain/obc-peer/files/159453/inside_vagrant_log_file.txt)

**Comment by rameshthoomu** [comment]
Updated bug description

**Comment by tuand27613** [comment]
reading through the log files, I'm seeing things such as
in 477.txt
- line 269 `ERRO[1108] HTTP Error                                    err=no such id: dev-vp0-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c statusCode=404`
- line 509 `Exception: Max time exceeded waiting for transactions with current response map = {'bddtests_vp0_1': 200, 'bddtests_vp1_1': 200, 'bddtests_vp2_1': 200, 'bddtests_vp3_1': 404}`

in 391.txt
- line 77 `ERRO[0938] HTTP Error                                    err=Cannot start container 28e818c0ffef658c32b8f1ee4b974f52650c73a7c2356fd4dc070375735a3813: Error starting userland proxy: listen tcp 0.0.0.0:5000: bind: address already in use statusCode=500`

so it looks like the issue has to do with Travis and Docker rather than with consensus code.

**Comment by binhn** [comment]
@tuand27613 do you know where "no such id" come from?  I searched the code and got no hits. Does that mean somehow it failed to launch a peer at dev-vp0?

This problem doesn't occur when running behave on local machine.

**Comment by tuand27613** [comment]
I think that message is coming from some interaction between travis/docker and that it's unrelated to what's going on in the behave test.

I've talked with @rameshthoomu about figuring out a way to not have those in the log

**Comment by rameshthoomu** [comment]
I am working on the options to restrict INFO and ERRO log messages in Travis Log file. I observed below mentioned scenarios always fails with below error log. I could see any one scenario fails for each build from State Transfer functionality.

```
in 477.txt
line 269 ERRO[1108] HTTP Error err=no such id: dev-vp0-bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c statusCode=404
    line 509 Exception: Max time exceeded waiting for transactions with current response map = {'bddtests_vp0_1': 200, 'bddtests_vp1_1': 200, 'bddtests_vp2_1': 200, 'bddtests_vp3_1': 404}
```

Scenarios failing are:
Scenario Outline: 
chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) --@1.1 Consensus Options
peer_basic.feature:477 chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options"
peer_basic.feature:489  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.2 Consensus Options

**Comment by tuand27613** [comment]
The state transfer error will be fixed by #751 which is in sprint1.  

We really should comment out that test until the fix is merged in.  I'll try to get to that today. Or you can edit the .feature file yourself ;)

**Comment by rameshbabu79** [comment]
@tuand27613 made changes in _.behaverc_ file `tags=-wip` and now skipping `Scenario Outline: chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer)` from behave test execution. Below are the Pull Request details. Thanks

Commit#  3ef73d3
Pull Request#  Skipping WIP tags #822

**Comment by rameshthoomu** [comment]
After #751 merge, still i am seeing inconsistent issue in State Transfer functionality when I execute behave test cases using Travis CI.  

Attached failed scenario log file and below is the scenario failing inconsistently.

`Scenario Outline: chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options                    # peer_basic.feature:490 
Given we compose "docker-compose-4-consensus-sieve.yml"`

Above mentioned scenario is working as expected inside the vagrant environment but not on Travis.
[751_StateTransfer_680_Scenario_Failed.txt](https://github.com/openblockchain/obc-peer/files/193521/751_StateTransfer_680_Scenario_Failed.txt)

**Comment by tuand27613** [comment]
I added the state transfer label since that's the behave test that's failing.  

Reading through logs now.

**Comment by tuand27613** [comment]
@rameshthoomu , can we get the VP container logs from Travis ? Running `behave -D logs-yes` will write the logs out to file when a test fails.  Not sure how to pull those files from Travis though.

From the behave output, this error is very similar to a deadlock bug @jyellick  found when we were unit testing PR #833 but we can't really tell until we can read the container logs.

**Comment by tuand27613** [comment]
@rameshthoomu   any luck ?

**Comment by rameshthoomu** [comment]
@tuand27613 -- Oserved same failure in TRAVIS environment on latest commit. Below are the attached container logs files from Travis for all 4 peers and behave log file for reference.

commit# 8580de6
Author: Sheehan Anderson sranderson@gmail.com
Date:   Tue Apr 12 11:44:16 2016 -0400
 Merge pull request #1072 from tuand27613/memberservicedoc

**Container LOG Files:**
[bddtests_vp0_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_@1.1_Consensus_Options.txt](https://github.com/hyperledger/fabric/files/215862/bddtests_vp0_1_chaincode_example02_with_4_peers_and_1_membersrvc._issue_.680_.State_transfer._--_.1.1_Consensus_Options.txt)
[bddtests_vp1_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_@1.1_Consensus_Options.txt](https://github.com/hyperledger/fabric/files/215864/bddtests_vp1_1_chaincode_example02_with_4_peers_and_1_membersrvc._issue_.680_.State_transfer._--_.1.1_Consensus_Options.txt)
[bddtests_vp2_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_@1.1_Consensus_Options.txt](https://github.com/hyperledger/fabric/files/215865/bddtests_vp2_1_chaincode_example02_with_4_peers_and_1_membersrvc._issue_.680_.State_transfer._--_.1.1_Consensus_Options.txt)
[bddtests_vp3_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)_--_@1.1_Consensus_Options.txt](https://github.com/hyperledger/fabric/files/215866/bddtests_vp3_1_chaincode_example02_with_4_peers_and_1_membersrvc._issue_.680_.State_transfer._--_.1.1_Consensus_Options.txt)
**Travis Log File:**
[Behave Logs.txt](https://github.com/hyperledger/fabric/files/215867/Behave.Logs.txt)

**Comment by jyellick** [comment]
@rameshthoomu These logs seem like they are truncated.

For vp0 I see:

```
bddtests_vp0:19:24:26.036 [consensus/obcpbft] prepared -> DEBU bfd Replica 0 prepare count for view=0/seqNo=10: 0
bddtests_vp0:19:24:26.037 [consensus/obcpbft] recvPrepare -> DEBU bff Replica 0 received prepare from replica 1 for view=0/seqNo=10
bddtests_vp0:19:24:26.037 [consensus/obcpbft] prepared -> DEBU c00 Replica 0 prepare count for view=0/seqNo=10: 1
bddtests_vp0:19:24:26.038 [consensus/obcpbft] prepared -> DEBU c02 Replica 0 prepare count for view=0/seqNo=10: 1
bddtests_vp0:19:24:26.038 [consensus/obcpbft] recvPrepare -> DEBU c04 Replica 0 received prepare from replica 3 for view=0/seqNo=10
bddtests_vp0:19:24:26.038 [consensus/obcpbft] prepared -> DEBU c05 Replica 0 prepare count for view=0/seqNo=10: 2
bddtests_vp0:19:24:26.062 [consensus/obcpbft] prepared -> DEBU c0c Replica 0 prepare count for view=0/seqNo=10: 2
bddtests_vp0:19:24:26.062 [consensus/obcpbft] prepared -> DEBU c0f Replica 0 prepare count for view=0/seqNo=10: 2
bddtests_vp0:19:24:26.063 [consensus/obcpbft] recvPrepare -> DEBU c20 Replica 0 received prepare from replica 2 for view=0/seqNo=10
bddtests_vp0:19:24:26.064 [consensus/obcpbft] prepared -> DEBU c21 Replica 0 prepare count for view=0/seqNo=10: 3
```

and for vp2 I see:

```
bddtests_vp2:19:24:26.034 [consensus/obcpbft] recvPrepare -> DEBU b16 Replica 2 received prepare from replica 1 for view=0/seqNo=10
bddtests_vp2:19:24:26.035 [consensus/obcpbft] recvPrePrepare -> DEBU b19 Backup 2 broadcasting prepare for view=0/seqNo=10
bddtests_vp2:19:24:26.035 [consensus/obcpbft] recvPrepare -> DEBU b1d Replica 2 received prepare from replica 2 for view=0/seqNo=10
bddtests_vp2:19:24:26.035 [consensus/obcpbft] prepared -> DEBU b1e Replica 2 prepare count for view=0/seqNo=10: 2
bddtests_vp2:19:24:26.036 [consensus/obcpbft] prepared -> DEBU b24 Replica 2 prepare count for view=0/seqNo=10: 2
bddtests_vp2:19:24:26.036 [consensus/obcpbft] recvPrepare -> DEBU b26 Replica 2 received prepare from replica 3 for view=0/seqNo=10
bddtests_vp2:19:24:26.036 [consensus/obcpbft] prepared -> DEBU b27 Replica 2 prepare count for view=0/seqNo=10: 3
bddtests_vp2:19:24:26.036 [consensus/obcpbft] prepared -> DEBU b29 Replica 2 prepare count for view=0/seqNo=10: 3
bddtests_vp2:19:24:26.037 [consensus/obcpbft] prepared -> DEBU b2c Replica 2 prepare count for view=0/seqNo=10: 3
```

These logs show both show that vp1 and vp3 broadcast prepares for seqNo=10 to the network (both vp0 and vp2 receive these prepares).  This occurs at 19:24:26.037.

But, the logs for vp1 ends at 19:24:25.786, and the logs for vp3 end at 19:24:24.281.

Similarly, the logs for vp1 show the last sequence number processed as seqNo=8, while the logs for vp3 show the last sequence number processed as seqNo=2.

Could you verify that the logs were collected and uploaded correctly? Otherwise, this seems like it's some other more serious error which is also corrupting our logging.

**Comment by rameshthoomu** [comment]
@jyellick re-tested #793 issue after code fix merge and observed the same issue. Travis Logs were collected properly. PFB the logs files of failed scenario:

bddtests_vp0_1_chaincode_example02_with_4_peers_and_1_membersrvc,_issue_#680_(State_transfer)@1.3_Consensus_Options

**Log Files:**
[Vp0.txt](https://github.com/hyperledger/fabric/files/220285/Vp0.txt)
[vp1.txt](https://github.com/hyperledger/fabric/files/220286/vp1.txt)
[vp2.txt](https://github.com/hyperledger/fabric/files/220288/vp2.txt)
[vp3.txt](https://github.com/hyperledger/fabric/files/220287/vp3.txt)

**Behave Logs:**
[Behave Logs.txt](https://github.com/hyperledger/fabric/files/220293/Behave.Logs.txt)

**Comment by jyellick** [comment]
@rameshthoomu Thanks for retesting.  Looks like there is another stress related bug, I'm now able to reproduce this locally, will post here once it is resolved.

**Comment by jyellick** [comment]
@rameshthoomu I was going to suggest you attempt with the PR above, but looking at your latest set of logs, I believe the problem may simply be a timeout.  

You can see this message:

```
02:44:46.883 [peer] beforeHello -> DEBU 061 Received DISC_HELLO from endpoint=peerEndpoint:<ID:<name:"vp1" > ...
```

This is after

```
02:44:46.847 [consensus/obcpbft] processExecute -> DEBU 05c Block block number in execute wrong: expected 0, got 37
```

which indicates the network has already begun to make progress before the replica is entirely started and connected to its peers.  Eventually the network would catch up, but this test does not issue enough requests for this to happen.

Please try modifying your behave test to allow more time for the replica to start up.  I'm not submitting this as a PR, because the behave tests are perhaps already too slow for most people, but this can be debated if it solves your problem.

For your convenience, you may use [my branch](https://github.com/jyellick/fabric/tree/793-workaround) which has this sleep bumped from 5 to 15 seconds.

I'll wait for your confirmation, but I believe this issue is fixed.

**Comment by rameshthoomu** [comment]
@jyellick I have modified behave feature file @issue_680 to `And I wait "15" seconds` from `And I wait "5" seconds` and observed all behave tests are passed. I ran behave tests from TRAVIS for 3 times and observed all tests passed.

**Comment by jyellick** [comment]
@rameshthoomu Great! Glad to hear it, could please close this issue then?

**Comment by srderson** [comment]
@rameshthoomu could you submit a PR for the modified behave test?

**Comment by jyellick** [comment]
@srderson Do we have a policy for picking these timeouts? 5 seconds seems to work on most systems, but apparently not Travis

@rameshthoomu Could you try backing down the timeout value to something between 5 and 15 seconds? Maybe try 10? or 8? Since this test runs 3 times increasing the timeout by 10 seconds will cause our behave tests to take an extra 30 seconds to run.

**Comment by srderson** [comment]
@jyellick we do not have a policy for picking timeouts. Originally there was some desire to use the timeouts in the behave tests as a method to detect performance degradation, but I think that's no longer possible given the wide range of systems that are running these tests.

**Comment by rameshthoomu** [comment]
@jyellick Seems issue got fixed after I change timeout to `7` secs in behave feature file for issue#680 scenario. I ran multiple times with different time parameters and observed this is working as expected above `7` secs.

I could see failure when I revert changes back to `5 or 6` secs.

**Comment by jyellick** [comment]
@rameshthoomu Can you submit a PR for this with `7` seconds for the timeout?

**Comment by corecode** [comment]
Seems this can be closed

**Comment by rameshthoomu** [comment]
After increasing the timeout to 15 secs, this specific scenario is not failing hence closing the issue.
