### ISSUE TITLE
Testnet monitor

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#80]
We need a network monitor, like the one used in Car Demo application, to show activities on the nodes in the testnet, including useful metrics such as transaction rate, volume, active chaincode, etc.

**Comment by binhn** [comment]
@nitingaur6817, please update progress here

**Comment by nitingaur6817** [comment]
I now await approval, and we should have the environment once approved. I am hoping  by end of this week.

**Comment by binhn** [comment]
@frankyclu could you help define the detail requirements for the monitor: what are the important things that we should display?

**Comment by frankyclu** [comment]
Current considerations, details are discussed on the slack channel

Performance
-  Average latency
- Average Capacity (Tx/sec on the Openchain network.)

Volume
- Transaction Load
  -  # of transaction for last minute/Hour/weekly …
- Transaction Types
  - Chaincode – deployment transactions
  - Chaincode invocation transactions

Network Participant Health - Information
- Validating Peers List
  - Name 
  - Status (Up or down)
  - Consensus success rate 
  - IP Address (optional)
  - Location
- Non VPs node List
  - Name 
  - Status (Up or down)
  - IP Address (optional)
  - Location

Inter-Ledger Data (We’re not gonna have data for this for MVP, but can reserve the space and provide dummy values)
- InterLedger list (outbound)
  - Name
  - # of transactions sent over last minute/hour/day
- InterLedger list (Inbound)
  - Name
  - # of transactions received over last minute/hour/day

**Comment by seanbarclay** [comment]
@binhn @markparz. Unless we're considering this a Story for the Milestone, please close this ticket out. The requirements appear to have been addressed in the UI and are currently being implemented. Thanks

**Comment by binhn** [comment]
ok, considered completed and closed
