### ISSUE TITLE
The account values ("a" or "b") are  no  changed after some number of invokes are processed 

### ISSUE THREAD

**Issue by samding01** [hyperledger-archives/fabric#803]
I setup a 8 peers with security enabled and consensus=obcpbft (mode=batch) on LoZ platform.
Here is the configuration files 
[peer8_secerity_consensus_config.zip](https://github.com/openblockchain/obc-peer/files/163564/peer8_secerity_consensus_config.zip)

After processing some `invoke` requests, the value of accounts (`a` or `b`) is not changed even 
no error from  processing `invokes`. This  is found from  the latest master code.

**Reproduce:**
-  1) copy and unzip the attached config file; build images
-  2)  start peers and deploy
  
  ```
  docker-compose -f docker-compose.yml -f compose-consensus-8-links.yml -f compose-consensus-8-sieve.yml up --force-recreate -d
  docker exec -it obcpeer_cli_1 bash
  OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer login jim    pw=6avZQLwcUe9b
  OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer chaincode deploy -u jim -p github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02 -c '{"Function":"init", "Args": ["a","1000", "b", "2000"]}'
  ```
-  3)  send `invokes` via REST. ( I use Jmeter, here is the test plan 
  [obc8_sec.zip](https://github.com/openblockchain/obc-peer/files/163584/obc8_sec.zip)
- 4) In obcpeer_cli_1 to verify the account values of `a` and `b`
  
  ```
  OPENCHAIN_PEER_ADDRESS=vp0:30303 obc-peer chaincode query -u jim -l golang -n NAME -c '{"Function": "query", "Args": ["a"]}'
  ```

**Note:** the same problem is not found on 4 peers with the same configuration (security enabled, consensus=obcpbft).

**Comment by bmos299** [comment]
@samding01 does this issue still exist?  Thanks, @bmos299

**Comment by samding01** [comment]
The problem seems gone. Please close this issue.

Thanks.
