### ISSUE TITLE
Creating a Docker network with security enabled

### ISSUE THREAD

**Issue by slsd123** [hyperledger-archives/fabric#808]
I cannot set up a network on my machine using Docker containers with security enabled. I get the following error:

`$ docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer
04:26:33.268 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
04:26:33.271 [main] serve -> INFO 002 Security enabled status: true
04:26:33.271 [main] serve -> INFO 003 Privacy enabled status: false
04:26:33.272 [eventhub_producer] start -> INFO 004 event processor started
04:26:33.273 [crypto] NewPeerWithHandler -> INFO 005 Registering validator [binhn] with name [binhn]...
2016/03/09 04:26:34 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/03/09 04:26:35 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/03/09 04:26:35 Failed to dial localhost:50051: grpc: timed out trying to connect; please retry.
04:26:35.955 [crypto] callECAReadCACertificate -> ERRO 006 [validator.binhn] Failed requesting read certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.955 [crypto] getECACertificate -> ERRO 007 [validator.binhn] Failed requesting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.955 [crypto] retrieveECACertsChain -> ERRO 008 [validator.binhn] Failed getting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.956 [crypto] registerCryptoEngine -> ERRO 009 [validator.binhn] Failed retrieveing ECA certs chain [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.956 [crypto] register -> ERRO 00a [validator.binhn] Failed registering crypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.956 [crypto] register -> ERRO 00b Failed registering [binhn]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
04:26:35.957 [crypto] RegisterValidator -> ERRO 00c Failed registering [binhn]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
04:26:35.957 [crypto] NewPeerWithHandler -> ERRO 00d Failed registering validator [binhn] with name [binhn] [rpc error: code = 2 desc = "grpc: the client connection is closing"].
04:26:35.958 [main] serve -> CRIT 00e Failed creating new peer with handler rpc error: code = 2 desc = "grpc: the client connection is closing"`

I have my obcca server running in a separate window and I have `security.enabled` set to `true` in my `openchain.yaml` file. I am simply following the instructions found [here](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devnet-setup.md). I already completed the [Setting Up Development Environment](https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devenv.md) instructions and got things running in the [Chaincode Development Instructions](https://github.com/openblockchain/obc-docs/blob/master/api/SandboxSetup.md#security-setup-optional).

**Comment by genggjh** [comment]
Add "--log-level=debug" behind the "obc-peer peer" when you run the docker container, and past the more detail debug log into here. May help us to investigate.

**Comment by slsd123** [comment]
Here is the debug detail:

```
$ docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp1 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true openchain-peer obc-peer peer --logging-level=debug
16:53:40.374 [crypto] main -> INFO 001 Log level recognized 'info', set to INFO
16:53:40.374 [logging] LoggingInit -> DEBU 002 Setting default logging level to DEBUG for command 'peer'
16:53:40.377 [main] serve -> DEBU 003 Listen address not specified, using peer endpoint address
16:53:40.379 [eventhub_producer] AddEventType -> DEBU 004 registering block
16:53:40.379 [eventhub_producer] AddEventType -> DEBU 005 registering register
16:53:40.379 [main] serve -> INFO 006 Security enabled status: true
16:53:40.379 [main] serve -> INFO 008 Privacy enabled status: false
16:53:40.379 [eventhub_producer] start -> INFO 007 event processor started
16:53:40.381 [main] serve -> DEBU 009 Running as validating peer - installing consensus noops
16:53:40.381 [peer] NewPeerWithHandler -> DEBU 00a Registering validator with enroll ID: binhn
16:53:40.382 [crypto] NewPeerWithHandler -> INFO 00b Registering validator [binhn] with name [binhn]...
2016/03/09 16:53:41 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/03/09 16:53:43 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"
2016/03/09 16:53:43 Failed to dial localhost:50051: grpc: timed out trying to connect; please retry.
16:53:43.075 [crypto] callECAReadCACertificate -> ERRO 00c [validator.binhn] Failed requesting read certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.076 [crypto] getECACertificate -> ERRO 00d [validator.binhn] Failed requesting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.078 [crypto] retrieveECACertsChain -> ERRO 00e [validator.binhn] Failed getting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.078 [crypto] registerCryptoEngine -> ERRO 00f [validator.binhn] Failed retrieveing ECA certs chain [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.078 [crypto] register -> ERRO 010 [validator.binhn] Failed registering crypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.078 [crypto] register -> ERRO 011 Failed registering [binhn]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
16:53:43.079 [crypto] RegisterValidator -> ERRO 012 Failed registering [binhn]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
16:53:43.079 [crypto] NewPeerWithHandler -> ERRO 013 Failed registering validator [binhn] with name [binhn] [rpc error: code = 2 desc = "grpc: the client connection is closing"].
16:53:43.080 [main] serve -> CRIT 014 Failed creating new peer with handler rpc error: code = 2 desc = "grpc: the client connection is closing"
```

Thanks!

**Comment by binhn** [comment]
@slsd123 I updated your comment for easy to read.
The problem is the peer was trying to connect to localhost:50051 which is not the docker contain, but on the host, where obc-ca was running.

> 2016/03/09 16:53:41 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:50051: getsockopt: connection refused"; Reconnecting to "localhost:50051"

Follow the devnet-setup.md and replace the ip address with your host IP when you start up the peer

```
    pki:
        eca:
            paddr: host_ip:50051
        tca:
            paddr: host_ip:50051
        tlsca:
            paddr: host_ip:50051
```

**Comment by slsd123** [comment]
I've been trying to follow the devnet-setup.md file and that's where I ran into my issue. I have tried changing the pki.eca/tca/tlsca paddr in my openchain.yaml to obcca:50051 as well and I get the same error. How can I find out what the ip address of my obc-ca docker container?

**Comment by tuand27613** [comment]
from the command line `docker ps` to list the container IDs, then `docker inspect <containerid>` to get its ip address.

Alternatively,  look at [compose-consensus-4.md](https://github.com/openblockchain/obc-peer/blob/master/compose-consensus-4.md) or the docker-compose files in [openchain/peer/bddtests](https://github.com/openblockchain/obc-peer/tree/master/openchain/peer/bddtests) for examples of how docker environments have been setup.

**Comment by GauriSawant** [comment]
I created my CA server and now trying to run - docker run command it gives me similar error as mentioned in above comments. I want to know how shall i substitute localhost with host IP of CA server in core.yaml?

**Comment by christo4ferris** [comment]
@slsd123 thanks for submitting this. I am closing this as I believe we have moved on considerably since this was raised and it should be possible to set up a network with security enabled.
