### ISSUE TITLE
Query chaincode timeout when security is enabled

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#810]
Start a single validator with the following settings:

```
OPENCHAIN_PEER_ID=vp0
OPENCHAIN_PEER_ADDRESSAUTODETECT=false
OPENCHAIN_PEER_ADDRESS=obc01.watson.ibm.com:30303
OPENCHAIN_PEER_LISTENADDRESS=0.0.0.0:30303
OPENCHAIN_PEER_VALIDATOR_CONSENSUS=noops
OPENCHAIN_PEER_PKI_ECA_PADDR=debian2.watson.ibm.com:50051
OPENCHAIN_PEER_PKI_TCA_PADDR=debian2.watson.ibm.com:50051
OPENCHAIN_PEER_PKI_TLSCA_PADDR=debian2.watson.ibm.com:50051
OPENCHAIN_LOGGING_PEER=info
OPENCHAIN_SECURITY_ENABLED=true
OPENCHAIN_SECURITY_PRIVACY=true
OPENCHAIN_SECURITY_ENROLLID=test_vp0
OPENCHAIN_SECURITY_ENROLLSECRET=MwYpmSRjupbT
```

Through REST API, the following calls are made: register, deploy, and query.

register:

```
{
  "enrollId": "lukas",
  "enrollSecret": "NPKYL39uKbkj"
}

```

deploy:

```
{
  "type": "GOLANG",
  "chaincodeID": {
    "path": "github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
  },
  "ctorMsg": {
    "function": "init",
    "args": ["a", "100", "b", "200"]
  },
  "secureContext": "lukas"
}
```

query:

```
{
  "chaincodeSpec": {
    "type": "GOLANG",
    "chaincodeID": {
      "name": "bb540edfc1ee2ac0f5e2ec6000677f4cd1c6728046d5e32dede7fea11a42f86a6943b76a8f9154f4792032551ed320871ff7b7076047e4184292e01e3421889c"
    },
    "ctorMsg": {
      "function": "query",
      "args": ["b"]
    },
    "secureContext": "lukas"
  }
}
```

The query fails with an error in the log:

`11:30:32.346 [rest] ServerOpenchainREST -> ERRO 046 {"Error": "Querying Chaincode -- Error:Failed to execute transaction or query(Timeout expired while executing transaction)"}`

The full log is attached.

[obc-peer.log.txt](https://github.com/openblockchain/obc-peer/files/165745/obc-peer.log.txt)

**Comment by adecaro** [comment]
Hi @gongsu832, I think you are using an old version of obc. May you use the latest version of the master? Thanks.

**Comment by gongsu832** [comment]
@adecaro I'm not using the latest version. Because last time I tried, there are some failed behave tests. So it's OK to ignore some failed behave tests? Thanks.

**Comment by tuand27613** [comment]
@gongsu832 ,  there's one behave test that will by fixed by #751. Ignore the fail on the "(State transfer)" for now.

**Comment by gongsu832** [comment]
@tuand27613 OK thanks.

**Comment by gongsu832** [comment]
@tuand27613 I just rebased to latest commit. My behave test results are the following:

```
Failing scenarios:
  peer_basic.feature:404  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
  peer_basic.feature:490  chaincode example02 with 4 peers and 1 obcca, issue #680 (State transfer) -- @1.3 Consensus Options
  peer_basic.feature:678  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.1 Consensus Options
  peer_basic.feature:725  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
18 scenarios passed, 4 failed, 1 skipped
478 steps passed, 4 failed, 33 skipped, 0 undefined
Took 17m10.444s
```

Does this look OK? Thanks.

**Comment by tuand27613** [comment]
Only failed test should have been the `peer_basic.feature:490` above.  
Could you re-run and capture the behave stdout ?

Even with that, I'd say you can run with the latest commit. Please re-run your test so @angelo can debug further and create a separate issue for the behave errors

**Comment by gongsu832** [comment]
@tuand27613 Thanks Tuan. I will create a separate issue and upload the behave test log.

**Comment by adecaro** [comment]
Hi @gongsu832, is the issue still in place?

**Comment by gongsu832** [comment]
@adecaro I haven't had a chance to try the latest hyperledger code. But you can close it if you want. I will create a new issue if there is a problem. Thanks.

**Comment by adecaro** [comment]
Please, may you do that. It seems that I don't have anymore the right to close issues.
