### ISSUE TITLE
Consensus won't accept log parameter if it's in caps

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#815]
Description:  Setting the openchain.yaml file's consensus validator to OBCPBFT results in the OBC-PEER peer using noops.

Steps:
1.  Set the consensus validator to all uppercase OBCPBFT in your openchain.yaml file
2.  Set your peer logging to debug
3.  Start your docker container based on this openchain.yaml file

Results:

The main debug message correctly says it's installing OBCPBFT plugin for consensus.
![obcpbft](https://cloud.githubusercontent.com/assets/17052305/13687870/0b66ef02-e6ec-11e5-9ecc-8dcb0e27e04e.jpg)

Expected Results:

Parameters should be accepted regardless of case (drop case before comparison).

**Comment by corecode** [comment]
Consensus handler should complain about unknown (uppercase) consensus plugin.

**Comment by tuand27613** [comment]
PR #829

**Comment by corecode** [comment]
I don't think #829 handles this satisfactorily - typos still will result in the same confusing outcome.

**Comment by RicHernandez2** [comment]
Verified this fix, thanks!
