### ISSUE TITLE
Consensus panic when 4th validating peer comes up.

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#817]
Description:  4th VP of a set of 4 VPs crashes with a panic error message when they are brought up in a staggered manner, per the instruction documents.

Steps to Repro:
1.  Set peer log level to debug
2.  Bring up a set of 4 VPs per the devnet_setup.md
3.  View logs on 4th VP

Results:

obc-peer crashes with a panic message

Expected results:

All VPs should be able to come up and speak to each other
[pbftpanic.txt](https://github.com/openblockchain/obc-peer/files/169485/pbftpanic.txt)

**Comment by tuand27613** [comment]
what's the peer id for the 4th VP ?  OPENCHAIN_PEER_ID=VP4 or VP3 ?

**Comment by RicHernandez2** [comment]
docker run --rm -it -e OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243 -e OPENCHAIN_PEER_ID=vp4 -e OPENCHAIN_PEER_ADDRESSAUTODETECT=true -e OPENCHAIN_PEER_DISCOVERY_ROOTNODE=172.17.0.4:30303 openchain-peer obc-peer peer

This is how I called it, I should have named it vp3, but I named it vp4, but if they're going to come up out of sequence would this not expose the same bug?

**Comment by tuand27613** [comment]
The VPs can start up out of sequence but the peer IDs have to be in order 0,1,2,...n with no gaps.

It's a bit of a pain right now but we're working on how to get the consensus peers to recognize each other, e.g. #756 or some other mechanisms

**Comment by kchristidis** [comment]
Should be handled by #756.

**Comment by RicHernandez2** [comment]
Tested vp0, vp1, vp2, vp4 today... issue resolved.
