### ISSUE TITLE
Small study on behave test failures

### ISSUE THREAD

**Issue by gongsu832** [hyperledger-archives/fabric#821]
I'm using commit tag 42c6fe9ff5bceb4258eb9754fa33fef5f668ecd2 of Mar. 8.

On my Linux s390x system there are some failures in behave tests. I noticed that my system only has 2 CPUs and 4GB memory. So I tried another system that has 2 CPUs and 16GB memory and I still got some failures (some the same, some are different). I also noticed that the two systems were using different docker storage drivers, one is using devicemapper and the other is using btrfs. So I did a small study of different combinations of distro, host FS, memory size, and docker storage driver to see how the results of behave tests differ. My finding are in the attached PDF. I'm also attaching the running logs of all tests so you can debug.

General findings:
- CPU doesn't seem to matter. I've tried both 2 CPUs and 4 CPUs and results are pretty much the same.
- Memory seems to help in some cases but not in other cases.
- Docker storage driver differs greatly across distros. For example, btrfs performs pretty well on SLES but is very bad on RHEL, while devicemapper performs pretty well on Debian but is very bad on SLES.

I briefly looked at some of the failures and it seems that a lot of them are timeouts. So it may be just a simple matter of increasing the wait time. But I'll leave the fix to you. I hope you find these findings helpful for debugging or designing your test cases. Thanks.

[behave_tests.pdf](https://github.com/openblockchain/obc-peer/files/170064/behave_tests.pdf)
[behave_logs.zip](https://github.com/openblockchain/obc-peer/files/170066/behave_logs.zip)

**Comment by gongsu832** [comment]
Updating to commit tag 3ef73d319b01fe84c0c88973350a240fc490d82e of Mar. 11.

Behave tests on Debian 8:

```
Failing scenarios:
  peer_basic.feature:404  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
  peer_basic.feature:405  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.2 Consensus Options
  peer_basic.feature:407  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.4 Consensus Options
  peer_basic.feature:539  chaincode example02 with 4 peers and 1 obcca, issue #724 -- @1.1 Consensus Options

0 features passed, 1 failed, 0 skipped
16 scenarios passed, 4 failed, 3 skipped
405 steps passed, 4 failed, 106 skipped, 0 undefined
Took 16m32.023s
```

Behave tests on RHEL 7.2:

```
Failing scenarios:
  peer_basic.feature:17  Range query test, single peer, issue #767
  peer_basic.feature:76  chaincode shim table API, issue 477
  peer_basic.feature:289  chaincode example 02 single peer
  peer_basic.feature:330  chaincode example02 with 5 peers, issue #520
  peer_basic.feature:404  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
  peer_basic.feature:405  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.2 Consensus Options
  peer_basic.feature:406  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.3 Consensus Options
  peer_basic.feature:407  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.4 Consensus Options
  peer_basic.feature:539  chaincode example02 with 4 peers and 1 obcca, issue #724 -- @1.1 Consensus Options
  peer_basic.feature:616  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.1 Consensus Options
  peer_basic.feature:617  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.2 Consensus Options
  peer_basic.feature:618  4 peers and 1 obcca, consensus still works if one backup replica fails -- @1.3 Consensus Options
  peer_basic.feature:678  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.1 Consensus Options
  peer_basic.feature:679  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.2 Consensus Options
  peer_basic.feature:680  4 peers and 1 obcca, consensus fails if 2 backup replicas fail -- @1.3 Consensus Options
  peer_basic.feature:723  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.1 Consensus Options
  peer_basic.feature:724  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.2 Consensus Options
  peer_basic.feature:725  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
2 scenarios passed, 18 failed, 3 skipped
207 steps passed, 18 failed, 290 skipped, 0 undefined
Took 16m10.189s
```

Behave tests on SLES 12.1:

```
Failing scenarios:
  peer_basic.feature:723  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.1 Consensus Options
  peer_basic.feature:724  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.2 Consensus Options
  peer_basic.feature:725  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.3 Consensus Options

0 features passed, 1 failed, 0 skipped
17 scenarios passed, 3 failed, 3 skipped
425 steps passed, 3 failed, 87 skipped, 0 undefined
Took 14m17.255s
```

All machines have 4 CPUs and 16GB memory. Logs attached.
[behave_logs.zip](https://github.com/openblockchain/obc-peer/files/170541/behave_logs.zip)

**Comment by gongsu832** [comment]
OK I was stupid with RHEL 7.2. The reason is failed so many tests is because it had firewalld enabled by default. I had disabled it before but forgot to disable it after changing memory config and reboot. After disabling the firewall:

```
Failing scenarios:
  peer_basic.feature:404  chaincode example02 with 4 peers and 1 obcca, issue #567 -- @1.1 Consensus Options
  peer_basic.feature:539  chaincode example02 with 4 peers and 1 obcca, issue #724 -- @1.1 Consensus Options
  peer_basic.feature:723  4 peers and 1 obcca, consensus still works if 1 peer (vp3) is byzantine -- @1.1 Consensus Options

0 features passed, 1 failed, 0 skipped
17 scenarios passed, 3 failed, 3 skipped
396 steps passed, 3 failed, 116 skipped, 0 undefined
Took 13m56.199s
```

[behave-RHEL-4CP-16GB-devmp.log.txt](https://github.com/openblockchain/obc-peer/files/171138/behave-RHEL-4CP-16GB-devmp.log.txt)

**Comment by srderson** [comment]
Please reopen if tests are still failing. These currently pass in the Travis build.
