### ISSUE TITLE
Got error message "cannot find package google/protobuf"

### ISSUE THREAD

**Issue by linwumeng** [hyperledger-archives/fabric#824]
I'm new to Goland and OBC. I'd like to run obc-peer locally, but I always get the error message "cannot find package google/protobuf" when I run "go build" under /openchain/src/github.com/openblockchain/obc-peer. Could anyone help me?  Thank you a lot!

**Comment by ckeyer** [comment]
cp -a vendor/google $GOPATH/src/google   OR   ues govendor

**Comment by linwumeng** [comment]
it works. Thank you!
