### ISSUE TITLE
Illegal expresssion Error while running "obc-peer" service on pulled image from docker hub

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#826]
Pushed an image to docker hub after perform 'go build' and 'go test' commands from vagrant environment. 

After successfully pulled the image from docker hub using `docker pull repository-name`, user trying to execute `./obc-peer peer` command in vagrant box but he keeps on getting an error message saying **Illegal expression**

**Comment by srderson** [comment]
This issue needs more info. Is this still a problem?

**Comment by rameshthoomu** [comment]
It's working as expected now in softlayer machine and from Vagrant box. Able to start peer process after pulled an image from docker hub (pushed to docker hub from vagrant). We can close this issue.

[docker pull .txt](https://github.com/hyperledger/fabric/files/224811/docker.pull.txt)

**Comment by ibmmark** [comment]
@rameshthoomu is there more work needed on this?

**Comment by rameshthoomu** [comment]
No @ibmmark. We can close this issue.

**Comment by rameshthoomu** [comment]
Working as expected. Closing this issue.
