### ISSUE TITLE
Empty Results When Issuing the REST call for GET /network/peers

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#827]
From the spec I see:

6.2.1.4 Network API

Use the Network API to retrieve information about the network of peer nodes comprising the blockchain fabric.

The /network/peers endpoint returns a list of all existing network connections for the target peer node. The list includes both validating and non-validating peers. The list of peers is returned as type PeersMessage, containing an array of PeerEndpoint, defined in section 3.1.1.

message PeersMessage {
    repeated PeerEndpoint peers = 1;
}

Network Request:

GET host:port/network/peers

I am using POSTMAN on commit level: 3ef73d319b01fe84c0c88973350a240fc490d82e

My results are coming back empty.  It is easier to show with curl:
$ curl  http://127.0.0.1:3000/network/peers 2>/dev/null
{}

Notice I only received back the curly braces with no data.

Please ping with any questions.
Barry

**Comment by angrbrd** [comment]
@bmos299 ,

Do you actually have other peers connected to yours? If you are (a) running in development mode or (b) are running in network mode as the only existing peer, then the response is expected to be empty as you don't have any other peers connected to the target peer that you're sending this request to. But if you actually have a network with multiple peers up and running, this request should return the peers that you have connections to inside the curly braces. Can you please elaborate as to the setup that you have?

Thanks.

**Comment by bmos299** [comment]
@angrbrd 
Sure.   It returns the grpc address and port of the other peers in the network.
1.  Why  not include yourself in the list.
A use case is a network admin is using this to determine how to evenly distribute clients to peers.  For example, I have 500 clients and 5 peers.  I want to distribute 100 clients to each peer.  
I don't think I should issue the network call than then have to add myself back into the group.
2.  Why not have the returned information provide more detail to include REST IP:PORT and GRPC IP:PORT for all peers?  If the command is designed for networking info on a peer....then let's give all the networking information we know.
Thanks, Barry
