### ISSUE TITLE
Could not add a user back to security after  calling DELETE Rest API.

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#828]
## Steps to Reproduce:
1. Register a user using:

POST: http://127.0.0.1:3000/registrar 
{
"enrollId":"jim",
"enrollSecret":"6avZQLwcUe9b"
}
1. Then GetUserRegistration: 
   http://127.0.0.1:3000/registrar/jim
   {"OK": "User jim is already logged in."}
2. Delete UserRegistration 
   http://127.0.0.1:3000/registrar/jim
   {"OK": "Deleted login token and directory for user jim."}
3. ReRegister jim POST: http://127.0.0.1:3000/registrar 
   {
   "enrollId":"jim",
   "enrollSecret":"6avZQLwcUe9b"
   }

Expected Result:
To be able to add jim in step4.

Actual Result:
Errors:

21:33:32.160 [crypto] getEnrollmentCertificateFromECA -> ERRO 1706 [client.jim] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = "identity or token do not match"].
21:33:32.160 [crypto] retrieveEnrollmentData -> ERRO 1707 [client.jim] Failed getting enrollment certificate [id=jim]: [rpc error: code = 2 desc = "identity or token do not match"]
21:33:32.160 [crypto] registerCryptoEngine -> ERRO 1708 [client.jim] Failed retrieveing enrollment data [rpc error: code = 2 desc = "identity or token do not match"].
21:33:32.160 [crypto] register -> ERRO 1709 [client.jim] Failed registering crypto engine [rpc error: code = 2 desc = "identity or token do not match"].
21:33:32.160 [crypto] RegisterClient -> ERRO 170a Failed registering [jim] [rpc error: code = 2 desc = "identity or token do not match"].
21:33:32.160 [crypto] Login -> ERRO 170b Failed registering client [jim] with name [jim] [rpc error: code = 2 desc = "identity or token do not match"].
21:33:32.160 [rest] Register -> ERRO 170c Error on client login: rpc error: code = 2 desc = 'identity or token do not match'

**Comment by angrbrd** [comment]
@2016Nishi ,

This is working as designed. The registration with the CA is expected to work only ONCE per the documentation. The registrationID and registrationPW are designed to be used only once.

https://github.com/angrbrd/obc-docs/blob/angrbrd-doc-edits/api/SandboxSetup.md#note-on-security-functionality

"Upon successful user authentication, the application will perform user registration with the CA exactly once. If registration is attempted a second time for the same user, an error will result. During registration, the application sends a request to the certificate authority to verify the user registration and if successful, the CA responds with the user certificates and keys."

Closing. Thanks.
