### ISSUE TITLE
Manage VP whitelist via system chaincode

### ISSUE THREAD

**Issue by kchristidis** [hyperledger-archives/fabric#830]
(This will be the follow-up to #756.)

Once you have the whitelist structure populated (see #756), you'll need to persist it so that a node that crashes and restarts knows which VPs to connect to.

I was originally thinking of a simple `save_whitelist()`, `load_whitelist()` pair of calls in the DB, but @srderson suggests that doing this via a chaincode may be the best way to go He is right in that it makes for a cleaner design.

I also think this will allow for system "blocks" later on that will allow us to re-configure the membership.

If we are to go the chaincode route, we will have a `whitelist` system chaincode in the `genesis` block.

The nodes start up and form N-1 connections to each other, and then either (a) the leader invokes the `whitelist` chaincode so as to update it with the newly-formed whitelist, or (b) each VP invokes that chaincode and write their own separate, version of the whitelist there. (All the versions stored there should coincide.)

Regardless of which approach we go with, we'll need to leverage the membership service and apply some policy to the chaincode that prevents unauthorized invocations of the `write()` function of that chaincode. For example, in the first only the current leader should be allowed to update the whitelist. In the second case, a VP should only update the whitelist that corresponds to them.

In the first case, we should also inspect the payload of the suggested transaction, i.e. what are the suggested nodes, and vote negatively if we don't agree. However, in PBFT we do not inspect the payload before agreeing. And in Sieve we only check for non-deterministic transactions, and this one isn't.

So, I guess I have two questions:
1. Is there an example and documentation that shows how access to chaincode invocations can be restricted and modified? Also, can this restriction apply to the function level? i.e. `write()` should be access-controlled, but `read()` shouldn't. @adecaro I'm not sure if you're the one to ping about this.
2. How would we go about inspecting proposed transactions? Do we treat it as a special case in Sieve where you execute, but if you see that it's a system chaincode you send your result to the primary only if the payload is right (i.e. the leader attempts to install the right whitelist)? @corecode let me know what you think. (In general, I may be approaching this wrong.)

**Comment by corecode** [comment]
I think this is a task for system management chaincode, which we don't have yet.  Until system management chaincode is available as API, I suggest using duct tape.

**Comment by binhn** [comment]
We are working on system chaincode now and sprint 3, so let's leverage that.

**Comment by kchristidis** [comment]
If system chaincodes are not up and running and documented already, I would suggest moving this to Sprint 4 (or the Sprint after which these items are delivered).

FWIW, the work in #756 now does persisting as well so we're covered in one regard and this is not as critical as it used to be.

**Comment by kchristidis** [comment]
Following the discussion with @binhn on Monday, this is moved to the backlog.

Also, updated the title to reflect the work that will be done on this issue.

**Comment by adecaro** [comment]
@kchristidis, actually, for access control you can have a look at the asset management example. It presents a very simple way of defining access control at chaincode level. Don't hesitate to contact me for more information on this.

**Comment by tuand27613** [comment]
@muralisrini ,  could you link to the issue you're using for system chaincode ?

**Comment by corecode** [comment]
can we merge this with #999?
