### ISSUE TITLE
Error message when building peer image with default openchain.yaml settings

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#831]
Description:  The default openchain.yaml settings generates a logging error when building the image via commandline:  go test -run BuildImage_Peer

Results:
![chainchainchain](https://cloud.githubusercontent.com/assets/17052305/13796042/d2e6db0e-eada-11e5-9740-58546561a57e.jpg)

Expected results:

The openchain.yaml should contain all fields necessary to ensure an error free setup.

Additional info:  I changed my local files to narrow down the source of the error message.   It's the config.go in the container directory.

**Comment by binhn** [comment]
@RicHernandez2 could you verify this bug still there?

**Comment by RicHernandez2** [comment]
Hey @binhn, sure thing, I'm out sick today,  but I will make sure to test this first thing tomorrow.

**Comment by RicHernandez2** [comment]
The bug is still there, as noted it's coming from config.go

![stillthere](https://cloud.githubusercontent.com/assets/17052305/14641766/d6f81c02-0615-11e6-927a-84bbfe66515e.JPG)

**Comment by bmos299** [comment]
@RicHernandez2 does this problem still exist?

**Comment by RicHernandez2** [comment]
Yes, it's still going on:

![logerror](https://cloud.githubusercontent.com/assets/17052305/14837271/d259ba8c-0be4-11e6-861c-082d058dbbbb.JPG)

**Comment by RicHernandez2** [comment]
Checked again today, again this is coming from config.go

![stillthere2](https://cloud.githubusercontent.com/assets/17052305/14891655/821a0bec-0d35-11e6-839c-06708e3c981b.jpg)

**Comment by christo4ferris** [comment]
closing this as it is likely no longer relevant.
