### ISSUE TITLE
"Failed to launch chaincode spec" when a peer connects after chaincode has been deploye

### ISSUE THREAD

**Issue by znewsham** [hyperledger-archives/fabric#832]
Unsure if this is a "feature" or a bug. When I connect a new peer to the network, none of the existing blocks on the network are transferred to the new peer. This issue is particularly clear when a deploy is missed, but it leads to invalid data whenever an invoke is missed too. 

Is there an additional undocumented step in order to keep peers synchronized/re-synchronize when they come back online?

"Error:Failed to launch chaincode spec(Could not get deployment transaction for 63fc1ff322d2d9ebc7c5d1970ba6ea04a6bdf1f0e0a63f3b0108aa87af2dd3aa205b24d807428c094e66b7684bd76363ced349421c662489eea60894e60dc642 - ledger: resource not found)

**Comment by znewsham** [comment]
I believe this is partly that the peers don't sync after coming online and partly a potential bug in  buildChaincodeContainerUsingDockerfilePackageBytes. Shouldn't the "Name" parameter of the BuildImageOptions be GetVMFromName(spec.ChaincodeID.Name) rather than just spec.ChaincodeID.Name?

**Comment by corecode** [comment]
I don't think we support adding new peers yet.

**Comment by znewsham** [comment]
Thats a shame, could you explain the use case of a system that only allows a fixed number of nodes that must have 100% uptime? Or is it more the case that you will support it when OBC is released, but it's not yet functional?

**Comment by tuand27613** [comment]
The pbft protocol allows for consensus to work even if some number of peers are down ( or act in byzantine ways ). The formula is for N total peers, the maximum number of faulty peers is (N-1)/3.

So in a network of 4,  consensus still works if at most 1 peer is faulty. 

When that peer restarts,  it will at some point receive checkpoint messages from the other peers, realize that it's behind and initiate state transfer.

**Comment by znewsham** [comment]
I see, so there is a mechanism in place to sync to peers as they come online, will/should that faulty peer be able to  accept transactions/queries prior to receiving the checkpoints, and if it does and realizes it is behind, what happens to the transactions that occurred before the state transfer?

**Comment by tuand27613** [comment]
that peer will not participate until it has sync'ed states (basically by getting the blocks that it's missing ) with the rest of the peers.

**Comment by znewsham** [comment]
I think this is the part that isn't working, because currently it will allow me to issue transactions and queries, and will update it's local state accordingly, they the two nodes in my network will have different states. Admittedly, I only have two nodes, so this would have violated the (N-1)/3.

**Comment by corecode** [comment]
do you use pbft consensus?

**Comment by znewsham** [comment]
I use the default, is that not pbft?

**Comment by corecode** [comment]
I think the default is still NOOPs, which does not provide any guarantees regarding divergence of nodes.

**Comment by tuand27613** [comment]
currently default is NOOPS. Check in openchain.yaml

**Comment by znewsham** [comment]
I see and all the sync is done through consensus, so no consensus, no sync? I'll take a look at pbft, thanks!

**Comment by christo4ferris** [comment]
closing this, seems resolved. Please reopen if this is still an issue
