### ISSUE TITLE
Error: Error building chaincode - "Registration to the Membership Service required." when Enable Security and Privacy through CLI

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#834]
Getting error message while executing chaincode deploy command with security and privacy enabled through CLI.

**Steps to Reproduce:**
- Make sure Security and Privacy enabled to False in openchain.yml file before execute series of commands.
- Execute series of "security and privacy" enabled steps mentioned in https://github.com/openblockchain/obc-docs/blob/master/api/SandboxSetup.md document

Note: `OPENCHAIN_SECURITY_ENABLED=true OPENCHAIN_SECURITY_PRIVACY=true ./obc-peer peer --peer-chaincodedev` to enable Security and Privacy through CLI.
- After execute chaincode deploy command, observed `"Error: Error building chaincode: rpc error: code = 2 desc = "Registration to the Membership Service required."`

I Didn't see any issue if i enable Security and Privacy manually in "openchain.yml" file and run the series of commands..

[Failed Client Intialization - Registration to the memebership service required.docx](https://github.com/openblockchain/obc-peer/files/176162/Failed.Client.Intialization.-.Registration.to.the.memebership.service.required.docx)

**Comment by rameshthoomu** [comment]
I have started `obcca server` before execute the series of steps...

**Comment by christo4ferris** [comment]
@rameshthoomu I am closing this as it is rather stale and based on code that has been significantly improved since. Please reopen if it is still relevant, and provide updated info on observations and how to reproduce, etc.
