### ISSUE TITLE
integrate openblockchain compiler

### ISSUE THREAD

**Issue by ghaskins** [hyperledger-archives/fabric#837]
This is a placeholder for discussion on the proposed [openblockchain compiler](https://github.com/ghaskins/obcc) toolchain, as it is developed.  This could help in a few aspects of chaincode development/deployment including adding new chaincode language types, abstracting chaincode interfaces, ABI management, etc.

@muralisrini @joequant @kletkeman

**Comment by christo4ferris** [comment]
@ghaskins closing this as I believe it is covered by fabric-chaintool. Please reopen if you think otherwise.
