### ISSUE TITLE
Redis instead of RocksDB ?

### ISSUE THREAD

**Issue by bgrieder** [hyperledger-archives/fabric#839]
Do you think it would be possible to use Redis instead of RocksDB as a key/value store ?

Has any work been already carried out on the subject ?

If yes, is this work publicly available ?
If not, could you provide pointers (in the code) to look at ?

Many Thanks

**Comment by srderson** [comment]
The interface to RocksDB is https://github.com/openblockchain/obc-peer/blob/master/openchain/db/db.go. It uses column families and snapshots which are specific to RocksDB. Wrapping these in interfaces so OBC can potentially support other DBs more easily is probably a good idea.

Why are you interested in using Redis over RocksDB? I usually think of Redis as a fast remote in-memory store where as OBC needs an embedded key/value store that is persisted to disk.

**Comment by srderson** [comment]
Closing for now. Please reopen if you wish to discuss further or need more info.
