### ISSUE TITLE
Add vi/vim to Docker Images

### ISSUE THREAD

**Issue by bmos299** [hyperledger-archives/fabric#840]
Ramesh and I are working on publishing the obc-peer image for people to pull and run with.  I am going through the process of pulling the image and noticed vi or vim is not stalled.   Can we add this to our Dockerfile?  If someone wants to pull image and tweak the openchain.yaml, I'm thinking doing an apt-get install everytime for vi or vim seems tedious.  Obviously, they can make a new image, but vi is just so low overhead everyone expects to have it on their linux image.

Thanks, Barry.

**Comment by bmos299** [comment]
This isn't really a bug, but I did tag it.

**Comment by binhn** [comment]
We might want a separate dockerfile for this purpose and add vi to that.
Could we also have a doc on how-to for those who are not familiar with Docker

**Comment by bcbrock** [comment]
If you are going to add an editor, please add an easy-to-use visual editor in addition to vi. Ideally it would be emacs, but that's quite a big package. How about nano?

**Comment by srderson** [comment]
The peer image is now based on openblockchain/baseimage and includes both vi and nano

**Comment by bcbrock** [comment]
Thanks Sheehan

**Comment by bmos299** [comment]
Thanks Sheehan.
