### ISSUE TITLE
Correct and clarify Setting up the development environment

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#842]
This url: 
https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devenv.md

has instructions for setting up the BlockChain development.  While working through the set up instructions, I noticed an error.   Additional notes for Windows users are required as well. 

I will attach an odt file within a zip file containing with suggested amendments highlighted in red.  Here is a summary:

1) One, and probably two, directory names are incorrect
2) Windows users need to execute Vagrant commands from a Unix shell, and yet the page doesn't mention this hard requirement.  I suggest placements for this note. 
3) Windows users have the option of installing a Unix shell when installing the git client.  I suggest a note to add to help Windows users. 
4) Bootstrapping the VM using Vagrant works better than 'Boostrapping' the VM.  I shouted 'Boo' at my laptop for half an hour and it didn't do a darn thing!

[Correct and clarify Setting up the development environment.zip](https://github.com/openblockchain/obc-peer/files/178798/Correct.and.clarify.Setting.up.the.development.environment.zip)

**Comment by madhvesh** [comment]
Is the location of zip still valid? I am trying to setup on windows10 and when I run ./peer peer it fails

21:24:16.511 [db] CreateDB -> ERRO 00b Error calling  os.MkdirAll for directory path [/var/hyperledger/production/db]: mkdir /var/hyperledger: permission denied
Error opening DB IO error: /var/hyperledger/production/db: No such file or directory

**Comment by jjjjibm** [comment]
Hi Madhvesh,
The team moved the peer from the openblockchain directory to the hyperledger directory.

You can find the new instructions here.
https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devenv.md

Some directory names have changed, but the errors I reported are still valid EXCEPT for this (dev seems to  have fixed the name when they updated the directory names):


vagrant ssh
Once inside the VM, you can find your WORKSPACE directory under /openchain and the obc-peer project under $GOPATH/src/github.com/openblockchain/obc-peer. Additional instructions describe how to build, run and test the Open Blockchain Peer project.

NOTE: Any time you git clone any of the projects in your Host's WORKSPACE, the update will be instantly available within the VM /openblockchain directory.        <<==== Probably /openchain; I haven't tried it yet.
