### ISSUE TITLE
Compilation Error in go unit tests

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#848]
Compilation error observed while performing unit tests on the below commit.

commit fa0d476
Merge: 23e1ac8 072954d
Author: jeffgarratt garratt.jeff@gmail.com
Date:   Fri Mar 18 19:15:48 2016 -0400
Merge pull request #847 from srderson/issues/776/utxo_add_env Add ENV to utxo dockerfile

After trace back, observed the same issue from the below commit. 

commit a2b53e9
Author: Jeff Garratt garratt.jeff@gmail.com
Date:   Fri Mar 18 17:11:25 2016 -0400
UTXO chaincode implementation.  Still need to test chaincode in dev mode.

_Below is the log file:_

```
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer$ go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/)
?       github.com/openblockchain/obc-peer      [no test files]
ok      github.com/openblockchain/obc-peer/events       2.032s
?       github.com/openblockchain/obc-peer/events/consumer      [no test files]
?       github.com/openblockchain/obc-peer/events/producer      [no test files]
?       github.com/openblockchain/obc-peer/examples/chaincode/go/map    [no test files]
# github.com/openblockchain/obc-peer/examples/chaincode/go/utxo/consensus
examples/chaincode/go/utxo/consensus/consensus_wrap.cxx:230:33: fatal error: bitcoin/consensus.hpp: No such file or directory
 #include <bitcoin/consensus.hpp>
                                 ^
compilation terminated.
```

**Comment by srderson** [comment]
Ooops, I missed this issue and opened issue #849. I updated the readme. When running the test cases, use

```
go test -timeout=20m $(go list github.com/openblockchain/obc-peer/... | grep -v /vendor/ | grep -v /examples/)
```
