### ISSUE TITLE
unstable chaincode with aufs - btrfs works better

### ISSUE THREAD

**Issue by joequant** [hyperledger-archives/fabric#855]
I'm having problems with chaincode in that when I follow the development instructions, I can't get the docker image to compile the chaincode reliably under aufs.  When I switch storage to btrfs, everything works pretty reliably.

**Comment by joequant** [comment]
This could be the result of bad memory.  Closing until it can be reproduced.

**Comment by jeremyeder** [comment]
Hey  @joequant  please consider device mapper docker graph driver -- as you know, POSIX matters.
