### ISSUE TITLE
Migrate code to Hyperledger github

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#860]
To change github organization, we need the modify references in GOPATH and IMPORT statements. This involves source code files, scripts and documents (obc-peer, obc-dev-env, obc-docs).

We need a script to change `openblockchain` to `hyperledger` where appropriate since not all instances of `openblockchain` can/should be modified.

Rerun all tests (unit and functional).

**Comment by corecode** [comment]
This may be helpful:
https://gist.github.com/jackspirou/61ce33574e9f411b8b4a

**Comment by christo4ferris** [comment]
seems like this could be closed @binhn
