### ISSUE TITLE
Security and Consensus bugs

### ISSUE THREAD

**Issue by itp4IBM** [hyperledger-archives/fabric#861]

**Comment by kchristidis** [comment]
@itp4IBM You'll need to be a bit more specific.

**Comment by itp4IBM** [comment]
When a peer is shut down and a new one is added the following message will appear:

18:02:23.888 [crypto] callECAReadCACertificate -> ERRO 020 [validator.vp] Failed requesting read certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.888 [crypto] getECACertificate -> ERRO 021 [validator.vp] Failed requesting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.888 [crypto] retrieveECACertsChain -> ERRO 022 [validator.vp] Failed getting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.888 [crypto] registerCryptoEngine -> ERRO 023 [validator.vp] Failed retrieveing ECA certs chain [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.888 [crypto] register -> ERRO 024 [validator.vp] Failed registering crypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.888 [crypto] register -> ERRO 025 Failed registering [vp]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
18:02:23.889 [crypto] RegisterValidator -> ERRO 026 Failed registering [vp]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
18:02:23.889 [crypto] NewPeerWithHandler -> ERRO 027 Failed registering validator [vp] with name [vp] [rpc error: code = 2 desc = "grpc: the client connection is closing"].
18:02:23.889 [main] serve -> CRIT 028 Failed creating new peer with handler rpc error: code = 2 desc = "grpc: the client connection is closing"

**Comment by tuand27613** [comment]
I see several possible configuration issues:
1. `client connection closing` point to the peer not communicating with the obcca server. Check your openchain.yml for the pki.*.paddr values and verify that they point to the obcca hostname
2. `failed registering [vp]`. The validating peers should be named vp0,1,2,3  with no gaps in the sequence, e.g. you cannot have a set [vp0, vp2,vp3]

**Comment by srderson** [comment]
Closing as configuration issue.
