### ISSUE TITLE
Is this a configuration issue ? Deploying a chaincode when security enabled fails

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#864]
with following error messages:

21:11:35.733 [crypto] loadPublicKey -> ERRO 327 [client.test_vp5] Failed loading public key [chain.key]: [open /var/openchain/production/crypto/client/test_vp5/ks/raw/chain.key: no such file or directory].
21:11:35.733 [crypto] loadEnrollmentChainKey -> ERRO 328 [client.test_vp5] Failed load enrollment chain key: [open /var/openchain/production/crypto/client/test_vp5/ks/raw/chain.key: no such file or directory]
21:11:35.733 [crypto] init -> ERRO 329 [client.test_vp5] Failed initiliazing crypto engine [open /var/openchain/production/crypto/client/test_vp5/ks/raw/chain.key: no such file or directory].
21:11:35.733 [crypto] Deploy -> ERRO 32a Failed client initialization [test_vp5]: [open /var/openchain/production/crypto/client/test_vp5/ks/raw/chain.key: no such file or directory].
21:11:35.733 [rest] Deploy -> ERRO 32b {"Error": "Deploying Chaincode -- open /var/openchain/production/crypto/client/test_vp5/ks/raw/chain.key: no such file or directory"}

Have enabled security and privacy in openchain.yaml.

Are there any other configurations that I have to set for deploy to find chain.key for a given user?

**Comment by 2016Nishi** [comment]
Had to set "addressAutoDetect: true" inside openchain.yaml file.

Is this a recent change in configuration? for I do not remember changing "addressAutoDetect" earlier when I tested with security using SoapUI/Postman.

**Comment by 2016Nishi** [comment]
This happens when I launch a single stand alone peer inside vagrant. This behavior does not happen when the peer is running inside a docker container.

**Comment by bmos299** [comment]
This is not occurring for @itp4ibm.

**Comment by ibmmark** [comment]
@2016Nishi can this issue be closed ?

**Comment by 2016Nishi** [comment]
Tested on latest code base. Was able to launch a peer in secure mode and send Deploy/Invoke?Query requests successfully using obcsdk.

**Comment by 2016Nishi** [comment]
Build-ID: 82edde7f1951df593654bda45a1cb4303075fc6a
