### ISSUE TITLE
Decrypt/parse transacrion  payload

### ISSUE THREAD

**Issue by SECVBulRep** [hyperledger-archives/fabric#865]
How to decrypt field "payload"  received by http://localhost:5000/transactions/_id_ ?

thanks

**Comment by genggjh** [comment]
@secvbulrep: this issue has been closed by you without any comments. I want to know if you got the solution because I have similar concerns.

**Comment by hengyicai** [comment]
I have the similar problem with the decrypt of payload received by call `transactionInfoInstance.getEnvelope().getPayload()`.
