### ISSUE TITLE
Deploy function for chaincodeexample02  deploying inspite of passing incorrect number of args

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#874]
Could deploy successfully with 5 set of arguments something like
{"a", "100", "b", "200", "2000}
or
{"a", "100", "b"}

eg: deploy PayLoad

{
"type": "GOLANG",
        "chaincodeID": {
                "path":"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
},
"ctorMsg": {
        "function": "init",
        "args": {"a", "100", "b"}
},
"secureContext":"test_vp5"
}

After:  http://127.0.0.1:3000/devops/deploy using payload above

Actual Result:
{"OK": "Successfully deployed chainCode.","message":"171a782b682b8318742f5f7827e93a1c830059be550d10428490639b664c2b607456a93b89140f215d6bc16061713624a5c94875ad9c212d8ca1322a23a4b082"}
Subsequent queries on "a" and "b" do fail.

Expected  Result:

Expected the chaincode not let this happen and inform the user that he/she is passing wrong number of arguments.

**Comment by muralisrini** [comment]
@2016Nishi : when you "deploy" all that a success tells you is the deploy transaction was "submitted" successfully ... the chaincode has not executed the "init" func at that point,

**Comment by ibmmark** [comment]
@2016Nishi can we close this?

**Comment by 2016Nishi** [comment]
Closing as per comments from @muralisrini
