### ISSUE TITLE
we need the shim to provide the transaction timestamp to the contract

### ISSUE THREAD

**Issue by kletkeman** [hyperledger-archives/fabric#875]
In our domain, timestamps at the nano level are critical to sorting out the history of events relating to an asset. This in fact is equally important in any domain, even finance. You must know the time at which something was signed.

Currently, our contract generates timestamps when the event does not carry one, but on today's interlock call with @mastersingh24, we confirmed that we will _never_ achieve consensus in a network with actual consensus running because the state can not converge on one timestamp unless it comes in in the transaction. We absolutely cannot assume that we can force every application and device in the entire world to send timestamps, so we are suddenly very stuck.

After some discussion of messy front ends to inject timestamps, Gari suggested that the transaction already has a timestamp that is generated at the moment of initial creation and then forever propagated, and that contracts should be asking the shim for that timestamp in order to have something to define the time accurately. Since the transaction is propagated, every peer will get the same txn time if this is implemented.

This issue is as high a priority as we can imagine. We cannot run on pbft with timestamps generated inside the contract, but we must have timestamps. 

Since the transaction UUID is already available in the stub:

// ChaincodeStub for shim side handling.
type ChaincodeStub struct {
    UUID string
}

May we please get the transaction timestamp in there as well? 

Edit: Note that the timestamp we need is defined in [3.1.2.1 Transaction Data Structure](https://github.com/hyperledger/fabric/blob/master/docs/protocol-spec.md#3121-transaction-data-structure).

**Comment by corecode** [comment]
Timestamp service is important, and we're currently working on a principled design.

Using a timestamp provided by the transaction is possible, but do keep in mind that the timestamp supplied is as unreliably and untrustworthy as the party submitting the transaction is.

As a quick workaround, you could add a timestamp parameter to your `invoke` method.  Whoever submits this transaction may cheat, however, and provide an incorrect time.

**Comment by kletkeman** [comment]
We already have a timestamp parameter on our invokes. But we cannot force people to use it properly, which mitigates the value almost to the point of being useless. 

I'm not sure what you mean when you say "timestamp service" and how that would be different from the invoke's understanding of its invoke time, which must exist somewhere in the peer and be both propagated to the fabric and accessible to the shim (perhaps with a bit of work.) 

Could you comment on what I am missing with my presumptions? Thx.

**Comment by corecode** [comment]
You say that an invoke carries its own invoke time, but this time is as unreliable as the timestamp parameter to the invoke.  A defective or malicious node can still enter a wrong time in the invoke timestamp field.

**Comment by kletkeman** [comment]
Yes, I understand that. But if the node is defective and the timestamps are wrong, then they are all consistently wrong. And if you have a timestamp service that, say, propagates the current time through the network periodically, you still have that same problem. The node could still be defective. 

And you can't use a central timestamp service because it would violate one of the greatest strengths of a peer network, which is the resiliency in the face of network path interruptions. A peer needs to stand alone for the resiliency to work.

So what are you suggesting we do as an alternative if we can't get access to the timestamp that goes into the transaction (which is the only one that can work with real consensus we are told)?

**Comment by kletkeman** [comment]
Oops ... I meant to say that you cannot use a central timestamp service that is polled in real time as dependencies like that would mitigate resiliency.

It strikes me that peers should be checking each others' timestamps as well ... they would be able to estimate transit time and so would know if there were a major issue and force the non-conforming peer to update itself (from one of the many time services out in the world.)

Anyway, we could really use a viable alternative ... thx

**Comment by corecode** [comment]
Time needs to be a fundamental part of the network, and we're working on it.  Until this is available, I suggest using a timestamp parameter and assuming that the timestamp is correct.  This is not worse than using the invoke timestamp (if you could), because the invoke timestamp is not checked for correctness either.

**Comment by kletkeman** [comment]
Yes, we already are asking every client to pass timestamps. 

I would prefer, though to store a system timestamp as well so that we could get consistency and trust into the time. I agree that we need to wait until the peer network's own concept of time is reliable. (As in, I think you are telling me that the existing timestamp mechanism is inherently unreliable and that you will be making it reliable at some point in the future.)

The client timestamp is useful for documentary purpose, and the system timestamp is useful for ordering of events, which helps with lightweight analytical work.

If I may clarify the part I am not quite understanding yet: Since the peer network timestamps are the safest way to get a reasonable system time, and since these can only improve with time, why is it that the shim cannot grant us access? That way we can get the best of both worlds and still pass consensus with the only caveat that the time is inherently unreliable today (but still better than time passed from devices) and that it will improve over time.

**Comment by corecode** [comment]
I think this is a reasonable request.  Let's define an API call to "get recent timestamp", and for now the chaincode support can return whatever timestamp is in the transaction (if there is one - I don't know).  Later on, this call will return a correct (and not just consistent) time.

What do you think, @muralisrini?

**Comment by kletkeman** [comment]
Thanks. That sounds great. 

A thought on the name -- would getTxnTimestamp be better for self-documentation? As in the timestamp has to the one that is propagated so that state created on other peers is consistent and I think most people like me (as in not steeped in the internals of the peer) would presume that the transaction always knows its timestamp. 

And of course until there is a perfectly reliable timestamp, time.Now() is much better than nothing so long as it gets propagated and all peers give the same timestamp to the caller.

**Comment by corecode** [comment]
`time.Now()` is absolutely not guaranteed to provide the same time to the caller.  I don't think that all transactions finally will contain a valid (and verified) timestamp.  The reason I call it "get recent timestamp" instead of "get current timestamp" is that "current" implies now, while "recent" would describe the nature of the timestamp you obtain more correctly.

Could you explain what you intend to do when knowing the current time?

**Comment by kletkeman** [comment]
Hmmm ... so a transaction can be written into a block and only the block is timestamped. That makes sense for the needs of the fabric.

To answer your question, we need to know and especially prove that a certain event happened at a certain time, or at least that we received it at a specific time. We cannot rely on the device itself to do that, and there will be no consistency between devices in various parts of the world anyway. So as I mentioned, a system time would be very useful even with caveats.

Once we have that, we can offer secondary features like lightweight analytics. The example I've used before is a contract violation for an OVERTEMP, which leads to inspection on arrival and penalty for spoiled goods. 

The penalized party will have a monitor application that can poll the contract for the history in a certain time range for the asset that was violated. We use the **system** timestamps to grab an accurate range, and to allow for accurate correlation of location to event.)

I do understand that there are all sorts of issues possible, but we'll still do better with transaction based time.Now() being propagated along with the txn than with any solution that relies on all the devices that generate events through the invoke. We can inform early adopters that peer time might not be perfect and as that reliability will improve over time (no pun intended.)

**Comment by binhn** [comment]
@muralisrini We have the chaincode context now, so we should decide on what useful metadata from the tx should go into the context when calling the chaincode.

**Comment by binhn** [comment]
@kletkeman I implemented this in pull request #1317

**Comment by corecode** [comment]
Related #1321

**Comment by kletkeman** [comment]
@binhn : That's awesome :-)
