### ISSUE TITLE
With Security Enabled: Query after deployment is timing out and failed to fetch value

### ISSUE THREAD

**Issue by 2016Nishi** [hyperledger-archives/fabric#876]
deploy PayLoad

{
"type": "GOLANG",
        "chaincodeID": {
                "path":"github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example02"
},
"ctorMsg": {
        "function": "init",
        "args": ["c","10000","d","40000"]
},
"secureContext":"test_vp5"
}

{"OK": "Successfully deployed chainCode.","message":"b92168d03b6c7953499ec01aafa24baf52afced44dd6ae4c1290a19e80b1216179e91a11c0d6f4bdc39ba05d355b0da144eaeaf11e57ba06c68dbf6ac9561303"}

Query PayLoad

{"chaincodeSpec":
{
"type": "GOLANG",
        "chaincodeID": {
                "name":"b92168d03b6c7953499ec01aafa24baf52afced44dd6ae4c1290a19e80b1216179e91a11c0d6f4bdc39ba05d355b0da144eaeaf11e57ba06c68dbf6ac9561303"
},
"ctorMsg": {
        "function": "query",
        "args": ["c"]
},
"secureContext":"test_vp5"
}
}

Had time.Sleep(40000 \* time.Millisecond); in between deploy and query.
## Expected Result:

{"OK":"10000"}
## Actual Result:

{"Error": "Error:Failed to execute transaction or query(Timeout expired while executing transaction)"}
## Messages on Obc-Peer:

14:51:28.708 [chaincode] processStream -> ERRO 9e6 [cecc13cd]Error handling message, ending stream: [cecc13cd-439f-446f-9be1-4c8d31c796d6]Chaincode handler validator FSM cannot handle message (ERROR) with payload size (134) while in state: ready
14:51:28.708 [chaincode] deregisterHandler -> DEBU 9e7 Deregister handler: b92168d03b6c7953499ec01aafa24baf52afced44dd6ae4c1290a19e80b1216179e91a11c0d6f4bdc39ba05d355b0da144eaeaf11e57ba06c68dbf6ac9561303
14:51:28.708 [chaincode] deregisterHandler -> DEBU 9e8 Deregistered handler with key: b92168d03b6c7953499ec01aafa24baf52afced44dd6ae4c1290a19e80b1216179e91a11c0d6f4bdc39ba05d355b0da144eaeaf11e57ba06c68dbf6ac9561303
14:51:58.705 [consensus/handler] SendMessage -> DEBU 9e9 Sending to stream a message of type: RESPONSE
14:51:58.705 [peer] SendMessage -> DEBU 9ea Sending message to stream of type: RESPONSE
14:51:58.706 [peer] handleChat -> DEBU 9eb Received EOF, ending Chat
14:51:58.707 [peer] func1 -> DEBU 9ec Received RESPONSE message as expected, will wait for EOF
14:51:58.707 [peer] func1 -> DEBU 9ed Received EOF
14:51:58.708 [CRYPTO] closeClientInternal -> INFO 9ee Closing client [test_vp5]...
14:51:58.708 [CRYPTO.client.test_vp5] close -> INFO 9ef Closing keystore...
14:51:58.709 [CRYPTO.client.test_vp5] close -> INFO 9f0 Closing keystore...done!
14:51:58.710 [CRYPTO] closeClientInternal -> INFO 9f1 Closing client [test_vp5]...done! [<clean>].
14:51:58.711 [rest] Query -> ERRO 9f2 {"Error": "Querying Chaincode -- Error:Failed to execute transaction or query(Timeout expired while executing transaction)"}

P.S. It happened with other set of arguments as well. 
       Sending a query after 5min from SoapUI resulted in
14:55:20.614 [chaincode] processStream -> ERRO a5f [5f19ade6]Error handling message, ending stream: [5f19ade6-9624-42a1-906e-341091e02bd7]Chaincode handler validator FSM cannot handle message (ERROR) with payload size (134) while in state: ready

Since nothing is propagated to end user if arguments are invalid, it is difficult to trace cause of the problem as end user deploying and querying on a result.

Build: 
53a58acdde81f1ba0e45d30b5a47b9458fe0afdc
Thanks!

**Comment by bmos299** [comment]
Discussed with @2016Nishi
