### ISSUE TITLE
Deploy failed with EOF when obc-peer server down

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#878]
I ran obcpeer-test (Nishi's new tool) without starting the obc-peer server to see what would happen.
Incidentally, I did not start the security server either.

the first error is in deploy.  I got this result:

CallChainCode02:
http://127.0.0.1:3000/devops/deploy
2016/03/25 11:28:58 Error http://127.0.0.1:3000/devops/deploy Post http://127.0.0.1:3000/devops/deploy: EOF
Post http://127.0.0.1:3000/devops/deploy: EOF
Error in unmarshalling
From Deploy test  <nil>

'EOF' doesn't say 'Your remote server is not accepting connections' or 'Error contacting server' to me.

Can this message be improved?

**Comment by bmos299** [comment]
@jjjjibm please talk to @2016Nishi about this.
