### ISSUE TITLE
obc panic and grpc timeout with pbft consensus

### ISSUE THREAD

**Issue by dongmingh** [hyperledger-archives/fabric#879]
commit f08ccce33b13f23eb1af97a43bf654aa48129794
Merge: ab0e167 bfecc0f
Author: tuand27613 tdang@us.ibm.com
Date:   Thu Mar 24 17:30:24 2016 -0400

```
Merge pull request #833 from jyellick/executor-split

obcpbft Executor split
```

Running PBFT consensus, security and privacy enabled, 4 docker containers,  invoke requests with threads = 100.  

Steps to recreate:
1. bring up 4 docker containers
2. login as lukas
3. deploy example02
4. issue single query and invoke transactions and confirm that the responses are correct
5. use SoapUI to generate invoke transactions with 100 threads
Then vp0 and vp3 have panic and vp1 and vp2 have grpc timeout.  See logs below.

vp0 has panic:
20:03:26.325 [consensus/obcpbft] Execute -> ERRO 002 name:"vp0"  error queueing request (queue full) for sequence number 72
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x9e7a82]

goroutine 51 [running]:
panic(0xcd2c00, 0xc820010090)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(_obcExecutor).execute(0xc8203d5440, 0xc82861bbf0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:477 +0x82
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(_obcExecutor).queueThread(0xc8203d5440)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:301 +0x13ef
created by github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.NewOBCExecutor
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:108 +0x5d4

vp1 has gRPC timeout:
20:03:26.723 [peer] handleChat -> ERRO 003 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
2016/03/25 20:03:26 transport: http2Client.notifyError got notified that the client transport was broken read tcp 172.17.0.3:32922->172.17.0.2:30303: read: connection reset by peer.
2016/03/25 20:03:27 grpc: ClientConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.17.0.2:30303: getsockopt: connection refused"; Reconnecting to "172.17.0.2:30303"
2016/03/25 20:03:29 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
20:03:30.725 [peer] chatWithPeer -> ERRO 004 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
2016/03/25 20:03:33 transport: http2Client.notifyError got notified that the client transport was broken EOF.
20:03:33.534 [peer] handleChat -> ERRO 005 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
20:03:34.726 [peer] chatWithPeer -> ERRO 006 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
2016/03/25 20:03:36 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
20:03:37.549 [peer] chatWithPeer -> ERRO 007 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:38.732 [peer] chatWithPeer -> ERRO 008 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:41.552 [peer] chatWithPeer -> ERRO 009 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:42.735 [peer] chatWithPeer -> ERRO 00a Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:45.554 [peer] chatWithPeer -> ERRO 00b Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:46.737 [peer] chatWithPeer -> ERRO 00c Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:49.556 [peer] chatWithPeer -> ERRO 00d Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:50.739 [peer] chatWithPeer -> ERRO 00e Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:53.558 [peer] chatWithPeer -> ERRO 00f Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:54.740 [peer] chatWithPeer -> ERRO 010 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:57.559 [peer] chatWithPeer -> ERRO 011 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:58.742 [peer] chatWithPeer -> ERRO 012 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:04:01.560 [peer] chatWithPeer -> ERRO 013 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:04:02.756 [peer] chatWithPeer -> ERRO 014 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
2016/03/25 20:04:04 transport: http2Client.notifyError got notified that the client transport was broken EOF.
20:04:04.190 [peer] handleChat -> ERRO 015 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
20:04:04.191 [peer] handleChat -> ERRO 016 Error during Chat, stopping handler: connection error: desc = "transport is closing"
20:04:05.564 [peer] chatWithPeer -> ERRO 017 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect

vp2 gRPC timeout:
20:03:26.727 [peer] handleChat -> ERRO 005 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
2016/03/25 20:03:29 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
20:03:30.729 [peer] chatWithPeer -> ERRO 006 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
2016/03/25 20:03:33 transport: http2Client.notifyError got notified that the client transport was broken EOF.
20:03:33.556 [peer] handleChat -> ERRO 007 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
20:03:33.556 [peer] handleChat -> ERRO 008 Error during Chat, stopping handler: connection error: desc = "transport is closing"
2016/03/25 20:03:33 transport: http2Client.notifyError got notified that the client transport was broken EOF.
20:03:33.557 [peer] handleChat -> ERRO 009 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
20:03:34.730 [peer] chatWithPeer -> ERRO 00a Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
2016/03/25 20:03:36 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
2016/03/25 20:03:36 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
20:03:37.557 [peer] chatWithPeer -> ERRO 00b Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:37.559 [peer] chatWithPeer -> ERRO 00c Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:38.736 [peer] chatWithPeer -> ERRO 00d Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:41.559 [peer] chatWithPeer -> ERRO 00e Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:41.565 [peer] chatWithPeer -> ERRO 00f Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:42.739 [peer] chatWithPeer -> ERRO 010 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:45.561 [peer] chatWithPeer -> ERRO 011 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:45.570 [peer] chatWithPeer -> ERRO 012 Error creating connection to peer address=172.17.0.5:30303:  grpc: timed out trying to connect
20:03:46.742 [peer] chatWithPeer -> ERRO 013 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect

vp3 panic:
20:02:47.979 [ledger] sendProducerBlockEvent -> ERRO 003 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
2016/03/25 20:03:26 transport: http2Client.notifyError got notified that the client transport was broken read tcp 172.17.0.5:43904->172.17.0.2:30303: read: connection reset by peer.
20:03:26.726 [peer] handleChat -> ERRO 004 Error during Chat, stopping handler: rpc error: code = 13 desc = "transport is closing"
2016/03/25 20:03:29 grpc: ClientConn.transportMonitor exits due to: grpc: timed out trying to connect
20:03:30.728 [peer] chatWithPeer -> ERRO 005 Error creating connection to peer address=172.17.0.2:30303:  grpc: timed out trying to connect
20:03:33.455 [consensus/obcpbft] Execute -> ERRO 006 name:"vp3"  error queueing request (queue full) for sequence number 172
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x9e7a82]

goroutine 33 [running]:
panic(0xcd2c00, 0xc820010090)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(_obcExecutor).execute(0xc8203e2a20, 0xc8259917a0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:477 +0x82
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.(_obcExecutor).queueThread(0xc8203e2a20)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:301 +0x13ef
created by github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.NewOBCExecutor
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-executor.go:108 +0x5d4

**Comment by bcbrock** [comment]
I'm seeing this as well. 4 docker-compose peers, classic PBFT, no security, 1 client thread sending 1000 transactions to a simple chaincode.

**Comment by jyellick** [comment]
I've submitted a PR to fix this crash.  However, the fact that you are witnessing it makes me wonder if your configuration was entirely consistent.  There are three values in the obcpbft `config.yaml`, `general.K`, which defaults to 10, and `general.logmultiplier` which defaults to 2, and `executor.queuesize` which defaults to 30.  It's documented in the comment for `queuesize`, but this value should always exceed the log size `K * logmultiplier`.  So, if you had modified the values of `K` or `logmultiplier`, the `queuesize` should also be adjusted.

If you were witnessing this error with no modification fo `K` or `logmultiplier` then I will try to investigate more as to why, as this error should not have arisen with the default configuration.

This is something that intuitively makes sense to be derived, rather than configured, but as execution and ordering become independent services, the derivation will not be possible, so it was not implemented like that.  The PR above does however add an error to the log when this sort of misconfiguration is detected to speed up diagnosis.

**Comment by bcbrock** [comment]
@jyellick, I have not modified any of the defaults in any of my yaml files. The only modification I have made to the code I'm running is to comment out the line in main.go that limits GOMAXPROCS to 2.

**Comment by bcbrock** [comment]
I can't say whether this is fixed or not for me -  all of my runs with Classic PBFT continue to fail with #906 after the code update.

**Comment by dongmingh** [comment]
I tested the code pull today which includes the fix of this bug, see git log below, and do not see the panic and gRPC timeout.

commit 6ef721d1ad93c786db37ae6ee44cd2623dfca1d8
Merge: 0b3f7b1 ba5fffe
Author: Sheehan Anderson sranderson@gmail.com
Date:   Wed Mar 30 18:28:33 2016 -0400

```
Merge pull request #914 from muralisrini/convert_lang_to_upper_/issue#912

convert chaincode lang arg toupper
```

commit ba5fffea030d3a6096fd342c4544133900843ae6
Author: Srinivasan Muralidharan muralisr@us.ibm.com
Date:   Wed Mar 30 18:24:48 2016 -0400

```
convert chaincode lang arg toupper
```

commit 0b3f7b144d80016e92c4c26fbc613caa4ccee534
Merge: be2cdde c14b3b4
Author: tuand27613 tdang@us.ibm.com
Date:   Wed Mar 30 16:41:05 2016 -0400

```
Merge pull request #909 from jyellick/nil-execinfo-fix

Nil execinfo fix for issue #879
```

**Comment by tuand27613** [comment]
@dongmingh try a few more runs just to be sure.  Up to you when to close the issue.

@bcbrock , pls open a separate issue if you run into this again later.

**Comment by tuand27613** [comment]
whoops, hit the wrong comment button !

**Comment by dongmingh** [comment]
I observed a different issue this afternoon: queue full.  This is seen with invoke transactions, not for query.

20:12:50.480 [ledger] sendProducerBlockEvent -> ERRO 001 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
20:13:42.216 [consensus/obcpbft] Execute -> ERRO 002 name:"vp0"  error queueing request (queue full) for sequence number 78
20:13:42.223 [consensus/obcpbft] Execute -> ERRO 003 name:"vp0"  error queueing request (queue full) for sequence number 79
20:13:51.093 [consensus/statetransfer] stateThread -> ERRO 004 name:"vp0"  could not retrieve blocks as recent as 80 as the block hash advertised

**Comment by dongmingh** [comment]
I open bug #920 to track the issue of queue full.

**Comment by jyellick** [comment]
@dongmingh Mind if I close this since the original issue has been fixed?

**Comment by jyellick** [comment]
@dongmingh Can this be closed?

**Comment by jyellick** [comment]
Per agreement in slack, closing.
