### ISSUE TITLE
Unable to invoke/query another chaincode

### ISSUE THREAD

**Issue by rilaaax** [hyperledger-archives/fabric#882]
I tried to invoke/query another chaincode as shown in examples:
`github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example04`
and
`github.com/openblockchain/obc-peer/openchain/example/chaincode/chaincode_example05`

In both cases it doesn't work. I also tried to do it with my own chaincodes but I get the same problem.

Does anyone know what's wrong with these features?

Thanks.

**Comment by muralisrini** [comment]
@rilaaax : 
Unit test executetransactions_test.go excercises chaincode_example04 and chaincode_example05. 
If they run successfully then there's probably its user error of some sort. If they didn't, I'd check to make sure chaincode_example02 is not modified and chaincode_example02/ contains only chaincode_example02.go (if something is modified, the chaincode name will change. You'll have to use the deployed name). To test them
- cd $GOPATH/src/github.com/openblockchain/obc-peer/openchain/chaincode
- go test -run ChaincodeInvokeChaincode
- go test -rub ChaincodeQueryChaincode

Somethings to check
- is chaincode_example02 deployed and running ?
- are you running in --peer-chaincodedev mode ? This is ok but you have to uniformly use the name you provided to start  chaincode_example02

**Comment by rilaaax** [comment]
@muralisrini:
I tried the first test and it seems that it worked fine (my console looked like Matrix)... But the goal is just to do a simple test by myself to see how it works and use these features in other chaincodes. And when I try to do it I get an error.

To be more precise I will explain my process, using `chaincode_example05` which (if I well understood the chaincode) query `chaincode_example02` upon invoke and computes `a` and `b` to store it in `sum` state.

(I have a peer running in `--peer-chaincodedev` mode and security enabled running the CA server)

First I set up `chaincode_example02`:
`OPENCHAIN_CHAINCODE_ID_NAME=cc_ex02 OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 ./example02`
then I deploy it:
`./obc-peer chaincode deploy -u jim -n cc_ex02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'`
and I get:
`[cc_ex02]Received INIT, initializing chaincode
Aval = 100, Bval = 200`

In the same way for `chaincode_example05`:
`OPENCHAIN_CHAINCODE_ID_NAME=cc_ex05 OPENCHAIN_PEER_ADDRESS=0.0.0.0:30303 ./example05`
then I deploy it:
`./obc-peer chaincode deploy -u jim -n cc_ex05 -c '{"Function":"init", "Args": ["sum", "0"]}'`
and I get:
`[cc_ex05]Received INIT, initializing chaincode
sumVal = 0`

So far all is ok!

Now when I try to invoke the `invoke`function in `cc_ex05` which query `cc_ex02`'s `a` and `b` states and do the compute:
`./obc-peer chaincode invoke -u jim -l golang -n cc_ex05 -c '{"Function": "invoke", "Args": ["cc_ex02", "sum"]}'`

I get an error:
[CONSOLE] `cc_ex02`:
`2016/03/27 22:22:36 [e577f315]Received message QUERY from shim`
`2016/03/27 22:22:36 [e577f315]Handling ChaincodeMessage of type: QUERY(state:ready)`
`2016/03/27 22:22:36 [e577f315]Sending GET_STATE`
`2016/03/27 22:22:36 [e577f315]Received message ERROR from shim`
`2016/03/27 22:22:36 [e577f315]Handling ChaincodeMessage of type: ERROR(state:ready)`
`Error starting Simple chaincode: Error handling message: [e577f315-4428-49fa-ba12-f97cb2e91cbb]Chaincode handler FSM cannot handle message (ERROR) with payload size (82) while in state: ready`

[CONSOLE] `cc_ex05`:
`2016/03/27 22:22:36 [e577f315]Received message TRANSACTION from shim`
`2016/03/27 22:22:36 [e577f315]Handling ChaincodeMessage of type: TRANSACTION(state:ready)`
`2016/03/27 22:22:36 [e577f315]Received TRANSACTION, invoking transaction on chaincode(Src:ready, Dst:transaction)`
`2016/03/27 22:22:36 [e577f315]Sending INVOKE_QUERY`
`2016/03/27 22:23:06 [e577f315]Received message ERROR from shim`
`2016/03/27 22:23:06 [e577f315]Handling ChaincodeMessage of type: ERROR(state:transaction)`
`2016/03/27 22:23:06 [e577f315]before send`
`2016/03/27 22:23:06 [e577f315]after send`
`2016/03/27 22:23:06 [e577f315]Error received from validator ERROR, communicated(state:ready)`
`2016/03/27 22:23:06 [e577f315]Received ERROR.`
`Failed to query chaincode. Got error: Timeout expired while executing transaction`
`2016/03/27 22:23:06 [e577f315]Transaction execution failed. Sending ERROR`
`2016/03/27 22:23:06 [e577f315]Move state message ERROR`
`2016/03/27 22:23:06 [e577f315]Handling ChaincodeMessage of type: ERROR(state:ready)`
`Error starting Simple chaincode: Error handling message: [e577f315-4428-49fa-ba12-f97cb2e91cbb]Chaincode handler FSM cannot handle message (ERROR) with payload size (81) while in state: ready`

Sorry for this long post but I hope it will help you understand my concern.

Thank you again for your help!

**Comment by rilaaax** [comment]
See issue #905
