### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by xbh2015** [hyperledger-archives/fabric#883]
When I am running the chaincode in examples/chaincode/go/utxo using the docker run -it <image ID> /bin/bash command where id is just as follows b88cf78866ac , the execute output always says no such file or dictionary.However the docker images list shows that image ID was created.
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
utxo                           0.1.0               b88cf78866ac        3 hours ago         1.229 GB
So, I tried docker run -it utxo:0.1.0 /bin/bash.But it turned to root user like this root@5180875727c8:  and I can't cd the obc-peer for there is no github.com directory in $GOPATH/src/.
 I don't  know why.So if anybody encountered this problem, please tell me. 
Thank you

**Comment by RicHernandez2** [comment]
Are you running these docker images inside vagrant?  If so you need to ensure that this directory structure exists before running the vagrant up command, if you're running it outside of vagrant, keep in mind Docker is an incomplete VM that relies on the underlying OS to provide the missing pieces.

**Comment by xbh2015** [comment]
@RicHernandez2  
Yes, I just typed these commands through ssh to vagrant. Before typed docker run -it < image id> /bin/bash command, I followed all instructiongs showed in utxo/readme file. 
I also tried  docker run -it  image id  /bin/bash without <>,however it worked out the same as  docker run -it utxo:0.1.0 /bin/bash

**Comment by RicHernandez2** [comment]
Could you give me a link to these UTXO files you mention?  Give this one a try, if it's not updated by the time you get to the command line to start the docker images, please note that we always start at VP0-VPn-1 where n=the total number of VPs in the set.

https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devnet-setup.md

**Comment by xbh2015** [comment]
@RicHernandez2 
Thank you for your quick reply. The link to UTXO file is  https://github.com/openblockchain/obc-peer/tree/master/examples/chaincode/go/utxo .I just followed the readme.md file step by step. You mean that I should set up the network and then try to use docker to build image and deploy chaincode? I just use ./obc-peer peer command to start one node and then do those steps.

**Comment by RicHernandez2** [comment]
Use the commands in the devnet-setup.md, that should get you up and running, just remember the command line for bringing up the first VP should name it VP0 not VP1, if that error is still in the doc (merge pending) you'll have to adjust the command line manually.  But this doc will help you setup the environment, let us know if you have any questions!

**Comment by srderson** [comment]
@xbh2015 I think you're trying to use the `docker run -it <image> /bin/bash` with the wrong image. It's not the UTXO image that you want to run. It's the chaincode image built using the UTXO image as the base. This image was created after you ran the deploy command. The 'Repository' name should be something like `dev-jdoe-cbe6be7ed67931b9be2ce31dd833e523702378bef91b29917005f0eaa316b57e268e19696093d48b91076f1134cbf4b06afd78e6afd947133f43cb51bf40b0a4`

I believe you're right that you need to use the Repository name instead of the image ID. I'll fix the documentation.

**Comment by xbh2015** [comment]
@srderson 
Oh, I know the relationship between these two images. However after I executed deploy the example UTXO chaincode command which is: OPENCHAIN_PEER_ADDRESS=localhost:30303 ./obc-peer chaincode deploy -p github.com/openblockchain/obc-peer/examples/chaincode/go/utxo -c '{"Function":"init", "Args": []}' . There is nothing new image created. I also modified the openchain.yaml where 
          # from golang:1.5.1
            from utxo:0.1.0
under chaincode.golang.Dockerfile struct .I do not know why.

**Comment by xbh2015** [comment]
@RicHernandez2 @srderson 
Thank you for your useful reply. The problem is settled.I just update the version of obc-peer to the latest and then the problem disappeared.

**Comment by RicHernandez2** [comment]
:+1:   Happy Coding!
