### ISSUE TITLE
obc-peer stop command is not working

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#886]
I tried to stop obc-peer applying `obc-peer stop` command. After execute the command obc-peer status is showing as stopped when I execute

`obc-peer status` peer status is showing as `UNKNOWN` and 
`fuser -n tcp 5000` command resulting me that peer is still running. 

Attached snapshot of the error message.
![obc-peer status_stop](https://cloud.githubusercontent.com/assets/17034502/14110470/914a6782-f594-11e5-9729-26933848b9ba.PNG)

**Comment by srderson** [comment]
Resolved via PR #1141
