### ISSUE TITLE
utxo deploy failed

### ISSUE THREAD

**Issue by apollos** [hyperledger-archives/fabric#887]
I follow the example description of utxo but failed at the step " OPENCHAIN_PEER_ADDRESS=localhost:30303 ./obc-peer chaincode deploy -p github.com/openblockchain/obc-peer/examples/chaincode/go/utxo -c '{"Function":"init", "Args": []}'
".

First, I failed at 
23:33:50.804 [container] build -> ERRO 030 Error building Peer container: The command '/bin/sh -c go install github.com/openblockchain/obc-peer/examples/chaincode/go/utxo && cp src/github.com/openblockchain/obc-peer/openchain.yaml $GOPATH/bin && mv $GOPATH/bin/utxo $GOPATH/bin/b4e953ff2219e032eb75ccfc3e8aa75864416770794af11a7c55572842f12684e542db1165c60d3d0c3b0766ad0e95742af156350873a9cfcdf0c64d02b186fd' returned a non-zero code: 1

And then, I change the code of openchain/container/controller.go to bypass the go install part since I create a new image which has already build the utxo and install it to $GOPATH/bin. And I change the openchain.yaml to point the peer and chaincode image to my image.

After that, I still failed at 

00:15:07.508 [container] start -> DEBU 03c Start container dev-jdoe-b4e953ff2219e032eb75ccfc3e8aa75864416770794af11a7c55572842f12684e542db1165c60d3d0c3b0766ad0e95742af156350873a9cfcdf0c64d02b186fd
00:15:07.508 [container] createContainer -> DEBU 03d Create container: dev-jdoe-b4e953ff2219e032eb75ccfc3e8aa75864416770794af11a7c55572842f12684e542db1165c60d3d0c3b0766ad0e95742af156350873a9cfcdf0c64d02b186fd
00:15:07.609 [container] createContainer -> DEBU 03e Created container: dev-jdoe-b4e953ff2219e032eb75ccfc3e8aa75864416770794af11a7c55572842f12684e542db1165c60d3d0c3b0766ad0e95742af156350873a9cfcdf0c64d02b186fd
**00:15:07.977 [container] start -> ERRO 040 start-could not start container API error (500): Container command not found or does not exist.**

I do not understand the error. Is there any issue in my env? But my docker run well.

**Comment by srderson** [comment]
There have been many changes in this area since this was opened. Could you please try to reproduce in the current env and reopen if needed? Thanks.
