### ISSUE TITLE
Enable dynamic registration of users

### ISSUE THREAD

**Issue by dulcep** [hyperledger-archives/fabric#892]
At the moment users are registered at start up time by reading username/password from the configuration file.

**Comment by binhn** [comment]
@dulcep there's a gRPC API on the membership services that we need to document and provide usage sample code

**Comment by mastersingh24** [comment]
@binhn @dulcep  - I think we can close this one given the new client SDK

**Comment by smithbk** [comment]
Yes, this was completed with issue 1186.

**Comment by dulcep** [comment]
Yes, we will close this after #1801 is closed.

**Comment by christo4ferris** [comment]
closing per discussion thread ( #1801 was closed)
