### ISSUE TITLE
Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group

### ISSUE THREAD

**Issue by clydedacruz** [hyperledger-archives/fabric#900]
I get the following error after a deploy transaction on all 4 peer.But the docker container comes up successfully .
Note: I have consensus set to obcpbft classic , security is turned on and privacy is turned on .

```
00:15:03.163 [consensus/obcpbft] processNewView -> INFO 055 Replica 0 ignoring new-view from 3, v:3: we are active in view 3
00:15:05.991 [container] newDockerClient -> INFO 056 Creating VM with endpoint: unix:///var/run/docker.sock
00:15:06.322 [ledger] sendProducerBlockEvent -> ERRO 057 Error unmarshalling deployment transaction for block event: proto: protos.ChaincodeDeploymentSpec: wiretype end group for non-group
```

what could be the cause of this ?

**Comment by corecode** [comment]
please provide complete logs from all peers

**Comment by clydedacruz** [comment]
@corecode  I have attached below the logs on all 4 peers . Thanks.

[deploy3.txt](https://github.com/hyperledger/fabric/files/201779/deploy3.txt)
[deploy4.txt](https://github.com/hyperledger/fabric/files/201781/deploy4.txt)
[deploy1.txt](https://github.com/hyperledger/fabric/files/201780/deploy1.txt)
[deploy2.txt](https://github.com/hyperledger/fabric/files/201782/deploy2.txt)

**Comment by muralisrini** [comment]
@clydedacruz : this error occurs during event generation and is not related to consensus.  Should affect only event listeners.

**Comment by corecode** [comment]
@muralisrini do you understand how this happens?  I had a brief browse through the code, but couldn't figure out the flow of the message.

**Comment by adecaro** [comment]
@clydedacruz, #1204 seems a duplication of this. Shall we close this issue because the discussion is now on #1204?

**Comment by clydedacruz** [comment]
@adecaro  sure you can close it .
