### ISSUE TITLE
Failed to setup the dev env

### ISSUE THREAD

**Issue by jinfahua** [hyperledger-archives/fabric#901]
I'm trying to setup the dev env by following instruction in page https://github.com/openblockchain/obc-docs/blob/master/dev-setup/devenv.md 
But it kept failing in step '**Boostrapping the VM using Vagrant**' with following error message in console.

  0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0
==> default: curl: (7) Failed to connect to github-cloud.s3.amazonaws.com port 443: Connection timed out
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

When I ping the address print in the error log, it shows timeout...

ing github-cloud.s3.amazonaws.com
PING s3-1-w.amazonaws.com (54.231.14.233): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

Are there any work-around to solve the problem?

**Comment by srderson** [comment]
I'm able to ping those addresses. It looks like GitHub's Amazon servers are blocked on your network.

You could try commenting out lines 49, 52, and 53 in installGolang.sh
https://github.com/openblockchain/obc-dev-env/blob/master/installGolang.sh#L49
Those tools are not necessary for running OBC.

**Comment by ghaskins** [comment]
@srderson we should probably mask non-fatal errors with something like "optional.sh || /bin/true" for cases like above where the usefulness of the environment is not predicated on success.

**Comment by jinfahua** [comment]
@srderson Thanks, I finally setup the env successfully. But I'm not sure what will be impact if not installing with those software?

**Comment by srderson** [comment]
@jinfahua golint and goimports are tools we ask developers to run before making a PR to the OBC code. govendor is a tool needed for developers modifying OBC dependencies. They are not needed to run OBC or develop chaincode.

@ghaskins The more I see people encounter these types of issues, the more I think we should include everything possible in the atlas base image. It would likely solve these problems.

**Comment by ghaskins** [comment]
@srderson thats not a bad idea, especially if it qualifies as a) generally useful b) not controversial, and c) and not very large.

**Comment by jinfahua** [comment]
@srderson Thanks for your response.
