### ISSUE TITLE
where is merkle and sha256 in the obc-peer's code?

### ISSUE THREAD

**Issue by pangjiuzala** [hyperledger-archives/fabric#902]
I'm studying the source code of obc-peer, and trying to analysis the Merkle and SHA256 algorithm， I wonder that how it explains in the code

**Comment by srderson** [comment]
See https://github.com/openblockchain/obc-peer/tree/master/openchain/ledger/statemgmt. There are two implementations of the Merkle tree. Bucket tree and trie. You can configure which one is being used at https://github.com/openblockchain/obc-peer/blob/master/openchain.yaml#L345. The bucket tree is a fixed sized tree that groups the data in buckets at the leaf nodes.

The hashing of the Merkle tree is done using SHA3 SHAKE256. See https://github.com/openblockchain/obc-peer/blob/master/openchain/util/utils.go#L34. We could consider making this configurable so people could pick different hashing algorithms which may have better hardware acceleration support.

**Comment by pangjiuzala** [comment]
Thank's for your reply,I have founded  it
