### ISSUE TITLE
Error when query/invoke other chaincode with security enabled

### ISSUE THREAD

**Issue by rilaaax** [hyperledger-archives/fabric#905]
When trying to query/invoke another chaincode as shown in `chaincode_example04` and `chaincode_example05`, it returns an error when security enabled and CA running.

Some logs (test with `chaincode_example05`)
<img width="1280" alt="mycc log after invoke" src="https://cloud.githubusercontent.com/assets/17408950/14148201/e01b76d4-f69e-11e5-887d-ace916b7da67.png">
<img width="1280" alt="mycc2 log after invoke" src="https://cloud.githubusercontent.com/assets/17408950/14148202/e0492a5c-f69e-11e5-851c-0e9d2eebcd9f.png">
<img width="1280" alt="peer after mycc2 invoke 1 2" src="https://cloud.githubusercontent.com/assets/17408950/14148204/e04f5062-f69e-11e5-8f2f-d9d096c6b216.png">
<img width="1280" alt="peer after mycc2 invoke 2 2" src="https://cloud.githubusercontent.com/assets/17408950/14148203/e04e2b10-f69e-11e5-910d-4a307958daa5.png">

@muralisrini

**Comment by muralisrini** [comment]
had worked with @rilaaax on this. The issue happens with security/privacy enabled.

@rilaaax : should have checked... can you do one more test please - enable security but not privacy ? Thanks!

**Comment by rilaaax** [comment]
@muralisrini Test done.

 It works with security enabled and privacy disabled.

**Comment by muralisrini** [comment]
thanks @rilaaax

**Comment by wwendy** [comment]
@rilaaax i tried disabling privacy, security enabled, i got a lot of garbled state output.

**Comment by muralisrini** [comment]
@wwendy - once privacy is on data is encrypted on the ledger. One cannot switch back and forth between privacy and no privacy  (@adecaro to confirm/correct please).

To switch - in test or development phase of course - you could maintain different /var/hyperledger databases or simply rm -rf /var/hyperledger/\* (keep /var/hyperledger but delete everything under it).

**Comment by wwendy** [comment]
@muralisrini is it the directory /var/openchain/production/db for openblockchain dev env setup?

**Comment by muralisrini** [comment]
@wwendy : I assumed you are in hyperledger project.... (though the issue was opened under OBC). Further I assumed you are in vagrant environment. You should adjust the path based on your env.

**Comment by adecaro** [comment]
@rilaaax @muralisrini @wwendy is this still opened? Shall I check what's going on in the crypto layer?

**Comment by rilaaax** [comment]
@adecaro yeah still opened, you do well asking because I just tested again and now it does not work with security enabled not only privacy

**Comment by muralisrini** [comment]
@rilaaax @adecaro - I'm not sure about the recent problem with just security enabled.  However the original problem is that we are not dealing with context for encryption/decrytion on the called chaincode correctly when invoking chaincode from a chaincode,  So that part @adecaro is a chaincode issue. Think we know where the problem is but looking for the right solution.

@rilaaax ax: I didn't expect just security enabled  (with privacy disabled) to fail. One possibility is you might be using the old ledger which had privacy enabled ? Wonder if you could try it after "rm -rf /var/hyperledger/*" (if not already tried of course)

**Comment by rilaaax** [comment]
@muralisrini i did the `rm -rf /var/hyperledger/production` command before testing. Got the following error in peer log (security enabled / privacy disabled)
`09:22:54.740 [chaincode] func1 -> ERRO 227 [9c426996]Got error ([9c426996]transaction context is nil for uuid 9c426996-44e0-4df5-bfd7-858a40edfc63) while decrypting. Sending ERROR`

**Comment by rilaaax** [comment]
@muralisrini i did the `rm -rf /var/hyperledger/*` command before testing. Got the following error (security enabled / privacy disabled)
`09:41:12.633 [chaincode] func1 -> ERRO 227 [0cd73da1]Got error ([0cd73da1]transaction context is nil for uuid 0cd73da1-5167-42f6-90ad-d66b1f8d13fa) while decrypting. Sending ERROR`

Tested with all disabled and it is working fine.

**Comment by christo4ferris** [comment]
@rilaaax @muralisrini is this still an issue? If not, let's close it. Thanks

**Comment by muralisrini** [comment]
@christo4ferris Its a known limitation. C-C with privacy is being looked in detail for the New arch. This can be closed, I think. Agree, @rilaaax ?

**Comment by rilaaax** [comment]
@muralisrini I didn't test it recently but if you say it will be fixed soon we can close it. @christo4ferris

**Comment by christo4ferris** [comment]
closing per discussion
