### ISSUE TITLE
Allowing configuration to use SHA2

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#908]
Currently we only support SHA3 with configurable length. We need to also support SHA2, which can be configured as:

```
security:
    level: 256
        sha: 2
```

**Comment by andresgaragiola** [comment]
@binhn I'm working in this issue

**Comment by andresgaragiola** [comment]
@binhn After pull request #1148 this issue should be closed.

**Comment by binhn** [comment]
closed by PR 1148
