### ISSUE TITLE
Transaction UUID revealed in plaintext

### ISSUE THREAD

**Issue by itp4IBM** [hyperledger-archives/fabric#910]
A test was conducted on the encryption of transactions revealed that transaction UUIDs are transferred in plaintext. The adversary could use this transaction UUID from the deployment call to invoke transactions on a compromised system after a client has logged in. This could happen if a client's computer is infected with trojan horse where it captures log-in credentials.

**Comment by itp4IBM** [comment]
The transaction ID returned from an invoke transaction could reveal the privacy of the transaction. In the invoke call, the parameters are ["sender", "recipient", "amount"]. Calling the REST API with /transactions/transactionID reveals all the parameters.  This could become a privacy concern.

**Comment by corecode** [comment]
Could you explain the adversary scenario?  Clearly a compromised system cannot be distinguished from a non-compromised system.

**Comment by itp4IBM** [comment]
On a compromised system, we may safely assume that the user's enrollIid and enrollsecret is known by the adversary. The adversary could substitute the field, "recipient" to his name and run the invoke call. Since the user is authenticated, the consensus will pass for this transaction.

Thank you.

**Comment by tuand27613** [comment]
@elli-androulaki   @adecaro your thoughts ?

**Comment by corecode** [comment]
@itp4IBM I don't understand the problem.  Could you please elaborate on the specific scenario, with a step-by-step list of (hypothetical) events?

**Comment by itp4IBM** [comment]
@corecode:
Suppose user Usr1 has logged in on his infected computer and then executes a "Deploy" call. The deployment returns a hash. This hash is the required string to later make Invoke/Query calls. The invoke call has fields, "a", "b", and "amount" where it allows the sender "a" to transfer to "b" an amount of "amount". The adversary then sets b = his name and amount = amount*X and call the Invoke function again. Since Usr1 is a legitimate user, validators in the network will authorize this transaction.

**Comment by corecode** [comment]
The chaincode should prevent transfers from `a` to any other account, if `a` did not authorize this transaction.  This is independent of the "name" (hash) of the chaincode (as returned by the deploy transaction).

**Comment by itp4IBM** [comment]
@corecode:
Please let me take a step back and clarify what I meant as transaction UUID. Are they allowed to be transferred in clear-text by design?
1. ChaincodeID, which is returned from the Deploy call.
2. Transaction ID, which is returned from the Invoke/Query call. 

I was informed that there is no Access Control in place to control who can execute the deploy, invoke, or query. So, that could be postponed for future discussion regarding transfers.

Angelo @adecaro has pointed out that we currently need to achieve IND-CPA. But IND-CCA/2 seems to be a desired property in such a scheme for the future.

Thank you.

**Comment by adecaro** [comment]
Hi @itp4IBM, actually the Transaction UUID is supposed to be unique per transaction and independent from the content of the transaction itself. The ChaincodeID is, on the other hand, encrypted. 

Regarding access control, right now, there is support only for access control at chaincode level. There is an example on how to use it in the repo.

Regarding the security definition to be required for encryption, it really depends on the context. I would need to go case by case to give you a more precise answer.

**Comment by adecaro** [comment]
@itp4IBM, may we close this issue?

**Comment by ibmmark** [comment]
@itp4IBM ... Hi, are you ok if we close this one, per @adecaro 's explanation above?

**Comment by itp4IBM** [comment]
Sure. Please go ahead and close the issue. Thank you.

**Comment by christo4ferris** [comment]
closing per discussion
