### ISSUE TITLE
Sieve with 4 validating peers - One peer never executes a single transaction

### ISSUE THREAD

**Issue by bcbrock** [hyperledger-archives/fabric#915]
I have set up a network of 4 validating peers running Sieve. I have deployed 4 chain codes to the network. I send several hundred transactions to each peer. One of the peers, which happens to be the last one created, was sent 1300 transactions which the logs show it has received and then forwarded on to "the validator".  However at the end of the run, it is clear from the chaincode logs that this peer has never executed a single transaction via any of its 4 chaincodes.

Is this expected? My expectation was that all peers should be independently executing every transaction, since they are all working correctly and the chain codes are deterministic.

**Comment by bcbrock** [comment]
@corecode @vukolic Could one of you please comment on this issue?

**Comment by corecode** [comment]
could you please provide DEBUG level logs for all 4 peers?

**Comment by bcbrock** [comment]
Thanks @corecode - Sorry for the delay, I have reduced the problem to reduce the log file size. Here there are 4 peers each managing 2 chain codes. In the tarball, vp[0-3]_logs/stderr are the peer logs, and dev-vp*_logs/stderr are the chaincode logs.

In this example, peer 1 (vp1) is the one that never executed a transaction. The run "fails" due to this fact.

[vplogs.tar.gz](https://github.com/openblockchain/obc-peer/files/198346/vplogs.tar.gz)

**Comment by corecode** [comment]
@jyellick I think this is because sieve now does not stop the pbft timer anymore; probably got lost in changes #833.  Could you verify my thoughts?

**Comment by jyellick** [comment]
@corecode This actually appears to be a race.  In order to not block waiting to acquire the pbft lock, which can cause a deadlock, you'll see in `Validate` that the timer is reset on a goroutine.  Invariably, the verify set arrives before this goroutine executes, and so the timer is not stopped as it should be.  If this happens to two nodes, then the view advances, and state transfer occurs, which is why the error is never observed in more than 2 replicas.

@bcbrock As I implement #919 I will do my best to eliminate much of the Sieve hacky cruft which accumulated in the #833 changeset.  Unless there are objections, I think this issue would be best addressed in the #919 work.

**Comment by corecode** [comment]
The goroutine starts the timer, and doesn't stop it.  I think once a decision comes out of `validResultChan`, the timer must be stopped.

**Comment by jyellick** [comment]
@corecode No, I don't think this is correct.  Looking at the changeset, and at older versions of Sieve, I don't believe Sieve has ever stopped that timer.  Instead, Sieve is using the PBFT timer, knowing that when a request executes, the timer will be stopped.  Here, the request is executing, stopping the timer _before_ the timer is started, which is the race.

**Comment by corecode** [comment]
This means that either we do not use goroutines, or we use separate timers for sieve and pbft.

**Comment by jyellick** [comment]
Yes, much of the goroutine gymnastics was required in order to return the message thread so that the peer could process state transfer messages.  Issue #919 will make this unnecessary, and should allow me to eliminate some of these goroutines, that is why I was suggesting we roll this fix into that work.

**Comment by mastersingh24** [comment]
@bcbrock - Sieve is not a high priority at this point.  The focus is on getting plain old PBFT hardened at this point.  

Of course if others in the community want to take a look, that's fine as well.

**Comment by corecode** [comment]
This most likely is resolved.  Additionally, you cannot expect all replicas to progress at the same rate; only 2f+1 out of 3f+1 are guaranteed to progress at all.

**Comment by bcbrock** [comment]
@corecode I agree I'm not seeing this anymore. Once I see some moderate stress tests with Sieve consistently passing w/o crashes I will close this.

@jyellick and I discussed the "2f+1 out of 3f+1" issue the other day. I understand that I may have to work around this at the moment. Although I appreciate the mathematical beauty of the "2f+1 out of 3f+1" invariant, if we tell a client that even if every piece of hardware, software and networking equipment is working perfectly, then there is no guarantee that his local peer is up-to-date, the client will consider this to be a bug, and I would agree with the client.

Consider how IBM describes our blockchain to the world: http://www.ibm.com/blockchain
We say

```
Entries in the ledger are synchronized to all ledgers in the network. Consensus is used to ensure all ledgers are exact copies.
```

We eventually need to get there.

**Comment by corecode** [comment]
In an asynchronous system where nodes can behave adversarial, the network cannot wait for stragglers.  The best we can do is a best effort to locally catch up with the network.

We need to define what kind of lagging behind is not acceptable, and then come up with a method to prevent these situations.

CC @vukolic @cca88

**Comment by vukolic** [comment]
All correct nodes need to make progress modulo network outages and asynchrony.

However, these nodes do not have to make progress simultaneously. In fact, the "exact" copies from the above quotation is not possible to achieve in a possibly asynchronous system with possible node faults. That said, truth is there are protocols which are better than PBFT in "keeping sync" when things do not go wrong. We will get to implementing these protocols at some point.

**Comment by bcbrock** [comment]
This issue seems to be fixed.
