### ISSUE TITLE
EnrollmentID and EnrollmentPWD are hardcoded in the obcca.yaml

### ISSUE THREAD

**Issue by genggjh** [hyperledger-archives/fabric#916]
The EnrollmentPWD is in plaintext in the obcca.yaml which will not pass our security check and not be accepted by our enduser.

And also the EnrollmentID list is hardcoded, we have to restart CA server once we need add new one.

We should provide API to support create new EnrollmentID with password at runtime.

**Comment by binhn** [comment]
@genggjh there's api to do that;  IDs in the yaml file is for testing conveniences. 
https://github.com/hyperledger/fabric/blob/master/docs/API/MemberSericesAPI.md

**Comment by genggjh** [comment]
@binhn, I knew this API, but it is still in gRPC layer, I think we should expose the REST API and cli.
