### ISSUE TITLE
PBFT Classic Consensus seems to keep changing views

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#917]
Description:

PBFT Classic seems to keep changing views, it went from view 4 to view 17 in a span of 10 minutes

Steps to repro:
1.  Setup pbft classic on a laptop
2.  Run Deploy, Query
3.  Run GO SDK tests

Results:

Primary logs have gone through 13 view changes in that time

Expected Results:

Primary and VPs should not be constantly changing views, as they are unable to process transactions when voting on a new primary (view change)

[vp0 View Mania.txt](https://github.com/openblockchain/obc-peer/files/197552/vp0.View.Mania.txt)

**Comment by corecode** [comment]
can you please supply a full log for all replicas?

**Comment by RicHernandez2** [comment]
I can't, I did this first thing in the morning and wiped my machine clean for the latest build, I'll lock my machine and see if I can repro the issue by unlocking it again after a few minutes.  The referenced closed bug has a larger chunk of the vp0 log.  I'll start getting into the habit of pulling all vp logs, now to see if I can nail down a solid repro.

**Comment by RicHernandez2** [comment]
Could not reproduce the issue, so I have no solid repro, I'll try again tomorrow.

**Comment by RicHernandez2** [comment]
Ok, I got a partial repro of this mornings bug while tracking down another bug.  Here are all the log files:

[vp0 viewmania 1 of 4.txt](https://github.com/openblockchain/obc-peer/files/198622/vp0.viewmania.1.of.4.txt)
[vp1 viewmania 2 of 4.txt](https://github.com/openblockchain/obc-peer/files/198620/vp1.viewmania.2.of.4.txt)
[vp2 viewmania 3 of 4.txt](https://github.com/openblockchain/obc-peer/files/198623/vp2.viewmania.3.of.4.txt)
[vp3 viewmania 4 of 4.txt](https://github.com/openblockchain/obc-peer/files/198621/vp3.viewmania.4.of.4.txt)

**Comment by corecode** [comment]
can you please attach the complete log files?  These are missing a lot on top.

**Comment by tuand27613** [comment]
@jyellick has potential fix. See #699

**Comment by jyellick** [comment]
@RicHernandez2 @tuand27613 PR #971 may fix this, but without complete logs, there is no way to tell.  The links to the partial logs seem to be broken, so reproducing complete logs would be great.  You may want to wait until the PR is merged before retesting however.
