### ISSUE TITLE
Go test -run BuildImage_Peer panics and fails when Consensus plugin set to &amp&amp&amp;

### ISSUE THREAD

**Issue by RicHernandez2** [hyperledger-archives/fabric#918]
Description:

Just ad-hoc testing while executing my "Default to noops when we don't understand the plugin name" test by putting in a malformed XML entity (Ampersand), and the entire build process ground to a halt.

Steps:
1.  Open openchain.yaml
2.  Edit consensus plugin to "&amp&amp&amp;"
3.  Save openchain.yaml
4.  Attempt to build obc-peer docker image

Results:

```
vagrant@vagrant-ubuntu-trusty-64:/opt/gopath/src/github.com/openblockchain/obc-peer/openchain/container$ go test -run BuildImage_Peer
panic: Fatal error config file: While parsing config: yaml: line 151: did not find expected alphabetic or numeric character


goroutine 1 [running]:
panic(0x98a6e0, 0xc82015eb00)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/openblockchain/obc-peer/openchain/container.SetupTestConfig()
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/container/config.go:70 +0x2c1
github.com/openblockchain/obc-peer/openchain/container.TestMain(0xc820125ee8)
        /opt/gopath/src/github.com/openblockchain/obc-peer/openchain/container/vm_test.go:35 +0x18
main.main()
        github.com/openblockchain/obc-peer/openchain/container/_test/_testmain.go:74 +0x114
exit status 2
FAIL    github.com/openblockchain/obc-peer/openchain/container  0.046s
```

Expected results:

System should build, not understanding the parameter for consensus plugin should result in Noops being used.

**Comment by corecode** [comment]
I disagree violently.  Incorrect settings should not be ignored.

**Comment by RicHernandez2** [comment]
But that's what we state in the .yaml file, isn't it?  That an unrecognized plugin results in Noops being used?  This exposes a bug in that if there were to be a future public OR private consensus plugin with symbols in the name, we run the risk that such a customer not even be able to build because there's a symbol in the name.  I know this test seems pedantic, just trying to make the system as bullet-proof as possible, IBM's customers deserve that.

**Comment by tuand27613** [comment]
isn't this a Viper/YAML issue ? I'll bet we fail if you put that string anywhere in openchain.yaml.

**Comment by RicHernandez2** [comment]
What about localization in other languages that might result in a non alpha-numeric characters?  Kanji for example?  Does viper not work with other languages?

If that's the case it's at least a good thing to be aware of... is there a flag for KB option?

**Comment by tuand27613** [comment]
everything in .yaml files is not text but  keywords which we restrict to specific strings which are never translated.

BuildImage_peer should fail a bit more gracefully though.

**Comment by christo4ferris** [comment]
Just reproduced with https://github.com/hyperledger/fabric/commit/ee024d56f1a42b9eda2902f45099695608ca7634

**Comment by christo4ferris** [comment]
basically, further investigation reveals this is working as designed... could be more graceful means of exiting, I agree but closing.
