### ISSUE TITLE
Non-Validating peer is not able to send a successful DISC_HELLO with security enabled

### ISSUE THREAD

**Issue by harrijk** [hyperledger-archives/fabric#929]
I have observed some anomalies while attempting to incorporate a single non-validating peer node into a network with four validating peer nodes.

The non-validating peer's validator.enabled flag is set to false and security is enabled (all other security options are turned off).  The consensus module is first set to obcpbft and then noops.  The results are identical for both scenarios using either the obcpbft or noops consensus module.

The first scenario involves 4 validating nodes and 1 non-validating node.  Security is enabled, but all of other security options are disabled, e.g., TLS.  All 4 validating peers are started first.  As soon as I observed that all validating peers could see each other, I started up the non-validating peer.  The following messages were seen in the obc-peer logs for the root node and non-validating peer:

obc-peer log from the non-validating peer:
`23:02:31.689 [peer] SendMessage -> DEBU 036 Sending message to stream of type: DISC_HELLO`
<last message of the log>

obc-peer log from the root node:
`23:02:31.691 [peer] beforeHello -> DEBU 381 Received DISC_HELLO, parsing out Peer identification
23:02:31.691 [peer] beforeHello -> DEBU 382 Received DISC_HELLO from endpoint=peerEndpoint:<ID:<name:"non-validator01" > address:"192.168.40.233:30303" type:NON_VALIDATOR pkiID:"|\216\034\336T\033lP\206\201\013(\234\037\014j+\257\023H\331\214\202a\275\363\347\367\304\271\2774\302\244WN\370\311\023\2139D\\\255\243&Z\231" >
23:02:31.691 [peer] handleChat -> ERRO 383 Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error Verifying signature for received HelloMessage: Invalid signature. It is empty.`

The second scenario involves 4 validating nodes and 1 non-validating node.  Security is disabled for all nodes, both validating and non-validating.  All 4 validating peers are started first.  As soon as I observed that all validating peers could see each other, I started up the non-validating peer.  When security is disabled, the non-validating peer is able to insert itself into the peer network as seen in the log messages below:

Peers of the root node show that the non-validating peer is part of the network of peers:
`curl http://localhost:5000/network/peers
{"peers":[{"ID":{"name":"vp1"},"address":"192.168.81.118:30303","type":1},{"ID":{"name":"vp2"},"address":"192.168.81.116:30303","type":1},{"ID":{"name":"vp3"},"address":"192.168.81.117:30303","type":1},{"ID":{"name":"non-validator01"},"address":"0.0.0.0:30303","type":2}]}`

However, when security is disabled and a chaincode is deployed to one of the validating peers, the following errors occur in the obc-peer log of the non-validating peer.  The deployment of the chaincode to all validating peers occurred without error.

obc-peer log for non-validating peer:
`
22:46:24.178 [peer] handleChat -> ERRO 451 Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established
22:46:24.394 [peer] HandleMessage -> DEBU 452 Handling OpenchainMessage of type: CONSENSUS
22:46:24.394 [peer] handleChat -> ERRO 453 Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established
22:46:24.395 [peer] HandleMessage -> DEBU 454 Handling OpenchainMessage of type: CONSENSUS
22:46:24.395 [peer] handleChat -> ERRO 455 Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established
22:46:24.396 [peer] HandleMessage -> DEBU 456 Handling OpenchainMessage of type: CONSENSUS
22:46:24.396 [peer] handleChat -> ERRO 457 Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established
22:46:24.508 [peer] HandleMessage -> DEBU 458 Handling OpenchainMessage of type: CONSENSUS
22:46:24.508 [peer] handleChat -> ERRO 459 Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (13543359) while in state: established
22:46:24.577 [peer] HandleMessage -> DEBU 45a Handling OpenchainMessage of type: CONSENSUS
22:46:24.577 [peer] handleChat -> ERRO 45b Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (94) while in state: established
22:46:24.600 [peer] HandleMessage -> DEBU 45c Handling OpenchainMessage of type: CONSENSUS
22:46:24.600 [peer] handleChat -> ERRO 45d Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established
22:46:24.600 [peer] HandleMessage -> DEBU 45e Handling OpenchainMessage of type: CONSENSUS
22:46:24.600 [peer] handleChat -> ERRO 45f Error handling message: Peer FSM cannot handle message (CONSENSUS) with payload size (96) while in state: established`

Since the non-validating peer is not involved in consensus, it was strange to see the above messages in the non-validating peer's log.  Should we be concenred with these error messages?  Perhaps this is working as designed- I'm not sure, so I wanted to bring it to the community's attention.

**Comment by jeffgarratt** [comment]
Closed by #1220

**Comment by tonywang5671** [comment]
Hello Harrijk. I'm doing the test of 4 vp and 1 nvp network test on v0.6 but it not work. Would you please share yml for my reference? Many thanks
