### ISSUE TITLE
Panic occurs when exceeding the maximum validating peer count within the consensus config.yaml file

### ISSUE THREAD

**Issue by harrijk** [hyperledger-archives/fabric#932]
If you attempt to start an additional validating peer with censensus set to obcpbft and the total count of validating peers exceeds the value specified in the obcpbft consensus config.yaml file when you start this additional peer, you wil get a panic message when attempting to start the additional peer.
This should be checked to allow the peer to shutdown gracefully.

`06:44:24.791 [consensus/obcpbft] newPbftCore -> DEBU 022 Replica 4 assigning name:"vp0"  to index 0 for replicaCount 4 and id 4
06:44:24.791 [consensus/obcpbft] newPbftCore -> DEBU 023 Replica 4 assigning name:"vp1"  to index 1 for replicaCount 4 and id 4
06:44:24.791 [consensus/obcpbft] newPbftCore -> DEBU 024 Replica 4 assigning name:"vp2"  to index 2 for replicaCount 4 and id 4
06:44:24.791 [consensus/obcpbft] newPbftCore -> DEBU 025 Replica 4 assigning name:"vp3"  to index 3 for replicaCount 4 and id 4
panic: runtime error: index out of range
goroutine 7 [running]:
panic(0x807dc180, 0xc8200120b0)
        /opt/go/src/runtime/panic.go:500 +0x408
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.newPbftCore(0x4, 0xc82018c820, 0x3fffc2824e0, 0xc8202b0900, 0x3fffc282538, 0xc820223800, 0xc8202b8390)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/pbft-core.go:218 +0xff2
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.newObcClassic(0x4, 0xc82018c820, 0x3fffc282400, 0xc820223800, 0x100000000000007)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-classic.go:41 +0x16a
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.New(0x3fffc282400, 0xc820223800, 0x0, 0x0)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-pbft.go:58 +0x2dc
github.com/openblockchain/obc-peer/openchain/consensus/obcpbft.GetPlugin(0x3fffc282400, 0xc820223800, 0x0, 0x0)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/obcpbft/obc-pbft.go:45 +0x48
github.com/openblockchain/obc-peer/openchain/consensus/controller.NewConsenter(0x3fffc282400, 0xc820223800, 0x0, 0x0)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/controller/controller.go:42 +0xa2
github.com/openblockchain/obc-peer/openchain/consensus/helper.NewConsensusHandler(0x3fffc281888, 0xc820204750, 0x3fffc2820d8, 0xc82024c630, 0x100000000000002, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/consensus/helper/handler.go:65 +0x2a2
github.com/openblockchain/obc-peer/openchain/peer.(*PeerImpl).handleChat(0xc820204750, 0x3fffc281ba0, 0xc820012640, 0x3fffc2820d8, 0xc82024c630, 0x100000000000001, 0x0, 0x0)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:620 +0x26a
github.com/openblockchain/obc-peer/openchain/peer.(*PeerImpl).chatWithPeer(0xc820204750, 0xc82000e022, 0x14, 0x0, 0x0)
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:611 +0x91c
created by github.com/openblockchain/obc-peer/openchain/peer.NewPeerWithHandler
        /opt/obcwork/src/github.com/openblockchain/obc-peer/openchain/peer/peer.go:271 +0x798`

**Comment by genggjh** [comment]
@harrijk, I can not reproduce this issue in my environment. The log like following after I started a new VP.

2016-04-20T03:10:30.213763151Z 03:10:30.212 [consensus/obcpbft] newPbftCore -> INFO 012 PBFT Max number of validating peers (N) = 4
2016-04-20T03:10:30.213773343Z 03:10:30.212 [consensus/obcpbft] newPbftCore -> INFO 013 PBFT Max number of failing peers (f) = 1
2016-04-20T03:10:30.213780952Z 03:10:30.212 [consensus/obcpbft] newPbftCore -> INFO 014 PBFT byzantine flag = false
2016-04-20T03:10:30.213787911Z 03:10:30.212 [consensus/obcpbft] newPbftCore -> INFO 015 PBFT request timeout = 1m0s
2016-04-20T03:10:30.213818943Z 03:10:30.212 [consensus/obcpbft] newPbftCore -> INFO 016 PBFT view change timeout = 2s
2016-04-20T03:10:30.213873388Z 03:10:30.213 [consensus/obcpbft] newPbftCore -> INFO 017 PBFT Checkpoint period (K) = 10
2016-04-20T03:10:30.213888525Z 03:10:30.213 [consensus/obcpbft] newPbftCore -> INFO 018 PBFT Log multiplier = 2
2016-04-20T03:10:30.213899728Z 03:10:30.213 [consensus/obcpbft] newPbftCore -> INFO 019 PBFT log size (L) = 20
2016-04-20T03:10:36.979140413Z 03:10:36.978 [peer] handleChat -> ERRO 01a Error handling message: Peer FSM failed while handling message (DISC_HELLO): current state: created, error: transition canceled with error: Error registering Handler: Duplicate Handler error: {name:"vp1"  172.17.0.5:30303 VALIDATOR H
                                     �v~

Could you try it again with latest code?

**Comment by harrijk** [comment]
OK.  I will test with the latest code and post my findings.

**Comment by harrijk** [comment]
I have tested with the latest code and can confirm that the original issue (panic) does not occur.  
The document _/docs/dev-setup/devnet-setup.md_ (step 1 of **Using Consensus Plugin**) still mentions obcpbft as one of the options to use in the core.yaml file.  This should be changed to **pbft**.

**Comment by tuand27613** [comment]
thanks @harrijk  and @genggjh !

One more favor please ?  can one of you make the devnet-setup.md  update ? I have several branches in flight so can't do a "clean" pull request for a day or so.

**Comment by harrijk** [comment]
I just submitted a pull request for the devnet-setup.md update.

**Comment by corecode** [comment]
this should be closed

**Comment by christo4ferris** [comment]
agreed. Thanks @harrijk
