### ISSUE TITLE
Start of a validating peer node that was down during previous Ledger updates causes a panic

### ISSUE THREAD

**Issue by harrijk** [hyperledger-archives/fabric#933]
A panic occurs when you bring one of the validating peers back up after being shutdown, i.e., the process is stopped.  During the time that the validating peer was down, additional chaincode invoke functions were executed to update the ledger.  The panic occurs on all validating peer nodes at the same time.  The idea behind the test was to determine if the database of the offline peer could sync up with the other validating peers.  This issue can be easily recreated.

[out-of-memory.txt](https://github.com/openblockchain/obc-peer/files/199881/out-of-memory.txt)

**Comment by corecode** [comment]
Is this with pbft or noops?

**Comment by harrijk** [comment]
Sorry, I forgot to mention that obcpbft was used.

**Comment by corecode** [comment]
can you please provide the full log of all peers?

**Comment by tuand27613** [comment]
@RicHernandez2 , do you have a similar scenario ?

**Comment by RicHernandez2** [comment]
Not a panic, but the peers that were down won't come up with a query, not till I do a deploy

**Comment by harrijk** [comment]
I might have had one of the validating peers at a lower code level.  To be sure, I will rebuild all validating peers and retest.  I'll post my findings when complete.

**Comment by harrijk** [comment]
I have re-tested and collected logs for this issue.

Due to the large file size, please access the logs at:
https://ibm.box.com/s/ksvl98ohxxvlc9528ir43f9eyq5vzneo

I am running four validating peers: 2 running on Linux on z Systems and 2 running on x86 as KVM guests.  All obc-peer binaries have been compiled using the v0.1.0 source.  The obcpbft consensus module is being used for all 4 peers.  Security is enabled, but all other security options, e.g., transaction security and TLS, are disabled.

In the zip file that can be accessed from the link above, I've included a file called shell-command.log that includes a running history of the commands issued and comments, where applicable.

**Comment by corecode** [comment]
I can't access the box file, and nobody outside of IBM will be either :/

**Comment by harrijk** [comment]
@corecode try https://drive.google.com/open?id=0B_zkrFk74VRuVHVXRUtvZDRUcGM

**Comment by corecode** [comment]
It seems that you're running code from before March 4 - please try with current master.

**Comment by harrijk** [comment]
Will do.

**Comment by harrijk** [comment]
@corecode ... Just curious... You said that you could not download the file from ibm.box.com...  you will get a screen that says "we're sorry but you can't preview zip files", but you should be able to download the file just fine.  I just had someone that was not on the IBM network confirm this.

**Comment by harrijk** [comment]
I have re-tested with the latest code and I am now experiencing similar symptoms as issue #925.  Four peers are started with security enabled and pbft classic mode consensus is used. 

Chaincode is deployed to all four peers, a transaction is invoked and all four peers have the same block height and block hash.  When a single peer is shutdown, another chaincode transaction is invoked.  The single peer that was shutdown is then started up and the state of the peer that was down never did not sync up with the other peers state.

An additional chaincode invoke transaction was performed.  The transaction only ran on the three peers that were up during the test.  As for the peer that was started back up, the invoke transaction never ran and the its state did not change.

Logs:
[sync-issue.zip](https://github.com/hyperledger/fabric/files/204292/sync-issue.zip)

I tried increasing some of the timeout values in consensus/obcpft/config.yaml, but this did not resolve the issue.

Contents of config.yaml
[config-yaml.txt](https://github.com/hyperledger/fabric/files/204296/config-yaml.txt)

**Comment by corecode** [comment]
After restarting the peer, can you shut down another peer, and see whether the newly started peer catches up?  You cannot expect a newly restarted peer to catch within a defined period.

**Comment by harrijk** [comment]
@corecode, I went ahead and performed the test that you suggested.  I had 5 validating peers in my network; 3 Linux on z Systems and 2 x86.  Security was enabled and the pbft consensus module was used.  I ran a deploy transaction (example02) followed by 4 invoke transactions on the example02 chaincode.  The chain height and state hash codes all matched.

Next, I brought down a Linux on z Systems peer and then performed an additional invoke transaction on the example02 chaincode.  The remaining 4 peers chain height and hash states were identical.  I then restarted the Linux on z Systems peer that was down.  Approximately, 2 minutes later I shutdown one of the x86 peers.

I waited for 60 minutes and after that time the peer that was down and started back up still had not synched it's ledger/state with the other peers that were up at the time.

One other note... I also changed the statetransfer timeouts in core.yaml to:

```
timeout:
        # How long may returning a single block take
        singleblock: 120s
        # How long may returning a single state delta take
        singlestatedelta: 180s
        # How long may transferring the complete state take
        fullstate: 240s
```

The increase in the timeout values still did not resolve this issue.

Hope this helps.

**Comment by corecode** [comment]
You still cannot expect that peer to catch up.  You will have to inject transactions to trigger state transfer.

**Comment by harrijk** [comment]
@corecode, thanks for the information.  As the peer is still somewhat of a "black box" to me, it's always good to pick up tips on how some of the internals operate.

OK, so I went a head and performed "invoke" transactions at a rate of 1 per second after the downed peer started back up.  

**Observations:**
1. The chain height of the peers (including the peer that was restarted) before injecting "invoke" transactions was approximately 10.
2. The chain of the peer that was down finally synced when the chain height of the peers that stayed up reached 61.
3. At this point the chain height of the peer that was restarted remained at 61 until the chain height of the other peers reached 71, at which point the chain height of the peer that was restarted synced to 71.
4. As "invoke" transactions continued to be injected into the peer network, the chain height of the peer that was restarted remained at 71 while the other peer chain heights grew in sync with each other.
5. Once the chain heights of the peers (that were not restarted) approached 1,000, I decided to restart the peer that was initially targeted for restart.  After performing the restart, the peer did eventually sync up, but once again the chain height stopped increasing while the other peers continued to perform "invoke" transactions with updates to their respective blockchain databases.
6.  I performed step 5 once again, and after a period of time, the restarted peer synced up with the other peers in the network and continued to be in sync with the other peers in the network.  In some cases I had to restart the targeted peer two or three times before it got back in sync (and stayed in sync) with the other peers.
7. The above set of steps is somewhat repeatable (random number of peer restarts for successful sync) including the initial "freeze" of the restarted peer's chain heights of 61 and 71.  I should also note that when I mention "chain height" I am also checking the current and previous block hashes.

Is there something that I should be doing in my testing to eliminate the multiple peer restarts in order to get it to sync and execute "invoke" transactions and remain a participating peer in the network? 

If I am not doing anything incorrectly, is this behavior a bug?

Thanks.

**Comment by corecode** [comment]
Thanks for the great description.  I think what you're seeing is normal PBFT behavior:  2f+1 replicas are making progress, and f replicas are lagging slightly behind, and catch up occasionally.

If you shut down another peer, you should observe that the one you originally shut off and restarted will now participate fully, and the network will continue to make progress.

As long as the network is making progress, and the participating nodes share a correct prefix, you're all good.

The reason for f replicas lagging behind is that those f may be acting byzantine and progress deliberately slowly.  You cannot tell a difference between a slower correct replica, and a deliberately slower byzantine replica.  Therefore we cannot wait for the last f stragglers.  They will be left behind and sync up occasionally.  If it turns out that some other replica is crashed, the network will stop making progress until one correct straggler catches up, and then the network will progress normally.

**Comment by harrijk** [comment]
Good stuff.  Thanks for the explanation.

Cheers.

**Comment by bmos299** [comment]
@corecode @harrijk 

The statement the step that makes me wonder is:
6.  I performed step 5 once again, and after a period of time, the restarted peer synced up with the other peers in the network and continued to be in sync with the other peers in the network. In some cases I had to restart the targeted peer two or three times before it got back in sync (and stayed in sync) with the other peers.

Why would it be necessary to restart a targeted peer two or three times to get back in sync?

**Comment by corecode** [comment]
If indeed you need to restart the peer, that's a problem.  The peer should catch up at some point as the network is progressing.  Certainly it should catch up when the peer is required for the network to make progress.

**Comment by harrijk** [comment]
@bmos299 @corecode ... I'll perform the tests again... it's possible that I might not have given the peer that was down more time to eventually catch up.  I'll keep you posted.

**Comment by corecode** [comment]
you will have to force it to catch up by switching off another peer. at any point there are only 2f+1 out of 3f+1 replicas guaranteed to make progress.

**Comment by ijmitch** [comment]
@corecode ... are you saying that it doesn't even try to keep _all_ peers up to date?

**Comment by harrijk** [comment]
@corecode  OK.  I will switch off another peer.  I am currently running the test and the peer that was down is still slightly lagging behind (as you indicated in your earlier posts).  I've been injecting 1 invoke transaction per second for about 30 minutes now and the "lagger" is always about 50 to 60 blocks behind.

I'll turn off another peer and see if the original downed peer catches up.  I'll then bring up the second peer that I brought down and see if that one catches up.

**Comment by corecode** [comment]
@ijmitch the peers try to stay up to date, but especially at high transaction rates some will always be behind.

**Comment by harrijk** [comment]
@corecode  When I stopped a second peer, the first peer that was stopped and subsequently brought back up, eventually caught up with the 3 peers that were in sync with each other.  When I started the second peer, which was stopped to allow the first downed peer to catch up, the second peer exhibited the same behavior as the first peer that was stopped and started, i.e., lags slightly behind.  

I understand that this behavior is to be expected per your comments above. 

Thinking ahead... in a production setting where you are in a network of peers -- let's say banks --, and your company's peer goes down and is then restarted, there is no guarantee that their peer's state will catch up anytime soon... If they are tapping into their peer for purposes of (for example) updating their SOR due to events that have occurred in the blockchain, and their peer has not synced up with the other peers in the network, what mechanism(s) is/are there to ensure that they are accessing a real time state of the blockchain?  One thing that comes to mind for me is perhaps some sort of HA setup where there would be more than one participating peer within a company's IT environment and they have access to at least one "good" peer.  .... Just thinking out loud....

Moving ahead, I will run a scenario of injecting 1 invoke transaction every 10 seconds (assuming this is not considered a high transaction rate) and see if a peer that was restarted catches up without the need for bring down a different peer within the network. 

At this point... PBFT is "magic" to me... perhaps some day I'll get a grasp on these concepts. :-)

Cheers.

**Comment by corecode** [comment]
Either all replicas are guaranteed to be in sync, or we can tolerate network outage and byzantine nodes.  We can't have both.  We can try to minimize how much nodes are (possibly) lagging behind, but we cannot eliminate that lag.  It would be good if you could formulate a requirement of how much any node may be lagged behind, so that this can be incorporated into a design specification.

**Comment by harrijk** [comment]
Understand... Fair enough.

**Comment by morehendrix** [comment]
I can understand that the network must make progress as soon as there is agreement among 2f+1 nodes, and therefore, there is no guarantee of sync. But, in spite of this, I would expect that peers behaving normally (also non-validating peers) do their best to synchronize with the network. However, this is not the case in the experiments I made, and from what I see in the scenarios described here, I am not alone here.

**Comment by muralisrini** [comment]
@harrijk @corecode apologize for jumping in the middle, but was curious about certain observations...
- what are the commands used for stopping and restarting a peer ?
- as I understand it, when you send an invoke transaction **after** the restarted syncs up, the transaction does not succeed on the started peer. If I understood that correctly do you have logs on the peer for that  ?

**Comment by harrijk** [comment]
@muralisrini ... To start the peer, I am using a shell script that contains the following:

```
export LD_LIBRARY_PATH=/opt/rocksdb
cd /opt/obcwork/src/github.com/hyperledger/fabric/peer
./peer node start --logging-level=debug > /var/log/obc-peer.log 2>&1 &
```

To stop the peer, I issue the command `peer node stop` from the hyperledger/fabric/peer directory.

From my observations (and knowing me, they could be faulty :-) ), the chaincode container that was running when the `peer node stop` command was issued is also stopped.  When you start the peer that was down, the chaincode container is never started until the peer "syncs" up with the other peers, at which point succeeding "invoke" transactions do run successfully.  When that same peer starts to lag behind again and is out of sync, "invoke" transactions no longer run (chaincode container is stopped) until it syncs up again.

The lagging effect of the restarted peer is an effect of the PBFT design as @corecode mentioned earlier.

**Comment by bmos299** [comment]
@corecode is there any thought to a 'guaranteed query'.  For example, if I am querying a peer that is behind, and I use its local ledger, how can I every bet my business on the accuracy?  It totally makes sense for general query, however, have we thought about a query that is actually a transaction on the blockchain to guarantee it gets the latest value?

**Comment by corecode** [comment]
There is no concept of latest value.  Imagine you send a query, and right after that an invoke takes place.  When you get the answer for the query, the value has already changed.

**Comment by bmos299** [comment]
@corecode, good point.  I think of the scenario where I need a real time piece of data like a stock price which will trigger my decision to buy/sell.  Different peers providing different values at the same point in time seems like it could be a concern.

**Comment by corecode** [comment]
There is no "same point in time", except for (accepted) historical data.  And this is not just an implementation detail, but based on physics: even with a central server (say, in NYC), if you query it "at the same time", from LA and from Sydney, the server will receive the answers at different times; or conversely, if the server receives the queries at the same time, the answers will not arrive "at the same time".

If you want to implement a buy/sell stock chaincode, you would probably include a price you want to buy/sell at, or a range.  The chaincode then can check whether these conditions are valid, and execute your order or discard it.

**Comment by jimthematrix** [comment]
Thanks for the information provided by @corecode . may I ask 2 follow-up questions:
1. when performing queries, I believe the REST API is targeting a particular peer (to my best understanding), what happens if that peer has crashed before and is lagging behind? Is there a way to have the network answer the query with the answer formed by the consensus?
2. when listening to events, the event listener is also attached to a particular peer (TMBU), can event listeners be attached to a quorum representing the network instead? for instance in Apache Kafka a message consumer can be configured to listen on a "leader" dynamically elected by a zookeeper quorum

**Comment by jimthematrix** [comment]
@muralisrini we discussed bullet 2 above a bit, would like to hear your input as well...

**Comment by corecode** [comment]
There is no provision for strong reads yet (query the whole network).

**Comment by bmos299** [comment]
@harrijk is the original issue resolved?  There are many side discussions in this issue.  I think we are better off opening new issues for some of the conversations.

**Comment by harrijk** [comment]
@bmos299, yes, the original panic issue was resolved a while ago.  As the subsequent discussions within this issue have taken on a life of their own in other side discussions, it's fair to close this issue.

**Comment by christo4ferris** [comment]
as they say: "take it outside" ;-) please continue any discussion on the mailing list. closing.
