### ISSUE TITLE
Add HTTP tests for the REST API

### ISSUE THREAD

**Issue by srderson** [hyperledger-archives/fabric#95]
We need to test the http functionality of the REST API. For example, making sure that 200 and 400 response codes are returned when expected.

**Comment by angrbrd** [comment]
Discussed with Jeff today. We will move this issue out, prioritizing the demo work instead. We will return to this in the next several days and make a decision on how to properly implement these tests against the test network. Moving out to milestone 4.

Tnx.

**Comment by binhn** [comment]
Move to sprint4 since it requires the testnet

**Comment by binhn** [comment]
move to testing cycle period

**Comment by angrbrd** [comment]
I just spoke to @jeffgarratt. He is using all of the REST endpoints in the behave tests at this time. This issue is no longer necessary. As new tests are created, I will be adding the required REST endpoints for that as well, as we presume to use the REST APIs for all behave tests going forward.
