### ISSUE TITLE
Fix up core

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#955]
fabric/core should only contain main.go core.yaml and other folders for sub components

**Comment by muralisrini** [comment]
@binhn : should we make homes for each of the go files under "fabric/core" (e.g., devops.go goes into fabric/devops). 

Also should we move fabric/main.go into fabric/peer/main.go ?

Or... do we leave things as they are and close.

**Comment by binhn** [comment]
@srderson will create a different issue to move main into peer, so  I am closing this issue
