### ISSUE TITLE
Move UTXO code into fabric

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#959]
The code for UTXO support is still in some public repos. We need to consolidate and move it into the fabric repo

**Comment by srderson** [comment]
@rfajta - could you work with @noamher to help move your commits from https://github.com/hyperledger-incubator/obc-peer/commits/master. This will allow me to test your API with the hyperledger fabric repo.

**Comment by noamher** [comment]
I've started working on it. I cherry-picked all the necessary commits but I can't seem to build the dev-... docker image.
@srderson how can I get a hold of you to figure this out?

**Comment by srderson** [comment]
Is this the dev-... in the UTXO [README](https://github.com/hyperledger/fabric/blob/master/examples/chaincode/go/utxo/README.md)? I'm going to give it a try today to see if anything broke after all the changes associated with moving to the new repository. Is there a specific error you are seeing?

**Comment by srderson** [comment]
@noamher See https://github.com/hyperledger/fabric/pull/1053. I was able to deploy the UTXO chaincode with these changes.

**Comment by christo4ferris** [comment]
@binhn @srderson @tamasblummer closing this as I believe the intention is satisfied by the integration of systemcc etc. please reopen if you disagree.
