### ISSUE TITLE
Dead links in fabric readme: https://github.com/hyperledger/fabric/blob/master/README.md

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#985]
1) Writing Chaincode

... Follow the instructions on the Sandbox Setup page, which allows you to run your chaincode off the blockchain. <== sandbox set up points to https://github.com/hyperledger/fabric/blob/master/docs/api/SandboxSetup.md which produces error 404

2) Working with CLI, REST, and Node.js

When you are ready to start interacting with the peer node through the available APIs and packages, follow the instructions on the API Documentation page.  << API Documentation page points to https://github.com/hyperledger/fabric/blob/master/docs/api/CoreAPI.md  which produces error 404.

**Comment by nickgaski** [comment]
links work now

**Comment by gregmisiorek** [comment]
links are not working for me, 404 is still there.

**Comment by joshhus** [comment]
The disconnect on this issue might be that the title references the README file, but the cited problems are in files in /API ... /dev-setup also has some issues, I'm looking at these now.

**Comment by joshhus** [comment]
Also finding a number of references to "OPENCHAIN_" and obc-peer, various .yaml files that appear to have been renamed. So potentially more to do than just correcting the links.

**Comment by joshhus** [comment]
The problem with some of the /API links appears to be the old directory was /api and the new one is /API -- so links that haven't been updated with capital /API are not found. I'd like to check with the dev. on which change they'd like to make - directory name or links.

**Comment by joshhus** [comment]
Anya confirms /API - so all links with /api need to be changed to /API. An example of where link URLs defined in one place, as single common entities, would really help; GitHub doesn't support this, to my knowledge.

**Comment by christo4ferris** [comment]
docs have been refactored. closing this for now as no longer relevant,
