### ISSUE TITLE
wrong  clone instruction in readme

### ISSUE THREAD

**Issue by mukosolu** [hyperledger-archives/fabric#998]
it should read
git clone https://github.com/hyperledger/fabric.git instead of https://github.com/< username >/fabric.git

and why does the preamble talk about forking and cloning into the right place since we are only pulling down a local copy?

**Comment by binhn** [comment]
@mukosolu This instruction is to set up the dev environment -- see the title, so we require developers to work of their own forks, not directly on upstream.
